### ISSUE TITLE
Include current request method when options.retry is set to a number

### ISSUE THREAD

**Issue by broom9** [sindresorhus/got#1002]
#### What problem are you trying to solve?

I tried to configure retry on a POST request and found it didn't retry as expected:
```
 got.post(
        `https://sample-server/api-path`,
        {
          json: { a: 1 },
          retry: 2,
        },
      );
```

After reading the docs a few times I looked into the codes and figured out when `options.retry` is set to a number, it only affects `options.retry.limit`. But if the current request's method is POST. It still doesn't retry. I configured it as below and it seems working.
```
 got.post(
        `https://sample-server/api-path`,
        {
          json: { a: 1 },
          retry: {
            limit: 2,
            methods: ['POST'],
          },
        },
      );
```
...

#### Describe the feature

I suggest if the `options.retry` is set to a number, the intention is clear that the current call should be retried. In this case, the current call's http method should be added to the `options.retry.methods` automatically.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
There's a good reason `POST` is not in the default list of methods to retry. It's not idempotent, and it could cause problems to retry `POST` as you might end up, for example, creating duplicate entries of some data.

We're not going to change the behavior as the current one is the best default, but I think we could document why `POST` is not in the list of defaults methods, so people know the risk of manually adding it there.

**Comment by broom9** [comment]
Hi @sindresorhus ,

Yes. 100% agree POST should not be in the default methods. But if the `retry` option is specifically configured for one single POST request, not the whole got client, then I think it's reasonable to say the intention is clearly to make this one request retry, and it was a surprise POST method needs to be added as an additional config.

**Comment by sindresorhus** [comment]
Even if we were talking about an non-idempotent method like `PUT`, we wouldn't want that kind implicit magic behavior in Got. And we especially don't want it for `POST` for reasons outlined earlier. Let's say we did add this, that would mean that most users, who don't want to retry on `POST`, could not use `{retry: 3}` as it would cause retry on `POST`. You're asking us to simplify a use-case, that in most cases, is wrong. I think it's better for you with the edge-case to have to add some config than everyone else. Also, keep in mind that Got config can be extended, so behavior between direct config and inherited config would be different.

**Comment by broom9** [comment]
OK, that's fair.

Whether to include implicit magic behavior is a more philosophical choice.

Whether to distinguish behavior of a default config and a single-request config is a design choice. If the whole design is to make them consistent. Then I agree we should require edge cases to have specific configurations.
