### ISSUE TITLE
Please provide Formdata syntax and example for got 9.6.0

### ISSUE THREAD

**Issue by krishna01012002** [sindresorhus/got#1005]
Using old Got 9.6.0 , now we can not upgrade to new Got.
Please help me to pass formdata with Got 9.6.0
Formdata example for got 9.6.0

Document is not available for Got 9.6.0

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got#form-data

**Comment by sindresorhus** [comment]
Documentation is available for each version: https://github.com/sindresorhus/got/tree/v9.6.0#form-data
