### ISSUE TITLE
How to not follow redirects but log redirect URL?

### ISSUE THREAD

**Issue by carbotaniuman** [sindresorhus/got#1006]
#### What would you like to discuss?
Title. Setting `{followRedirects: false}` ignores all redirects altogether, and I cannot find the URL.

#### Checklist

- [x ] I have read the documentation.

**Comment by szmarczak** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

**Comment by szmarczak** [comment]
This is not a Got-related issue.

**Comment by szmarczak** [comment]
Got is just a wrapper around the native `http` module.
