### ISSUE TITLE
tunnel compatability for proxying broken in Version 10

### ISSUE THREAD

**Issue by rpappa** [sindresorhus/got#1009]
#### Describe the bug

 - Node.js version: Tested in 10.11.0 and 13.5.0
 - OS & version: Windows 10 1903

Proxying requests via the `tunnel` module as reccomended in the readme fail using got 10.

#### Actual behavior

An error is thrown:
```
tunnel.js:208    var hostHeader = options.request.getHeader('host');
                                     ^
TypeError: options.request.getHeader is not a function    at ...\node_modules\tunnel\lib\tunnel.js:208:38    at ClientRequest.onConnect (...\node_modules\tunnel\lib\tunnel.js:172:12)
```

I recognize that the error is thrown within `tunnel` code and not `got`, but as the README reccomends to use tunnel with example code provided, I think this behavior is worth opening an issue about.

#### Expected behavior

No error is thrown, as occurs using got 9.6.0

#### Code to reproduce
Replace the proxy options with a working proxy (I have tested using both Charles proxy and live proxies)

```
const got = require('got');
const tunnel = require('tunnel');
 
got('https://sindresorhus.com', {
    agent: tunnel.httpsOverHttp({
        proxy: {
            host: 'localhost',
            port: "8888"
        }
    })
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by malsatin** [comment]
I have the same issue.

Temporary solution that I have created for myself

```js
let https = require('https');
gotOptions.request = https.request;
gotOptions.hooks = {
    beforeRequest: [
        options => {
            options.request.getHeader = (name) => options.headers[name] || null;;
        }
    ]
};
```

**Comment by tobiasmuehl** [comment]
Also have problems with this code

```ts
got('https://v4.icanhazip.com/', {
  agent: tunnel.httpsOverHttp({ proxy: { ... }),
  timeout: 5000
})
```

**Comment by Sollunad** [comment]
Is there any ETA for the release of this fix?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/releases/tag/v10.2.2

**Comment by ash0080** [comment]
test several packages, this's the only work one 
https://github.com/zjael/simple-proxy-agent

**Comment by ash0080** [comment]
@szmarczak 
I noticed that when accessing https using above one, 
most time it doesn't work, just hang up, I think maybe its because got distinguish http/https strictly, but anyway, the protocol of 'Agent' is not so clear.

For comparison purposes,  I tried needle, it works well.

**Comment by malsatin** [comment]
> https-proxy-agent



> test several packages,
> tunnel, https-proxy-agent, proxy-agent and so on...
> 
> this's the only work one
> https://github.com/zjael/simple-proxy-agent

https-proxy-agent works fine for me

**Comment by ash0080** [comment]
> > test several packages,
> > tunnel, https-proxy-agent, proxy-agent and so on...
> > this's the only work one
> > https://github.com/zjael/simple-proxy-agent
> 
> https-proxy-agent works fine for me

Not work for me as described above, 
weird 503 error, 
maybe because I am not using a REAL https proxy?
