### ISSUE TITLE
Questions about creating plugins

### ISSUE THREAD

**Issue by mastermatt** [sindresorhus/got#1010]
#### What would you like to discuss?

I have a couple of questions that flow together.
1. Should plugin authors use `create` or `extend`?
  The [docs/example](https://github.com/sindresorhus/got/blob/master/documentation/lets-make-a-plugin.md) using `gh-got` make use of `extend`. However, the [real `gh-got`](https://github.com/sindresorhus/gh-got/blob/master/index.js) uses `create` and extends the options manually and copies the methods.
  Since `create` is no longer a documented method, I assume the preference going forward is to use `extend` and `gh-got` has simply not been updated to use v10.0 yet.

1. Are plugin authors expected to add top level keys to the options object when appropriate, or is there another mechanism? 
  I ask this because the options are normalized, and while extra keys are currently passed through, I don't want to rely on this feature unless it's intended and not likely to change in the future. 

1. If the answer to the last question is **yes**: Would a PR be welcome that would change the `ExtendOptions` type interface into a globally extendable interface so plugin authors could include their options? 
  Something similar to how [Express is setup](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts#L16-L24) to allow declaration merging. 
#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> Since create is no longer a documented method, I assume the preference going forward is to use extend and gh-got has simply not been updated to use v10.0 yet.

Not that it's not documented, it has been completely removed.

> Are plugin authors expected to add top level keys to the options object when appropriate, or is there another mechanism?

Yes

> Would a PR be welcome that would change the ExtendOptions type interface into a globally extendable interface so plugin authors could include their options?

Sure, any PR is welcome :)

**Comment by mastermatt** [comment]
Thanks.

I have a WIP on the type changes, but I want to flush them out a bit on some projects I have before I open a PR.
