### ISSUE TITLE
Cancel request before actual request

### ISSUE THREAD

**Issue by Couto** [sindresorhus/got#1012]
#### What would you like to discuss?
I wasn't able to find this on the docs, nor can I find a way using the hooks features. I might be missing something.

I would like to cancel a request before it leaves my machine.

Example (this is not working, it might just better illustrate what I want to do):

```ts
import got, {
  BeforeRequestHook,
  AfterResponseHook,
  BeforeErrorHook,
  Response,
} from "got";

export default <R>(response: Response<R>) => {
  const beforeRequest: BeforeRequestHook = () => {
    throw new Error("Canceled");
  };

  const afterRequest: AfterResponseHook = () => {
    return response;
  };

  const beforeError: BeforeErrorHook = _err => {
    return response;
  };

  return got.extend({
    hooks: {
      beforeRequest: [beforeRequest],
      afterResponse: [afterRequest],
      beforeError: [beforeError],
    },
  });
};
```

My idea is to provide some predefined responses in some specific situations.
Any idea on how to do this?

Thanks

PS: My objective is to mock requests so it would be ideal to return the instance itself instead of using `.cancel()`

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> Example (this is not working, it might just better illustrate what I want to do):

Actually this works. Throwing in a hook cancels the request.

> My idea is to provide some predefined responses in some specific situations.

You can use `afterResponse` hook to modify the response. To provide predefined responses, you may want to set custom `request` option.

**Comment by Couto** [comment]
> Actually this works. Throwing in a hook cancels the request.
It does in practice, but it will call the `beforeError` which only allows me to return an Error. So I have to `.catch` requests instead of just using a simple `.then`.

So with the goal of mocking requests, not so much.

I totally missed the `request` options, yeah that could actually work, will take a look. 

Thank you!

**Comment by szmarczak** [comment]
@sindresorhus Should it be possible to return a response from a `beforeError` hook?

**Comment by sindresorhus** [comment]
@szmarczak Wouldn't it be better to allow returning a new different request from `beforeRequest`?

**Comment by szmarczak** [comment]
@sindresorhus You can already modify options in a `beforeRequest` hook. Alternatively you can pass custom `request` function.

Or we can allow returning `IncomingMessage` directly from the `request` function. That would be very useful e.g. when using cache (the `request` function would be async so `await` is needed). That way people could do something like this:


```js
const request = (url, options) => new Promise((resolve, reject) =  {
    const request = http.request(url, options);
    request.once('error', () => {
        resolve(createIncomingMessage());
    });

    request.once('socket', () => resolve(request));
});

await got(url, {request});
```

**Comment by sindresorhus** [comment]
> You can already modify options in a beforeRequest hook. Alternatively you can pass custom request function.

I'm not sure how modifying options helps with canceling the request? But another use-case for being able to return `IncomingMessage` in `beforeRequest` is if you already have it cached yourself, or for prototyping when you have a static response.

> Or we can allow returning IncomingMessage directly from the request function.

I wouldn't really find that useful as I don't want to override `request` and implement all the low-level request details myself.

**Comment by szmarczak** [comment]
> But another use-case for being able to return IncomingMessage in beforeRequest is if you already have it cached yourself, or for prototyping when you have a static response.

#1051 allows to return an IncomingMessage (ResponseLike) instance using the `request` option. It's to make the HTTP-based caching mechanism easier to code. ([I've already wrapped `cacheable-request`](https://github.com/szmarczak/got/blob/a01e6e73e84a977063df24e8c886a22f22de8436/source/core/index.ts#L192-L213))

I'll make `beforeRequest` accept `IncomingMessage`s too.

**Comment by sindresorhus** [comment]
Great 👌
