### ISSUE TITLE
Status code is undefined

### ISSUE THREAD

**Issue by Mintonne** [sindresorhus/got#1013]
#### Describe the bug

 - Node.js version: 12.14.0
 - OS & version: Win10

#### Actual behavior

The status code is `undefined`

#### Expected behavior

Code should return 404

#### Code to reproduce

```js
const got = require('got');

got('https://api.github.com/some-endpoint', {
  hooks: {
    beforeError: [
      error => {
        const { response } = error
        if (response && response.body) {
          error.message = response.body.message
          error.code = error.statusCode
        }

        return error
      }
    ]
  }
})
  .catch(error => {
    console.error(error.code)
  })
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
There is no such `error.code` example in the docs. Please read it again. It's `error.response.statusCode`.

**Comment by HayDegha0917** [comment]
Per your doc page, there should be: https://github.com/sindresorhus/got/blob/HEAD/documentation/8-errors.md

**Comment by szmarczak** [comment]
@HayDegha0917 Those docs didn't exist back then. If you found a bug, please open a new issue.
