### ISSUE TITLE
The `merge` function is slow

### ISSUE THREAD

**Issue by cesarfd** [sindresorhus/got#1016]
#### What would you like to discuss?

Hi, we are using got heavily in my company to send several thousand requests/s so I'm doing some profiling to see in which places our app spends its time the most.

I've recently upgraded to Got 10 and I've seen that the library spends a significant (though, not alarming) percentage of the time in the normalize arguments phase, which at the same time calls the aforementioned merge function.

<img width="723" alt="Captura de pantalla 2020-01-08 a las 15 50 59" src="https://user-images.githubusercontent.com/10957618/71987541-b41e7200-322e-11ea-8226-80f130c2c9a5.png">

It looks like this single `slice` call to clone the array seems to spend quite a lot of time. So, my question is, do we really need to clone the array or could it be just referenced? If we need a copy, is `slice()` the fastest method? 

I tried https://jsperf.com/cloning-arrays/3 in Chrome 79 and it seems that there're faster (not so much tbh) alternatives.

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/72006866-cf9a7480-3250-11ea-9b3e-7b5b5accb98d.png)

Ran on i7-7700k Intel CPU.

**Comment by szmarczak** [comment]
> Hi, we are using got heavily in my company to send several thousand requests/s so I'm doing some profiling to see in which places our app spends its time the most.

Are there any other heavy places like `merge.ts`? This is very interesting work.

**Comment by cesarfd** [comment]
> ![image](https://user-images.githubusercontent.com/36894700/72006866-cf9a7480-3250-11ea-9b3e-7b5b5accb98d.png)
> 
> Ran on i7-7700k Intel CPU.

<img width="979" alt="Captura de pantalla 2020-01-08 a las 20 30 49" src="https://user-images.githubusercontent.com/10957618/72009342-fdce8300-3255-11ea-8a6d-dc7675240bf0.png">

On Intel i7-5557U

Weird.

**Comment by yovanoc** [comment]
I don't know if it will help but on my 2.3 GHz 8-Core Intel Core i9
![image](https://user-images.githubusercontent.com/7302317/72011201-9f0b0880-3259-11ea-9ceb-041bbd0ff1b5.png)

**Comment by cesarfd** [comment]
> > Hi, we are using got heavily in my company to send several thousand requests/s so I'm doing some profiling to see in which places our app spends its time the most.
> 
> Are there any other heavy places like `merge.ts`? This is very interesting work.

Here's a more detailed tree where we can see what the code does when we invoke got:

<img width="1120" alt="got normalize options" src="https://user-images.githubusercontent.com/10957618/72010799-d5945380-3258-11ea-84dd-cf996c7725ae.png">

This comes from a 70 second profiling. There are more places where we call got with a different option object each time as we are performing POST json requests.

It seems the `normalizeArguments` section (and the whole merging process) is the only place where got spends a noticeable amount of time, at least with our use case.

**Comment by szmarczak** [comment]
@sindresorhus You need to see this:

![image](https://user-images.githubusercontent.com/36894700/72096316-4780a180-331a-11ea-9d6c-1bd0891fb83f.png)

**Comment by sindresorhus** [comment]
@szmarczak Micro-benchmarks are pretty useless without context. If you run Got seven million times in real-world situations, the network is going to be the bottleneck, not a simple loop.

**Comment by sindresorhus** [comment]
@cesarfd What Node.js version and OS?

**Comment by szmarczak** [comment]
> Micro-benchmarks are pretty useless without context. If you run Got seven million times in real-world situations, the network is going to be the bottleneck, not a simple loop.

I think it depends if you're running a very very very low-spec machine / VPS and make thousands of requests...

**Comment by szmarczak** [comment]
@sindresorhus Also shouldn't we deep clone arrays too? For example you can do:

```js
got.extend({hooks: {beforeRequest}});
beforeRequest.push(fn);
```

and the instance will be affected.

**Comment by szmarczak** [comment]
@cesarfd Could you also provide performance profiling for `normalize-arguments.js`?

**Comment by cesarfd** [comment]
> 
> 
> @cesarfd What Node.js version and OS?

Node 12.13.1 under a [buster-slim](https://hub.docker.com/_/node) docker image + Linux AMI

**Comment by cesarfd** [comment]
> 
> 
> @cesarfd Could you also provide performance profiling for `normalize-arguments.js`?

Yes, I'll rerun the profiler on Monday.

**Comment by szmarczak** [comment]
Relevant dockerfile: https://github.com/nodejs/docker-node/blob/cd046b99024274af8a782bc7fb722a89f65ecfdc/12/buster-slim/Dockerfile

**Comment by cesarfd** [comment]
@szmarczak `normalize-arguments.js`:

<img width="884" alt="Captura de pantalla 2020-01-13 a las 9 19 59" src="https://user-images.githubusercontent.com/10957618/72241047-14723280-35e6-11ea-9259-b28408c8b93e.png">
<img width="846" alt="Captura de pantalla 2020-01-13 a las 9 20 22" src="https://user-images.githubusercontent.com/10957618/72241064-1d630400-35e6-11ea-8b41-366b8bfd27e0.png">

**Comment by szmarczak** [comment]
Thank you very much, if you provide also profiling for `mergeOptions` and `normalizeArguments` (it's in the `normalize-arguments.js` file) that will be great! I've got a few ideas on how to improve the performance.

**Comment by sindresorhus** [comment]
> I think it depends if you're running a very very very low-spec machine / VPS and make thousands of requests...

Sure. My point was that standalone micro-benchmarks doesn't mean anything without the context. It's better to profile the actual running code on the actual system.

**Comment by sindresorhus** [comment]
> Also shouldn't we deep clone arrays too? For example you can do:

Yes

**Comment by cesarfd** [comment]
> Thank you very much, if you provide also profiling for `mergeOptions` and `normalizeArguments` (it's in the `normalize-arguments.js` file) that will be great! I've got a few ideas on how to improve the performance.

Wops, I pasted the pre normalize function before, sorry.

`mergeOptions`:
<img width="614" alt="Captura de pantalla 2020-01-13 a las 11 17 21" src="https://user-images.githubusercontent.com/10957618/72247983-602cd800-35f6-11ea-8ab9-aeb544b94759.png">

`normalizeArguments`:
<img width="968" alt="Captura de pantalla 2020-01-13 a las 11 17 42" src="https://user-images.githubusercontent.com/10957618/72248003-67ec7c80-35f6-11ea-864a-8e96872da5d4.png">

**Comment by Jolg42** [comment]
I also noticed that got can be "relatively slow" to create an instance, If you have any improvements I'm interested to try them :)

In my case the request is done on localhost so the network is fast.

**Comment by szmarczak** [comment]
@cesarfd What tool do you use to display the performance timings? Could you tell me how to enable it please? That'd be very useful.

**Comment by cesarfd** [comment]
@szmarczak It's all in the chrome inspect tool. basically the procedure is as follows:

- Start a node process with the `--inspect` flag or  send a `kill -USR1 <node pid>`. This will enable the debug mode on the process, by default it listens to port 9229.
- Fire up a `chrome://inspect`, this will show you an available remote target in localhost, just click it and it will show the tools, including a drop down menu for the flame graph.

https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by szmarczak** [comment]
@cesarfd I already know that, I thought you were running a fork of Chrome Dev Tools because I can't find anywhere the option to enable the timings in the Source tab...

**Comment by szmarczak** [comment]
@cesarfd Friendly ping :)

**Comment by szmarczak** [comment]
I meant this, not the flamegraph (sorry if I got you confused):

![image](https://user-images.githubusercontent.com/36894700/73595229-79021c80-4516-11ea-8207-0ac3522626e2.png)

**Comment by cesarfd** [comment]
Oh, right, just click on the source code file, where it says the file name
and number, it will take you there.

**Comment by szmarczak** [comment]
Hmm... It takes me there but there are no timings... Will try a different Chromium browser.

**Comment by szmarczak** [comment]
@cesarfd Oh, I've got it now! The running node script must not exit in order to display the timings. Thank you :)

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/73595901-c5048f80-451d-11ea-9a7b-ebf25752e81f.png)

lol I didn't know that comments take CPU time (just kidding). It gives me wrong results. Some functions aren't called at all and it says it took 7ms to run them. The flamegraph gives good results tho. Tried two different browsers: Google Chrome and Brave. I run Node 13.7.0. Will try Node 10 & 12.

**Comment by resynth1943** [comment]
Maybe Sindre should consider removing comments as an optimization. :stuck_out_tongue:
