### ISSUE TITLE
Fail fast if user has patched request by agent-base

### ISSUE THREAD

**Issue by gugu** [sindresorhus/got#1018]
#### Describe the bug

 - Node.js version: any
 - OS & version: any

Currently got does not work with agent-base<=4. I understand you don't want to deal with this crappy module, but a nice error message will save a lot of time to `got` users.

In my module agent-base v4 is used by:
1. google APIs
2. sentry
3. socks-proxy-agent

#### Actual behavior
1. `got` shows a cryptic error message  "can not connect to localhost"
2. it shows this message in runtime

#### Expected behavior

detect if `https.request.__agent_base_https_request_patched__` is defined and throw an exception "got is incompatible with agent-base<=4, please upgrade"

#### Code to reproduce

```js
require('agent-base')
require('got').default('https://google.com')
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Here's a fix: https://github.com/sindresorhus/got/issues/876#issuecomment-573348808

I don't think we should check that, because `agent-base` fixed that in `4.3.0` I think.
