### ISSUE TITLE
Typescript: missing headers in Response type

### ISSUE THREAD

**Issue by jaulz** [sindresorhus/got#1019]
#### What would you like to discuss?

I would like to read the response headers but with `got@10.2.2` I cannot because
```typescript
const response = await this.request<ResponseType>(link, {})
```

returns a `Response` type which is defined the following way:
```typescript
export interface Response<BodyType = unknown> extends IncomingMessageWithTimings {
    body: BodyType;
    statusCode: number;
    /**
    The remote IP address.

    Note: Not available when the response is cached. This is hopefully a temporary limitation, see [lukechilds/cacheable-request#86](https://github.com/lukechilds/cacheable-request/issues/86).
    */
    ip: string;
    fromCache?: boolean;
    isFromCache?: boolean;
    req?: http.ClientRequest;
    requestUrl: string;
    retryCount: number;
    timings: Timings;
    redirectUrls: string[];
    request: {
        options: NormalizedOptions;
    };
    url: string;
}
```

Am I doing anything wrong?

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
I think you missed that part: `extends IncomingMessageWithTimings` which is defined in the following way:

```ts
export interface IncomingMessageWithTimings extends IncomingMessage {
	timings?: Timings;
}
```

which has got defined the `headers` property: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L286

**Comment by jaulz** [comment]
Sorry for some reason Typescript complained but now it is working properly. Thanks also for pointing me to the link!
