### ISSUE TITLE
Got 10 doesn't work with AWS XRay in lambda

### ISSUE THREAD

**Issue by MickVanDuijn** [sindresorhus/got#1022]
#### Describe the bug

 - Node.js version: 10.x and 12.x
 - OS & version: AWS Lambda, Got 10

This might not be caused by Got, but occurs when using Got 10 in combination with AWS XRay on AWS Lambda. **Note**: Got 9 works fine with the provided snippet. 

I also opened an issue on the [`aws-xray-sdk-node`](https://github.com/aws/aws-xray-sdk-node/issues/240) repository.

#### Actual behavior

Whenever XRay capture is enabled, the lambda doesn't return any response, and the actual request is made against `https://localhost`. Subsequent executions take longer and longer (even up to 2 minutes) until finally one execution will show a bunch of LAMBDA_RUNTIME_ERROR.

#### Expected behavior

Get contents of `google.com` and return the specified response (`body: 'ok'`)

#### Code to reproduce

```js
require('aws-xray-sdk-core').captureHTTPsGlobal(require('https'))
const got = require('got')

export async function handler() {
    await got.get(`https://google.com`)

    return {
        statusCode: 200,
        body: 'ok',
    }
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got. (Lambda only supports up to Node.js 12)

**Comment by szmarczak** [comment]
`aws-xray-sdk-core` monkey-patches the `https` module wrongly. They provide only `request(options, callback)` while we use Node 10's `request(url, options, callback)`. Closing since this is not a Got issue.

**Comment by MickVanDuijn** [comment]
Thanks! I quickly verified, and indeed if I monkey-patch the `aws-xrat-sdk-core` code right before deploying it to lambda to only provide the `request(url, options, callback)` (just to verify, not a desired solution), the Got request succeeds as expected! I'll update the issue on their side to include this info. Thanks again!
