### ISSUE TITLE
Any alternative proxy agent or maybe native proxy support?

### ISSUE THREAD

**Issue by JamesJGoodwin** [sindresorhus/got#1023]
#### What would you like to discuss?

Hello. I'm having an issue with [tunnel](https://github.com/koichik/node-tunnel) for my proxied requests. Usage of some proxies may throw an exception that crashes the process entirely and is unable to catch. Developer of this module is unresponsive and I consider this module is unmaintained since there's no answer from dev on that issue for more than month. Is there any alternative that is compatible with Got? If so could you please add it to docs? And are you considering to add native proxy support to Got?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> Usage of some proxies may throw an exception that crashes the process entirely and is unable to catch

What exception is it?

**Comment by JamesJGoodwin** [comment]
@szmarczak there's an issue [#40](https://github.com/koichik/node-tunnel/issues/40)
