### ISSUE TITLE
Can't understand the difference

### ISSUE THREAD

**Issue by legrandjeremy** [sindresorhus/got#1030]
Hi,

I spend hours to understand this, I'm stucked with it.
I tried to work with "got" to send a simple POST request to an endpoint with "form-urlencoded" header.
I can't get it worked... So I tried to use axios and it worked well...

This is my fully code with axios and "got" calls 👍 

```js
const axios = require('axios')
const qs = require('querystring')
const got = require('got')


const requestBody = {
  'id': 'XDED'
}

const config = {
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  }
}

axios.post('API_URL', qs.stringify(requestBody), config)
  .then((result) => {
    // it worked well
    console.log(result.data)
  })


got.post('API_URL', {
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  form: requestBody
}).then(function(r) {
    // the result is correct but the request is not correctly received !
    console.log(r.body)
  })
```

My endpoint failed to respond me correctly with got request, it seems no post parameters is received.

Can you help me understand why axios worked and not "got" in my example ?

MANY thanks in advance,

**Comment by szmarczak** [comment]
You need to pass an object, not a string. `options.body` accepts strings.

**Comment by sindresorhus** [comment]
@szmarczak It's the `form` option being used, not `body`.

**Comment by szmarczak** [comment]
`form` accepts objects IIRC. We don't check that so it passes silently.

**Comment by szmarczak** [comment]
oh sorry I didn't notice it was *just* `requestBody`, investigating now

**Comment by szmarczak** [comment]
It works as expected: https://runkit.com/szmarczak/5e2c575cacc4ba001a917a4c
