### ISSUE TITLE
Socket connect timeout is not firing when it should in node 12

### ISSUE THREAD

**Issue by fabianflugund** [sindresorhus/got#1034]
#### Describe the bug

 - Node.js version: v12.14.1
 - OS & version: Docker base image node:12 

While upgrading from node 10 to node 12 we have discovered that the timeout defined in the extend option `{ timeout: { connect: number } }` does not behave as expected. 

#### Actual behavior

Setting the timeout to `1000` results in an actual timeout time of roughly 6s. 

#### Expected behavior

We expect that the timeout should fire close to the defined time. 

#### Code to reproduce

got-timeout.js
```js
const got = require('got')

const client = got.extend({
    timeout: { connect: 1000 },
});

const test = async () => {
    const start = Date.now()

    try {
        await client('http://192.0.0.2/missing') // Non existing endpoint
    } catch (err) {
        console.log(err.code, err.message)
    }

    const end = Date.now()

    console.log(`Actual time: ${end - start}`)
}

test()
```
Dockerfile
```docker
FROM node:12
COPY package*.json ./
RUN npm install
COPY . .
CMD [ "node", "got-timeout.js" ]
```
package.json
```json
{
  "name": "scripts",
  "version": "1.0.0",
  "description": "",
  "main": "got-timeout.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "got": "^10"
  }
}
```

result
```bash
ETIMEDOUT Timeout awaiting 'connect' for 1000ms
Actual time: 6194
```
#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please read the documentation before filing an issue.

> By default, Got will retry on failure. To disable this option, set options.retry to 0.

**Comment by fabianflugund** [comment]
OK, I see. 

We originally discovered this in v9.6.0, where the behaviour was that the request took 8s. 

Setting the retry to 0 seems to fix the issue for v10. 

Thanks
