### ISSUE TITLE
I see such error on request "connect ECONNREFUSED 127.0.0.1:443"

### ISSUE THREAD

**Issue by CrispusDH** [sindresorhus/got#1039]
#### Describe the bug
I run `puppeteer` and after it launch use `GOT` to send some request

 - Node.js version: 13.7.0
 - GOT version: 10.2.2
 - OS & version: macOS Catalina

#### Actual behavior
```
  node_modules/got/dist/source/request-as-event-emitter.js:137

  Rejected promise returned by test. Reason:

  RequestError {
    code: 'ECONNREFUSED',
    message: 'connect ECONNREFUSED 127.0.0.1:443',
  }

  onError (node_modules/got/dist/source/request-as-event-emitter.js:137:29)
  handleRequest (node_modules/got/dist/source/request-as-event-emitter.js:170:17)
```

#### Expected behavior
The request will be sent

#### Code to reproduce
I create an example repository https://github.com/CrispusDH/puppeteer-got

Here is the single file from it:
```js
import * as puppeteer from 'puppeteer';
import test from 'ava';
import got from "got";

test('example', async () => {
  const browser: puppeteer.Browser = await puppeteer.launch(
    {
      headless: false,
      defaultViewport: {
        width: 1366,
        height:766
      }
    });
  const pages = await browser.pages();
  const page = pages[0];
  await page.goto('https://github.com/avajs/ava');

  await got('https://github.com/avajs/ava');
});
```

#### Notes:
1. Oddly this isn't happening in a stand alone file.
2. some similar issue but I did not find solution for me:
- https://github.com/sindresorhus/got/issues/951

#### UPDATE:
I got the same error even just with only `AVA` and `GOT`

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by yovanoc** [comment]
I have the exact same thing but I don't use puppeteer neither https-proxy-agent...

**Comment by CrispusDH** [comment]
I got the same error even without `puppeteer`. Just `AVA` and `GOT`:
```
import test from 'ava';
import got from "got";

test('example', async () => {
  await got('https://github.com/avajs/ava');
});
```

**Comment by folkhack** [comment]
Seeing same issue with got 10.2.2.

**Comment by yovanoc** [comment]
I found a thing. Look if like me you are using in your entire repo a version of node-agent-base < 5 with `npm ls agent-base` 

https://github.com/npm/make-fetch-happen/issues/17

**Comment by CrispusDH** [comment]
this is my dependencies in `package.json`
```
    "typescript": "3.7.5",
    "ava": "3.0.0",
    "@types/node": "13.5.0",
    "got": "10.2.2"
```

**Comment by jrnelson90** [comment]
I see this issue in 10.3.0 when I run suite of Mocha tests using Got on Jenkins, but not when I run them on my machine.

**Comment by jrnelson90** [comment]
Update: Since I'm also using the New Relic JS client, I have 

```
└─┬ newrelic@6.2.0
  └─┬ https-proxy-agent@3.0.1
    └── agent-base@4.3.0 
```
So not being on `agent-base` < 5 as mentioned by @yovanoc seems to be the root of my issue. When I run locally, New Relic metrics are disabled by default, hence the disparity in my test run on Jenkins.

**Comment by szmarczak** [comment]
Puppeteer fixed it in `v2.1.0`.

**Comment by lostpebble** [comment]
Would just like to add that I've run into this issue now as well since updating from `9.6.0` to `10.x`. Its impossible for me to move on to versions `10.x` because of this issue- I have a monorepo with many libraries depending on different versions of `https-proxy-agent`. The strange thing is that I've never faced this issue with other request libraries- it really feels like a regression on `got`'s part, even though it apparently isn't.

I see from other issues this is not something you feel the need to resolve from your side, and I respect that. Just thought you should know this is making newer versions a non-starter for me and probably many others.

**Comment by szmarczak** [comment]
> The strange thing is that I've never faced this issue with other request libraries- it really feels like a regression on got's part, even though it apparently isn't.

Modern problems require modern solutions. The other libraries use Node.js legacy code and sometimes aren't compatible with newer APIs, so the saying doesn't apply here :(

**Comment by justinasfour04** [comment]
I'm facing this same issue in my project when trying to run a get request on a url

npm ls agent-base
update-service-alerts@2.0.0 /Users/jasfour/Transit/UpdateServiceAlerts
├─┬ @google-cloud/storage@4.7.0
│ ├─┬ @google-cloud/common@2.4.0
│ │ └─┬ teeny-request@6.0.3
│ │   └─┬ http-proxy-agent@4.0.1
│ │     └── agent-base@6.0.0  deduped
│ └─┬ gaxios@3.0.2
│   └─┬ https-proxy-agent@5.0.0
│     └── agent-base@6.0.0
└─┬ cloudflare@2.7.0
  └─┬ https-proxy-agent@2.2.4
    └── agent-base@4.3.0

**Comment by perry-mitchell** [comment]
Seeing the same! I think this should be reopened @szmarczak -

```
$ npm ls agent-base
my-proj@0.14.0-r.1 /my-proj
└─┬ pubnub@4.27.5
  └─┬ superagent-proxy@2.0.0
    └─┬ proxy-agent@3.1.1
      ├── agent-base@4.3.0 
      ├─┬ http-proxy-agent@2.1.0
      │ └── agent-base@4.3.0  deduped
      ├─┬ https-proxy-agent@3.0.1
      │ └── agent-base@4.3.0  deduped
      ├─┬ pac-proxy-agent@3.0.1
      │ └── agent-base@4.3.0  deduped
      └─┬ socks-proxy-agent@4.0.2
        └── agent-base@4.2.1 
```

The second I installed `pubnub`, which uses `superagent-proxy` and `agent-base`, it borked.

**Comment by szmarczak** [comment]
It should not be reopened, this is not a Got issue!
