### ISSUE TITLE
searchParams does not replace url parameters

### ISSUE THREAD

**Issue by dakaraphi** [sindresorhus/got#1048]
#### Describe the bug

 - Node.js version: 12.10.0

#### Actual behavior
When url is URL object, query string parameters are not replaced with values from the searchParams option
...

#### Expected behavior
query string parameters are replaced as indicated by documentation.
...

**Comment by szmarczak** [comment]
Well we have many `searchParams` tests, for example: https://github.com/sindresorhus/got/blob/27cdd982058ed77d6d81b58059217a8a7f2d2471/test/arguments.ts#L131-L141 and as you can see all tests pass :)

Please fill out the issue template properly.

**Comment by szmarczak** [comment]
@dakaraphi Friendly ping :)

**Comment by barinali** [comment]
I was trying to consume the `searchParams` property to have a query string in the request. However, that was not working as expected from my perspective and ended up using `query` property instead of `searchParams`. However, I couldn't find any documentation regarding the `query` property.

Since this is somewhat relevant, I wanted to share it.

**Comment by szmarczak** [comment]
>  However, that was not working as expected from my perspective and ended up using query property instead of searchParams

Well, can you reproduce it somehow?

> I couldn't find any documentation regarding the query property.

It's a Node.js legacy property. When you pass any legacy property it will throw in Got 12.

**Comment by barinali** [comment]
The behavior is pretty consistent on my side. When I build up my request like the following;

```javascript
    const options = {
      headers: {
        'Content-Type': 'application/json',
      },
      query: new URLSearchParams({
        q: emailAddress,
        sobject: 'Case',
        in: 'EMAIL',
        'Case.fields': 'id',
      })
    };
  
    const response = got.get('{url}', options);
```
The following `request` is logged;

```javascript
{
  gotOptions:{
    path: '/services/data/v46.0/parameterizedSearch?q=an@email.com&sobject=Case&in=EMAIL&Case.fields=id',
    protocol: 'https:',
    hostname: '-redacted-',
    hash: '',
    search: '',
    pathname: '/services/data/v46.0/parameterizedSearch',
    href:
      '-redacted-',
    retry: [Object],
    headers: [Object],
    hooks: [Object],
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    baseUrl: [Getter/Setter],
    method: 'GET'
  }
}
```

If I implement it with the `searchParams`, the query string is not be embedded in `path`.

It'll be left in the `searchParams` property in the `gotOptions` property in the return of `got.get`.

```
searchParams:
  URLSearchParams {
    'q' => 'an@email.com',
    'sobject' => 'Case',
    'in' => 'EMAIL',
    'Case.fields' => 'id'
  }
```

Note; I have tried to provide the values without URLSearchParams, as a plain Object.

**Comment by szmarczak** [comment]
Can you set up a RunKit example? You can use e.g. `httpbin.org` as the endpoint.

**Comment by barinali** [comment]
I have just prepared a RunKit example. However, I have just realized that I am using v9.6.0. So I'd like to mention the difference may be due to that if you find what I said above unexpected.

Here is the RunKit example; https://runkit.com/barinali/query-vs-searchparams-in-got.

**Comment by barinali** [comment]
I have just checked the release for v10 to see the changes. It seems to be due to the version I use. So, sorry for unnecessarily drawing the attention.

https://github.com/sindresorhus/got/releases/tag/v10.0.0

**Comment by szmarczak** [comment]
No problem. It is good to fill out the template issue, right?

**Comment by barinali** [comment]
@szmarczak I'd strongly agree on that. However, I'd like to let you know that I'm not the original poster just in case.
