### ISSUE TITLE
Auth request breaks if password has # (hash) in it

### ISSUE THREAD

**Issue by Jakobud** [sindresorhus/got#105]
I was given an API ID and password for a service. The password has a `#` in it. When using got to make a put request, it bugs out. I have traced the problem back to the `#` in the password. Here is something to recreate it (at least using the API service I am using..., but you should be able to simulate something similar with some other service you make requests to) :

```js
// First lets do a normal https request to show that this works:
var id = "test";
var pass = "45d3ps#453";

var https = require('https');
var options = {
	'method': 'POST',
	'host': 'account.myservice.com',
	'path': '/api/token',
	'auth': id + ":" + pass,
	'headers': {
		'Content-Type': 'application/x-www-form-urlencoded'
	}
};

var req = https.request(options, function(res){
	console.log(res.statusCode);
	console.log(res.headers);

	res.on('data', function(data){
		process.stdout.write(data);
	});
});

req.on('error', function(err){
	console.log("Error", err);
});

req.write('request=credentials');
req.end();
```
I get the expected response:
```js
200
{ 'content-type': 'application/json; charset=UTF-8',
  'cache-control': 'no-store',
  date: 'Fri, 18 Sep 2015 22:05:09 GMT',
  'accept-ranges': 'bytes',
  vary: 'Accept-Charset, Accept-Encoding, Accept-Language, Accept',
  pragma: 'no-cache',
  connection: 'close' }
{"expires_in":1799,"token_type":"api-test","access_token":"dk393kd-3i9dk3-39dk"}
```

So that works fine. Now with `got`:
```js
var id = "test";
var pass = "45d3ps#453";

var got = require('got');

var url = "https://" + id + ":" + pass + "@account.myservice.com/api/token";

var options = {
	'body': 'request=credentials',
	'headers': {
		'Content-Type': 'application/x-www-form-urlencoded'
	}
}

got.post(url, options, function(err, data, res){
	if (err) {
		console.log("Error", err);
	} else {
		console.log(data, res);
	}
});
```
I get:
```js
Error { [RequestError: getaddrinfo ENOTFOUND test]
  message: 'getaddrinfo ENOTFOUND test',
  code: 'ENOTFOUND',
  host: 'test',
  hostname: 'test',
  method: 'POST',
  path: '/:45d3ps' }
```

The first thing I noticed was that the return headers path had part of the password in it. It didn't take long to figure out that the `#` hash was causing some issues with the url. Honestly, I'm not sure (according to internet w3c standards) if it's even valid to have a `#` hash in the username or password section of a URL since a hash is typically used at the end of a url.... But it's working for Node's vanilla https module so I dunno...

Any thoughts on this?

**Comment by floatdrop** [comment]
@Jakobud `auth` option in `http` module computer `Authorization` header, so this should work for you:

```js
var options = {
    'body': 'request=credentials',
    'headers': {
        'Authorization': id + ':' + pass,
        'Content-Type': 'application/x-www-form-urlencoded'
    }
}
```

Another question, should we parse out `id` and `pass` from `url`.

**Comment by sindresorhus** [comment]
Passing Basic Auth in the URL is deprecated and not even possible anymore in Chrome and IE.

http://serverfault.com/questions/371907/can-you-pass-user-pass-for-http-basic-authentication-in-url-parameters

I think we should add a note now about using auth header instead and in the next major throw if user try to do that instead of using the header. @floatdrop Thoughts?

**Comment by floatdrop** [comment]
@Jakobud on second thought you can pass `#`, but you must use [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent):

```js
let res = require('http').get('http://user:' + encodeURIComponent('pa##word')+ '@google.com', function (){});

console.log(res._headers); // => GET / HTTP/1.1\r\nHost: google.com\r\nAuthorization: Basic dXNlcjpwYSMjd29yZA==\r\nConnection: close\r\n\r\n
```

@sindresorhus yes, `username:password` is deprecated by [rfc3986](https://tools.ietf.org/html/rfc3986#section-3.2.1), but this format is supported by Node `url.parse` method, so I don't see why we should explicitly forbid that.

**Comment by sindresorhus** [comment]
> yes, username:password is deprecated by rfc3986, but this format is supported by Node url.parse method, so I don't see why we should explicitly forbid that.

In contrast to Node, we can actually prevent its usage. Node has way too much baggage and dependence to do something like that. As for reasoning, it's deprecated and it would help users doing the right thing, and not end up with problems like this one. I see no downside doing this: https://github.com/sindresorhus/got/issues/106

**Comment by Jakobud** [comment]
So if I don't use `username:password` in the url for a particular service, should that service automatically accept the Header authentication alternative?

Thanks for answering this one. It's kind of a weird one.
