### ISSUE TITLE
The latest release is missing p-event dependency

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#1055]
Version: 10.5.1

```
  Error: Cannot find module 'p-event'
  Require stack:
  - /Users/gajus/Documents/dev/rayroute/rayman/node_modules/got/dist/source/request-as-event-emitter.js
  - /Users/gajus/Documents/dev/rayroute/rayman/node_modules/got/dist/source/as-promise.js
  - /Users/gajus/Documents/dev/rayroute/rayman/node_modules/got/dist/source/create.js
  - /Users/gajus/Documents/dev/rayroute/rayman/node_modules/got/dist/source/index.js

```

**Comment by gajus** [comment]
Looks like it is now used in the main package:

https://github.com/sindresorhus/got/blob/453a3a31041804d46466df7ac3bc1e3a68d0eef2/source/request-as-event-emitter.ts#L19

**Comment by fisker** [comment]
Broken on my github actions too https://github.com/fisker/git-hooks-list/pull/122/checks?check_run_id=431293206

**Comment by sindresorhus** [comment]
Fixed: https://github.com/sindresorhus/got/releases/tag/v10.5.2

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/issues/1056
