### ISSUE TITLE
Got doesn't throw on leading slashes

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1057]
As per the readme:

> Note: Leading slashes in input are disallowed when using this option to enforce consistency and avoid confusion. For example, when the prefix URL is https://example.com/foo and the input is /bar, there's ambiguity whether the resulting URL would become https://example.com/foo/bar or https://example.com/bar. The latter is used by browsers.

But it does not throw:

https://github.com/sindresorhus/got/blob/3c6ca29000707dfad1d51edd013748107806404d/source/normalize-arguments.ts#L303-L319

**Comment by azz** [comment]
I don't think it should throw if `prefixUrl` is just a hostname:

```js
const myApi = got.extend({ prefixUrl: 'https://api.example.com' });

myApi.get('/things'); // this should be fine as it is not ambiguous.
```

**Comment by szmarczak** [comment]
@azz The readme says that the ending `/` will be added automatically if not present, thus it should throw if the input starts with `/`.

**Comment by azz** [comment]
That's what's currently documented but I'm challenging whether that behaviour is appropriate, especially in the case where it is non-ambiguous.

**Comment by szmarczak** [comment]
The documentation provides a non-ambiguous behavior, which has been intensively discussed. please see #829 and #943 for more information.
