### ISSUE TITLE
A way to customize `cacheable-lookup`

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/got#1058]
Hello,

I noted `dnsCache` is used only for setup cache adapter at `cacheable-lookup`: 

https://github.com/sindresorhus/got/blob/1f363b976cd23626462314c7cd5670cddd951c73/source/normalize-arguments.ts#L147

Since I'm interested in customize some `cacheable-lookup` capabilities, (such as [resolver](https://github.com/szmarczak/cacheable-lookup#optionsresolver)) I want to ask if you will accept a way for passing a `cacheable-lookup` instance as `dnsCache` to be used 🙂

**Comment by szmarczak** [comment]
This is already fixed in #1051, but I don't think it'll be merged this month. Also I don't have much time now, so my work is strictly focused on #1051. Anyway, PRs are welcome :)

**Comment by szmarczak** [comment]
For now you can do this:

```js
const instance = got.extend({
	dnsCache: new Map(),
	mutableDefaults: true
});

instance.defaults.options.dnsCache._resolver.setServers([
    '1.1.1.1',
    '8.8.8.8'
]);
```

**Comment by Kikobeats** [comment]
wow #1051 is huge, if you think this is resolved there then that's enough 🙂
