### ISSUE TITLE
Canceling request: "r.cancel is not a function"

### ISSUE THREAD

**Issue by garyo** [sindresorhus/got#1066]
#### What would you like to discuss?

I'm trying to cancel an ongoing request like this:
```typescript
      const request = got(url, { retry: 0 })
      function startTimer(r: typeof request) {
        return setTimeout(() => r.cancel(), timeoutMs)
      }
      const timer = startTimer(request)
      const response = await request
      clearTimeout(timer)
      // check response or handle error
```
but I get `TypeError: r.cancel is not a function` at runtime. Typescript thinks all is OK at compile time and can see that `request` and `r` are of type `CancelableRequest`.

I must be doing something wrong; I'm new to got.
(I'm trying this method because I have a server that may be down and I don't want to wait a long time for ECONNREFUSED -- I tried setting all the timeouts in `options.timeout`, but they had no effect, so I'm trying this.)

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
I cannot reproduce with your example: https://runkit.com/szmarczak/5e46bac55abbb10013e2e34a

**Comment by garyo** [comment]
OK, I switched to another lib anyway. Must have been my error. Closing.
