### ISSUE TITLE
Make some normalized options enumerable

### ISSUE THREAD

**Issue by aalexgabi** [sindresorhus/got#1067]
Got errors have an options property which is not enumerable: https://github.com/sindresorhus/got/blob/1d012a513a2263f0f51d327e7b509d9d3bd8ffc5/source/errors.ts#L23

This was introduced because of a security issue: https://github.com/sindresorhus/got/issues/754

But the chosen solution is not good for all cases. This means that in a service that does many requests it's impossible to know where the error comes from unless remembering to do manual exception wrapping in all places http requests are initiated:
```js
  try {
        await got.patch(url, {
          json: body,
          headers: {
            Authorization: `Bearer ${configuration.get('api.token')}`,
          },
        });
      } catch (err) {
        err.context = _.omit(err.options, ['options.headers.Authorization'])
        throw err;
      }
```
Without it I get errors like this in logs which are useless:
```
    HTTPError: Response code 500 (Internal Server Error)
        at EventEmitter.<anonymous> (.../node_modules/got/dist/source/as-promise.js:118:31)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I think this needs to be improved. For example one solution would be to have a default list of properties paths that should not be enumerable (ex. headers.Authorization) that can be overwritten by the user.

The very least would be to make the url, method and status code enumerable.

**Comment by sindresorhus** [comment]
> The very least would be to make the url, method and status code enumerable.

I agree. We should whitelist some known-to-be-safe properties.

**Comment by szmarczak** [comment]
This also applies to `error.response`.

**Comment by robcresswell** [comment]
@szmarczak Do you have any thoughts on what a solution might look like here? The quirk from my own usage with `got` is that logging the error thrown is not sufficient; you have to know to log the response body to get usable error messages usually, which isn't ideal for new consumers of the library

**Comment by szmarczak** [comment]
Closing in favor of #1353
