### ISSUE TITLE
Cookies don't seem to be persisting across requests

### ISSUE THREAD

**Issue by sbrl** [sindresorhus/got#107]
Does `got` support cookies? If so, how do I pass it a cookie jar? Where do I get a cookie jar? The README doesn't seem to explain this.

Context: I'm switching a project of mine from request to got, which uses a cookie jar (it doesn't appear to work without one). When I finished switching it over, I got a "Not Authorised" response from a url in a sequence of 3 which I should have got a success response instead. This leads me to think that `got` isn't storing cookies correctly.

**Comment by floatdrop** [comment]
@sbrl `got` does not have cookie support out-of-the-box, but it can be easly achieved with [`cookie`](https://github.com/jshttp/cookie) module:

```js
let got = require('got');
let cookie = require('cookie');

got('google.com', {
    headers: {
        cookie: cookie.serialize('foo', 'bar')
    }
});
```

See also:
* [tough-cookie](https://www.npmjs.com/package/tough-cookie)
* [cookies](https://www.npmjs.com/package/cookies)

**Comment by sbrl** [comment]
Ok. I was hoping that there would be built in support. I'll see what I can do. The problem is that I need to make multiple different requests and save the cookie state after each one in order to login to a particular online service :/

**Comment by floatdrop** [comment]
@sbrl I'd recommend make all requests to this service through new module (like [gh-got](http://npmjs.com/gh-got) or [vk-got](http://npmjs.com/vk-got)) and add default jar storage into it.

**Comment by sbrl** [comment]
Default jar storage? What's that?

**Comment by floatdrop** [comment]
@sbrl shared instance of [tough-cookie](https://www.npmjs.com/package/tough-cookie) for example.

**Comment by sbrl** [comment]
@floatdrop Right. I don't understand how I can pass a default jar into a `gh-got` or `vk-got` instance without doing it manually - in which case I should use vanilla `got` instead. Sorry for all the questions :(

**Comment by franklinyu** [comment]
Bloated `request` has built-in cookie jar support.

**Comment by gajus** [comment]
This thread doesn't answer the question how to use `tough-cookie` with `got`, e.g. How will the redirects be handled?
