### ISSUE TITLE
Can't get GOT to send simple GET requests

### ISSUE THREAD

**Issue by qwertangel** [sindresorhus/got#1071]
#### Describe the bug

 - Node.js version: v10.4.1
 - OS & version: MacOs Catalina

#### Actual behavior
Getting error..

`{ GotError: The "listener" argument must be of type Function. Received type object
    at get (/Users/user/Documents/gotTest/node_modules/got/dist/source/request-as-event-emitter.js:199:27)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (https.js:272:10)
    at get (/Users/user/Documents/gotTest/node_modules/got/dist/source/request-as-event-emitter.js:196:65) name: 'RequestError', code: 'ERR_INVALID_ARG_TYPE' }
`

#### Expected behavior
Response from website.
...

#### Code to reproduce

```js
const got = require('got');

(async () => {
    try {
        const body = await got('https://teasdfasd2er.free.beeceptor.com');
        console.log(body);
    } catch (error) {
        console.log(error);
    }
})();
```

Package.json
```
{
  "name": "gotTest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "got": "^10.5.5"
  }
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Your Node.js 10.x version is very old. Try upgrading to the latest Node.js 10 version, or preferably 12. There have been a lot of Node.js bug fixes since Node.js 10.4.

**Comment by qwertangel** [comment]
yup.. upgrading node to latest version fixed it.
