### ISSUE TITLE
The RunKit example is outdated

### ISSUE THREAD

**Issue by Eomm** [sindresorhus/got#1072]
#### Describe the bug

The runkit example is not updated for got v10:
https://npm.runkit.com/got

#### Actual behavior

```
(await got(ISS, { json: true })).body.iss_position;
```

> TypeError: The `GET` method cannot be used with a body

The code should be updated with:

```
(await got(ISS, { responseType: 'json' })).body.iss_position;
```

I didn't find where this example is stored in this repo, I suppose it is not.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
We don't have any control over that example as it's made by npm, but it seems like we can override it: https://blog.runkit.com/2015/10/28/npm-plus-runkit/

**Comment by szmarczak** [comment]
Fixed in #1253 48bbb369d715b8ec3c36e0af1ec88f47e2299172

**Comment by szmarczak** [comment]
Unfortunately it still doesn't have any effect:

![image](https://user-images.githubusercontent.com/36894700/82125106-e96e3a00-97a3-11ea-86b8-a2ffce208910.png)

**Comment by Giotino** [comment]
Maybe it has to be in `files`...

**Comment by szmarczak** [comment]
Let's wait a while a let's see. Maybe it should be moved to root directory, idk.
