### ISSUE TITLE
Add an option to allow GET with body

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1074]
Currently Got throws <code>TypeError: The `GET` method cannot be used with a body</code> when you try to upload some data using the GET method. [The RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.1) doesn't specify any particular behavior regarding this situation. Undefined behavior is considered to be an [anti-pattern](https://en.wikipedia.org/wiki/Anti-pattern).

Although this has been discussed in some issues, there are many people who are still interested in this. Sometimes the HTTP servers don't follow the RFC. We have already added an option to [ignore invalid cookies](https://github.com/sindresorhus/got/pull/826). The proposed solution is to disable the error via another option, for example ~`ignoreStrictPayload`~ `allowGetBody`.

**Comment by sindresorhus** [comment]
Wouldn't it be clearer with an option called `allowGetBody`?

**Comment by szmarczak** [comment]
Sure.

**Comment by sindresorhus** [comment]
In addition, to anyone that decides to work on this. The docs should strongly advice against using this option and explain that it's an anti-pattern and that HTTP2 doesn't allow a GET with body. That it's only meant to interact with non-compliant servers when you have no other choice.

**Comment by dcharbonnier** [comment]
Sorry but just in case someone find this thread I need to give some information to avoid the spread of disinformation, people trust what they read on the web.
 - If a server does not accept a body with GET it's up to the server, like a server that would refuse you to do a POST on a certain url.
- If a proxy / a firewall does not allow you to pass a body with a GET request it's a non compliant server, traefik, nginx for example are perfectly compliant, no issue here.
- Sending a body with a GET request is not "considered" an anti-pattern (the link point to  "anti-pattern is on wikipedia  that obviously does not mention the body with GET). It's considered by some as a good pattern for some specific cases, carrying more sense than having an  "artificial" POST for the development of REST api especially (exemple elastic search, facebook at some point), even made it recently in openapi 3.1 (https://github.com/OAI/OpenAPI-Specification/pull/1937) and by others as an anti-pattern with probably good points too.
- For http 1.1 https://tools.ietf.org/html/rfc7230#section-3.3 its very clear, for http/2 @sindresorhus seams to be really sure about it but from what I can read in the RFC https://tools.ietf.org/html/rfc7540#section-8.1 it seams that the http 1.1 rules apply but in the Example section there is a sentence conflicting with the same RFC, IMO a mistake in the example as it's not writen in the strict RFC vocabulary but we will have to expect a new RFC to correct this issue.
For reference #966 #1065

**Comment by dopecodez** [comment]
Hey @sindresorhus , i just migrated from request to got and might have a edge case where I may have to support a body on a GET request. I was looking through the code and it would like to contribute a PR to fix this issue with the option `allowGetBody` as discussed. Could i take this up if no-one is working on this right now?
Also looking through the code, i noticed we don't support body on both GET and HEAD requests. Since the [RFC 7321](https://tools.ietf.org/html/rfc7231#section-4.3.2) isn't clear on whether we should support a body on a HEAD request, should we think about supporting this as well? (Although i can't imagine a use case where a HEAD request could have a body). Thanks.

**Comment by szmarczak** [comment]
> Could i take this up if no-one is working on this right now?

Sure. Feel free.

> Since the RFC 7321 isn't clear on whether we should support a body on a HEAD request, should we think about supporting this as well?

Personally I think that we shouldn't do that for HEAD, as it's used only for scraping headers. If there would be any use case, then it should be another issue.

**Comment by dopecodez** [comment]
Should be fixed with PR #1081

**Comment by dopecodez** [comment]
I think this issue can be closed @sindresorhus @szmarczak
