### ISSUE TITLE
How to retry all request not receiving http status code 200

### ISSUE THREAD

**Issue by kdankert** [sindresorhus/got#1075]
#### What would you like to discuss?

I would like to know, how you can modify the got request retry option in order to retry every request that was not successful. Unfortunately I didn't find something about this on the internet or in the docs and I couldn't find out myself how to do that

Right now for example 502 Bad Gateway and 404 Not Found are not retried

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Bad Gateway is an improperly configured server, Not Found means the destination does not exist. I see no reason to retry here. Anyway:

> I didn't find something about this on the internet or in the docs

It's in the docs, keep reading.

> retry every request that was not successful

If you really want this, then you need to use a handler.

**Comment by kdankert** [comment]
@szmarczak Could you provide example to do that. I had a look in the retry options on how to specify status codes and error codes to retry, but status codes type only allows to set values from Array<408 | 413 | 429 | 500 | 502 | 503 | 504>, which wouldn't not solve the 404 error retry.

**Comment by szmarczak** [comment]
> status codes type only allows to set values from Array<408 | 413 | 429 | 500 | 502 | 503 | 504>, which wouldn't not solve the 404 error retry.

Where did you get that info? What Got version are you using?

**Comment by kdankert** [comment]
I am using the Version that is delivered from the latest Version of openid-vlient by panva. When i look in the Type definitions for the HTTPOptions i get the type definitions

**Comment by szmarczak** [comment]
Can't you just do `npm install got`? Older versions aren't very likely to be supported in the future.

**Comment by kdankert** [comment]
This issue is resolved. Thx for your help
