### ISSUE TITLE
Got does not work when required in in Auth0 Hooks

### ISSUE THREAD

**Issue by MylesWardell** [sindresorhus/got#1076]
#### Describe the bug

 - Node.js version: Unknown
 - OS & version: Unknown

When using Auth0 Hooks got was the only package that did not work when requiring in packages. Auth0 Does Provide a debug JSON and I will provide that below.

I understand this might be an issue with Auth0 but out of ~4 packages I tested got was the only one that did not require in correctly. It might just be that their version of nodejs is out of date.

#### Actual behavior
Error Message Provided From Auth0
{
  "message": "Unable to compile the extensibility code as javascript",
  "statusCode": 500,
  "error_description": "Unexpected token *",
  "stack": "/data/_verquire/got/10.5.7/node_modules/got/dist/source/create.js:101\n    got.paginate = async function* (url, options) {\n                                 ^\n\nSyntaxError: Unexpected token *\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:617:28)\n    at Module._compile (/data/sandbox/lib/module.js:178:19)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)"
}

#### Expected behavior

Import Correctly

#### Code to reproduce

```js
const got = require('got') -> In Auth0 Hooks Fiddle
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
They don't support generators

**Comment by szmarczak** [comment]
Please run Got in actual Node.js on your machine before making an issue.
