### ISSUE TITLE
request lifecycle timing info: `tcp` and `request` phase are not properly measured

### ISSUE THREAD

**Issue by jgehrcke** [sindresorhus/got#1080]
#### Describe the bug

I have been using `got` for a while. For most of the time this was version 9.6.x and now we switched to got 10. 

All the time, across various kinds of environments and HTTP requests, I have had a close look at the timing information returned with got response objects. I noticed, consistently, that the `tcp` and `request` phases must be measured incorrectly, always being displayed with 0 or 1 ms. This also happens for big HTTP requests where it is obvious that the `request` phase (starting after the successful TCP connect, ending with the last byte of the request having been written) takes a significant amount of time.

Example `response.timing` object after sending an HTTP request with 1 MB body size over a slow Internet connection:
```json
{
  "start": 1582121339601,
  "socket": 1582121339601,
  "lookup": 1582121339606,
  "connect": 1582121339606,
  "upload": 1582121339607,
  "response": 1582121343884,
  "end": 1582121343885,
  "phases": {
    "wait": 0,
    "dns": 5,
    "tcp": 0,
    "request": 1,
    "firstByte": 4277,
    "download": 1,
    "total": 4284
  }
}
```
Here, the `"request": 1` is definitely incorrect (note: these numbers are documented to have the unit `ms`). This must have been closer to 1 second, and I expected a three-digit or four-digit value.

Across invocations I saw the the `request` phase value oscillate between 0 and 1. Is there a unit conversion problem, or a systematic measurement error?

#### Environment

 - Node.js version: 12.16.1
 - OS & version: Linux
 - got 10.5.7 and 9.6.x

**Comment by szmarczak** [comment]
Resolved in the `http-timer` issue
