### ISSUE TITLE
Custom options not being merged (got.extend)

### ISSUE THREAD

**Issue by kgruszka** [sindresorhus/got#1088]
#### Describe the bug

 - Node.js version: v12.14.1
 - OS & version: macOS Mojave 10.14.6

Up to got version v10.4.0 I could pass any custom options to `got.extend` and then access merged options in hooks. From v10.5.0 that behaviour changed. Is it on purpose? I couldn't find an official statement that got supports merging any custom options though for anyone who was using it it's a breaking change.

#### Actual behavior

Custom options passed to `got.extend` are not merged/passed to hooks.

#### Expected behavior

Custom options passed to `got.extend` are merged/passed to hooks.

#### Code to reproduce

```js
const got = require('got');
const base = got.extend({ myCustomOption: 'test' });

const gotClient = base.extend({
  hooks: {
    init: [initHook]
  }
});

function initHook(options) {
  console.log(options.myCustomOption);
  // prints undefined
}

gotClient('https://google.com').catch(err => console.log(err));
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I think you meant to report a bug. Please include some code to reproduce the issue.

**Comment by kgruszka** [comment]
Actually I wasn't sure if that merging was an offical feature so wanted to ask first. I'll change it to bug.

**Comment by kgruszka** [comment]
@szmarczak updated the issue with code sample

**Comment by szmarczak** [comment]
You're using an `init` hook. From [the docs](https://github.com/sindresorhus/got#hooksinit):

> Called with plain request options, right before their normalization.

You pass no options here:

> gotClient('https://google.com')

Instead you should use `beforeRequest`, which is called after the normalization.
