### ISSUE TITLE
Where did the migration guide to v10 go?

### ISSUE THREAD

**Issue by zvictor** [sindresorhus/got#1089]
I didn't have the time to update my code when v10 was released, but I remember there was a migration guide from v9 to v10.

I am looking for it now and I can't find it anywhere. Has it been moved somewhere else or just killed? 😢

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/releases/tag/v10.0.0

**Comment by zvictor** [comment]
Sorry for wasting your time! I looked for a CHANGELOG.md, MIGRATIONS.md, and also searched in the docs, but I forgot about the releases. My fault.

thanks for the quick reply! 🎉
