### ISSUE TITLE
Configuring chained requests via express middlewares

### ISSUE THREAD

**Issue by retrocausal** [sindresorhus/got#1091]
#### What would you like to discuss?
I have a project where I am using express to proxy requests to a backend from the browser

[I found an issue that might be related](https://github.com/sindresorhus/got/issues/1062),  But was not too sure.

the express configuration is pretty straightforward , and looks like so: 

```js
router.use(`route`, middleware1, middleware2);
```

middlewares use got via a wrapper object . This is by design, so every route handler need not import got and configure options

the wrapper does nothing but provide an `execute` method, that looks like so:

```js
execute (){
   this.options.method = this.method
   this.options.headers = this.request.headers
   this.options.responseType = this.downstreamContentType
  /* attach body only if method is POST / PUT*/
   try {
          const awaited = await got(this.source, this.options);
    }catch(e){}

}
```

the problem is, once middleware1 finishes and `next()` is called within the stack, middleware 2
changes the `url/source` ,`method` , adds an `Authorization` token received by middleware1
and creates a new wrapper - then calls `wrapper.execute`

this call simply times out. or, gives me an `ECONNRESET` message in the catch block.

1. I have tried requesting the same resource via postman and curl after adding the same `Authorization` token, and it works fine. 
2. I have tried making the above two requests as chained fetch calls, from the browser and it still works.

The issue only happens when I use a multiple middleware stack on a route in express with got
Or, even when i dont use chained middlewares, and try to execute two got requests in a single middleware. the second request still fails.

I am using got v10+
 I have not configured a timeout or a retry in got's options, almost everything apart from whats needed is left to its default value
...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Could you set up a RunKit example? Or create an example repository? I can't recreate the issue by myself.

**Comment by szmarczak** [comment]
@retrocausal Friendly ping.

**Comment by retrocausal** [comment]
@szmarczak  Sorry, I havent been able to create an example repository. I meant to reply earlier, and could not do so. 

Should I close this and check later once I have an example repo?

**Comment by szmarczak** [comment]
Please try [11.0.0-beta.1](https://github.com/sindresorhus/got/tree/v11.0.0-beta.1) out and let me know if it's fixed or not.

**Comment by szmarczak** [comment]
Friendly ping.

**Comment by szmarczak** [comment]
Closing due to a lack of response.
