### ISSUE TITLE
Can't test expected error responses because HTTPError is thrown 

### ISSUE THREAD

**Issue by gtracy** [sindresorhus/got#1095]
#### Describe the bug

 - Node.js version: v12.12.0
 - OS & version: MacOS 10.15.3 (19D76)

I've tried using this package in mocha tests but struggling in cases where I want to test API error cases. Since the got.post() response Promise gets rejected for any HTTP status >= 300, I can't write a test that will ensure 400+ status codes for bad request payloads. Consider the following test,

```
async function post(slug,payload) {
    return await got.post(API_TEST_ENDPOINT + slug, 
        {
            json : payload,
            responseType : 'json'
        }
    );
};

describe('reject missing location data', function() {
    const logs = {
        "logs": [{ 
            //"location": "Paris",
            "timestamp": "01-27-2020 16:44:23",
        }]
    };

    it('responds with a 400', (done) => {
        post('api/log/device',logs).then(res => {
            expect(res.statusCode).to.equal(400);
            done();
        }).catch(err => {
            done(err);
        });
    });
});
```

The post call falls into the catch block and there is no result object to check status against. 

```
HTTPError: Response code 400 (Bad Request)
    at EventEmitter.<anonymous> (/Users/greg/propeller/code/server/api-device-resetter/node_modules/got/dist/source/as-promise.js:118:31)
```

In this case, a 400 status is perfectly valid and desired. I'd like to test against that status, but HTTPError prevents me from doing it.

**Comment by szmarczak** [comment]
Read the docs, it's there.

**Comment by szmarczak** [comment]
Hint in case you're struggling with it: set `throwHttpErrors` to `false`.

**Comment by gtracy** [comment]
thanks. for others, here's the alternate implementation of the post call above which will prevent errors from being thrown,

```
async function post(slug,payload) {
    return await got.post(API_TEST_ENDPOINT + slug, 
        {
            json : payload,
            responseType : 'json',
            throwHttpErrors : false
        }
    );
};
```

This lets you test properties of the response object just like cases where the API calls are successful.

**Comment by NigelGreenway** [comment]
For others, the documentation can be found [here](https://github.com/sindresorhus/got/blob/1018c2029eea1f5b75b5120265996f1c0b3c12ae/documentation/2-options.md#throwhttperrors).
