### ISSUE TITLE
Failed to load got after instalation

### ISSUE THREAD

**Issue by mrbontor** [sindresorhus/got#1104]
#### Describe the bug

 - Node.js version: v8.16.1
 - OS & version: windows 10

#### Actual behavior
getting error while initialization in
_[xxxxx\node_modules\got\dist\source\create.js:101]_  >>>` got.paginate = async function* (url, options) {` 
...

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/cf4fdad553f4bec82a9972dda40f5762f8c70c6d/package.json#L10
