### ISSUE TITLE
how can I make post request?

### ISSUE THREAD

**Issue by kuntergunt** [sindresorhus/got#1106]
I created a post request based on the documentation. But I get an error "The `body` option must be a stream.Readable, string or Buffer".
But I don't want to send a file or stream from some http destination. I just want to send some data from my code. Can I have a simple documentation on just a simple thing that most people might need.

kuntergunt

- [x ] I have read the documentation.

**Comment by sindresorhus** [comment]
Can you include some code? Hard to say what you're doing wrong without that.

**Comment by szmarczak** [comment]
how come we know what's the type of the `authRequest` if you haven't told us?

**Comment by kuntergunt** [comment]
How comes that not providing the answer to the question I have is the reason for closing the issue. Can you help me to find some library that has documentation on how to do a POST request?

**Comment by szmarczak** [comment]
no
