### ISSUE TITLE
Pass custom data through hooks

### ISSUE THREAD

**Issue by rifler** [sindresorhus/got#1108]
#### What problem are you trying to solve?

I have an Express application with many common (for my company) middlewares, which add some props to req. For example `req.lang`, `req.csrf`, `req.requestId` and so. It would be nice if I could access req object in hooks

#### Describe the feature
I would like to create instances and have access to req object inside hooks:
```js
const instance = got.extend({
    prefixUrl: 'https://example.com',
    hooks: {
    	beforeRequest(options, customData) {
			options.searchParams.add('lang', customData.lang);
			options.searchParams.add('request_id', customData.request_id);
        }
    },
});

app.get('/', ...expessMiddlewares, async (req, res) => {
	const data = await instance.get('yeeey', {
		customData: req,
	});
	
	res.send(data);
})
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
That's what the [`context`](https://github.com/sindresorhus/got#context) option is for.
