### ISSUE TITLE
Issues with got/index.js line 37 in our CI build

### ISSUE THREAD

**Issue by ajayindfw** [sindresorhus/got#111]
We are indirectly using got.js as an indirect dependency in our mobile application (Cordova, AngularJS and Ionic).  The CI build inside the corporation is throwing the following exception which does not impact the IPA/APK files that get generated as an output from the CI build but it is annoying to see that in a CI build where folks usually expect perfect log statements.  Here's the stack trace:

mozjpeg@4.0.1 postinstall /Users/hudson/.hudson/jobs/Mobile-Dashboard-Pilot/workspace/node_modules/ionic-minify/node_modules/mozjpeg-stream/node_modules/mozjpeg
> node lib/install.js

  ⚠ Redirected 10 times. Aborting.
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ MaxRedirectsError: Redirected 10 times. Aborting.
    at ClientRequest.<anonymous> (/Users/hudson/.hudson/jobs/Mobile-Dashboard-Pilot/workspace/node_modules/ionic-minify/node_modules/mozjpeg-stream/node_modules/mozjpeg/node_modules/bin-build/node_modules/download/node_modules/got/index.js:37:23)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

> pngout-bin@2.0.1 postinstall /Users/hudson/.hudson/jobs/Mobile-Dashboard-Pilot/workspace/node_modules/ionic-minify/node_modules/pngout-bin
> node lib/install.js

  ✔ pngout pre-build test passed successfully

> ionic-minify@1.0.11 postinstall /Users/hudson/.hudson/jobs/Mobile-Dashboard-Pilot/workspace/node_modules/ionic-minify
> node scripts/install.js

Copying minifier file to project's hooks/after_prepare...
Copying configuration file to project's hooks/ folder...
Copying chalk to your node_modules/ folder...
Copying clean-css to your node_modules/ folder...
Copying mozjpeg-stream to your node_modules/ folder...
Copying ng-annotate to your node_modules/ folder...
Copying pngout-bin to your node_modules/ folder...
Copying uglify-js to your node_modules/ folder...
Copying win-spawn to your node_modules/ folder...
Finished installing. Experience the awesomeness ;)

**Comment by sindresorhus** [comment]
> ✖ MaxRedirectsError: Redirected 10 times. Aborting.

That means your internet connection is somehow intercepting the connection and making it redirect in an infinite loop. The alternative is that `got` would never finish and indefinity stall the install process.

**Comment by ajayindfw** [comment]
Is there way I can check what URL is it trying to go to so I can test it with our proxy administrators? Where would I be putting a log message to test it.
