### ISSUE TITLE
Avoid double JSON parsing

### ISSUE THREAD

**Issue by rifler** [sindresorhus/got#1110]
#### What problem are you trying to solve?

case 1:
I call some API, which returns json in `{"snake_case": true}`. I would like to automatically converts body to camelCase.

In `afterResponse` hook receives `response` object, and body has string type.
So I do parse, convert and stringify back. And after that `got` does one more parse (as I understand).

case 2:
For some instances it would be nice to receive only `body` to `.then` callbacks like that:
```js
const directlyBody = await gotInstance.get('http://example.com');
```

#### Describe the feature

...

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
I see no problem here

**Comment by rifler** [comment]
Both cases are not problems
1) there is double json parsing/serialization
2) is it ok to return not `response` object from `afterResponse` hook? because there are some operations on response after `afterResponse` hook is called https://github.com/sindresorhus/got/blob/v9.6.0/source/as-promise.js for example redirects

**Comment by szmarczak** [comment]
> is it ok to return not response object from afterResponse hook?

No. You can use something like https://github.com/lukechilds/responselike

**Comment by szmarczak** [comment]
`afterResponse` hook is called **after** serialization, so you need to set `responseType` to `text` and do the parsing in the hook.

**Comment by szmarczak** [comment]
There's an example here: https://github.com/sindresorhus/got/blob/master/documentation/migration-guides.md#breaking-changes

**Comment by rifler** [comment]
> `afterResponse` hook is called **after** serialization, so you need to set `responseType` to `text` and do the parsing in the hook.

Thanks. It is called after in v10, not v9

**Comment by rifler** [comment]
> > is it ok to return not response object from afterResponse hook?
> 
> No. You can use something like [lukechilds/responselike](https://github.com/lukechilds/responselike)

I understand that there is an options `resolveBodyOnly` in v10, which is ideal for case2. Thanks!

**Comment by rifler** [comment]
> There's an example here: [/documentation/migration-guides.md@`master`#breaking-changes](https://github.com/sindresorhus/got/blob/master/documentation/migration-guides.md#breaking-changes) [](/sindresorhus/got/blob/HEAD@{2020-03-10T19:36:41Z}/documentation/migration-guides.md#breaking-changes)

I don't understand, why it important to set `options.responseType = 'text';`, because body is already parsed on line 84 https://github.com/sindresorhus/got/blob/master/source/as-promise.ts#L84

and hooks run on 97 - https://github.com/sindresorhus/got/blob/master/source/as-promise.ts#L97

**Comment by szmarczak** [comment]
You're right. That example does not work with Got 10. Can you make a **bug** issue about it?
