### ISSUE TITLE
[Documentation] logic error in ˋcontextˋ sample code

### ISSUE THREAD

**Issue by PopGoesTheWza** [sindresorhus/got#1112]
#### Describe the bug

 - Node.js version: n.a.
 - OS & version: n.a.

In ˋREADME.mdˋ where the ˋcontextˋ option is described, sample code seems to have a logic error:

ˋˋˋjs
if (!options.context && !options.context.token) {
	throw new Error('Token required');
}
ˋˋˋ

Here !A && !B should be either !(A && B) or !A || !B.

Perhaps ˋ!options?.context?.tokenˋ would be valid too but awkward in the context of simple sample code.

#### Actual behavior

n.a.

#### Expected behavior

n.a.

#### Code to reproduce

Using Typescript, the code below is obviously wrong with the second term having the type ˋneverˋ

```js
if (!options.context && !options.context.token) {
	throw new Error('Token required');
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Good catch!
