### ISSUE TITLE
How to correctly type an instance returned by `got.extend`

### ISSUE THREAD

**Issue by jogold** [sindresorhus/got#1117]
#### What would you like to discuss?

Given the following client:

```ts
const jsonClient = got.extend({
  responseType: 'json',
  resolveBodyOnly: true
});
```

Doing:
```ts
const response = await jsonClient('https://httpbin.org/json');
```
hints TypeScript to believe that `response` is of type `Response<string>` while it should be `unknown`.

How can I correctly type `jsonClient` to take into account my options?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
For now you need to cast it manually.

**Comment by chinesedfan** [comment]
In theory, it can be achieved by [conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types). See examples like https://github.com/sindresorhus/pify/pull/76.

@szmarczak If you agree with this kind of mechanism, I can send a PR to handle `options.resolveBodyOnly`.

**Comment by Maxpain177** [comment]
Any news about this?

**Comment by ejmartin504** [comment]
I agree that the typing should be correct here, using conditional types as @chinesedfan mentioned. I'd like to point out one workaround for this _specific_ instance of `got.extend`, which my team used quite effectively in our project to get better typing: use `.json`

From the docs:
```
// This
const body = await got(url).json();

// is semantically the same as this
const body = await got(url, {responseType: 'json', resolveBodyOnly: true}); 
```

**Comment by TkaczykAdam** [comment]
I am a newbie in the TS world, I didn't want to type it as any. For a quick workaround, I just add the redundant `.json()`
@szmarczak please let us know when it will be fixed or provide an example of how to do it correctly :smiley:

**Comment by metelliandrea** [comment]
As workaround I put my response in a const and cast it to any (I guess a custom interface works too), in you case:

```javascript
const jsonClient = got.extend({
  responseType: 'json',
  resolveBodyOnly: true
});

const response = await jsonClient('https://httpbin.org/json');
const data = response as any;

// other stuffs
```

Hope it help! :)
