### ISSUE TITLE
Example Implementation in TypeScript

### ISSUE THREAD

**Issue by blubberbo** [sindresorhus/got#1119]
Hello,

Great package - is there an example of this being implemented in a TypeScript project? It seems all the examples are implementing it in JS. `const got = require('got');` for instance doesn't seem very TypeScriptey.

Thank you!

**Comment by sindresorhus** [comment]
You can easily translate the require statement to TypeScript yourself. Are there any other things you're struggling with regarding using Got with TypeScript?

**Comment by blubberbo** [comment]
> You can easily translate the require statement to TypeScript yourself. Are there any other things you're struggling with regarding using Got with TypeScript?

The following issue is sending me for a wild ride as well: https://github.com/sindresorhus/got/issues/1118
