### ISSUE TITLE
Got throws an error on a redirect response while followRedirect = false

### ISSUE THREAD

**Issue by NinoFloris** [sindresorhus/got#1123]
#### Describe the bug

 - Node.js version: node 13
 - OS & version: macOS catalina

#### Actual behavior

Got throws an error on a redirect response while followRedirect = false.

These POST requests originate on a client (browser), we expect to pass this request and have the client handle the response (redirect), which is why followRedirect = false.

#### Expected behavior

Got should not try to interpret any responses if followRedirect = false, this prevents us from proxying POST requests. Expected is no thrown errors

#### Code to reproduce

```ts
import got from 'got';
import stream from 'stream';
import { promisify } from 'util';
import * as express from "express";

const pipeline = promisify(stream.pipeline);

export default async (req: express.Request, res: express.Response) => {
    await pipeline(req, got.stream(req.originalUrl.substring(1), {
        method: req.method as Method,
        headers: { Host: req.hostname },
        followRedirect: false
    }), res);
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by NinoFloris** [comment]
Workaround seems to be 
```
throwHttpErrors: false,
```

But I believe this to be a hammer that's a bit too big, am I wrong?

**Comment by szmarczak** [comment]
Please fill out the issue template unless you want to get this issue closed.

**Comment by NinoFloris** [comment]
Updated, apologies

**Comment by szmarczak** [comment]
I still don't know how to reproduce the issue :| Could you set up a RunKit example please?

**Comment by NinoFloris** [comment]
I'm not sure, what's the easiest way to setup server and client in the same sample?

**Comment by szmarczak** [comment]
Got is the client here, right? So you need to set up a server. Then in the `listen` callback you make the requests.
