### ISSUE TITLE
got actually need nodejs >= 10.9, not >= 10

### ISSUE THREAD

**Issue by MythRen** [sindresorhus/got#1130]
#### Describe the bug

 - Node.js version: 10.2
 - OS & version: MacOS

got actually need nodejs >= 10.9, not >= 10

the request function prototype used in GOT was appeared in NodeJS 10.9:

https://github.com/sindresorhus/got/blob/master/source/request-as-event-emitter.ts#L246

https://nodejs.org/docs/latest-v10.x/api/http.html#http_http_request_options_callback

![image](https://user-images.githubusercontent.com/5511286/77408072-1b8d9c00-6df2-11ea-85e9-e72b0a9b0c8c.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
It's expected that users upgrade patch versions of a Node.js minor version. Without doing so, you're leaving yourself unpatched to lots of security issues.

Relevant: https://github.com/sindresorhus/meta/issues/8

We'll bump the version in package.json to `>=10.19` *(or newer)* when we do the next major version of Got.
