### ISSUE TITLE
Properly handle charset encoding for non buffer responseType

### ISSUE THREAD

**Issue by fengkx** [sindresorhus/got#1132]
#### What problem are you trying to solve?
When we request to a non utf8 endpoint with `repsoneType` text. It always treated as utf8.

For example
```js
const got = require("got")
;(async () => {
    const resp = await got('https://www.163.com/'); // www.163.com is using gbk
    console.log(resp.body);
})()
```
We got a `resp.body` using wrong encoding.

#### Describe the feature
For many cases we can only know the charset after we got a response.(Or at least response header)
I create a wrapper using [handlers in got](https://github.com/sindresorhus/got/blob/master/documentation/lets-make-a-plugin.md)

https://github.com/fengkx/got-iconv

Maybe can decode it correctly by embed `iconv-lite`. Or we can let user to set response encoding on `text` method if we already know the charset.

I also found `needle` handle encoding automatically using `iconv-lite`
https://github.com/tomas/needle/blob/6959db6b68f9e23e6a556dd918901f7b83f5184d/lib/decoder.js
...

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
This is a very rare use case and I don't think it's worth adding 340KB to the package size.

@sindresorhus I think the best option here would be to include `got-iconv` in the `Related` section.

**Comment by sindresorhus** [comment]
This is too much of an edge-case for Got to handle. You can easily solve this in a hook or wrap Got like you've done.
