### ISSUE TITLE
TypeScript returns an error regarding PCancelable within got source code

### ISSUE THREAD

**Issue by pawelgalazka** [sindresorhus/got#1135]
#### Describe the bug

 - Node.js version: v12.13.1
 - OS & version: macOS High Sierra 10.13.4
- `got` version `10.7.0` 
- `typescript` version `3.8.3`

`tsconfig.json` within the project:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*"
      ]
    },
    "lib": [
      "es2017",
      "esnext.asynciterable"
    ]
  },
  "include": [
    "src/**/*",
    "tests/**/*"
  ]
}
```

After running type check through command `npx tsc --noEmit --pretty`, I get an error within `got` source:

```
node_modules/got/dist/source/types.d.ts:205:83 - error TS2709: Cannot use namespace 'PCancelable' as a type.

205 export interface CancelableRequest<T extends Response | Response['body']> extends PCancelable<T>, GotEvents<CancelableRequest<T>> {
```

#### Actual behavior

`npx tsc --noEmit --pretty` returns errors within `got` source code

#### Expected behavior

`npx tsc --noEmit --pretty` should not return errors within `got` source code

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got. (latest node.js lts checked)

**Comment by szmarczak** [comment]
1. Your TypeScript config is very very outdated.
2. Please set up a reproducible repository. I cannot reproduce otherwise.

**Comment by szmarczak** [comment]
@pawelgalazka Friendly ping :) Can you try out [11.0.0-beta.1](https://github.com/sindresorhus/got/releases/tag/v11.0.0-beta.1)?

**Comment by szmarczak** [comment]
> Your TypeScript config is very very outdated.

I mean the target. Got targets ES2018.

**Comment by szmarczak** [comment]
Closing due to the lack of response.
