### ISSUE TITLE
Errors  have undefined body when using streams

### ISSUE THREAD

**Issue by adityapatadia** [sindresorhus/got#1138]
#### Describe the bug

 - Node.js version: 12.6.1
 - OS & version: Macos 10.14

#### Actual behavior
When `isStream: true` is set and request results in HTTPError, the stream emits `error` event. The emit handler is only called with `error` argument and `body` and `response` arguments are `undefined`.

...

#### Expected behavior
As per the [docs](https://github.com/sindresorhus/got#onerror-error-body-response), the `body` and `response` arguments should be set with `error` event.
...

#### Code to reproduce

```js
const got = require('got');

let stream = got("https://www.google.com/non-existant-path", {
  isStream: true,
  method: "GET",
  headers: {}
});

stream.on("response", (response) => {
  console.log(response.headers);
  console.log(response.statusCode)
});

stream.on("error", (err, body, response) => {
  // err is set
  console.log(err);

  // body should have been set but it's undefined
  console.log(body);

  // response should have been set but it's undefined.
  console.log(response);
});

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
This has been also fixed in #1051

**Comment by szmarczak** [comment]
You need to access the response via `error.response`, the docs are outdated

**Comment by adityapatadia** [comment]
Is this going to be consistent in future versions? Or is it going to change in #1051 ?

**Comment by szmarczak** [comment]
I don't know exactly what do you mean, but this issue is fixed in #1051.

**Comment by adityapatadia** [comment]
I meant currently `err.response` works. My question is will the function be `.on("error", (err, body, response)= {})` or it will be `.on("error", (err)= {})` ? Are you going to update the docs with the existing functionality or you are going to give functionality as per current docs?

I am asking because if it's going to change, we will also need to change code.

**Comment by szmarczak** [comment]
`.on('error', error => { ... })`

**Comment by adityapatadia** [comment]
Cool. I will disregard the docs then. I am doing coding as per `err.response` now.

**Comment by adityapatadia** [comment]
Btw, I found another bug. Even if `decompress:true` is passed, the error response is not decompressed if it's a `gzip` from the server. Should I report that one?

**Comment by szmarczak** [comment]
yes, it'd be best to include some reproducible code

**Comment by adityapatadia** [comment]
Opened #1142
