### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by tsjensen** [sindresorhus/got#1139]
#### Versions

- Node.js version: v12.16.1
- OS & version: Windows 10 (64bit)
- Webpack version: 4.42.1
- *got* version: 10.7.0

#### Actual behavior

When using *got* with Webpack, the Webpack process outputs the following WARNING:
```
WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/cacheable-lookup/index.js
 @ ./node_modules/got/dist/source/normalize-arguments.js
 @ ./node_modules/got/dist/source/create.js
 @ ./node_modules/got/dist/source/index.js
 @ ./src/foo.js
```

#### Expected behavior

The expected behavior is not to see warnings in a Webpack run (unless I caused them).

#### Code to reproduce

To reproduce:

- unpack the [attached project](https://github.com/sindresorhus/got/files/4401727/got-issue.zip)
- `npm install`
- `npm run webpack`

The source code of the project is simply the code snippet from the *got* readme, and *got* is the only production dependency in the demo project.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

Thanks for looking into this! If there is anything I can do on my side to work around the problem, or to help you fix it for good, please advise.

**Comment by sindresorhus** [comment]
The warning is caused by `keyv`. You should open an issue there instead.

**Comment by tsjensen** [comment]
Ok - sorry for not noticing this. 😇

Someone else already did: lukechilds/keyv#45  
The recommendation was to "close your eyes when the warning appears".

Will have to drop the components then. 😢
