### ISSUE TITLE
confusing documentation: the term ‘request’ is overloaded

### ISSUE THREAD

**Issue by danielweck** [sindresorhus/got#1144]
#### What would you like to discuss?

in the documentation, the term ‘request’ is overloaded (it confusingly refers to both the ‘request’ function parameter of the ‘createServer’ callback, and the ‘request’ deprecated lib):

https://github.com/sindresorhus/got/blob/master/documentation/migration-guides.md#more-about-streams

‘’’
http.createServer((request, response) => {
	if (request.url === '/doodle.png') {
		request.pipe(request('https://example.com/doodle.png')).pipe(response);
	}
});
‘’’

Suggestion: rename the ‘request’ and ‘response’ callback params to shorthand ‘req’ and ‘res’, leaving ‘request(URL)’ as is.

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/commit/b11f2d7c110ee929562542aa4578c69c780e5828
