### ISSUE TITLE
Converting from request library to got library -> Request with header 

### ISSUE THREAD

**Issue by CalvinTp** [sindresorhus/got#1145]
#### What would you like to discuss?

I am currently using request with header such as below: 

      request.get( {
          url : apiUrl,
          json: true,
          headers : {
              "Authorization" : authTokenCombined
          }
        }, function(error, response, body) {

What is the equivalent for got library? 

#### Checklist

- [ ] I have read the documentation.

**Comment by sindresorhus** [comment]
We have a migration guide here: https://github.com/sindresorhus/got/blob/master/documentation/migration-guides.md
