### ISSUE TITLE
How to search for Got info on the web

### ISSUE THREAD

**Issue by gilles-leblanc** [sindresorhus/got#1146]
#### What would you like to discuss?

I keep running into issues but I can't find anything online because searching for Got doesn't yield anything. On StackOverflow, the [got] tag is for something else and there is no [gotjs] tag.

Searching through DuckDuckGo or Google is a pain since Got is such a common word. 

What is the best way to search for questions regarding the Got library ? For example "got jwt token".

#### Checklist

- [ ] I have read the documentation.

**Comment by sindresorhus** [comment]
Maybe use `got node.js` before the search word.
