### ISSUE TITLE
GotError: Hostname/IP does not match certificate's altnames: Host: example.com. is not in the cert's altnames

### ISSUE THREAD

**Issue by skyfolderio** [sindresorhus/got#1147]
#### What would you like to discuss?
I'm trying to POST a file to `content.dropboxapi.com` and am getting the error `Hostname/IP does not match certificate's altnames: Host: example.com. is not in the cert's altnames` where `example.com is the hostname of my own server. I'm on Node 13.12 and Got version 10.2.

When I manually change the request header for `host` to `content.dropboxapi.com`, the request works. Are there security implications to this change?

I tried this same request on Postman and it seems to work.

My request code looks something like this:

```javascript
import { pipeline } from "stream";
import fs from "fs";
import got from "got";

const readStream = fs.createReadStream("hello-world.txt")

const dropboxGot = got.extend({
  prefixUrl: "https://content.dropboxapi.com"
  responseType: "text",
  headers: {
    Authorization: "Bearer dfjaiods ... adsfnioa",
    "Content-Type": "application/octet-stream",
    // host: "content.dropboxapi.com"
    // When I add the `host` header, the request works.
  }
)

const writeStream = dropboxGot.stream.post("2/files/upload", {
  "Dropbox-API-Arg": "DROPBOX_ARGS...",
 })

pipeline(readStream, writeStream)
```

The full error message was:

GotError: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:content.dropboxapi.com, DNS:api-content-photos.dropbox.com, DNS:api-content-photos8.dropbox.com, DNS:api-content-photos7.dropbox.com, DNS:api-content-photos6.dropbox.com, DNS:api-content-photos5.dropbox.com, DNS:api-content-photos4.dropbox.com, DNS:api-content-photos3.dropbox.com, DNS:api-content-photos2.dropbox.com, DNS:api-content-photos1.dropbox.com, DNS:api-content-photos0.dropbox.com, DNS:content-photos.dropboxapi.com, DNS:api-content.dropbox.com, DNS:api-content9.dropbox.com, DNS:api-content8.dropbox.com, DNS:api-content7.dropbox.com, DNS:api-content6.dropbox.com, DNS:api-content5.dropbox.com, DNS:api-content4.dropbox.com, DNS:api-content3.dropbox.com, DNS:api-content2.dropbox.com, DNS:api-content1.dropbox.com, DNS:api-content0.dropbox.com, DNS:api-content-photos9.dropbox.com

...

#### Checklist

- [x] I have read the documentation.

**Comment by skyfolderio** [comment]
Not a Got issue.

**Comment by finwarman** [comment]
How did you resolve this in the end?

**Comment by skyfolderio** [comment]
I was trying to upload to `https://content.dropboxapi.com` and it showed the error above. I ended up using the SDK. However, if that wasn't available, I was going to manually set the host in my Got request to `content.dropboxapi.com` (see [code snippet above](https://github.com/sindresorhus/got/issues/1147#issue-596166727)). I don't understand why that works and why I would need to do that since `host` is a [forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) and shouldn't be altered.
