### ISSUE TITLE
Silently fails with rejectUnauthorized:false 

### ISSUE THREAD

**Issue by bezoerb** [sindresorhus/got#1148]
#### Describe the bug

 - Node.js version: v13.8.0
 - OS & version: macOS 10.14.6

When i set the `rejectUnauthorized` [request](https://nodejs.org/api/https.html#https_https_request_options_callback) option the script silently fails without error. 

#### Actual behavior

Running this script fails with the TLS error:
```
const got = require('got');
(async () => {
  try {
    const response = await got('https://fonts.googleapis.com/css?family=Merriweather:300,700,700itali', {
      rejectUnauthorized: true,
    });
    console.log('DONE');
  } catch (error) {
    console.error(error);
  }
})()
```
-> 
```
GotError: unable to verify the first certificate
    at onError (.../got/dist/source/request-as-event-emitter.js:139:29)
    at handleRequest (.../got/dist/source/request-as-event-emitter.js:172:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1475:34)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket._finishInit (_tls_wrap.js:918:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:688:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  name: 'RequestError'
}
```
when setting the `rejectUnauthorized` option to `true` the script just exits without any output.
This was working as expected in got@9 

#### Expected behavior

The response is returned 

#### Code to reproduce

See above ;)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
https://runkit.com/szmarczak/5e8ec73dff2d91001a42c188 it works
