### ISSUE TITLE
Convert tests to use the promise interface by default

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#115]
Except for a few tests that specifically tests the callback interface.

We can then use async functions, which are so nice:

```js
test('retry - timeout errors', async t => {
	t.is(await got(`${s.url}/knock-twice`, {timeout: 1000}), 'who`s there?');
});
```

More info: https://github.com/sindresorhus/ava#async-function-support

**Comment by floatdrop** [comment]
`xo` will be a kind of problem here - with `esnext` option it will forbid `var` statements in `index.js`, but without it `async` keyword in test is `Unexpected identifier`.

**Comment by sindresorhus** [comment]
Yeah, I'm planning on fixing that in the next XO release. For now we can just ignore the `test` folder.

**Comment by sindresorhus** [comment]
Awesome! :heart:
