### ISSUE TITLE
Not able to post buffer in body

### ISSUE THREAD

**Issue by roastedmonk** [sindresorhus/got#1151]
#### Describe the bug

 - Node.js version: v12.16.1
 - OS & version: Windows 10

#### Actual behavior

receiving server getting buffer in json format as req.body
Restify is the server used in the receiving end.

#### Expected behavior

req.body should be a instance of Buffer.
Restify is the server used in the receiving end.

tested with currently depricated request plugin it works fine, but GOT is having this issue.

#### Code to reproduce

```js

try {
		got(`http://myurl/api/users/user1`, {
			method: 'PUT',
			body: fs.readFileSync('c:\\test.zip')
		});
	} catch(err) {
		throw `Remote update failed : ${err}`;
        }
```

#### Checklist

- [x] I have tried my code with the latest version of Node.js and Got.
- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Can you set up a RunKit example?

**Comment by szmarczak** [comment]
Or a reproducible repo?

**Comment by roastedmonk** [comment]
[GOT.zip](https://github.com/sindresorhus/got/files/4455825/GOT.zip)

Attached the sample code for the same.

Both server & got client code.

**Comment by szmarczak** [comment]
Your example is incomplete therefore I'm not able to reproduce the issue.

**Comment by szmarczak** [comment]
I've written a simple test that proves it works as expected: 442be0c78b63b3a1795a74a205be9693fcbeddf6

**Comment by szmarczak** [comment]
I'll close this issue for housekeeping purposes. Feel free to send a reproducible code so I'll open this issue again. It'd be best if you used plain Node.js HTTP server instead of Restify as I'm not familiar with it.

**Comment by roastedmonk** [comment]
i raised issue for Buffer not stream.
@szmarczak

**Comment by szmarczak** [comment]
> i raised issue for Buffer not stream.

The body? It's a `Readable` stream in your example, so I followed it.

**Comment by roastedmonk** [comment]
> > i raised issue for Buffer not stream.
> 
> The body? It's a `Readable` stream in your example, so I followed it.

![image](https://user-images.githubusercontent.com/29171405/79073338-9d8f2780-7d03-11ea-8a4f-ffc19758e38e.png)
![image](https://user-images.githubusercontent.com/29171405/79073393-e810a400-7d03-11ea-9fd8-6bb9b0ccf0c5.png)

**Comment by szmarczak** [comment]
oh sorry my bad looking into this rn

**Comment by szmarczak** [comment]
It works as expected and we have a test for that:

https://github.com/sindresorhus/got/blob/bf0b0cde07b6b65b18601aa3f43f976f4150c1f2/test/post.ts#L53-L58

**Comment by roastedmonk** [comment]
i dont want `wow` in response, it should be buffer of wow in server.

**Comment by szmarczak** [comment]
> it should be buffer of wow in server

That's not a Got issue. You are responsible for parsing the data.

**Comment by szmarczak** [comment]
Feel free to experiment around our tests. In that test we just output the received body, so it works as expected.
