### ISSUE TITLE
Move @types/* dependencies to devDependencies

### ISSUE THREAD

**Issue by Congelli501** [sindresorhus/got#1152]
#### What problem are you trying to solve?

Reduce got dependencies size for production

#### Describe the feature

Unless there is something I'm missing here, it seams those dependencies can be moved to devDependencies:

```
"@types/cacheable-request": "^6.0.1",
"@types/keyv": "3.1.1",
"@types/responselike": "1.0.0"
```

For example, `@types/cacheable-request` needs `@types/node` which weight over 800kb.

**Comment by sindresorhus** [comment]
Those types definitions needs to be dependencies as they're used by the generated TypeScript definitions of Got.

**Comment by sindresorhus** [comment]
> For example, @types/cacheable-request needs @types/node which weight over 800kb.

This is indeed a bug. You should open an issue on https://github.com/DefinitelyTyped/DefinitelyTyped It should not depend on `@types/node` directly, but rather have it as an optional peer dependency.
