### ISSUE TITLE
Cannot set property ip of #<IncomingMessage> which has only a getter

### ISSUE THREAD

**Issue by trendchaser4u** [sindresorhus/got#1157]
#### Describe the bug

 - Node.js version: 10.16.3
 - OS & version: Windows 10

#### Actual behavior

Executing the below code should console response body 

```js
(async () => {
    try {
      const response = await got('https://sindresorhus.com');
      console.log(response.body);
      //=> '<!doctype html> ...'
    } catch (error) {
      console.log(error);
      //=> 'Internal server error ...'
    }
  })();
```

...

#### Expected behavior

But throwing below error

![image](https://user-images.githubusercontent.com/8087340/79196599-fe2a7b80-7e4d-11ea-9bb5-548d6883cc2a.png)

...

#### Code to reproduce

```js
const got = require('got');

(async () => {
    try {
      const response = await got('https://sindresorhus.com');
      console.log(response.body);
      //=> '<!doctype html> ...'
    } catch (error) {
      console.log(error);
      //=> 'Internal server error ...'
    }
  })();

```

#### Checklist

- [ x] I have read the documentation.
- [ x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Can you update your Node.js version to the latest v10.x version? To rule out it’s not an already fixed Node.js issue.

**Comment by szmarczak** [comment]
Also please try out the newest Got release (`11.0.0-beta.1`).

**Comment by trendchaser4u** [comment]
> Can you update your Node.js version to the latest v10.x version? To rule out it’s not an already fixed Node.js issue.

yes, I've updated the node version, still, error occurs. This type of error will come only in strict mode.

![image](https://user-images.githubusercontent.com/8087340/79218520-304bd580-7e6e-11ea-92af-ceac50142ed6.png)

**Comment by trendchaser4u** [comment]
> Also please try out the newest Got release (`11.0.0-beta.1`).

Sure will try this version and let you know the result. :)

**Comment by szmarczak** [comment]
Glad to hear this. You must've used a custom `IncomingMessage` instance since Node.js doesn't define the `ip` property.

**Comment by NiteshKumar-BDev** [comment]
I am stuck same issue how can solve this 
node-> 22.12.0
npm-> 10.9.0
express-mongo-sanitize->2.2.0
