### ISSUE TITLE
v11 feedback: streams are not async iterable

### ISSUE THREAD

**Issue by darksabrefr** [sindresorhus/got#1159]
It seems v11 streams are a little bit broken when used with async iteration:
```javascript
'use strict';
const got = require('got');
(async () =>  #{
	const timeout = setTimeout(() => {}, 10000);
	try {
		const streamResponse = got.stream('https://sindresorhus.com');

		for await (const chunk of streamResponse) {
			console.log('chunk from streamResponse');
		}
		console.log('end');
	} finally {
		clearInterval(timeout);
	}
})();
```
This doesn't output anything. Note there is no error, where in a situation of a non-implemented async iterator should throw a TypeError saying "streamResponse is not async iterable" (you can add `streamResponse[Symbol.asyncIterator] = undefined;` to show that).

Now, a functional version (I used node's streams Readable.wrap for simplicity but implementing the right Symbol.asyncIterator is surely better):
```javascript
'use strict';
const got = require('got');
const {Readable} = require('stream');
(async () => {
	const timeout = setTimeout(() => {}, 10000);
	try {
		const gotStreamResponse = got.stream('https://sindresorhus.com');
		const streamResponse = new Readable().wrap(gotStreamResponse);

		for await (const chunk of streamResponse) {
			console.log('chunk from streamResponse');
		}
		console.log('end');
	} finally {
		clearInterval(timeout);
	}
})();
```
This one outputs results:
```
chunk from streamResponse
chunk from streamResponse
end
```
Link it to #1154

**Comment by szmarczak** [comment]
Fixed in e97cf7edeb3c4e543e28ac6da51f9bc359068e47
