### ISSUE TITLE
5.0.0 ✨

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#116]
Hey! We are about to release new major version!

These changes are already in:

- 0109725b7406e8b7005a4a435a0617179b1dc2da Reject promise on internal exception
- df26918b3d39ac803ecc5020c92e5a7d8c3d88b3 Catch callbacks in stream mode
- f9f2807e63635432ab175824859caa70e3c583aa Reduce size for browserify
- 066e6125e0c5da942650e67bd9b920c949718704 Remove `response` event on `error` (in stream mode) (#110)
- 62ff082deb41e711ae29c9e09ce173eef04390d6 Catch `auth` option passed in `url` string (#106)
- 6c59ce8b346e3171e9388c18d78ccc5f38a96c8e Add retries on network errors (#98)
- 9ffbbdf5aba98892519282ad7799a991c0b04483 Deferred `response` event

Is there something, that should be added or changed before release happens?

//cc @sindresorhus @kevva @julien-f @vdemedes

**Comment by sindresorhus** [comment]
Looks good. Can't think of anything else. `got` is now pretty much feature complete in my view.

**Comment by vdemedes** [comment]
👍!
