### ISSUE TITLE
Passing stream from multer upload to object storage

### ISSUE THREAD

**Issue by dangxquang** [sindresorhus/got#1174]
#### What would you like to discuss?
I have an objects storage which working fine with the code below
``` ES6
const form = new FormData()
form.append('bucket', bucket || 'tmp')
form.append('file', fs.createReadStream(file.path))
const responseFile = await got.post('http://domain.com/v1/objects', { body: form })
```
I want to write a `/uploads` route which accept `.csv` file using multer storage engine.
When a file is being uploaded from client, multer custom storage engine will parse `file.stream`
with `csv-parser` package, then go through a `Transform` to validate each row and count the total number of rows. 
File will be uploading to object storage using `got` without stored as a temp in disk/memory. 
If any rows are invalid, `Transform` will throw an error and stop all stream.
``` ES6
const csvParser = csv()
pipeline(
    file.stream,
    csvParser,
    rowsTransform,
    gotPostStream,
    (err) => {}
)
```
What I'm trying to do is that passing the stream to the form-data, then post to the object storage but I'm stuck at the got stream.
Any idea how to pipe the data?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Sorry for late response. Before you `pipeline`, can you attach this piece of code:

```js
rowsTransform.once('end', () => {
	console.log('rowsTransform ended');
});
```

and confirm whether 'rowsTransform ended' is displayed?

**Comment by szmarczak** [comment]
Closing due to a lack of response.
