### ISSUE TITLE
On Windows, library cannot stat hosts file if located on drive other than C:

### ISSUE THREAD

**Issue by ahuggins-nhs** [sindresorhus/got#1176]
#### Describe the bug

 - Node.js version: 12
 - OS & version: Azure Function App running on Windows Server 2016

When making http requests using this library, the etc/hosts file cannot be found on the C: drive; it is on the D: drive. For whatever reason, this library is using the wrong path when attempting to resolve dns names.

#### Actual behavior

```
Exception: RequestError: ENOENT: no such file or directory, stat 'C:\Windows\System32\drivers\etc\hosts' partners.wayfair.com:443
Stack: RequestError: ENOENT: no such file or directory, stat 'C:\Windows\System32\drivers\etc\hosts' partners.wayfair.com:443
    at ClientRequest.request.once (D:\home\site\wwwroot\node_modules\got\dist\source\core\index.js:759:25)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.origin.emit.args (D:\home\site\wwwroot\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### Expected behavior

Successful http request when resolving dns names

#### Code to reproduce

```js
// Any request on a Windows environment where C: drive is not the OS root.
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
> For whatever reason

The C: drive is the default Windows installation. I'm not sure if Node.js has an API to check this, but I'll look at it.

**Comment by szmarczak** [comment]
As I see it there should be an env var called `SystemDrive`.

**Comment by ahuggins-nhs** [comment]
@szmarczak Did I file this in the correct area? Taking a deeper look through the code looks like this is actually a problem with cacheable-lookup. I'm forking and should have a pull request some time this morning.

**Comment by ahuggins-nhs** [comment]
@szmarczak Pull request submitted to that repo. https://github.com/szmarczak/cacheable-lookup/pull/14

Hopefully this can be resolved on the sooner side. LEt me know if I can help in any way to get this fic upstream.

**Comment by ahuggins-nhs** [comment]
Intermediate fix for others who may stumble across this issue:
```js
const got = require('got')
const CacheableLookup = require('cacheable-lookup')
const instance = got.extend({
  dnsCache: new CacheableLookup({
    customHostsPath: process.env.SystemDrive + '\\Windows\\System32\\drivers\\etc\\hosts' })
  })
})
```

**Comment by szmarczak** [comment]
Fixed in https://github.com/szmarczak/cacheable-lookup/pull/14 I'll do a release tomorrow
