### ISSUE TITLE
Modify response headers when using streams as part of express middlware

### ISSUE THREAD

**Issue by cookch10** [sindresorhus/got#1179]
#### What would you like to discuss?
Hi @szmarczak,

I was looking through the issue list, and #669 looked a lot like what I am trying to accomplish, which is to use this package as part of an express server middleware.

I need to make requests to resources on external domains, and then serve that back up within my local server with the response headers from the external domain modified.

I have this working for the most part, with one caveat.  That is, I am not sure how I can modify the response header before it's piped to the middleware response when using streams (the hook that I think I would need to use would be the afterResponse hook. which is not available with streams).

In the example you gave in #669 , I was curious about this line:
```js
req.pipe(stream).pipe(res);
```

Can the got stream be piped into the request?

I've tried your example from #669 , but this yields a 400 (bad request) server error.  

This is my current setup which works, but does not currently allow modifying the response headers from the got request:
```js
  app.get('/external', (req, res, next) => {
    const stream = require('stream');

    const { CookieJar } = require('tough-cookie');

    const { promisify } = require('util');

    const got = require('got');

    const pipeline = promisify(stream.pipeline);

    const jar = new CookieJar();

    const setCookie = promisify(jar.setCookie.bind(jar));

    const { search } = req._parsedUrl;

    const searchUrl = search ? search : '';

    const uri = `https://www.external.com${req.path}${searchUrl}`;

    const gotInstance = got.extend({
      hooks: {
        beforeRequest: [
          options => {
            console.log(options);
          }
        ]
      }
    });

    try {
      pipeline(gotInstance.stream(uri, { decompress: false, cookieJar: jar }), res);
    } catch (error) {
      next();
    }
  });
```

I've been struggling with this one, so any insight you may have would be appreciated.
...

#### Checklist

- [ x] I have read the documentation.

**Comment by szmarczak** [comment]
I haven't read the issue yet but by looking at the title only I can suggest this:

```js
gotStream.on('response', response => {
	response.headers.yourOwnHeader = 'itsValue';
});
```

**Comment by cookch10** [comment]
Thanks @szmarczak, this helped!

**Comment by Kikobeats** [comment]
@szmarczak do you know how to prevent copy headers from the original request?

I tried

```js
gotStream.on('response', response => {
	response.headers = {}
});
```

```js
gotStream.on('response', response => {
	delete response.headers
});
```

without success 🤔

**Comment by szmarczak** [comment]
```
gotStream.on('response', response => {
	response.headers = {}
});
```

this works for me. If it doesn't work you please open an issue.
