### ISSUE TITLE
Correct way to modify the got.stream response

### ISSUE THREAD

**Issue by cookch10** [sindresorhus/got#1184]
#### What would you like to discuss?
I am using got as part of express server middleware to request external resources.  In some cases, I need to be able to modify the response body before passing it on.  I am using got.stream to request the response, and am piping that on to express.

I was able to get this working by using a Transform stream, however, when piping to the transform stream, all the http attributes are lost in translation (internally I believe there's a check in the call to .pipe to express to see if the incoming data is of ServerResponse / IncomingMessage type).  Any suggestions on how to maintain the ServerResponse / IncomingMessage typing while still being able to modify the content?

Here's what I have thus far:
```js
app.get('/external', (req, res, next) => {
  const uri = 'https://www.external.com/';

  gotInstance.stream(uri, { decompress: false })
    .on('error', (/* error */) => {
      next();
    })
    .pipe(new TransformStream({
      replacementFunc: (value) => {
        const replacementRegExp = /www\.external\.com/gim

        return value.replace(replacementRegExp, 'www.moocows.com');
      }
    }))
    .pipe(res);
});
```
TransformStream is a class instance which extends the node Transform stream and implements the methods for modifying the content.

...

#### Checklist

- [X ] I have read the documentation.

**Comment by cookch10** [comment]
I was able to get this working by adding an `on('response', (res2) => {...})` callback, and in that callback, copying the headers from res2 to res.

**Comment by szmarczak** [comment]
The best way to do this is normally just use a promise, and then replace things on the entire body. Then you need to set the response headers manually. Because the first chunk may be `www.e` and the other `xternal.com`.

**Comment by cookch10** [comment]
Yes @szmarczak , I am piping the chunks into a stream and then performing the transform on the entirety of the content for this very reason.
