### ISSUE TITLE
How to get the response body from a stream?

### ISSUE THREAD

**Issue by PierBover** [sindresorhus/got#1185]
#### What would you like to discuss?

How do we get the `response.body` when using `got.stream` ?

```
got.stream.put(options).on('response', (response) => {
  console.log(response.body); // returns undefined
});
```

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
This is a Node.js basic question. Google "how to read a readable stream in Node.js"

**Comment by PierBover** [comment]
I finally got it:

```
const body = [];

got.stream.put(options)
.on('end', () => {
    console.log(Buffer.concat(body).toString());
})
.on('data', (chunk) => {
    body.push(chunk);
});
```

**Comment by sindresorhus** [comment]
You could use https://github.com/sindresorhus/get-stream to simplify that.

**Comment by PierBover** [comment]
Thanks @sindresorhus it was easier than I thought.

I was just confused by the `response` event. :P

**Comment by szmarczak** [comment]
The `response` gives the **raw** response, and in 99% you don't need it unless you want to modify its properties.

**Comment by szmarczak** [comment]
Also you should not read directly from it: https://github.com/sindresorhus/got/issues/223#issuecomment-405076226
