### ISSUE TITLE
allowGetBody payload is dropped by .paginate()

### ISSUE THREAD

**Issue by PopGoesTheWza** [sindresorhus/got#1186]
this is a spinoff of #1171 

 - Node.js version: 12.16.1
 - OS & version: latest MacOQ

since got@11.0.0, `.paginate()` no longer send the body (json payload) of an `allowGetBody` query

#### Actual behavior

the json payload (a filter expression) is not sent to the server which returns the whole set of records

#### Expected behavior

Like in got@10.x the server should only return the records matching the filter (i.e. the json payload)

#### Code to reproduce

I have two simple allowGetBody test cases. In order to run, `test/helpers/with-server.ts` needs to be changed in lines 16-20:

```typescript
	const server = await createTestServer({
		bodyParser: {
			// type: () => false
		}
	}) as ExtendedTestServer;
```

This enable the bodyParser middleware to properly populate `request.body`. Because I do not fathom the possible impact of above change, I won't issue a PR.

First a simple and successful test

```typescript
test('allowGetBody sends json payload', withServer, async (t, server, got) => {
	server.get('/', (request, response) => {
		if (request.body.hello !== 'world') {
			response.statusCode = 400;
		}

		response.end();
	});

	const {statusCode} = await got({
		allowGetBody: true,
		json: {hello: 'world'},
		retry: 0,
		throwHttpErrors: false
	});
	t.is(statusCode, 200);
});
```

Now with .paginate() (it fails)

```typescript
test('allowGetBody sends json payload with .paginate()', withServer, async (t, server, got) => {
	server.get('/', (request, response) => {
		if (request.body.hello !== 'world') {
			response.statusCode = 400;
		}

		response.end(JSON.stringify([1, 2, 3]));
	});

	const iterator = got.paginate({
		allowGetBody: true,
		json: {hello: 'world'},
		retry: 0
	});

	const result = await iterator.next();

	t.is(result.value, 1);
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Good news: I have located the source of the bug

**Comment by PopGoesTheWza** [comment]
About time! ;)

Thanks a lot.

**Comment by szmarczak** [comment]
It was a typo in the code :P
