### ISSUE TITLE
 Duplicate base searchParams with a URL with pre-existing querystring

### ISSUE THREAD

**Issue by alexghr** [sindresorhus/got#1188]
#### Describe the bug

 - Node.js version: 14.0.0
 - OS & version: Ubuntu 18.04 (WSL)
- got: 11.0.2

When using an extended `got` instance, with default `searchParams` and using a URL with a querystring, `got` will duplicate the default parameters and overwrite the URL's querystring.

#### Actual behaviour

See test code below, documentation says that passing in a `searchParams` option will overwrite the `url`'s querystring but in this case `got` overwrites _and_ duplicates parameters.

#### Expected behaviour

According to [docs] `got` should delete the `url`s querystring and overwrite it with the `searchParams` option.

#### Code to reproduce

```js
const got = require('got').extend({
  searchParams: new URLSearchParams({ foo: '123' }),
  // simple hook to print the final URL
  hooks: {
    beforeRequest: [
      ({ url }) => console.log('url %s', url)
    ]
  }
});

(async () => {
  await got('https://example.com?bar=456'); // https://example.com/?foo=123&foo=123
  await got(new URL('https://example.com?bar=456')); // https://example.com/?foo=123&foo=123

  await got('https://example.com', { searchParams: new URLSearchParams({ bar: '456' }) }); // https://example.com/?bar=456&foo=123
  await got(new URL('https://example.com'), { searchParams: new URLSearchParams({ bar: '456' }) }); // https://example.com/?bar=456&foo=123
})()
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

[docs]: https://github.com/sindresorhus/got#searchparams

**Comment by szmarczak** [comment]
```js
  await got('https://example.com', { searchParams: new URLSearchParams({ bar: '456' }) }); // https://example.com/?bar=456&foo=123
  await got(new URL('https://example.com'), { searchParams: new URLSearchParams({ bar: '456' }) }); // https://example.com/?bar=456&foo=123
```

[The last two examples are perfectly valid.](https://github.com/sindresorhus/got#gotmergeoptionsparentoptions-newoptions)

**Comment by szmarczak** [comment]
Please note that in the first two you define `options.searchParams` through the defauts, so the URLs will be `https://example.com/?foo=123` in both cases. To bypass this, simply pass `searchParams` as `undefined` precisely.
