### ISSUE TITLE
Retry intermittent errors only

### ISSUE THREAD

**Issue by jonasfj** [sindresorhus/got#119]
Retrying connection errors mindlessly isn't great. Not entirely sure this list is complete, but I've had a lot of luck with it:
```js
var TRANSIENT_HTTP_ERROR_CODES = [
  'ETIMEDOUT',
  'ECONNRESET',
  'EADDRINUSE',
  'ESOCKETTIMEDOUT',
  // One could argue against retrying ECONNREFUSED,
  // but this often happens if a remote service is restarting (or temporarily crashed)
  'ECONNREFUSED',
  'EPIPE'
];
```
Retring when encountering `ENOTFOUND` isn't useful (DNS resolution error)

Also if error code is 5xx retry is often the right thing. But that might something to specify as an option.

-----
I look at this module as something pretty neat for REST apis, where as many others don't have promise and retry support (and are much bigger)... So far liking what I see...

**Comment by floatdrop** [comment]
Thanks for feedback @jonasfj!

Retrying `ENOTFOUND` can be useful, when DNS server is failing (for example in cloud environment, when DNS is used in service resolution). Any way [we decided to not stick to the list](https://github.com/sindresorhus/got/pull/113#discussion_r42026313) of possible errors (because they can be even platfrom specific) and there is no definitive list of those.

> Also if error code is 5xx retry is often the right thing. But that might something to specify as an option.

You can wrap `got` (as [got-retry](http://npmjs.com/got-retry) does) and specify custom logic for responses with wrong status codes. This is recommended way - it allows you to tune logic all the ways you can imagine :)

Still we are open to discussion about retry functionality in got, because it could be improved, I think.

**Comment by techniq** [comment]
I've been struggling to find a way to perform a retry on 5xx errors when using `got.stream()`.  I tried using something like https://github.com/feross/multistream (which I'm using to stream paginated api calls),  but so far I keep running into issues.

Any ideas how I could wrap `got.stream` to retry a set number of attempts and then continue piping if say on the second attempt it was successfully?

The api I'm accessing returns 504 gateway timeouts regularly I'm trying to retry against.

**Comment by techniq** [comment]
I ended up coming up with this using highland.js (might be overkill but works)

```js
function retryStream(streamFunc, retries) {
  let stream = _((push, next) => {
    let attempt = 1;
    retries = retries || 3;

    (function loop() {
      // console.log('loop ' + attempt);

      if (attempt <= retries) {
        let streamPage = streamFunc()
          .on('error', (err) => {
            // console.log('error, retrying');
            attempt++;
            loop();
          })
          .on('response', () => {
            // console.log('success');
            streamPage.pipe(stream);
          })
      } else {
        push('Max attempts reached');
      }
    }());
  });

  return stream;
}
```

example usage (contrived example)
```js
  streamPageRetry(page, perPage, retries) {
    return retryStream(() => got.stream('http://localhost'), retries)
      .pipe(JSONStream.parse('data.*'))
  }
```

**Comment by floatdrop** [comment]
@techniq retrying streamed data is quite hard - because you can't resend already sent data from Stream (once it's gone - it is gone), unless you buffer it or part of it. So quick solution is to dump data into buffer (with [get-stream](https://github.com/sindresorhus/get-stream) for example) and use buffered data in `body` option.

**Comment by techniq** [comment]
@floatdrop In my case I'm streaming data down and not posting it up (if I'm understanding your comment correctly).  I was needing to retry a GET whenever it returned a 504 (Gateway Time-out) (for example).  Once it's successfully it then pipes it onward (to `JSONStream.parse`, etc).  What I posted above is working for me.

**Comment by floatdrop** [comment]
@techniq okay, now I get ya. Yes, your variant is quite close how it can be done now, but I would go with `PassThrough` stream inside:

```js
var got = require('got');
var PassThrough = require('readable-stream').PassThrough;

function streamRetry() {
	var through = new PassThrough();
	var trys = 0;

	function request() {
		if (trys++ > 5) {
			through.emit('error', 'Max retries reached');
			return;
		}

		var stream = got.stream('localhost:8000')
			.on('error', request)
			.on('response', function () {
				stream.pipe(through);
			});
	}

	request();

	return through;
}
```

**Comment by techniq** [comment]
Looks good, thanks

**Comment by floatdrop** [comment]
@jonasfj since we now have `retries` as function, this issue can be solved just by passing `err` to `retries`  function here - https://github.com/sindresorhus/got/blob/master/index.js#L59

**Comment by jonasfj** [comment]
Yeah, passing `err` as an argument to `retries` would be nice...

Also allowing `retries` to just return `true/false` in case someone doesn't want to reimplement the backoff logic.
It should be possible to support both `true/false` and number, as numbers can be treated differently.

**Comment by floatdrop** [comment]
@jonasfj you can return `true`/`false` values - in first case request will be retried in next frame, in second it will not be retried.
