### ISSUE TITLE
document: make an HTTP request over TLS and disable server certificate verification 

### ISSUE THREAD

**Issue by jgehrcke** [sindresorhus/got#1191]
For controlled environments like test suites one wants to be able to make the HTTP client do communication over TLS but instruct it to _not_ perform server certificate verification.

Looks like currently this can be done with
```
got('https://local.dev', { rejectUnauthorized: false });
```
see https://github.com/sindresorhus/got/issues/477#issuecomment-582450042.

I think this (or something like this) should be an official/documented part of the API. At least discussed / easy to find in the documentation.

Thanks!

**Comment by sindresorhus** [comment]
I agree. We should add a section about this. It's a common use-case. We can add it after this section: https://github.com/sindresorhus/got#custom-endpoints

**Comment by Giotino** [comment]
On the same topic there's also `checkServerIdentity` which enables custom certificate validation (useful for certificate pinning).

```
await got("https://google.com", {
  checkServerIdentity: (hostname: string, certificate: DetailedPeerCertificate) => {
    return;
  }
});
// I'm not 100% sure on the "DetailedPeerCertificate" type
```

It works, but on the Node.JS I can't find any documentation applied to `http.Request`.

>The following additional options from tls.connect() are also accepted: ca, cert, ciphers, clientCertEngine, crl, dhparam, ecdhCurve, honorCipherOrder, key, passphrase, pfx, rejectUnauthorized, secureOptions, secureProtocol, servername, sessionIdContext, highWaterMark.

But, some lines after, there's an example with it...
"Example pinning on certificate fingerprint, or the public key (similar to pin-sha256):"

This is just a guess, but:
core/index.ts:118
```
export interface Options extends URLOptions, SecureContextOptions
```
maybe should extend something like `ConnectionOptions` (from `tls`) and not `SecureContextOptions`

**Comment by szmarczak** [comment]
> On the same topic there's also checkServerIdentity which enables custom certificate validation (useful for certificate pinning).

Can you send a PR for that? Thanks.

**Comment by szmarczak** [comment]
I'll open an issue for that.
