### ISSUE TITLE
Cache silently fails on particular URL

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/got#1193]
#### Describe the bug

 - Node.js version: 12.16.2
 - OS & version: Mac

#### Actual behavior
Using got to hit the Vue endpoint on UNPKG fails silently.

#### Expected behavior
For it to not silently fail.

#### Code to reproduce

```js
const got = require('got');

got('https://unpkg.com/vue@2.6.11/dist/vue.js', {
	cache: new Map(), // Removing this fixes it
}).then(console.log);
```

Interestingly, other endpoints work fine:
```js
got('https://unpkg.com/react', {
	cache: new Map(),
}).then(console.log);
```

Will be using `v10.7.0` for now.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
> Will be using v10.7.0 for now.

Are you saying that it works as expected on 10.7.0?

**Comment by privatenumber** [comment]
Yep

**Comment by szmarczak** [comment]
Found the bug

**Comment by privatenumber** [comment]
Thanks @szmarczak !!
