### ISSUE TITLE
got.stream is not a function and stream documentation

### ISSUE THREAD

**Issue by paazmaya** [sindresorhus/got#120]
The example for using `stream` mode seems to be a bit off.
The documentation mentions stream mode several times, but the configuration option does not seem to be documented.
Perhaps this can be made clearer?

**Comment by floatdrop** [comment]
There is no configuration option for Stream mode - you just call `.stream` method of got:

```js
// Stream mode
got.stream('todomvc.com').pipe(fs.createWriteStream('index.html'));

// For POST, PUT and PATCH methods got.stream returns a WritableStream
fs.createReadStream('index.html').pipe(got.stream.post('todomvc.com'));
```

And it should work (because [tests](https://github.com/sindresorhus/got/blob/master/test/stream.js#L53-L68) and stuff).

May be you are using old version of got?

**Comment by floatdrop** [comment]
Feel free to reopen, if this still a problem.
