### ISSUE TITLE
Proxy documentation is no longer correct for Got v11+

### ISSUE THREAD

**Issue by corford** [sindresorhus/got#1201]
With Got v11.0.0:
>The agent option now accepts only an object with http, https and http2 properties.

However, the documentation on proxies still mentions passing the `tunnel` package to the agent option.

Would be great to update this with information on the new recommended way to configure Got to proxy traffic (including HTTP/2.0) through a standard, non-h2 aware proxy server (more background here: https://github.com/szmarczak/http2-wrapper/issues/40)

**Comment by szmarczak** [comment]
Fixed in 16ff82f92a59ca63e8dbc468d40d9836def65f6a

**Comment by szmarczak** [comment]
> Would be great to update this with information on the new recommended way to configure Got to proxy traffic (including HTTP/2.0) through a standard, non-h2 aware proxy server

I found this: https://github.com/nxtedition/node-http2-proxy#readme but haven't tested it.

**Comment by corford** [comment]
That could be one way. Alternatively, to keep it all client side, the code to create a reusable (TLS) socket to a proxy is not too crazy: https://github.com/TooTallNate/node-https-proxy-agent/blob/master/src/agent.ts

Would be neat to be able to pass in a `createConnection()` (https://github.com/szmarczak/http2-wrapper/blob/master/examples/agent.js) function to Got that setup and returned a socket to the proxy. http2-wrapper could then perform ALPN protocol discovery over it and call the correct Agent.
