### ISSUE TITLE
URL search parameter mangled / modified by GOT

### ISSUE THREAD

**Issue by cookch10** [sindresorhus/got#1202]
#### Describe the bug

 - Node.js version: 12.13.1
 - OS & version: Windows 10 x64

When passing in a URL object (or string) to got, the path changes from what was originally passed in.

#### Actual behavior
Given the following url:
```js
const uri = new URL('https://www.external.com/path/morepath?someparam&&param=value&param2=value2&param3=value3&param4=value4&param5=value5&param6=');

gotInstance.stream(uri, {
})
  .on('error', (error) => {
    next();
  })
  .on('request', (req) => {
    // At this point, req.path now equals '/path/morepath?someparam=&param=value&param2=value2&param3=value3&param4=value4&param5=value5&param6='
  })
  .pipe(res);
```

The initial URL path is: `/path/morepath?someparam&&param=value&param2=value2&param3=value3&param4=value4&param5=value5&param6=`
  
After passing through got, the path becomes: `/path/morepath?someparam=&param=value&param2=value2&param3=value3&param4=value4&param5=value5&param6=`
...

#### Expected behavior
got should not be modifying the url I am passing in, as it causes the requested resource to respond with an error.  The endpoint (which I have no control over) is expecting the original url path and query string.
...

#### Code to reproduce
`see above`

I've created the following (hack) workaround by doing the following:
```js
const uri = new URL('https://www.external.com/path/morepath?someparam&&param=value&param2=value2&param3=value3&param4=value4&param5=value5&param6=');

const _search = uri.search;

Object.defineProperty(uri, 'search', {
  get() {
    return _search;
  },
  set() {
  }
});
```

As far as I can tell, this is happening due to the following code in `source/core/index.ts`:
https://github.com/sindresorhus/got/blob/429db406c6e55b0deac254004682cdddabfcddad/source/core/index.ts#L732

#### Checklist

- [X ] I have read the documentation.
- [ X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The behavior is correct. See https://github.com/nodejs/node/issues/33037

Got just triggers the normalization manually due to the bug mentioned above.
