### ISSUE TITLE
No response with http2 using Node.js 14

### ISSUE THREAD

**Issue by Allain55** [sindresorhus/got#1205]
#### Describe the bug

 - Node.js version: 14.0.0
 - OS & version: Ubuntu 14, 16, 18
 - got version: 11.0.2

#### Actual behavior
Running this code snippet does not log anything, the app exists.
It works using got 10.7 or Node 13.8.0 or removing "http2: true" or loading a file from the local environment
...

#### Expected behavior
This should log "got" to the console
...

#### Code to reproduce

```const got = require('got');

(async () => {
	await got(
		'https://unpkg.com/vue@2.6.11/dist/vue.js',
		{
			http2: true
		}
	)
	console.log('got');
})();
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Fixed https://github.com/szmarczak/http2-wrapper/releases/tag/v1.0.0-beta.4.5
