### ISSUE TITLE
Throw Http Error

### ISSUE THREAD

**Issue by navedmirCM** [sindresorhus/got#1210]
#### Throw Got HttpError 
I had testcases, which stub my function and return got http error. It used to work fine with got version "10.6.0" but doesn't work any more with current version 11.0.3.

My stub used to return the below httperror

`new got.HTTPError(
         { statusCode: 401, statusMessage: 'Unauthorized' }
        )`

It still throws an error, but the problem is error.response is undefined.
I was reading  `error.response.statusCode` but response body is undefined for new got version 11.0.3
I saw there is new condition to check the request object `if (self instanceof Request) ` in RequestError class.

Is there a way to throw got httperrors.

Node version:- 12.16

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by PopGoesTheWza** [comment]
@navedmirCM I am pretty sure this issue is documented in the [v11.0.0 release notes](https://github.com/sindresorhus/got/releases/tag/v11.0.0)

**Comment by szmarczak** [comment]
Well that sounds like a bug. Can you provide some reproducible code so I can look at what's failing?

**Comment by navedmirCM** [comment]
The code below is similar to my mocha test case, where I am using sinon to stub a function to make it return got HttpError
```
 let sandbox = sinon.createSandbox(); 
 let listStub = sandbox.stub(someModule, 'list');

listStub.throws(new got.HTTPError(
          { statusCode: 401, statusMessage: 'Unauthorized' }
        ));
```
In other function I am checking for error statusCode and Message

```
const destructGotHttpErrorObject = errObj => {
  if (errObj instanceof (got.HTTPError)) {
    return { code: errObj.response.statusCode,
      error: errObj.response.statusMessage };
  }
  return errObj;
};
```
It works fine in version 10 but in version 11+, it throws an undefinded error where response is undefined.
`errObj.response.statusCode`
Can't read statusCode of undefined

**Comment by szmarczak** [comment]
I need a full reproducible example. Can you set up an example repo please?

**Comment by szmarczak** [comment]
The object you're passing through is not a Got Response. A workaround looks like:

```js
const response = {statusCode: 401, statusMessage: 'Unauthorized'};
const error = new got.HTTPError(response);
error.response = response;
```

**Comment by navedmirCM** [comment]
Thanks @szmarczak

**Comment by nicoga97** [comment]
Have this been resolved? or we still need to do the @szmarczak workaround? thanks

**Comment by rbargholz** [comment]
Apologies for the thread necro.
@szmarczak's workaround won't work in a TypeScript file as `error.message` is readonly. Setting `response` with `Object.defineProperty` allowed me to adapt the workaround for a TypeScript file.
