### ISSUE TITLE
Note that 304 doesn't throw `HTTPError`

### ISSUE THREAD

**Issue by arty-name** [sindresorhus/got#1213]
#### What would you like to discuss?

The PR #252 updated `got` not to throw `HTTPErrors`. The ReadMe was updated that in case of 304 response status code the body would be empty. However the documentation on `HTTPError` still says that they are thrown for non-20x codes. 

I read the documentation on `HTTPError` and expected an exception for 304. It didn’t work this way. Would it make sense to update this part?

#### Checklist

- [x] I have read the documentation.

**Comment by AlSufyaniT1** [comment]
Please Help
