### ISSUE TITLE
rawBody inside beforeRetry

### ISSUE THREAD

**Issue by sayem314** [sindresorhus/got#1217]
#### What problem are you trying to solve?

My use case require access to request body for parsing tokens.

#### Describe the feature

I need access to `rawBody` on `beforeRetry` hooks before retrying using custom logic.

#### Checklist

- [ x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
> I need access to rawBody on beforeRetry hooks before retrying using custom logic.

Simple answer: you don't. You're looking for `error.response.body`, note that all errors will have a body.

**Comment by sayem314** [comment]
@szmarczak I have tried that and the response body is undefined for error 503. The server is returning body tho.

**Comment by geminigeek** [comment]
this issue is correct error.response.body is missing in beforeRetry !!

**Comment by szmarczak** [comment]
> this issue is correct error.response.body is missing in beforeRetry !!

How am I supposed to believe you? I need some proof.

**Comment by geminigeek** [comment]
> > this issue is correct error.response.body is missing in beforeRetry !!
> 
> How am I supposed to believe you? I need some proof.

hi ,

i guess you have acknowledged this here https://github.com/sindresorhus/got/issues/1423

thanks
