### ISSUE TITLE
Is there a template or guidelines to publish Got plugins?

### ISSUE THREAD

**Issue by PopGoesTheWza** [sindresorhus/got#1218]
#### What would you like to discuss?

> I will likely contribute a got template for Sugar CRM.

Is there a template or guidelines to publish Got plugins?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/master/documentation/lets-make-a-plugin.md but it hasn't been updated in three months

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/master/documentation/advanced-creation.md is a bit outdated too

**Comment by szmarczak** [comment]
> publish Got plugins?

You mean publishing or writing?

**Comment by szmarczak** [comment]
If the first one, then @sindresorhus knows best.

**Comment by PopGoesTheWza** [comment]
Sorry for I should have been more specific with my question. I am confident about creating a github repos, setting up enough files to publish an npm package and such. ;)

My question was more if there was key function/interface/naming convention to implement, mandatory link to this repos and praise in your name... that kind of guidelines... ;)

**Comment by szmarczak** [comment]
Here's an example: https://github.com/sindresorhus/gh-got/blob/master/readme.md

I think just link to Got and you'll be good.

**Comment by sindresorhus** [comment]
@PopGoesTheWza If you comment your plugin here when it's out, I'm happy to give it a review. And we could maybe add some tips to the readme based on that.
