### ISSUE TITLE
Zip file download works with curl, but not with got...?

### ISSUE THREAD

**Issue by lukehorvat** [sindresorhus/got#122]
I'm downloading a repo's zip file like so:

```javascript
var fs = require("fs");
var got = require("got");

got("https://codeload.github.com/sindresorhus/got/zip/master")
.then(res => {
  fs.writeFileSync("master.zip", res.body);
}).catch(err => {
  console.error(err);
});
```

It produces a `master.zip` archive that is seemingly corrupt and not openable. :disappointed: 

But it works via curl:

```bash
$ curl 'https://codeload.github.com/sindresorhus/got/zip/master' -o master.zip 
```

Any ideas?

**Comment by floatdrop** [comment]
Pass `{encoding: null}` to get raw Buffer from `got`.

**Comment by lukehorvat** [comment]
Thanks. :smile:

**Comment by binarymist** [comment]
Is this still the case? [This](Don't set this option to null) says Don't set this option to null
