### ISSUE TITLE
How to make POST call with JSON body  . Im getting RequestError: The `body`, `json` and `form` options are mutually exclusive

### ISSUE THREAD

**Issue by amitpareek1** [sindresorhus/got#1222]
#### What would you like to discuss?
How to make POST call with JSON body 
...

#### Checklist

- [x] I have read the documentation.
Yes

This is my code -
```js
var reqbody = paymentintentjson.config;
    var options = {
        
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "x-ibm-client-id": oAuthConfig.credentials.id,
            "x-ibm-client-secret": oAuthConfig.credentials.secret,
            "Authorization": accesstoken
        },
        
        json: true,
        body: reqbody
    };
    console.log("Options ---->>", options);
     var intentresponse = await got(paymentcalljson.payment.intent.url,options);
```

Below is the response Im getting - ------------------------------------

Options ---->> { method: 'POST',
  headers:
   { 'Content-Type': 'application/json',
     'x-ibm-client-id': 'xxxxxxx',
     'x-ibm-client-secret': 'yyyyyy',
     Authorization: 'Bearer xxxxx' },
  json: true,
  body:
   { Data: { Initiation: [Object] },
     Risk:
      { PaymentContextCode: 'Other',
        MerchantCategoryCode: '5967',
        MerchantCustomerIdentification: '053598653254',
        DeliveryAddress: [Object] } } }

(node:14284) UnhandledPromiseRejectionWarning: RequestError: The `body`, `json` and `form` options are mutually exclusive ..

Im not sure how body is going to be send .

If I do JSON.Stringyfy(reqbody)  ---- Backend returned with bad request error , as JSON stringyfy put 'reqbody'  quotes on request body .

**Comment by PopGoesTheWza** [comment]
@amitpareek1 try using only one of

- `json: {myPayload: 'as pure json'}`
- `body: JSON.stringify({myPayload: 'as pure json'})`

**Comment by szmarczak** [comment]
You're are migrating from an old version of Got and didn't update your options.

https://github.com/sindresorhus/got/releases/tag/v10.0.0
https://github.com/sindresorhus/got/releases/tag/v11.0.0

**Comment by amitpareek1** [comment]
> @amitpareek1 try using only one of
> 
> * `json: reqbody`
> * `body: JSON.stringify(reqbody)`

Thanks it worked ...
