### ISSUE TITLE
Regression handling multiple request errors

### ISSUE THREAD

**Issue by mastermatt** [sindresorhus/got#1224]
#### Describe the bug

 - Node.js version: 10, 12, 14
 - OS & version: macOS 10.15.4

Starting with v11.0, emitting more than one error on the `ClientRequest` causes an unhandled error event.

#### Code to reproduce

```js
got('http://example.com')
  .on('request', req => {
    req.once('socket', () => {
      req.emit('error', new Error("foo bar 1"))
      req.emit('error', new Error("foo bar 2"))
    })
  })
  .catch(reason => {
    console.log('caught', reason.message)
  })
```

#### Actual behavior

```
    throw er; // Unhandled 'error' event
    ^

Error: foo bar 2
    ...
```

#### Expected behavior

Previous behavior was to reject the promise with the first error, but each subsequent error would still run through the beforeError hook and propagate the event.
Not sure if that is the _right_ behavior, but it probably is. 
Regardless, looking at the changelog, this new behavior seems to be an unintended change.

I'm sure @szmarczak will know off hand, but this seems to have been caused by the "Rewrite Got" aligning on using `request.once` instead of using `request.on` in request-as-event-emitter.ts.

One thing to note about the 'code to reproduce' above is that the errors are emitted between the `socket` and `response` events. This was identified because it broke Nock's test suite when upgrading to Got 11. https://github.com/nock/nock/issues/1992
Nock emits the "Nock: No match for request" error between those two events, Got then calls `abort` on the ClientRequest which emits a "socket hang up" error.
The same behavior can seen with the 'code to reproduce' by commented out the second call to `emit`. 

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
> Starting with v11.0, emitting more than one error on the ClientRequest causes an unhandled error event.

That is correct. Please note, that starting Node.js 14.0.0 the recommended approach to `req.destroy(...)` and not `req.emit('error', ...)`. Streams that have errored should be destroyed.

**Comment by szmarczak** [comment]
> this new behavior seems to be an unintended change

It is intended. It leads to more strict behavior. But you're right, it should've been mentioned in the changelog.

https://nodejs.org/api/stream.html#stream_event_error

**Comment by szmarczak** [comment]
Please see the following: https://github.com/nodejs/node/issues/32995#issuecomment-617899672

**Comment by mastermatt** [comment]
Thanks for the response.

For other folks coming here, the relevant bit of the docs linked above for [`stream.Writable` "error" event](https://nodejs.org/api/stream.html#stream_event_error):
> After 'error', no further events other than 'close' _should_ be emitted (including 'error' events).

----
This question might be better suited for the Node issue thread, but I'm hoping to pick @szmarczak brain.
If `destroy` is preferred over emitting an error on ClientRequest, why are conn reset errors emitted? ([example](https://github.com/nodejs/node/blob/v14.2.0/lib/_http_client.js#L437))

Because the following throws an uncaught error event, even in v14.
```js
const req = http.get("http://example.com")
req.on("socket", () => req.destroy())
```

**Comment by szmarczak** [comment]
> If destroy is preferred over emitting an error on ClientRequest, why are conn reset errors emitted?

Because the Node.js maintainers haven't fixed it yet / didn't have the time to do so. Note that it is a big project. You can find many bugs in Node.js, not only this. /cc @ronag

**Comment by ronag** [comment]
> If destroy is preferred over emitting an error on ClientRequest, why are conn reset errors emitted? (example )

Because Node as a lot of legacy code which is not trivial to re-write to use pragmatic streams. It should use `destroy(err)` but we haven't yet managed to refactor this part of the code. It is work in progress.

**Comment by ronag** [comment]
> Because the following throws an uncaught error event, even in v14.

Why is this strange?

**Comment by mastermatt** [comment]
I understand the work in progress, makes perfect sense. 

> That works as expected. Why is this strange?

With Node's current implementation, I agree that an uncaught error is expected. 
I just want to clarify that once the work in progress is finished, there won't be an uncaught error anymore. 
My understanding is that `req.destroy()` is the preferred way to end/stop a request without an error, however, currently (v14.2) calling `destroy` before the `response` event **implicitly** emits an error.

**Comment by ronag** [comment]
> My understanding is that req.destroy() is the preferred way to end/stop a request without an error,

You can't end/stop a request and be guaranteed to not receive an error.

**Comment by mastermatt** [comment]
> You can't end/stop a request and be guaranteed to not receive an error.

Understood. How do I end a request without causing an error?

**Comment by ronag** [comment]
> Understood. How do I end a request without causing an error?

`request.end()`, but that does not guarantee you won't get any error.

**Comment by mastermatt** [comment]
Sorry, I'm not worried about guaranteeing an error or multiple errors won't happen, nor if they're uncaught if they do happen. 
I also didn't mean to use `end` in this case, as `request.end()` will continue the request/response flow. 
I want to stop a request in its tracks (abort/kill/term) and not have the request emit an error for that action.

**Comment by ronag** [comment]
> I want to stop a request in its tracks (abort/kill/term) and not have the request emit an error for that action.

Not possible unfortunately.

**Comment by mastermatt** [comment]
Does the design of the work in progress (using `destroy` for the conn resets) allow for this to be possible? Or is the current behavior desired?

**Comment by ronag** [comment]
> Does the design of the work in progress (using destroy for the conn resets) allow for this to be possible? Or is the current behavior desired?

The current behavior is desired.

**Comment by mastermatt** [comment]
Thanks for your time @ronag
