### ISSUE TITLE
Cannot GET shortened http2 link

### ISSUE THREAD

**Issue by markb-trustifi** [sindresorhus/got#1225]
#### Describe the bug

 - Node.js version: v12.14.1
 - OS & version: MacOS 10.14

#### Actual behaviour
Returns error:
HTTPError: Response code 404 (Not Found)
    at PromisableRequest.<anonymous> (xxx/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
...

#### Expected behaviour
Return valid response with HTML in body.
The "request" library returns correct result.
...

#### Code to reproduce

```js
got.get('https://bit.ly/3dnGFTH', {http2: true}).then(res => {
            console.log(res)
        }, err => {
            console.error(err)
        });
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The same happens without `http2`. It redirects to these:

```
https://misiciowa.org/.mpp/service
https://misiciowa.org/.mpp/service/
https://misiciowa.org/.mpp/service/app/index
https://misiciowa.org/.mpp/service/app/signin
```

`curl` gives the same output: `curl https://bit.ly/3dnGFTH -L -I`

This is not a Got issue.

**Comment by markb-trustifi** [comment]
The fact is that the `request.js` gets this link correct.
Please try this command: `curl https://bit.ly/3dnGFTH -L -I -k --http2`.
If it fails, that means that the http2 is not installed on your PC.
