### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Ahmed-Maruf** [sindresorhus/got#1230]
Describe the bug

    Node.js version: v14.1.0
    OS & version: macOS clatina

When trying to make a call currentPath.startsWith(item.slug) in my pug file I got this error. 

Actual behavior
 TypeError: /Users/maruf/www/sites/storify/views/layout.pug:18
[💻]     16|             each item in h.menu
[💻]     17|               li.nav__item
[💻]   > 18|                 a.nav__link(href=item.slug, class=(currentPath.startsWith(item.slug) ? 'nav__link--active' : ''))
[💻]     19|                   != h.icon(item.icon)
[💻]     20|                   span #{item.title}
[💻]     21|           .nav__section.nav__section--search
[💻] 

Cannot read property 'startsWith' of undefined at eval (eval at wrap (/Users/maruf/www/sites/storify/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:44:92)

Expected behavior
Don't throw error

**Comment by sindresorhus** [comment]
Wrong repo.
