### ISSUE TITLE
Core bugs with got@10.x + got@11.x - may have issues with prior versions, tested on Node LTS stable v12.x

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/got#1232]
I receive errors such as:

```sh
node TimeoutOverflowWarning: X does not fit into a 32-bit signed integer.
```

As soon as I switch `got` with `superagent` in my application, the errors go away.

**Comment by niftylettuce** [comment]
Possibly related to #1227 and #1220

**Comment by szmarczak** [comment]
Can you run `node --trace-warnings file.js`?

**Comment by szmarczak** [comment]
Friendly ping.

**Comment by niftylettuce** [comment]
I'm not able to do so due to privacy issues, but as soon as I swapped out `got` with `superagent` (and left all options/endpoints/params the same) everything worked fine.

**Comment by niftylettuce** [comment]
Here was my usage with `got` @szmarczak that caused this error:

<https://github.com/forwardemail/free-email-forwarding/commit/a20cfe9b5ea6ce906850a49cde37ec0312872a1c>

**Comment by szmarczak** [comment]
Unfortunately, the information you've posted doesn't point at Got at all, therefore I'm unable to help you.

> I'm not able to do so due to privacy issues,

You cannot trace process warnings? Nonsense. There are no private information. If you are worried about stack traces, you can replace sensitive file names with random letters.

**Comment by niftylettuce** [comment]
> Unfortunately, the information you've posted doesn't point at Got at all, therefore I'm unable to help you.

Yes it does, look at the commit.

As soon as I swapped `got` with `superagent`, the problem went away.

https://github.com/forwardemail/free-email-forwarding/commit/a20cfe9b5ea6ce906850a49cde37ec0312872a1c#diff-168726dbe96b3ce427e7fedce31bb0bcL1013-L1019

**Comment by szmarczak** [comment]
> Yes it does, look at the commit.

But are there any stack traces pointing to Got? `node --trace-warnings file.js` would do it.

**Comment by niftylettuce** [comment]
I'd prefer not to test this in the production environment where it happened.  I can say that it's running `v12.16.1`.  I think this is due to retries or something.

**Comment by szmarczak** [comment]
If you experience it with Got 10 as well as with Got 11, then the only possibility of timeouts I can image of is [the retry mechanism](https://github.com/sindresorhus/got/blob/master/source/as-promise/calculate-retry-delay.ts) or the [`timed-out` module](https://github.com/sindresorhus/got/blob/master/source/core/utils/timed-out.ts). Since you don't pass the `timeout` option, the only possibility here is the retry mechanism. But that also requires a server to send a `Retry-After` header that would point to 49+ days to the future.

You can try setting the `retry` option to `0`. That would minimize the possibility of Got being faulty to 0% (I think).

> node TimeoutOverflowWarning: X does not fit into a 32-bit signed integer.

What is the number `X`?

**Comment by szmarczak** [comment]
Also you're using `parse-domain@2.3.4`, which uses `got@8.3.2`. Latest `parse-domain@3.0.2` uses `node-fetch@2.6.0`.

**Comment by niftylettuce** [comment]
The latest version of parse-domain has core underlying issues/poor
documentation (https://github.com/peerigon/parse-domain/issues/106), so I
can't upgrade that right now.  I'm just going to switch to use superagent
as time an time again I've experienced issues with got, and there are quite
a few open core bugs on Github with the package already.  I'm a veteran in
the community and appreciate your work here and patience, but I have to
switch.  The integer value was a very large number.

**Comment by szmarczak** [comment]
> I've experienced issues with got, and there are quite
a few open core bugs on Github with the package already. 

What issues? The only breaking bug is `cacheable-lookup@4.2.3`, but the DNS cache has been disabled by default `got@11.1.2`.  [v11.1.3](https://github.com/sindresorhus/got/releases/tag/v11.1.3) fixed all other core issues.

The only thing I can recommend is to upgrade to `got@11.1.3` and set the `retry` option to `0`.

If you aren't willing to do neither that or `node --trace-warnings`, then I cannot help you :|

**Comment by szmarczak** [comment]
The only issue I haven't handled yet is #1227
