### ISSUE TITLE
please update min semver version for cacheable-lookup

### ISSUE THREAD

**Issue by fluffynuts** [sindresorhus/got#1236]
Please see https://github.com/szmarczak/cacheable-lookup/issues/24

An issue fixed upstream can still present downstream. An install @latest and republish would be appreciated.

**Comment by szmarczak** [comment]
I'm going to release an update of `cacheable-lookup` today.

**Comment by szmarczak** [comment]
Released `11.1.2`, which disables `dnsCache` by default. As of now there are too many inconsistencies beetwen `cacheable.lookup` and `dns.lookup`. While it's indeed performant when making lots of requests to public hostnames, it makes no sense to have it while developing, as `dns.lookup` is executed as the fallback when `dns.resolve4` and `dns.resolve6` fail.

**Comment by cesarfd** [comment]
Hi, could we have a new Got release that supports cacheable-lookup 5 (currently in `master`)?

**Comment by szmarczak** [comment]
> Hi, could we have a new Got release that supports cacheable-lookup 5 (currently in master)?

I'll try to make a release today. I need to fix [`decompress-response`](https://github.com/sindresorhus/decompress-response) first.

**Comment by szmarczak** [comment]
Waiting to get this merged: https://github.com/sindresorhus/decompress-response/pull/27

**Comment by szmarczak** [comment]
Released `11.1.4` :tada:
