### ISSUE TITLE
Support getting content length from the HTTP source stream in a pipeline

### ISSUE THREAD

**Issue by mikedld** [sindresorhus/got#1237]
#### What problem are you trying to solve?

I want to be able to pipe from one HTTP stream to another and satisfy destination stream requirement of having`content-length` header present. Currently per documentation this header would not be set in this case since HTTP stream is not "a `string` / `Buffer` / `fs.createReadStream` instance / `form-data` instance".

#### Describe the feature

Since some (most?) HTTP streams would contain the `content-length` header in their response, it should be possible to copy it over into the destination request headers (unless already explicitly specified). I don't have a proposed syntax for this.

Below is a workaround that I've come up with. Not sure if it's the right thing to do but it seems to work.

```js
const pipeline = promisify(stream.pipeline);
const sleep = promisify(setTimeout);

let srcHeaders;

const src = got.stream('http://src/data', {
    decompress: false
});
src.on('response', (response) => {
    srcHeaders = response.headers;
});

const dst = got.stream.post('http://dst/data', {
    hooks: {
        beforeRequest: [
            async (options) => {
                while (!srcHeaders) {
                    await sleep(500);
                }
                options.headers['content-length'] = srcHeaders['content-length'];
            }
        ]
    }
});

await pipeline(src, dst);
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
You can use something like [`getStream`](https://github.com/sindresorhus/get-stream). Then it would look like this:

```js
const dst = got.stream.post('http://dst/data', {
    body: await getStream(src)
});
```
