### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by erfanium** [sindresorhus/got#1239]
#### What problem are you trying to solve?
Using got in Deno: https://github.com/denoland/deno

#### Describe the feature
On 13 may, Deno will release its 1.0.0 version. It's awesome to have this powerful package there as well

**Comment by sindresorhus** [comment]
I doubt we'll do this. Maybe in the future if Deno gets a good compatibility mode for Node.js, but Got depends on a lot of specific Node.js internals, so it would not be easy.

For Deno, I would recommend https://github.com/sindresorhus/ky instead, which should *just work*.

**Comment by sholladay** [comment]
If anyone does want to pursue making Got work on Deno, the best course of action would be to contribute to Deno's [std/node](https://github.com/denoland/deno/tree/master/std/node) library, which is a compatibility layer designed to provide the Node APIs that Got needs to run. It already has some of the required Node APIs, including `fs` and `events`, but it's missing others such as `net`, `http`, `tls`, and `stream`, for example. Most of the missing APIs should be relatively easy to add and also more approachable than modifying Got itself.
