### ISSUE TITLE
Socket hang up with parallel requests and maxSockets agent options with node >= 14.1.0

### ISSUE THREAD

**Issue by darksabrefr** [sindresorhus/got#1245]
#### Describe the bug

 - Node.js version: 14.1.0 and 14.2.0
 - OS & version: Ubuntu 19
 - Got: 11.1.3

Starting with node 14.1.0 (not 14.0.0), there's socket hang ups when doing parallel requests and limiting the sockets number with the `maxSockets` option from Agent class. If it could be a clue, I was incapable to reproduce this bug with an independent test including an http server on my localhost. Node's http/https libs are not affected but it's clear there's something related to a node change as the following example runs fine with node 14.0.0 but not above.

#### Code to reproduce

```js
'use strict';
const https = require('https');
const got = require('got');
(async () => {
	try {
		const promises = [];
		const options = {
			url: 'https://github.com',
			agent: {
				https: new https.Agent({ maxSockets: 1 })
			},
			retry: 0
		};

		for (let i = 0; i < 5; i++) {
			promises.push(
				got(options).then(() => {
					console.log('end');
				})
			);
		}

		await Promise.all(promises);
		console.log('all done');
	} catch (e) {
		console.log(e);
	}
})();
```

#### Node's native functional code
```js
'use strict';
const https = require('https');
(async () => {
	try {
		const promises = [];
		const options = {
			hostname: 'github.com',
			agent: new https.Agent({ maxSockets: 1, })
		};

		for (let i = 0; i < 5; i++) {
			promises.push(new Promise((resolve, reject) => {
				const req = https.request(options, (res) => {
					res.on('data', () => {});
					res.on('end', () => {
						console.log('end')
						resolve();
					});
					res.on('error', reject);
					req.on('error', reject);
				});
				req.end();
			}));

		}

		await Promise.all(promises);
		console.log('all done');
	} catch (e) {
		console.log(e);
	}
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
It doesn't matter if the `maxSockets` value is `4`, `3`, `2` or `1`. I think there's a race condition...

**Comment by szmarczak** [comment]
Got calls `request.destroy()` on cleanup unless `response.complete` is `true`. I don't know why it's `false`...

**Comment by szmarczak** [comment]
I think I've already been through this one... Ah, I knew it! https://github.com/sindresorhus/mimic-response/issues/5

**Comment by darksabrefr** [comment]
> It doesn't matter if the `maxSockets` value is `4`, `3`, `2` or `1` (as long as it's less than the actual amount of requests). ~I think there's a race condition...~ It fails even with `keepAlive` set to `true`...

Yes, the `maxSockets` value doesn't really matter, you only need to do more requests than this value (if you do more requests than this limit but with a close value, the bug is not always triggered).
`keepAlive` doesn't change anything, that's true too.

> I think I've already been through this one... Ah, I knew it! [sindresorhus/mimic-response#5](https://github.com/sindresorhus/mimic-response/issues/5)

I've seen that `IncomingMessage` properties are not defined by getters (https://github.com/nodejs/node/blob/master/lib/_http_incoming.js#L57-L64) and so you can't easily mimic them. But that's not the only problem here I think: there was a modification in node between 14.0.0 and 14.1.0 conducing to this issue because there is no bug when executing these minimal use cases in 14.0.0. There is certainly chances too this modification will break other things.
