### ISSUE TITLE
Unable to solve challenge

### ISSUE THREAD

**Issue by 0Franky** [sindresorhus/got#1250]
Hi,
I'm trying to get html from this site:
https://www.netfreex.club/
but I receive an error. It looks like the challenge can't be solved.

I can see through the html the challege `__cf_chl_jschl_tk__` , but this site:
https://ilgeniodellostreaming.tw/?s=casa+di+carta (accessible only by Italian IP)
use the same challenge, and here it works.

**Comment by Giotino** [comment]
```
try {
  const resp = await got.get("URL_HERE");
  console.log(resp.body);
} catch (e) {
  console.log(e.response.body);
}
```

With this test it fails with both URL (HTTP 503) and the body is the cloudflare challenge.

Maybe your IP has been temp banned from `www.netfreex.club`

**Comment by szmarczak** [comment]
This is not a Got issue.

**Comment by 0Franky** [comment]
No my IP isn't banned, there are no bans. I found out that the site applied an hCAPTCHA, but not always and not on browser.

**Comment by Giotino** [comment]
UNRELATED TO GOT

@0Franky 
https://support.cloudflare.com/hc/en-us/articles/200170056-Understanding-the-Cloudflare-Security-Level
https://support.cloudflare.com/hc/en-us/articles/360027519452-Understanding-Cloudflare-Bot-Management

**Comment by 0Franky** [comment]
Thank you @Giotino
