### ISSUE TITLE
Got RequestError when explicitly set responseType to undefined

### ISSUE THREAD

**Issue by nguyenlc1993** [sindresorhus/got#1252]
#### Describe the bug

 - Node.js version: v12.16.2
 - OS & version: Ubuntu 18.04

The project at my company uses [`got-fetch`](https://github.com/alexghr/got-fetch) library, which uses `got` as peer dependency to create fetch-like function. Starting with `got` v11.1.1, we encounter this error when using `got-fetch`:

```
RequestError: Unknown body type 'undefined' in "https://www.google.com/" in "https://www.google.com/"
    at Object.exports.parseBody (/home/nguyen/Desktop/got-test/node_modules/got/dist/source/as-promise/core.js:29:15)
    at PromisableRequest.<anonymous> (/home/nguyen/Desktop/got-test/node_modules/got/dist/source/as-promise/index.js:78:44)
    at Object.exports.parseBody (/home/nguyen/Desktop/got-test/node_modules/got/dist/source/as-promise/core.js:23:15)
    at PromisableRequest.<anonymous> (/home/nguyen/Desktop/got-test/node_modules/got/dist/source/as-promise/index.js:78:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
After investigating the source code, we found that `got-fetch` sets `responseType` to be `undefined` and parses the response body by itself.

[got-fetch/src/lib/fetch.ts:53](https://github.com/alexghr/got-fetch/blob/9a6bf179aa650aa5d50dc5ab39399d9678c0762d/src/lib/fetch.ts#L53)
```
    const gotOpts: GotOptions = {
      // url needs to be stringified to support UNIX domain sockets, and
      // For more info see https://github.com/alexghr/got-fetch/pull/8
      url: url.toString(),
      searchParams,
      followRedirect: true,
      throwHttpErrors: false,
      method: (request.method as any) || 'get',
      isStream: false,
      resolveBodyOnly: false,
      // we'll do our own response parsing in `GotFetchResponse`
      responseType: undefined
    };
```

When we run test code with `responseType` explicitly set to `undefined`, we also got the same behavior. This behavior does not happen in `got` v11.1.0 and before.

#### Actual behavior
Got throws `RequestError: Unknown body type 'undefined'`.

#### Expected behavior
Got throws no error and return response as normal.

#### Code to reproduce

```js
const got = require('got');

(async function() {
    const response = await got('https://www.google.com', {
        responseType: undefined,
    });
    console.log(response.body);
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
According to the documentation [responseType](https://github.com/sindresorhus/got#responsetype) should be a string (`'text'`, `'json'` or `'buffer'`).

This behavior is due the fact that `responseType` must be a string.

https://github.com/sindresorhus/got/blob/9770e540d088c35ec0b467fa3d2fafb60ed6797d/source/as-promise/core.ts#L23,L42

**Comment by nguyenlc1993** [comment]
> According to the documentation [responseType](https://github.com/sindresorhus/got#responsetype) must be a string (`'text'`, `'json'` or `'buffer'`).
> 
> That behavior is due to this code:
> https://github.com/sindresorhus/got/blob/9770e540d088c35ec0b467fa3d2fafb60ed6797d/source/as-promise/core.ts#L23,L42

Thank you, I know that `undefined` is not a valid value for `responseType`, and also know the code that caused the behavior. I just don't understand why this behavior did not happen in earlier versions, as well as why `responseType` not default to `text` when set to `undefined`.
The issue caused us not be able to update `got` to latest version, so I wonder if the old behavior can be restored.

**Comment by Giotino** [comment]
> I just don't understand why this behavior did not happen in earlier versions

In Got v10 there was this line after the merge
https://github.com/sindresorhus/got/blob/5c74084fe49fe69e3e12e059d6adf46def2af764/source/normalize-arguments.ts#L228
That took care of defaulting `responseType` to `'text'` event if it was overwritten by the user options as `undefined`.

> as well as why `responseType` not default to `text` when set to `undefined`.

This is because `responseType` , documentation wise, cannot be `undefined`.

I don't want to be rude but you where using it wrong, even the Got v10 documentation states that it must be
> Type: `string`

**Comment by szmarczak** [comment]
Options are optional, so when you pass anything as `undefined` it should not throw.
