### ISSUE TITLE
Send PUT request with content-length > 0 and empty payload

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#1258]
#### What problem are you trying to solve?

https://cloud.google.com/storage/docs/performing-resumable-uploads#upload-file

Google's resumable file upload protocol requires that you send PUT request with `content-length` equal to the total upload size and any (including empty) body.

The goal here is to upload file in chunks, such as in the case of https://github.com/gajus/express-tus.

#### Describe the feature

I should be able to make a request with `content-length` > 0 and empty body.

```js
await got('https://[..]', {
  headers: {
    'content-length': 100,
  },
  method: 'PUT',
});

```

Currently, this does not issue a HTTP request.

**Comment by Giotino** [comment]
`Content-Length` (if required and present) must be the size of the body of the request.
https://tools.ietf.org/html/rfc2616#section-14.13
https://tools.ietf.org/html/rfc7230#section-3.3.2

> Google's resumable file upload protocol requires that you send PUT request with content-length equal to the total upload size and any (including empty) body.

That's not true

In the case of GCP
```
You can resume the upload operation by sending a PUT Object request. The PUT Object request must have the following:
[...]
A Content-Length request header, which specifies the number of bytes you are uploading in the current request.
```

In the case of tus
```
The Upload-Length request and response header indicates the size of the entire upload in bytes. The value MUST be a non-negative integer.
```

**Comment by szmarczak** [comment]
> I should be able to make a request with content-length > 0 and empty body.

That's against the spec.

> Google's resumable file upload protocol requires that you send PUT request with content-length equal to the total upload size

No, that's the length of the current chunk. If you prefer to send the body in one chunk, then you should provide the total upload size. But you cannot have `content-length` that does not reflect the actual length of the chunk / file.

**Comment by gajus** [comment]
I will experiment further, though I did not manage to make it work so far.
