### ISSUE TITLE
ExperimentalWarning: The dns.promises API is experimental

### ISSUE THREAD

**Issue by s-KaiNet** [sindresorhus/got#1259]
#### Describe the bug

 - Node.js version: v10.13
 - OS & version: Win10 ver.2004

#### Actual behavior

Two warnings are printed into the console:
> (node:13060) ExperimentalWarning: The dns.promises API is experimental
(node:13060) ExperimentalWarning: The fs.promises API is experimental  

Nothing else is printed.
#### Expected behavior

Google page content is printed.

#### Code to reproduce

```js
const got = require('got');

(async () => {
	try {
		const response = await got('https://google.com');
		console.log(response.body);
	} catch (error) {
		console.log(error.response.body);
	}
})();
```

#### Additional info

When I `npm install got@10` everything works as expected. 

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Why people are using outdated Node.js versions? Please upgrade...
