### ISSUE TITLE
Supported nodejs version

### ISSUE THREAD

**Issue by s-KaiNet** [sindresorhus/got#1260]
#### What would you like to discuss?
Why do you guys do not support node 10.13, since it will be available till the 2021? I cannot upgrade to the latest node right now, because of dependency on other third-party things.  

Please don't close the issue without a way for the issue author to answer, since that's not the best way to communicate in OSS world. 

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> since it will be available till the 2021?

It will be always available. But Node.js 10.13 is not maintained anymore. Move on to 10.20.1 (Got requires at least 10.19.0).

> Please don't close the issue without a way for the issue author to answer, since that's not the best way to communicate in OSS world.

That's not a Got issue. It strictly relates to your project. This is a Got issue tracker, isn't it?

**Comment by szmarczak** [comment]
Duplicate of #1084
