### ISSUE TITLE
The types are missing `family` option

### ISSUE THREAD

**Issue by duongvanba** [sindresorhus/got#1263]
Hi, 
I want to use my local address v6 address but when i use "localAddress" property it show 
```typescript
import got from 'got'
got('https://api6.ipify.org', {
       localAddress: '2604:A880:0400:00D0:0000:0000:1832:C001'
})

// RequestError: bind EINVAL ... 

```
How to use my local ipv6 address
Thank you ?

**Comment by duongvanba** [comment]
I think i need to update types typescript for got

**Comment by Giotino** [comment]
@szmarczak I think this should be considered as a bug (or, at least, lack of documentation).

The problem here is that `api6.ipify.org` resolves to both IPv4 and IPv6. @duongvanba Your software throws `EINVAL` because it's trying to bind an IPv6 address for an IPv4 connection.
One workaound would be specifying `family: 6`, since it's passed down to the socket object underneath the request.
```typescript
got('https://api6.ipify.org', {
       localAddress: '2604:A880:0400:00D0:0000:0000:1832:C001',
       family: 6
})
```

Currently I can't verify the correctness of that solution (I don't have a public IPv6 and I don't have time to setup a local test workspace).
When using `family: 6` the error changes to `GotError: getaddrinfo ENOENT api6.ipify.org`, which seems a problem whit the resolve of the IPv6 (AAAA) record.

@szmarczak I think Got needs some documentation about how to force IPv6 in cases like this.

**Comment by Giotino** [comment]
After some trial and error I found out that by using also `hints: dns.V4MAPPED` it resolves correctly
```javascript
const dns = require("dns");
await got("https://api6.ipify.org", {
      family: 6,
      hints: dns.V4MAPPED,
      lookup: false,
      localAddress: "fd67:38d4:ab6c:1:29e6:2c72:f080:aaab"
});
```

But, to me, that make no sense.

Node.JS documentation
`dns.V4MAPPED: If the IPv6 family was specified, but no IPv6 addresses were found, then return IPv4 mapped IPv6 addresses.`

`api6.ipify.org` has IPv6 records...

**Comment by szmarczak** [comment]
> One workaound would be specifying family: 6, since it's passed down to the socket object underneath the request.

That's not a workaround. That's the required way to go.

> family <number> IP address family to use when resolving host or hostname. Valid values are 4 or 6. When unspecified, both IP v4 and v6 will be used.

v4 IP addresses are preffered above v6 IP addresses.

**Comment by szmarczak** [comment]
```
> dns.lookup('api6.ipify.org', {all: true, hints: dns.ADDRCONFIG}, console.log)
GetAddrInfoReqWrap {
  callback: [Function: bound consoleCall],
  family: 0,
  hostname: 'api6.ipify.org',
  oncomplete: [Function: onlookupall]
}
> null [
  { address: '108.171.202.203', family: 4 },
  { address: '108.171.202.195', family: 4 },
  { address: '108.171.202.211', family: 4 },
  { address: '2607:f2d8:4010:c::2', family: 6 },
  { address: '2607:f2d8:4010:8::2', family: 6 },
  { address: '2607:f2d8:4010:b::2', family: 6 }
```

See? `dns.lookup` by default picks the first element from the array.

**Comment by szmarczak** [comment]
So just passing `family: 6` should fix it.

**Comment by Giotino** [comment]
> That's not a workaround. That's the required way to go.

But on the Got side is undocumented.

> v4 IP addresses are preffered above v6 IP addresses.

I'm fine with this behaviour, but if you specify `family: 6` it fails:
`dns.lookup('api6.ipify.org', {all: true, family: 6, hints: dns.ADDRCONFIG}, console.log)`
```
Error: getaddrinfo ENOENT api6.ipify.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:74:26) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'api6.ipify.org'
}
```

**Comment by szmarczak** [comment]
> It could be due to the fact that I've no public IPv6, can you try it?

I don't have an IPv6 address. I'm running `miredo` on Linux (it's a tunnel).

```
> https.request('https://api6.ipify.org', {family: 6}, res => { res.on('data', chunk => console.log(chunk.toString())); }).end(); '';
''
> 2001:0:53aa:64c:ab:25fa:46c9:c76d
> require('.').get('https://api6.ipify.org', {family: 6}).text().then(console.log);
Promise { <pending> }
> 2001:0:53aa:64c:ab:25fa:46c9:c76d
```

As you can see everything works as expected. It's just missing types.

**Comment by szmarczak** [comment]
But yeah, the docs also need to be fixed.

**Comment by duongvanba** [comment]
I tested in my VPS, i think problem is typescript define, not from got
Thank you for quick response

**Comment by Giotino** [comment]
> I tested in my VPS, i think problem is typescript define, not from got
> Thank you for quick response

That's due to the fact that Got uses its custom options, and `family` is missing.
I'm trying to solve it there #1264
