### ISSUE TITLE
How to proxy HTTP/2 via a HTTP proxy using got

### ISSUE THREAD

**Issue by swang2019** [sindresorhus/got#1265]
tried to do :

            http2: tunnel.http(s)OverHttp({
                proxy: {
                    host: 'localhost',
                    port: 6767
                }
            }),

received runtime error: 

(node:60026) UnhandledPromiseRejectionWarning: RequestError: The "listener" argument must be of type function. Received an instance of Object

any ideas ?

**Comment by szmarczak** [comment]
The `http2` Agent is not the `http.Agent`. It's this: https://github.com/szmarczak/http2-wrapper/#new-http2agentoptions

I'm not sure how you can proxy it for now.

**Comment by swang2019** [comment]
> The `http2` Agent is not the `http.Agent`. It's this: https://github.com/szmarczak/http2-wrapper/#new-http2agentoptions
> 
> I'm not sure how you can proxy it for now.

that's sad. I need both http/2 and proxy to be functional, and I do not know how to do this...

**Comment by yovanoc** [comment]
I'm trying to do the same... @swang2019 did you find something?

**Comment by swang2019** [comment]
No. I still have no idea how to do this. 

发自我的iPhone

**Comment by SwiTool** [comment]
> Is HTTP/2 proxy support planned for the near future?
>
>Short answer:
>
>No, there are no plans.
>
>Long answer:
>
>There is almost no sense to implement it, as the main HTTP/2 benefit is that it allows multiplexing many requests within a single connection, thus [almost] removing the limit on number of simalteneous requests - and there is no such limit when talking to your own backends. Moreover, things may even become worse when using HTTP/2 to backends, due to single TCP connection being used instead of multiple ones.
>
>On the other hand, implementing HTTP/2 protocol and request multiplexing within a single connection in the upstream module will require major changes to the upstream module.
>
>Due to the above, there are no plans to implement HTTP/2 support in the upstream module, at least in the foreseeable future. If you still think that talking to backends via HTTP/2 is something needed - feel free to provide patches.

I don't know if it's reliable but i'll still link that

source: https://stackoverflow.com/a/41647983

**Comment by szmarczak** [comment]
https://github.com/szmarczak/http2-wrapper#proxy-support Make sure you're using `http2-wrapper@1.0.0-beta.5.2`

**Comment by swang2019** [comment]
> https://github.com/szmarczak/http2-wrapper#proxy-support Make sure you're using `http2-wrapper@1.0.0-beta.5.2`

fantastic job, thanks! though we switched node-libcurl before your solution is out.. will check in our next project.
