### ISSUE TITLE
How to ignore a HTTP error?

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#1268]
#### What would you like to discuss?

I have been searching the issues for a dozen minutes now, but I cannot find an option to suppress a specific error (and return the original response).

I have a HTTP response that returns 308 and this should be (in this case) treated as valid response, i.e. I don't want Got to throw an error.

I can use `throwHttpErrors`, but that requires that I handle myself all other error codes.

Is there a way to conditionally suppress an error?

**Comment by sindresorhus** [comment]
The `beforeError` hook?

**Comment by gajus** [comment]
Right, but what do I do with it?

It is not clear from the documentation how to suppress the error.

https://github.com/sindresorhus/got#hooksbeforeerror

I am having a strong deja vu. I am pretty sure I already had this conversation.

**Comment by szmarczak** [comment]
> I have a HTTP response that returns 308 and this should be (in this case) treated as valid response, i.e. I don't want Got to throw an error.

If you're using promises, then you can catch the error and access `error.response`.

**Comment by szmarczak** [comment]
Friendly ping.

**Comment by szmarczak** [comment]
> I have a HTTP response that returns 308 and this should be (in this case) treated as valid response, i.e. I don't want Got to throw an error.

It's a redirect. It doesn't throw. Can you send a reproducible example?

**Comment by szmarczak** [comment]
https://httpstatuses.com/308

**Comment by gajus** [comment]
I think that the solution that @szmarczak proposed is reasonable, i.e.

```js
let response;

try {
  response = await got(url);
} catch (error) {
  if (error.response.status === 308) {
    response = error.response;
  } else {
    throw error;
  }
}

```

still feels a bit hacky (this is regardless of whether 308 throws, but about how to tolerate certain error codes).
