### ISSUE TITLE
Callback never returned in browser

### ISSUE THREAD

**Issue by kevva** [sindresorhus/got#127]
Since https://github.com/sindresorhus/got/commit/9ffbbdf5aba98892519282ad7799a991c0b04483 the callback is never returned when using `got` in browsers. Removing the wrapping `setImmediate` fixes it.

```js
got(url).then(() => {
    console.log('foo');
    // never reached
});
```

At first I thought it had something to do with `setImmediate` not being supported in browsers (other than IE lol) but if I modify `got` and log something before `ee.emit(...)` I can see it being logged in the console, so yeah, don't know why the `response` event isn't getting emitted correctly.

```js
setImmediate(function () {
    console.log('foo');
    // this is being logged
    ee.emit('response', typeof unzipResponse === 'function' ? unzipResponse(res) : res);
});
```

**Comment by ncuillery** [comment]
+1

Same problem here :fire_engine:

**Comment by ThariqS** [comment]
also experiencing this

**Comment by floatdrop** [comment]
@ncuillery @ThariqS does `catch` callback outputs something to you?

```js
got(url).catch(err => console.log(err));
```

**Comment by ewnd9** [comment]
+1, I've tried either 
```
got('/api/v1/locations').then((res) => console.log(res)).catch((err) => console.log(err));
got('/api/v1/locations').then((res) => console.log(res), (err) => console.log(err));
```

Promise returned from `got` call always stays "pending", but I see in developer tools that actual http request was successfully completed. I am using `got` `v5.2.0` bundled with `webpack`

**Comment by floatdrop** [comment]
This code works fine with browserify (tested on `6.0.0`version):

```js
// Workaround for setImmediate
global.setImmediate = setTimeout;

const got = require('got');
got('/bundle.js')
    .then(res => {
        console.log(res.body.length);
    })
    .catch(err => {
        console.error(err);
    });
```

It could be, that Promise polyfil is broken in browsers.

**Comment by ewnd9** [comment]
Webpack build is still not working, but problem related to webpack's http polyfill, not got

### source

```
// index.js
const http = require('http');

const req = http.request({
  port: 8000,
  hostname: 'localhost',
  method: 'GET',
  path: '/bundle.js'
}, function(stream) {
  console.log(stream);
});

req.end();
```

### webpack

```js
// webpack.config.js
module.exports = {
	entry: "./index.js",
	output: {
		path: __dirname,
		filename: "bundle.js"
	}
};
```

`$ node_modules/.bin/webpack index.js`

![2016-01-15-174347_741x152_scrot](https://cloud.githubusercontent.com/assets/1713789/12350107/766e617e-bba7-11e5-87f6-a64dab56db34.png)

### browserify

`$ node_modules/.bin/browserify index.js > bundle.js`

![2016-01-15-174451_762x241_scrot](https://cloud.githubusercontent.com/assets/1713789/12350154/dd5d1132-bba7-11e5-87a3-79e6d04d7b14.png)
