### ISSUE TITLE
Socket hang up error occurs when redirected after submitting FormData

### ISSUE THREAD

**Issue by prfss** [sindresorhus/got#1271]
-   Got version: 11.3.1
-   Node.js version: 14.2.0 (12.16.3)
-   OS & version: Windows10 (Ubuntu 18.04 on WSL)

#### Code to reproduce

```ts
import got from "got";
import FormData from "form-data";

(async function f() {
    try {
        const body = new FormData();
        body.append("aaa", "bbb");
        const res = await got.post(`http://httpstat.us/302`, { body });
    } catch (err) {
        console.log(err);
    }
})();
```

```
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at TLSSocket.socketOnEnd (_http_client.js:453:23)
    at TLSSocket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
```

#### Additional info

Similar result is produced with the local flask server (no error message, simply get stucked)

```python
from flask import Flask, request, redirect, url_for
app = Flask(__name__)


@app.route('/', methods=["GET", "POST"])
def index():
    return "hello"


@app.route('/redirect', methods=["POST"])
def redirect_to_index():
    return redirect(url_for("index"))


if __name__ == '__main__':
    app.run(debug=True)
```

#### Checklist

-   [x] I have read the documentation.
-   [x] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
In the master branch it fails with
`GotError [HTTPError]: Response code 302 (Found)`

**Comment by Giotino** [comment]
This bug is due to the fact that `FormData` is a stream-like object.
It is read until the end for the first call. Then, when it comes the redirect, it's already at the end, so no body is transmitted (the server is waiting for it).

**Comment by Giotino** [comment]
@szmarczak
One solution could be calling `await this._finalizeBody();` right before sending the body and making the user change the body in the `beforeRedirect` (or `beforeRequest`) hook, but, to me, it seems a little tricky.

Another solution could be reading all the stream a single time and using it as a Buffer when making requests, but this is going to break the stream feature (big file are going to fill the RAM).

**Comment by szmarczak** [comment]
@Giotino is right. It is not a bug, it's the intended behavior. If you want to use method rewriting, please use [`get-stream`](https://github.com/sindresorhus/get-stream) and pass the output to the `body` option.

**Comment by prfss** [comment]
Thank you for your quick response. Giving `body: await getStream(body)` solves the problem.
By the way, how to remove the body (and re-calculate the headers) in the second request when `methodRewriting: false` or 303 is returned ?

**Comment by szmarczak** [comment]
> how to remove the body (and re-calculate the headers) in the second request when methodRewriting: false

What do you mean? The body is removed if you disable method rewriting.

**Comment by proton-ab** [comment]
Using `methodRewriting: false` does not seem to work for me, it still causes crash. Only setting `followRedirect: false` helped.

Perhaps the code still tries to read FormData but simply not sending it despite that?

**Comment by nyuszika7h** [comment]
I have the same issue. Using `get-stream` results in a HTTP 413 Request Entity Too Large error. However, curl is able to POST the same file without issues. Any ideas on how to fix this?

**Comment by Giotino** [comment]
> I have the same issue. Using `get-stream` results in a HTTP 413 Request Entity Too Large error. However, curl is able to POST the same file without issues. Any ideas on how to fix this?

When using `get-stream` on a form data are you also setting the boundary header?
