### ISSUE TITLE
parseJson option

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/got#1274]
As discussed there: https://github.com/sindresorhus/ky/issues/254#issuecomment-629613861

Option should allow to pass a user-function that will perform JSON parsing.

Use cases:

1. Use `bourne` to mitigate the hyped prototype pollution.
2. Parse JSON with `reviver`

Example API:

```typescript

type ParseJsonFunction = <OUTPUT = unknown>(text: string) => OUTPUT

const myGot = got.extend({
  parseJson: text => bourne(text),
})
```

Should be available both via `.extend()` and as an option to each request.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/releases/tag/v11.3.0
