### ISSUE TITLE
Retries on 404

### ISSUE THREAD

**Issue by yoavain-sundaysky** [sindresorhus/got#1277]
#### Describe the bug
I'm seeing retries on RC 404.
Using default statusCodes in the retry options.
Added a beforeRetry hook to log some info.

<details>
<summary>Error</summary>

```json
{
	"code": undefined,
	"name": "HTTPError",
	"message": "Response code 404 (Not Found)",
	"stack": "HTTPError: Response code 404 (Not Found)
		at PromisableRequest._onResponse (..\\node_modules\\got\\dist\\source\\core\\index.js:737:37)
		at ClientRequest.<anonymous> (..\\node_modules\\got\\dist\\source\\core\\index.js:779:18)
		at Object.onceWrapper (events.js:417:26)
		at ClientRequest.emit (events.js:322:22)
		at ClientRequest.EventEmitter.emit (domain.js:482:12)
		at ClientRequest.origin.emit (..\\node_modules\\@szmarczak\\http-timer\\dist\\source\\index.js:39:20)
		at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
		at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
		at TLSSocket.socketOnData (_http_client.js:469:22)
		at TLSSocket.emit (events.js:310:20)"
}
```
</details>

<details>
<summary>Response</summary>

```json
{
	"statusCode": 404,
	"statusMessage": "Not Found"
}
```
</details>

<details>
<summary>NormalizedOptions</summary>

```json
{
  "method": "GET",
  "retry": {
    "limit": 2,
    "methods": [
      "GET",
      "PUT",
      "HEAD",
      "DELETE",
      "OPTIONS",
      "TRACE"
    ],
    "statusCodes": [
      408,
      413,
      429,
      500,
      502,
      503,
      504,
      521,
      522,
      524
    ],
    "errorCodes": [
      "ETIMEDOUT",
      "ECONNRESET",
      "EADDRINUSE",
      "ECONNREFUSED",
      "EPIPE",
      "ENOTFOUND",
      "ENETUNREACH",
      "EAI_AGAIN"
    ],
    "maxRetryAfter": 2000
  },
  "headers": {
    "user-agent": "Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36",
    "accept": "application/json",
    "accept-encoding": "gzip, deflate, br"
  },
  "decompress": true,
  "throwHttpErrors": true,
  "followRedirect": true,
  "isStream": false,
  "responseType": "json",
  "resolveBodyOnly": false,
  "maxRedirects": 10,
  "prefixUrl": "",
  "methodRewriting": true,
  "ignoreInvalidCookies": false,
  "http2": false,
  "allowGetBody": false,
  "rejectUnauthorized": true,
  "pagination": {
    "countLimit": null,
    "requestLimit": 10000,
    "stackAllItems": true
  },
  "url": "https://........................................",
  "username": "",
  "password": "",
  "timeout": {
    "request": 2000
  }
}
```
</details>

According to docs, retry is only on:
statusCodes: 408 413 429 500 502 503 504 521 522 524
errorCodes: ETIMEDOUT ECONNRESET EADDRINUSE ECONNREFUSED EPIPE ENOTFOUND ENETUNREACH EAI_AGAIN

 - Node.js version: 12.x (latest)
 - OS & version: Windows 10
 - Got version: 11.1.4

#### Actual behavior
2 retries on RC 404
...

#### Expected behavior
No retries on RC 404 (unless overridden in options)
...

**Comment by yoavain-sundaysky** [comment]
Also, a question regarding a workaround:
Can I abort a request inside the beforeRetry hook?
```js
if (error.response.statusCode === 404) {
   // abort request?
}
```

**Comment by szmarczak** [comment]
> Can I abort a request inside the beforeRetry hook?

Just make it throw. Please include some reproducible code. The information you've provided doesn't mean anything right now. It can be an issue in your code as well.

**Comment by yoavain** [comment]
Trying to create a reproducible code, I think I found the problem. 
My code overrides the default calculateDelay function, and I guess I misinterpreted the purpose of this function.
All I wanted was to use an exponential backoff function with lower delays than the default. I didn't understand from documentation that once I override this function, I need to handle the entire logic. i.e. checking methods, error-codes & status codes. I understood it only from looking at the source code...

You can close this issue...

**Comment by szmarczak** [comment]
> All I wanted was to use an exponential backoff function with lower delays than the default. 

Then simply check if `computedValue` is truthy. If it is, then simply pass a non-zero value.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/a337dfdfc4151593044c8b729245308081a071be/source/index.ts#L41

Make it something like this:

```js
({computedValue}) => {
	if (computedValue) {
		return 100;
	}

	return 0;
}
```
