### ISSUE TITLE
Test in browser

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#128]
We need to test `got` in browser environment to prevent [regressions](https://github.com/sindresorhus/got/issues/127).

For example [saucelabs](https://saucelabs.com/u/shtylman-superagent) (like superagent does) or [browserling](https://www.browserling.com/), etc.

---

Nice guide - http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html

**Comment by floatdrop** [comment]
@kevva could you provide example of how you getting got into browser? Browserify?

**Comment by kevva** [comment]
Yup, using `got` in the browser is no biggie to setup. I think the worst part is getting the tests to run.

**Comment by AlexTes** [comment]
@floatdrop say one was able to get an automated browser test environment up and running. Browser launches, got is available to it. How would you run all the tests? AVA doesn't run in the browser last I checked 😞.

**Comment by sindresorhus** [comment]
Closing. People have `fetch`-based libs now that are better suited for the browser. Got's focus is Node.js.

**Comment by sholladay** [comment]
I like `fetch()`, but I haven't seen any higher-level libraries that I like.

If someone wants to collaborate on a `got`-like library for the browser, I'd be interested. In particular, I want:
 - Promise API, caching, redirect following, request cancellation (all easy thanks to `fetch()`)
 - Timeouts
 - Automatic retries
 - Errors with metadata
 - JSON mode

And maybe custom instances (`.create()`, `.extend()`)

**Comment by jleaders** [comment]
Could someone point me to these `fetch`-based libs that are as beautiful and simple to use as `got()`?
