### ISSUE TITLE
Got hangs if passed a stream which has already emitted 'open'

### ISSUE THREAD

**Issue by LinearSpoon** [sindresorhus/got#1280]
#### Describe the bug

 - Node.js version: 14.0.0
 - OS & version: Linux mint 19
 - got version: 11.1.4

Hi, I've got some code where a `fs.ReadStream` is created, and passed to Got some time later in an async callback. It seems Got will hang if the stream has already emitted the `open` event before being passed in. Any chance this can be fixed, or is this an unsupported scenario?

#### Code to reproduce

```js
const got = require('got');
const fs = require('fs');

const fstream = fs.createReadStream('test.txt');
fstream.once('open', async () => {
	// Prevent node from exiting early due to empty event loop.
	setTimeout(() => {}, 10000);

	console.log('Starting request...');
	const response = await got({
		url: 'https://www.google.com',
		method: 'POST',
		body: fstream,
	});
	// This is never executed.
	console.log(response.statusCode);
});
```
#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by kibertoad** [comment]
@LinearSpoon While there might be something that `got` could be doing better to handle scenarios like this, it seems like you are mixing callbacks and async functions, which may work in a way you might not expect.
This is a highly recommended viewing: https://www.youtube.com/watch?v=e3Nh350b6S4

**Comment by Giotino** [comment]
A temporary workaround could be using the [Stream API](https://github.com/sindresorhus/got#streams)
```js
const fstream = fs.createReadStream('test.txt');
fstream.once('open', async () => {
  // Prevent node from exiting early due to empty event loop.
  setTimeout(() => {}, 10000);

  console.log('Starting request...');
  const request = got.stream({
    url: 'https://www.google.com',
    method: 'POST',
    throwHttpErrors: false
  });
  fstream.pipe(request);

  const response = await new Promise(resolve => request.on('response', response =>  resolve(response)));
  console.log(response.statusCode);
});
```
