### ISSUE TITLE
Tunneling broken by 11.0.0 rewrite

### ISSUE THREAD

**Issue by joel-solymosi** [sindresorhus/got#1281]
#### Describe the bug

 - Node.js version: 12.14.1
 - OS & version: windows 10.0.18362.836

Before 11, tunneling worked by setting options.agent = tunnel.httpsOverHttp(opts);
In the documentation, this is marked as the official way to set up tunneled requests via got.
Upgraded to 11.1.4

#### Actual behavior
> TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`

#### Expected behavior
Tunneling to be accepted as options.agent parameter, or a working, non-global tunnel integration to be suggested by documentation.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
This is clearly covered in the release notes: https://github.com/sindresorhus/got/releases/tag/v11.0.0

**Comment by joel-solymosi** [comment]
Yep, you're right, thank you!
