### ISSUE TITLE
Timeout callback instead of an error

### ISSUE THREAD

**Issue by kibertoad** [sindresorhus/got#1288]
#### What problem are you trying to solve?

We have an SLA with external party which defines that they are to provide a response within 1 second timeframe. If there is no response, we have to interrupt the request and assume the default value. We do not consider that to be an error that needs to be handled but just one possible flow.

#### Describe the feature

Expose additional field `callback` on Timeout options object. If specified, no timeout error will be thrown, instead, a callback is invoked with original `request`, as well as same `event` and `timings` that TimeoutError has.

#### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.

**Comment by kibertoad** [comment]
@szmarczak I can work on a PR if this functionality is approved.

**Comment by sindresorhus** [comment]
Can't you use the `beforeError` hook, check if it's a TimeoutError, and then handle it?

**Comment by kibertoad** [comment]
@sindresorhus It means that error is generated (which can be a bit expensive for heavy load scenarios), and also requires type-checking  code for error. Doable, but less elegant and efficient.

**Comment by sindresorhus** [comment]
It's created, just not thrown.

Alternatively, maybe we could add a `beforeTimeout` hook, but there's has to be some good reasons why `beforeError` wouldn't work.

**Comment by kibertoad** [comment]
@sindresorhus It would work. However:
1) Errors in general are not the right mechanism for doing the flow control, especially for something that is already expected by application in advance;
2) There is a performance impact (mostly related to capturing stacktrace, I believe).

I can submit an MR for `beforeTimeout` hook if you could point me in the direction of some existing hook I could model it after :). Idea would be that you could swallow timeout if you want to and do not propagate it further?

**Comment by sindresorhus** [comment]
I'll let @szmarczak chime in first.

**Comment by kibertoad** [comment]
@szmarczak Any opinion on this?

**Comment by szmarczak** [comment]
> We have an SLA with external party which defines that they are to provide a response within 1 second timeframe. If there is no response, we have to interrupt the request and assume the default value. We do not consider that to be an error that needs to be handled but just one possible flow.

IOW you mean to have a `timeout` event and update it on the first run?

**Comment by kibertoad** [comment]
@szmarczak Could you please clarify what do you mean by "updating timeout event on the first run"? Basically ask here is to avoid spawning/handling error in the first place, and expose a mechanism to handle it as an expected scenario.

**Comment by szmarczak** [comment]
Something like this:

```js
const promise = got('https://example.com', {timeout: 1000});
promise.once('timeout', request => {
	request.setTimeout(30000);
});
```

**Comment by kibertoad** [comment]
yup, that would work, if that also would resolve promise.

**Comment by szmarczak** [comment]
> yup, that would work, if that also would resolve promise.

Why do you need the promise to resolved and not rejected?

**Comment by szmarczak** [comment]
Not sure what do you refer to. Do you mean that you want to reschedule the timeout and if the request is successful then resolve the promise? If so, then we could work on that. If you want to drop the request instead, then an error is appropriate.

**Comment by szmarczak** [comment]
Friendly ping.

**Comment by kibertoad** [comment]
@szmarczak Sorry for the delay in response. So to reiterate what the use-case is: we are calling an external partner API and we want to handle the case when they do not respond in time, and we want to continue with an alternate flow in case that happens, and conceptually we do not consider that to be an error. Do I understand your position correctly that your preferred way to handle that would be to swallow an error?

**Comment by szmarczak** [comment]
> we want to continue with an alternate flow

Can you please explain how does this look like? It's hard for me to imagine without a bigger image. What exactly should happen in case of a timeout?

**Comment by kibertoad** [comment]
@szmarczak This is an availability check. If partner says there is availability, we return 200 OK and `isAvailable: true`. If partner doesn't respond in time, we revert to default behaviour, which is assume there is availability, and results in same 200 OK and `isAvailable: true`.

**Comment by szmarczak** [comment]
> we revert to default behaviour, which is to assume there is availability

What exactly happens when reverting to the default behaviour? A new timeout is set and the request continues?

**Comment by kibertoad** [comment]
@szmarczak No, we don't need the request anymore, as availability check is done synchronously, so as to not block user, if there is no response now, we don't care if there is a response later.
So when default behaviour is triggered, our API returns the reply to the caller without doing any more requests.

**Comment by szmarczak** [comment]
> There is a performance impact (mostly related to capturing stacktrace, I believe).

There will always be. If Got doesn't create the timeout error, then Node.js will create `socket hung up`:

```js
const http = require('http');
const request = http.get('http://example.com');
request.destroy();
```

**Comment by szmarczak** [comment]
> Errors in general are not the right mechanism for doing the flow control, especially for something that is already expected by application in advance;

Unfortunately there is no other choice as to the Node.js behavior mentioned above. Oh wait, there is, you can write own HTTP client from scratch that doesn't throw errors :P

**Comment by szmarczak** [comment]
Closing. I don't see any other solution than swallowing the `ETIMEDOUT` error. But feel free to continue the discussion, I'm open to questions and puzzles.
