### ISSUE TITLE
json: true is not working with promises

### ISSUE THREAD

**Issue by kevinsimper** [sindresorhus/got#129]
https://tonicdev.com/kevinsimper/563e0dff569e3f0c0089b187

It works if you remove `json: true`

**Comment by floatdrop** [comment]
You don't added `catch` - so error was ignored.

https://tonicdev.com/563b6c715e6a230c00d2c500/got-promise-example

**Comment by kevinsimper** [comment]
@floatdrop Try to create a new requestbin, it does not work

![image](https://cloud.githubusercontent.com/assets/1126497/11015817/8d40faee-856d-11e5-8dd0-26067ed0f0a2.png)

**Comment by floatdrop** [comment]
@kevinsimper 

<img width="966" alt="screen shot 2015-11-07 at 20 47 51" src="https://cloud.githubusercontent.com/assets/365089/11015877/d68e66b4-8590-11e5-8c52-2ce1fac15d23.png">

**Comment by kevinsimper** [comment]
Try to create a new requestbin :)

**Comment by floatdrop** [comment]
@kevinsimper I don't quite get a problem. `json` option is used to _parse_ JSON response from endpoint. Requestbin is always returning `ok` - which is obviously not JSON - so that is an error.
