### ISSUE TITLE
retryWithMergedOptions: not propagating method if not put in options

### ISSUE THREAD

**Issue by alferpal** [sindresorhus/got#1291]
I'm not sure if this is a bug or intended behaviour, and would like to clarify that before opening a bug. Also, we're using got 10 and due to some of the breaking changes, we can't check right know with 11.

So, the thing:

We have some afterResponse hooks in order to retry in given scenarios. The most typical one is we got a 401, re-authenticate, fire the request again.

The problem is, when that request hook is called from a POST request that is so due to `client.post()` instead of `method: 'POST'` in options, the retried request is a GET, and then we get the expected "Can't use a body with GET".

So, the question: Is this intended behaviour?

Thank you

**Comment by szmarczak** [comment]
What Got version do you encounter the error with?

**Comment by alferpal** [comment]
10.7.x is what we're using.

**Comment by szmarczak** [comment]
Can you try `11.1.4` please?

**Comment by alferpal** [comment]
I'll try to mount a little repro with both 10x and the last of 11.x

**Comment by alferpal** [comment]
Found the problem, it was on our side.

When merging with defaultOptions, there the method is get.
