### ISSUE TITLE
Drop support of Node.js 0.10/0.12

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#130]
Due to [Node LTS schedule](https://github.com/nodejs/LTS/blob/master/schedule.png) - 0.10 version will not be maintained after October 2016 - so we can make 5.x version of `got` last compatible version with 0.10 and drop support in 6.x and above.

**Comment by sindresorhus** [comment]
:+1:

**Comment by floatdrop** [comment]
@sindresorhus what do you think about 0.12? It's not maintained much longer.

**Comment by sindresorhus** [comment]
I would just drop them both at once. The next one is Node.js 4.2 which brings a *lot* of improvements and ES2015 goodies.

**Comment by arthurvr** [comment]
I'd also drop both. :+1:

**Comment by sindresorhus** [comment]
I would also like to drop callback-API support in that version.

**Comment by julien-f** [comment]
I think it would be good (not necessarily in the near future) to bring the promise and stream APIs closer:

```js
const { stream } = await got.stream('http://example.org')
```

- easy to use with ES2015's generators and ES2016's async functions
- no more complexity to implement retrial on top of streams
- should be more intuitive to use
- should be easier to maintain

**Comment by floatdrop** [comment]
@julien-f I don't quite get it. Getting stream is synchronous operation - why should we use `await` on it?
