### ISSUE TITLE
HTTP2 returning 403 when site is OK

### ISSUE THREAD

**Issue by nkostadinov** [sindresorhus/got#1301]
#### Describe the bug

 - Node.js version: 12.13.1
 - OS & version: Windows 10

When making http2 request with {http2: true} option throws error

#### Actual behavior
the request is rejected with "HTTPError: Response code 403 (Forbidden)"

#### Expected behavior
return the site's content

#### Code to reproduce

```js
const got = require('got')
const url = 'https://vestirama.ru/novosti/&section=d5faa707'
const got_params = {
  http2: true,
}
got(url, got_params)
  .then(res => {
    console.log('res',res)
  })
  .catch(res => console.log('error', res))
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Does it succeed with `{http2: false}`?

**Comment by nkostadinov** [comment]
Well I'm currently getting too many redirects error. But i'm pretty sure that earlier today it did work :). I use same headers with axios and it worked there but got is much faster and supports http2.

**Comment by szmarczak** [comment]
You can reproduce the error with native Node.js:

```js
const http2 = require('http2');
http2.connect('https://vestirama.ru').request({}, {endStream: false}).on('response', console.log);
```

**Comment by szmarczak** [comment]
It's possible that they reject all `endStream: false` requests:

https://github.com/nodejs/node/blob/654df09ae0c5e17d1b52a900a545f0664d8c7627/lib/internal/http2/core.js#L2561-L2562

https://github.com/nodejs/node/blob/654df09ae0c5e17d1b52a900a545f0664d8c7627/lib/internal/http2/core.js#L2587

**Comment by josepilar** [comment]
@nkostadinov I'm experiencing the same issue and discovered that the user agent being set by got is the root cause `got (https://github.com/sindresorhus/got)` once I changed it the request went through just fine.

As a side note my API is on Azure API management.

Does anyone know why this might be happening?

**Comment by szmarczak** [comment]
@josepilar Ask Azure.
