### ISSUE TITLE
digest authentication

### ISSUE THREAD

**Issue by project-owner** [sindresorhus/got#1302]
Is there any way to use digest authentication in the library?

**Comment by sindresorhus** [comment]
There’s an example here: https://github.com/vMReal/digest-auth/issues/8

**Comment by gobukhov-dev** [comment]
I'm trying to migrate from the deprecated 'request' library to another one. The Digest Authentication is one of the requirements. 'request' had it without installing any additional library. I tried 'axios', 'got' and 'node-fetch' and all need installation of the additional libraries. For 'node-fetch' you need to install 0.5 MB library. I ended up with my own ~20 lines of code implementation.
Thank you!
