### ISSUE TITLE
Better HTTP(S) Request options documentation

### ISSUE THREAD

**Issue by Giotino** [sindresorhus/got#1306]
#### What would you like to discuss?

Since we made some modification to the `options`, this statement
```
options
Type: object

Any of the https.request options.
```
from the [documentation](https://github.com/sindresorhus/got#options) is no more valid.

Maybe the individual `https.Request` options should be documented on the got page.

<hr />

Node.JS options (checked ones are those already documented by Got)

From `http.request`
- [x] agent
- [x] auth
- [x] createConnection (not present in README.md)
- [ ] defaultPort
- [x] family
- [x] headers
- [ ] host
- [ ] hostname
- [ ] insecureHTTPParser
- [x] localAddress
- [x] lookup (not present in README.md)
- [ ] maxHeaderSize
- [x] method
- [x] path (might be reviewed)
- [x] port (not present in README.md)
- [x] protocol (not present in README.md)
- [ ] setHost
- [ ] socketPath
- [x] timeout

From `tls.createSecureContext` (documented `https.request`)
- [x] ca
- [x] cert
- [ ] ciphers (WIP #1435)
- [ ] clientCertEngine
- [ ] crl
- [ ] dhparam
- [ ] ecdhCurve
- [ ] honorCipherOrder (WIP #1435)
- [x] key
- [x] passphrase
- [x] pfx (#1364)
- [x] rejectUnauthorized
- [ ] secureOptions
- [ ] secureProtocol
- [ ] servername
- [ ] sessionIdContext
- [ ] highWaterMark
- [x] checkServerIdentity (unducumented by Node.JS)

From `tls.createSecureContext` (but undocumented in `https.request`)
- [ ] minVersion (WIP #1435)
- [ ] maxVersion (WIP #1435)

**Comment by sindresorhus** [comment]
Yes. It's time to do that. We should take the opportunity to see if any of the `https.request` options could be improved, like we did with your previous PRs.

**Comment by Giotino** [comment]
I think this should be done in 2 steps.
The first is renaming/remapping current `https.Request` options, giving deprecation errors for the old ones (as we did in the previous PRs).
The second, to be implemented in got 12, is to not use got `options` with the request function, but crafting a dedicated `options` object to be used for the request

**Comment by sindresorhus** [comment]
That sounds like a good plan.

**Comment by Giotino** [comment]
I updated the first message with a list of all the options taken by `http.request` and `https.request`

**Comment by yovanoc** [comment]
We can't pass ciphers anymore? ;(

**Comment by Giotino** [comment]
We broke the definition of the `https.request` options, but they're still there.

So, in got 11, you can do something like this
```js
got('https://example.org', {
  ciphers: '...'
} as any);
```

**Comment by zedd3v** [comment]
Yes please fix this

**Comment by sindresorhus** [comment]
@zedd3v Please use GitHub reactions instead of commenting something that doesn't add anything to the discussion.

**Comment by markdboyd** [comment]
Issued #1364 to add support for the TLS option `pfx` to the supported HTTPS options

**Comment by efalkner** [comment]
Is there documentation for how to handle non-standard protocols? I've created [an issue with webdriverio project](https://github.com/webdriverio/webdriverio/issues/5711),  but it seems as though URIs that start with something other than `http` or `https` are throwing 500 server errors when passed through got.

**Comment by Giotino** [comment]
For all the `ciphers` fans (@yovanoc @zedd3v): I'm going to add the option in this PR #1435

**Comment by szmarczak** [comment]
Enabled more HTTPS options here: 83575d590a119027d319bd9208681973087564a9

@Giotino We just need to do the tests and add docs.

**Comment by Giotino** [comment]
> Enabled more HTTPS options here: [83575d5](https://github.com/sindresorhus/got/commit/83575d590a119027d319bd9208681973087564a9)
> 
> @Giotino We just need to do the tests and add docs.

https://github.com/Giotino/got/tree/https-tests

I adapted the tests from #1435.
The tests cover:
- `ciphers`
- `honorCipherOrder`
- `minVersion`

Other options are a little bit tricky to test.

**Comment by szmarczak** [comment]
Great! Can you submit a PR?

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/5-https.md#other-https-options
