### ISSUE TITLE
response under error causing unhandled promise rejection 

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/got#1308]
#### Describe the bug

 - Node.js version: v13.14.0
 - OS & version: Tested over Linux and Mac

#### Actual behavior

When a request is performed by `got` and it throws an `error`, `got` returns the `error` properly.

However, since the original request `response` is still a thing living at `error.response` and it's a stream, errors can still happen (e.g., an HTTP parser error), creating scenarios where the underlying request errors throw without a handler associated.

#### Code to reproduce

- https://runkit.com/kikobeats/5edd7ef599b73f001abdaa3c
- https://runkit.com/kikobeats/5ef8adf14093fb00135e3e8c

#### Expected behavior

First, not sure if this is an edge case `got` should to handle.

In my particular case, since `got` throws an `error` at the first level, that all that I need to know and the underlying error can be skipped.

I tried to skip it using hooks or cancelling the internal response without success.

**Comment by kirillgroshkov** [comment]
Yes, we also noticed such "UnhandledRejections" since some version of `got` (not sure from which one). Looks not right.

**Comment by ifibercc** [comment]
I can't catch the error when the status code is 400 with version 11.3, but it's ok on version 10.x.

**Comment by leodutra** [comment]
Same thing happening to me. It's happening when the server abort the pending request.

**Comment by leodutra** [comment]
It seems `Transfer-Encoding: chunked`, as response header, is related somehow. But this is only a guess.

**Comment by Kikobeats** [comment]
Added another way to reproduce the error:

```js
const got = require('got')
const pReflect = require('p-reflect')

const result = await pReflect(got('https://gitlab.com/edpratti'))

console.log(result)
```

In this case, under 5xx, an unhandled promise reaches the process execution

**Comment by szmarczak** [comment]
Simplest repro: `const result = await got('https://gitlab.com/edpratti', {retry: 1});`

**Comment by Stono** [comment]
Hey, I'm seeing this is anything newer than `11.1.4` `ReadError: The server aborted the pending request`

**Comment by szmarczak** [comment]
Released `got@11.4.0`.

**Comment by psi-4ward** [comment]
Having this issue while downloading bigger files on windows node 14 with got 11.7

```
ReadError: The server aborted pending request
```

after some time. 
The Application is packed with pkg 

Smaller files work. Seems there is a timeout?

```
      await pipelinePromised(
        got.stream(fromUrl),
        fs.createWriteStream(targetFile)
      );
```

**Comment by fazulk** [comment]
Getting the same error using node 14.10.1, 14.10.0, 14.14.0 and various version of got starting with 11.5.1, 11.6.2, 11.7. Also using node Pipeline. I cannot get it to reproduce the error every time and normally happens with larger data transfers.

**Comment by NishilSB** [comment]
i got this error in 11.8.3 

`The server aborted pending request
    at IncomingMessage.<anonymous> (C:\Projects\surveyorapp\node_modules\got\dist\source\core\index.js:809:31)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at IncomingMessage.origin.emit (C:\Projects\surveyorapp\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketCloseListener (_http_client.js:432:11)
    at TLSSocket.emit (events.js:388:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET',
  timings: {
    start: 1686040058331,
    socket: 1686040058331,
    lookup: 1686040058332,
    connect: 1686040058553,
    secureConnect: 1686040059496,
    upload: 1686040059496,
    response: 1686040060163,
    end: undefined,
    error: undefined,
    abort: 1686040061713,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 221,
      tls: 943,
      request: 0,
      firstByte: 667,
      download: undefined,
      total: 3382
    }
  }
}`
