### ISSUE TITLE
timeout issues with streams

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#1314]
#### Describe the bug

 - Node.js version: Only with node >= 14
 - OS & version:  Macos Catalina

```ts
function myRequest() {
  return new Promise((resolve, reject) => {
    const request = client
      .stream("LINK")
      .on("data", (buffer: Buffer) => {
        const chunk = buffer.toString("utf8");
        const regex = regexFind.exec(chunk);

        if (!regex) {
          return;
        }

        request.emit("end");
        request.removeAllListeners();

        return resolve(regex[2]);
      })
      .on("error", reject);
  });
}
```

#### Actual behavior

I get a `RequestError: Timeout awaiting 'request' for 3000ms` (3000 is my timeout option) but the request is resolving good data... just the timeout appear to not be cleared but only with node >= 14

**Comment by szmarczak** [comment]
Please include full reproducible code. At first I can tell you that you shouldn't do `request.emit('end')` on your own.
