### ISSUE TITLE
POST request sends no data

### ISSUE THREAD

**Issue by ajgeiss0702** [sindresorhus/got#1315]
#### What would you like to discuss?
I assume that I am doing something wrong. I am trying to send a POST request to a site, but when looking it appears that no data is sent.

Here is my code:
```js
await got.post("https://ajg0702.us/post_test.php", {
    json: {
      login: username,
      password: password,
      register: 0,
      remember: 1,
      cookie_check: 1
    }
  });
```
Here is the server-side code:
```php
<?php
print_r($_POST);
```
Here is the output:
```
Array
(
)
```
Am I doing something wrong?

I have also tried sending data using form-data with the same result.

#### Checklist

- [x] I have read the documentation.

**Comment by Giotino** [comment]
According to the PHP documentation
`$_POST`
> An associative array of variables passed to the current script via the HTTP POST method when using application/x-www-form-urlencoded or multipart/form-data as the HTTP Content-Type in the request.

You're sending an `application/json`, so you need to parse the body yourself.
Example:
```php
$requestBody= file_get_contents('php://input');
$requestPayload = json_decode($requestBody, TRUE);
var_dump($requestPayload);
```

**Comment by ajgeiss0702** [comment]
I tried FormData too but it shows the same thing

**Comment by Giotino** [comment]
> I tried FormData too but it shows the same thing

```ts
import got from "../source";
import FormData = require('form-data');

(async () => {
  const form = new FormData();
  form.append('username', 'USER');
  form.append('password', 'PASS');

  const response = await got.post("http://192.168.2.4:8123", {
    body: form,
  });
  
  console.log(response.body);
})();
```

```php
<?php
print_r($_POST);
```

```
Array
(
    [username] => USER
    [password] => PASS
)
```

**Comment by ajgeiss0702** [comment]
Heres some test code. I cant see a major difference between mine and yours.
```js
const got = require("got");
const FormData = require('form-data');
const getStream = require("get-stream");

(async ()=>{
  var form = new FormData();
  form.append("login", "username");
  form.append("password", "password123");

  var lr = await got.post("https://ajg0702.us/post_test.php", {
    body: await getStream(form)
  });
  console.log(lr.url+" - "+lr.method+" - "+lr.statusCode+" "+lr.statusMessage);
  console.log(lr.body);
})();
```

**Comment by Giotino** [comment]
Actually you're doing the best thing, width a small body it's better to read it all and then send it, so, in case of retries, it doesn't fail. But you're forgetting to set the correct header:
```ts
var form = new FormData();
form.append("login", "username");
form.append("password", "password123");

var lr = await got.post("https://ajg0702.us/post_test.php", {
  body: await getStream(form),
  headers: {
    'content-type': `multipart/form-data; boundary=${form.getBoundary()}`
  }
});
```

**Comment by ajgeiss0702** [comment]
Ah, thank you very much!
