### ISSUE TITLE
Node.js 10 support

### ISSUE THREAD

**Issue by NMinhNguyen** [sindresorhus/got#1319]
#### What would you like to discuss?

I noticed in https://github.com/sindresorhus/got/pull/1051#discussion_r440845532 that the minimum version of Node was bumped from just 10 to 10.19.0 (via `engines`) and I wanted to ask why that happened. Is the current version of `got` relying on a feature/bugfix not available in 10.0.0? Arguably, it should be listed as a breaking change in v11 release notes.

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
> Is the current version of got relying on a feature/bugfix not available in 10.0.0?

Yes

> Arguably, it should be listed as a breaking change in v11 release notes.

Updated

**Comment by NMinhNguyen** [comment]
Thanks @sindresorhus! Mind sharing what this feature/bugfix is?
