### ISSUE TITLE
application/hal+json returns string

### ISSUE THREAD

**Issue by QAnders** [sindresorhus/got#1320]
#### Describe the bug

 - Node.js version: v12.14.1
 - OS & version: Ubuntu 16.04

Calling an API that requires the use of `application/hal+json` as Accepted content-type is not being returned as JSON but as String.
`responseType: 'json'` does not have any affect.

#### Actual behavior

Returns `String`

#### Expected behavior

Return `JSON`

#### Code to reproduce

```js
{
  method: 'GET',
  uri: URI,
  headers: {
    Authorization: `Bearer ${token}`,
    Accept: 'application/hal+json'
  },
  responseType: 'json'
}
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
> Code to reproduce

This is an object, I need a full code to reproduce the issue.

**Comment by QAnders** [comment]
The API I call is a private API requiring AUTH and I haven't found any public HATEOS (hal+json) API's to test against. The code would be just a regular GET, eg:

```
  const options = {
    uri: 'https://some.hateos.api/,
    headers: {
      Accept: 'application/hal+json'
    }
  }

  try {
    const response = await https.get(options.uri, { headers: options.headers });
    return response.body;
  } catch (error) {
    console.log('getBBCSearchResult error:', error);
    throw new Error('getBBCSearchResult error: ' + error);
  }
```

**Comment by szmarczak** [comment]
In the example above you're missing the `responseType` option.

**Comment by QAnders** [comment]
Sorry, forgot it in the sample I wrote up but it's in the original post...

Strangely, that didn't work but now adding it as:
`const response = await https.get(options.uri, { headers: options.headers, responseType: 'json' });`

does work...

I'll leave it like that and thanks for getting back to me!
