### ISSUE TITLE
prefixUrl is ignored with empty URLs for instances created from chained extend calls

### ISSUE THREAD

**Issue by targos** [sindresorhus/got#1322]
#### Describe the bug

 - Node.js version: v14.4.0
 - OS & version: Windows 10

If an instance is created with `otherInstance.extend({ prefixUrl: 'something' })`, it still uses the `prefixUrl` from the parent instance when no URL or an empty URL is passed.

#### Actual behavior

```js
const got = require('got');
const parent = got.extend({ prefixUrl: 'http://localhost:8888', responseType: 'json' });
const child = parent.extend({ prefixUrl: 'http://localhost:8888/other/path' });
child.get(''); // or child.get()
// Request goes to 'http://localhost:8888'

// Workaround:
child.get('./');
// Request goes to 'http://localhost:8888/other/path/'

// Note that it works correctly if the instance is created directly from `got`:
const other = got.extend({ prefixUrl: 'http://localhost:8888/other/path', responseType: 'json' });
other.get('');
// Request goes to 'http://localhost:8888/other/path/'
```

#### Expected behavior

Extending from an extended instance should behave the same way as extending from `got`.

#### Code to reproduce

See above.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Thanks for the report, indeed, this was a tricky one!
