### ISSUE TITLE
http2 option toggle breaks request

### ISSUE THREAD

**Issue by punitivebars** [sindresorhus/got#1324]
#### Describe the bug

 - Node.js version: 12.13.1
 - OS & version: Windows 10

#### Actual behavior
Running a request to a URL with the `http2` option set to `true`. Stop the program and run the same code, but with the option now set to `false` and the request no longer works. 

`RequestError: connect ECONNREFUSED`
...

#### Checklist

- [ ✓] I have read the documentation.
- [ ✓] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please fill out the issue template, otherwise this issue will remain closed.
