### ISSUE TITLE
http/2 option toggle breaks request 

### ISSUE THREAD

**Issue by punitivebars** [sindresorhus/got#1325]
#### Describe the bug

 - Node.js version: 12.13.1
 - OS & version: Windows 10

#### Actual behavior
Running a request to a URL with the http2 option set to true. Stop the program and run the same code, but with the option now set to false and the request no longer works.

RequestError: connect ECONNREFUSED
...

#### Expected behavior
Toggling http2 to `false` should make it fallback to http and not have any errors.
...

#### Code to reproduce
```js
const got = require('got');
const url = `https://discord.com/`;

got(url, {
    resolveBodyOnly: false,
    retry: {
        limit: 0
    },
    http2: true
}).then((res) => {
    console.log(res);
}).catch((err) => {
    console.log(err);
});
...
```
#### Checklist

- [ ✓ ] I have read the documentation.
- [ ✓ ] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
Setting `http2` explicitly to `false` or not setting it at all is the same.
I tried your example, I'm having no problem with `http2: false`, I think this might be a problem on your side.

I tried with Node.JS `12.13.1`, `12.18.1` and `14.1.0`.

**Comment by szmarczak** [comment]
I cannot reproduce on `got@11.4.0`.
