### ISSUE TITLE
I am getting below error Error: connect ECONNREFUSED 172.17.161.48:443 in Postman.

### ISSUE THREAD

**Issue by svarshney2311** [sindresorhus/got#1327]
Getting below error: Error: connect ECONNREFUSED 172.17.161.48:443.  My scripts were working few hours before, but throwing mentioned error now as of June 23rd 2020 5:52 PM EST.

 - Node.js version: 
 - OS & version: 

#### Actual behavior

...

#### Expected behavior

...

#### Code to reproduce

```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by svarshney2311** [comment]
Hi,

Have you provided solution for this issue?

**Comment by Giotino** [comment]
That's not a Got issue, it's related to your environment.
If you want to be sure try `curl https://172.17.161.48` on the system where your Node.JS script is running.
