### ISSUE TITLE
Inconsistent response body in afterResponse hook when using responseType vs shortcuts

### ISSUE THREAD

**Issue by mastermatt** [sindresorhus/got#1330]
#### Describe the bug

- Got version: 11.3.0
 - Node.js version: 12.16.1
 - OS & version: macOS 10.15.5 

#### Actual behavior

Using the shortcuts `.buffer()`, `.json()` and `.text()` does not parse the body before calling `afterResponse` hooks, while setting `responseType` directly in the options does.

#### Expected behavior

The two calling forms should produce consistent results for the response body (personally, I'd prefer it was parsed for both cases).

As a question: I'm curious why [`shortcut`](https://github.com/sindresorhus/got/blob/56df87671c741251a657fd57f60857ed9927f76b/source/as-promise/index.ts#L242) doesn't just set `responseType` on the `options` object instead of calling `parseBody` directly. Or maybe it should be and that would be the fix 🤷 

#### Code to reproduce

```js
 const client = got.extend({
  hooks: {
    afterResponse: [
      async (response) => {
        console.log("response body type:", typeof response.body)
        return response
      }
    ]
  }
})

await client("https://postman-echo.com/get", { responseType: "json" })
// response body type: object

await client("https://postman-echo.com/get").json()
// response body type: string
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
You can do `.json()` and `.buffer()` on the same promise and the results will be different. If we were to set the option instead, both would return the same result.
