### ISSUE TITLE
Trying to download a zip file, but responseType error

### ISSUE THREAD

**Issue by corydorning53** [sindresorhus/got#1332]
#### What would you like to discuss?
When I try to download a zip file using got 11.1.4, I get the error:
```
TypeError: To get a Buffer, set `options.responseType` to `buffer` instead
```

My code looks like this:
```
const scanFile = path.join(scanDirectory, fileName);

got("http://myurl.com/file.zip", {encoding: null, responseType: 'buffer'})
  .then(res => {
    fs.writeFileSync(scanFile, res.body);
  }).catch(err => {
    console.error(err);
  });
```

#### Checklist

- [ x] I have read the documentation.
I have read the docs but am admittedly new to streams/buffers

**Comment by sindresorhus** [comment]
You should not set `encoding`. I think we could make the error message more clear in this case.

I think the docs https://github.com/sindresorhus/got#encoding should also be changed from:

> To get a Buffer, you need to set responseType to buffer instead.

To:

> To get a Buffer, you need to set responseType to buffer instead. Don't set this option to `null`.

Just to be entirely clear. Since `encoding: null` is a common way to do it in Node.js.
