### ISSUE TITLE
Add and compare with other clients ,"fetch-h2"

### ISSUE THREAD

**Issue by masx200** [sindresorhus/got#1334]
#### What problem are you trying to solve?

Add and compare with other clients,"fetch-h2"

https://www.npmjs.com/package/fetch-h2
...

#### Describe the feature
https://www.npmjs.com/package/got#comparison
...

#### Checklist

- [x ] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
We already have `fetch` in the comparison. The only difference is that one supports HTTP2.
