### ISSUE TITLE
SearchParams allows for a null value which is converted to "null" string literal.

### ISSUE THREAD

**Issue by thedillonb** [sindresorhus/got#1338]
#### What would you like to discuss?

searchParams allows for a value `null` but it gets converted to a literal string "null" which is almost never what I would assume someone would want. Was there a reason for this? `null` seems more convertible to an empty value, or even removed entirely from the query parameters, rather than the arbitrary `null` literal. 
#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
It's the default `URLSearchParams` behavior: `(new URLSearchParams({foo: null})).toString()` => `foo=null`

**Comment by thedillonb** [comment]
I understand that you guys use that as the underlying structure however, how do you see that being useful? `URLSearchParams` seems undoubtedly wrong in this situation as `null` and `"null"` is not equivalent. Its behavior is counter-intuitive for those using your library (given they don't know about the underlying `URLSearchParams` usage). Would it not appear more useful to prevent your users from making the mistake by either stripping out that value before being passed to `URLSearchParams` or not allow `null` in the typing?

**Comment by sindresorhus** [comment]
Yeah, I really hate query strings. They're so ambiguous and inconsistent...

I guess we could align with https://github.com/sindresorhus/query-string#falsy-values
