### ISSUE TITLE
Remove parse-json dependency

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#134]
I'm not 100% sure that this is possible, but depending on two versions of same thing is not ok either.

//cc @Qix-

**Comment by sindresorhus** [comment]
@floatdrop I think we should just drop `parse-json`. I don't think it's worth its size in this case.

**Comment by floatdrop** [comment]
@sindresorhus that's one way. I found it very useful on wrong backends responses. If we decide to drop it - first line of broken input should stay in error message.
