### ISSUE TITLE
Current method typing prevents some of the lesser-known HTTP methods.

### ISSUE THREAD

**Issue by thedillonb** [sindresorhus/got#1346]
#### What problem are you trying to solve?

I'd like to use some of the lesser-known HTTP methods but am unable to as the typing for `Method` is `'GET' | 'POST' | 'PUT' | 'PATCH' | 'HEAD' | 'DELETE' | 'OPTIONS' | 'TRACE' | 'get' | 'post' | 'put' | 'patch' | 'head' | 'delete' | 'options' | 'trace'`

#### Describe the feature

Right now, the "core" HTTP methods (GET, PUT, POST, etc...) are typed into the code as string literals which prevents using some of the lesser-known methods: https://www.iana.org/assignments/http-methods/http-methods.xhtml. Postman had a similar problem in the past where it's bound list of methods excluded use-cases: https://blog.postman.com/custom-http-methods-more-flexibility-and-autonomy/.

My request is that the typing is changed to allow flexibility in HTTP methods.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
We're optimizing or the 99% case. You can just force it though. `'FOO' as Method`. TS doesn't have any middle-ground, either we make it a string and worsen the experience for the 99% use-case or we force you to force-cast the type.

**Comment by szmarczak** [comment]
> Right now, the "core" 

Why `core` in quotation marks? The HTTP/1.1 spec (RFC7231) defines **only** these methods:

![image](https://user-images.githubusercontent.com/36894700/86651437-d0d01280-bfe3-11ea-9392-e98320f9ec8d.png)

The thing you're talking about is [WebDAV](https://en.wikipedia.org/wiki/WebDAV), which extends `HTTP/1.1`. Got is a `HTTP/1.1` client, not a WebDAV client.

If you want not to obey by the WebDAV semantics, or you have implemented them already, you can follow the tip mentioned by @sindresorhus.

**Comment by thedillonb** [comment]
That's fair @sindresorhus. However, instead of making the type a `string` I was more thinking extending the union with a class that allows raw flexibility. E.g 

```js
class RawMethod {
  name: string;
}

type Method = 'GET' | 'POST' | ... | RawMethod
```

That way you cover 99% of your use case but don't force users of lesser-known methods to have to cast.

@szmarczak 

> Why core in quotation marks?

For the very reason you listed: because those are explicitly listed in the spec. However, while WebDav was in my mind, it certainly wasn't the entirety of my thought. As the HTTP spec states: `Additional methods, outside the scope of this specification, have been standardized for use in HTTP. ` which are listed here: http://www.iana.org/assignments/http-methods/http-methods.xhtml. Which most of them are indeed WebDav. However, just like `LINK` and `UNLINK` were once standard methods in HTTP 1.1 tomorrow you may have new methods which I would think a library would want to provide a means to access without having to resort to skirting the type checking system.

**Comment by szmarczak** [comment]
> tomorrow you may have new methods

Then tomorrow I would update the types (or when someone would raise an exact issue) :) Got is actively maintained.

WebDAV defines new semantics for these methods and we would have to implement those in order to be compatible. Got is RFC-compatible, which means it follows all the semantics defined in the RFC7231.

**Comment by szmarczak** [comment]
@Giotino Just a quick note, you could continue the discussion here instead of opening #1475. Because an issue is closed it doesn't mean the discussion is closed too :) The discussion can keep going. Let's continue at #1475 then as it's open already.
