### ISSUE TITLE
upgrade of http2-wrapper is breaking builds

### ISSUE THREAD

**Issue by jsnoble** [sindresorhus/got#1347]
#### Describe the bug

 - Node.js version: 10.19
 - OS & version: 

#### Actual behavior
The recent update of http2-wrapper locks the node engine to >=10.21 while this library says that it is >=10.19.0. This update automatically was inserted if got was installed and broke our builds.
...

#### Expected behavior
Not to throw or break build automatically in ci for patch version updates
...

#### Code to reproduce

```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Ah sorry I forgot to check Got... Will publish a fix ASAP.

**Comment by szmarczak** [comment]
Released `http2-wrapper@1.0.0-beta.4.8` which now accepts Node.js 10.19.0.
