### ISSUE TITLE
followRedirect is not working as expected

### ISSUE THREAD

**Issue by noteme-io** [sindresorhus/got#1348]
#### Describe the bug

 - Node.js version:  14.4
 - OS & version:  Windows

#### Actual behavior
Input URL - https://link.medium.com/9R8XLPnMU7
Got response with a redirected URL is - https://rsci.app.link/9R8XLPnMU7?_p=c11130dc9c0a7af1eb1490faed
...

#### Expected behavior
But this should be the redirect URL for the above-mentioned input URL -  https://elemental.medium.com/inside-a-lab-developing-a-coronavirus-treatment-d849f16b4f7d
...

#### Code to reproduce

```js
const {
            body: html,
            url
          } = await got("https://link.medium.com/9R8XLPnMU7", {
            rejectUnauthorized: false
          });
console.log(url);
...

**Comment by noteme-io** [comment]
Any updates on this issue???

**Comment by szmarczak** [comment]
Will take a look soon.

**Comment by Jon165** [comment]
I am getting issue with 'redirect' code throws 302.

got(url,{ method:method, headers:headers})
.then(res=>console.log(res))
.catch(err=> console.log(err));

Please fix this issue.

**Comment by szmarczak** [comment]
@noteme-io The status code is `200` so it doesn't follow that redirect. As expected.

**Comment by szmarczak** [comment]
@Jon165 Please file a bug report.
