### ISSUE TITLE
Replace duplexify with something

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#135]
[`duplexify`](https://www.npmjs.com/package/duplexify) is depending on quite big `readable-stream` package, so it would be nice to find alternative.

**Comment by sindresorhus** [comment]
Lol, I was literally just writing this exact ticket :p

**Comment by sindresorhus** [comment]
When we depend on at least Node.js 4, I don't really see the point of having a dependency on `readable-stream`. It's huge.

**Comment by julien-f** [comment]
Open a PR to make readable-stream optional :)

**Comment by sindresorhus** [comment]
Yup, that will be the first thing we'll try.
