### ISSUE TITLE
HTTP2 with proxy agent not working

### ISSUE THREAD

**Issue by matthew1232** [sindresorhus/got#1356]
#### Describe the bug

 - Node.js version: v14.5.0
 - OS & version: MacOS v10.13.6

Using an http2 proxy/agent with the http2-wrapper example shown in the README throws an ssl error (using [Charles Proxy](https://www.charlesproxy.com/) as a proxy)

#### Actual behavior
This error is thrown: RequestError: 140736139293568:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

#### Expected behavior
The request goes through

#### Code to reproduce

(Make sure you have Charles running, or you use your own http2 proxy)

```js
const http2 = require('http2-wrapper');
const got = require('got');
const { Agent } = http2;

class ProxyAgent extends Agent {
	constructor(url, options) {
		super(options);

		this.origin = url;
	}

	request(origin, sessionOptions, headers, streamOptions) {
		return super.request(this.origin, sessionOptions, {
			...headers,
			':authority': (new URL(origin)).host
		}, streamOptions);
	}
}

const res = await got('https://www.google.com/', {
        http2: true,
        agent: {
            http2: new ProxyAgent('https://localhost:8888')
        }
});
```

#### Checklist

- [ x ] I have read the documentation.
- [ x ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Hi, I have updated the `http2-wrapper` repo. The proxies are quite buggy and will let you know once it's stable. Thanks for trying it out.

`wrong version number` basically means that some socket doesn't transmit encrypted TLS data. Which of [these proxies](https://github.com/szmarczak/http2-wrapper#proxy-support) does Charles support?

It would help a lot if you can successfully make a request using `curl`. The command would tell a lot.

**Comment by zedd3v** [comment]
What's the status of using proxies with http2?
Is it stable yet?

**Comment by szmarczak** [comment]
Not yet.

**Comment by zedd3v** [comment]
Any eta? Or repository we can help?

**Comment by szmarczak** [comment]
Sure. Here's the exact directory https://github.com/szmarczak/http2-wrapper/tree/master/source/proxies of what needs to be tested (I'm using AVA as a test runner) and it's also missing TypeScript typings. Please note that is the `master` branch and not an actual release.

**Comment by szmarczak** [comment]
Regarding to the main subject of the issue, it depends on the proxy implementation. The directory mentioned above includes many of them.
