### ISSUE TITLE
Unexpected error for HEAD and 404 URLs

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/got#1357]
Hello,

I noted when a HEAD request is performed for a 404 URL, an unexpected error occurs.

#### Actual behavior

https://runkit.com/kikobeats/5f09864696e7a6001baff6a7

```js
const got = require('got')
const pReflect = require('p-reflect')

const result = await pReflect(got.head('https://www.sachadrake.com/images/assetimages/social_media_default.jpg'))

console.log(result)
```

#### Expected behavior

If the same code is performed using GET instead of HEAD, `got` returns the error:

```
HTTPError: Response code 404 (Not Found)
```

and that should be the expected behavior for the HEAD as well.

#### Details

Tested the bug thing is happening at `got@11.5.0` and any `got@11x` version.

**Comment by szmarczak** [comment]
I'm actually getting `RequestError: Parse Error: Expected HTTP/` and if I open the URL it says 404.

**Comment by szmarczak** [comment]
ah you mean actually that error
