### ISSUE TITLE
Document whether RequestError is the ancestor of all error classes

### ISSUE THREAD

**Issue by redneb** [sindresorhus/got#1358]
I was looking at `got`'s code and it appears that all errors thrown by it are of a class that is a subclass of `RequestError`. Am I correct about this? If so, I think it would be nice to make that fact part of the module's public api and add it to the documentation. This would allow users to determine if an exception they caught was thrown by `got` by testing whether the exception is an instance of `RequestError`.

**Comment by szmarczak** [comment]
Yes, you are correct. You can easily guess so from reading the first paragraph of https://github.com/sindresorhus/got#errors

A PR is welcome :)

**Comment by redneb** [comment]
Upon more careful inspection, I noticed that one of the possible exception class that can be thrown by `got` is `CancelError` which is a defined in `p-cancelable` and is thus *not* a subclass of `RequestError`.

**Comment by redneb** [comment]
Done #1359.
