### ISSUE TITLE
Too large backoff timeout

### ISSUE THREAD

**Issue by maxvipon** [sindresorhus/got#136]
Now the first retry takes ~2-2,5 sec. It's not acceptable in some cases when we load data from fast-response service with `timeout = 100 ms` and `retry = 2`
```js
function backoff(iter) {
	var noise = Math.random() * 1000;
	return (1 << iter) * 1000 + noise;
}
```
```
> backoff(1)
2581.360480748117
> backoff(1)
2050.7622794248164
> backoff(1)
2390.814026352018
> backoff(2)
4402.163911843672
> backoff(2)
4387.177913216874
> backoff(2)
4485.101141734049
```

Let's add some option for backoff quantize?

**Comment by sindresorhus** [comment]
I would prefer a solution that don't result in more options. How about just improving the default?

**Comment by maxvipon** [comment]
1000 → 100 ?

**Comment by floatdrop** [comment]
@maxvipon yes, something like this, I guess noise can be lower too. :+1:

**Comment by maxvipon** [comment]
@sindresorhus @floatdrop what about ability to use custom backoff function?

**Comment by sindresorhus** [comment]
Why? Does lowering it not solve your problem?

**Comment by maxvipon** [comment]
Because I think maybe 1sec timeout is good choice for most cases and
lowering it from 2sec to 100ms will solve my problem (though now I use 10ms
in my retry wrapper), but may occures little-ddos-like problem for others.

-- 
--
С уважением, Максим Пономарев
maxvipon@gmail.com

**Comment by maxvipon** [comment]
@floatdrop you decreased noise but not timeout))

**Comment by floatdrop** [comment]
@maxvipon `++` operator was moved before `retryCount` variable - https://github.com/sindresorhus/got/commit/54bd6f5bbad9590be6ffc7baf004c381bf1ea7a9#diff-168726dbe96b3ce427e7fedce31bb0bcR65 therefore delays will start from ~1s.
