### ISSUE TITLE
CancelError is not a descendant of RequestError

### ISSUE THREAD

**Issue by redneb** [sindresorhus/got#1362]
As discussed in #1358, it would be nice if all exceptions thrown by `got` descended from a single class. This would enable the users of the library to detect whether an exception they caught was thrown by `got` or not, with the help of the `instanceof` operator. Currently, all exceptions thrown by `got` descend from `RequestError` with the exception of `CancelError` which is defined in `p-cancelable` and is thus not a descendant of RequestError. Should we change that?

A counter argument would be that `CancelError`, unlike all other errors, is initiated by the user (with `.cancel()`) and not by `got`, so it is special in that way. Also, if we think of `p-cancelable` as a general purpose framework, it would make sense that it would behave consistently across all its uses.

FWIW, my preference would be to make `CancelError` is a descendant of `RequestError`.

**Comment by szmarczak** [comment]
> Currently, all exception thrown by got descend from RequestError with the exception of RequestError which is defined in p-cancelable and is thus not a descendant of RequestError.

I don't understand. Can you provide an example of an error which is named `RequestError` and `error instanceof got.

**Comment by redneb** [comment]
Oops, sorry, I meant `CancelError`. I updated my post and the title.

**Comment by redneb** [comment]
So @szmarczak, do you agree that it would be a good idea to make the change I propose? If so, I might take a look at it. The idea is to define our own `CancelError` in `got` and have `.cancel()` throw that error instead.

**Comment by szmarczak** [comment]
Yes, I do. We can throw our very own `CancelError` in a `onCancel` handler.
