### ISSUE TITLE
How can I force TLS?

### ISSUE THREAD

**Issue by QAnders** [sindresorhus/got#1365]
#### What would you like to discuss?

I am doing a HTTPS request to a server that clearly isn't doing things right... I am getting an error back:
`write EPROTO 140096394807168:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 40`

Which would indicate that it is trying to negotiate SSLv3 which isn't allowed.

We previously used the `https`module and could do `secureProtocol: 'TLSv1_method'` in the options.

Is there anything similar in GOT that could "force" it to use a supported SSL version?

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
Have you tried passing the `secureProtocol` option to Got?

**Comment by QAnders** [comment]
Thanks for the quick response, appreciated! 

Tried various combinations, yes, please see below:

```
async function sendRequest(requestData) {
  const key = process.env.SMP_PRIVKEY;
  const certificate = process.env.SMP_PUBKEY;
  const url = process.env.SMP_ENDPOINT;
  const postOptions = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/xml',
      Connection: 'Keep-Alive',
      'Content-Length': Buffer.byteLength(requestData)
    },
    https: {
      key,
      certificate,
      rejectUnauthorized: false
    }
    // strictSSL: false, // HAS NO EFFECT
    // secureProtocol: 'TLSv1_method' // HAS NO EFFECT
  };

  postOptions.body = requestData;
  try {
    const response = await got.post(
      url,
      postOptions
    );

    return response.body;
  } catch (error) {
     throw new Error(error);
  }
}
```

**Comment by szmarczak** [comment]
`strictSSL` is not a Got option. Try putting `secureProtocol` in `postOptions.https`. Please note that is a legacy option. In case it doesn't work, try passing `maxVersion` in `postOptions.https`.

**Comment by QAnders** [comment]
OK, thanks!

So I tried this first:
```
  https: {
      key,
      certificate,
      rejectUnauthorized: false,
      secureProtocol: 'TLSv1_method'
    }
```
No go though unfortunately, still the same error for SSLv3 handshake in the logs... 

So I instead tried this (and please correct me if I did it wrong):
```
  https: {
      key,
      certificate,
      rejectUnauthorized: false,
      maxVersion: 'TLSv1.2'
    }
```
Same thing though... :(

Also did try this, but no go:
```
    https: {
      key,
      certificate,
      rejectUnauthorized: false,
      minVersion: 'TLSv1.2',
      maxVersion: 'TLSv1.2'
    }
```

`write EPROTO 140295459993472:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 40`

**Comment by szmarczak** [comment]
Try `node --tls-max-v1.2 script.js`

**Comment by QAnders** [comment]
Ah, It's running in an AWS Lambda so I can't actually alter the runtime... I've raised a ticket with them to see if they have any suggestions...

**Comment by szmarczak** [comment]
> Ah, It's running in an AWS Lambda

What are the results if you run the scripts locally?

**Comment by cybairfly** [comment]
@szmarczak would like to ask what the conclusion was as I am currently facing the same problem and the node flag is not helping

**Comment by cybairfly** [comment]
Running got on node 16 and trying a request to HTTPS URL:

```
RequestError: write EPROTO 2792:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1546:SSL alert number 40

    at ClientRequest.<anonymous> (file:///D:/Code/Wolt/node_modules/.pnpm/got@13.0.0/node_modules/got/dist/source/core/index.js:792:107)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
```
