### ISSUE TITLE
Typescript issue with afterResponse hook

### ISSUE THREAD

**Issue by zedd3v** [sindresorhus/got#1366]
#### Describe the bug

 - Node.js version: 
 - OS & version: 

Typescript issue with afterResponse hook

#### Actual behavior

Type '(response: Response<unknown>) => Promise<string>' is not assignable to type 'AfterResponseHook'.
  Type 'Promise<string>' is not assignable to type 'Response<unknown> | CancelableRequest<Response<unknown>> | Promise<Response<unknown> | CancelableRequest<Response<unknown>>>'.
    Type 'Promise<string>' is not assignable to type 'Promise<Response<unknown> | CancelableRequest<Response<unknown>>>'.
      Type 'string' is not assignable to type 'Response<unknown> | CancelableRequest<Response<unknown>>'.

#### Expected behavior

Should work

#### Code to reproduce

```js
import got from "got";

const instance = got.extend({
	hooks: {
		afterResponse: [
			async (response) => {
				return instance(response.request.options);
			},
		],
	},
});
```

#### Checklist

- [✓] I have read the documentation.
- [✓] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
The TypeScript types are correct: https://github.com/sindresorhus/got#hooksafterresponse

**Comment by szmarczak** [comment]
Can you set up an example repository please?

**Comment by zedd3v** [comment]
Accidentally uploaded the wrong version, please recheck the code.

**Comment by szmarczak** [comment]
`instance` has many overloads, you need to cast it as `Promise<Response>`. You shouldn't call `instance(...)` in `afterResponse` because you may end up in an infinite loop.

**Comment by zedd3v** [comment]
> `instance` has many overloads, you need to cast it as `Promise<Response>`. You shouldn't call `instance(...)` in `afterResponse` because you may end up in an infinite loop.

Unfortunately, I have to do that, I have measures to protect
```js
const instance = got.extend({
	hooks: {
		afterResponse: [
			async (response) => {
				return instance(response.request.options) as Promise<Response>;
			},
		],
	},
});
```
Tried doing this but still same result

**Comment by szmarczak** [comment]
I've tried that and it worked. Can you set up an example repository? Why cannot you use the `retryWithMergedOptions` function?
