### ISSUE TITLE
Not possible to send query array parameter in coma separated format

### ISSUE THREAD

**Issue by pawelusfr** [sindresorhus/got#1368]
#### Describe the bug

 - Node.js version: 10.21.0
 - OS & version: -

I need to send a query parameter that is an array in comma separated format e.g. `htts://someurl.com?users=user1,user2`
In got 9.6.0 it was possible using `query-string` module as described in [documentation](https://github.com/sindresorhus/got/tree/v9.6.0#query)
In got 11.5.1 that part of documentation about `query-string` is gone and got will url escape the `searchParams` no matter what I try (query-string or URLSearchParams)

#### Actual behavior

got url escapes searchParams and will send the request to `http://someurl.com?users=user1%2Cuser2`

#### Expected behavior

got should not escape searchParams and send the request to `htts://someurl.com?users=user1,user2`

#### Code to reproduce

```js
const users = ['user1', 'user2'];
const result = got.get('http://someurl.com', {searchParams: new URLSearchParams({users})});
...
```

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by 414412** [comment]
return retryWithMergedOptions(updatedOptions);

**Comment by szmarczak** [comment]
You need to pass the search string in a URL:

```js
require('got').get('https://httpbin.org/anything?users=a,b,c').json();
```

**Comment by szmarczak** [comment]
That's because the search string doesn't have to be a query string.
