### ISSUE TITLE
`got` seems to be calling the wrong url instead of one we are providing. How can we narrow in on where the issue is?

### ISSUE THREAD

**Issue by ankurkaushal360** [sindresorhus/got#1369]
#### What would you like to discuss?
First of all, thank you for this awesome library! 

We have been using `got` for one of our service clients. We initialize `got` with the options on the application startup & expose an endpoint that calls a URL using `got` & is cached with `p-memoize`. 

Locally everything works fine. The issue happens on our TEST environment, where the service picks up different set of configs. We tried to log everything before call & the URL is correct.

**More Info**

The URL it tries to make call to is `127.0.0.1:80` & hence we end up getting `RequestError: connect ECONNREFUSED 127.0.0.1:80` in our TEST logs.

Our `package.json`:

```json
 "devDependencies": {
    "chai": "^4.2.0",
    "husky": "^4.2.5",
    "mocha": "^8.0.1",
    "mocha-teamcity-reporter": "^3.0.0",
    "nock": "^10.0.2",
    "nodemon": "^2.0.4",
    "nyc": "^15.1.0",
    "opener": "^1.5.1",
    "rimraf": "^3.0.2",
    "sinon": "^9.0.2",
    "snazzy": "^8.0.0",
    "standard": "^14.3.4",
    "stats-map": "^1.0.0"
  },
  "dependencies": {
    "cuid": "^2.1.8",
    "got": "^11.5.0",
    "lodash": "^4.17.19",
    "p-memoize": "^4.0.0",
    "quick-lru": "^5.1.1"
  }
```

Unfortunately I cannot share any code since it's proprietary code but all I am looking for is ideas to debug this. Is there a way or a library that can help us narrow down where / why it's happening?

#### Checklist

- [x] I have read the documentation.

**Comment by baconandon** [comment]
"We" had a similar issue which turned out to be caused by a dependency on an old version of Datadog's tracing library. HTH

**Comment by szmarczak** [comment]
What's your Node.js version in your test environment? Do you specify the agent option?

**Comment by ankurkaushal360** [comment]
@szmarczak We are on Node 12. As for the `agent` option, we didn't. We ended up finding that `datadog` was messing with the `http.request` & it was a matter of upgrading the `datadog` library.
