### ISSUE TITLE
`dnsCache: true` has no effect

### ISSUE THREAD

**Issue by ltagliamonte-dd** [sindresorhus/got#1372]
#### Describe the bug

 - Node.js version:  v12.16.1
 - OS & version: OSX 10.14.6

I'm trying to enable DNS cache for my app but looking at the DNS requests using tcdump the DNS TTL isn't respected.

#### Actual behavior

DNS TTL isn't respected

#### Expected behavior

DNS TTL is respected

#### Code to reproduce
npm install got
```js
const got = require('got');
setInterval(() => {
 got('https://google.com',{dnsCache: true}).then(response =>{
        console.log(`${response.body},`);
  });
}, 1000);

```

you can see the DNS requests going on using tcpdump:
```
tcpdump -i any -A  -vv port 53
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by alexvlasoff** [comment]
we have such bug in our applications

**Comment by known-as-bmf** [comment]
I think one workaround would be to provide your own `CacheableLookup` instance.

```ts
import got from 'got';
import CacheableLookup from 'cacheable-lookup';

const dnsCache = new CacheableLookup();

setInterval(() => {
 got('https://google.com', { dnsCache }).then(response =>{
        console.log(`${response.body},`);
  });
}, 1000);
```

**Comment by ltagliamonte-dd** [comment]
Thank you @known-as-bmf the workaround seems to work, but i'd like to see this fixed in got as well.
Any maintainers looking at this issue? @sindresorhus  @szmarczak ?

**Comment by szmarczak** [comment]
I'll look at this later today.

**Comment by szmarczak** [comment]
```js
const instance = got.extend({dnsCache: true});

instance('https://google.com').then(response =>{
	console.log(`${response.body.length}`);
});
```

Works. So that means `got('https://google.com', {dnsCache: true})` generates a new CacheableLookup instance **every time**. Fixing this now.

**Comment by szmarczak** [comment]
This also causes a memory leak. Good spot!

**Comment by ltagliamonte-dd** [comment]
@szmarczak thank you fixing this when can we have a release with the fix in it?

**Comment by szmarczak** [comment]
I'll do one tomorrow.

**Comment by ltagliamonte-dd** [comment]
@szmarczak sorry to bug you further, is there anything that is blocking a tag release?

**Comment by szmarczak** [comment]
Sorry it took so long. Released `11.5.2`.

**Comment by ltagliamonte-dd** [comment]
Thank you @szmarczak !

**Comment by szmarczak** [comment]
I got your email. I'm pretty sure I made also an NPM release... Weird, I access publish anymore and when I try to log in it loads indefinitely.

@sindresorhus Can you try to publish a new NPM version (`11.5.2`)?

**Comment by sindresorhus** [comment]
@szmarczak Done. I think it failed because npm had some downtime.

**Comment by ltagliamonte-dd** [comment]
thank you @sindresorhus and @szmarczak !
