### ISSUE TITLE
[FEA] chaining prefixUrl scopes or a mechanism to do so

### ISSUE THREAD

**Issue by lmeyerov** [sindresorhus/got#1375]
#### What problem are you trying to solve?

We like to nest route path scopes as part of building our api client through a module tree, and currently manually chain `prefixUrl`s outside of got as a `got` object gets passed through the tree's route constructors. `baseUrl` -> `module` -> `resource_set` -> ... .

The deeper issue may be the current behavior of `.extend()` is not really a generic compose operator. It's not `extend()` but `extendWithPolicyReplaceAlways()`, and we have a different policy for what extending means with a new `prefixUrl`. 

#### Describe the feature

Our workaround is a custom `extend`

```
function extendChaining (got, ...opts) {
    let out = got;
    opts.forEach(opt => {
        if (out.defaults.options.prefixUrl && opt.prefixUrl) {
            const prefix = out.defaults.options.prefixUrl.toString();
            const join = prefix.slice(-1) === '/' ? '' : '/';
            const prefixUrl = `${prefix}${join}${opt.prefixUrl}`;
            out = out.extend(opt).extend({prefixUrl});
        } else {
            out = out.extend(opt);
        }
    });
    return out;
}
```

(The full also has more error checking etc. as we're ok with slower construction speed.)

```
//across several files
baseGot = got.extend({'prefixUrl': cfg.BASE_PATH});
...
modGot = extendChaining(g1, {'prefixUrl': SERVICE})
...
mthdGot = extendChaining(modGot, {'prefixUrl': RESOURCE})
...
export {getter: mthdGot.extend({'method': 'GET', ...}), ...}
```

#### Alternatives

I can imagine nicer syntax (`.extendChaining()`), and generalizing to other fields/methods and policies (`.extendHook('prefixUrl', myFn)`), including user-defined. Likewise, we thought about doing somehow via `context`, but while the above looks less integrated, but lacking core support, it provides more stability. 

Another more specialized solution for this specific case may be to introduce something like `ExtendOption : {'subpath': str, ...}` which gets interpreted as as above if passed in, and throws an exn if `url` or `prefixUrl` are also supplied.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
We used to support this with the `baseUrl` option,  unfortunately we decided to drop this. See #783

The best you can do is:
```js
const instance = got.extend({
    prefixUrl: `${BASE_URL}${SERVICE}${RESOURCE}`
});
```
