### ISSUE TITLE
got http interceptors

### ISSUE THREAD

**Issue by yosiasz** [sindresorhus/got#1377]
#### What problem are you trying to solve?
Ability for  got to give me interceptors out of the box

```
got.post(url, options) to get session/token, intercept it
HttpInterceptorHandler here

//another controller
var options = {
  'sessionid': sessionFromHandler
}
got.get(url, options )
```
#### Describe the feature
When dealing with some rest api, there are many situations wherein I need to intercept session/tokens to be passed on to other routes downstream

- [ X] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Got supports hooks. Can you elaborate on how they don't work for your use-case?
