### ISSUE TITLE
useElectronNet When can support it

### ISSUE THREAD

**Issue by xinshangshangxin** [sindresorhus/got#1378]
#### What would you like to discuss?
I want to use `useElectronNet`  with latest version got
now i'm using version 9.x
...

#### Checklist

- [X] I have read the documentation.

**Comment by sindresorhus** [comment]
It's mentioned in the Got release notes why that option was removed.

**Comment by xinshangshangxin** [comment]
I just found doc

[`The deprecated useElectronNet option has been removed.`](https://github.com/sindresorhus/got/releases/tag/v11.0.0-beta.1)

but i donn't know why
