### ISSUE TITLE
Accept backoff function in `retries` option

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#138]
From #136:

Now `retry` option accepts only number of retries. Idea is to pass function to `retries`, which will return delay of retry or `false` (if retry is not needed):

```js
// Constant delay of 10ms for 5 iterations
got('google.com', {
    retries: iter => iter < 5 && 10
});

// Infinity retries with constant delay - this is not possible now, 
// because delay will increase up to the MaxInt :(
got('google.com', {
    retries: () => 10
});
```

I think this will cover like 99% of usecases and will not introduce new option.

**Comment by sindresorhus** [comment]
I guess this is a good compromise and frees us from more requests about retries.

**Comment by sindresorhus** [comment]
Shouldn't it be `0` and not `false`?

**Comment by floatdrop** [comment]
> Shouldn't it be 0 and not false?

@sindresorhus maybe. Would it be confusing, if `retries: () => 0` will disable retries? Wouldn't `retries: () => false` be more readable/expectable?

**Comment by sindresorhus** [comment]
@floatdrop Those aren't realistic examples, though. For both of those you would just do `retries: 0` instead. The thought with `0` is that it's already using numbers, so we keep it to one type.

@maxvipon Thoughts on this?

**Comment by maxvipon** [comment]
In my opinion `retrues: () => 0` and `retries: () => false` are the same
