### ISSUE TITLE
timings object has null values

### ISSUE THREAD

**Issue by joergd** [sindresorhus/got#1388]
#### Describe the bug

 - Node.js version: 14.5.0
 - Got version: 11.5.1

#### Actual behavior

When I do a stream GET request, the "response" event listener has the timings.end (and phases.download) values set to null.

    {
      start: 1596617145631,
      socket: 1596617145637,
      lookup: 1596617145637,
      connect: 1596617145663,
      secureConnect: 1596617145686,
      upload: 1596617145686,
      response: 1596617146117,
      end: undefined,
      error: undefined,
      abort: undefined,
      phases: {
        wait: 6,
        dns: 0,
        tcp: 26,
        tls: 23,
        request: 0,
        firstByte: 431,
        download: undefined,
        total: undefined
      }
    }

#### Expected behavior

I expect those values to not be null, so that I can see the total request time.

#### Code to reproduce

```js
    const got = require("got");

    got
      .stream(
        "https://raw.githubusercontent.com/sindresorhus/got/master/media/logo.svg",
        {}
      )
      .on("response", response => {
        console.info(response.timings);
      });
```

This should work right?

**Comment by szmarczak** [comment]
This works as expected. You haven't read the stream so `end` is `undefined`. Also the `response` event is emitted  when the headers are received, not when it is fully read.

Try attaching a listener to the `end` event and log `gotStream.timings`.
