### ISSUE TITLE
Add an example of nock integration with retrying

### ISSUE THREAD

**Issue by tomkoufakis** [sindresorhus/got#1392]
#### Describe the bug

 - Node.js version: 10.15.3
 - OS & version: Mac OSX 10.14.6
 - nock version: 13.0.3
 - got version: 11.5.1

When running unit tests against Got, I am using nock as a mocking framework. When I run the test, I get nock errors. I have disabled all other tests except for this one. The mocked request returns a status code of 503.

#### Actual behavior

The test results in a nock error with HTTP status code of 500:

expected 'Nock: No match for request {\n  "method": "GET",\n  "url": "http://local/path3",\n  "headers": {\n    "user-agent": "got (https://github.com/sindresorhus/got)",\n    "x-rdc-correlation-id": "560ade99-30cc-4940-8683-4af03b8b7cb4",\n    "x-amzn-trace-id": "GQL=560ade99-30cc-4940-8683-4af03b8b7cb4",\n    "accept-encoding": "gzip, deflate"\n  }\n}' to equal 'error message'
...

#### Expected behavior

The test should pass with HTTP status code of 503.

...

#### Code to reproduce

See the repo: https://github.com/tomkoufakis/got-test-bug

**NOTE: I have tested the same code using node-fetch and it works successfully. This indicates it is a Got issue. See: https://github.com/tomkoufakis/got-test-bug/tree/node-fetch**

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you please point out what exactly is failing so I don't have to run the tests (I'll run them anyway because I have no other option)? Please try to provide as much information as you can when opening an issue.

> The test should pass with HTTP status code of 503.

It doesn't give any new information.

**Comment by szmarczak** [comment]
> https://github.com/sindresorhus/got#api

![image](https://user-images.githubusercontent.com/36894700/89483922-8803a900-d79d-11ea-8d54-24cb05a3da04.png)

I don't think we can make this more clear...

**Comment by tomkoufakis** [comment]
@szmarczak it wasn't immediately clear how your comments were related to my bug report. However it dawned on my that because of the retry mechanism, nock would later clear the response mapping and throw the error.

How you can make this more clear, is to add something about this in your section on Testing. The examples there do not set the retry value to 0 thereby making your samples incorrect. Please either update the sample code to include this or add a comment about retry in the Testing section in order to tie these two things together as it is not clear.

**Comment by szmarczak** [comment]
> nock would later clear the response mapping and throw the error.

It's your responsibility to know the nock API and how it works. The issue tracker here is NOT meant to help people having basic issues.

> How you can make this more clear, is to add something about this in your section on Testing. The examples there do not set the retry value to 0 thereby making your samples incorrect. Please either update the sample code to include this or add a comment about retry in the Testing section in order to tie these two things together as it is not clear.

This is precious feedback. Thanks.
