### ISSUE TITLE
TS2339: Property 'body' does not exist on type 'CancelableRequest<Response<...>>'

### ISSUE THREAD

**Issue by akopchinskiy** [sindresorhus/got#1398]
#### Describe the bug

Type issue.
`error TS2339: Property 'body' does not exist on type 'CancelableRequest<Response<unknown>>'.`

 - Node.js version: 14.7.0
 - OS & version: Win 10
 - got: 11.5.2

#### Actual behavior

```ts
await got.get('https://api.com/qwerty', {
            method: 'GET',
            headers: {
                'Authorization': `Bearer ${ token }`
            },
            responseType: 'json'
        });  
```

#### Expected behavior

...

#### Code to reproduce

```ts
await got.get('https://api.com/qwerty', {
            method: 'GET',
            headers: {
                'Authorization': `Bearer ${ token }`
            },
            responseType: 'json'
        }); 
```

**Comment by szmarczak** [comment]
Can you please include full reproducible code? You don't access the `body` property in your example so this bug report is invalid.

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and we'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.
