### ISSUE TITLE
Javascript heap out of memory 11.5.1 -> 11.5.2

### ISSUE THREAD

**Issue by pcorey** [sindresorhus/got#1402]
#### Describe the bug

 - Node.js version: `v12.16.1`
 - OS & version: Some kind of `Linux_x86_64` running on Semaphore. MacOS Catalina (10.15) locally.

I'm afraid this isn't going to be an incredibly helpful bug report since I don't have a minimal reproduction, but after upgrading from `11.5.1` to `11.5.2`, our long running test suite consistently fails with a heap memory exception.

#### Actual behavior

After upgrading from `got@11.5.1` to `got@11.5.2`, with no other changes, our long-running test suite fails with a "Javascript heap out of memory" error.

```
<--- Last few GCs --->
--
546 |  
548 | [4153:0x3c4c600]   153786 ms: Scavenge 1942.1 (1970.7) -> 1941.7 (1970.9) MB, 11.8 / 0.0 ms  (average mu = 0.333, current mu = 0.471) allocation failure
549 | [4153:0x3c4c600]   153814 ms: Scavenge 1942.5 (1970.9) -> 1942.0 (1971.2) MB, 11.5 / 0.0 ms  (average mu = 0.333, current mu = 0.471) allocation failure
550 | [4153:0x3c4c600]   153840 ms: Scavenge 1943.0 (1971.4) -> 1942.5 (1971.4) MB, 11.0 / 0.0 ms  (average mu = 0.333, current mu = 0.471) allocation failure
550 |  
551 |  
552 | <--- JS stacktrace --->
553 |  
555 | ==== JS stack trace =========================================
555 |  
556 | 0: ExitFrame [pc: 0x13a71b9]
558 | 1: StubFrame [pc: 0x132d357]
558 | Security context: 0x025e311008d1 <JSObject>
560 | 2: isValidSchema(aka isValidSchema) [0x2559f5d0fac1] [/home/semaphore/project/node_modules/fast-json-stringify/index.js:27] [bytecode=0x18c75e87f601 offset=5](this=0x0aeda61c04b1 <undefined>,0x1a0fdb4e2bf9 <Object map = 0x11264b080899>,0x0aeda61c04b1 <undefined>)
560 | 3: build(aka build) [0x2559f5d2c831] [/home/semaphore/i...
561 |  
563 | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
564 | 1: 0x9ef190 node::Abort() [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
565 | 2: 0x9f13b2 node::OnFatalError(char const*, char const*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
566 | 3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
567 | 4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
568 | 5: 0xd0a765  [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
569 | 6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
570 | 7: 0xd1760a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
571 | 8: 0xd18515 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
572 | 9: 0xd1afcc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
573 | 10: 0xce254e v8::internal::Factory::NewFixedArrayWithHoles(int, v8::internal::AllocationType) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
574 | 11: 0xdea094 v8::internal::interpreter::ConstantArrayBuilder::ToFixedArray(v8::internal::Isolate*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
575 | 12: 0xdccda1 v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray(v8::internal::Isolate*, int, int, v8::internal::Handle<v8::internal::ByteArray>) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
576 | 13: 0xdbf7e1 v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray(v8::internal::Isolate*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
577 | 14: 0xdd17bc v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Script>) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
578 | 15: 0xdee78c v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
579 | 16: 0xc33c18  [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
580 | 17: 0xc36a83  [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
581 | 18: 0xc373fb v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
582 | 19: 0xc39d6e v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
583 | 20: 0x100acf2 v8::internal::Runtime_CompileLazy(int, unsigned long*, v8::internal::Isolate*) [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
583 | 21: 0x13a71b9  [/home/semaphore/.nvm/versions/node/v12.16.1/bin/node]
584 | Aborted
```

#### Expected behavior

I would expect the test suite to complete successfully, as it did with `11.5.1`.

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
What happens if you update to Node.js 14.7.0?

**Comment by pcorey** [comment]
@szmarczak We've tried with the latest Node.js stable version (`14.8.0`) and it still fails with a "heap out of memory" error when running `got@11.5.2`. The suite runs successfully with Node 14 if we downgrade to `got@11.5.1`.

**Comment by szmarczak** [comment]
Thanks. Will check this out today.

**Comment by szmarczak** [comment]
Sorry it took so long. I've just checked and there's no way it's Got's fault. Are you running Jest? It's known for causing many problems in Got. Are you sure you are not using https://github.com/sindresorhus/import-fresh nor https://github.com/bevry/requirefresh?

**Comment by szmarczak** [comment]
Also try running latest Node.js 14.

**Comment by pcorey** [comment]
@szmarczak Looking through the commits in the 11.5.1 -> 11.5.2 patch, I agree that it doesn't seem like they could be causing this. It's just strange that bumping the patch version, with no other changes, consistently causes our suite to fail.

I'm not directly using `import-fresh` or `requirefresh`, but `import-fresh` is a transitive dependency used by a few other packages in our project.

I have tried the latest Node.js 14. No change.

I'll try poking around a bit more, and/or making a minimal reproduction. I imagine you're right and the problem is related to Jest's behavior of creating an isolated require cache for every test file, but I can't imagine what Got would be doing to blow the heap, even when required hundred of times.

Thanks for looking into this.

**Comment by szmarczak** [comment]
If you're not using DNS cache you can try setting `globalDnsCache` to `undefined` (source/core/index.ts I think). Maybe Node.js doesn't clean it up.

**Comment by szmarczak** [comment]
Or Jest still holds a reference to it.

**Comment by pcorey** [comment]
Yeah, changing `globalDnsCache` to `undefined` fixes the problem. Looks like it's related to these issues:

https://github.com/szmarczak/cacheable-lookup/issues/19
https://github.com/facebook/jest/issues/6423

Apparently the `dns` module isn't properly cleaning up after itself?

To fix my suite, I just mock `cacheable-lookup` in a global setup file, since I have no way of preventing `CachableLookup` from being initialized without forking the repo.

```js
jest.mock('cacheable-lookup');
```

Hopefully whatever's wrong with the `dns` module will be figured out eventually and I can remove this mock. But until then I'll just close out this issue. Thanks for your help @szmarczak!
