### ISSUE TITLE
Can't resolve optional dependency Electron

### ISSUE THREAD

**Issue by DivisionSi** [sindresorhus/got#1404]
#### Describe the bug
Webpack can't resolve optional dependancy:
```
if (opts.useElectronNet && process.versions.electron) {
	const electron = require('electron');
	fn = electron.net || electron.remote.net;
}		
```
I went over this [issue](https://github.com/sindresorhus/got/issues/345) and saw your commit to version 8.x to supress Electron requirement by setting it to false [here](https://github.com/sindresorhus/got/commit/e871099c4663be41995d742d7969ffe53b4f1303#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) but I am still getting the same error when compiling with webpack.

Although I have tried using ignore plugin at my end as well:
    `new webpack.IgnorePlugin(/^electron$/)`
but it didn't work, and I think with your update, this should not even be required at my end.

#### Actual behavior
```
  ./node_modules/openid-client/node_modules/got/index.js 91:20-39
  Can't copy external package "electron" because it is not a direct dependency.
  To fix this, run npm install -P electron
   @ ./node_modules/openid-client/lib/helpers/http.js
   @ ./node_modules/openid-client/lib/issuer.js
   @ ./node_modules/openid-client/lib/index.js
   @ ./lib/source/backend/auth/AuthenticationClient.js
   @ ./lib/source/backend/main.js
   @ multi ./lib/source/backend/main.js
```
...

#### Expected behavior
No error and optional dependency ignored. 

Versions:
**got**: 9.6.0
**openid**-client: 2.5.0

**Comment by sindresorhus** [comment]
This should no longer be a problem with the latest Got version.
