### ISSUE TITLE
Document `stream.options`

### ISSUE THREAD

**Issue by electerious** [sindresorhus/got#1405]
#### What would you like to discuss?

I would like to log the request body/json when an error occurs because it makes it easy to reproduce the failed request. I know that I can log the response body with `err.response.body`, but can't find a way to do so with the request body.

How can I log the body of the request?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Can you try `error.request.options.body`?

**Comment by electerious** [comment]
`error.request.options.body` is `undefined`

**Comment by szmarczak** [comment]
Then you must've done something wrong. https://runkit.com/szmarczak/5f2c9b65c39ec50014a13e48

**Comment by szmarczak** [comment]
Actually we need to document `error.request` because it's undocumented.

**Comment by szmarczak** [comment]
Actually it's documented. But `stream.options` is not documented...

**Comment by electerious** [comment]
This issue was that I've provided the data via `json` and therefore need to use `error.options.json`.
