### ISSUE TITLE
Do not send `content-length` header when `methodRewriting` is `false`

### ISSUE THREAD

**Issue by playnation81** [sindresorhus/got#1406]
#### Describe the bug

 - Got version: 11.5.2
 - Node.js version: 14.8.0
 - OS & version: Windows 10 Pro 1909

#### Actual behavior
Empty body request with header[content-length > 0] was sent when got a 302(Found) response status code after submitting POST request.

#### Expected behavior
Send empty body request without header[content-length] when got a 302(Found) response status code after submitting POST request.

#### Additional Info
`Content-Length` (if required and present) must be the size of the body of the request.
Which was mentioned by @Giotino in https://github.com/sindresorhus/got/issues/1258#issuecomment-627794239_

#### Code to reproduce

```javascript
const got = require('got');

(async () => {
  try {
    const res = await got({
      url: `http://httpstat.us/302`,
      method: 'POST',
      methodRewriting: false,
      form: { aaa: 'bbb' },
    });
  } catch (err) {
    console.log(err);
  }
})();
```

#### Temporary solution
Adding a hooks.beforeRedirect to delete the `Content-Length` header.

```javascript
const got = require('got');

(async () => {
  try {
    const res = await got({
      url: `http://httpstat.us/302`,
      method: 'POST',
      methodRewriting: false,
      form: { aaa: 'bbb' },
      hooks: {
        beforeRedirect: [
          (options, response) => {
            options.headers['content-length'] &&
              delete options.headers['content-length'];
          },
        ],
      },
    });
  } catch (err) {
    console.log(err);
  }
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
>     A user agent SHOULD send a Content-Length in a request message when
>    no Transfer-Encoding is sent and the request method defines a meaning
>    for an enclosed payload body.  For example, a Content-Length header
>    field is normally sent in a POST request even when the value is 0
>    (indicating an empty payload body).

https://tools.ietf.org/html/rfc7230#section-3.3.2

**Comment by playnation81** [comment]
Sorry, I forgot to mention that I disabled the `methodRewriting` option.
Which means the redirected request would be a GET request and the body has been removed.

`The body is removed if you disable method rewriting.`
_Originally posted by @szmarczak in https://github.com/sindresorhus/got/issues/1271#issuecomment-629757169_

```
A user agent SHOULD NOT send a
Content-Length header field when the request message does not contain
a payload body and the method semantics do not anticipate such a
body.
```
https://tools.ietf.org/html/rfc7230#section-3.3.2
