### ISSUE TITLE
How can I get a JSON respond after the POST streaming is done. 

### ISSUE THREAD

**Issue by amitm02** [sindresorhus/got#1407]
How can I get a JSON respond after the POST streaming is done. 
E.g how can I get the resend from the POST request of 'https://sindresorhus.com' in the following code?

```
const stream = require('stream');
const {promisify} = require('util');
const fs = require('fs');
const got = require('got');

const pipeline = promisify(stream.pipeline);

(async () => {
    // For POST, PUT, and PATCH methods `got.stream` returns a `stream.Writable`
    await pipeline(
        fs.createReadStream('index.html'),
        got.stream.post('https://sindresorhus.com')
    );
})();
```

**Comment by szmarczak** [comment]
Use something like [`get-stream`](https://github.com/sindresorhus/get-stream).

**Comment by amitm02** [comment]
I do not understand. 
To my knowledge get-stream does not work with pipeline, so how it can be used in the above example?

**Comment by szmarczak** [comment]
> To my knowledge get-stream does not work with pipeline

Where did you get that info?

> how it can be used in the above example?

Just call it and as the first argument pass the result of `stream.pipeline(...)`.

**Comment by amitm02** [comment]
I get it now. I've kept the "promisfiy pipline" from the example:
`const pipeline = promisify(stream.pipeline);`
Which returns `Promise<void>`. the get-stream should wrap native pipeline.

I do suggest to add such an example in the docs. It can't be a rare use case.

**Comment by szmarczak** [comment]
Yeah but it's just pure Node.js API and Got is not a tutorial for Node.js.

**Comment by amitm02** [comment]
That may be, but 1) it is a common use case for the library 2) not trivial to implement (for instance a 3rd party library is needed).
Your comment was very helpful for me. I believe that it will help many others if it will be in the docs.
For the similar reason there is this example code (https://github.com/sindresorhus/got#streams). 
Any way, that is my line of thinking,  feel free to disregard :)

**Comment by szmarczak** [comment]
Many many issues opened in this repository could be solved just by reading Node.js docs. This is not a place to demonstrate what Node.js offers.
