### ISSUE TITLE
`beforeRequest` doesn't merge `options.json`

### ISSUE THREAD

**Issue by nghiepit** [sindresorhus/got#1408]
Hi,

I have custom `options.json` in `beforeRequest` hook, but it not working well.

#### Describe the bug

 - Node.js version: ^14
 - OS & version: macOS
 - Got: ^11.5.2

#### Actual behavior
```js
import got from 'got';

const client = got.extend({
  prefixUrl: 'https://domain.com',
  hooks: {
    beforeRequest: [
      options => {
        if (options.method === 'post' || options.method === 'POST') {
          options.json = options.json ?? {};
          options.json.myValue = 'newValue';

          // Debug here: I see data correctly
          console.log(options.json);
        }
      },
    ],
  },
});

client.post('my-api", {
  json: {
    ok: "ok"
  }
});
```

In fact, `myValue` doesn't merge with options.json data.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Because it's converted into `options.body`.

**Comment by nghiepit** [comment]
Is there ways to merge with `options.json` instance defaults?

**Comment by szmarczak** [comment]
Try this:

```js
const client = got.extend({
  prefixUrl: 'https://domain.com',
  hooks: {
    beforeRequest: [
      options => {
        if (options.method === 'post' || options.method === 'POST') {
          options.json = options.json ?? {};
          options.json.myValue = 'newValue';
		  options.body = JSON.stringify(options.json);
        }
      },
    ],
  },
});
```

**Comment by szmarczak** [comment]
I think you should use the `init` hook instead. Let me know if that fixes the issue.

**Comment by nghiepit** [comment]
`options.body = JSON.stringify(options.json);` doesn't work.

I cant' use the `init` hook. Because the `options.context` in the  `init` hook is undefined.
I need some data in `context`.

**Comment by szmarczak** [comment]
I think we can pass a `Proxy` instance instead and normalize the options again if something changes.

**Comment by Giotino** [comment]
> options.body = JSON.stringify(options.json); doesn't work.

Same problem here, also some explanations:
https://github.com/sindresorhus/got/issues/1427#issuecomment-682412401

**Comment by szmarczak** [comment]
> options.body = JSON.stringify(options.json); doesn't work.

Ah... I just forgot that:

> Because it's converted into options.body.

So you'd have to

```js
const client = got.extend({
  prefixUrl: 'https://domain.com',
  hooks: {
    beforeRequest: [
      options => {
        if (options.method === 'post' || options.method === 'POST') {
          options.json = JSON.parse(options.body);
          options.json.myValue = 'newValue';
		  options.body = JSON.stringify(options.json);
        }
      },
    ],
  },
});
```

> I cant' use the init hook. Because the options.context in the init hook is undefined.

In the upcoming release this will be possible. The `init` hook now accepts a second argument: `self`. So if `context` is defined in the instance, you can access `context` via `self.context`.

<hr>

Yet another solution is to use the `stringifyJson` option.

<hr>

Another way is to pass the body in the `context` and stringify it inside `beforeRequest` hooks. Note that you will have to update the `content-length` header as well.
