### ISSUE TITLE
Uncaught errors when using timeout option in the browser

### ISSUE THREAD

**Issue by ncuillery** [sindresorhus/got#141]
When using the `timeout` option, the following code causes 2 uncaught errors:

```javascript
got('/rest/rules', {timeout: 5000}, function () {
  [...]
});
```

![capture du 2015-12-06 18 25 16](https://cloud.githubusercontent.com/assets/4425455/11614573/d6f7150c-9c46-11e5-9cca-61489c833f38.png)

The last one appears once the timeout is elapsed.

Maybe it is related to #127

**Comment by floatdrop** [comment]
Seems like `http` polyfil is lacking some methods on request object. Hard to say without knowing your build steps.

**Comment by floatdrop** [comment]
It works with browserify@12 and got@6:

```js
global.setImmediate = setTimeout;
const got = require('got');
got('/bundle.js', {timeout: 5000})
    .then(res => {
        console.log(res.body.length);
    })
    .catch(err => {
        console.error(err);
    });
```

At least I see `setTimeout` method here - https://github.com/jhiesey/stream-http/blame/master/lib/request.js#L248. If you are using different `http` module polyfill - you can try to open issue about `setTimeout` method there.
