### ISSUE TITLE
Hostname/IP does not match certificate's altnames: Cert is empty | Crawlera

### ISSUE THREAD

**Issue by octalpixel** [sindresorhus/got#1413]
#### Describe the bug

 - Node.js version: 12.11
 - OS & version:  Ubuntu | AWS

I have the following issues in term of using a proxy service ("crawlera"). I get the following error
RequestError: Hostname/IP does not match certificate's altnames: Cert is empty. Using tunnel (https://www.npmjs.com/package/tunnel) to send httpsOverHttp. The issue only persist when the scraper is moved to AWS.

#### Actual behavior
Getting the follow error
`RequestError: Hostname/IP does not match certificate's altnames: Cert is empty at ClientRequest.<anonymous> (/home/ubuntu/project/scrape-test/node_modules/got/dist/source/core/index.js:891:25) at Object.onceWrapper (events.js:300:26) at ClientRequest.emit (events.js:215:7) at ClientRequest.origin.emit (/home/ubuntu/project/scrape-test/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20) at TLSSocket.socketErrorListener (_http_client.js:406:9) at TLSSocket.emit (events.js:210:5) at emitErrorNT (internal/streams/destroy.js:91:8) at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) at processTicksAndRejections (internal/process/task_queues.js:80:21) at Object.checkServerIdentity (tls.js:279:12) at TLSSocket.onConnectSecure (_tls_wrap.js:1328:27) at TLSSocket.emit (events.js:210:5) at TLSSocket._finishInit (_tls_wrap.js:792:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) { name: 'RequestError', code: 'ERR_TLS_CERT_ALTNAME_INVALID', timings: { start: 1597835558025, socket: 1597835558122, lookup: 1597835558122, connect: 1597835558122, secureConnect: undefined, upload: undefined, response: undefined, end: undefined, error: 1597835558209, abort: undefined, phases: { wait: 97, dns: 0, tcp: 0, tls: undefined, request: undefined, firstByte: undefined, download: undefined, total: 184 } } }`
...

#### Expected behavior
Returns the expected HTML
...

#### Code to reproduce

```js
var tunnel = require('tunnel');
const got = require('got');

const certPath  =  path.join(__dirname,"/crawlera-ca.crt")
var tunnelingAgent = tunnel.httpsOverHttp({
    ca: [ fs.readFileSync(certPath)],
    proxy: { // Proxy settings
      host: process.env.PROXY_HOST, // Defaults to 'localhost'
      port: process.env.PROXY_PORT, // Defaults to 80  
      proxyAuth: process.env.PROXY_AUTH,
    }
  });

const getGot = async (url) => {

    try {
        const response  = await got(url,{
            agent: {
                https: tunnelingAgent
            }
        });
        const body =  response.body

        console.log(`boody -->`,body);
    } catch (error) {
        console.log(error);
        return null
    }

}

Calling the getGot function will throw the error

...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
I'm a little confused, why are you trying to use the crawlera CA if you're connecting to some server (origin server) through crawlera (proxy server) via HTTP?

I never used the module `tunnel`, but looking at the documentation
> // CA for origin server if necessary
> ca: [ fs.readFileSync('origin-server-ca.pem')],

You can see that the CA is for the origin server and not the proxy server.

**Comment by szmarczak** [comment]
This is not a Got bug.
