### ISSUE TITLE
using typescript, jest and http2:true causes RequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by ssypi** [sindresorhus/got#1414]
#### Describe the bug

http2:true option causes error when using got inside tests with jest and typescript.

 - Node.js version: 14.8.0
 - OS & version: macOS Catalina 10.15.4
 - got version 11.5.2

I saw some other ECONNREFUSED issues where the problem was old version of agent-base, but I have very simple list of dependencies and "npm ls agent-base" found nothing.

The same code works without jest so maybe it's not necessarily got's fault, but I'd like some help pinpointing the problem. 

dependencies in the test repo:

```
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-typescript": "^7.10.4",
    "got": "^11.5.2",
    "jest": "^26.4.0",
    "typescript": "^3.9.7"
```

Possibly one of these causes the problem, all are the latest versions though.

#### Actual behavior

```await got("https://google.com", {http2: true});```
throws error  
RequestError: connect ECONNREFUSED 127.0.0.1:443

#### Expected behavior

Should work. Works if http2 is false. Also works if running the typescript code without jest.

#### Code to reproduce

I have created a simple repo at https://github.com/ssypi/got-http2-jest

Just clone, npm install and run npm test.

There are two tests inside tests/test.ts, one with http2: true which errors and one without http2 which works.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by mwallace72** [comment]
Is https://github.com/szmarczak/http2-wrapper/pull/50 with latest 11.8.0? I'm using that release and experiencing this.

**Comment by szmarczak** [comment]
Not yet. Anyway HTTP/2 is still buggy on Node.js' side, therefore I do not recommend running it on production.

**Comment by mwallace72** [comment]
Oh I'm sorry - I must have read this wrong, I was seeing this error message, but without using `{http2: true}`. My mistake.

**Comment by szmarczak** [comment]
Then I'm 100% sure there is an old version of agent-base in your dependencies.
