### ISSUE TITLE
Are there any parameters to tune for better performance?

### ISSUE THREAD

**Issue by AjayChoudary** [sindresorhus/got#1418]
We used request module in every project from last 7 years, and now it got deprecated.
For compliance we have to migrate all those projects to a new library.

Readme is showing the impressive [comparison](https://github.com/sindresorhus/got#comparison)
But I am more worried about these [benchmarks](https://github.com/gevorggalstyan/http-request-libraries-benchmarks)

#### What would you like to discuss?
For us performance is the key factor for choosing a library than number of features
I would like to see the benchmarks against node-fetch with different preferences (cache, retries, http2, etc)

#### Checklist

- [ ] I have read the documentation.

**Comment by szmarczak** [comment]
We have our benchmarks too:

https://github.com/sindresorhus/got/blob/0d43f5fea0460977089236b58f2354307fbf27fc/benchmark/index.ts#L182-L196

And as you can see, normalizing options has some impact. This is necessary as we provide hooks and the options must be normalized there. Other HTTP clients don't do this, which is a flaw.

> Readme is showing the impressive comparison
> But I am more worried about these benchmarks

Then you aren't looking for Node.JS. Use low-level programming language like C++ instead. Or write your own HTTP client which meets your needs. 3k req/s is enough for most applications. If you still insist on Node.JS, then use workers or clusters. Or you could go serverless.

**Comment by szmarczak** [comment]
Also you may be interested in https://github.com/mcollina/undici which is much much faster than the native Node.js http module.
