### ISSUE TITLE
Close the connection.

### ISSUE THREAD

**Issue by pdonias** [sindresorhus/got#142]
I am using `got.stream()` with a big amount of data and the action may be interrupted. So I would like to be able to close the connection before having received the whole response.

**Comment by floatdrop** [comment]
Something like this should work:

```js
let response;
got.stream('...').on('response', res => response = res);
setTimeout(() => res.destroy(), 1000);
```

**Comment by julien-f** [comment]
@floatdrop Where is `IncomingMessage#destroy()` documented? The only thing I found in the documentation is `ClientRequest#abort()`…

**Comment by floatdrop** [comment]
@julien-f my bad, [`request.abort()`](https://nodejs.org/api/http.html#http_request_abort) is right method for it.

**Comment by julien-f** [comment]
Unfortunatly, I don't think there is a way to access it with got :/

**Comment by floatdrop** [comment]
@julien-f why so? We are [emitting it](https://github.com/sindresorhus/got/blob/master/index.js#L158) on stream.

**Comment by julien-f** [comment]
My bad :)

**Comment by sindresorhus** [comment]
@floatdrop I think we should document it, for clarity.

**Comment by floatdrop** [comment]
@sindresorhus [already are](https://github.com/sindresorhus/got#onrequest-request).

**Comment by julien-f** [comment]
It [already is](https://github.com/sindresorhus/got#onrequest-request) :)

**Comment by floatdrop** [comment]
@sindresorhus or you are talking about additional `Aborting stream` section in readme?

**Comment by sindresorhus** [comment]
Yes, but we don't linkify the `response` to the corresponding Node.js docs (we should do this too), and even if we did I think it's worth be explicit about it as the Node.js docs are pretty messy. Just to make it simple for people.

**Comment by sindresorhus** [comment]
> or you are talking about additional Aborting stream section in readme?

Yes. Doesn't have to be a section, could just be somewhere in the docs as a tip or something.

**Comment by julien-f** [comment]
So there is a way to abort the connection in stream mode but what is the equivalent in promise mode?

**Comment by sindresorhus** [comment]
@julien-f Promises can't yet be cancelled. https://twitter.com/phuunet/status/668576359728422912

**Comment by julien-f** [comment]
In a project of mine, I solved this issue using [a `@cancellable` decorator](https://github.com/vatesfr/xo-server/commit/5c614383354067090236f65c8ab0f4e20bac497b#diff-7e7d3b9c861502c26b4533b7a3fb26e7R70) which injects a cancellation promise as a first argument and augment the returned promise with a `cancel()` method.
