### ISSUE TITLE
The type on BeforeRetryHook shouldn't contain any optional parameters

### ISSUE THREAD

**Issue by alvis** [sindresorhus/got#1420]
#### Describe the bug

In the typescript definition of `BeforeRetryHook`, `error` and `retryCount` are declared as optional, meaning they're potentially `undefined`. However, it's not true.

https://github.com/sindresorhus/got/blob/0d43f5fea0460977089236b58f2354307fbf27fc/source/core/index.ts#L107

#### Actual behavior

`error` and `retryCount` contains the `undefined` type

#### Expected behavior

`error` and `retryCount` should be just simply `RequestError` and `number`

**Comment by alvis** [comment]
Sorry I have an oversight on the documentation. It's now clear to me that `beforeRetry` may be called with only the `options` parameter when a response is updated. For instant, updating an access token and retry.
See https://github.com/sindresorhus/got#hooksbeforeretry

The implementation can be found below. The hook is passed with only the options but not any error and retry count
https://github.com/sindresorhus/got/blob/1f132e88b4e9b295631637757d64307032a4e56e/source/as-promise/index.ts#L107-L110

**Comment by szmarczak** [comment]
There is no `retryCount`.

**Comment by szmarczak** [comment]
Yeah, but I think we could at least add retry count in that case.

**Comment by szmarczak** [comment]
Actually it's correct. It should be missing since it's not classic retrying. But I'm not sure whether we should call `beforeRetry` hook or not. Anyway, you can make a check and if `retryCount` is missing then you know it's from `afterResponse`.

**Comment by alvis** [comment]
My 2cents, but maybe it'll make the usage clearer by separating this special case to another hook in the next version? e.g. `beforeRetryAfterResponseChange`. `beforeRetry` for a classic automatic retry, and `beforeRetryAfterResponseChange` for a programmatic retry?

**Comment by sindresorhus** [comment]
I agree the current situation could be improved, but I'm not sold on a `beforeRetryAfterResponseChange` hook either. I'm going to keep this issue open for alternative proposals on how to improve the situation.

**Comment by szmarczak** [comment]
Fixed in #1667
