### ISSUE TITLE
Can not remove accept-encoding from headers

### ISSUE THREAD

**Issue by EsterDanielYtterbrink** [sindresorhus/got#1421]
#### Describe the bug

 - Node.js version: v14.8.0
 - OS & version: macOS 10.15.6 (19G2021)

I am migrating some code to got and it has existing tests that, among others, checks the sent headers. I want to be able to use those tests to migrate the code safely. But when setting the header 'accept-encoding' to undefined to match the tests it is set to 'gzip, deflate, br'

#### Actual behavior
Setting `options['accept-encoding'] = undefined` results in `options['accept-encoding'] =  'gzip, deflate, br'`
...

#### Expected behavior
Setting `options['accept-encoding'] = undefined` results in options not to have the property accept-encoding.

...

#### Code to reproduce

I am quite sure the problem is in index.ts on line 2269 and would love to write a test for it, but am unsure where to place the test. 

```js
for (const key in headers) {
			if (is.undefined(headers[key])) {
				// eslint-disable-next-line @typescript-eslint/no-dynamic-delete
				delete headers[key];
			} else if (is.null_(headers[key])) {
				throw new TypeError(`Use \`undefined\` instead of \`null\` to delete the \`${key}\` header`);
			}
		}

		if (options.decompress && is.undefined(headers['accept-encoding'])) {
			headers['accept-encoding'] = supportsBrotli ? 'gzip, deflate, br' : 'gzip, deflate';
		}
...
```

#### Checklist

- [x ] I have read the documentation.
- [ x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Read the docs. Also the code you've posted exactly describes the scenario in which the header is set.

**Comment by EsterDanielYtterbrink** [comment]
So why should it not be possible to remove accept-encoding from your header?

**Comment by szmarczak** [comment]
It is already possible. Read the docs.

**Comment by EsterDanielYtterbrink** [comment]
I have read the docs, and tried to set it to undefined, but then it is removed just to be set again by 		
```
if (options.decompress && is.undefined(headers['accept-encoding'])) {
			headers['accept-encoding'] = supportsBrotli ? 'gzip, deflate, br' : 'gzip, deflate';
		}
}
```
Or is it something else I have missed? 
- I have done a project wide search on accept-encoding, and find nothing
- I have a test in my codebase that confirms the bug and that using my branch solves it

Though if I allow retries the accept-encoding will show up again for the retries. So it is not a universal fix.

**Comment by szmarczak** [comment]
> tried to set it to undefined

Well I have no idea why did you try this, because the `is.undefined(headers['accept-encoding'])` check clearly says that it will be overriden.

> Or is it something else I have missed?

Yes, you missed `options.decompress`. Disable it and you're good to go.

**Comment by EsterDanielYtterbrink** [comment]
Ah, I tried ` decompress = false` first, but accidentally put it in the header... 🤦 I can not really defend not seeing that! And now I found the test as well. Nice!

I tried to set it to `undefined` as that was what worked for the other header options, but I see now that it has to be dealt with differently than the others. Especially since the _request method is called more than once at retries. 

If it is ok I can make a PR for the documentation instead making it even more explicit how it is intended to work. If I misunderstood there will probably be at least one more not getting how it works.
  
Thank you for your patients and pointing me in the right direction. The good thing is that I have forked the repo and might be able to make actual contributions some day. Have a nice weekend when you get so far.

**Comment by szmarczak** [comment]
> Ah, I tried decompress = false first, but accidentally put it in the header... 🤦 I can not really defend not seeing that! And now I found the test as well. Nice!

I'm really glad.

> I tried to set it to undefined as that was what worked for the other header options, but I see now that it has to be dealt with differently than the others.

`undefined` is the default value here, which leads to the default behavior.

> If it is ok I can make a PR for the documentation instead making it even more explicit how it is intended to work.

Sure.

> If I misunderstood there will probably be at least one more not getting how it works.

Ah, fails don't matter. The key is to keep going.

> Thank you for your patients and pointing me in the right direction. The good thing is that I have forked the repo and might be able to make actual contributions some day. Have a nice weekend when you get so far.

That would be great! Have a nice weekend too.
