### ISSUE TITLE
got post broken 11.5.2

### ISSUE THREAD

**Issue by mr-smit** [sindresorhus/got#1428]
#### Describe the bug

 - Node.js version:  6.14.6
 - OS & version: ubuntu 16

got.post json does not sending json to server

#### Actual behavior

returns nothing

#### Expected behavior

should return: {hello: 'world'}

#### Code to reproduce

```js
const got = require('got');
 
(async () => {
    const {body} = await got.post('https://httpbin.org/anything', {
        json: {
            hello: 'world'
        },
        responseType: 'json'
    });
 
    console.log(body.data);
    //=> {hello: 'world'}
})();
```

**Comment by mr-smit** [comment]
using axios, works fine:

`    const body = await axios.post('https://httpbin.org/anything', 
        {
            hello: 'world'
        }
    );
 
    console.log(body.data.json);`

**Comment by Giotino** [comment]
You're using Node.JS 6, it's not supported. It works fine on my Node.JS 14.8.0

**Comment by mr-smit** [comment]
oh.. updated. now works, thanks. closed.
