### ISSUE TITLE
How to use proxy settings ?

### ISSUE THREAD

**Issue by amitpareek1** [sindresorhus/got#1440]
Hi ,

Im using GOT npm from enterprise environment where outbound calls are secured by proxy .

1) Does below mentioned way of  setting proxy is correct ? Does GOT pick the proxy like below ? As request npm pick proxy like given below 

process.env.HTTP_PROXY = "http://x.x.x.x:80";
process.env.HTTPS_PROXY = "http://x.x.x.x:80";

2) As mentioned in the GOT document , the only way to set proxy is as given below ?
 In option 2, I need to set tunnel agent .
const tunnel = require('tunnel');

got('my.outbound.url', {
    agent: {
        https: tunnel.httpsOverHttp({
            proxy: {
                host: 'htp://xxxx:80'
            }
        })
    }
});

What is the preferred and working way ?
...

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
`1` would not work. What's documented in the readme is the preferred way.

**Comment by amitpareek1** [comment]
Can you please check if below option config is correct ?
Agent(proxy) config never worked for me and I got connectivity issue ?  
System where proxy is not required , I remove agent code and its working . Can you please check if I used it incorrectly ?

var options = {

  method: 'POST',

  headers:

  {

    accept: 'application/json',

    'content-type': 'application/x-www-form-urlencoded'

  },

  form:

  {

    grant_type: 'authorization_code',

    client_id: process.env.CLIENT_ID,

    client_secret: process.env.CLIENT_SECRET,

    code: "code",

    redirect_uri: process.env.REDIRECT_URL,

    scope: 'openid profile email',

  },

  agent: {

    https: tunnel.httpsOverHttp({

        proxy: {

            host: 'http://10.59.9.101',

            port: 80

        }

    })

}

};

logger.info('Token options::: ', options);

(async () => {

  try {

      const response = await got(process.env.XERO_TOKEN_URL, options);

      console.log("response body ---"+JSON.parse(response.body));

      //=> '<!doctype html> ...'

  } catch (error) {

      console.log(error);

      //=> 'Internal server error ...'

  }

})();

**Comment by Giotino** [comment]
I think you should correct the tunnel options as follow:
```js
tunnel.httpsOverHttp({
  proxy: {
    host: '1.9.9.1',
    port: 80
  }
})
```

If it's still not working continue reading.

HTTP tunneling is done with `CONNECT`, maybe your proxy (1.9.9.1:80 in your example) does not support HTTP CONNECT.

For a little more informations take a look at this https://en.wikipedia.org/wiki/HTTP_tunnel

**Comment by amitpareek1** [comment]
Ohh , good spot , let me try with removing http. from host .
