### ISSUE TITLE
destroy does not mean error

### ISSUE THREAD

**Issue by ronag** [sindresorhus/got#1445]
https://github.com/sindresorhus/got/blob/408e22aed99300afd4af49a4eb50963665d8a144/source/core/index.ts#L2682

Not exactly sure what the logic here is but it should probably check for e.g. `this._readabledState.endEmitted`, i.e. calling `destroy()` after `'end'` has been emitted is not an error.

**Comment by ronag** [comment]
I need to try and understand this a bit better.

**Comment by szmarczak** [comment]
This just wraps the error inside `RequestError`. It has more properties, so it's easier to debug. The Node.js 14.10.0 bug is not here :sweat_smile:
