### ISSUE TITLE
Lookback regex breaks firefox when the package is used as a dependency in meteor

### ISSUE THREAD

**Issue by bogdanrn** [sindresorhus/got#1447]
#### Describe the bug

 - Node.js version: v12.18.3
 - OS & version: macOS 10.15.6

When the `got` package is being used as part of a dependency in a meteor project, the regex used here:

https://github.com/sindresorhus/got/blob/master/source/core/index.ts#L2313

Makes the web-app unable to load in firefox (chrome works fine). I guess the same bug would happen if webpack is used as well. 

#### Actual behavior
Firefox throws error in console: `SyntaxError: invalid regexp group`. Breaks the whole script.

#### Expected behavior
No firefox error when a regex check is done. 

#### Code to reproduce

Run the following line in firefox console
```js
 /(<socketPath>.+?):(?<path>.+)/.exec(`'test'`);
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
While this would be an easy fix I think you shouldn't use Got on non-Node.JS platforms (like a Browser).

From the documentation:
> For browser usage, we recommend [Ky](https://github.com/sindresorhus/ky) by the same people.

**Comment by sindresorhus** [comment]
I believe this was fixed in the latest Firefox version where they started using the same regex code as Chrome. We don't intend to work around this as the main target for Got is Node.js.
