### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by jenslind** [sindresorhus/got#145]
I get this error in node `5.1.1`:
```
{ [ReadError: unexpected end of file]
  code: 'Z_BUF_ERROR',
  message: 'unexpected end of file',
  host: 'domain.com',
  hostname: 'domain.com',
  method: 'HEAD',
  path: '/' }
```
Some url:s seems to be working but most of them I tested do not.
Any ideas what causing this?

Thanks.

**Comment by SamVerschueren** [comment]
Can you provide an URL that's not working?

**Comment by jenslind** [comment]
This for example:
https://github.com/sindresorhus/got/releases/latest
But tested with random url's like google.com and it didn't work.

Also forgot to mention I'm using `got.head`.

https://github.com/jenslind/electron-gh-releases/issues/13

**Comment by SamVerschueren** [comment]
Can reproduce on node `5.1.1`. It does not occur on `4.2.1`.

More information for the core team

#### example
```js
'use strict';

const got = require('got');

got.head('http://google.com').catch(err => {
    console.error(err);
    //=> ReadError: unexpected end of file
});
```

#### error stack

```
ReadError: unexpected end of file
    at Unzip.<anonymous> (/Users/sam/Projects/playground/got/node_modules/got/index.js:97:8)
    at Unzip.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at Unzip.emit (events.js:169:7)
    at Zlib._handle.onerror (zlib.js:366:10)
```

**Comment by floatdrop** [comment]
@jenslind @SamVerschueren thanks! Fixed in `5.2.1`.

**Comment by tobslob** [comment]
Please i need urgent help, i am trying to install epress on node js, here is my error


TOBI@DESKTOP-45DCDK2 MINGW64 ~/UIUXDesign/UI/node-meetup (master)                
$ npm install express --save                                                     
npm ERR! code Z_BUF_ERROR                                                       
 npm ERR! errno -5                                                                
npm ERR! zlib: unexpected end of file                            
npm ERR! A complete log of this run can be found in:                            
 npm ERR!     C:\Users\TOBI\AppData\Roaming\npm-cache\_logs\2018-12-23T04_54_22_9 46Z-debug.log
--

**Comment by tobslob** [comment]
_> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'express',
> 1 verbose cli   '--save' ]
> 2 info using npm@6.4.1
> 3 info using node@v11.5.0
> 4 verbose npm-session 0e1ee2f80e0e630a
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 200 https://registry.npmjs.org/express 104ms (from cache)
> 8 silly pacote tag manifest for express@latest fetched in 172ms
> 9 timing stage:loadCurrentTree Completed in 1127ms
> 10 silly install loadIdealTree
> 11 silly install cloneCurrentTreeToIdealTree
> 12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
> 13 silly install loadShrinkwrap
> 14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
> 15 silly install loadAllDepsIntoIdealTree
> 16 silly resolveWithNewModule express@4.16.4 checking installable status
> 17 http fetch GET 200 https://registry.npmjs.org/array-flatten 52ms (from cache)
> 18 http fetch GET 200 https://registry.npmjs.org/accepts 54ms (from cache)
> 19 http fetch GET 200 https://registry.npmjs.org/content-disposition 53ms (from cache)
> 20 http fetch GET 200 https://registry.npmjs.org/cookie 46ms (from cache)
> 21 http fetch GET 200 https://registry.npmjs.org/content-type 49ms (from cache)
> 22 http fetch GET 200 https://registry.npmjs.org/cookie-signature 46ms (from cache)
> 23 http fetch GET 200 https://registry.npmjs.org/body-parser 58ms (from cache)
> 24 http fetch GET 200 https://registry.npmjs.org/encodeurl 46ms (from cache)
> 25 http fetch GET 200 https://registry.npmjs.org/depd 47ms (from cache)
> 26 silly pacote version manifest for array-flatten@1.1.1 fetched in 62ms
> 27 silly resolveWithNewModule array-flatten@1.1.1 checking installable status
> 28 silly pacote range manifest for accepts@~1.3.5 fetched in 68ms
> 29 silly resolveWithNewModule accepts@1.3.5 checking installable status
> 30 silly pacote version manifest for content-disposition@0.5.2 fetched in 65ms
> 31 silly resolveWithNewModule content-disposition@0.5.2 checking installable status
> 32 http fetch GET 200 https://registry.npmjs.org/debug 54ms (from cache)
> 33 silly pacote version manifest for cookie@0.3.1 fetched in 61ms
> 34 silly resolveWithNewModule cookie@0.3.1 checking installable status
> 35 silly pacote range manifest for content-type@~1.0.4 fetched in 71ms
> 36 silly resolveWithNewModule content-type@1.0.4 checking installable status
> 37 silly pacote version manifest for cookie-signature@1.0.6 fetched in 64ms
> 38 silly resolveWithNewModule cookie-signature@1.0.6 checking installable status
> 39 silly pacote range manifest for encodeurl@~1.0.2 fetched in 69ms
> 40 silly resolveWithNewModule encodeurl@1.0.2 checking installable status
> 41 silly pacote version manifest for body-parser@1.18.3 fetched in 85ms
> 42 silly resolveWithNewModule body-parser@1.18.3 checking installable status
> 43 silly pacote range manifest for depd@~1.1.2 fetched in 74ms
> 44 silly resolveWithNewModule depd@1.1.2 checking installable status
> 45 http fetch GET 200 https://registry.npmjs.org/escape-html 41ms (from cache)
> 46 http fetch GET 200 https://registry.npmjs.org/etag 41ms (from cache)
> 47 http fetch GET 200 https://registry.npmjs.org/merge-descriptors 35ms (from cache)
> 48 http fetch GET 200 https://registry.npmjs.org/fresh 37ms (from cache)
> 49 http fetch GET 200 https://registry.npmjs.org/finalhandler 43ms (from cache)
> 50 http fetch GET 200 https://registry.npmjs.org/methods 35ms (from cache)
> 51 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-2.6.9.tgz 44ms (from cache)
> 52 silly fetchPackageMetaData error for debug@2.6.9 zlib: unexpected end of file
> 53 silly pacote range manifest for escape-html@~1.0.3 fetched in 67ms
> 54 silly resolveWithNewModule escape-html@1.0.3 checking installable status
> 55 http fetch GET 200 https://registry.npmjs.org/parseurl 44ms (from cache)
> 56 http fetch GET 200 https://registry.npmjs.org/on-finished 46ms (from cache)
> 57 silly pacote range manifest for etag@~1.8.1 fetched in 66ms
> 58 silly resolveWithNewModule etag@1.8.1 checking installable status
> 59 silly pacote version manifest for merge-descriptors@1.0.1 fetched in 62ms
> 60 silly resolveWithNewModule merge-descriptors@1.0.1 checking installable status
> 61 silly pacote version manifest for fresh@0.5.2 fetched in 65ms
> 62 silly resolveWithNewModule fresh@0.5.2 checking installable status
> 63 silly pacote version manifest for finalhandler@1.1.1 fetched in 72ms
> 64 silly resolveWithNewModule finalhandler@1.1.1 checking installable status
> 65 silly pacote range manifest for methods@~1.1.2 fetched in 64ms
> 66 silly resolveWithNewModule methods@1.1.2 checking installable status
> 67 http fetch GET 200 https://registry.npmjs.org/path-to-regexp 64ms (from cache)
> 68 silly pacote range manifest for parseurl@~1.3.2 fetched in 69ms
> 69 silly resolveWithNewModule parseurl@1.3.2 checking installable status
> 70 silly pacote range manifest for on-finished@~2.3.0 fetched in 72ms
> 71 silly resolveWithNewModule on-finished@2.3.0 checking installable status
> 72 silly pacote version manifest for path-to-regexp@0.1.7 fetched in 84ms
> 73 silly resolveWithNewModule path-to-regexp@0.1.7 checking installable status
> 74 http fetch GET 200 https://registry.npmjs.org/range-parser 42ms (from cache)
> 75 http fetch GET 200 https://registry.npmjs.org/proxy-addr 52ms (from cache)
> 76 http fetch GET 200 https://registry.npmjs.org/safe-buffer 37ms (from cache)
> 77 http fetch GET 200 https://registry.npmjs.org/send 40ms (from cache)
> 78 http fetch GET 200 https://registry.npmjs.org/setprototypeof 40ms (from cache)
> 79 http fetch GET 200 https://registry.npmjs.org/serve-static 41ms (from cache)
> 80 silly fetchPackageMetaData error for send@0.16.2 Unexpected end of JSON input while parsing near '...":"0.3.5","mocha":"~2'
> 81 silly fetchPackageMetaData error for serve-static@1.13.2 Unexpected end of JSON input while parsing near '...ries":{},"dist":{"sha'
> 82 http fetch GET 200 https://registry.npmjs.org/qs 57ms (from cache)
> 83 silly pacote range manifest for range-parser@~1.2.0 fetched in 56ms
> 84 silly resolveWithNewModule range-parser@1.2.0 checking installable status
> 85 http fetch GET 200 https://registry.npmjs.org/statuses 36ms (from cache)
> 86 silly pacote range manifest for proxy-addr@~2.0.4 fetched in 67ms
> 87 silly resolveWithNewModule proxy-addr@2.0.4 checking installable status
> 88 silly pacote version manifest for safe-buffer@5.1.2 fetched in 53ms
> 89 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
> 90 http fetch GET 200 https://registry.npmjs.org/type-is 36ms (from cache)
> 91 silly pacote version manifest for setprototypeof@1.1.0 fetched in 54ms
> 92 silly resolveWithNewModule setprototypeof@1.1.0 checking installable status
> 93 silly pacote version manifest for qs@6.5.2 fetched in 68ms
> 94 silly resolveWithNewModule qs@6.5.2 checking installable status
> 95 silly pacote range manifest for statuses@~1.4.0 fetched in 44ms
> 96 silly resolveWithNewModule statuses@1.4.0 checking installable status
> 97 http fetch GET 200 https://registry.npmjs.org/utils-merge 27ms (from cache)
> 98 silly pacote range manifest for type-is@~1.6.16 fetched in 41ms
> 99 silly resolveWithNewModule type-is@1.6.16 checking installable status
> 100 http fetch GET 200 https://registry.npmjs.org/vary 17ms (from cache)
> 101 silly pacote version manifest for utils-merge@1.0.1 fetched in 30ms
> 102 silly resolveWithNewModule utils-merge@1.0.1 checking installable status
> 103 silly pacote range manifest for vary@~1.1.2 fetched in 20ms
> 104 silly resolveWithNewModule vary@1.1.2 checking installable status
> 105 timing stage:rollbackFailedOptional Completed in 1ms
> 106 timing stage:runTopLevelLifecycles Completed in 1371ms
> 107 silly saveTree meetup@1.0.0
> 107 silly saveTree `-- express@4.16.4
> 107 silly saveTree   +-- accepts@1.3.5
> 107 silly saveTree   +-- array-flatten@1.1.1
> 107 silly saveTree   +-- body-parser@1.18.3
> 107 silly saveTree   | +-- content-type@1.0.4
> 107 silly saveTree   | +-- depd@1.1.2
> 107 silly saveTree   | +-- on-finished@2.3.0
> 107 silly saveTree   | +-- qs@6.5.2
> 107 silly saveTree   | `-- type-is@1.6.16
> 107 silly saveTree   +-- content-disposition@0.5.2
> 107 silly saveTree   +-- content-type@1.0.4
> 107 silly saveTree   +-- cookie-signature@1.0.6
> 107 silly saveTree   +-- cookie@0.3.1
> 107 silly saveTree   +-- depd@1.1.2
> 107 silly saveTree   +-- encodeurl@1.0.2
> 107 silly saveTree   +-- escape-html@1.0.3
> 107 silly saveTree   +-- etag@1.8.1
> 107 silly saveTree   +-- finalhandler@1.1.1
> 107 silly saveTree   | +-- parseurl@1.3.2
> 107 silly saveTree   | `-- statuses@1.4.0
> 107 silly saveTree   +-- fresh@0.5.2
> 107 silly saveTree   +-- merge-descriptors@1.0.1
> 107 silly saveTree   +-- methods@1.1.2
> 107 silly saveTree   +-- on-finished@2.3.0
> 107 silly saveTree   +-- parseurl@1.3.2
> 107 silly saveTree   +-- path-to-regexp@0.1.7
> 107 silly saveTree   +-- proxy-addr@2.0.4
> 107 silly saveTree   +-- qs@6.5.2
> 107 silly saveTree   +-- range-parser@1.2.0
> 107 silly saveTree   +-- safe-buffer@5.1.2
> 107 silly saveTree   +-- setprototypeof@1.1.0
> 107 silly saveTree   +-- statuses@1.4.0
> 107 silly saveTree   +-- type-is@1.6.16
> 107 silly saveTree   +-- utils-merge@1.0.1
> 107 silly saveTree   `-- vary@1.1.2
> 108 verbose stack ZlibError: zlib: unexpected end of file
> 108 verbose stack     at Zlib.(anonymous function).onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:131:21)
> 108 verbose stack     at Unzip.write (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:255:31)
> 108 verbose stack     at Unzip.flush (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:222:10)
> 108 verbose stack     at Unzip.end (C:\Program Files\nodejs\node_modules\npm\node_modules\minizlib\index.js:229:10)
> 108 verbose stack     at Object.end (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:415:21)
> 108 verbose stack     at PassThrough.onend (_stream_readable.js:655:10)
> 108 verbose stack     at Object.onceWrapper (events.js:277:13)
> 108 verbose stack     at PassThrough.emit (events.js:194:15)
> 108 verbose stack     at endReadableNT (_stream_readable.js:1129:12)
> 108 verbose stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
> 109 verbose cwd C:\Users\TOBI\UIUXDesign\UI\node-meetup
> 110 verbose Windows_NT 10.0.15063
> 111 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
> 112 verbose node v11.5.0
> 113 verbose npm  v6.4.1
> 114 error code Z_BUF_ERROR
> 115 error errno -5
> 116 error zlib: unexpected end of file
> 117 verbose exit [ -5, true ]
>_

**Comment by tobslob** [comment]
> Please i need urgent help, i am trying to install epress on node js, here is my error
> 
> ## TOBI@DESKTOP-45DCDK2 MINGW64 ~/UIUXDesign/UI/node-meetup (master)
> $ npm install express --save
> npm ERR! code Z_BUF_ERROR
> npm ERR! errno -5
> npm ERR! zlib: unexpected end of file
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\TOBI\AppData\Roaming\npm-cache_logs\2018-12-23T04_54_22_9 46Z-debug.log

I have fixed it!
