### ISSUE TITLE
Unusable with typescript 4: typing of got is wrong.

### ISSUE THREAD

**Issue by Nokel81** [sindresorhus/got#1458]
#### Describe the bug

 - Node.js version: v12.18.0
- Typesctipt version: 4.0.2
 - OS & version: macos 10.15.6

#### Actual behaviour
The type of `res` in the following is `unknown`:
```typescript
const res = await got.post('https://httpbin.org/anything', {
        json: {
            hello: 'world'
        },
        responseType: 'json'
    });
```

#### Expected behaviour
The type to be `Response`

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got. (currently typescipt)

**Comment by Giotino** [comment]
I just tested it with Node.JS v12.18.0, Typescript v4.0.2 and Got v11.6.2.

The type of `res` is `Response<unknown>` which is correct.

**Comment by Nokel81** [comment]
Ah I see now what caused me to fail, I had a function that returned `Options` which doesn't help the typing very much....

Sorry for the noise.

**Comment by Nokel81** [comment]
Though I do think that the type for the options of `got.stream(...)` should be exported.
