### ISSUE TITLE
Expect response object, but got exception when server is unreachable and throwHttpErrors is false

### ISSUE THREAD

**Issue by patoi** [sindresorhus/got#1465]
#### Describe the bug

 - Node.js version: 11.6.2
 - OS & version: MacOS 10.15.6 (19G2021) Catalina

I've expected get a response object, when `throwHttpErrors: false` if server is unreachable.

#### Actual behavior

Result is (catch): `error message: connect ECONNREFUSED 127.0.0.1:60099`

#### Expected behavior

Result is a response object (then): `response: ...`

#### Code to reproduce

```js
'use strict'
const got = require('got')
got({
  throwHttpErrors: false,
  retry: 1,
  url: 'http://localhost:60099',
  method: 'GET'
})
  .then(response => {
    console.log('response: ', response)
  })
  .catch(error => {
    console.error('error message:', error.message)
  })
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
It's not an HTTP error.
