### ISSUE TITLE
400 after migration form request

### ISSUE THREAD

**Issue by PSeitz** [sindresorhus/got#1467]
#### Describe the bug

 - Node.js version: v10.19.0
 - OS & version: MacOS 10.15.6

I recently moved from `request` to `got`. Almost all request work fine, but there is one request for which I get a 400 bad request.

It's a simple get request with some headers and the input is exactly the same.

Headers:
```js
{
  "x-csrf-token": "...",
  "Authorization": "...",
  "cookie": "...",
  "x-sap-orca-session-id": "...",
  "x-sap-boc-user-properties-b64": "..."
}
```

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please fill out the template properly and I'll reopen.
