### ISSUE TITLE
How to process after error

### ISSUE THREAD

**Issue by on2air** [sindresorhus/got#1468]
#### Describe the bug

 - Node.js version: 14.1
 - OS & version: Ubuntu

#### Actual behavior
How do I continue processing after an error occurs when getting a readable stream?

Code:
```
 const downloadStream = got.stream(url)
        downloadStream.on('error', error => logger.error({msg: 'Got Stream error: '+ error.toString()}));
        const { data } = await googleDriveApi.files.create({
          requestBody: {
            name: name,
            parents: [path],
          },
          media: {
            body: downloadStream,
          },
        });
       logger.info('DOESN'T REACH HERE ON ERROR')
```
I'm getting a stream to an external URL and sending to google drive api for it to upload directly from stream.
If there is an error with the download (i.e. Im getting a 403 error) - i print my 'Got Stream error' but it doesn't get to my debug line after the call, nor does it throw an error.

How can I continue on after it processes the error in the .on('error') ?

Everything works fine if there are no errors with the file.
...

**Comment by szmarczak** [comment]
Set `throwHttpErrors` to `false` or use `error.response.body`.

**Comment by szmarczak** [comment]
It's not a Got issue.

**Comment by on2air** [comment]
ok, but is there a way I can detect the stream is valid before passing into google drive?

**Comment by szmarczak** [comment]
Ask the Google Drive API folks. I'm not their programmer, so I have no idea how to use it.
