### ISSUE TITLE
How do I get the curl from a Got response?

### ISSUE THREAD

**Issue by Codermar** [sindresorhus/got#1471]
#### What would you like to discuss?
With request I am able to do this:
```
        import 'request-to-curl';

// then in my request response
        const requestCurl = response.request.req.toCurl();
        logger.info({ requestCurl }, ' ** Request CURL ** ');
```
Using the [request-to-curl package](https://github.com/jmealo/node-request-to-curl)

How do I do something similar in Got?

...

#### Checklist

- [ x] I have read the documentation.

**Comment by szmarczak** [comment]
No

**Comment by Codermar** [comment]
Boy!... that was a brief response... Not even one little idea on this?

**Comment by szmarczak** [comment]
Well, technically there could be a plug-in to generate a curl command but do note that it won't run anything Got-related like retries, hooks, streams and advanced timeouts. It would be best if this were a separate package instead. Got is just an HTTP client, not a codemod.

**Comment by szmarczak** [comment]
Sorry to disappoint you 😅 Don't hesitate to ask other questions whenever you have any.

**Comment by Codermar** [comment]
Thanks for the response. I do not intend to run anything but just merely create a curl for debugging purposes which we find very useful. Not a big expert here but I could try writing a plugin. Could you give me some hints and/or point me to examples I can look at? Also,

**Comment by koerbcm** [comment]
I am looking for something similar as well. I would agree that it doesn't make sense to have it within got but if you were able to find a solution, I would be interested in trying it out @Codermar.
