### ISSUE TITLE
Not standardized HTTP methods

### ISSUE THREAD

**Issue by Giotino** [sindresorhus/got#1475]
#### What problem are you trying to solve?

It has already been discussed (#1346) but I still don't think the way Got handle this is right.
In the RFC 7231 there's nothing that say "these are the only methods HTTP supports".
To me it sounds like "these methods (GET, POST, etc.) are standardized by this RFC, but you can use whatever you want as long as it's a `token`" (pretty much confirmed by the phrase "Additional methods, outside the scope of this specification, have been standardized for use in HTTP.").

Since "Got is RFC-compatible" it should permit the user to use HTTP/1.1 as specified by RFC 7231 at it full potential.

For example: WebDav is an "extension" of the HTTP protocol, so, should it be supported by an HTTP client?
I think yes and no, Got should be able to communicate with a WebDav server (also through an HTTP proxy, which should follow the "other methods" part of the RFC) but it doesn't need to understand what's going on with the "WebDav stuff" (of curse). The last part ("WebDav stuff") should be managed by the user (by the software using Got).

Also methods are defied as case-sensitive but Got converts everything to uppercase.

I know you can just play a little with Typescript in order to use anything you like (except for the case-sensitive part), but I don't think this is the 100% correct way to handle this.

**Comment by szmarczak** [comment]
> at it full potential.

RFC 7231 is **not** WebDAV. It doesn't specify any other methods than `GET`, `HEAD`, `POST`, `PUT`, `DELETE`, `OPTIONS` and `TRACE`. WebDAV introduces new behavior, so to comply with it we would need to do changes in Got. We already support RFC 7231 at its full potential.

> For example: WebDav is an "extension" of the HTTP protocol, so, should it be supported by an HTTP client?

The quotation marks are unnecessary. Yes, it is an **extension**, but not the HTTP protocol itself. As mentioned already many times, I'll repeat: Got is not a WebDAV client.

> Got should be able to communicate with a WebDav server

Got doesn't implement any WebDAV behavior. The user is responsible for using Got in a way so they can communicate properly.

> The last part ("WebDav stuff") should be managed by the user (by the software using Got).

I agree.

> Also methods are defied as case-sensitive but Got converts everything to uppercase.

Please attach [source](https://tools.ietf.org/html/rfc7231#section-4.1) whenever possible :)

>    The method token is case-sensitive because it might be
>    used as a gateway to object-based systems with case-sensitive method
>    names.

I think the solution is to check whether the method is an RFC7231 one and uppercase it. Otherwise, leave it as it is.

> I don't think this is the 100% correct way to handle this.

If the types include WebDAV methods than it may wrongly suggest that Got is a WebDAV client.

/cc @sindresorhus

**Comment by Giotino** [comment]
> I think the solution is to check whether the method is an RFC7231 one and uppercase it. Otherwise, leave it as it is.

I don't think that's fine, `GET` is not `gEt` and each of them should be fine.

I also found a way to sum up my entire point:
Is this a valid request for RFC 7231?

```
CustomMethod /path HTTP/1.1
Host: we.are.in.http.1.1.com
Some-Header: Hello
```

If yes Got should be able to make it (or an equivalent). If not we are fine as we are now (except for the case-sensitive).

I think that request is valid, so Got should give the user the ability to make it.

> The user is responsible for using Got in a way so they can communicate properly.

That's the same thing I was saying, but currently the user is unable to use Got (without messing with Typescript) to communicate with WebDAV (or other similar protocols).

> If the types include WebDAV methods than it may wrongly suggest that Got is a WebDAV client.

I was not saying "lets add every method we can find on the internet as a type for `Method`", I was saying "lets type `Method` as a `string` (maybe with some control on the allowed chars)".

**Comment by szmarczak** [comment]
> I don't think that's fine, GET is not gEt and each of them should be fine.

Yeah, but what about `get`? 99% of people consider it `GET`. Anyway we cannot accept non-uppercased methods as Node.js doesn't support this:

https://github.com/nodejs/node/blob/3b10f7f933dee3607649b6bd1ca24876704222ac/lib/_http_client.js#L182

> Is this a valid request for RFC 7231?

It is, but the `CustomMethod` is not standardized by RFC 7231.

> I think that request is valid, so Got should give the user the ability to make it.

Unfortunately that's not possible :(

> I was saying "lets type Method as a string

Yeah, that would make sense :+1:

**Comment by Giotino** [comment]
> nodejs/node@`3b10f7f`/lib/_http_client.js#L182

I didn't know about this, this is kind of a big deal for the RFC 7231. This is not following the RFC, maybe we should open a little issue discussing about that on the Node.JS repo.

> let's type Method as a string (maybe with some control on the allowed chars)

I think this is the best thing to do, we can support more protocols extending HTTP without breaking anything.

> maybe with some control on the allowed chars

About this, the check is kindly offered by the Node.JS source:

```js
const tokenRegExp = /^[\^_`a-zA-Z\-0-9!#$%&'*+.|~]+$/;
/**
 * Verifies that the given val is a valid HTTP token
 * per the rules defined in RFC 7230
 * See https://tools.ietf.org/html/rfc7230#section-3.2.6
 */
function checkIsHttpToken(val) {
  return tokenRegExp.test(val);
}
```

**Comment by sindresorhus** [comment]
So the problem is only with the TypeScript `Method` type, correct? If so, the user can just do:

```js
await got('https://sindresorhus.com', {method: 'FOO' as Method});
```

**Comment by szmarczak** [comment]
That's right. https://www.iana.org/assignments/http-methods/http-methods.xhtml doesn't introduce any methods that would contain lowercase characters.

@Giotino Even though the RFC says `METHOD` is case-sensitive, there is no standard that would contain at least one lowercase character in `METHOD`.
