### ISSUE TITLE
I can not use got

### ISSUE THREAD

**Issue by yinshuaibin** [sindresorhus/got#1476]
When I use got, it prompts me to in
![1600917442(1)](https://user-images.githubusercontent.com/35283085/94096830-a90c8000-fe57-11ea-9f39-27d8080f6b49.jpg)
stall http2 and dns, after install, it prompts TypeError: Cannot read property'node' of undefined

**Comment by Giotino** [comment]
Got does not support browsers, use [ky](https://github.com/sindresorhus/ky) instead.
