### ISSUE TITLE
Filter requests

### ISSUE THREAD

**Issue by ashuradev** [sindresorhus/got#1477]
#### What would you like to discuss?

Hello, how I can filter all requests that is send to got? I need to apply a filter so that a request with the same URL does not occur more than once. I tried to use handlers, but to no avail.

For example:

```js
const queue = [];

const uniqueRequest = (url) => {
  if (queue.includes(url)) {
    // drop the request
  } else {
    queue.push(url);
    // continue
  }
};
```

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
> I tried to use handlers, but to no avail.

What did you try with them?

**Comment by szmarczak** [comment]
Handlers are very similar to `init` hooks with the difference they pass normalized options, and `init` hooks pass unmodified options. Each get called only once per a `got()` call.

**Comment by ashuradev** [comment]
> > I tried to use handlers, but to no avail.
> 
> What did you try with them? https://github.com/sindresorhus/got#hooksbeforerequest is what you'd want.

I tried to use hooks and handlers, trying to cancel a request by throwing an Error if the request has already been made, but I need these errors to be silenced globally.

**Comment by ashuradev** [comment]
> Handlers are very similar to `init` hooks with the difference they pass normalized options, and `init` hooks pass unmodified options. Each get called only once per a `got()` call.

I need to access the request URL to filter the duplicates requests.

**Comment by szmarczak** [comment]
> I need these errors to be silenced globally.

You can do this in pure Node.js.

> I need to access the request URL to filter the duplicate requests.

See @sindresorhus' answer, `beforeRequest` hooks is what you're looking for. Can you please tell us what did you try?

**Comment by ashuradev** [comment]
I tried this:

```js
let queue = []

const got = require('got').extend({
  handlers: [
    (options, next) => {
      if (!queue.includes(options.url.href)) {
        queue.push(options.url.href)
        return next(options)
      } else {
        // I need this error to be handled automatically, without the need to add a 
        // .catch or try-catch block to each call to got.
        throw new Error('Dropping request')
      }
    },
  ],
})

got('http://google.com').then(() => {
  console.log('Foo')
})

got('http://google.com').then(() => {
  console.log('Bar')
})
```

**Comment by szmarczak** [comment]
Can you try a `beforeRequest` hook instead?

**Comment by ashuradev** [comment]
The result is the same of handlers:

```js
let queue = []

const got = require('got').extend({
  hooks: {
    beforeRequest: [
      (options) => {
        if (!queue.includes(options.url.href)) {
          queue.push(options.url.href)
        } else {
          // I need this error to be handled automatically, without the need to add a
          // .catch or try-catch block to each call to got.
          throw new Error('Dropping request')
        }
      },
    ],
  },
})

got('http://google.com').then(() => {
  console.log('Foo')
})

// I wanted to silently ignore this request
got('http://google.com').then(() => {
  console.log('Bar')
})
```

**Comment by szmarczak** [comment]
I cannot reproduce: https://runkit.com/szmarczak/5f6e8381669b26001307544d

**Comment by szmarczak** [comment]
As you can see only `Foo` shows up and an error is thrown for the `Bar` request.

**Comment by ashuradev** [comment]
This errors is because of `throw`.

**Comment by ashuradev** [comment]
The problem is the error that is thrown inside the hook, because I want you to just ignore it.

**Comment by szmarczak** [comment]
Sorry, but that's is not a Got issue. You're responsible for handling errors.

I can only propose `.catch(fn)` or `async/await + try/catch`.
