### ISSUE TITLE
Referer not being set on redirect

### ISSUE THREAD

**Issue by MirrorBytes** [sindresorhus/got#1479]
#### Describe the bug

 - Node.js version: 14.4.0
 - OS & version: Windows 10 1909 & RHEL 8

Is it intended for the referer header to not be set on redirect?

#### Actual behavior
Referer header is not set with redirect request url, retains original referer.
...

#### Expected behavior
For referer header to be set with redirect request url.
...

#### Checklist

- [x] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by MirrorBytes** [comment]
Nevermind, read the RFC in regards to this; it doesn't mention a standard. I'll work around it.

**Comment by MirrorBytes** [comment]
Sorry, for the confusion. I'm greatly confused myself, and this definitely seems like an issue related to ```got```.

So when providing a referer header to ```got```, it doesn't override when redirecting. When trying to set it with the beforeRedirect hook, it doesn't retain through the request and still shows the original provided one.

**Comment by szmarczak** [comment]
Can you please attach some code?

**Comment by MirrorBytes** [comment]
To specify, I'm attempting to replace Request in jsdom.

```javascript
    const proxyOptions = {};

    if (this._proxy) {
      proxyOptions.http = new HttpProxyAgent({
        keepAlive: true,
        proxy: this._proxy
      });

      proxyOptions.https = new HttpsProxyAgent({
        keepAlive: true,
        proxy: this._proxy
      });
    }

    const requestOptions = {
      responseType: "buffer",
      retry: 0,
      ignoreInvalidCookies: true,
      https: {
        rejectUnauthorized: true
      },
      hooks: {
        beforeRedirect: [
          (options, response) => {
            options.headers.referer = response.requestUrl;
          }
        ]
      },
      headers: {
        "User-Agent": this._userAgent,
        "Accept-Language": "en",
        Accept: accept,
        referer: "http://example.com"
      },
      agent: proxyOptions,
      cookieJar
    };

    const req = got(url, requestOptions);
```

Now in this case, the url will redirect from ```/1``` to ```/2```. However, referer is not updated to ```/1```, and remains "http://example.com".

In Request's redirect class, they set the header here: https://github.com/request/request/blob/master/lib/redirect.js#L143-L145.

**Comment by MirrorBytes** [comment]
I got it to work by moving the hooks initialization further down, and directly changing requestOptions instead of the provided options in the hook.

**Comment by szmarczak** [comment]
So you fixed it?

**Comment by MirrorBytes** [comment]
Yes.

```javascript
    const requestOptions = {
      responseType: "buffer",
      retry: 0,
      ignoreInvalidCookies: true,
      https: {
        rejectUnauthorized: this._strictSSL
      },
      headers: {
        "User-Agent": this._userAgent,
        "Accept-Language": "en",
        Accept: accept,
        referer: "http://example.com"
      },
      agent: proxyOptions,
      cookieJar
    };

    requestOptions.hooks = {
      beforeRedirect: [
        (options, response) => {
          requestOptions.headers.referer = response.requestUrl;
        }
      ]
    };
```
