### ISSUE TITLE
Piping on response?

### ISSUE THREAD

**Issue by tolmasky** [sindresorhus/got#148]
Just wanted to know whether doing the following was fine:

```
got.stream(url).on("response", function(response)
{
     var contentLength = +response.headers["content-length"];
    
     this.pipe(fs.createWriteStream....)
}
```

**Comment by julien-f** [comment]
It should be fine.

**Comment by kevva** [comment]
`var contentLength = +response.headers["content-length"];` should probably be defined outside the `response` event?

**Comment by floatdrop** [comment]
Yes, but pipe `response` argument instead of `this`:

```js
got.stream('google.com').on('response', res => {
    res.pipe(process.stdout);
});
```

**Comment by julien-f** [comment]
@floatdrop I don't think it works or it is a good idea, the response stream is already piped into the proxy stream and a readable stream should only be pipe into a single writable stream or there will be issues regarding back pressure.

**Comment by floatdrop** [comment]
@julien-f it is working, but you right - race condition can happen and first couple of chunks can be lost.
