### ISSUE TITLE
Retries on got.TimeoutError

### ISSUE THREAD

**Issue by davidcreel** [sindresorhus/got#1482]
#### What would you like to discuss?
Why are `got.TimeoutError` errors generated by using the `timeout` option not retried when `ETIMEDOUT` is included in the `retry.errorCodes` option? The error code of the [TimeoutError class](https://github.com/sindresorhus/got/blob/ab338a70dd9547a6c48af18ab5e2306639e5cbad/source/core/utils/timed-out.ts#L34) is ETIMEDOUT which led me to believe this would be the case. Is there a way to enable this behavior that I am missing? Or is the recommendation to create a custom solution?
...

#### Checklist

- [✅ ] I have read the documentation.

**Comment by szmarczak** [comment]
```js
const got = require('got');
const http = require('http');

const server = http.createServer(() => {});

server.listen(error => {
    if (error) {
        throw error;
    }
    
    (async () => {
        try {
            await got(`http://localhost:${server.address().port}`, {
                timeout: 1000,
                hooks: {
                    beforeRetry: [
                        () => {
                            console.log('Retrying...');
                        }
                    ]
                }
            });
        } catch (error) {
            console.log(error);
        } finally {
            server.close();
        }
    })();
});
```

I cannot reproduce. Am I missing something?

**Comment by davidcreel** [comment]
Thanks for the reply. Since I can replicate the retries with a simple implementation like you posted, it must be something with the options or hooks I am using. I have been specifically using the lookup timeout and dnsCache to reduce and stop some EAI_AGAIN errors that I have encountered. 
``` javascript
dnsCache: new CacheableLookup({
        cache: new QuickLRU({maxSize: 1000})
}),
timeout: {
    lookup: 5000
},
retry: {
    limit: 2,
    statusCodes: [408, 429, 503, 504],
    methods: ['GET', 'POST', 'DELETE', 'PUT']
}
```
Along with this beforeRetry hook and unspecified `errorCodes` (so default).
``` javascript
hooks: {
        beforeRetry: [
            (options, error, retryCount) => {
                if (error instanceof got.TimeoutError) {
                    logger.error(`Request to ${options.url} timed out. ${error.message}. Retrying... (Attempt #${retryCount})`);
                } else ...
            }
        ]
}
```
I noticed failures in my logs for `Timeout awaiting 'lookup' for 5000ms` but did not see corresponding retry log. 

I do have beforeRequest and afterResponse hooks. But I do not trigger the retry functions in my afterResponse hooks. 

Going to close this since the original question is incorrect and this is probably my error somewhere. If I find anything consistently reproducible I'll reopen. Thanks
