### ISSUE TITLE
`content-length: 0` on linux file with size `0` on `stat`

### ISSUE THREAD

**Issue by Giotino** [sindresorhus/got#1486]
#### Describe the bug

 - Node.js version: Irrelevant
 - OS & version: Linux and maybe MacOS

In linux where "everything is a file" some files have no size when calling stat (eg. `/proc/cpuinfo`).
In this case Got set `content-length` to `0`, when it should use a `chunked` transfer encoding.

#### Actual behavior

Got set `content-length` to `0`.

#### Expected behavior

Got uses a `chunked` transfer encoding.

#### Code to reproduce

```js
const {createReadStream} = require('fs');
const got = require('got');

const stream = createReadStream('/proc/cpuinfo');

(async () => {
	const response = got('https://httpbin.org/post', {method: 'POST', body: stream});
	const json = await response.json();
	
	console.log(json)
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
It's working properly on 9.6.0 but it's failing on 10.0.0

**Comment by szmarczak** [comment]
Works on `got@10.0.0-alpha.3.2` but doesn't on `got@got@10.0.0-beta.1`.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/compare/v10.0.0-alpha.3...v10.0.0-beta.1

**Comment by Giotino** [comment]
I think the fix is quite simple: if it's a stream go with chunked, no content-length even if we know it.

**Comment by Giotino** [comment]
> I think the fix is quite simple: if it's a stream go with chunked, no content-length even if we know it.

Ok, it's not that easy because the upload progress feature is gonna break, but at least we can go with:
if stat.size == 0
  we don't know the size
else
  stat.size

**Comment by szmarczak** [comment]
> Ok, it's not that easy because the upload progress feature is gonna break, but at least we can go with:

That's not the right solution. The alpha version has the same `getBodySize` implementation and it works there.

**Comment by Giotino** [comment]
> That's not the right solution. The alpha version has the same `getBodySize` implementation and it works there.

I'm sorry but currently I've no time to investigate this, but I can say this: if `stat` returned `0` and Got used that value on `content-length` there's no way it was working fine, except in the case of a Got bug that wasn't setting the `content-length` properly.

**Comment by szmarczak** [comment]
No problem, I'll look into this ASAP.
