### ISSUE TITLE
Uncaught TypeError when running from inside FiveM's FXServer.

### ISSUE THREAD

**Issue by tabarra** [sindresorhus/got#1490]
#### Describe the bug

 - Node.js version: 12+ (probably irrelevant)
 - OS & version: irrelevant

When running inside FiveM's runtime environment, errors cause an unhandled TypeError when inferring the stack is an string.
I know this is kinda niche issue, but an issue nontheless.
Changing  `!is.undefined(error.stack)` to `is_1.string(error.stack)` in [HERE ](https://github.com/sindresorhus/got/blame/master/source/core/index.ts#L1225) solves it! I'll make an PR for that in a bit.

#### Actual behavior

Its not even caught by the `uncaughtException` process event due to how FXServer node integration works. The following is just printed to the console.

```
Executing got()
Error calling system tick function in resource monitor: TypeError: this.stack.slice(...).split is not a function
stack:
[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

#### Expected behavior

```
Executing got()
HANDLED ERROR
```

#### Code to reproduce

```js
const got = require('got');

(async () => {
    try {
        console.log('Executing got()');
        await got('https://google.com/', { timeout: 1, retry: 0 }).text();
        console.log('Done.');
    } catch (err) {
        console.log('HANDLED ERROR');
    }
})()

process.on('uncaughtException', function(err) {
    console.log('UNHANDLED ERROR');
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by trippythabum** [comment]
I have this problem can someone help
