### ISSUE TITLE
example doesn't work on node 14 

### ISSUE THREAD

**Issue by lpc921** [sindresorhus/got#1498]
I am trying out the example in readme but it doesn't wok. My node version is v14.10.0. OS is Ubuntu 18.04

``` js
const got = require("got");
(async () => {
  try {
    console.log("1");
    const response = await got("https://sindresorhus.com");
    console.log("2");
  } catch (error) {
    console.log("3");
  }
})();
```

Output: `1`

`curl https://sindresorhus.com` works fine on the same machine. If I replace got with axios it works fine.

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
Can you try Node.js v`14.13.1`? Thanks.

**Comment by lpc921** [comment]
After upgrading node to 14.13.1 it just worked. Thanks a lot!
