### ISSUE TITLE
beforeRetry hook does not read form-data stream

### ISSUE THREAD

**Issue by rumaf** [sindresorhus/got#1500]
#### Describe the bug

 - Node.js version: 14.13.0
 - OS & version: macOS 10.15.7
 - got: 11.7.0

Using `form-data` to do a post request the beforeRetry hook reads the form-data stream but ignores subsequent retries.
Can this be done without having to buffer the form into memory?

#### Code to reproduce
**Server:**
```js
const express = require('express')
const multer = require('multer');

const app = express()
app.use(multer().any());

const port = 3000
app.use(express.urlencoded({extended: true}))
app.post('/', (req, res) => res.status(500).end())
app.listen(port, () => console.log(`http://localhost:${port}`));
```

**Request:**
```js
const fs = require('fs');
const got = require('got');
const formData = require('form-data');

function getBody() {
	var form = new formData();
	form.append('field1', 'field1');
	form.append('file', fs.createReadStream('./big_file.webm'), 'filename');
	return form;
}

(async () => {
	const form = getBody();
	await got.post('http://localhost:3000', {
		body: form,
		retry: {
			limit: 3,
			methods: ['POST'],
		},
		headers: {
			'content-type': `multipart/form-data; boundary=${form.getBoundary()}`
		},
      hooks: {
        beforeRetry: [
        (options, error, retryCount) => {
			console.log('beforeRetry hook: error %s - count %s', error?.response?.statusCode, retryCount);
			options.body = getBody();
          },
        ],
      },
	}).on('uploadProgress', console.log)
})().catch(err => {
	console.error(err.message);
});
```

**Output:**

```bash
(...)
{ percent: 0.9999993776361802, transferred: 93193020, total: 93193078 }                                       │
{ percent: 1, transferred: 93193078, total: 93193078 }                                                        │
beforeRetry hook: error 500 - count 1                                                                         │
Response code 500 (Internal Server Error) 
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
Actually there's a safety check in order to prevent the retry if the body is a stream (in the case a user do not reopen the stream).

https://github.com/sindresorhus/got/blob/1f132e88b4e9b295631637757d64307032a4e56e/source/as-promise/index.ts#L156-L161

```js
You could do sometconst fs = require('fs');
const got = require('got');
const formData = require('form-data');
const getStream = require('get-stream');

function getBody() {
	var form = new formData();
	form.append('field1', 'field1');
	form.append('file', fs.createReadStream('./big_file.webm'), 'filename');
	return getStream(form);
}

(async () => {
	const form = getBody();
	await got.post('http://localhost:3000', {
		body: form,
		retry: {
			limit: 3,
			methods: ['POST'],
		},
		headers: {
			'content-type': `multipart/form-data; boundary=${form.getBoundary()}`
		},
      hooks: {
        beforeRetry: [
        (options, error, retryCount) => {
			console.log('beforeRetry hook: error %s - count %s', error?.response?.statusCode, retryCount);
			options.body = getBody();
          },
        ],
      },
	}).on('uploadProgress', console.log)
})().catch(err => {
	console.error(err.message);
});hing like this
```

But you're going to lose the streaming feature.

We can try to figure something out to keep the safety check and allowing users to change the body with a stream on retry.

**Comment by rumaf** [comment]
@Giotino I'm currently using `get-stream`, as in your example, to do the upload, but I'm trying to find a way to do it without losing the streaming feature as you said, as in my case it is an important feature to have.
I'm going to do some tests without the safety check and to see if it works with any side effects.

**Comment by Giotino** [comment]
> @Giotino I'm currently using `get-stream`, as in your example, to do the upload, but I'm trying to find a way to do it without losing the streaming feature as you said, as in my case it is an important feature to have.
> I'm going to do some tests without the safety check and to see if it works with any side effects.

I'm working on a PR that is going to fix this without breaking anything, but, if it's ok, it's gonna land in Got 12.

**Comment by Giotino** [comment]
BTW I don't think only using `get-stream` can solve your issue, with form data also the `boundary` change, so you need to replace it.

```js
            beforeRetry: [
				options => {
					const form = getBody();
					options.body = form;
					options.headers['content-type'] = `multipart/form-data; boundary=${form.getBoundary()}`;
				}
			]
```

**Comment by rumaf** [comment]
You are right, the `boundary` also changes. Thank you for the heads up.

**Comment by rumaf** [comment]
@Giotino Just tested your PR and it's working like a charm. Thank you!

**Comment by ngingihy** [comment]
@rumaf , hey what PR you tried? where is it?
