### ISSUE TITLE
302 Redirect Not Converted to GET

### ISSUE THREAD

**Issue by mwallace72** [sindresorhus/got#1502]
#### Describe the bug

 - Node.js version: v12.14.1
 - OS & version: MacOSX 10.15.7

Per documentation, `got` follows redirects automatically, and further, if a 303 is received on a POST call, it will be followed through to subsequent URL as a GET. I have a redirect that uses a 302 instead, which is not automatically followed through as a GET, but instead followed through as a POST.

I am converting my code over from request/request-promise.

#### Actual behavior

Fails with 405 not allowed method for POST (the end url will not accept a POST). Upon checking the options of the `error` object, I see that the `url.href` is the correct final (redirected) URL expected, but the `method` shows as `'POST'` instead of a `'GET'`.

#### Expected behavior

Succeed with 200 

#### Code to reproduce

Using `got.post` to a URL with form data & cookieJar:

```js
const response = await got.post(mainFormURL, {form: mainFormInput, cookieJar: jar})
```

This URL is expected to redirect to a final URL. The final redirect URL should be a GET request, although the original is a POST.

I checked 
```js
const response = await got.post(mainFormURL, {form: mainFormInput, cookieJar: jar, followRedirect: false})
console.log(response.statusCode)
```
And confirmed that it's actually a 302.

I can substitute with 
```js
const originalResp = await got.post(mainFormURL, {form: mainFormInput, cookieJar: jar, followRedirect: false})
const response = await got(originalResp.headers.location, {cookieJar: jar})
```
Which gets the expected 200. Using the `request` library, this was just the single call:
```js
const response = await request.post({
     url: mainFormURL,
     form: mainFormInput,
     followAllRedirects: true,
})
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Read the docs: https://github.com/sindresorhus/got/#methodrewriting
