### ISSUE TITLE
Stream created from readable-stream module does not work

### ISSUE THREAD

**Issue by kanongil** [sindresorhus/got#1503]
#### Describe the bug

 - Node.js version: any
 - OS & version: n/a

#### Actual behavior

Rejected with error: ```RequestError: The `body` option must be a stream.Readable, string or Buffer```

#### Expected behavior

Upload the stream data as request body.

The [`readable-stream`](https://www.npmjs.com/package/readable-stream) module is a node official implementation of streams2+, with 50M weekly downloads. It is recommended to use to get a stable stream implementation across node releases, so I would expect it to work here.

#### Code to reproduce

```js
const Got = require('got');
const { Readable } = require('readable-stream');

const stream = new Readable({
  _read() {
    this.push('ok');
    this.push(null);
  }
});

Got.post('http://google.com', {
  body: stream
}).catch(console.error);
```

Note, this is fixed with https://github.com/sindresorhus/got/pull/1424, but there might be a more appropriate fix, like a duck-typed check for the `_readableState` property.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
I would recommend opening an issue on Node.js about adding a `Stream.isStream()` method, like `Buffer.isBuffer()`.

For now, I guess we could just borrow the logic from https://github.com/sindresorhus/is-stream/blob/46239f19bafec11fd4c04fc09819fb7ca48b4f1f/index.js#L3-L6

I would prefer to see an enhancement request in the Node.js issue tracker before we add our own duck-typing/workaround though.

**Comment by szmarczak** [comment]
Is `is-stream` included in `@sindresorhus/is`?
