### ISSUE TITLE
afterResponse hook is not called after a retryWithMergedOptions()

### ISSUE THREAD

**Issue by OlivierRiberi** [sindresorhus/got#1506]
#### Describe the bug

Retrying a request with retryWithMergedOptions() does not call again the afterResponse hook.

#### Actual behavior

afterResponse hook is called properly the first time, but it's skipped after a retry. 
May be because of: https://github.com/sindresorhus/got/blob/6aa86f2494194907f6c6c8b4774dfa1f69df6876/source/as-promise/index.ts#L105

#### Expected behavior

I think a request after a retry should call all the hooks defined in the instance's options.

#### Code to reproduce

Let's consider that /test returns 401 if the authorization header does not exist

```js
  const instance = got.extend({
    responseType: 'json',
    hooks: {
      beforeRequest: [
        async options => {
          console.log('beforeRequest')
        }
      ],
      afterResponse: [
        (response, retryWithMergedOptions) => {
          console.log('afterResponse')

          response.body = { test: 'added-param' }

          if (response.statusCode === 401) { // Unauthorized
            const updatedOptions = {
              headers: {
                authorization: 'needed-header'
              }
            }

            // Save for further requests
            instance.defaults.options = got.mergeOptions(instance.defaults.options, updatedOptions)

            // Make a new retry
            return retryWithMergedOptions(updatedOptions)
          }

          // No changes otherwise
          return response
        }
      ]
    },
    mutableDefaults: true
  })

  const data = await instance.get('/test')
  console.log('data.body', data.body)
```

Actual result:
```js
beforeRequest
afterResponse
beforeRequest
data.body
```

Expected result:
```js
beforeRequest
afterResponse
beforeRequest
afterResponse
data.body { test: 'added-param' }
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
It works as expected. `retryWithMergedOptions` doesn't start from scratch. The `afterResponse` hook has been already called and there are no more.
