### ISSUE TITLE
A body with a Readable can cause uncaughtException

### ISSUE THREAD

**Issue by kanongil** [sindresorhus/got#1507]
#### Describe the bug

 - Node.js version: v14.14.0
 - OS & version: n/a

If a `Readable` that has been passed as a `body` of a request is too quick to finish, got will fail to perform the request, and instead throw an error in an `end` handler.

Note that in general, it is bad idea to ever _throw in an event handler_, since it will cause other listeners to not be called, and will likely (as in this case) cause en `uncaughtException`. The error should probably have been emitted/rejected on the got request instead.

#### Actual behavior

Process exits with `uncaughtException`:
```
<snip>/node_modules/got/dist/source/core/index.js:687
            throw new TypeError('The payload has been already provided');
            ^

TypeError: The payload has been already provided
    at Request.onLockedWrite (<snip>/node_modules/got/dist/source/core/index.js:687:19)
    at onend (_stream_readable.js:684:10)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

#### Expected behavior

It actually attempts to post the stream payload.

#### Code to reproduce

```js
const { Readable } = require('stream');
const Got = require('got');

const stream = new Readable({ read() {} });
const request = Got.post('http://www.google.com', {
    body: stream
});

stream.push('hi');
stream.push(null);
stream.resume();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by kanongil** [comment]
One workaround, is to pipe() the readable to a got stream, instead of passing it as a body.

**Comment by szmarczak** [comment]
I'm getting `HTTPError: Response code 405 (Method Not Allowed)` instead. Can you please post a RunKit example?

**Comment by kanongil** [comment]
Sure https://runkit.com/kanongil/got-uncaughtexception.

**Comment by szmarczak** [comment]
Ah indeed, forgot about `stream.resume()`.

**Comment by szmarczak** [comment]
I think it has something to do with

https://github.com/sindresorhus/got/blob/e0cb8206dacf352ce969267209c5c390f0cafabf/source/core/index.ts#L1399-L1413
