### ISSUE TITLE
Support `AbortController`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#1511]
Node.js 15 now supports `AbortController` and it makes sense for us to support it in Got. While I'm personally not a big fan of its overly verbose way of handling cancellation, it seems to become the de-facto way of handling cancellation going forward.

I think we should still retain the current `.cancel()` method if possible.

https://medium.com/@nodejs/node-js-v15-0-0-is-here-deb00750f278
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://github.com/nodejs/node/commit/8390f8a86b

**Comment by szmarczak** [comment]
> I think we should still retain the current .cancel() method if possible.

👍 Maybe throw if the signal option is provided? That way we would avoid ambiguity.

**Comment by sindresorhus** [comment]
> 👍 Maybe throw if the signal option is provided?

👍🏻
