### ISSUE TITLE
Memory leak reported by Jest

### ISSUE THREAD

**Issue by tmorell** [sindresorhus/got#1516]
#### Describe the bug

 - Node.js version: 14.8.0
 - OS & version: Manjaro 5.4.67

#### Actual behavior

Jest is reporting a memory leak, "Your test suite is leaking memory.".

#### Expected behavior

There should be no such report.

#### Code to reproduce

```js
import got from "got";

test("just a test", () => {
    expect(true).toBeTruthy();
});

// Not even called, but forcing load
function loadIt(): void {
    console.log(got.name);
}
```

It does not happen with other packages, for example replacing got with express or Mongodb.

Using:
Jest: 26.6.1
ts-jest: 26.4.3

jest.config.js
```js
module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node'
};
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
What exactly is leaking? Does Jest show a trace log or something? There's nothing actionable in this report. Jest has also had many false-positives with the memory leak reporting in the past.

**Comment by tmorell** [comment]
I was able to trace it to this specific global reference:
./source/core/index.ts
```js
const globalDnsCache = new CacheableLookup();
```

**Comment by szmarczak** [comment]
There is no memory leak, it's a false-positive by Jest. Related with https://github.com/facebook/jest/issues/9982
