### ISSUE TITLE
Add additional info to error object

### ISSUE THREAD

**Issue by kobik** [sindresorhus/got#1517]
#### What problem are you trying to solve?
Whenever I get an error I'd like log all relevant data, such as the request options and retryCount.

#### Describe the feature
Add request options and retryCount to the error object

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got#errors
https://github.com/sindresorhus/got#response
https://github.com/sindresorhus/got#retrycount

**Comment by kobik** [comment]
@szmarczak you're correct regarding the options, but `retryCount` is missing on some errors as is part of the response object which is missing in some cases.

**Comment by szmarczak** [comment]
Then you can do `error.response ? 0 : error.response.retryCount`.

**Comment by kobik** [comment]
But in case of a retries that eventually ended with error without a response, I'd like to have the actual `retryCount`

**Comment by szmarczak** [comment]
Closing in favor of #1353 (which is basically the same issue)
