### ISSUE TITLE
Body coming back as an empty string instead of null

### ISSUE THREAD

**Issue by rkhir** [sindresorhus/got#1519]
#### What would you like to discuss?

My service returns an empty body, which was being resolved as null in request-promise. 
but `got` is resolving the body as an empty string which is causing assertions failures when validating the response against the service swagger YAML using 'chai-openapi-response-validator' 

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
The answer is no, you need to either rewrite the tests or use a handler to replace empty strings with a null.

**Comment by szmarczak** [comment]
You can use an `afterResponse` hook to do this.
