### ISSUE TITLE
Http2 downloads are super slow

### ISSUE THREAD

**Issue by kanongil** [sindresorhus/got#1520]
#### Describe the bug

 - Node.js version: v14.14.0
 - OS & version: macOS 10.15.7

Http2 downloads are horrendously slow due to https://github.com/nodejs/node/issues/31084, with no workaround.

Note: the actual transfer speed will vary drastically depending on your link speed and the RTT to the server.

#### Actual behavior

Super slow transfer: `default: 48.537s`

#### Expected behavior

Something matching the `http2: false` speed, which returned: `default: 10.923s`

#### Code to reproduce

```js
const Got = require('got');

(async () => {

    console.time();
    await Got.get('https://mirror.leaseweb.com/speedtest/100mb.bin', { http2: true });
    console.timeEnd();
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Fixed in `http2-wrapper@2.0.4`

**Comment by kanongil** [comment]
@szmarczak Won't your update crash on node 14? You unconditionally call a non-existing API in your patch.

**Comment by szmarczak** [comment]
So no, it doesn't crash because it doesn't call that function.
