### ISSUE TITLE
get original request body from response

### ISSUE THREAD

**Issue by spasquali-ww** [sindresorhus/got#1537]
I'd like to get back the original request `body` on a POST `response`. Is that possible?

Note that I'm setting `throwHttpErrors` to `false`, so parsing through this mixed `response`.

I'm able to find the Symbol for (body) in `response.value.request` and derive what I need from there, but am hoping there is a shortcut (don't want to iterate through `response` Symbols on every request)

Thanks!

- [x ] I have read the documentation.

**Comment by szmarczak** [comment]
`response.request.options.body` but note that it won't work for streams.

**Comment by spasquali-ww** [comment]
Just what I needed (`response.value.request.options.body` in my case). Thank you so much!
