### ISSUE TITLE
JSON shortcut does not work when using throwHttpErrors: false

### ISSUE THREAD

**Issue by deadNightTiger** [sindresorhus/got#1540]
#### Describe the bug

 - Node.js version: v14.14.0
 - OS & version: Fedora 33

When the server returns an error code with JSON body, and I try to parse it using `.json()` and `{throwHttpErrors: false}`, I get the following error:

```
TypeError: Cannot read property 'request' of undefined
    at /path/to/my/project/node_modules/got/dist/source/as-promise/index.js:157:48
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### Actual behavior
TypeError is thrown

#### Expected behavior
Returning the body of response, parsed as JSON (matching the behavior of `{responseType: 'json', resolveOnlyBody: true}`, as documented)

#### Code to reproduce
https://runkit.com/embed/3tt06wxjbio1
```js
const got = require("got");
await got("https://api.github.com/user", {throwHttpErrors: false}).json();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by akhll** [comment]
why have you closed this issue ?
actually i have the same problem now with got version 11.8.2

**Comment by szmarczak** [comment]
> why have you closed this issue ?

![Screenshot_20210610-170920_Chrome](https://user-images.githubusercontent.com/36894700/121550079-b5009800-ca0e-11eb-9d15-12fb93632d25.png)

> actually i have the same problem now with got version 11.8.2

Please open another issue with the full code to reproduce the bug.
