### ISSUE TITLE
Property 'data' does not exist on type 'unknown' when using .post().json()

### ISSUE THREAD

**Issue by bluecomm42** [sindresorhus/got#1548]
#### Describe the bug

 - Node.js version: N/A
 - OS & version: N/A
 - got version: 11.8.0

#### Actual behavior
When using `(await got.post().json()).data` in TypeScript it gives the error `Property 'data' does not exist on type 'unknown'`.
**Note:** This is a *complier* error, the code runs without issue, but the compile-time type checker isn't happy.

#### Expected behavior
I would expect that the code wouldn't error, without me having to resort to using `// @ts-ignore` or writing a custom interface to conform the returned object to.

#### Code to reproduce

```typescript
// <snip>
const res = await got
  .post("<url>", { body: form, headers })
  .json();
return res.data; // <-- error is here
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The .json() function takes a template. Use `.json<{data: type}>()`

**Comment by szmarczak** [comment]
This is TypeScript - we are trying to be as strict as possible.
