### ISSUE TITLE
Is it easy to port from request to got?

### ISSUE THREAD

**Issue by sergeyt** [sindresorhus/got#155]
Just wonder how to port [apiproxy](https://github.com/sergeyt/apiproxy/blob/master/index.js) to use got with support of uploads and text/event-stream? Maybe someone knows the better way to make transparent HTTP proxy in express.js server?

**Comment by floatdrop** [comment]
@sergeyt don't see any problems there, should be pretty straightforward.

**Comment by floatdrop** [comment]
**More general answer:** request have rich functionality and if you are using it (for example [HAR](https://github.com/request/request#support-for-har-12), [proxies](https://github.com/request/request#proxies), [OAuth](https://github.com/request/request#oauth-signing)) - you will need to use corresponding modules with got. For some of those [we have code-snippets](https://github.com/sindresorhus/got#proxies) on how you can implement them.

**Comment by sergeyt** [comment]
@floatdrop so I can use just tunnel package to simulate proxy behavior, right?

**Comment by floatdrop** [comment]
@sergeyt `tunnel` package provides `http`/`https` Agent to use proxies, not to create your own. I guess [`http-proxy`](https://www.npmjs.com/package/http-proxy) is what you are looking for.

**Comment by sergeyt** [comment]
@floatdrop thanks for answers!
