### ISSUE TITLE
changing the order of headers

### ISSUE THREAD

**Issue by liteCarma** [sindresorhus/got#1551]
I noticed that Got changes the order of headers, but this is critical in my case. Is there any way to change this?

**Comment by sindresorhus** [comment]
Please use English for the issue title too.

Why is it a problem?

**Comment by liteCarma** [comment]
> Please use English for the issue title too.

Oh, sorry I accidentally wrote (

> Why is it a problem?

The server checks this and denies access

**Comment by szmarczak** [comment]
Got doesn't change the order of the headers, it only converts their names to lower case.

**Comment by shirshak55** [comment]
@szmarczak what to do if we want uppercase header instead of lowercase?

**Comment by szmarczak** [comment]
According to the spec headers are case insensitive. But if you badly need them you can pass a custom `request` function or use an agent.

**Comment by shirshak55** [comment]
@szmarczak do you mean i should write my own agent? i am currently using hpagent. Let me know I really don't know too much about agent thing.

**Comment by szmarczak** [comment]
```js
const https = require('https');

const agent = new https.Agent({
    keepAlive: true
});

class TransformHeadersAgent {
    constructor(agent) {
        this.agent = agent;
    }
    
    addRequest(request, options) {
        const headers = request.getHeaderNames();
        
        for (const header of headers) {
            const value = request.getHeader(header);
            request.removeHeader(header);
            request.setHeader(this.transformHeader(header), value);
        }
        
        return this.agent.addRequest(request, options);
    }
    
    transformHeader(header) {
        return header.split('-').map(part => {
            return part[0].toUpperCase() + part.slice(1);
        }).join('-');
    }
    
    // The below are required
    // Used by https://github.com/nodejs/node/blob/master/lib/_http_client.js
    get keepAlive() {
        return this.agent.keepAlive;
    }
    
    get maxSockets() {
        return this.agent.maxSockets;
    }
    
    get options() {
        return this.agent.options;
    }
    
    get defaultPort() {
        return this.agent.defaultPort;
    }
    
    get protocol() {
        return this.agent.protocol;
    }
}

const wrappedAgent = new TransformHeadersAgent(agent);

const request = https.request('https://httpbin.org/anything', {
    agent: wrappedAgent,
    headers: {
        test: 'foo'
    }
}, response => {
    console.log(request._header);
    
    const chunks = [];
    
    response.on('data', chunk => {
        chunks.push(chunk);
    });
    
    response.on('end', () => {
        const buffer = Buffer.concat(chunks);
        const json = JSON.parse(buffer);
        console.log(json.headers);
    });
});

request.end();
```

**Comment by H0r53** [comment]
@szmarczak `got` does indeed manipulate the header order. Most of the headers it does not rearrange, but in my case `got` is always moving the `User-Agent` header to the first position instead of leaving it in the specified position.

**Comment by H0r53** [comment]
@szmarczak that does work! Though it makes my TypeScript compiler unhappy. I'm getting TS errors such as this

```
TS2339: Property 'defaults' does not exist on type 'GotJSONFn & Record<"head" | "get" | "post" | "put" | "patch" | "delete", GotJSONFn> & { stream: GotStreamFn & Record<"head" | "get" | "post" 
| "put" | "patch" | "delete", GotStreamFn>; ... 8 more ...; TimeoutError: typeof TimeoutError; } & ... 11 more ... & { ...; }'.
```
Should I just `// @ts-ignore` or is there a way I can use this workaround while making TypeScript happy?

**Comment by szmarczak** [comment]
Yeah you can just `// @ts-expect-error` it. I noticed you have `GotJSONFn` but there's no such type. here Why don't you use the default typings?

**Comment by H0r53** [comment]
I'm honestly not sure. I just installed got with `npm install @types/got` which gave me version `^9.6.12`, then I imported it with `import got from "got";`. Should I be doing something differently to get the default typings?

**Comment by shirshak55** [comment]
@H0r53 I think you don't have to import @types/got. Got is written in typescript entirely.

**Comment by H0r53** [comment]
@shirshak55 I'm not importing `@types/got`. My import line looks like this: `import got from "got"`. When I installed got via npm, I used this command to install the TypeScript version: `npm install @types/got`. Should I be doing something else to get the default typings?
