### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#1552]
I have enabled the [Discussions feature](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/). It would be a good place to ask Got-related questions and discuss it in general.

**Please be kind and constructive.**

This issue can be used for discussing adding new categories and other meta things.

**Comment by malihdabboussi** [comment]
Hello, i am new to GOT and node js, I am trying to test the debugging tool using Charles with SSL proxy enabled, but the traffic is not intercepted as expected. anyone can help?

const got = require("got");
const tunnel = require("tunnel");

const ApiUrl = "https://api.ipify.org?format=json";

const ProxyHost = "localhost";
const ProxyPort = "8866";

(async () => {
  try {
    const ProxIP = await got(ApiUrl, {
      agent: {
        http: tunnel.httpsOverHttps({
          proxy: {
            host: ProxyHost,
            port: ProxyPort,
          },
        }),
      },
    });
    console.log(ProxIP["ip"]);
  } catch {
    console.log("error");
  }
})();

**Comment by sindresorhus** [comment]
@malihdabboussi Please read the issue text. This is not the place to discuss this.

**Comment by malihdabboussi** [comment]
oh sorry my bad

**Comment by szmarczak** [comment]
I think it would be a very good move to add a link to Discussions in the readme.
