### ISSUE TITLE
Don't get any error output when invalid url is requested

### ISSUE THREAD

**Issue by mrgodhani** [sindresorhus/got#156]
When I request invalid url e.g "http://example.comhttp://example.com" It doesn't catch / stop the execution and doesn't give me any kind of error.

**Comment by sindresorhus** [comment]
That's unfortunately how promises works. They are silent by default. You have to explicitly `.catch()` it.

**Comment by sindresorhus** [comment]
You might find https://github.com/sindresorhus/loud-rejection useful ;)

**Comment by mrgodhani** [comment]
I just figure out that it was due to retries. By default it retries 5 times. So I had to explicitly make to 0.
