### ISSUE TITLE
[ts] make context type more free

### ISSUE THREAD

**Issue by rifler** [sindresorhus/got#1562]
#### What problem are you trying to solve?

I think it is a common way in express applications to use `req` as application context to store some information about user like lang, tld, region and so. And it is easy to use `req` as got `context`.

But now it is prohibited on type-level only (runtime works)

#### Describe the feature

make `context` type compatible with express' Request. for example can turn back old behaviour and describe context as `object` instead of `Record<string, unknown>`

this change was made in https://github.com/sindresorhus/got/pull/1345/files

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by rifler** [comment]
If the current behaviour with `Record<string, unknown>` is OK, then I suppose it should be done in major release, not in 11.5.0

**Comment by sindresorhus** [comment]
That change was intentional. `object` is too loosely typed. We could maybe make the `context` generic, so you could pass in the `Request` type there.
