### ISSUE TITLE
The documentation doesn't clarify if the promise api throws if status code is not 4xx or 5xx

### ISSUE THREAD

**Issue by quesurifn** [sindresorhus/got#1570]
#### What would you like to discuss?

The documentation doesn't clarify if the promise api throws if status code is not 4xx or 5xx.

What is the behavior here? 

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
> Determines if a got.HTTPError is thrown for unsuccessful responses.

https://httpstatuses.com/

> 4×× Client Error
> 5×× Server Error
