### ISSUE TITLE
RequestError: queryA EREFUSED

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/got#1573]
Hello,

After running a production service for a while, I noted DNS errors tend to occur in a very sporadic way

https://sentry.io/share/issue/fc8344d080f349f7a6fe2f18c52689f0/

I think `http-timer` is throwing the error after the connection hangs. I'm not sure what should be the solution; maybe retry DNS errors could be a desirable thing for trying to minimize them?

In that error stack trace, the connection is targetting s.microlink.io which is actually an s3 bucket, so it normally works as expected.

**Comment by szmarczak** [comment]
`http-timer` just forwards the error.  Got here works as expected.

> dns.REFUSED: DNS server refused query.

https://nodejs.org/api/dns.html#dns_error_codes

The underlying DNS server rejected the request. Try CloudFlare DNS or Google DNS. If that doesn't help then perhaps you're running this in a container which has some limits.

**Comment by Kikobeats** [comment]
My `got` instance is using a custom `dnsCache`:

```js
const cloudFlareDnsResolver = (() => {
  const resolver = new Resolver()
  resolver.setServers(['1.1.1.1', '1.0.0.1'])
  return resolver
})()

const dnsCache = new CacheableLookup({
  resolver: cloudFlareDnsResolver,
  maxTtl: ms('24h'),
  cache: new Map()
})

const got = got.extend({ cloudFlareDnsResolver})
```

As you can see I'm already using CloudFlare DNS. You're right, my production servers are running under Kubernetes Pods that use Google DNS by default. 

Maybe it's just a thing related to CloudFlare DNS that can be resolved by adding Google DNS as a fallback

```js
resolver.setServers(['1.1.1.1', '1.0.0.1', '8.8.8.8', '8.8.4.4'])
```

I'm going to try that approach for a while, thanks for the reply!

**Comment by szmarczak** [comment]
Are you passing `dnsCache` to `got.extend`? In the code above you posted `got.extend({cloudFlareDnsResolver}})` which has no effect.

**Comment by Kikobeats** [comment]
oh yea sorry; I'm passing it as `got.extend({ dnsCache })`

**Comment by szmarczak** [comment]
1. Once the error is thrown, how long do you have to wait to see it again?

2. Are you running more than one instance on a single container?

**Comment by Kikobeats** [comment]
this is the cadence of error

<img width="483" alt="Screen Shot 2021-01-02 at 00 00 15" src="https://user-images.githubusercontent.com/2096101/103447591-8cb98400-4c8d-11eb-8367-0aeb7c426f13.png">

I'm running one instance per pod and multiple pods on the same node

**Comment by szmarczak** [comment]
I would first make sure that there's only one CacheableLookup per instance. Then try 8.8.8.8 - if that doesn't help then you can try setting up your own DNS server: https://github.com/coredns/coredns
