### ISSUE TITLE
status code cov vs coveralls for readme

### ISSUE THREAD

**Issue by MichaelDimmitt** [sindresorhus/got#1584]
#### What would you like to discuss?

Looking at the readme,

code cov  === 0%
coveralls.io === 98%

Should coveralls.io replace code cov as the shield in the header of the readme?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
We switched to codecov. The coverage hasn't been uploaded yet because the tests are failing - some of them need to be updated due to Node.js updates.
