### ISSUE TITLE
@szmarczak would you mind giving an example?

### ISSUE THREAD

**Issue by ngingihy** [sindresorhus/got#1588]
@szmarczak
One solution could be calling `await this._finalizeBody();` right before sending the body and making the user change (re-initialize) the body in the `beforeRedirect` (or `beforeRequest`) hook, but, to me, it seems a little tricky.

Another solution could be reading all the stream a single time and using it as a Buffer when making requests, but this is going to break the stream feature (big file are going to fill the RAM).

_Originally posted by @Giotino in https://github.com/sindresorhus/got/issues/1271#issuecomment-629647503_

**Comment by Giotino** [comment]
https://github.com/sindresorhus/got/issues/1500#issuecomment-709918643

**Comment by szmarczak** [comment]
Please fill out the issue template properly. Otherwise the issue will remain closed.
