### ISSUE TITLE
When transfer encoding is chunked, GOT sometimes does not download full content

### ISSUE THREAD

**Issue by adityapatadia** [sindresorhus/got#1591]
#### Describe the bug

 - Node.js version: 14.15.1. GOT latest.
 - OS & version: Ubuntu 20.04

#### Actual behavior

When downloading content which does not have content-length header, i.e. chunked transfer, GOT sometimes does not download full content when `responseType: 'buffer'` is set. One example URL is here: https://cdn.sentinelassam.com/h-upload/2021/01/28/193125-whatsapp-image-2021-01-28-at-112922-am.webp

#### Expected behavior

It should download full content.

#### Code to reproduce

Not able to re-produce reliably as it happens only sometimes. I am not sure under which conditions but it certainly happens.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
There unfortunately no actionable info here. Would you be able to try on the latest Node.js 15 release?

**Comment by adityapatadia** [comment]
We could solve it by putting this code

```javascript
let lengthMatches = true;
if (response.headers && response.headers['content-length']) {
    lengthMatches = parseInt(response.headers['content-length']) == response.body.byteLength;
  }

if(response.body.byteLength != 0 && lengthMatches && response.complete){
   //everything looks okay....
  }
```

May be this can give you some idea? We will not be able to try on Node 15 because this issue is not reproducible on local machine and can only be produced when there is very high load. We will still give you info if we find something.

**Comment by szmarczak** [comment]
Closing in favor of #1462
