### ISSUE TITLE
Package name being a "stop word" makes it impossible to get help beyond official documentation.

### ISSUE THREAD

**Issue by likwidoxigen** [sindresorhus/got#1592]
#### What would you like to discuss?
Unlike "axios" "node-fetch" and "superagent" it is impossible to use common search engine like DuckDuckGo or Google to search for additional help and examples of usage of this library rendering it against it's description of "Human-friendly".
I've checked the documentation for assistance and other resources but found none.
Has there been discussion or consideration regarding this issue? 

...

#### Checklist

- [ x ] I have read the documentation.

**Comment by sindresorhus** [comment]
I agree the name is unfortunate, but in my defense, I never thought Got would become this popular. The initial version of Got was just 40 lines. The previously most popular HTTP client is named "request". I wouldn't say it's much more easily googlable. Just google `got node.js` or `got javascript`.

Support places:
- https://stackoverflow.com/questions/tagged/got+node.js
- https://github.com/sindresorhus/got/discussions

**Comment by likwidoxigen** [comment]
From a natural language processing perspective stop words are filtered out. So the word "request" wouldn't qualify as a stop word and is searchable. Stop words are things like "got", "and", "the"  are usually filtered out and so searching by them becomes luck of the draw.

I see what you mean about the surprise popularity and by the same right from that popularity you can choose not to consider or investigate a name-change because of it.

**Comment by prateek-somaiya** [comment]
It is not just this repo, I have seen other repos from @sindresorhus and quite a few of them follow the same pattern, very frustrating... here are some examples... 
https://github.com/sindresorhus/Regex
https://github.com/sindresorhus/public-ip
https://github.com/sindresorhus/del

The list goes on... there are just too many...

@sindresorhus don't get me wrong, you do great work, but really? got? cmon dude...
