### ISSUE TITLE
Missing method in afterResponse hook

### ISSUE THREAD

**Issue by mgcrea** [sindresorhus/got#1594]
#### Describe the bug

 - Node.js version: v14.15.4
 - OS & version: macOS big sur

In an `afterResponse` hook, the response object (first argument) always have a `null` value for the key `method`:

The method can be found in `response.req.method` but I guess it should be properly exposed back to the root `response` object since the key is there. 

#### Code to reproduce

```js
afterResponse: [
  (response) => {
    const { url, method, body } = response;
    console.log(`Just received response to request url=${url} with method=${method}`);
    console.log(`Actual method was ${response.req.method}`);
    return response;
  },
],
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
> #### [Response](https://github.com/sindresorhus/got#response)
> 
> The response object will typically be a [Node.js HTTP response stream](https://nodejs.org/api/http.html#http_class_http_incomingmessage), however, if returned from the cache it will be a [response-like object](https://github.com/lukechilds/responselike) which behaves in the same way.

[![image](https://user-images.githubusercontent.com/36894700/106290832-33705080-624b-11eb-8044-b8c13607948a.png)](https://nodejs.org/api/http.html#http_message_headers)

Everything is in the docs :) `response.request.options.method` is what you want.

**Comment by mgcrea** [comment]
Thanks! Sorry for the trouble.
