### ISSUE TITLE
Return body when statusCode !== 200

### ISSUE THREAD

**Issue by luanmuniz** [sindresorhus/got#160]
I'm trying to use `got` in an api library.
But the api return statusCode 404, 401 and 500 when there are erros. 
But the erros codes and messages are in the body. 
Today, i cant find a way to get the body using got. i had to switch back to `request` :(
im using promise mode

**Comment by sindresorhus** [comment]
The first example in the readme shows how you can access the body in an error.

```js
    .catch(error => {
        console.log(error.response.body);
        //=> 'Internal server error ...'
    });
```

**Comment by luanmuniz** [comment]
You are right. So sorry for not notice that before
