### ISSUE TITLE
Timeout removed on response event

### ISSUE THREAD

**Issue by ksladkov** [sindresorhus/got#161]
Here's the test that reproduces the issue.
https://gist.github.com/ksladkov/cf70614f3ee07c8a34be
First two test cases are passed, but the last does not.

I think it happens because after connection established the http 'response' event emitted, then timeout cleared in timed-out lib.
It can be fixed (at least it fixed in my case) by emitting custom event in got: https://github.com/sindresorhus/got/blob/master/index.js#L114
```
ee.emit('done', res);
```
and listening this 'done' event in timed-out lib.

**Comment by floatdrop** [comment]
@ksladkov we behaving like [request](https://github.com/request/request) module in this case, because if server responded with headers - then it is alive and working. I don't think we should remove timeout on response body end - suppose you have long-polling server or just response body size can vary.

**Comment by ksladkov** [comment]
@floatdrop thank you, it makes sense. But we need to wait the response no longer than some fixed time and abort when time is over. Sure, it is not a problem to use some external function for this, but is exists any way to get such behavior with `got`? If not, I think, the documentation for the `timeout` option should be fixed a bit to remove ambiguity.

**Comment by floatdrop** [comment]
@ksladkov yup, some places in readme still need to be improved. Fixed in https://github.com/sindresorhus/got/commit/db420fbab9fe5c3c6fdbea3f19a32600e1f3c7b0

**Comment by SEAPUNK** [comment]
...but say that you _do_ want a timeout for end-of-response, what would you suggest?

**Comment by floatdrop** [comment]
@SEAPUNK I would suggest use something like [`.timeout`](http://bluebirdjs.com/docs/api/timeout.html) from Bluebird in case of Promise and something similar for Stream API.

**Comment by SEAPUNK** [comment]
Alright, thanks!

**Comment by SEAPUNK** [comment]
Is there a way to "abort" a request mid-way on given timeout? There could be an instance where a keep-alive connection never finishes sending the response body (even if it's very rare).

**Comment by floatdrop** [comment]
@SEAPUNK there is [a way](https://github.com/sindresorhus/got#onrequest-request), but only for Streams, you can join discussion about cancelation in Promise API in got here #211

**Comment by SEAPUNK** [comment]
Okay, thank you!
