### ISSUE TITLE
Retry when timing-out question

### ISSUE THREAD

**Issue by patryk-smc** [sindresorhus/got#1611]
#### What would you like to discuss?

I'm dealing with quite unresponsive API and would like to retry request up to 3 times if response is taking longer than 1000 ms. 

For that, I'm using options:

```
timeout: 1000,
retry: 3,
```

However, when I inspect requests with my instrumenting tool, I can see that first request took more than 2000 ms.
![image](https://user-images.githubusercontent.com/37963339/108108244-aa517a00-7090-11eb-9b1b-5590e122b112.png)

I would expect that a second request would occur after 1000 ms.

What I'm missing here? Are my options not valid for what I want to achieve?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> Delays between retries counts with function 1000 * Math.pow(2, retry - 1) + Math.random() * 100, where retry is attempt number (starts from 1).

https://github.com/sindresorhus/got#retry
