### ISSUE TITLE
pseudo-head request method?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#162]
Because some servers can have issues with using "head" and using "get" can download more than we may want, I propose a middle ground where "get" is used, but the stream is closed once the body data starts to come in. At which point, any any of the body that may have downloaded can be excluded from the returned response.

Maybe call it "neck" method ;)

**Comment by sindresorhus** [comment]
> some servers

What servers? I don't like the idea of having to support broken servers.

**Comment by julien-f** [comment]
IMHO, this is out of got's scope, if it starts to support this kind of thing it will get bigger than request.

**Comment by stevenvachon** [comment]
Yes, broken servers.

**Comment by floatdrop** [comment]
@stevenvachon maybe this can be achieved through [abort](https://github.com/sindresorhus/got#streams) on response event - do not tested this myself.

**Comment by stevenvachon** [comment]
@floatdrop very cool. Considering this, would any of you agree that a shortcut to this functionality would still be a good idea? I think it contributes to this project's goal and doesn't bloat.

**Comment by floatdrop** [comment]
@stevenvachon I'd recommend you to create a module (like [gh-got](https://www.npmjs.com/package/gh-got)), that incapsulates these calls to a broken server.

For now there is not way to cancel request in Promise API, so shortcut to `abort` method could be handy.

**Comment by stevenvachon** [comment]
@floatdrop but then I'd need to maintain it :persevere:

**Comment by stevenvachon** [comment]
I'd think that if it *were* to be implemented in this library, which I hope that it will be, it should be its own method: `got.pseudoGet()`

**Comment by sindresorhus** [comment]
Adding stuff just because of broken servers is a slippery slope. Probably better to try to add it to `requests` which is huge for a reason and covers a lot more legacy and broken behavior than `got`.

**Comment by stevenvachon** [comment]
I'd thought that `request` was unnecessarily bloated and messy. Interesting to know that it got that way for good reason. Fortunately, there's [Request Next](https://github.com/request/request/issues/1982).

**Comment by stevenvachon** [comment]
I take it back -- not just for broken servers. Some servers simply refuse to support http head and spit out a 405 error.

**Comment by stevenvachon** [comment]
@sindresorhus please re-open -- see reason above.
