### ISSUE TITLE
Support *.mjs

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#1635]
#### What problem are you trying to solve?
Trying to `import` this package into an *.mjs file with Node.js

Since this project is transpiled to CommonJS, you'll need to include [babel-plugin-add-module-exports](https://npmjs.com/babel-plugin-add-module-exports) in your build pipeline.

#### Checklist

- [z] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
https://nodejs.org/api/esm.html#esm_commonjs_namespaces

**Comment by stevenvachon** [comment]
Eww, I don't want to `import { default }`. It's better to correctly support the Node.js ecosystem, which includes *.mjs

**Comment by stevenvachon** [comment]
Please reopen.. I've reworded my original post.

**Comment by sindresorhus** [comment]
You have to import it as a default import. This is nothing unique to Got. We don't plan to do anything about this. However, we do plan to move Got to ESM in the near future.

**Comment by stevenvachon** [comment]
But you can satisfy both worlds with the aforementioned Babel plugin.

**Comment by sindresorhus** [comment]
I'm not interested in adding that Babel plugin.
