### ISSUE TITLE
incorrect interpretation 301 as an error

### ISSUE THREAD

**Issue by a-x-** [sindresorhus/got#164]
request:
~~`require('got')('http://www.cian.ru/cat.php?deal_type=sale&metro[0]=14')`~~
**UPD**: 
```js
require('got')('http://www.cian.ru/cat.php?deal_type=sale&metro[0]=14',
    { method: 'head' })
    .then(data=>console.log(data), e=>console.log('err', e))
```

result:
```
err [HTTPError: Response code 301 (Moved Permanently)]
  message: 'Response code 301 (Moved Permanently)',
  host: 'www.cian.ru',
  hostname: 'www.cian.ru',
  method: 'head',
  path: '/cat.php?deal_type=sale&metro[0]=14',
  statusCode: 301,
  statusMessage: 'Moved Permanently' }
```

is it have to be interpret as a success request?

and i cannot access response headers (my interest: `Location` header) that's request.

**Comment by sindresorhus** [comment]
It should redirect automatically for you when the code is 301: https://github.com/sindresorhus/got/blob/db420fbab9fe5c3c6fdbea3f19a32600e1f3c7b0/index.js#L35 Maybe the `location` header is missing in the response.

**Comment by floatdrop** [comment]
```js
const got = require('got')
got('http://www.cian.ru/cat.php?deal_type=sale&metro[0]=14')
  .then(data => console.log(data), err => console.log(err));
```

@a-x- this code works for me on `5.4.0` and `6.0.0` and gives HTML in output.

**Comment by a-x-** [comment]
hm, i forgot write here about this: `got(uri, { method: 'head' })`

**Comment by floatdrop** [comment]
@a-x- okay, got it reproduced. Please use `got.head(...)` for now until this is fixed.

**Comment by floatdrop** [comment]
`5.4.1` and `6.1.1` released with fix.

**Comment by a-x-** [comment]
thank you! ^_^
