### ISSUE TITLE
Option to disable following redirects

### ISSUE THREAD

**Issue by ruyadorno** [sindresorhus/got#165]
Hello there, first of all, many thanks for all the hard work that went into this module :blush: 

I have a suggestion that may or may not make any sense for it to be implemented on **got** - that would be to add an option to disable the automatic following of redirects.

I'm using **got** in an express app that serves as a middleman/proxy between the client and other servers and I would love to have the possibility to just forward the 3xx status codes from the original server.

Thanks for your time and keep up with the good work :zap:

**Comment by floatdrop** [comment]
@ruyadorno thanks for the nice issue and PR!

After some thinking I'm quite positive, that `got` is not the best solution to proxy request from other server to client – `got` will decompress content and send broken response with decompressed content and `content-encoding: gzip` (if you just passing headers by).

May be it will be a better solution to use native `http` module instead?

**Comment by ruyadorno** [comment]
hi @floatdrop!

I understand your reasoning, I have thought the same thing and as a matter of fact I actually reimplemented three times the same micro-service to try different approaches but **got** was the clear winner for me.

The reason being that I actually want to fetch all the data from the server, parse it, modify and send it back to the user - **got** abstracts a lot of the hard work from that, such as gzipping on prod but not on local development, not to say the beautiful API it provides.

That said, I really don't mean to make any pressure, please take time to evaluate if this is a constructive addition to other users/use cases and feel free to close the PR if that's not the case :blush: 

:+1: thanks again!

**Comment by dfilatov** [comment]
+1 to add this feature. I have some cases when I have to parse location of redirect.

**Comment by floatdrop** [comment]
Released in `5.6.0` and `6.3.0` :tada:

**Comment by dfilatov** [comment]
@floatdrop Thanks!
