### ISSUE TITLE
Compiling error with Typescript

### ISSUE THREAD

**Issue by tom-mayer** [sindresorhus/got#1653]
#### What would you like to discuss?

I use Spectron for Electron integration testing which has webdriver as a dependency which in turn uses got. I updated from a quite old version of Spectron to the current one and running into some issues with got now that I don't know how to resolve: 

`electron.wrapper/node_modules/webdriver/node_modules/got/dist/source/as-promise/types.d.ts(251,102): error TS2709: Cannot use namespace 'PCancelable' as a type.`

This is the error I get. I tried node versions 10.x, 14.x and 15.x. My tsconfig looks like this (not sure if this is relevant): 

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": true,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*"
      ]
    },
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": [
      "es2017",
      "dom"
    ],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "include": [
    "app/**/*"
  ]
}
```

If there is more information I can provide please let me know.

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
What Got version?

**Comment by tom-mayer** [comment]
package.json says 11.8.2

**Comment by tom-mayer** [comment]
I found out my tsconfig was the issue. I had to remove 
```
    "paths": {
      "*": [
        "node_modules/*"
      ]
    },
```
I don't really understand why, but it solved the compile error.
