### ISSUE TITLE
If agent fails, try again without

### ISSUE THREAD

**Issue by joergd** [sindresorhus/got#1654]
If I start up a stream request with an agent (proxy), and that request fails (if say the proxy is unavailable), is there an easy way to fallback to making the call without the agent?

**Comment by szmarczak** [comment]
It should be possible to remove the `agent` option in the `beforeRetry` hooks.

**Comment by szmarczak** [comment]
Let's keep this issue. This needs a test.

**Comment by joergd** [comment]
I can't use that hook, as I am streaming ...

**Comment by szmarczak** [comment]
In that case - yes, it's possible: https://github.com/sindresorhus/got#retry

**Comment by joergd** [comment]
Yeah I looked at that - but I couldn't get that to work. Just to confirm with that sample code, the writeStream is the stream that represents the actual response that I can stream further along in my pipeline?

**Comment by szmarczak** [comment]
This is still possible with Got v11.8.2:

```js
const https = require('https');
const got = require('got');

class MyAgent extends https.Agent {
    createConnection(port, options, callback) {
        console.log(`Connecting with MyAgent`);
        return https.Agent.prototype.createConnection.call(this, port, options, callback);
    }
}

const fn = retryCount => {
    const stream = got.stream('https://httpbin.org/status/408', {
        agent: {
            https: retryCount === 0 ? new MyAgent() : undefined
        }
    });
    
    stream.retryCount = retryCount;

    stream.on('retry', (retryCount, error) => {
        console.log('Creating new retry:', retryCount);
        fn(retryCount);
    }).on('error', error => {
        console.log('Retry count:', error.request.retryCount);
    }).resume().on('end', () => {
        console.log('`end` event');
    });
};

fn(0);
```
