### ISSUE TITLE
default maxRetryAfter is not calculated correctly

### ISSUE THREAD

**Issue by jolivaSan** [sindresorhus/got#1663]
#### Describe the bug

 - Node.js version: v12.20.0
 - OS & version: macOS Mojave | 10.14.6

In got documentation sais

> If `maxRetryAfter` is set to `undefined`, it will use `options.timeout`.

But is not working well in case of use extends

#### Actual behavior

Event if we use a timeout config like `timeout: { request: 5000 }`if don't provide a `maxRetryAfter` value when  config is "normalized" the maxRetryAfter is being calculated as `Infinity`

#### Expected behavior

As per documentation `maxRetryAfter` should get `5000` as value.

#### Code to reproduce

```js
const { describe, it } = require('mocha')
const { strictEqual } = require('assert').strict
const Got = require('got')

describe.only('default maxRetryAfter', function () {
  it('should get timeout value', async function () {
    const newGot = Got.extend({ timeout: { request: 5000 } })
    strictEqual(newGot.defaults.options.retry.maxRetryAfter, 5000)
  })
})

/**
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

Infinity !== 5000

/*
```

I think the problem is because the code to calculate default value for `maxRetryAfter` is in the method  `normalizeArguments()` and is calculating the default value before the options are merged, for this reason get timeout as undefined and the `maxRetryAfter` is getting infinity value

**Comment by szmarczak** [comment]
Weird. `{timeout:5000, retry: {maxRetryAfter: undefined}}` works as expected

**Comment by szmarczak** [comment]
https://runkit.com/szmarczak/604bbd2740bfe2001abf04a5
