### ISSUE TITLE
URI malformed exception

### ISSUE THREAD

**Issue by vmalawade** [sindresorhus/got#1669]
#### Describe the bug

 - Node.js version: 14.5
 - OS & version: MacOS

When I try to get a url formatted as follows, I get URL malformed exception
https://example.com/d2/5fdbcc0902957c5dd81f8648/525/impression?app=https%3a%2f%2fchannelstore.roku.com%2fdetails%2f13535%2fplex&cb=1530025784&us_privacy=&crid=737&crn=1835798&dadv=%eadv!&dcam=%ebuy!&dpl=%epid!&dste=%s&dsteid=%esid!&vdid=1c7364ea-9283-5d78-8fcf-681e15329795&vdhwt=SET_TOP_BOX&dnt=0&evt=impression&eadvid=48&ecid=73&ecn=0063m00000iM2BqAAK&elid=743&eln=a003m00001tFz9jAAC&ip=127.0.0.1&metro=&pub=207616&brid=1616083726321183.3656463166.12292.videoamp&vpxid=000&bwb=1
#### Actual behavior
Exception Url malformed
...

#### Expected behavior
Valid Url
...

#### Code to reproduce

```js
// https://github.com/sindresorhus/got
const got = require('got');

class Test {
	constructor() {
		console.log('Constructor is called')
		this.foo()
	}
	async foo() {
		console.log('Foo is called')
		var response;
		try {
			const url = 'https://example.com/d2/5fdbcc0902957c5dd81f8648/525/impression?app=https%3a%2f%2fchannelstore.roku.com%2fdetails%2f13535%2fplex&cb=1530025784&us_privacy=&crid=737&crn=1835798&dadv=%eadv!&dcam=%ebuy!&dpl=%epid!&dste=%s&dsteid=%esid!&vdid=1c7364ea-9283-5d78-8fcf-681e15329795&vdhwt=SET_TOP_BOX&dnt=0&evt=impression&eadvid=48&ecid=73&ecn=0063m00000iM2BqAAK&elid=743&eln=a003m00001tFz9jAAC&ip=127.0.0.1&metro=&pub=207616&brid=1616083726321183.3656463166.12292.videoamp&vpxid=000&bwb=1'
			response = await got(url);
			console.log('HTTP_Status:',response.statusCode);
			console.log(response);
			//=> '<!doctype html> ...'
		} catch (error) {
			console.log(error);
			console.log(response);
			//=> 'Internal server error ...'
		}
	}
}

const t = new Test()
```

#### Checklist

- [X] I have read the documentation.
- [X ] I have tried my code with the latest version of Node.js and Got.

**Comment by luckyyyyy** [comment]
> The exception is valid. `%ep` is not a valid component.

non-UTF-8 encoding, which is allowed

eg: action_page.php?firstname=%D6%D0%CE%C4&lastname=Mouse

GBK: 中文


```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="gbk" />
  </head>
  <body>
    <form action="action_page.php">
      First name:<br>
      <input type="text" name="firstname" value="">
      <br>
      Last name:<br>
      <input type="text" name="lastname" value="">
      <br><br>
      <input type="submit" value="Submit">
      </form>
  </body>
</html>

```
