### ISSUE TITLE
Retry not respected when using POST request

### ISSUE THREAD

**Issue by peterdemartini** [sindresorhus/got#1672]
#### Describe the bug

 - Node.js version: v12.21.0
 - OS & version: macOS 10.15.7

When setting `retry` to a number a greater than `0` and when making a `POST` request that returns a retriable status code, the request is not retried.

#### Actual behavior

The request fails after the first request

#### Expected behavior

The request should be retried until the limit is reached

#### Code to reproduce

```js
// node --unhandled-rejections=strict service.js
'use strict';

const express = require('express');

const app = express();

app.all('/:status', (req, res) => {
    const status = parseFloat(req.params.status);
    console.error('received', status);
    res.sendStatus(status);
});

app.listen(4000);


// node --unhandled-rejections=strict test-request.js
'use strict';

const got = require('got');

async function run() {
    const response = await got.post('http://localhost:4000/502', {
        retry: 3
    });
    console.dir(response);
}

run();
```

**Comment by szmarczak** [comment]
Got doesn't retry on POST by default.

**Comment by peterdemartini** [comment]
I see, I need to set it in `retry.methods`
