### ISSUE TITLE
Document types of Object properties

### ISSUE THREAD

**Issue by Naramsim** [sindresorhus/got#1675]
#### What problem are you trying to solve?

Understanding better the docs

#### Describe the feature

Document the types of properties inside an `Object`.

Take the retry example. In the [docs](https://github.com/sindresorhus/got/blob/main/readme.md#retry) you state that an `Object` has to be passed. But you don't specify the types of the `statusCodes` property (which [should be a list](https://github.com/sindresorhus/got/blob/1120370e05fd8d9e768677d8474d0c82cf91a6a6/source/index.ts#L18)) and all the other properties.

...

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

---

Thanks for the amazing work.

**Comment by szmarczak** [comment]
Fixed:

- https://github.com/sindresorhus/got/blob/488001730f8094d1f569d6ca2d940a8915580dc8/documentation/7-retry.md
- https://github.com/sindresorhus/got/blob/488001730f8094d1f569d6ca2d940a8915580dc8/documentation/9-hooks.md
- https://github.com/sindresorhus/got/blob/488001730f8094d1f569d6ca2d940a8915580dc8/documentation/6-timeout.md
- https://github.com/sindresorhus/got/blob/488001730f8094d1f569d6ca2d940a8915580dc8/documentation/4-pagination.md
