### ISSUE TITLE
Add "number of dependencies" to the comparison table

### ISSUE THREAD

**Issue by dandv** [sindresorhus/got#1677]
#### What problem are you trying to solve?
Trying to choose the request library with the fewest dependencies. At a first glance, `got` has the smallest install size, but `axios` has only one dependency.

#### Describe the feature

Happy to submit a PR with an extra row in [the table](https://www.npmjs.com/package/got#comparison) if this idea is approved.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
I disapprove. The number of dependencies doesn't reflect reliability. You might go with the native `https` module, that way you wouldn't have to instally any package whatsoever!

**Comment by dandv** [comment]
@szmarczak: Why did you conclude that I was after reliability? Does the size of the installed code reflect reliability? Or TypeScript support? Both are in the table.

> You might go with the native https module, that way you wouldn't have to instally any package whatsoever!

If I wanted to go with the native module, I would not have looked at this comparison table.

Let's calm down please. I was merely suggesting another metric, for a specific use case - minimalistic modules that might want to depend on one of these request modules, and for which the number of dependencies is important, for whatever reason.

**Comment by szmarczak** [comment]
> Why did you conclude that I was after reliability?

Well, there is no point in using a package that is buggy (note: not implying anything by these words).

> Does the size of the installed code reflect reliability?

No, but it's a factor worth considering. The lighter dependencies, the faster it will take to load them. Also nobody likes heavy apps.

> Or TypeScript support?

Actually TypeScript makes packages more reliable as it enforces strict types. That way you can avoid lots of bugs. This is one of the main reasons we switched to TypeScript.

> I was merely suggesting another metric, for a specific use case - minimalistic modules that might want to depend on one of these request modules, and for which the number of dependencies is important, for whatever reason.

I'm highly interested in hearing what's the reasoning behind this.

You may have 20 dependencies and end up with 100KB total as well as 1 dependency and a few megabytes. It just makes no sense to me. What if Got bundled all the required dependencies? The code would be the same, the install size would be the same, just the number of dependencies would be zero.

You're still free to open a PR. I'm hold myself back from any action if you decide to do so :)
