### ISSUE TITLE
RequestError: connect ETIMEDOUT

### ISSUE THREAD

**Issue by atubo2012** [sindresorhus/got#1678]
#### Describe the bug

 - Node.js version: 14.16.0-win-x64
 - OS & version: windows 10 professional
  win32 <-platform
 x64 <-arch
 Windows_NT <-type
 [Function: getOSVersion] {
  [Symbol(Symbol.toPrimitive)]: [Function (anonymous)]
} <-version
 10.0.18363 <-release
 LE <-endianness

![image](https://user-images.githubusercontent.com/30145089/113803199-9ff95580-978e-11eb-8b1a-5c0211b79495.png)

#### Actual behavior
Got above error.

...

#### Expected behavior
Get content about blog ,like this:
![image](https://user-images.githubusercontent.com/30145089/113803400-0a11fa80-978f-11eb-836d-e3df7a616708.png)

...

#### Code to reproduce

```js
const got = require('got');

(async () => {
    try {
        const response = await got('https://www.googleapis.com/blogger/v3/blogs/4635670594938406451/posts/7881404100950905564?key=xxxxxxxx-xxxxx');
        console.log(response);
    } catch (error) {
        console.log('error occur :',error);
        //=> 'Internal server error ...'
    }
})();
```
But it works in gitpod, I am wondering if it was caused by vpn :(

#### Checklist

- [y] I have read the documentation.
- [y] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Got works correctly here.

**Comment by atubo2012** [comment]
Solved  after environment variable http_proxy is set : 
http_proxy=http://127.0.0.1:10001  
The port number could be found in "Internet option->connection->LAN setting->Proxy".
Thank you!
