### ISSUE TITLE
Got 403 while chrome can access the page correctly

### ISSUE THREAD

**Issue by tambdc-self** [sindresorhus/got#1679]
#### Describe the bug

 - Node.js version:  14.15.4
 - OS & version: win10

Code:

(async () => {
  console.log(await got.get("https://javdb.com/"));
})();

#### Actual behavior

get html of that page

#### Expected behavior

(node:21476) UnhandledPromiseRejectionWarning: HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (d:\Projects\avengine\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

#### Code to reproduce

(async () => {
  console.log(await got.get("https://javdb.com/"));
})();
```

- [X ] I have read the documentation.
- [X ] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Try setting the user-agent to the same as, for example, Chrome.

**Comment by tambdc-self** [comment]
Not working with user-agent set:

(async () => {
    console.log(await got.get("https://javdb.com/",
        {
            headers:
            {
                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36'
            }
        }
    ));
})();

output:
(node:1820) UnhandledPromiseRejectionWarning: HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (d:\Projects\avengine\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tambdc-self** [comment]
I did some debug and find out the header needs a line of 
Host: javdb.com

at beginning, Host with Capital H at beginning. got seems to change the order of header and lower all chars.

**Comment by szmarczak** [comment]
The HTTP spec says headers are case-insensitive, so there is nothing wrong with the current solution.
