### ISSUE TITLE
TS issue with got.stream

### ISSUE THREAD

**Issue by sinedied** [sindresorhus/got#1682]
#### Describe the bug

 - Node.js version: 14.15.4
 - OS & version: Mac OS 10.15.7

#### Actual behavior

When copying the stream code example from the README in a TypeScript project with strict mode enable, I get this error:
```
error TS2339: Property 'stream' does not exist on type 'typeof import("/Users/sinedied/projects/nubesgen-vscode/node_modules/got/dist/source/index")'.

103       got.stream('https://sindresorhus.com'),
```

...

#### Expected behavior

No errors :)

...

#### Code to reproduce

Set up a TypeScript project, enable strict mode and copy the code example from readme:

```ts
import stream = require('stream');
import util = require('util').promisify;
import fs = require('fs');
import got = require('got');

const pipeline = util.promisify(stream.pipeline);

(async () => {
	await pipeline(
		got.stream('https://sindresorhus.com'),
		fs.createWriteStream('index.html')
	);
})();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you create a repository? I'm not able to reproduce this.

**Comment by szmarczak** [comment]
Ah, I think you should use `import got from 'got'` instead.

**Comment by szmarczak** [comment]
```
import stream = require('stream');
import util = require('util');
import fs = require('fs');
import got from 'got';

const pipeline = util.promisify(stream.pipeline);

(async () => {
	await pipeline(
		got.stream('https://sindresorhus.com'),
		fs.createWriteStream('index.html')
	);
})();
```

**Comment by sinedied** [comment]
Thanks, works fine this way!
Most Node.js don't support native TS imports, so I didn't thought of using that. Great job on the lib BTW! 👍
