### ISSUE TITLE
Rewrite docs

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1684]
The `v11.8.2` docs are a bit outdated. Furthermore, there API changes in https://github.com/sindresorhus/got/pull/1667. The docs need an update.

#### To be fixed

- [x] #1675
- [x] #617
- [x] #1473
- [x] #1405
- [x] #1053
- [ ] ...

#### Need to mention

- [x] https://github.com/sindresorhus/got/issues/1610#issuecomment-817328410
- [x] https://github.com/sindresorhus/got/issues/1654#issuecomment-817333127

#### To be fixed first

- [ ]  #1591 & #1462
- [x] #1137
- [x] #1599
- [x] #1574 - needs a test
- [x] #1569

**Comment by szmarczak** [comment]
Note to myself: fix remaining stuff from #1667

**Comment by szmarczak** [comment]
Todo:

- update TypeScript docs
- Node.js migration guide
- Axios migration guide

**Comment by sindresorhus** [comment]
Semi-related to this. Do we have an overview of the breaking changes in v12?

**Comment by szmarczak** [comment]
Fully? Not yet. Some are mentioned in #1667. I'll write them today.
