### ISSUE TITLE
A lot of lines with "got (https://github.com/sindresorhus/got)" in apache log. 

### ISSUE THREAD

**Issue by AntoineR951** [sindresorhus/got#1686]
Hi,
I have in my apache log a lot of lines with "got (https://github.com/sindresorhus/got)" : 

81.49.82.xxx - - [13/Apr/2021:01:07:33 +0200] "GET /file.html HTTP/1.1" 200 7421 "-" "got (https://github.com/sindresorhus/got)"
90.92.118.xxx - - [13/Apr/2021:01:07:33 +0200] "GET /file.html HTTP/1.1" 200 7421 "-" "got (https://github.com/sindresorhus/got)"

With different IP address.

What are these lines? 

Is this another website crawling my website? 

Could I block them?

**Comment by sindresorhus** [comment]
Someone is just using this library.

**Comment by AntoineR951** [comment]
Thanks for your reply. 

I don't know your library. What can it be used for? I have more than 5000 requests per day on a site which displays schedules. Is it about content aspiration? 

Do any browsers use this library?

Block all requests that use it can it block real users?

**Comment by szmarczak** [comment]
You can figure out what this library is just by reading the readme.
