### ISSUE TITLE
retryWithMergedOptions doesn't work with FormData as body

### ISSUE THREAD

**Issue by jeanmatthieud** [sindresorhus/got#1691]
#### Describe the bug

 - Node.js version: 12 & 14
 - OS & version: Windows 10

I'm using the exemple `afterResponse` hook of the documentation for [retrieving a token and storing it](https://github.com/sindresorhus/got#hooksafterresponse).
Everything is working fine with a body as JSON.
But when I'm sending a FormData object, even if the `afterResponse` hook is called, the request isn't sent.

#### Actual behavior
The request isn't sent after a `retryWithMergedOptions` when the body is FormData.
I tried with and without a file, it doesn't seems to be the issue.

#### Expected behavior
The request should be sent after a `retryWithMergedOptions` when the body is FormData.

#### Code to reproduce
```js
const odrFetcher = got.extend({
  prefixUrl: "https://123soleil.com/api/v2",
  hooks: {
    afterResponse: [
      async (response, retryWithMergedOptions) => {
        if (response.statusCode === 401) { // Unauthorized
          const updatedOptions = {
            headers: {
              // Refresh the access token
              Authorization: `Bearer ${await getNewToken()}`,
            }
          };

          // Save for further requests
          odrFetcher.defaults.options = got.mergeOptions(odrFetcher.defaults.options, updatedOptions);

          // Make a new retry
          return retryWithMergedOptions(updatedOptions);
        }

        // No changes otherwise
        return response;
      }
    ],
    beforeRetry: [
      (options, error, retryCount) => {
        // This will be called on `retryWithMergedOptions(...)`
      }
    ]
  },
  mutableDefaults: true
});

var form = new FormData();
form.append('uploadFile[file]', fs.createReadStream("./my-file.png"));
form.append('validityDate', '2021-06-18');

const result = await odrFetcher.post(`document`, {
  body: form,
  headers: form.getHeaders(),
}).json();
```
#### Checklist

- [X ] I have read the documentation.
- [ X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Indeed this is a bug. It may be already fixed in the upcoming Got 12. Will check tomorrow.

**Comment by szmarczak** [comment]
Fixed in 62305d77d3428b5c714d21b4bbee68cc75b5f787

**Comment by sunknudsen** [comment]
Trying to figure out how to adapt following code for version 12 (if need be).

Can one drop using `genForm` workaround in version 12? This issue appears to indicate that Got would throw an error rather than try again.

```typescript
const genForm = async () => {
  const form = new formData()
  form.append("foo", "bar")
  return form
}
const form = await genForm()
await got.put("some/api/path", {
  headers: form.getHeaders(),
  body: form,
  hooks: {
    beforeRetry: [
      async (error) => {
        const form = await genForm()
        error.options.body = form
        error.options.headers[
          "content-type"
        ] = `multipart/form-data; boundary=${form.getBoundary()}`
      },
    ],
  },
})
```

**Comment by sunknudsen** [comment]
Thanks for helping out @szmarczak!

**Comment by jeanmatthieud** [comment]
So, a "retry" cannot be attempted for a form ? (the merge seems only throw a new error, but not fix the issue).
How can we avoid that ? I would like to avoid managing the auth tokens outside got...

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/3-streams.md#createretrystream
