### ISSUE TITLE
options.username and options.password are not working

### ISSUE THREAD

**Issue by samkrait** [sindresorhus/got#1692]
I am trying to use Basic Auth and passing credentials as options.username and options.password but it does not populate the options.auth and I get unAuthorized error.

    const options = {
      headers: {
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
    
      },
        username: APP_CLIENT_ID,
        password: encodeURI(APP_CLIENT_SECRET),
        body:  'grant_type=credentials'
        
      
    }
	
	await got.post(url,options)
	

<img width="533" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/43655122/115127201-4c8ad100-9ff2-11eb-9f78-51d20eed99c2.png">

**Comment by samkrait** [comment]
I also cant pass the grant type using options.form,  form: {
          grant_type: 'client_credentials'
        }
and thats why I am passing it in body. I am migrating from request here, and its the same way I used to perform there. I went through documentation and it looks this is a valid syntax.

**Comment by szmarczak** [comment]
We don't support Got 9 anymore.

**Comment by szmarczak** [comment]
If you're using Got 11, please create a reproducible example.

**Comment by samkrait** [comment]
Thanks, Upgrading the version fix the issue.
