### ISSUE TITLE
Json body is not being sent

### ISSUE THREAD

**Issue by zoran-petrovic-87** [sindresorhus/got#1693]
#### Describe the bug

 - Node.js version: 14.15.0
 - OS & version: Windows 10 Pro

When sending JSON body, Content-Type header is not set and body is not included in request at all. I can get correct result using Postman or cURL.

#### Actual behavior

POST /projects/req/index.php HTTP/1.1
user-agent: got/9.6.0 (https://github.com/sindresorhus/got)
accept: application/json
accept-encoding: gzip, deflate
Host: localhost
Connection: close
Content-Length: 0

#### Expected behavior

POST /projects/req/index.php HTTP/1.1
**Content-Type: application/json**
user-agent: got/9.6.0 (https://github.com/sindresorhus/got)
accept: application/json
accept-encoding: gzip, deflate
Host: localhost
Connection: close
**Content-Length: 17**

**{"hello":"world"}**

#### Code to reproduce

(example from documentation)
```js
    await got.post('http://localhost/projects/req/index.php', {
      json: {
        hello: 'world'
      },
      responseType: 'json'
    })
```

#### Checklist

- [ x] I have read the documentation.
- [ x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Use Got 11. We don't support Got 9.
