### ISSUE TITLE
retry status 302 does not retry requests

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#1694]
#### Describe the bug

 - Node.js version: v15
 - OS & version: macOS Big Sur

#### Actual behavior

got makes request only once.

In the case of provided code example, "OK" is printed only once.

#### Expected behavior

got should make request 10 times.

#### Code to reproduce

```js
const response = await got('http://127.0.0.1:3001/test', {
  followRedirect: false,
  retry: {
    limit: 10,
    statusCodes: [
      302,
    ],
  },
});

```

You will also need a simple HTTP route, e.g.

```js
router.use('/test', (incomingMessage, serverResponse) => {
  console.log('OK');

  serverResponse.status(302).end('');
});

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by mindnuts** [comment]
@gajus As suggested by the documentation you need to set something like this explicitly:

```
retry: {
    limit: 5,
    methods: ["POST"]
}
```

**Comment by gajus** [comment]
@mindnuts I don't understand what you are implying. As shown in my code example, I did set which status code should be retried.

**Comment by mindnuts** [comment]
> @mindnuts I don't understand what you are implying. As shown in my code example, I did set which status code should be retried.
My bad, i thought you were making a "POST" request, and they are not retried by default.

**Comment by gajus** [comment]
Is this now a confirmed bug?

**Comment by szmarczak** [comment]
```cpp
RFC 7231             HTTP/1.1 Semantics and Content            June 2014

6.4.3.  302 Found

   The 302 (Found) status code indicates that the target resource
   resides temporarily under a different URI.  Since the redirection
   might be altered on occasion, the client ought to continue to use the
   effective request URI for future requests.

   The server SHOULD generate a Location header field in the response
   containing a URI reference for the different URI.  The user agent MAY
   use the Location field value for automatic redirection.  The server's
   response payload usually contains a short hypertext note with a
   hyperlink to the different URI(s).

      Note: For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.
```

**Comment by szmarczak** [comment]
Hmm I think it should retry. Lemme see

**Comment by szmarczak** [comment]
Actually this is not a bug. `302` is not an error code in this case, since you explicitly set the `followRedirects` option to `false`. Therefore the request is considered successful. In order to retry, you can use the `afterResponse` hook.

**Comment by szmarczak** [comment]
@sindresorhus I'm wondering if we should change this behavior. Or we can just document that successful status codes are ignored and `afterResponse` can be used instead.

**Comment by szmarczak** [comment]
I'm afraid that if we changed this behavior then it could be misused. It's possible to emit `HTTPError` inside an `afterResponse` hook.

**Comment by szmarczak** [comment]
(sorry, attached wrong issue, reopened)

**Comment by sindresorhus** [comment]
> I'm afraid that if we changed this behavior then it could be misused.

I'm concerned about this too. I think we should just clearly document the behavior.
