### ISSUE TITLE
Missing Accept-Encoding causes Z_DATA_ERROR error

### ISSUE THREAD

**Issue by tot-ra** [sindresorhus/got#1695]
#### Describe the bug
 - Node.js version: 14
 - OS & version: MacOS Catalina + Docker 3

#### Actual behavior
We've encountered an error
`{"message":"incorrect header check","code":"Z_DATA_ERROR"}`
 
 ```
Error: incorrect header check
at Zlib.zlibOnError [as onerror] (zlib.js:181:17) {
errno: -3,
code: 'Z_DATA_ERROR'
}
```

That seems to come from the server, because it fails to support / understand these `gzip, deflate, br` encodings which [got tries to use](https://github.com/sindresorhus/got/blob/1a983f31cf221d7496c54026bb936f81ff72b565/source/core/index.ts#L1012)

<img width="1027" alt="Screenshot 2021-04-23 at 12 21 36" src="https://user-images.githubusercontent.com/445122/115850536-a0e8e300-a42e-11eb-8dd9-59036c173257.png">

Why doesn't got use `identity` or `*` [by default](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) instead for uncompressed traffic?

**Comment by szmarczak** [comment]
I cannot confirm this without any code to reproduce this.

**Comment by szmarczak** [comment]
https://tools.ietf.org/html/rfc7231#section-5.3.4


```
   A request without an Accept-Encoding header field implies that the
   user agent has no preferences regarding content-codings.
```

**Comment by Darebear21** [comment]
I encountered the same error, but I fixed it by removing "deflate" from the accept-encoding header
