### ISSUE TITLE
Site hangs got

### ISSUE THREAD

**Issue by vladtreny** [sindresorhus/got#1696]
#### Describe the bug

 - Node.js version:  15
 - OS & version:  Ubuntu 20 / Windows

Just run this code and you will never get a response. Timeout doesn't help.
```
const response = await got("http://www.1a2f.com");
console.log(response.body);
```
If you enable handler, you will see
```
{ percent: 0, transferred: 0, total: undefined }
{ percent: 1, transferred: 0, total: 0 }
{ percent: 0, transferred: 0, total: 1927 }
{ percent: 1, transferred: 4605, total: 4605 }
```

#### Actual behavior
stucks at `const response = await got("http://www.1a2f.com");`
P.S. Timeout doesn't help.
...

#### Expected behavior
get `console.log(response.body);`
...

#### Code to reproduce

```js
const response = await got("http://www.1a2f.com");
console.log(response.body);
```
 
#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Try setting a user-agent header.

https://github.com/sindresorhus/got#user-agent

**Comment by vladtreny** [comment]
> Try setting a user-agent header.
> 
> https://github.com/sindresorhus/got#user-agent

Hello, it doesn't help. It is just a buggy site I encountered (one per 500k).
It returns 503 error and hangs got somewhere.

**Comment by szmarczak** [comment]
Indeed this is a bug. I need to check if this is fixed in Got 12.

**Comment by vladtreny** [comment]
> Indeed this is a bug. I need to check if this is fixed in Got 12.

Another example `http://aadeshjain.com/`

It returns 503 error the same way.

It took me a lot of time to find out what is wrong in my setup, hope will help other people :)

**Comment by szmarczak** [comment]
It doesn't hang. The `retry-after` header is set to `86400`, which is 1 day. So Got is going to make a new retry after 1 day. You need to set a `timeout` in order to prevent this.
