### ISSUE TITLE
Cannot be run on Node v14.10.0?

### ISSUE THREAD

**Issue by pzhyy** [sindresorhus/got#1697]
#### What would you like to discuss?

This example cannot be run on Node v14.10.0? nothing is output to the screen. 

```js
const got = require('got')

(async () => {
  try {
    const response = await got('https://sindresorhus.com')
    console.log(response.body)
    //=> '<!doctype html> ...'
  } catch (error) {
    console.log(error.response.body)
    //=> 'Internal server error ...'
  }
})()
```

Then I switched to Node v14.8.0, it was ok.

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
Try 14.16.

**Comment by pzhyy** [comment]
> Try 14.16.

Node v14.16.1 is no problem! It seems I can only upgrade the version of Node first.
