### ISSUE TITLE
Issue with Http2 Integration Understanding

### ISSUE THREAD

**Issue by prabhatmishra33** [sindresorhus/got#1707]
#### What would you like to discuss?

I was to discuss about the http2 implementation with GOT. Below changes i have done as to implement http2 for GOT.
- Upgraded Node to v15.10.0
- added `http2: true` into my options. you can see below
`		let options = {
			retry: httpClient.getRetryConfig(url),
			timeout: 5000,
			responseType: 'json',
			agent: httpClient.getHttpAgent(),
			maxContentLength: Infinity,
			http2: true
		};
`
- Added http2 in the agent
`
          const HttpAgent = require('agentkeepalive');
          const { HttpsAgent } = HttpAgent;
          const Http2Wrapper = require('http2-wrapper');
        
        http: new HttpAgent(),
        https: new HttpsAgent(),
        http2: new Http2Wrapper.Agent()
`
Please let me know if some more changes needed to be integrated 
...

#### Checklist
node v15.10.0
"got": "^11.8.2"
"http2-wrapper": "^1.0.3"
"agentkeepalive": "^4.1.4"

- [x] I have read the documentation.
https://www.npmjs.com/package/got#http2

**Comment by sindresorhus** [comment]
What issue are you seeing?
