### ISSUE TITLE
Set error codes on all errors

### ISSUE THREAD

**Issue by p-bakker** [sindresorhus/got#1711]
#### What would you like to discuss?
On HTTPErrors the statusCode of the response is not exposed directly. You have to go through the HTTPError.response to get the statusCode

I would've expected the statusCode to be directly exposed on the HTTPError or otherwise set as the value of the `code` property, but neither is true

Is that as expected or is this a bug?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
In regards to the documentation this is expected.

**Comment by p-bakker** [comment]
Tnx for the quick response.

I wasn't able to deduct this from the documentation, so thanks for clarifying

**Comment by p-bakker** [comment]
Additionally: shouldn't the code property on HTTPError instances be set to 'HTTPError'? According to the docs: `Contains a code property with error class code, like ECONNREFUSED`

**Comment by Drewfergusson** [comment]
Per @sindresorhus comments in #1739 it would be good to take a comprehensive approach to the code property for all error objects. The plain RequestError seems to always have a code associated with it that correlates to a Linux kind of error 

`[
			'ETIMEDOUT',
			'ECONNRESET',
			'EADDRINUSE',
			'ECONNREFUSED',
			'EPIPE',
			'ENOTFOUND',
			'ENETUNREACH',
			'EAI_AGAIN'
]` 

The other child error messages all seem to return with the code property as undefined. As also stated it would be good to follow a Node.JS convention of ERR_*. 

I might suggest

- CacheError `ERR_CACHE_ACCESS`
- ReadError `ERR_READING_RESPONSE_STREAM`
- ParseError `ERR_BODY_PARSE_FAILURE`
- UploadError `ERR_READING_REQUEST_STREAM`
- HTTPError `ERR_NON_2XX_3XX_RESPONSE`
- MaxRedirectsError `ERR_MAX_REDIRECTS`
- UnsupportedProtocolError `ERR_UNSUPPORTED_PROTOCOL`
- TimeoutError `ERR_TIMEOUT`
- CancelError `ERR_CANCEL_INVOKED`

**Comment by sindresorhus** [comment]
> CancelError ERR_CANCEL_INVOKED

`ERR_CANCELED`

**Comment by sindresorhus** [comment]
Otherwise, looks good to me.

@szmarczak ?

**Comment by szmarczak** [comment]
`ERR_READING_REQUEST_STREAM` -> `ERR_UPLOAD`
