### ISSUE TITLE
Issue while sending request to https url from non-https node application

### ISSUE THREAD

**Issue by abhishek2244** [sindresorhus/got#1725]
#### Describe the bug

 - Node.js version: v10.20.1
 - OS & version: CentOS Linux 7

#### Actual behavior
We have a reverse proxy Nginx server that is handling the SSL and behind that, a node application running on 3006 port. When we perform any request to an internal network IP or any external URL without HTTPS then everything works fine.
Until we try to perform a request to an external URL with HTTPS enabled.  
For example, http://example.com would give us a valid response, but https://example.com would give our own server's home page which we serve on our main route like http://127.0.0.1:3006/.

When we checked the response.ip key from the response that too was showing 127.0.0.1 and the response.url and response.requestUrl both were the external https URL.

#### Expected behavior
The request should go through and provide a valid response.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
> The request should go through and provide a valid response.

What happens instead?

**Comment by abhishek2244** [comment]
It gives 200 status code and in response the same express server's home page template
Also in the response object, the value of IP key is 127.0.0.1. 

The request has never gone to the external URL.

**Comment by szmarczak** [comment]
Can you try Node.js 14? Node.js 10 is not supported anymore

**Comment by szmarczak** [comment]
Also what's the result of `dns.lookup('example.com', console.log)`?

**Comment by szmarczak** [comment]
Are you using HTTP agents?

**Comment by abhishek2244** [comment]
Tried with node v14.16.0 same result.
here is the output of dns.lookup statement
`null '93.184.216.34' 4`

Also I am not using any HTTP agent

**Comment by abhishek2244** [comment]
The issue arises only with the https URLs

**Comment by szmarczak** [comment]
There must be an issue with your dependencies. Got doesn't do any custom DNS handling / overrides, so it should be `93.184.216.34` instead of `127.0.0.1`.

If you can reproduce the issue in a repo, that would be great.

**Comment by abhishek2244** [comment]
It cannot be replicated in repo as this is a production setup where Nginx is configured as a reverse proxy for SSL handling and proxy node server is being configured on 3006 port.

If you could guide me through why this is happening i could look into it myself. Also, I have gone through the documentation and found out about proxies. How do these work and when do we require these?

**Comment by szmarczak** [comment]
> why this is happening

To be honest I have no idea why this is happening. I'm pretty sure that Got handles this correctly here, as we use `https.request(...)` directly. You can try this:

```js
const https = require('https');

const request = https.get('https://example.com', response => {
	const chunks = [];

	response.on('data', chunk => {
		chunks.push(chunk);
	});

	response.once('end', () => {
		console.log(Buffer.concat(chunks).toString());
	});
});
```

> I have gone through the documentation and found out about proxies. How do these work and when do we require these?

Long story short when you want to redirect outcoming traffic through another proxy server. If you want to learn more about proxies, Got isn't the right place. We just provide integration.

> It cannot be replicated in repo as this is a production setup

In that case there's nothing we can do, sorry.

**Comment by abhishek2244** [comment]
I have tested the post request to https://example.com from got as well as https.request and both have different results.
Please see below:

**1. GOT module**

```
const got = require('got');

const resp = got.post('https://example.com', {
  body: 'testing',
});

resp.then((result) => {
  console.log(result);
}, (err) => {
  console.log(err.response.body);
  console.log(err.response.statusCode);
});
```

Response: 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:you@example.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Object not found!</h1>
<p>


    The requested URL was not found on this server.

  

    If you entered the URL manually please check your
    spelling and try again.

  

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:you@example.com">webmaster</a>.

</p>

<h2>Error 404</h2>
<address>
  <a href="/">localhost</a><br />
  <span>Apache/2.4.46 (Unix) OpenSSL/1.1.1k PHP/5.6.40</span>
</address>
</body>
</html>
```

The above response is the default home page of apache of my local machine. The request never went to example.com.


**2. HTTPS module**

```
const https = require('https');

const postData = 'testing';

const options = {
  hostname: 'example.com',
  port: 443,
  method: 'POST',
  headers: {
    'Content-Type': 'text/plain',
    'Content-Length': postData.length,
  },
};

const req = https.request(options, (res) => {
  console.log('statusCode:', res.statusCode);
  console.log('headers:', res.headers);

  res.on('data', (d) => {
    process.stdout.write(d);
  });
});

req.on('error', (e) => {
  console.error(e);
});

req.write(postData);
req.end();
```

Response: 
```
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
        
    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>    
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

The above response is a valid response and the same should be received with got as well.


**NOTE: The above code samples are run on an express server running on any local port like 3000. If you run the above code as a node script like `node script.js` then both of them should  work fine**

**Comment by szmarczak** [comment]
That's odd. Can you try the below? Please don't modify anything.

```js
const https = require('https');

console.log(https.request.toString());

const request = https.get(new URL('https://example.com'), {
	method: 'GET',
	headers: {
		'user-agent': 'got (https://github.com/sindresorhus/got)'
	}
});

request.on('response', response => {
	const chunks = [];

	response.on('data', chunk => {
		chunks.push(chunk);
	});

	response.once('end', () => {
		console.log(Buffer.concat(chunks).toString());
	});
});
```

**Comment by abhishek2244** [comment]
```
function request(...args) {
  let options = {};

  if (typeof args[0] === 'string') {
    const urlStr = args.shift();
    try {
      options = urlToOptions(new URL(urlStr));
    } catch (err) {
      options = url.parse(urlStr);
      if (!options.hostname) {
        throw err;
      }
      if (!urlWarningEmitted && !process.noDeprecation) {
        urlWarningEmitted = true;
        process.emitWarning(
          `The provided URL ${urlStr} is not a valid URL, and is supported ` +
          'in the https module solely for compatibility.',
          'DeprecationWarning', 'DEP0109');
      }
    }
  } else if (args[0] && args[0][searchParamsSymbol] &&
             args[0][searchParamsSymbol][searchParamsSymbol]) {
    // url.URL instance
    options = urlToOptions(args.shift());
  }

  if (args[0] && typeof args[0] !== 'function') {
    ObjectAssign(options, args.shift());
  }

  options._defaultAgent = module.exports.globalAgent;
  args.unshift(options);

  return new ClientRequest(...args);
}
```

```
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
        
    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>    
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

**Comment by szmarczak** [comment]
So it looks like the native `https` module is not being overriden in any way, which is a good sign. Can you try the below? This will log the `url` and `options` being passed to Node.js by Got directly.

```js
const https = require('https');
const got = require('got');

(async () => {
    await got('https://example.com', {
        request: (url, options, callback) => {
            console.log(url.href, options);
            return https.request(url, options, callback);
        },
        throwHttpErrors: false
    });
})();
```

**Comment by abhishek2244** [comment]
Here is the response from the above code:

```
https://example.com/ {
  method: 'GET',
  retry: {
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429, 500,
      502, 503, 504, 521,
      522, 524
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity,
    calculateDelay: [Function: calculateDelay]
  },
  headers: {
    'user-agent': 'got (https://github.com/sindresorhus/got)',
    'accept-encoding': 'gzip, deflate, br'
  },
  hooks: {
    init: [],
    beforeRequest: [],
    beforeRedirect: [],
    beforeRetry: [],
    beforeError: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: false,
  followRedirect: true,
  isStream: false,
  responseType: 'text',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: [Getter/Setter],
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: false,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  url: URL {
    href: 'https://example.com/',
    origin: 'https://example.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'example.com',
    hostname: 'example.com',
    port: '',
    pathname: '/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  username: '',
  password: '',
  shared: undefined,
  cacheHeuristic: undefined,
  immutableMinTimeToLive: undefined,
  ignoreCargoCult: undefined,
  [Symbol(isNormalizedAlready)]: true,
  [Symbol(request)]: [Function: request]
}

```

**Comment by szmarczak** [comment]
Yeah, so Got does everything correctly here. I [have modified](https://github.com/sindresorhus/got/issues/1725#issuecomment-849082625) the code a bit. Let me know if you see an `example.com` page or your webpage.

**Comment by szmarczak** [comment]
If you see your webpage, try replacing

```js
        lookup: dns.lookup,
```

with

```js
        lookup: dns.lookup,
		agent: {https: false},
```

**Comment by abhishek2244** [comment]
Same issue with both the options. I am seeing my homepage.

**Comment by szmarczak** [comment]
> If you run the above code as a node script like node script.js then both of them should work fine

This indicates that the issue is in the deps you're running. By looking at the logs I can say that Got does everything correctly here.

> Same issue with both the options.

Without any reproducible code we cannot do much. The last option you can try is to use another HTTP client like `node-fetch`.

Ah, and one more thing. Try this:

```js
const https = require('https');
const httpsAgent = new https.Agent();
...
    agent: {https: httpsAgent},
```

**Comment by vadimdemedes** [comment]
I just stumbled upon the same issue as @abhishek2244 and I'm totally confused what would cause this. I've tried everything in this thread and it didn't help me either. The surprising thing is it works with `node-fetch`, but not with `got`.

**Comment by abhishek2244** [comment]
Hi @vadimdemedes @szmarczak ,

Somehow I dug deep and found out that there was a module **googleapis** with the version(v34) installed on my application that was causing this issue. Updated the module and it is working now.
The googleapis module somehow had a conflict with got module.

**Comment by szmarczak** [comment]
@abhishek2244 would you mind creating a simple repro? We could make a detector in Got that would throw if there's an incompatible configuration.

**Comment by abhishek2244** [comment]
@szmarczak I have recreated the issue. 
Please check this repo: https://github.com/abhishek2244/https-got-issue

**Comment by mhemrg** [comment]
@abhishek2244 It's because of the `agent-base` package in your `package-lock.json`.
You need to upgrade to `agent-base@6` to fix this issue. If you're not dependent on this package directly, find which one of your dependencies is dependent on `agent-base` and then upgrade it.

**Comment by nikosolihin** [comment]
@abhishek2244 Did you find out what the conflict was with googleapis? 

I'm having the same got issue you described when googleapis@85.0.0 is installed alongside got.
