### ISSUE TITLE
Multipart/form-data

### ISSUE THREAD

**Issue by dsblv** [sindresorhus/got#173]
I think it'd be magical if got could generate `multipart/form-data` body from an object if `options.headers['content-type']` is set to `multipart/form-data`.

Or is it out of scope?

**Comment by floatdrop** [comment]
> Or is it out of scope?

I think so. You can use [Form data](https://github.com/sindresorhus/got#form-data) snippet – it is quite simple to use `form-data` with `got`.

**Comment by dsblv** [comment]
@floatdrop thanks.

It was a good idea to [add an example to readme](https://github.com/sindresorhus/got/commit/88c9f6b8b05eda50c37dcfc5dcfeb1947059d026). :+1: Too bad it wasn't there when I visited last time.

Closing.
