### ISSUE TITLE
A new TypeScript update is breaking the build

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1740]
https://github.com/sindresorhus/got/runs/2723006761

**Comment by sindresorhus** [comment]
Yeah, we have to remember to not use `^` for the TypeScript version. I keep forgetting.

**Comment by szmarczak** [comment]
It might be so that the `@types` got updated and some inconsistencies appeared. Will check this today.

**Comment by szmarczak** [comment]
Fixed: a06e7585ab4503e1dd7178d83dd4443ff6dda6c1
