### ISSUE TITLE
Type error with both http2 and cache enabled

### ISSUE THREAD

**Issue by paulknebel** [sindresorhus/got#1743]
#### Describe the bug

Node: v16.1.0
OS & version: CentOS Linux 7 (Core)
got: 11.8.2

When using both "cache: new Map()" and "http2: true", got will successfully store the request in the cache map, but throws an error when rebuilding the request from the cache.

In the provided example, I was able to avoid the error by using either the cache, or http2, but not both.

#### Actual behavior

The following error is thrown when retrieving a response from the cache (URL is an object)

```
RequestError: Argument `url` should be a string
    at Request._makeRequest (/var/www/node_modules/got/dist/source/core/index.js:1175:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /var/www/node_modules/got/dist/source/core/index.js:328:17
    at /var/www/node_modules/cacheable-request/src/index.js:200:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  name: 'CacheError',
  code: undefined,
  timings: undefined
}
```

#### Expected behavior

Response is successfully rebuilt from the cache

#### Code to reproduce

I am unable to share the actual URL used, but it does support http2, and provide shared cache headers. Sorry, I don't know where to find a URL with those traits.

```js
got.get('pet/findByStatus', {
    prefixUrl: 'https://petstore.swagger.io/v2',
    timeout: 400,
    responseType: 'text',
    searchParams: { status: 'available' },
    retry: 0,
    cache: this.cache, // new Map()
    http2: true,
    headers: {
        'x-trace-id': 'foo',
        'user-agent': 'foo-bar/baz, bash'
    }
});
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Fixed in `main` branch (upcoming Got v12). Although I found new issues when cache is enabled.

**Comment by szmarczak** [comment]
See #1786

**Comment by kevinlul** [comment]
This was not backported to v11, was it?

**Comment by szmarczak** [comment]
No.
