### ISSUE TITLE
Upgrade cacheable-request

### ISSUE THREAD

**Issue by Shinigami92** [sindresorhus/got#1749]
Upgrade `cacheable-request` when https://github.com/lukechilds/cacheable-request/pull/104 is merged and released

https://github.com/sindresorhus/got/blob/06a2d3d7d8d4fcc6898b6364d1a18ca1d407092b/package.json#L52

**Comment by Shinigami92** [comment]
@sindresorhus
/cc @szmarczak 

Could you let us know here when the next version was released? So we get notified via email and notifications 🙂 
THX in advance

**Comment by szmarczak** [comment]
please subscribe to https://github.com/sindresorhus/got/issues/1466

**Comment by Shinigami92** [comment]
But is there an ETA when the CVE will be fixed? / When will be the release?
So the eco-system like `vue-resource` can start to update.
Maybe it's also possible to just release a minor version instead of a new major v12

**Comment by szmarczak** [comment]
> Maybe it's also possible to just release a minor version instead of a new major v12

It's been fixed in `normalize-url@4.5.1` and `cacheable-request` uses ^4 so `npm install` should update it.

**Comment by Shinigami92** [comment]
Thx, I tried it myself and they only need to bump got up to at least v9, then it's fixed :tada: 
https://github.com/pagekit/vue-resource/issues/756#issuecomment-858755537
