### ISSUE TITLE
How to overwrite cache on request basis?

### ISSUE THREAD

**Issue by StarpTech** [sindresorhus/got#1752]
#### What would you like to discuss?

Hi,
some services don't implement RFC 7234 compliant HTTP caching. Is it possible to enforce caching with a fixed TTL value? Is it possible to configure the https://github.com/lukechilds/cacheable-request#optsmaxttl in got?

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
Currently not yet. Closing in favor of #875
