### ISSUE TITLE
Invalid options break handler execution in Got 12 (`main` branch)

### ISSUE THREAD

**Issue by mnmkng** [sindresorhus/got#1753]
#### Describe the bug

 - Node.js version: 14, 15, 16
 - OS & version: MacOS 11.2.3

#### Actual behavior
> This applies to the version of `got` that's in the `main` branch. We're trying to migrate to it because we need `http2-wrapper@2` for our use case.

When you pass an invalid option to `got`, the options do not get merged correctly or something else happens and the handlers are invoked without actually having access to the provided options. It's most likely caused by the newly added strict validation of options.

If you run the code example below, you'll see that `console.log(options.foo)` prints `undefined` and the `No URL` error will be thrown.

#### Expected behavior
I would expect an `Unexpected option: foo` error to be thrown. Not the handlers to be called with missing options. If I remove the handlers, the code behaves as expected. It also works fine in Got 11, albeit without the `Unexpected option` error.

#### Code to reproduce

```js
import got from 'got';

const got2 = got.extend({
    handlers: [
        (options, next) => {
            console.log(options.foo)
            if (!options.url) throw Error('No URL');
            return next(options);
        }
    ]
})
const response = await got2({
    url: 'https://example.com',
    foo: 'bar',
})
console.dir(response);

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by mnmkng** [comment]
It also seems that the `Unexpected option: foo` error comes "later" as an unhandled rejection:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
The promise rejected with the reason "RequestError: Unexpected option: foo".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by szmarczak** [comment]
I wasn't able to reproduce the unhandled promise rejection, but I managed to set `options.url` if possible.

**Comment by szmarczak** [comment]
> Not the handlers to be called with missing options.

But then Got would not know where to throw the error at. Is it a Promise? Is it a Stream?

**Comment by szmarczak** [comment]
If you can reproduce the unhandled promise rejection, please open another issue and I'll fix it.

**Comment by mnmkng** [comment]
I tried to reproduce the unhandled rejection again and was not able to. I guess your latest changes must have fixed it.
