### ISSUE TITLE
Not usable in atom

### ISSUE THREAD

**Issue by artoale** [sindresorhus/got#176]
I'm developing an Atom plugin that sends requests through GOT. 
First of all, to import the module I have to do 
```javascript
import { allowUnsafeEval } from 'loophole';

allowUnsafeEval( () => {
  got = require('got');
});
```

Since GOT uses (indirectly) `eval`, which breaks ATOM csp policy. 
Now, if the request is successful, got works fine, but when a network error occurs (e.g. 404) I get:

```
At evalmachine.<anonymous>:1

ReferenceError: captureStackTrace is not defined
    at new HTTPError (evalmachine.<anonymous>:1:25)
    at /Users/aartoni/dev/atom-codebase/node_modules/got/index.js:105:11
    at BufferStream.<anonymous> (/Users/aartoni/dev/atom-codebase/node_modules/read-all-stream/index.js:64:3)
    at emitNone (events.js:72:20)
    at BufferStream.emit (events.js:166:7)
    at finishMaybe (/Users/aartoni/dev/atom-codebase/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at afterWrite (/Users/aartoni/dev/atom-codebase/node_modules/readable-stream/lib/_stream_writable.js:390:3)
    at doNTCallbackMany (node.js:463:18)
    at process._tickCallback (node.js:361:17)
```

I believe it all boils down to custom Errors issue in the hybrid electron environment, and I'd understand if you think it's not worth fixing, but maybe there are other viable solutions not using eval?

**Comment by floatdrop** [comment]
`eval` is used in [`create-error-class`](https://github.com/floatdrop/create-error-class/blob/master/index.js#L30) to provide name to constructor. May be it can be achieved in other way or removed there. Can you reopen issue there?

**Comment by julien-f** [comment]
@floatdrop This has been fixed in [make-error](https://github.com/julien-f/js-make-error), perhaps you should consider using it…

**Comment by floatdrop** [comment]
@artoale fixed in `create-error-class@3.0.1`.

@julien-f I don't remember, why I ignored this module :blush: Can you do a PR?

**Comment by julien-f** [comment]
Perhaps because it's not easy to find good modules on npm :p
Or perhaps I did not use the right keywords :)

Anyway, if you prefer make-error over create-error-class I believe you should deprecate latter in favor of the first.

**Comment by artoale** [comment]
@floatdrop thanks for the super quick fix. Working perfectly now!
