### ISSUE TITLE
Async handlers do not get fully executed before a request is sent in Got 12 (`main` branch)

### ISSUE THREAD

**Issue by mnmkng** [sindresorhus/got#1760]
#### Describe the bug

 - Node.js version: 15, 16
 - OS & version: MacOS 11

#### Actual behavior
Got 12 (`main` branch code) does not wait for async handlers to fully execute. A race condition is created between the dispatch of the request and the async handler and any following handlers. This code works fine in Got 11.

#### Expected behavior
All handlers, async or not, are fully executed before Got starts to send the request.

#### Code to reproduce
The code illustrates the issue, but not completely. I recommend using [a request bin](https://requestbin.com) to inspect the actually sent headers. The console logs in the handlers will all fire, but that does not mean everything is fine, because the request will be sent before the next headers can be added. The `beforeRequest` illustrates the problem, because when we add it after the async call, the request is already sent and therefore the `beforeRequest` will not fire - no message will be logged.

```js
import got from 'got';

const got2 = got.extend({
    mutableDefaults: true,
    handlers: [
        (options, next) => {
            console.log('first handler');
            options.headers.first = 'first';
            return next(options);
        },
        async (options, next) => {
            console.log('second handler before await');
            options.headers.secondBefore = 'before';
            await new Promise(resolve => setTimeout(resolve, 1000)); // comment this out to get correct behavior
            console.log('second handler after await')
            options.headers.secondAfter = 'after';
            options.hooks.beforeRequest = [
                (options) => console.log('before request') // this will not get printed unless you comment the above
            ]
            return next(options);
        },
        (options, next) => {
            console.log('third handler');
            options.headers.third = 'third';
            return next(options);
        },
    ]
})

await got2({
    // this is just some request bin URL, if you create a bin yourself you'll find
    // that only the first two headers are sent, unless you comment the Promise
    url: 'https://en2dabgv3k6oo.x.pipedream.net/',
})

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by mnmkng** [comment]
Headers with the reproduction code:

```
Host: en2dabgv3k6oo.x.pipedream.net
X-Amzn-Trace-Id: Root=1-60cbb0b7-2b3bc6514a3b60410f4a5e13
user-agent: got (https://github.com/sindresorhus/got)
first: first
secondBefore: before
accept-encoding: gzip, deflate, br
```

Headers with the Promise wait commented:

```
Host: en2dabgv3k6oo.x.pipedream.net
X-Amzn-Trace-Id: Root=1-60cbb0bf-61db75647d34850d20ccb4fc
user-agent: got (https://github.com/sindresorhus/got)
first: first
secondBefore: before
secondAfter: after
third: third
accept-encoding: gzip, deflate, br
```

**Comment by szmarczak** [comment]
Found the culprit. The request is being wrongly flushed here:

https://github.com/sindresorhus/got/blob/f27e8d331627074e76e4a9ec85a2c8d0a0625e5f/source/as-promise/index.ts#L167

Fixing it right now.

**Comment by szmarczak** [comment]
Actually it needs to be flushed here but only when retrying.
