### ISSUE TITLE
Context merging in hooks

### ISSUE THREAD

**Issue by antoniomuso** [sindresorhus/got#1761]
#### Describe the bug

 - Node.js version: 14.15.1 and 14.17.0
 - OS & version: Ubuntu
 - GOT version: 11.8.2

I expect that the context will be merged, but in the following code only `startTime` is printed.

```js
const got = require('got');
const {performance} = require('perf_hooks');

const http = got.extend({
    hooks: {
        beforeRequest: [
            (options) => {
                console.log(options.url)
                options.context.test = 10;
            },
            (options) => {
                options.context = {
                    startTime: performance.now(),
                };
            },
            (options) => {
                console.log(options.context.test, options.context.startTime );
            }
        ],

    }
})


http('http://google.com')

...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Mergeable context has not yet been released: https://github.com/sindresorhus/got/commit/2b8ed1f5a185f30603d24e2ceb8181782de3bc5a

**Comment by antoniomuso** [comment]
Thanks for the answer. I have supposed that was integrated because MR was on 21 October 2020. and version 11.8.2 was of 26 February 2021.
