### ISSUE TITLE
Process persists upon error

### ISSUE THREAD

**Issue by joshxyzhimself** [sindresorhus/got#1762]
#### What would you like to discuss?

Is there something that makes got persist process?

We ran a test script (example below) and when it reached the `console.error(e)` part, the process didn't yet exit immediately.

Are there any background timers here? Thank you.

```js
try {
  const json_response = await got.get(/* some error-generating request */).json();
  console.log({ json_response });
  // when this part is reached, process closes immediately
} catch (e) {
  console.error(e); // when this part is reached, process persists a little longer
}
```

We're at `node 16.2.0`, `got 11.8.2`.

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
> process persists a little longer

How much longer exactly?

**Comment by joshxyzhimself** [comment]
Hi, i think there was just something wrong on the code I write, my bad.

Will close this for now, thank you thank you.
