### ISSUE TITLE
Speed up normalizeArguments

### ISSUE THREAD

**Issue by KyleAMathews** [sindresorhus/got#1763]
Running some tests with Got v11, if I request 16k URLs it takes about 5s. If I comment out `normalizeArguments` and just return options there immediately, the time drops to 2.5s.

It seems like there's been a number of improvements to this in Got v12 which is great! But as this is for Gatsby, we're supporting Node 12.13+ and will be for a while, I'd love to see improvements to `normalizeArguments` in v11 as well.

Maybe just add a `disableOptionNormalization` option to let people opt out of the normalization?

**Comment by KyleAMathews** [comment]
Oh hmm https://github.com/sindresorhus/got/blob/0d43f5fea0460977089236b58f2354307fbf27fc/benchmark/index.ts#L88

**Comment by szmarczak** [comment]
Here's Got v11: https://github.com/sindresorhus/got/blob/f896aa52abc41fe40d4942da94a0408477358f14/benchmark/index.ts#L32

**Comment by szmarczak** [comment]
When you pass already normalized options, Got doesn't have to normalize them again. It just only clones them.

**Comment by KyleAMathews** [comment]
Thanks!

I'm going to close this — you're already tracking this elsewhere. Also FYI, I had an error in my code that I was catching and ignoring which was short-circuiting requests so the overhead for normalization is only actually 4-5%.
