### ISSUE TITLE
Unable to use timeout option in browser environment

### ISSUE THREAD

**Issue by jandet** [sindresorhus/got#177]
Setting the timeout config on a got request generates the following errors in the browser environment:

```
TypeError: req.setTimeout is not a function
```
```
Uncaught TypeError: req.abort is not a function
```

Curious if this is a known regression or something perhaps I am doing wrong?

**Comment by floatdrop** [comment]
Dups https://github.com/sindresorhus/got/issues/141 - reopen if this issue is not the same 🌴

**Comment by ralphholzmann** [comment]
@jandet looks like this is due to us using webpack instead of browserify

**Comment by floatdrop** [comment]
@ralphholzmann more like this is due wrong `http` polyfill, that used by default in Webpack – I think you can use (custom shimming)[http://webpack.github.io/docs/shimming-modules.html] to override this.
