### ISSUE TITLE
Setting header values to undefined via beforeRequest hook results in error

### ISSUE THREAD

**Issue by GideonPARANOID** [sindresorhus/got#1771]
#### Describe the bug

 - Node.js version: v16.4.0
 - OS & version: MacOS Big Sur 11.4

Headers can be defined on a request in a few different ways.
Defining headers via the second argument with `headers` property allows setting headers with `undefined` values - the header is stripped away.
Defining headers via a `beforeRequest` hook does not allow setting headers with `undefined` values - an error is thrown.

#### Actual behavior

Headers with `undefined` values are not present in the request, [as is documented](https://github.com/sindresorhus/got#user-agent).

#### Expected behavior

An error is thrown & the request not made.

#### Code to reproduce

```js
const got = require('got');

got('http://example.com', {
  headers: {
    value: undefined
  }
}) // results in success with header removed

got('http://example.com', {
  hooks: {
    beforeRequest: [(options) => {
      options.headers.value = undefined
    }]
  }
}) // throws error 'RequestError: Invalid value "undefined" for header "value"'
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
You're accessing `header` instead of `headers`

**Comment by GideonPARANOID** [comment]
@szmarczak Apologies, typo in the post. Behaviour I'm trying to highlight here:
```
[gideon.jones@work-macbook]:[~]:[master] cat got.js
const got = require('got');

got('http://example.com', {
  hooks: {
    beforeRequest: [(options) => {
      options.headers.value = undefined
    }]
  }
})
[gideon.jones@work-macbook]:[~]:[master] node got.js
(node:27548) UnhandledPromiseRejectionWarning: RequestError: Invalid value "undefined" for header "value"
    at Request._makeRequest (/Users/gideon.jones/node_modules/got/dist/source/core/index.js:1177:19)
    at ClientRequest.setHeader (_http_outgoing.js:564:3)
    at new ClientRequest (_http_client.js:262:14)
    at request (http.js:94:10)
    at Request._makeRequest (/Users/gideon.jones/node_modules/got/dist/source/core/index.js:1124:43)
    at async /Users/gideon.jones/node_modules/got/dist/source/core/index.js:328:17
```

Should I raise a new issue or update this one?

**Comment by szmarczak** [comment]
This error is actually right. Node.js doesn't accept `undefined` as a value. Got doesn't do any processing after calling `beforeRequest` hooks.
