### ISSUE TITLE
Can't convert encoding from windows-1251 to utf8

### ISSUE THREAD

**Issue by azev** [sindresorhus/got#1773]
Can't convert encoding from `windows-1251` to `utf8`

https://stackoverflow.com/questions/68218368/

**Comment by sindresorhus** [comment]
Got has a encoding option. For encodings not supported there, you need to handle it yourself. There are decoding packages on npm.

**Comment by azev** [comment]
You could at least provie an example. Very rude.
No problem.

**Comment by szmarczak** [comment]
@azev This is not a Got issue. It's strictly related to Node.js. You haven't filled out the issue template properly.

The `readme` says:
> Support questions should be asked [here](https://github.com/sindresorhus/got/discussions).
