### ISSUE TITLE
Interest Check: AbortController Support

### ISSUE THREAD

**Issue by extraarya** [sindresorhus/got#1779]
#### What would you like to discuss?

I've been thinking of doing this for personal use, would y'all be interested in me adding support for it through a PR?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
Duplicate of #1511

**Comment by sindresorhus** [comment]
> would y'all be interested in me adding support for it through a PR?

Yes, but beware that PRs here are expected to be high-quality, with comprehensive tests and docs :)
