### ISSUE TITLE
Multiple PFXs with Different Passphrases in https api is not working as per the documentation

### ISSUE THREAD

**Issue by Arshad561** [sindresorhus/got#1783]
#### https pfx option
I have read the documentation and tried the multiple PFXs with different passphrases as mentioned in the readme
```
got('https://example.com', {
	https: {
		pfx: [
			{
				buffer: fs.readFileSync('./key1.pfx'),
				passphrase: 'passphrase1'
			},
			{
				buffer: fs.readFileSync('./key2.pfx'),
				passphrase: 'passphrase2'
			}
		]
	}
});
```

This is not working. Nodejs internally looks for ``buf``  and not ``buffer``.

##### Working Example
```
got('https://example.com', {
	https: {
		pfx: [
			{
				buf: fs.readFileSync('./key1.pfx'),
				passphrase: 'passphrase1'
			},
			{
				buf: fs.readFileSync('./key2.pfx'),
				passphrase: 'passphrase2'
			}
		]
	}
});
```

**Comment by sindresorhus** [comment]
What Got version? Note that the readme is the docs for the unreleased Got v12. If you're in 11, you need to read the docs for that version.

**Comment by Arshad561** [comment]
I have tested with version 11 (11.8.2 to be precise). In NPM [page](https://www.npmjs.com/package/got/v/11.8.2#advanced-https-api) it is mentioned as buffer for pfx and in your v11 branch's [readme](https://github.com/sindresorhus/got/blob/v11/readme.md#advanced-https-api) also it is mentioned as buffer only.

**Comment by szmarczak** [comment]
Indeed, I'll fix this.
