### ISSUE TITLE
Not all cookies are being listed caused by HTTP 303 forcing redirect even if disabled

### ISSUE THREAD

**Issue by quiquelhappy** [sindresorhus/got#1793]
#### Describe the bug

 - Node.js version: v14.17.0
 - OS & version: Windows 10 Pro

I need to list the set-cookie headers before the 303 redirect. I know that according to the specification 303 must redirect, but I need a way to bypass this and prevent any redirects to gather the cookies returned before the redirected is performed. So basically, what I need is a way to access the data before the redirect. **I already use "followRedirect": false & "maxRedirects": 0**, but as the documentation states here https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#note-18, **the 303 code overrides this settings.**

#### Actual behavior

The response follows the 303 see-more redirect preventing me from listing the new set-cookie headers before the redirect

#### Expected behavior

**I should be able to get the new set-cookies, as those should be accessible even after performing the redirect by any client**. A good way to fix this issue would be to **introduce a header history that list the headers status before a 303 redirect, or to add a secondary option to bypass the 303 specification**.

#### Code to reproduce

Instead of code, I'll provide images of my current HTTP flow. I ensured my issue was actually what I thought it was with fiddler.
![oEWC9LS8ie](https://user-images.githubusercontent.com/12534357/126209906-85d1bbd0-bfd2-4f19-906e-bc2d96ebc3e5.gif). I want to capture the response from POST spigotmc.org/login/login, and not the redirect (GET spigotmc.org/, which is actually triggering the result, as you can see in sync with my console)

#### Checklist

- [x] I have read the documentation. (yep, this is caused by the 303 specification listed on the documentation; https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#note-18)
- [x] I have tried my code with the latest version of Node.js and Got. (Latest Got; I know this is caused by the 303 override)

**Comment by quiquelhappy** [comment]
this was me being silly and not actually passing the values to the settings object. sorry for the unnecessary post.

**Comment by clintberry** [comment]
I feel like the cookie jar should set the cookies before the redirect automatically. I am having the same problem, but I am okay following the redirect as long as the cookies get set. Now I have to tell it to not follow the redirect, and set the cookies manually.

**Comment by szmarczak** [comment]
> as the documentation states here https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#note-18, the 303 code overrides this settings.

This is not actually correct, the `followRedirect` logic still applies. Sorry for the confusion, commited 09e8273931e4ccd4d87f4b0b315a2b063e9083e7
