### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by karaluton** [sindresorhus/got#1800]
#### Describe the bug

 - Node.js version: 14.15.4
 - OS & version: Big Sur 11.4

We are utilizing `got` in the following way `await get(url)`.

#### Actual behavior
A 503 response is being returned. 

```
at Request.<anonymous> (/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please fill out the issue template properly.

**Comment by szmarczak** [comment]
`503` is a server error, so I'm not sure what do you mean by reporting this as a bug...
