### ISSUE TITLE
Display weird characters when crawling sites with different charsets than UTF-8.

### ISSUE THREAD

**Issue by crazyfree** [sindresorhus/got#1802]
#### Describe the bug

 - Node.js version: 14.16.1
 - OS & version: Centos 8

#### Actual behavior
Display weird characters when crawling sites with different charsets than UTF-8.
...

#### Expected behavior
Display Japanese characters correctly with different charsets like Shift_JIS, EUC-JP...
...

#### Code to reproduce
import got from 'got';
const { body: html, url } = await got('https://www.atmarkit.co.jp/');
<img width="801" alt="Screen Shot 2021-07-24 at 19 22 54" src="https://user-images.githubusercontent.com/3860469/126869362-0b12716f-dc6b-403c-ac0b-f55efa982597.png">

console.log(html);
```js
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
You have to convert it on your own.

**Comment by shuiRong** [comment]
I also had this problem today and then solved it using `iconv-lite`

https://gist.github.com/shuiRong/f4703da89e7f07baafaaa4a8fad86668
