### ISSUE TITLE
Pipe stream throws error: response has been emitted already

### ISSUE THREAD

**Issue by Borewit** [sindresorhus/got#1803]
#### Describe the bug
Pipe stream causes error: "The response has been emitted already."

Blocks:  sindresorhus/file-type#470

- got version [v11.8.2](https://github.com/sindresorhus/got/releases/tag/v11.8.2)
 - Node.js version: 16.4.2
 - OS & version: Windows 10
 

#### Actual behavior

Throws an error
```
C:\Users\Maarten\code\github\got\dist\source\core\index.js:1476
            throw new Error('Failed to pipe. The response has been emitted already.');
                  ^

Error: Failed to pipe. The response has been emitted already.
    at Request.pipe (C:\Users\Borewit\code\github\got\dist\source\core\index.js:1476:19)
    at Request.<anonymous> (C:\Users\Borewit\code\github\examples\examples\file-type\got-error.js:9:14)
    at Object.onceWrapper (node:events:513:28)
    at Request.emit (node:events:394:28)
    at emitReadable_ (node:internal/streams/readable:571:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
#### Expected behavior
Be able to read the HTTP content using a stream.
I don't see what reading has to do with HTTP headers already sent (emitted).

#### Code to reproduce

```js
const got = require('got');
const stream = require('stream');

const url = 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg';

const httpStream = got.stream(url);
httpStream.on('error', error => console.error(error));
httpStream.once('readable', async () => {
  httpStream.pipe(new stream.PassThrough());
});
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

#### Workaround
See: https://github.com/sindresorhus/got/commit/dec028daf9acaf2d41c7b71ce6659c78bbb00296

**Comment by Borewit** [comment]
I checked out version [11.8.2](https://github.com/sindresorhus/got/releases/tag/v11.8.2) and created (branch from there)[https://github.com/Borewit/got/tree/issue-1803-prevent-emitted-already-error]. 

Interesting enough this the [11.8.2](https://github.com/sindresorhus/got/releases/tag/v11.8.2), respectively commit https://github.com/sindresorhus/got/commit/f896aa52abc41fe40d4942da94a0408477358f14 seems not to (no longer) belong to this repo...

**Comment by szmarczak** [comment]
You can replace

```ts
if (this[kStartedReading]) {
```

with

```ts
if (this[kStartedReading] && this.listenerCount('data') > 0) {
```

If that doesn't help then Got does everything correctly here. You cannot use a response once it has been used already.

**Comment by szmarczak** [comment]
I think that [this](https://github.com/sindresorhus/file-type/blob/dcd7c80611b7d890763d686a7eb98ce466d1525c/core.js#L1427) might cause the issue.

**Comment by szmarczak** [comment]
Hmm... `this.listenerCount('data')` may not be the ideal approach, but I don't think we have a better shot at detecting already-used responses...

**Comment by szmarczak** [comment]
This should fail:

```diff
import got from './dist/source/index.js';
import stream from 'stream';

const url = 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg';

const httpStream = got.stream(url);
httpStream.on('error', error => console.error(error));
httpStream.once('readable', async () => {
+ httpStream.read();
  httpStream.pipe(new stream.PassThrough());
});
```

**Comment by szmarczak** [comment]
You're incorrectly using streams here:

https://github.com/sindresorhus/file-type/blob/dcd7c80611b7d890763d686a7eb98ce466d1525c/core.js#L1438-L1451

If you want to re-use the stream (e.g. return it) then you need to restore what you have read.

https://nodejs.org/api/stream.html#stream_readable_unshift_chunk_encoding

**Comment by szmarczak** [comment]
Let's remove the check entirely. Maybe `undici` will prevent response reuse. Our check works incorrectly.

**Comment by szmarczak** [comment]
Will be released in the next beta, thanks for reporting.

**Comment by Borewit** [comment]
Thanks for your swift response & fix @szmarczak !

**Comment by szmarczak** [comment]
@Borewit Released second beta :)
