### ISSUE TITLE
Limiting body size in stream

### ISSUE THREAD

**Issue by danbulant** [sindresorhus/got#1806]
Is there a way to limit the response body size? I'm fetching user input using got stream (which gets piped elsewhere), and I would like to limit the size. Some website don't send Content-length header, so simply first sending `HEAD` request to check first doesn't work (for example [this one](https://osu.ppy.sh/assets/images/GradeSmall-SS-Silver.6681366c.svg)).

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/examples/advanced-creation.js#L43

**Comment by danbulant** [comment]
Sorry, didn't see that when I was reading docs. Thanks

**Comment by rightaway** [comment]
@szmarczak I'm always seeing `total` is `undefined` and `percent` is either 0 or 1. Do I have to set something for it to show correct values?

**Comment by szmarczak** [comment]
No. `total` being `undefined` has no hidden meaning. The total size is unknown. The server didn't reply how much data it will send.

**Comment by rightaway** [comment]
@szmarczak Does that come from content-length header or are there other ways to know how much data it will send?

**Comment by szmarczak** [comment]
Nope, the spec doesn't define any other places where the content length would be stored.
