### ISSUE TITLE
Handle status code 307

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#181]
See how it's done in https://github.com/olalonde/follow-redirects/pull/28.

**Comment by floatdrop** [comment]
@sindresorhus what should we do with Stream body? We have internal discussion about it and found no other way to implement POST redirects with Stream body than buffer it.

**Comment by sindresorhus** [comment]
I don't really know. How does `request` handle it? Maybe someone smarter than me will come along here and inform us. We could at least handle it correctly for non-streams, right?

**Comment by floatdrop** [comment]
@sindresorhus just pointing this detail. [request is not redirecting](https://github.com/request/request/blob/master/lib/redirect.js#L58) in case of POST, etc...

**Comment by sindresorhus** [comment]
https://github.com/request/request/blob/c289759d10ebd76ff4138e81b39c81badde6e274/lib/redirect.js#L117-L118

**Comment by floatdrop** [comment]
@sindresorhus hm... we don't change method of request on any redirect code atm, so 307 code should work properly now. Not sure about other codes.

**Comment by jamestalmage** [comment]
FYI: https://github.com/jamestalmage/browser-redirect-test

**Comment by jamestalmage** [comment]
What do you guys think about just relying on `follow-redirects`. I'm basically the sole maintainer now, so if there's something you don't like, you know who to bother 😄.

As for caching the stream: https://github.com/jamestalmage/caching-stream. The main advantage over other caching implementations I have seen is that you can abandon the cache or pass through any time you want. So if you received a redirect you would `.endPassThrough()`, and if you became certain you were not going to be redirected, `.dropCache()`. Unfortunately, I'm not sure there's anyway to actually know when it's safe to drop either, so it would probably have to be some type of configurable thing.

The other solution I considered for `follow-redirects` is allowing `opts.body` to be a `function` that returns a Stream. That breaks compatibility with the core `http` library, which is a goal of `follow-redirects`, so I never proceeded. `got` isn't restricted in the same way though.

**Comment by floatdrop** [comment]
> What do you guys think about just relying on follow-redirects. I'm basically the sole maintainer now, so if there's something you don't like, you know who to bother 😄.

I'm good with this – redirection logic becomes quite sophisticated and can be moved out to a module. But how `redirect` event will work with this module?

> As for caching the stream: https://github.com/jamestalmage/caching-stream.

This is cool, yet dangerous thing to do. What if server does not reply immediately with redirect code and waits for all upload to be finished (checks contents SHA for example)?

I would love to hear about use cases for caching – is this a common thing to handle?

**Comment by jamestalmage** [comment]
> This is cool, yet dangerous thing to do.

Agreed, it's why I never actually pulled it into `follow-redirects`. It's probably why you don't see other libraries doing it either.

I think you would be better of just allowing a stream generator function that can be called many times:

```
got.post('url',{
  body: () => fs.createReadStream('path')
});
```

**Comment by sindresorhus** [comment]
> I'm good with this

👍

**Comment by ninox92** [comment]
+1
Can confirm that 307 does not redirect properly and throws an error

```
{ HTTPError
    at EventEmitter.ee.on.res (/node_modules/got/index.js:182:24)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at Immediate.setImmediate (/node_modules/got/index.js:61:8)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  message: 'Response code 307 (Temporary Redirect)',
  host: 'storage......',
  hostname: 'storage........',
  method: 'PUT',
  path: '/n.svc/jsonsession',
  statusCode: 307,
  statusMessage: 'Temporary Redirect' }
```

**Comment by ninox92** [comment]
+1
Need a 307 PUT request to follow redirect

**Comment by floatdrop** [comment]
Dups #291 – will be done there.
