### ISSUE TITLE
Support multipart/form-data encoding

### ISSUE THREAD

**Issue by octet-stream** [sindresorhus/got#1810]
#### What problem are you trying to solve?

General support for spec-compatible FormData implementations.

#### Describe the feature

Current form-data encoding in Got relies on [`form-data`](https://npmjs.com/package/form-data) package implementation which is not spec-compatible and [lacks of most of FormData interface methods](https://github.com/form-data/form-data/issues/124). I suggest to add general support for this type of request body. How this can be done:

* Detect spec-compatible FormData objects in request body: this will allow to use either [`formdata-node`](https://npmjs.com/package/formdata-node), or [`formdata-polyfill`](https://npmjs.com/package/formdata-polyfill), or any other implementation as long as it follows the spec;
* Implement in-house form-data encoder or just use [`form-data-encoder`](https://npmjs.com/package/form-data-encoder) package instead;

References:

* https://github.com/node-fetch/node-fetch/issues/1167
* https://github.com/octet-stream/form-data/issues/1

If you don't mind to use `form-data-encoder` to handle this encoding, I can file a PR to bring its support.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Got v12 supports async iterators so https://www.npmjs.com/package/formdata-node should work out of the box.

**Comment by szmarczak** [comment]
https://github.com/jimmywarting/FormData is a no as of now - Got doesn't support Blobs

**Comment by octet-stream** [comment]
> Got v12 supports async iterators so npmjs.com/package/formdata-node should work out of the box.

Builtin encoding will be removed from formdata-node in next major release, because it must be handled by HTTP client. This suggestion is not about support for some specific package, but rather for `multipart/form-data` encoding in general.

**Comment by szmarczak** [comment]
Please consider removing [`nanoid`](https://packagephobia.com/result?p=nanoid). It weights 52KB.

**Comment by octet-stream** [comment]
Yeah, I will do something about this.

**Comment by octet-stream** [comment]
Decided to just use crypto.randomBytes for boundary string, should be more than enough. Kind of don't want to use just Math.radmom() for this, but it would've be fine too.

Available in form-data-encoder 1.1.0, now it weights 35 KB. I will reduce the size once again when I drop CJS support.

**Comment by szmarczak** [comment]
What's wrong with `Math.random()`?

**Comment by octet-stream** [comment]
> What's wrong with Math.random()?

It seem to be fine as well, found few other implementations which are using Math.random() boundaries (one of them is part of Deno).

form-data-encoder integration seem to work fine, the tests are passing and I can file a PR for further discussion of you want.

**Comment by szmarczak** [comment]
`crypto` is fine I guess :) I forgot Node.js has a dedicated API for generating random numbers.

**Comment by jimmywarting** [comment]
Firefox only use numbers for it's boundary. They don't have to be super random. Math.random is fine and more cross Deno/Browser/nodejs friendlier as it dose not depend on any core nodejs stuff

**Comment by octet-stream** [comment]
I already switched to Math.random()

**Comment by tutods** [comment]
Is it possible to use the got with multipart/formdata?
