### ISSUE TITLE
SSL ALTNAME_INVALID error on sites which redirect from domain apex record to www

### ISSUE THREAD

**Issue by AMega** [sindresorhus/got#1811]
request returns a FAIL, when firing up a request to a URL which has a 301 redirect from domain apex to www AND the site CERTIFICATE is only valid for the ALTNAME including www.

This happens even when enabling the "followRedirect" option and ONLY if you specify the HTTPS protocol. 
When you send the request to the http://myexample.com - the 301 correctly redirects you to the https://www(...) and the request returns a success.

It seems that the SSL cert check happens before the redirect is followed. 
Granted, this is an edge case, but not unheard of. 

FAIL Example: 
domain:  myexample.com  
requests sent to https://myexample.com --> 301 redirect to : https://www.myexample.com - request FAILS

SUCCESS Example: 
requests sent to http://myexample.com --> 301 redirect to : https://www.myexample.com - request is SUCCESSFUL

SSL CERT has ONLY 1 valid ALTNAME:  www.myexample.com

**Comment by szmarczak** [comment]
There is nothing wrong here. If the certificate is for the subdomain only then it's expected to throw if you don't use the subdomain.

**Comment by AMega** [comment]
I get that. 
I guess I was just suggesting that the redirect flag should delay checking the SSL Cert until AFTER the redirect is followed.

**Comment by szmarczak** [comment]
That wouldn't make any sense.

**Comment by AMega** [comment]
What if the redirect takes you to a completely different domain which is WORKING OK and has the correct certificate... 

In the current state - GOT will return a failure because it will check the SSL CERT of the original domain and NOT the one which is redirected to. 

What's the point of the "followRedirect" flag then ?

**Comment by szmarczak** [comment]
It checks the redirected domain. Before the request sent a TLS handshake occurs first.
