### ISSUE TITLE
Extend retry statusCode in order to work for 404.

### ISSUE THREAD

**Issue by y0x** [sindresorhus/got#1812]
I’m making HTTP requests to an API where I can expect an HTTP code 404 under certain conditions. I’d like to use Got's internal retry functionality for rerunning the request until the 404 error is gone (which will happen; I just don't know if it takes 1 minute or 30 minutes).

From the documentation I know that HTTP code 404 is not a supported statusCode for the built-in retry functionality and therefore I cannot perform any action within the beforeRetry hook of Got.

I’m extending a Got instance to allow some presets for the API I’m calling. For now I have not found a clean way to extend the existing retry statusCodes with 404.

```
const x= got.extend({
    prefixUrl: ".." + "..",
    mutableDefaults: true,
    responseType: 'json',
    //retry: { statusCode: got.defaults.options.retry.statusCode.push(404) }, //does not work | not clean
    https: { rejectUnauthorized: false },
    headers: {
        'PRIVATE-TOKEN': "..",
        Accept: 'application/json',
    },
    hooks: {
        beforeError: [
            (error) => {
                const { response } = error;
                console.log(response);
                /*
                Another idea: if I cannot extend retry statusCodes then I´d like to somehow force a retry from here
                if (response.statusCode === 404 && response.path.endsWith('/export/download')) {
                    console.log('FORCE A RETRY AS THE DOWNLOAD MIGHT NOT BE READY YET');
                }
                */

                if (response && response.body) {
                    error.name = 'x';
                    error.message = `${response.body.message !== undefined
                            ? response.body.message
                            : response.body.error
                        } (${response.statusCode})`;
                }

                return error;
            },
        ],
    },
});
```

1. How can I extend the HTTP statusCodes that allow running a retry?
2. If this is not possible, see my comment in the code. Is it somehow possible to force a retry manually by just using Got?

I´m aware that I could just catch the 404 and then do the retry manually, just asking for a way of doing it internal.

Thanks for the awesome lib, love it!

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
> //retry: { statusCode: got.defaults.options.retry.statusCode.push(404) }, //does not work | not clean

```js
retry: { statusCode: [...got.defaults.options.retry.statusCode, 404] },
```
