### ISSUE TITLE
Duplicate query param keys are stripped when using URLSearchParams

### ISSUE THREAD

**Issue by rosswilson** [sindresorhus/got#1814]
#### Describe the bug

 - Node.js version: v16.4.0
 - OS & version: Mac 10.15.7
 - Got version: 12.0.0-beta.1

#### Actual behavior

When passing a `URLSearchParams` with duplicate keys, only the last key/value is used in the URL search params.

```js
  const searchParams = new URLSearchParams();

  searchParams.append("a", "100");
  searchParams.append("a", "200");
  searchParams.append("a", "300");

  const response = await got.get(
    'https://example.com',
    {
      searchParams: searchParams,
    }
  );

  console.log(response.request.options.url);
```

Results in the following URL:

```
  URL {
      href: 'https://example.com?a=300',
      origin: 'https://example.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'example.com',
      hostname: 'example.com',
      port: '',
      pathname: '/',
      search: '?a=300',
      searchParams: URLSearchParams { 'a' => '300' },
      hash: ''
    }
```

#### Expected behavior

 I expected the duplicate search param keys to have been included.  The same happens even if I `toString()` the `URLSearchParams` myself and pass that in. Seems like Got is parsing and re-encoding the params.

```
  URL {
      href: 'https://example.com?a=100&a=200&a=300',
      origin: 'https://example.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'example.com',
      hostname: 'example.com',
      port: '',
      pathname: '/',
      search: '?a=100&a=200&a=300',
      searchParams: URLSearchParams { 'a' => '100', 'a' => '200', 'a' => '300' },
      hash: ''
    }
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by risyadzyn21** [comment]
Hi, I have same problem. how you handled this?

**Comment by rosswilson** [comment]
This was fixed by https://github.com/sindresorhus/got/commit/1018c2029eea1f5b75b5120265996f1c0b3c12ae, are you using an updated version of the library that includes that fix?

**Comment by risyadzyn21** [comment]
tbh I use useSearchParams from react-router-dom, is it different?
