### ISSUE TITLE
Can't import got

### ISSUE THREAD

**Issue by Nzent** [sindresorhus/got#1819]
#### Describe the bug

 - Node.js version: 
 - 14.17.3
 - OS & version: 
 - windows 10

can't import got in next.js
throwing error called module not found 'dns'
![image](https://user-images.githubusercontent.com/26079832/128161726-ab3e55f5-26d8-462b-bc10-3a0a5b8f936a.png)

**Comment by szmarczak** [comment]
Please set up a reproducible repo.

**Comment by szmarczak** [comment]
You can't use Got in client-side apps.
