### ISSUE TITLE
ParseError should contain err.statusCode

### ISSUE THREAD

**Issue by satazor** [sindresorhus/got#182]
`curl -v https://api.github.com/repos/震动/generator-test` should output a json but it does print an HTML pages, which gives a `ParseError` if we use `got()` with `options.json=true`. Though, I was expecting that the ParseError contained the `err.statusCode` property, which doesn't at the moment. It has to be accessed via `err.response.statusCode` which kind sucks :(

Thoughts?

**Comment by sindresorhus** [comment]
:+1:

**Comment by floatdrop** [comment]
Yes, it should for consistency, because other errors have these fields.

**Comment by satazor** [comment]
PR done.

**Comment by satazor** [comment]
I haven't added because thats already covered in the error introduction:

> Each error contains (if available) statusCode, statusMessage, host, hostname, method and path properties to make debugging easier.

Still do you want the `statusCode` and `statusMessage` mentioned in the `ParseError`?

**Comment by satazor** [comment]
Oh nvm you added that recently aha. :dancer:
