### ISSUE TITLE
null value should remove headers

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#1825]
#### What problem are you trying to solve?

Only `undefined` can be used to remove a header. `null` used to be able to do it too (https://github.com/sindresorhus/got/issues/485) but not anymore. Can it be added back?

There are situations where the library you are using uses `null` to indicate an empty value for a header. For example a library that parses environment variables or command line flags and considers a value that hasn't been provided to be `null` rather than `undefined`.

It would be a backwards compatible change to allow `null` since it doesn't have any current behavior. It only throws an error saying that you need to use `undefined`.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
> There are situations where the library you are using uses null to indicate an empty value for a header.

You can use a `beforeRequest` hook to transform `null` into `''`.

> For example a library that parses environment variables or command line flags and considers a value that hasn't been provided to be null rather than undefined.

And this is the part where it's ambiguous. Should `null` be treated as `''` or `undefined`? Avoid using `null` whenever possible. See https://github.com/sindresorhus/meta/discussions/7

**Comment by szmarczak** [comment]
Also see https://github.com/sindresorhus/meta/discussions/7#discussioncomment-186465
