### ISSUE TITLE
Track changes but normalize them later

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1830]
#### What problem are you trying to solve?

```js
const opts = new Options({
	url: 'https://example.com,
	headers: {
		foo: 'bar'
	}
});

opts.merge({
	hooks: {
		// some hooks
	}
});

opts.merge({
	hooks: {
		// some hooks
	}
});

opts.merge({
	headers: {
		// some headers
	}
});

instance(opts); // now normalize
```

> Hmm, so basically the defaults from the instance would never apply...
> because they are already set

`got(optionsInstance)` would be confusing as ones would expect this to override the defaults and ones would expect to merge the changes.

#### What's the idea?

This is just a builder pattern.

We build up the options, but it should be possible to export (use) the changes somehow.

#### Possible solutions

```js
got(url, [plainOptions1, plainOptions2])
```

but this is half a solution because there's no way to tell the actual value while generating the sequence of options. May be sufficient enough for some use cases.

#### What's the issue?

The issue is that `Option` stores **all** options normalized.
Got isn't aware of the context.

It doesn't know if the `Options` instance should be treated as the-only-options-and-nothing-more (aka defaults) or if it should merge changes only. So Got currenctly forces all `Options` to be passed as defaults (the third argument in `got` function).

Another issue is TypeScript. Having lots of overloads complicates the code.

#### Current workaround

```js
import got, {Options} from './dist/source/index.js';

class Tracker extends Options {}

const wrap = instance => {
	return (url, plainOptions, defaults = instance.defaults.options) => {
		if (url instanceof Tracker) {
			if (plainOptions instanceof Tracker) {
				throw new Error('Received two Tracker instances, expected only one.');
			}

			// This or just `(undefined, undefined, defaults)`
			const options = new Options(undefined, plainOptions, defaults);
			options.merge(url);

			// Yes, `url.url`, not `options.url`.
			return got(url.url, undefined, options);
		}

		if (plainOptions instanceof Tracker) {
			// This or just (undefined, undefined, defaults)
			const options = new Options(url, undefined, defaults);
			options.merge(plainOptions);

			if (plainOptions.url) {
				options.url = plainOptions.url;
			}

			return got(options.url, undefined, options);
		}

		return got(url, options, defaults);
	};
};

const wrapped = wrap(got);

const tracker = new Tracker({
	url: 'https://httpbin.org/anything',
	headers: {
		foo: 'bar'
	}
});

tracker.merge({
	hooks: {
		beforeRequest: [
			() => {
				console.log('beforeRequest called');
			}
		]
	}
});

tracker.merge({
	headers: {
		foo: 'bar'
	}
});

const {headers} = await wrapped(tracker).json();
console.log(headers.Foo);
```

or without a wrapper:

```js
const tracker = new Options({
	url: 'https://httpbin.org/anything',
	headers: {
		foo: 'bar'
	}
}, undefined, instance.defaults.options);

tracker.merge({
	hooks: {
		beforeRequest: [
			() => {
				console.log('beforeRequest called');
			}
		]
	}
});

tracker.merge({
	headers: {
		foo: 'bar'
	}
});

instance(tracker.url, undefined, tracker);
```

#### Other concerns

<details>
<summary>off-topic</summary>

The docs are still a bit poor in regrads to option normalization and extending instances.

They need say that `url` is not merged on `options.merge(another)`.

`How to store options` should list all the possible constructor arguments to avoid confusion:

- `(url, options, defaults)`
- `(url, options)`
- `(options)`

- `(undefined, options, defaults)`
- `(options, undefined, defaults)`
- `(undefined, options)`

</details>

**Comment by szmarczak** [comment]
@sindresorhus Is this something we want?

**Comment by mnmkng** [comment]
The grief I have with this is that the `new Options()` API does not feel intuitive and is not used in a way one would expect. For example, if I create an ordinary, intuitive instance, I have to use it very weirdly:

```js
```

**Comment by mnmkng** [comment]
The grief I have with this is that the `new Options()` API does not feel intuitive and is not used in a way one would expect. For example, if I create an ordinary, intuitive instance, I have to use it very weirdly:

```js
const opts = new Options({
    url: 'https://example.com',
    headers: {
        foo: 'bar'
    }
});

await got(opts.url, undefined, opts); // 🤷‍♂️
```

Also, it's extremely hard to tell the difference between all the various overloads and their purpose. E.g. `(undefined, options, defaults)` vs `(options, undefined, defaults)`.

Another thing is, why does the `Options` constructor even accept a third parameter called `defaults`? Defaults make sense on client level, not on options level. Having defaults somehow implies that I would reuse this instance of options for more requests. Is that the intention?

Normalization before it's actually needed is another puzzle. The options need to be normalized before the request is made, that's for sure. But do they really need to be normalized every time we `merge()` or add a property? Especially confusing is the early normalization of all the remaining options that were not even provided by the user.

Note that I'm coming from the "public API" perspective. I don't precisely know the reasons why those things might be needed internally, but knowing other HTTP clients, I would expect the public API to be consistent no matter if I use a plain object as options or the actual `Options` instance. And I would expect at most one overload, e.g. `got(url,options)` or `got(options)`.

With that said, I'm still thankful for Got 12 and the improvements it brings, I just have a hard time wrapping my head around the new `Options`.

**Comment by szmarczak** [comment]
> E.g. (undefined, options, defaults) vs (options, undefined, defaults).

In this example the two mean the same. 

- `(undefined, options, defaults)` is a longer form of `(undefined, options)`
- `(options, undefined, defaults)` is a longer form of `(options)` which translates to `(undefined, options)`

> Having defaults somehow implies that I would reuse this instance of options for more requests. Is that the intention?

Correct. There is a 16% performance improvement when there's no need to normalize the options, just clone them.

> Especially confusing is the early normalization of all the remaining options that were not even provided by the user.

Fetch `Request` behaves the same:

```js
new Request('https://example.com').method //=> 'GET'
new Request('https://example.com').redirect //=> 'follow'
...
```

> do they really need to be normalized every time we merge() or add a property?

Yes. If to chain options like this someone may want to know actual value before proceeding.

> I would expect at most one overload, e.g. got(url,options) or got(options).

As mentioned earlier, `defaults` as the third arguments prevents normalization (if no other object is provided than `url`) as the options are normalized and this gives a performance boost. While Got is still in beta, it's best if we discuss the changes now. We would have to bring back `got.create()` to make `defaults` disappear as the third argument. Unless the 16% performance improvement is not important, then we can forget about this and remove it completely.

> I just have a hard time wrapping my head around the new Options.

I can't find a better solution.

**Comment by mnmkng** [comment]
> Fetch `Request` behaves the same:
> 
> ```js
> new Request('https://example.com').method //=> 'GET'
> new Request('https://example.com').redirect //=> 'follow'
> ...
> ```

I see. But I see an important difference between `Options` and `Request`. In `Request` all the props are read only ([at least MDN says so](https://developer.mozilla.org/en-US/docs/Web/API/Request)) so it makes sense that the normalized options are returned immediately, because the `Request` is effectively "finished" by the time you call the constructor. Whereas `Options` are mutable and can also be merged. So I think it's weird to have them "finished" and "accepting changes" at the same time.

Still, I don't see this as a huge problem. More a different opinion about how APIs should look. Both approaches are valid.

**Comment by szmarczak** [comment]
> So I think it's weird to have them "finished" and "accepting changes" at the same time.

It's required for example when calling `beforeRequest` hooks. All options should be defined there and should be mutable.

**Comment by szmarczak** [comment]
@mnmkng This way is a bit simpler than what I mentioned earlier:

```js
import got, {Options} from './dist/source/index.js';

const instance = got.extend({
	hooks: {
		init: [
			(raw, self) => {
				if ('options' in raw) {
					self.merge(raw.options);

					// TODO (Got shouldn't force URL to be provided before .end() is called)
					// if (raw.options.url) {
					// 	self.url = raw.options.url;
					// }

					delete raw.options;
				}
			}
		]
	}
});

const tracker = new Options('https://httpbin.org/anything');

tracker.merge({
	headers: {
		foo: 'bar'
	}
});

const response = await instance(tracker.url, { options: tracker }).json();

console.log(response.headers.Foo);
```

**Comment by mnmkng** [comment]
Yeah, this looks readable 👏

**Comment by szmarczak** [comment]
I'll close this for now. Not something we should focus on, and the provided examples should be sufficient enough for this use case. We would need more feedback on this one.
