### ISSUE TITLE
How to stream the full track at once.

### ISSUE THREAD

**Issue by r0hin** [sindresorhus/got#1839]
I've got an ExpressJS server setup that downloads an audio file and then streams it directly to the result.
```
got.stream(url, {}).pipe(res).on('finish', () => {
    res.end();
  })
```
When I use an <audio> HTML tag and point towards the express server, about four minutes of the audio file loads and the rest is left unloaded. When I go to the source itself:
![image](https://user-images.githubusercontent.com/46874702/129298525-131c0a4c-91ca-4c4f-9372-2a23c4dc8e6e.png)
The first bit is loaded. However, it waits to load the second part until you get close to the end. When you do however, the rest loads instantly.

For me, it looks like the stream is holding off on sending the last bit of data until the user gets near it. In my case though, I need all the data at once since I'm using this as an alternative to downloading, then sending, so that the user can access the audio before the download is fully complete.

Does it make sense? Thank you for your help!

**Comment by szmarczak** [comment]
This is not a Got issue

**Comment by r0hin** [comment]
> This is not a Got issue

Do you know where the issue is coming from then?
