### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by canac** [sindresorhus/got#184]
Does `got` support HTTP basic auth? The code references an `auth` option, but none seems to currently exist. Of course, I can manually base64 encode my authentication data and pass it in through the `Authorization` header, but I would expect an HTTP request library to do that for me.

**Comment by sindresorhus** [comment]
It's right in the linked Node.js docs: https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by canac** [comment]
OK, now I see that the documentation says the `options` argument supports "any of the `http.request` options." I should have read it more carefully. Thanks for making this awesome module; it's a pleasure to use it!

**Comment by monkekode** [comment]
For anyone coming to this issue from Google, like me, you now have to set `username` and `password` instead of the `auth` (user:pass) option.
