### ISSUE TITLE
got.post() with json posting empty data

### ISSUE THREAD

**Issue by rburkard** [sindresorhus/got#1844]
Hi everyone

I am fairly new to working with APIs and ran into this issue today. 

Versions used: We are using 'got' 9.6.0 with 'nodejs' v14.15.4 and typescript.

When I try this:
` 
let response = await got.post("https://httpbin.org/anything", {
  json: { username: "email@gmail.com", password: "password1" },
  responseType: "json",
 });
`

I get the following response with an empty data field:

`{
   args: {},
   data: '',
   files: {},
   form: {},
   headers: {
     Accept: 'application/json',
     'Accept-Encoding': 'gzip, deflate',
     'Content-Length': '0',
     Host: 'httpbin.org',
     'User-Agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
     'X-Amzn-Trace-Id': 'Root=1-611b63e7-5cca42c77c327e835897e642'
   },
   json: null,
   method: 'POST',
   origin: '51.154.68.64',
   url: 'https://httpbin.org/anything'
}`

If I call the same endpoint with the same parameters using curl, I get the correct response.

Does anyone know what is wrong here or how I can test further?

Thank you and have a great day!

**Comment by sindresorhus** [comment]
First, try to upgrade to the latest version of Got.

**Comment by rburkard** [comment]
Oh wow, sorry for this one. I was on an outdated NPM version and it always installed 9.6.0.

Issue is gone with the current version!
