### ISSUE TITLE
httpVersion not appearing for errors without response

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#1846]
If you make a request that fails with an error that has no `e.response` (such as `ETIMEDOUT`), there is no `httpVersion`. It is not under `e.request` or `e.options` but it should be provided on one of them since `e.response` isn't available for this and other types of errors.

**Comment by szmarczak** [comment]
If the request times out (e.g. connection timeout, lookup timeout) it's not possible to get the http version because it has not yet connected.
