### ISSUE TITLE
`beforeRetry` docs need updating

### ISSUE THREAD

**Issue by lsloan** [sindresorhus/got#1849]
#### What would you like to discuss?

I'm getting started with using the `beforeRetry` hook in got 11.8.2.  Its documentation appears to be outdated.  In https://github.com/sindresorhus/got/blob/fa4b210/documentation/9-hooks.md#beforeretry the arguments are described as:

```ts
(error: RequestError, retryCount: number)
```

However, my IDE showed me that the hook uses three arguments of types `NormalizedOptions`, `RequestError`, and `number`.  Also, the `beforeRetry` example in the documentation didn't work, because the `error` argument doesn't have a `code` property.

I examined the code and I saw that some examples in comments show using the hook with three arguments, the first being for options.  However, the code itself seems to specify only two arguments.  I'm rather new to TypeScript, so I may be overlooking something, but I've found that it works for me if I use three arguments with the hook, as described by my IDE.

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
The docs you are viewing are for the `main` branch where Got 12 is being developed. Please navigate to the Releases tab and find the v11 tag there.

**Comment by lsloan** [comment]
OK.  So in Got 12, the `beforeRetry` hook will no longer use the `options` argument?

Are there plans to make the new hook compatible with the old method signature?  Or maybe recommendations for using the hook with Got 11 that will continue to work with Got 12?

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/releases/tag/v12.0.0-beta.1

> The beforeRetry hook now accepts only two arguments: error and retryCount
> ... [code + workaround]

**Comment by szmarczak** [comment]
Technically I think it's still possible to modify the options via `error.options`, but that doesn't work with Stream API therefore it's best to store the changes in the context and merge them in `beforeRequest` hook.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/fa4b210b003ce5bd04fc82f28dc44fc68a2e4a15/test/hooks.ts#L454-L469

The example in the release notes may be a bit incorrect. I forgot that the `context` is shallow cloned so the `headers` property is not persistent unless it's in another object. Meaning: it needs to be stored `context.someStorage.headers`.

**Comment by szmarczak** [comment]
Okay, forget what I said in these three comments above 😅 Fixed Stream API retry example here: edd39114acb642b712b00f4d664ddc0b9eab26c4

**Comment by szmarczak** [comment]
Edited the beta 1 release notes. TL;DR replace `options` (Got 11) with `error.options` (Got 12). That's all. The changes will be reflected in the next request as usual :)

**Comment by szmarczak** [comment]
I'll close this for now. If you have any other questions, please ask :)
