### ISSUE TITLE
Latest published version is 5.x

### ISSUE THREAD

**Issue by satazor** [sindresorhus/got#185]
I just did a npm install got and it installed 5.x instead of 6.x. Could we release a new version of 6.x to fix this? Thanks.

**Comment by floatdrop** [comment]
@satazor can you run `npm show got dist-tags`? I'm pretty sure, that `6.2.0` is latest version (https://npmjs.com/got is showing that).

**Comment by satazor** [comment]
Oh, this is a problem with `david`.. it uses the last entry from the times object: 

```js
"6.2.0": "2016-03-03T07:54:01.845Z",
"5.5.0": "2016-03-03T08:00:46.060Z"
```

See: https://david-dm.org/IndigoUnited/node-gh-issues-stats
