### ISSUE TITLE
Got doesn't work with electron

### ISSUE THREAD

**Issue by HuHguZ** [sindresorhus/got#1857]
#### What would you like to discuss?
Why does the got not work in the electron and is it possible to fix it? Maybe I need to shrink the version of the electron?
i have electron@13.2.2 and got@11.8.2.
![image](https://user-images.githubusercontent.com/32592443/131224637-54bb57a2-c200-48e4-b46f-74e45bdaece8.png)

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/tips.md#electron-net-module-is-not-supported
