### ISSUE TITLE
How to avoid calling multiple times the same request if the request time out exceeded?

### ISSUE THREAD

**Issue by aniinprni** [sindresorhus/got#186]
Hi we are using `got` with out any issues. But recently i was noticing one scenario. If we fire the request and the if the response did not came with in the timeout interval , `got` is firing the request again and again multiple times. We would like to avoid this scenario. if the response did not came with in the timeout interval then it should stop firing and error should be thrown. Below is the example code snippet .

```js
var reqObj = {
			  method: options.method || 'POST',
			  timeout: options.timeout || 180000,
			  retries:0,
			  headers: {
				'content-type': 'application/json'
			  },
			  body:data
			};
got(options.uri,reqObj)
		    .then(response => {
				var result=JSON.parse(response.body);
				
				return  callback(null,response,response.body);
		    })
		    .catch(error => {
		        console.log(error);
				callback(error,null,null);
		    });
```

Please help me out

**Comment by floatdrop** [comment]
@aniinprni this is strange - `retries: 0` [must disable retries](https://github.com/sindresorhus/got/blob/master/test/retry.js#L38).
