### ISSUE TITLE
always 503 error raise

### ISSUE THREAD

**Issue by BlueClouDragon** [sindresorhus/got#1862]
const { res } = await got.post(url, {
            json: offer_data,
            headers: headers
        }).json();

this request works with all other request libraries, but does not work with this got library
it always return 503 error

**Comment by sindresorhus** [comment]
Please fill out the bug report issue template. We cannot really help you without being able to reproduce.

**Comment by sindresorhus** [comment]
I would recommend trying to disable retrying and see if that fixes your problem.
