### ISSUE TITLE
Timeout not respected when requesting to unroutable host with HTTP/2

### ISSUE THREAD

**Issue by owenpearson** [sindresorhus/got#1899]
#### Describe the bug

 - Node.js version: v16.12.0
 - OS & version: macOS Big Sur 11.6

#### Actual behavior

When using HTTP/2 and making a request to an unroutable host the library does not respect the provided timeout and even if the request is explicitly cancelled it still leaves a socket open.

#### Expected behavior

The request should end with a TimeoutError and not leave any active handles open.

#### Code to reproduce

```js
const request = got({
  // An unroutable host
  url: 'https://10.255.255.1/',
  // NB: this code will give a timeout error and finish the Node process if http2 is set to false
  http2: true,
  timeout: {
    // The request will not fail with a timeout error after the given timeout has elapsed.
    request: 100,
  }
});

request.then(console.log).catch(console.log);

setTimeout(() => {
  // Causes the above promise to reject with CancelError but the Node process stays open because a socket is still active.
  request.cancel();
}, 5000);
```

**Comment by Xairoo** [comment]
Doesn't work in got v12.0.1, Node.js v16.11.1.

```
const response = await got('https://minecraft.net', {
  timeout: { request: 10000 },
});
```
