### ISSUE TITLE
Can we move @types/* from dependencies to devDependencies?

### ISSUE THREAD

**Issue by mattddean** [sindresorhus/got#1913]
#### What would you like to discuss?

https://github.com/sindresorhus/got/blob/main/package.json#L49-L50

```json
"@types/cacheable-request": "^6.0.2",
"@types/responselike": "^1.0.0",
```

...

#### Checklist

- [ ] I have read the documentation.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/issues/1620
https://github.com/sindresorhus/got/issues/1152
