### ISSUE TITLE
RetryError is not exported

### ISSUE THREAD

**Issue by superlc** [sindresorhus/got#1920]
#### Describe the bug

 - Node.js version: v14.17.5
 - OS & version: macos 10.15.7 (19H1323)

#### 
import { RetryError } from 'got'
![image](https://user-images.githubusercontent.com/4110124/142200409-3bf83b99-0bd0-4a17-b317-2b7d17645722.png)

#### Expected behavior

import { RetryError } from 'got'
...

#### Code to reproduce

```js
...
```

#### Checklist

- [ - ] I have read the documentation.
- [ - ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/30aad388ba1a11144be35356f020ababf4bffc79/source/index.ts#L20

https://github.com/sindresorhus/got/blob/30aad388ba1a11144be35356f020ababf4bffc79/source/core/errors.ts#L166

**Comment by superlc** [comment]
I have read the source code. The code of the href you gave is correct, but when I import { RetryError } from 'got', It shows that 
![image](https://user-images.githubusercontent.com/4110124/142343148-53286026-9dc0-4fb8-bbba-f9372dfc7fce.png)
I was so confused.

**Comment by superlc** [comment]
> https://github.com/sindresorhus/got/blob/30aad388ba1a11144be35356f020ababf4bffc79/source/index.ts#L20
> 
> https://github.com/sindresorhus/got/blob/30aad388ba1a11144be35356f020ababf4bffc79/source/core/errors.ts#L166

I have no problem with source code. If you read dist code carefully, you could find it out that no RetryError in types file.

**Comment by szmarczak** [comment]
The exported `types.d.ts` file is not used as the `types` entry in `package.json`, it's just a helper. Because it's defined in the source code, it's also exported here:

https://cdn.jsdelivr.net/npm/got@12.0.0-beta.4/dist/source/core/errors.d.ts
```ts
export declare class RetryError extends RequestError {
```

which is imported by https://cdn.jsdelivr.net/npm/got@12.0.0-beta.4/dist/source/index.d.ts

**Comment by szmarczak** [comment]
Can you set up a repro please?

**Comment by superlc** [comment]
> Can you set up a repro please?

After I installed the package of version 12.0.0-beta.4, it works. I can use RetryError now.
