### ISSUE TITLE
Drop-in Request shim/wrapper

### ISSUE THREAD

**Issue by dynamiclover** [sindresorhus/got#1922]
#### What problem are you trying to solve?
Several hundred internal repos that depend on `request` are going to be blocked from deployment. My org cannot be the only one facing this.

Before I embark on doing this on my own, I wanted to make sure it's not a fools errand or something that you recommend against.

Thank you for all of your hard work! Love your modules :+1:

#### Describe the feature
A drop-in replacement for `request` that uses `got` under the hood.

```
npm remove request
npm install --save request-got-dropped-in
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Use Got interface. It's more convenient.

**Comment by dynamiclover** [comment]
@szmarczak: I don't find changing call-site usage on 300 repos more convenient... Would you volunteer for that task? Probably not :) Thanks for replying either way.

**Comment by szmarczak** [comment]
> I don't find changing call-site usage on 300 repos more convenient.

Well, keeping old, not necessarily readable code is not good either.

> Would you volunteer for that task? Probably not :)

I definitely wouldn't work for free. Everything has its price :>
