### ISSUE TITLE
Got as a class

### ISSUE THREAD

**Issue by timvandam** [sindresorhus/got#1930]
#### What problem are you trying to solve?
I want to use dependency injection with got (in typescript), but this is currently not nice to do since `Got` is an interface: https://github.com/sindresorhus/got/blob/49c605ca85fa35b7c1b6819219cb7bd5209b4085/source/types.ts#L201
`Got` being an interface makes it impossible to use it as DI token

#### Describe the feature
Making `Got` a (abstract) class would make it possible to use `Got` as a DI token, which would make dependency injection possible without workarounds like manually having to specify a token

Example in Nest.js what it would look like to nicely do dependency injection with got being a class (with a constructor):
```ts
import { Got } from 'got';

@Module({
  providers: [Got, SomethingThatUsesGotService],
})
class SomethingThatUsesGotModule {}

@Injectable()
class SomethingThatUsesGotService {
    constructor (private got: Got) {}

    // implementation
}
```

Got being an abstract class (so no constructor):
```ts
import got, { Got } from 'got';

@Module({
  providers: [{ provide: Got, useValue: got }, SomethingThatUsesGotService],
})
class SomethingThatUsesGotModule {}

@Injectable()
class SomethingThatUsesGotService {
    constructor (private got: Got) {}

    // implementation
}
```

Workaround with a string DI token:
```ts
import got, { Got } from 'got';
const GOT_TOKEN = 'GOT_TOKEN';
@Module({
  providers: [{ provide: GOT_TOKEN, useValue: got }, SomethingThatUsesGotService],
})
class SomethingThatUsesGotModule {}

@Injectable()
class SomethingThatUsesGotService {
    constructor (@Inject(GOT_TOKEN) private got: Got) {}

    // implementation
}
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by timvandam** [comment]
I haven't looked into the code very carefully, but it seems that `create(...)` creates a Got instance. A very simple got class could thus be:
```ts
class Got implements xyz {
    constructor (...args: any[]) {
        // @ts-ignore typescript doesnt like these returns, but they work
        return create(...args);
    }
}
```

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I don't think we are interested in making such changes to Got.
