### ISSUE TITLE
isStream not typed in PlainDefaults

### ISSUE THREAD

**Issue by guyellis** [sindresorhus/got#1938]
#### What would you like to discuss?

I see that `isStream` is augmented in this test https://github.com/sindresorhus/got/blob/49c605ca85fa35b7c1b6819219cb7bd5209b4085/benchmark/index.ts#L20 and trying to work out why it's not in PlainDefaults or NormalizedPlainOptions?

...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
It's to narrow the type, because `gotOptions` is used here as well:
https://github.com/sindresorhus/got/blob/49c605ca85fa35b7c1b6819219cb7bd5209b4085/benchmark/index.ts#L76

`as const` works too.
