### ISSUE TITLE
Make the usage example work out of the box

### ISSUE THREAD

**Issue by sschuberth** [sindresorhus/got#194]
Just copying & pasting the usage example does not work because of

    example.js:4
        .then(response => {
         ^

    TypeError: got(...).then is not a function

IMO you should include a promise package into the example code to really make it work out of the box / stand alone.

**Comment by SamVerschueren** [comment]
Upgrade your node version.

**Comment by sschuberth** [comment]
I just downloaded and installed Node today:

    $ node --version
    v4.4.3

Which version do you expect me to use?

**Comment by SamVerschueren** [comment]
Mmmh, then it's not the node version. Promises where added since 0.12. 

What version of `got` are you using?

**Comment by floatdrop** [comment]
```js
const got = require('got');

got('todomvc.com')
    .then(response => {
        console.log(response.body);
        //=> '<!doctype html> ...'
    })
    .catch(error => {
        console.log(error.response.body);
        //=> 'Internal server error ...'
    });
```

@sschuberth example works for both `5.x.` and `6.x`. Please check `got` version and that you do not use caching npm proxies.

**Comment by sschuberth** [comment]
I'm playing around with the [spdx-license-list](https://github.com/sindresorhus/spdx-license-list) project, so I'm using [got version 2.9.2](https://github.com/sindresorhus/spdx-license-list/blob/master/package.json#L40).

**Comment by floatdrop** [comment]
@sschuberth [Promise API](https://github.com/sindresorhus/got/releases/tag/v4.0.0) was introduced in `got` since `4.x`, please update package.

**Comment by sschuberth** [comment]
Done, now I get

    got.stream('todomvc.com').pipe(fs.createWriteStream('index.html'));
                                   ^

    ReferenceError: fs is not defined

Sorry if this is something obvious, I'm completely new to Node.js development.

**Comment by floatdrop** [comment]
@sschuberth this is actually a bug in example. Thanks! Fixed in https://github.com/sindresorhus/got/commit/67ee190881f4ba9c498708dc41c1d71c5b6039a2

**Comment by sschuberth** [comment]
Now I get

    events.js:141
          throw er; // Unhandled 'error' event
          ^
     HTTPError: Response code 405 (Method Not Allowed)

Is that also a bug in the example, or an acceptable error due to an incomplete example?

**Comment by floatdrop** [comment]
@sschuberth I think this is because todomvc.com is not supporting POST method :)

**Comment by sschuberth** [comment]
Makes sense :-) So I agree the example is now good enough. Thanks for your quick responses!
