### ISSUE TITLE
throwHttpErrors: false cause Cannot read property 'request' of undefined 

### ISSUE THREAD

**Issue by GEEKiDoS** [sindresorhus/got#1941]
#### Describe the bug

 - Node.js version:  14.18.1
 - OS & version:  Ubuntu 20.04.3
 
When I use `throwHttpErrors: false` and server returns 500 or 400
#### Actual behavior
This method throws `Cannot read property 'request' of undefined `
...

#### Expected behavior
This method should not throws error and contains response with 500 or 400 status code
...

#### Code to reproduce
```ts
const buffer = await got.post(`http://some.host`, {
    throwHttpErrors: false,
    body: /* some body (mine is buffer) */,
}).buffer();
```

**Comment by szmarczak** [comment]
Can't reproduce:

```js
import got from 'got';

const buffer = await got.post(`https://httpbin.org/anything`, {
    throwHttpErrors: false,
    body: Buffer.from('adsf'),
}).buffer();

console.log(buffer);
```

**Comment by sindresorhus** [comment]
Happy to reopen if you submit a failing test :)

**Comment by tenjaa** [comment]
I stumbled about this issue today.
In my code it fails, but when creating a separate test it just never fails :(

**Comment by tenjaa** [comment]
@sindresorhus I guess for me the issue was, that I tried to use `.json()`.
Maybe the error message could be improved?

```typescript
  test('failing', async () => {
    const client = got.extend({
      prefixUrl: `https://httpbin.org`,
    });
    const result = await client.post('something', {
      throwHttpErrors: false,
      body: Buffer.from('adsf'),
    }).json();
    console.log(result);
  })
```

**Comment by szmarczak** [comment]
Still can't reproduce. What Got version are you using?

**Comment by tenjaa** [comment]
The latest at the time, 12.0.3.
But you are right. I also cannot reproduce it when using an empty project.
So probably something with ts-jest, esbuild, some other dependency, .... I don't know :(
But as just not using `.json()` solves it for me I probably won't investigate any further.
