### ISSUE TITLE
Incorrect Typescript types for retry and timeout options in got@12.0.0

### ISSUE THREAD

**Issue by lynxtaa** [sindresorhus/got#1947]
#### Describe the bug

 - Node.js version: 
 - OS & version: 

In got@12.0.0 Typescript is unhappy when I provide `retry` and `timeout` options as numbers 

#### Actual behavior

<img width="620" alt="Снимок экрана 2021-12-10 204126" src="https://user-images.githubusercontent.com/22496946/145618239-7975c38a-960a-4d77-90c9-fd72490afb96.png">

<img width="536" alt="Снимок экрана 2021-12-10 204145" src="https://user-images.githubusercontent.com/22496946/145618179-99165079-3719-46c1-a743-b53c62cf1c57.png">

#### Expected behavior

Expect no typescript errors

#### Code to reproduce

```ts
import got from 'got'

await got('', {
  retry: 0,
  timeout: 10_000,
})
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/releases/tag/v12.0.0
