### ISSUE TITLE
Got 12 throws Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by gregbarcza** [sindresorhus/got#1949]
#### Describe the bug

 - Node.js version: 16
 - OS & version: Mac / Big Sur
 - got: 12.0.0

#### Actual behavior
After upgrading to got 12 I've got the following error:
`Error [ERR_REQUIRE_ESM]: require() of ES Module`

```
/Users/gergobarcza/Projects/advent-of-code/got-error/index.js:6
const got_1 = __importDefault(require("got"));
                              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/gergobarcza/Projects/advent-of-code/got-error/node_modules/got/dist/source/index.js from /Users/gergobarcza/Projects/advent-of-code/got-error/index.js not supported.
Instead change the require of /Users/gergobarcza/Projects/advent-of-code/got-error/node_modules/got/dist/source/index.js in /Users/gergobarcza/Projects/advent-of-code/got-error/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/gergobarcza/Projects/advent-of-code/got-error/index.js:6:31) {
  code: 'ERR_REQUIRE_ESM'
}
```

#### Code to reproduce

https://gist.github.com/gregbarcza/e819ff1c968df279eccaf53e6cf66d64

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Please read the release notes.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by gregbarcza** [comment]
Hello @sindresorhus, thanks for the quick reply!
I think it would be helpful to highlight this in the Readme for now.
