### ISSUE TITLE
"Error: callback() can only be called once" crashes the program

### ISSUE THREAD

**Issue by dragonfish-au** [sindresorhus/got#195]
I have a special test case. When using "got" to download large files (so that I can have enough time to unplug the cable),  after about 5-10 seconds, I have the following error. Problem is, I'm unable to catch this error using try/catch or error from callback. 

The error itself is something like "getaddrinfo ENOENT". 

Any idea to capture the exception?

```js
Error: callback() can only be called once.
    at onetime (/<path>/node_modules/onetime/index.js:15:11)
    at /<path>/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/<path>/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/<path>/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at afterWrite (/<path>/node_modules/readable-stream/lib/_stream_writable.js:361:3)
    at nextTickCallbackWithManyArgs (node.js:464:18)
    at process._tickCallback (node.js:362:17)
```

**Comment by floatdrop** [comment]
You can't capture exceptions with `try...catch` in callbacks - you can only check for `error` argument in callback (callback will be called either way).

`try...catch` will work thou, if you using `async/await` or `yield` with [`co`](http://npmjs.com/co) for flow control:

```js
const co = require('co');

co(function * () {
  try {
      yield got('google.com');
  } catch (err) {
      // Oops
  }
});
```

**Comment by dragonfish-au** [comment]
Yes I know try/catch is not supposed for error handling of async functions, but depends on how the code is written, sometimes it make sense only in rare scenarios.

This issue is more about the library will crash the program in a scenario mentioned above, and this kind of error cannot be captured by callback.

**Comment by floatdrop** [comment]
@dragonfish-au from stacktrace I see, that error comes not from `got`, but from `download` package (`at onetime (/<path>/node_modules/onetime/index.js:15:11)`). As far as I know – all errors from `got` can be captured either in Promise or `error` event in stream mode (unless version of `got` a bit old).

Can you provide example code to reproduce it?
