### ISSUE TITLE
[ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/dendi/Desktop/works/nest/nuber-eats-backend/node_modules/got/dist/source/index.js

### ISSUE THREAD

**Issue by scott8013** [sindresorhus/got#1954]
#### Describe the bug

 - Node.js version: 
 - OS & version: 

#### Actual behavior

...

#### Expected behavior

...

#### Code to reproduce

```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.
![image](https://user-images.githubusercontent.com/26688426/147036257-21e10527-8a4d-4f64-9eaa-dbcea658bb5e.png)
![image](https://user-images.githubusercontent.com/26688426/147036347-e5ff49d6-bbff-4e56-99b5-baa9418d1f2b.png)

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/147039964-a94acb63-464c-40a7-a092-269dcaa87449.png)

https://github.com/sindresorhus/got/releases/tag/v12.0.0

**Comment by szmarczak** [comment]
@sindresorhus I wouldn't mind locking issues for another week 🤔

**Comment by sindresorhus** [comment]
Done
