### ISSUE TITLE
How to check response status code before creating a write stream

### ISSUE THREAD

**Issue by higoka** [sindresorhus/got#1955]
#### What would you like to discuss?

Im trying to download images from another server using `got.stream()`. I noticed that it creates empty files if the image does not exist on the other server. I tried to check for a `200` status code on the response before creating a write stream and piping the stream to it. However the `response.status` does not exist so i checked the docs about `got.stream()` but i couldn't find anything to check for a successful response first.

How can i avoid creating empty files? This is my code (simplified):

```js
import got from 'got'
import { pipeline } from 'stream/promises'
import { createWriteStream } from 'fs'

async function main () {
  const readStream = got.stream('https://example.com/image.png')

  // how to exit early here?
  if (readStream.status !== 200) {
    return
  }

  // create file and save response
  await pipeline(readStream, createWriteStream('image.png'))
}

main()
```

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
It emits a `response` event. There's missing docs.

**Comment by higoka** [comment]
@szmarczak I got it working now but i don't know if this is the correct way or if there is a better solution to this? This is my code: 
```js
import got from 'got'
import { pipeline } from 'stream/promises'
import { createWriteStream } from 'fs'

async function main () {
  const readStream = got.stream('https://www.example.com/image.png', { throwHttpErrors: false })

  readStream.on('response', async (res) => {
    if (res.statusCode !== 200) {
      console.log('failed')
      return
    }

    await pipeline(readStream, createWriteStream('image.png'))
    console.log('success')
  })
}

main()
```

**Comment by szmarczak** [comment]
Before returning after logging failed you want to destroy the stream to prevent hanging resources :) Then it's correct. Unfortunately there's no easier way to do this, this will be improved in another major release.

**Comment by higoka** [comment]
Awesome, thanks!

**Comment by dedwardstech** [comment]
I've added the response event to the stream docs. I included the code snippet from above and mentioned the part about destroying the read stream to prevent hanging resources.

**Comment by higoka** [comment]
Awesome!
