### ISSUE TITLE
Error:  Must use import to load ES Module

### ISSUE THREAD

**Issue by pberlinets** [sindresorhus/got#1956]
#### After update GOT library to version 12.0.0 I've got an error:
```
Error:  Must use import to load ES Module: .../node_modules/got/dist/source/index.js
require() of ES modules is not supported.
require() of .../node_modules/got/dist/source/index.js from .../CompaniesPage.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from .../node_modules/got/package.json.
```

 - Node.js version: v14.18.2
 - OS & version: MacOS Monterey 12.0.1 (21A559)

Actually, I'm using proper import and don't realize where the problem is
```js
import got from "got";
```

**Comment by sindresorhus** [comment]
Please read the release notes. Issues like these are usually caused by your build tool incorrectly transpiling dependencies like Got to CommonJS.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
