### ISSUE TITLE
It seems that `got` does not compatible with `nock` as of version 12.

### ISSUE THREAD

**Issue by huturen** [sindresorhus/got#1960]
#### It seems that `got` does not compatible with `nock` as of version 12.

 - Node.js version: v14.17.6
 - OS & version: ^12.0.0

#### Code to reproduce

```js
import got from 'got';
import nock from 'nock';

nock('https://jsonplaceholder.typicode.com')
  .get('/todos/1')
  .reply(200, {
    id: 1,
    title: 'mock content'
  })

got.get('https://jsonplaceholder.typicode.com/todos/1').then(res => {
  console.log('res body:', res.body);
});

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by huturen** [comment]
I've submitted a pull request to fix it:

https://github.com/sindresorhus/got/pull/1959

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/releases/tag/v12.0.1
