### ISSUE TITLE
 SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mrwolny** [sindresorhus/got#1961]
#### Describe the bug

 - Node.js version: 14.17.4
 - OS & version: macOS Big Sur

When I use `got@12.0.1` in TypeScript project importing library like this:
```typescript
import got from 'got';
```

results in error: 
```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import create from './create.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I'm able to use this import syntax in `got@11.8.3`

#### Actual behavior

Error: `Unable to resolve path to module 'got'`

#### Expected behavior

I should be able to import got in TS files.

#### Code to reproduce

Install `got@12.0.1` in TS project. 

Try to import `got` into your module. 

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
You must be doing something wrong. It works correctly here.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/got/releases/tag/v12.0.0

**Comment by yrue** [comment]
workaround with `transformIgnorePatterns` in jest.config.js as below
```
  transformIgnorePatterns: [
    "/node_modules/(?!(got|p-cancelable|@szmarczak|lowercase-keys)/)", 
  ],
```

**Comment by elazar** [comment]
I'm running into this issue as well.

Node: 16.14.2
OS: macOS Monterey 12.2.1 (21D62)
got: 12.0.4

Unfortunately, the `transformIgnorePatterns` workaround above doesn't seem to affect the error.

A bit more context: this is happening inside a [Jest](https://jestjs.io/) test suite where the class under test imports `got` as shown in the output below.

```
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/node/middleman-node/node_modules/got/dist/source/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import create from './create.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    >  8 | import got from "got";
         | ^

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
```

Some other package dependency details that may be relevant:

jest: 27.5.1
jest-runtime: 27.5.1
ts-jest: 27.1.4
ts-node: 10.7.0
typescript: 4.6.3

**Comment by brettswift** [comment]
If someone else runs into this, one thing that helped me get around this,  without using the implicit imports, (ie `import got from 'got'` was this: 

```
import * as got from 'got';

const theGot = got.default;

theGot.post() //ect.
```

Another way around with `tsconfig.json` is: 

```
~
    "allowSyntheticDefaultImports": true,
~
```

**Comment by szmarczak** [comment]
> "please do not use got with jest as jest doesn't fully support esm" means that we'll be moving away from got

Jest is old and flawed, cannot print circular structures and fails to detect open handles properly and has many more issues. We won't be officially supporting such outdated tools, as there's no point in having messy code. Thanks for understanding.

> Much easier to do that than to change a test library for an entire project.

True. However we are still staying with ECMAScript Modules approach.
