### ISSUE TITLE
Add Typescript Definitions

### ISSUE THREAD

**Issue by cyounkins** [sindresorhus/got#197]
If I write Typescript Definitions, will they be merged?

Relevant: 
https://github.com/typings/typings/issues/322
https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by floatdrop** [comment]
@cyounkins yes, but they should be updated from time to time.

**Comment by SamVerschueren** [comment]
Or submit them to `DefinitelyTyped`.

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
