### ISSUE TITLE
polling with retry

### ISSUE THREAD

**Issue by rifler** [sindresorhus/got#1974]
#### What would you like to discuss?
got@11.8.3

I need to realise "polling" logic - server answers with 200 status code, but if `response.data.some_field === 'pending'` I should retry. If `some_field` has other value - it is OK and should successfully end request

First i tried:
```ts
got.get('http://some-json-endpoint.com', {
    retry: 20,
    responseType: 'json',
    hooks: {
        afterResponse: [
            (response, retry) => {
                if (response.status === 200 && response.data.some_field === 'pending') {
                    return retry({})
                }
                
                return response
            }
        ],
    }
})
```

For example you can simplify `afterResponse` hook to `(response, retry) => retry({})`
In this case `afterResponse` called only once

After that I tried to add `200` to `retry.statusCodes`, but nothing changed.
After that instead of `return retry({})` I made `throw new Error()` and it seems to work

What is canonical way to make polling in got@11.8.3 ?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
I don't know what's the unexpected behavior so I'm *guessing* it doesn't work. I'm not able to reproduce this:

```js
const http = require('http');
const got = require('got');

let first = true;

http
  .createServer((request, response) => {
    if (first) {
      response.end('"bad"');
      first = false;
      return;
    }

    response.end('"good"');
  })
  .listen(8000)
  .unref();

(async () => {
  const r = await got('http://localhost:8000', {
    responseType: 'json',
    hooks: {
      afterResponse: [
        (response, retry) => {
          if (response.body === 'bad') {
            return retry();
          }
          return response;
        },
      ],
    },
  });

  console.log(r.body);
})();
```
