### ISSUE TITLE
If CJS is no longer supported, it would be nice to mention in README

### ISSUE THREAD

**Issue by mildsunrise** [sindresorhus/got#1976]
Hi! Apologies if there was already an issue for this, I didn't find any.
Just found out Got only provides an ESM version, but no CJS version, which makes it incompatible with CommonJS projects.
After digging through this repo I found [a Gist from sindersorhus](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) confirming that the package did indeed remove support for CommonJS.

A Gist is nice, but a lack of support like this should IMHO be mentioned clearly in the README as it can be frustrating to users (especially newbies).

Something like this before the 'Install' section would be nice:

> **Warning:** This package no longer provides a CJS module. If your project uses CommonJS, you'll have to [convert to ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), or use the dynamic `import()` function. Please don't open issues for questions regarding CommonJS / ESM.

WDYT?

**Comment by mildsunrise** [comment]
A warning like this would also be useful for experienced developers.
If someone is making a library that needs to provide CommonJS support, this immediately rules out Got.
It would be nice for the author to know beforehand so they can look for alternatives.

**Comment by sindresorhus** [comment]
Thanks for the suggestion. Done: https://github.com/sindresorhus/got/commit/c8902ba3420b2def5aab68b3f889039469d0b1a8

**Comment by mildsunrise** [comment]
I just saw there was a pinned issue :pensive:, should've commented there.
Thank you anyway!

**Comment by isaachinman** [comment]
Hello all. I've created a util to convert ESM-only packages to CJS, for those who need it. This is still very much a work in progress, so please open an issue [on the repository](https://github.com/isaachinman/cjs-exporter) with any feedback.

This package (`got@12.5.3`) can be installed as CJS via `@cjs-exporter/got`.
