### ISSUE TITLE
Consider allowing single hooks.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [sindresorhus/got#1979]
#### What problem are you trying to solve?

Currently, hooks must be passed in as arrays.

```ts
const instance = got.extend({
  hooks: {
    init: [
      (plain, options) => {
        // Do something.
      }
    ],
    beforeRedirect: [
      (options, plainResponse) => {
        // Do something.
      }
    ],
    beforeRequest: [
      options => {
        // Do something.
      },
      options => {
        // Do something else.
      }
    ],
  }
});
```

It's not particularly burdensome, but it's a bit more verbose than it needs to be.

#### Describe the feature

Ideally, hooks could be passed in without wrapping them in an array.

```ts
const instance = got.extend({
  hooks: {
    // No array.
    init: (plain, options) => {
      // Do something.
    },
    // Also acceptable.
    beforeRedirect(options, plainResponse) {
      // Do something.
    },
    // Still works.
    beforeRequest: [
      options => {
        // Do something.
      },
      options => {
        // Do something else.
      }
    ],
  }
});
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Makes sense to me. Most users only use a single hook for each type.

**Comment by TommyDew42** [comment]
This feature would make got even more user-friendly! Can I pick this up?

**Comment by szmarczak** [comment]
@TommyDew42 There's no PR for this currently, so I guess you're free to pick this up.

**Comment by szmarczak** [comment]
All you need is `npm install` and `npm test` (sometimes `npx xo` for manual linting).

**Comment by sindresorhus** [comment]
Turned out this was not worth the complexity it would bring. See: https://github.com/sindresorhus/got/pull/2053#issuecomment-1172926091
