### ISSUE TITLE
Zendesk API auth works everywhere but on `got`

### ISSUE THREAD

**Issue by baptisteArno** [sindresorhus/got#1983]
#### Describe the bug
I'm trying to execute an API request that works everywhere else (on Postman and other HTTP clients), it doesn't work with `got`

#### Actual behavior
The Zendesk API returns `{"error": "Couldn't authenticate you"}`

#### Expected behavior
To return the newly created ticket

#### Code to reproduce
(I've generated the provided token for you to easily test)

```js
const response = await got(
      'https://typebothelp.zendesk.com/api/v2/tickets',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization:
            'Basic baptiste@typebot.io/token:8Vs665J0Y1WGz1jmz2kYUwI8LIQiNuzr5d1BGwbV',
        },
        json: {
          ticket: {
            subject: 'Hello',
            comment: { body: 'Some question' },
            requester: {
              locale_id: 8,
              name: 'Pablo',
              email: 'pablito@example.org',
            },
          },
        },
      }
    )
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Basic authentication should be Base64 encoded. Check out the [`username / password` options](https://github.com/sindresorhus/got/blob/6eb0fd3a2ccb9545ccc662f44fa1adf7d7cc4da8/documentation/2-options.md#username).

**Comment by nexdrew** [comment]
@baptisteArno Instead of this:

```js
{
  headers: {
    Authorization: 'Basic baptiste@typebot.io/token:8Vs665J0Y1WGz1jmz2kYUwI8LIQiNuzr5d1BGwbV'
  }
}
```

try this:

```js
{
  username: 'baptiste@typebot.io/token',
  password: '8Vs665J0Y1WGz1jmz2kYUwI8LIQiNuzr5d1BGwbV'
}
```

or this:

```js
{
  headers: {
    Authorization: 'Basic ' + Buffer.from('baptiste@typebot.io/token:8Vs665J0Y1WGz1jmz2kYUwI8LIQiNuzr5d1BGwbV', 'utf8').toString('base64')
  }
}
```

**Comment by baptisteArno** [comment]
Thank you for the great help guys 💙
