### ISSUE TITLE
Will 11.x branch be kept up-to-date alongside 12.x?

### ISSUE THREAD

**Issue by paulrutter** [sindresorhus/got#1984]
Since got 12.x is now ESM only, and it's currently hard for us to move to a full ESM based application, i was wondering if bug fixes and security updates will remain to be backported to the 11.x branch?

I have read the README stating that for this case a dynamic import can be used, but that requires the CJS based application to use `got` in an asynchronous way. This is fine for most cases, although it's hard when using streams, as that would change the API from returning a `Stream` into `Promise<Stream>`, thus making it backwards incompatible.

Any thoughts on this?

**Comment by sindresorhus** [comment]
Security fixes will be back-ported. Bug fixes will be back-ported if someone does the work, however, v11 has been stable for a long time, and if there were any critical bugs, I think they would have been reported and fixed by now.

**Comment by paulrutter** [comment]
Ok, thanks for clarifying!
