### ISSUE TITLE
Usage with Typescript

### ISSUE THREAD

**Issue by intensite** [sindresorhus/got#1986]
#### Describe the bug

 - Node.js version: v17.1.0
 - OS & version:  Windows 10

Can't seem to be able to import got in Typescript.  
Probably not a bug but a documentation issue.

#### Actual behavior

I try to use got with Typescript and I can't import OR require "got": "^12.0.1"
I am using the Moleculer.js Microservices Framework

When I use:  
`import got from 'got';`

I get: 
``` 
require() of ES Module C:\Projects\experiments\ryder_speedtest\ryder_speedtest\node_modules\got\dist\source\index.js from C:\Projects\experiments\ryder_speedtest\ryder_speedtest\services\geek.service.ts not supported.
Instead change the require of index.js in C:\Projects\experiments\ryder_speedtest\ryder_speedtest\services\geek.service.ts to a dynamic import() which is available in all CommonJS modules.
```

If I try:
`const { got } = require('got');`

The result is the same :-/

#### Checklist

- [ X] I have read the documentation.
- [ X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/issues/1789
