### ISSUE TITLE
The encoding option is not working when combined with responseType: 'json'

### ISSUE THREAD

**Issue by baptistemarchand** [sindresorhus/got#1988]
#### Describe the bug

 - Node.js version: v14.18.3
 - OS & version: OSX 12.1

The `encoding` option is not working when combined with `responseType: 'json'`.

#### Actual behavior

I created a minimal repro repo : https://github.com/baptistemarchand/got-encoding-repro/blob/main/index.mjs
```javascript
  const res1 = await got('https://latin1-api.vercel.app/', {
    encoding: 'latin1',
    responseType: 'json',
  })
  // Outputs: {data: "?"} 
  console.log('res1', res1.body)

  const res2 = await got('https://latin1-api.vercel.app/', {
    encoding: 'latin1',
  })
  // Outputs: {data: "é"} 
  console.log('res2', JSON.parse(res2.body))
```
What it does :
I have a dummy api that returns a JSON with the latin1 encoding : https://latin1-api.vercel.app/.
I call it twice with `got` :
- once with `responseType: 'json'` => the encoding seems to be ignored
- once without `responseType: 'json'` and instead doing a `JSON.parse` manually => encoding working as expected
Here is the result : 
![image](https://user-images.githubusercontent.com/325095/155523138-300a379f-ad1e-401d-bfc8-eef3b79e7bce.png)

#### Expected behavior

I expected the result of both console.log to be the same. Like this :
```
res1 { data: 'é' }
res2 { data: 'é' }
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Good catch!

https://github.com/sindresorhus/got/blob/c8902ba3420b2def5aab68b3f889039469d0b1a8/source/core/response.ts#L141

should have an `encoding` argument like this one:

https://github.com/sindresorhus/got/blob/c8902ba3420b2def5aab68b3f889039469d0b1a8/source/core/response.ts#L137

Would you be up to sending a fix along with a test for this?

**Comment by baptistemarchand** [comment]
@szmarczak I cloned the repo and ran `npm install` and got the following TypeScript error
![image](https://user-images.githubusercontent.com/325095/155998511-55158537-978a-4bc3-a681-4a6281a75dab.png)

I have node `v14.18.3`.
Should I open a new issue for that?

**Comment by szmarczak** [comment]
Yes please.
