### ISSUE TITLE
How to implement retries for 503, 504 and other status codes using retries option.

### ISSUE THREAD

**Issue by satazor** [sindresorhus/got#199]
I want to retry on network errors but also on some service errors like 503 and 504.

AFAIK the `opts.retries` function is only called for request errors. For http errors it isn't called. This means that I can't create custom retry logic using `retries` options for this use-case. It seems I have to do ALL the retry logic outside of got for this to work.

Is this intended? Am I missing something?

**Comment by floatdrop** [comment]
@satazor yes, this is how things work now. As readme says:

> Number of request retries when __network errors__ happens.

Retries will be applied only when network error happened. You can read [this thread](https://github.com/sindresorhus/got/issues/98) about retry feature.

**Comment by satazor** [comment]
Doing a got wrapper that deals with retries the wait I want is easy except when wrapping `got.stream`. That will be harder to do since I don't have access to the internal event emitter. In this case I have to do it in the upper surface of the code.

**Comment by floatdrop** [comment]
@satazor you can look at [this comment](https://github.com/sindresorhus/got/issues/181#issuecomment-224694972) about caching streams (esp. https://github.com/jamestalmage/caching-stream) – it could fit your needs.

Closing this for now, since it can be done in wrapper.
