### ISSUE TITLE
Http version 1.0

### ISSUE THREAD

**Issue by rangav** [sindresorhus/got#1992]
#### What would you like to discuss?

Hi, is it possible to use http version 1.0, I can't find in documentation 
...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Got under the hood uses the native HTTP client provided by Node, so yes.

**Comment by rangav** [comment]
Hi @szmarczak thanks for the response.

How to tell got to use http 1.0? Instead of 1.1

**Comment by szmarczak** [comment]
The server should reply in 1.0.

**Comment by rangav** [comment]
Thanks got it
