### ISSUE TITLE
got doesn't seem to throw an error for domains with revoked certificates

### ISSUE THREAD

**Issue by rozenmd** [sindresorhus/got#1994]
#### Describe the bug

 - Node.js version: 16.13.1
 - OS & version: macOS 10.15.7
 - `got` version: 11.8.3

#### Actual behavior

Running
```js
// this is an actual URL from https://github.com/chromium/badssl.com
await got("https://revoked.badssl.com/", {https: { rejectUnauthorized: true }})
``` 
successfully fetches the page

#### Expected behavior

Running
```js
// this is an actual URL from https://github.com/chromium/badssl.com
await got("https://revoked.badssl.com/", {https: { rejectUnauthorized: true }})
``` 
should throw some sort of error, as the certificate is revoked, and `rejectUnauthorized` is enabled. Chrome 98.0.4758.102 throws `NET::ERR_CERT_REVOKED` for this URL.

#### Code to reproduce

see actual vs expected behaviour

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Got uses the same TLS config the same as Node.

```js
https.get('https://revoked.badssl.com/', r => console.log(r.headers))
```

https://stackoverflow.com/questions/46636179/nodejs-ssl-validation-incorrect

**Comment by szmarczak** [comment]
https://github.com/nodejs/node/issues/16338
