### ISSUE TITLE
npm install fails on a fresh clone

### ISSUE THREAD

**Issue by baptistemarchand** [sindresorhus/got#1997]
#### Describe the bug

 - Node.js version: v14.18.3
 - OS & version: OSX 12.1

npm install fails on a fresh clone.

#### Actual behavior

![image](https://user-images.githubusercontent.com/325095/156013338-74c30011-cb33-4b2b-b711-75988eb3e394.png)

#### Expected behavior

No errors.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Cannot reproduce (did fresh install):

```
~/dev/oss/got main
❯ npm run build

> got@12.0.1 build
> del-cli dist && tsc
```

**Comment by baptistemarchand** [comment]
> Cannot reproduce (did fresh install):
> 
> ```
> ~/dev/oss/got main
> ❯ npm run build
> 
> > got@12.0.1 build
> > del-cli dist && tsc
> ```

What version of node are you using?

**Comment by baptistemarchand** [comment]
The CI has the same error : https://github.com/sindresorhus/got/runs/5361889511?check_suite_focus=true

**Comment by szmarczak** [comment]
@sindresorhus This is due to a TypeScript update. I've pushed the fix to main but it seems CI for some reason doesn't include it. @baptistemarchand can you rebase and force push?

**Comment by baptistemarchand** [comment]
Fixed by https://github.com/sindresorhus/got/commit/dcbea9cbab077d4fd77f319c5ba44382de4cae87
