### ISSUE TITLE
Mutable global defaults

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/got#2003]
#### What problem are you trying to solve?

A library I uses uses `got` with vanilla settings. I would like to add hooks to the calls made in that library.

#### Describe the feature

Keep `mutableDefaults` as false for `got.extend`, but as a special case for the default-exported global instance, set it to `true`.

```js
// npm:some-library - not controlled by us
import got from 'got'

export const fetchThings = () => {
  return got('https://example.com/api/things') // note, no logging, no user-agent header, etc. etc.
}
```

```js
// our code
import got from 'got'
import {fetchThings} from 'some-library'

got.defaults.options.hooks = {
  ...got.defaults.options.hooks,
  beforeRequest: [req => {
    req.headers['user-agent'] = 'abcde'
  }]
}

export default async () => {
  const things = await fetchThings()
}
```

I don't _think_ there's a workaround other than proxying `require`/`import` or something.

Alternative: first require setting `got.defaults.mutableDefaults = true` to make sure people can't do it without acknowledging the risks (?) first.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
`got.extend` is the way to go.

**Comment by mmkal** [comment]
@szmarczak how do I use got.extend in this case? The library, outside of my control, is using the default export.

**Comment by szmarczak** [comment]
Then you'd have to fork it. It's not possible to modify something you don't have access to (applies to all packages, not just Got).

**Comment by mmkal** [comment]
I do have access to it - it's the default export of `got`. It's only not possible because `mutableDefaults` is set to `false` for the default client. That's why I made the issue.
