### ISSUE TITLE
Documentation with require("got")

### ISSUE THREAD

**Issue by caionakai** [sindresorhus/got#2007]
#### What would you like to discuss?

This file: https://github.com/sindresorhus/got/blob/main/documentation/tips.md has an example that uses `require("got")`.

Isn't better to change the way got is being imported from the documentation since the latest release do not support `require` anymore?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
That's intentional. Electron does not yet support ESM.

https://github.com/sindresorhus/got/commit/d95ceeafb16f306e11f5d7251a82ba073252cbee

**Comment by caionakai** [comment]
Oh I see, thanks!
