### ISSUE TITLE
TypeError: The payload has been already provided on node 17

### ISSUE THREAD

**Issue by bangbang93** [sindresorhus/got#2009]
#### Describe the bug

 - Node.js version: 17.7.1 & 17.5.0 & 17.4.0
 - OS & version: Manjaro

#### Actual behavior
```
TypeError: The payload has been already provided
    at Request.onLockedWrite (file:///home/bangbang93/Development/temp/node_modules/got/dist/source/core/index.js:497:19)
    at ReadStream.<anonymous> (node:internal/streams/pipeline:323:31)
    at Object.onceWrapper (node:events:641:28)
    at ReadStream.emit (node:events:539:35)
    at ReadStream.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1342:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
works on node 16.14.0
tests fails on node 17
```
  Uncaught exception in test/progress.ts

  TypeError: The payload has been already provided

  › Request.onLockedWrite (file://source/core/index.ts:557:10)



  Uncaught exception in test/progress.ts

  TypeError: The payload has been already provided

  › Request.onLockedWrite (file://source/core/index.ts:557:10)



  Uncaught exception in test/stream.ts

  TypeError: The payload has been already provided

  › Request.onLockedWrite (file://source/core/index.ts:557:10)

  ─

  525 tests passed
  3 known failures
  4 tests skipped
  3 uncaught exceptions

```

#### Expected behavior
post with stream

#### Code to reproduce

```typescript
import {createReadStream} from "fs";
import {fileURLToPath} from "url";
import {pipeline} from "stream/promises";
import got from "got";

const stream = createReadStream(fileURLToPath(import.meta.url))
await pipeline(stream, got.stream.post('https://example.com'))
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
There are some breaking changes in 17 which we have not addressed yet. Please stick by 16 for now.

**Comment by SudhirRamaniOD** [comment]
Is this expected behavior with NodeJS v17 and Got v12.0.3 every time?

**Comment by szmarczak** [comment]
No, this is not expected behavior. Please note that Node.js 17 is a breaking release. This will be fixed in the near future.

**Comment by SudhirRamaniOD** [comment]
Is there any working sample reference for uploading stream in chunks using got and pipe?

**Comment by szmarczak** [comment]
Fixed in https://github.com/sindresorhus/got/releases/tag/v12.0.4

**Comment by pwespi** [comment]
@szmarczak I have this issue in v11. Any chance you could take a look at https://github.com/sindresorhus/got/pull/2236? Thanks for your great work!
