### ISSUE TITLE
Add original error property

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#2010]
#### What problem are you trying to solve?

@szmarczak asked me to create a separate issue (https://github.com/sindresorhus/got/issues/1865#issuecomment-993725043).

Could you add a property on the `got` Error object like `original` that stores the original Error if there was one for example from `socks-proxy-agent`? It would really help with more involved error handling scenarios.

#### Describe the feature

More background is at https://github.com/sindresorhus/got/issues/1865.

The `cause` property could be used https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#differentiate_between_similar_errors since it is standard.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Yeah, we should use `cause` for all our errors. I guess we could use https://github.com/voxpelli/pony-cause for now until we target Node.js 16.

**Comment by rightaway** [comment]
@sindresorhus If the original error goes under a `cause` property in Node less than 16 without using a package like that will it cause a problem? Isn't it backwards compatible to just add a new property?

**Comment by sindresorhus** [comment]
If we just add a new property, it won't be included in the `.stack`.

**Comment by rightaway** [comment]
If nothing would break for people using Node 15 then maybe `cause` could be added without that package. Node 16 get the better `stack` and Node 15 things work as before.
