### ISSUE TITLE
does `json` option support all json values?

### ISSUE THREAD

**Issue by samzilverberg** [sindresorhus/got#2013]
I was trying to use GOT (latest) with Typescript to write some "niche" tests that send some json that probably only people trying to break your server would use.

values such as: `true`, `false`, `null`, `"123"`, `1`, `[1,2,3]`.

But noticed that GOT only supports `Record<string, any>`.

here's the source of it:

https://github.com/sindresorhus/got/blob/d95ceeafb16f306e11f5d7251a82ba073252cbee/source/core/options.ts#L1356-L1365

This means only objects and array can be passed in.
Shouldnt `json` support all valid json values?

I tried looking up documenation or issues to understand why this limitation exists but didn't find any :(

If this limitation is here to stay, then is there a way to use GOT to send the other json values?

**Comment by szmarczak** [comment]
In that case value should be typed as `any`.

**Comment by samzilverberg** [comment]
@szmarczak dya mean the type for the `set json(...)` function?

it can be typed better than `any` :)  , for example:
```
set json(value: Record<string, any> | number | string | boolean | undefined) { 
```

**Comment by szmarczak** [comment]
https://github.com/microsoft/TypeScript/blob/45c1e5880936a56b61071d14c929674e6f595c93/lib/lib.es5.d.ts#L1066

TypeScript ships `JSON.stringify` with `any` so let's stick with that.

**Comment by samzilverberg** [comment]
@szmarczak i made the proposed `any` change in https://github.com/sindresorhus/got/pull/2015 

I wanted to add some tests but wasn't sure which test file would be most appropriate.
I didn't find any exising tests of what `json` option should and shouldn't accept.

**Comment by samzilverberg** [comment]
@szmarczak i'm closing this issue.

note that sindresorhus suggested to use unknown for the return value of `get json`

https://github.com/sindresorhus/got/pull/2015#discussion_r832804667

i can confirm that using `unknown` instead of `any` compiles and all tests run (on my machine).
