### ISSUE TITLE
Timeout option not working as expected

### ISSUE THREAD

**Issue by krave1986** [sindresorhus/got#2014]
#### Describe the bug

When I try to send a request to a unavailable service to try out the [`timeout` option](https://github.com/sindresorhus/got/tree/0da732f4650c398f3b2fea672f8916e6c7004c8f#timeout), `got` throws error after almost same period no matter what timeout value I set to it.

 - Node.js version: v16.14.0
 - OS & version: Ubuntu 20.04.4 LTS
 - got version: 11.8.3

#### Actual behavior
If I set timeout to 500ms, request should finish within 500ms no matter success or failure.

#### Expected behavior
It takes around 3000 ms to finish the request.

#### Code to reproduce

```js
const got = require('got')

const run = async (timeout = 500) => {
    const start = performance.now()

    got('http://localhost:3333/1', {
        timeout
    }).catch(
        () => {
            console.log(`Set timeout as ${timeout} and the result is ${performance.now() - start}ms`);
        }
    )
}

run()
run(1000)
run(4000)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
What's the result with Got v12?

**Comment by szmarczak** [comment]
If you log `error.request.timings` you'll see that the request is aborted immediately.

https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md#retry

**Comment by krave1986** [comment]
`error.timings` and `error.request.timings` look identical.
Update the cache handler to
```
            const { error, start } = err.timings
            console.log(`Time consumed on server side: ${error - start}`);
```
Output:
> Time consumed on server side: 1

Now I can see that the request is aborted immediately as you said.
Then the only thing left which postpones the error being thrown should be the retry mechanism.

**Comment by krave1986** [comment]
After digging into the document, I feel that the retry mechanism is not trivial in my scenario.

Scenario: We do not care much about how many times to retry if error happens. We care about user can be notified with request result or failure notification within a relatively short period, say 1.25 seconds. For sure, we need to ambiguously retry some times if error occurs.

It seems that I need to use the `calculateDelay` option to achieve my goal.
Here is the final code I can figure out by myself right now.

```
import got from "got";

const throwIfFailureWithin = async (period = 5000, step = 1000) => {
    const start = performance.now()

    got('http://localhost:3333/1', {
        retry: {
            calculateDelay: function ({ attemptCount }) {
                const current = performance.now()
                const delay = (current - start + step > period) ? 0 : step
                console.log(period, attemptCount, current - start);
                return delay
            },
        },
    }).catch(
        (err) => {
            console.log(`Set timeout as ${period} and the result is ${performance.now() - start}ms`);
        }
    )
}

throwIfFailureWithin(1250, 600)
```

Any suggestions will be appreciated.
