### ISSUE TITLE
responseType json unknown

### ISSUE THREAD

**Issue by productdevbook** [sindresorhus/got#2021]
![image](https://user-images.githubusercontent.com/38668796/161563306-f658ae22-ebd8-4cb0-acab-d6622383e004.png)

2. problem ts and dont see json

![image](https://user-images.githubusercontent.com/38668796/161563398-2ea6fe06-8f37-4c5b-a4a8-456f4e31f261.png)

**Comment by szmarczak** [comment]
Can you set up an example repo please?

**Comment by szmarczak** [comment]
Also please fill out the issue template properly, it helps a lot.

**Comment by woacademy** [comment]
test
