### ISSUE TITLE
How do you go about reading non-2xx/3xx response bodies?

### ISSUE THREAD

**Issue by RavenHursT** [sindresorhus/got#2024]
#### What would you like to discuss?
I ran into a problem while using a library that's using `got` for making server-side requests:

https://github.com/MONEI/Shopify-api-node/issues/534

It appears that `got`, if it receives a response w/ a non-2xx/3xx status code, that it just packages up a custom `HTTPError` object and throws it.

The problem w/ that approach is that it doesn't seem like there's any way to get ahold of the response's body bytes (assuming there are any).  It seems like all that's thrown are essentially the code and the message.  Any `catch` block will not have any way to access the body of the response.

In my case, the APIs being called, when errors are sent via 4xx responses, the body of those responses comes w/ very important data to help in debugging usage of the APIs in question.

Am I missing something?  Is there some other way to get ahold of the body so that the stream can be read and parsed?
...

#### Checklist

- [ X] I have read the documentation.

**Comment by RavenHursT** [comment]
Ok.. so the `Response` object is indeed there.  Wish it had been more apparent that this was the case besides a comment buried in the source code.

Closing.

**Comment by RavenHursT** [comment]
Apparently it is possible to get ahold of the response in question.. just had to dig through `got`'s source code to find a comment buried there.  Closing.

https://github.com/sindresorhus/got/issues/2024#issuecomment-1095862934

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/8-errors.md#errors
