### ISSUE TITLE
Progress has been completed, but the file has not been uploaded

### ISSUE THREAD

**Issue by chenhb23** [sindresorhus/got#2031]
#### Describe the bug

 - Node.js version: v14.19.0
 - OS & version: macOS Monterey 12.3.1

#### Code to reproduce

```ts
const form = new FormData()
form.append('file', fs.createReadStream('test.mp4'))

await got.post('fileup', {
    body: form,
  })
  .on('request', request => {
    console.log(request)
  })
  .on('uploadProgress', progress => {
    console.log(performance.now(), progress)
  })
console.log(performance.now(), 'finished')
```

#### Actual behavior

[![LJwnCF.png](https://s1.ax1x.com/2022/04/16/LJwnCF.png)](https://imgtu.com/i/LJwnCF)

[![LJwxq1.png](https://s1.ax1x.com/2022/04/16/LJwxq1.png)](https://imgtu.com/i/LJwxq1)

---

https://github.com/sindresorhus/got/blob/53513ce3ca09258b575496a3f9899c7d0f6ab6ea/source/core/index.ts#L174-L180

I suspect that the `writableHighWaterMark` is not set to 0

[![LJBt6H.png](https://s1.ax1x.com/2022/04/16/LJBt6H.png)](https://imgtu.com/i/LJBt6H)

#### Expected behavior

when the progress ends, the FINISHED is triggered

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I don't see what's the problem with the current behavior?

**Comment by chenhb23** [comment]
maybe it's because i use a proxy tool

**Comment by szmarczak** [comment]
> maybe it's because i use a proxy tool

What do you mean by `it`?
