### ISSUE TITLE
Bypass 'X-Frame-Options' = 'sameorigin' ?

### ISSUE THREAD

**Issue by dyaacov** [sindresorhus/got#2032]
Hi All,
1. Is it possible to stream url data into iframe and remove the X-Frame-Options header?
2. What is the different between stream a url and a simple get?

thanks
Dekel
...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
This is Node.js, not a browser, there's no such thing as an `iframe`.

> What is the different between stream a url and a simple get?

https://nodejs.org/api/stream.html

**Comment by dyaacov** [comment]
I know that.
I meant:
I would like to use got as a proxy and be able to remove security headers so the browser can display any url inside an iframe

**Comment by szmarczak** [comment]
Perhaps you want to create a browser extension instead. If you really want this to be accessible for all users no matter the browser, then you're doing the wrong thing. Security headers exist for a purpose.
