### ISSUE TITLE
Add a response.ok boolean similar to fetch API?

### ISSUE THREAD

**Issue by KyleAMathews** [sindresorhus/got#2036]
It's quite handy and would ease migrating to got.

It's set to false if `(res.statusCode < 200 || res.statusCode > 299)` or true if in 200-299.

**Comment by sindresorhus** [comment]
Got throws on non-2xx/3xx status codes by default.

https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#throwhttperrors

**Comment by IswaryaS** [comment]
@szmarczak Saw your tag that this issue needs to be picked and that it is good for a beginner - I have couple of years work experience in writing code, and now would like to try to contribute to open source (completely new but want to learn). Do you think I can pick up this task? I've gotten a brief overview of the problem. But if I can be assigned to this, I would like to know more to help me resolve it. Thanks in advance.

**Comment by szmarczak** [comment]
@IswaryaS Feel free to pick this up. 

You need to add `ok` property [here](https://github.com/sindresorhus/got/blob/c25af092bf792c2c7e29db848a569f2eb3e527f8/source/core/response.ts#L8) and [here](https://github.com/sindresorhus/got/blob/c25af092bf792c2c7e29db848a569f2eb3e527f8/source/core/index.ts#L627). Don't forget to modify/add some tests.
