### ISSUE TITLE
Allow specifying minimum chunk size

### ISSUE THREAD

**Issue by longnguyen2004** [sindresorhus/got#2037]
#### What problem are you trying to solve?

I'm piping the output of got stream directly to `file-type`. However, due to slow connection, sometimes `file-type` receives a too small data chunk, which prevents it from detecting the file type properly.

#### Describe the feature

A `minChunkSize` option, which when set, ensures that a data chunk is at least that size.

```ts
const instance = got.extend({
    minChunkSize: 1000
});
```
```ts
const stream = got.stream(..., {
    minChunkSize: 1000
});
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
It should get the file type regardless of the chunk size, please open an issue in `file-type` instead.
