### ISSUE TITLE
How to get cookiejar object from got.extend?

### ISSUE THREAD

**Issue by opcodeIII** [sindresorhus/got#2042]
Is it even possible to get it? Or direct access is required
![изображение](https://user-images.githubusercontent.com/105169647/168846992-c71fb0f0-dfe7-4f84-87be-1ec67f4c6472.png)

...

#### Checklist

- [+] I have read the documentation.

**Comment by jeanbmar** [comment]
Maybe cookieJar could use a getter on the top level object. It feels a bit weird to retrieve a non-static object from `client.defaults.options.cookieJar`.
