### ISSUE TITLE
Retry on stale/stuck upload

### ISSUE THREAD

**Issue by Rychu-Pawel** [sindresorhus/got#2049]
#### What would you like to discuss?

My use case is to upload a large file to the server. I would like to force a retry when the upload gets stuck. 

I don't see any relevant timeout to be set in the library so I created a `setInterval()` logic that checks how long it has been since the last progress change. I also made a `uploadProgress` handler that reset the time variable that is used by the `setInterval`'s logic. 
Now I'm wondering what's the best way to force the retry when there has not been any progress for X seconds?

My first idea was to cancel the request and add the `beforeError` hook that will check if the promise was canceled and if so then throw a `RetryError` to force the retry but I guess that won't work as the promise is already set to canceled state, right?

Have you considered adding an `uploadTimeout` to the library that will check has there been any progress for the last X milliseconds and timeout if not?
#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> throw a RetryError to force the retry but I guess that won't work as the promise is already set to canceled state, right?

It should work. `beforeError` executes before the promise is settled.

**Comment by szmarczak** [comment]
> But won't it hurt that the promise.cancel() has already been called? Will it actually retry even that the promise.isCanceled is already true?

Ah, you haven't mentioned `promise.cancel()` earlier. If you call `promise.cancel()` then there will be no retries - that is the point of cancelling.

> And this is what I'm after - not to limit the total upload time but rather only retry uploads that got stuck and there has been no progress for, e.g, 5 minutes.

Then you're looking for the `socket` timeout: https://github.com/sindresorhus/got/blob/main/documentation/6-timeout.md#socket

**Comment by Rychu-Pawel** [comment]
> Then you're looking for the `socket` timeout: https://github.com/sindresorhus/got/blob/main/documentation/6-timeout.md#socket

Yes, indeed, looks like this is what I'm looking for, thank you! :)

I got a bit confused by the description saying that the timeout `Resets when new data are received.` and what I'm doing is actually an upload. Maybe it would be better to write `Resets when new data is transferred`? :)
Plus, I guess, the link should instead point at https://nodejs.org/api/net.html#socketsettimeouttimeout-callback, right?
