### ISSUE TITLE
code cannot compile

### ISSUE THREAD

**Issue by calidan-x** [sindresorhus/got#2052]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/source' is not defined by "exports" in /Users/calidan/Desktop/***/node_modules/got/package.json

NodeJS: 16.x

**Comment by sgehrman** [comment]
same issue.  why not answer the question rather than wasting time with your wacky rules.

**Comment by szmarczak** [comment]
@sgehrman The details are crucial in order to reproduce the issue reliably. Please refrain from passive aggressive comments as those are not helpful at all.
