### ISSUE TITLE
`request` object on upload

### ISSUE THREAD

**Issue by alex-phillips** [sindresorhus/got#206]
I'm attempting to get the `request` object on a `put` or `post` file upload so that I can display the amount of data transfered. It doesn't look like using `got.stream.post` and then adding `.on('data')` event doesn't really give me what I'm looking for. Any thoughts?

**Comment by floatdrop** [comment]
@alex-phillips listening on stream returned form `got` will get you data _from_ server, not uploaded chunks. I assume your endpoint is not answering anything, until upload is finished.

Try to listed `data` event on stream, that you put in the `stream` option.

**Comment by alex-phillips** [comment]
I believe you're right. It's just not receiving anything FROM the server until the end of the upload. The way I was previously able to accomplish this in the `request` package was that `var request = request.get(...)`, but since this is a promise-based library, it returns a promise instead.

I was just curious if there was any way to get that request object while still being a promise based flow.

**Comment by floatdrop** [comment]
@alex-phillips yes, you can use promises. Just pass stream to `body` option:

```js
const stream = fs.createReadStream('<file>');

stream.on('data', chunk => console.log(`Uploaded ${chunk.length} bytes...`));

got.post('<api>', {
    body: stream
}).then(res => {
    console.log(`Upload finished (${res.statusCode})`);
});
```

**Comment by alex-phillips** [comment]
This is perfect, thanks!

**Comment by floatdrop** [comment]
@alex-phillips p.s. please, remember to call `got` in same tick with `.on('data', ...)`. Otherwise you can lose first chunks of data.

**Comment by sindresorhus** [comment]
@floatdrop I don't think that applies anymore with Streams 2.
