### ISSUE TITLE
Improve stacktraces

### ISSUE THREAD

**Issue by alesmenzel** [sindresorhus/got#2063]
**got version: 11.8.5**

#### What problem are you trying to solve?

Currently `got` API errors don't even show which line of user code throws the error, which is pretty annoying to try and guess where the problem is. See the example error I got from `got`, no pun intended. It is pretty useless, I know there is an error in some API call, but I don't get the caller, I don't get the URL that was called, I don't get the method that was used or the payload...

```
HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (.../node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1655539247127,
    socket: 1655539247127,
    lookup: 1655539247128,
    connect: 1655539247315,
    secureConnect: undefined,
    upload: 1655539247315,
    response: 1655539247558,
    end: 1655539247559,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 187,
      tls: undefined,
      request: 0,
      firstByte: 243,
      download: 1,
      total: 432
    }
  }
}
```

#### Describe the feature

Please include a better stack trace, at least what is the caller code.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Duplicate od #1736
