### ISSUE TITLE
Remove control characters from UNIX Domain Socket

### ISSUE THREAD

**Issue by bllmo** [sindresorhus/got#2068]
#### What would you like to discuss?

Hello, i have a problem with docker exec command output, when i try to run 

```js
 const output = await client.runCommand([
      "cat -v ./tmp/schema.json"
  ]); 
```
Where `runCommand` return a stream with docker socket of exec command

```js
    return new Promise((resolve, reject) => {
      let chunks = [];

      stream.on("data", (chunk) => { 
        let output = chunk.toString();
        chunks.push(output);
      });

      stream.on("error", (err) => reject(err));
      stream.on("end", () => resolve(chunks.join("")));
    });
```
but when i parse with json parse the result of this promise i receive this  control characters

<img width="408" alt="Screen Shot 2022-06-23 at 5 15 29 PM" src="https://user-images.githubusercontent.com/6557615/175333952-98ed5cbc-259a-4b9d-a8fd-438dab81868a.png">

is possible to remove this control characters from the chunks? 
...

#### Checklist

- [ x] I have read the documentation.

**Comment by sindresorhus** [comment]
That's outside the scope of Got.
