### ISSUE TITLE
SNI support?

### ISSUE THREAD

**Issue by astoilkov** [sindresorhus/got#207]
I am trying to [upload a file on GitHub release](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) but without success. Does `got` support SNI?

These are my two attempts:
```js
var stream = fs.createReadStream(path.resolve('<path-to-file>'))
        .pipe(got.stream('<url>', {
          headers: {
            Authorization: 'token ' + this.options.accessToken,
            'Content-Type': 'text/plain'
          }
        }));
```

```js
var stream = fs.createReadStream(path.resolve('<path-to-file>'));
    
    return got('<url>', {
      headers: {
        Authorization: 'token ' + this.options.accessToken,
        'Content-Type': 'text/plain'
      },
      readableStream: stream
    });
```

I also tried providing `Content-Length` but without success. I am in a Node.js environment so I didn't try `FormData` approach.

**Comment by sindresorhus** [comment]
No idea, but Node.js supports it, so might be something you can pass to the options. Most of the `got` options are just passed through to the [`https`](https://nodejs.org/api/https.html) module.

**Comment by astoilkov** [comment]
Ok. Thanks for the information and will investigate more and look into the source code to figure it out.
