### ISSUE TITLE
Hangs when response code is 503

### ISSUE THREAD

**Issue by jijojosephk** [sindresorhus/got#2071]
#### Describe the bug

 - Node.js version: 16
 - OS & version: 22.04

When the HTTP response is 503 from a server, got() call does not end, no errors thrown.

#### Actual behavior

got() call is stuck in an infinite state.

#### Expected behavior

got() call should end as soon as the response is received from the server whether it's failed or succeeded.

#### Code to reproduce
`import got from 'got';
got('https://www.champagne-cazals.fr/boutique/gb/')`
```js
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Turning off retrying makes it resolve:

```js
import got from 'got';

await got('https://www.champagne-cazals.fr/boutique/gb/', {retry: {limit: 0}});
```

**Comment by szmarczak** [comment]
The server responds with `retry-after: 3600` which means it's going to retry in 1 hour. You can see the headers via `console.error(error.response.headers);`. You can also pass `{ retry: { maxRetryAfter: 10 } }` to limit it to 10s. https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md#maxretryafter
