### ISSUE TITLE
Maintenance of last Non-ESM release

### ISSUE THREAD

**Issue by konradjurk** [sindresorhus/got#2072]
Hi 👋

Due to our server (Nest.js, [source](https://discord.com/channels/520622812742811698/975798881667391518/975799372631662632)) as well as testing framework (Jest, [source](https://jestjs.io/docs/ecmascript-modules)) currently being incompatible or not sufficiently stable with ESM, we can't upgrade to your latest major version.

We are wondering if you are planning to continue to supply security updates to the last non-ESM release.

> Please don't open issues for questions regarding CommonJS / ESM.

I did read and understand this, but the question is important and was not answered in the documentation.

Thank you!

**Comment by sindresorhus** [comment]
We will backport security fixes to v11 for the foreseeable future (at least for another year).
