### ISSUE TITLE
Backport security fix to v10 for compatibility with gh-got

### ISSUE THREAD

**Issue by loren138** [sindresorhus/got#2074]
#### What would you like to discuss?

`gh-got` v9 (latest) depends on `got` v10.x
https://github.com/sindresorhus/gh-got/blob/v9.0.0/package.json#L35

To resolve the security issue, we've tried forcing it to use `got` v11.x.
Unfortunately, that results in:
> RequestError: The `GET` method cannot be used with a body

My best guess is this has something to do with these lines causing `got` to think there is a body when there is not really one:
https://github.com/sindresorhus/gh-got/blob/v9.0.0/index.js#L24-L27

Any chance of back porting the security fix to v10 or `gh-got` working with v11?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
> Any chance of back porting the security fix to v10 or gh-got working with v11?

No plans to backport to v10.

**Comment by sindresorhus** [comment]
The example here should work with Got v11. You could copy-paste it into a `gh-got.js` file in your project and use that for now: https://github.com/sindresorhus/got/blob/5e17bb748c260b02e4cf716c2f4079a1c6a7481e/documentation/examples/gh-got.js
