### ISSUE TITLE
Got 13

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#2075]
*We will not do Got 13 for a long time. Just opening it here to plan.*

TODO:

- [x] Require Node.js 16
- [x] Make the `enableUnixSocket` option `false` by default.
- [x] https://github.com/sindresorhus/got/issues/989
- [x] https://github.com/sindresorhus/got/issues/1581

Let me know if there's anything I forgot or if there's anything we should consider changing.

**Comment by liuhanqu** [comment]
would `got` use `undici` ?

**Comment by sindresorhus** [comment]
No. It would be a massive amount of work to switch and if we were to do it, I would want Unidici to be more stable. Maybe in a few years.

**Comment by szmarczak** [comment]
@liuhanqu you can use undici with https://github.com/sindresorhus/ky

**Comment by sindresorhus** [comment]
@szmarczak I plan to do Got 13 sometime in April. Are there any other breaking changes or important things you think we should do for Got 13?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/releases/tag/v13.0.0

**Comment by wicherfree** [comment]
> _We will not do Got 13 for a long time. Just opening it here to plan._
> 
> TODO:
> 
> * [x]  Require Node.js 16[x]  Make the `enableUnixSocket` option `false` by default.[x]  [Remove `import {URL} from 'url';` when TypeScript gets fixed #989](https://github.com/sindresorhus/got/issues/989)[x]  [Use `stream/promises` when targeting Node.js 16 #1581](https://github.com/sindresorhus/got/issues/1581)
> 
> Let me know if there's anything I forgot or if there's anything we should consider changing.

onesteppcloser
