### ISSUE TITLE
Don't retry on invalid SSL certificates

### ISSUE THREAD

**Issue by also** [sindresorhus/got#208]
Dealing with self-signed or other invalid SSL certificates with got confused me, because these requests will take a long time to fail due to retries that couldn't possibly ever succeed. The retries take long enough that it seems something has hung.

This request will be retried five times before failing with "RequestError: unable to verify the first certificate" (`UNABLE_TO_VERIFY_LEAF_SIGNATURE`)
```js
got('https://self-signed.badssl.com/')
    .catch((err) => console.error(err.stack));
```

I realize that the retry logic is delegated to the is-retry-allowed library, but it doesn't seem to handle this common class of HTTP(S) error.

**Comment by sindresorhus** [comment]
Agreed

**Comment by floatdrop** [comment]
Fixed upstream.
