### ISSUE TITLE
`RetryError` is not working as expected

### ISSUE THREAD

**Issue by Mehdi-Hp** [sindresorhus/got#2082]
#### Describe the bug

 - Node.js version: `v18.5.0`
 - OS & version: `MacOS 12.4`

As you can see in the reproduction example, I can't make got to retry the request. I've provided a simple example, but in my actual scenario, I'm setting a proxy in `beforeRequest` and if the proxy has some error in `beforeError`, I need to retry the request, so it has a new proxy.

From Docs:
`You can trigger a retry by throwing the [RetryError](https://github.com/sindresorhus/got/blob/main/documentation/8-errors.md#retryerror) in any hook.`

```
RetryError
Code: ERR_RETRYING
Always triggers a new retry when thrown.
```

#### Actual behavior
```
beforeRequest: 1
RETRYING...: 1
beforeRequest: 2
RETRYING...: 2
beforeRequest: 3
beforeError: 1
catch
```
...

#### Expected behavior
```
beforeRequest: 1
RETRYING...: 1
beforeRequest: 2
RETRYING...: 2
beforeRequest: 3
RETRYING...: 3
beforeRequest: 4
RETRYING...: 4
beforeRequest: 5
RETRYING...: 5
beforeRequest: 6
RETRYING...: 6
... To infinity
```
...

#### Code to reproduce

```js
import got, { RetryError } from 'got';

const client = got.extend({
    hooks: {
        beforeRequest: [
            (request) => {
                console.count('beforeRequest');
            }
        ],
        beforeRetry: [
            (options, error) => {
                console.count('RETRYING...');
                return error;
            }
        ],
        beforeError: [
            (error) => {
                console.count('beforeError');
                return new RetryError();
            }
        ],
        afterResponse: [
            (response, retryWithMergedOptions) => {
                console.count('afterResponse');
                console.log('response 👉 ', response);
                return response;
            }
        ]
    }
});


try {
    const response = await client.get('https://google20000.com');
} catch {
    console.log('catch');
}

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
This is working as intended. It's limited by `retry.limit`, alternatively you can provide your own `retry.calculateDelay` to work around this.

**Comment by Mehdi-Hp** [comment]
Hmm, Alright. But I think it could be more useful if `RetryError` retries the request _no matter what the `retry` config is`. If not, it seems like `RetryError` doesn't have any use case.

**Comment by Mehdi-Hp** [comment]
> Hmm, Alright. But I think it could be more useful if `RetryError` retries the request, no matter what the `retry` config is. If not, it seems like `RetryError` doesn't have any use case.

For example, I think It's reasonable for this one to retry for infinity

```js
import got, { RetryError } from 'got';

const client = got.extend({
    retry: {
        limit: Number.POSITIVE_INFINITY,
        methods: [],
        statusCodes: [],
        errorCodes: [],
        backoffLimit: Number.POSITIVE_INFINITY,
    },
    hooks: {
        beforeRequest: [
            (request) => {
                console.count('beforeRequest');
            }
        ],
        beforeRetry: [
            (options, error) => {
                console.count('RETRYING...');
                return error;
            }
        ],
        beforeError: [
            (error) => {
                console.count('beforeError');
                // return new RetryError();
            }
        ],
        afterResponse: [
            (response, retryWithMergedOptions) => {
                console.count('afterResponse');
                console.log('response 👉 ', response);
                return response;
            }
        ]
    }
});


try {
    const response = await client.get('https://google20000.com');
} catch {
    console.log('catch');
}
```

**Comment by szmarczak** [comment]
> I think It's reasonable for this one to retry for infinity

That's exactly what we want to prevent. Hanging promises that never finish. Hence the limit.

**Comment by Mehdi-Hp** [comment]
> > I think It's reasonable for this one to retry for infinity
> 
> That's exactly what we want to prevent. Hanging promises that never finish. Hence the limit.

That's a valid point, But got already prevents that with `retry` property.  
`RetryError` seems like a more low level API which gives the developer more freedom and comes with responsibility.   
Maybe you can think of my use case? Setting a proxy on `beforeRequest` and retrying if proxy fails to connect. I want to retry this many times, But I don't want to retry that much if for example I get `ETIMEDOUT`.

**Comment by szmarczak** [comment]
If we have enough people that would need this behavior change, then we would probably change it. For now you can do this:

> you can provide your own `retry.calculateDelay` to work around this.
