### ISSUE TITLE
followRedirect: true and http-equiv="refresh"

### ISSUE THREAD

**Issue by mtimofiiv** [sindresorhus/got#2086]
#### What would you like to discuss?

So the library works great for redirects of other types, but what about the HTML method of the following tag:

```html
<html>
  <head>
    <meta http-equiv="Refresh" content="0; URL=/anotherpage.html">
  </head>
  <body>
  </body>
</html>
```

Currently, `followRedirect: true` does not do this redirect, probably because it would require parsing the HTML in case the response is HTML. Maybe it's even outside the scope of the library.

What do you all think?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
Parsing HTML is outside the scope of Got.

Someone could make a [Got plugin](https://github.com/sindresorhus/got/blob/main/documentation/lets-make-a-plugin.md) that does it.
