### ISSUE TITLE
Module parse error

### ISSUE THREAD

**Issue by eugeneross** [sindresorhus/got#209]
I'm receiving a weird error at the build time utilizing Webpack. The error in question is referring to Got's package.json file that I'm importing.

```
Module parse failed: .../node_modules/got/package.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
```
Curious to what is causing this and if this is on my end or Got's end.

**Node version**: v4.2.0

**NPM version**: 2.14.7

**Comment by jamestalmage** [comment]
https://webpack.github.io/docs/using-loaders.html

https://github.com/webpack/json-loader

**Comment by sindresorhus** [comment]
This is supported by Node.js. Anything Webpack doesn't handle that Node.js does is on you to handle.

**Comment by sindresorhus** [comment]
@jamestalmage That's is if you want to load JSON yourself. Webpack should handle the case of Node modules using `require` for JSON. It's a very common convention. Users shouldn't have to care if a dependency they use do this.

**Comment by eugeneross** [comment]
@sindresorhus  @jamestalmage Thanks, but I'm curious to why a json loader would be needed for Got?
