### ISSUE TITLE
How to determine protocol used for request?

### ISSUE THREAD

**Issue by wreiske** [sindresorhus/got#2096]
#### What would you like to discuss?

Is there a way to determine the protocol used for the request? 

From https://nodejs.org/api/tls.html#tlssocketgetprotocol

> Protocol versions are:
> 'SSLv3'
> 'TLSv1'
> 'TLSv1.1'
> 'TLSv1.2'
> 'TLSv1.3'

For example, https://www.geeksforgeeks.org/node-js-tlssocket-getprotocol-method/ using tls.connect allows you to getProtocol on the socket to return something useful, like TLSv1.3.

Another example would be using the `https` node package, and doing an `https.request`. The response will include a `socket.getProtocol()` function that will return the protocol used, like TLSv1.3.

I've tried getting it from `got`'s `response.socket`, but haven't had much luck finding it.

#### Checklist

- [x] I have read the documentation.

**Comment by wreiske** [comment]
Looks like there is an open discussion about this as well, here: https://github.com/sindresorhus/got/discussions/1916

**Comment by szmarczak** [comment]
Response extends IncomingMessage so it's the same like in pure Node.
