### ISSUE TITLE
Is there any other option than to add "type": "module" in the package.json file for import package?

### ISSUE THREAD

**Issue by turivishal** [sindresorhus/got#2097]
Error:
```
got = require('got');
      ^
Error [ERR_REQUIRE_ESM]: require() of ES Module ..\node_modules\got\dist\source\index.js from ..\util\general.helper.js not supported.
Instead change the require of index.js in ..\util\general.helper.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (..\util\general.helper.js:5:7)
    at Object.<anonymous> (..\app.js:8:1) {
  code: 'ERR_REQUIRE_ESM'
}
```
I checked the latest version 12.3.0 requires to import package by import command,
```
import got from 'got';
```

It will work when I add `"type": "module"` in the package.json file, but if i do that I have to update my all code where I have used `require()` to `import` command and it is a lot of work for 8 projects.

Please suggest any other options,
Can I stick with an older version 11.8.5 or can I move to another package?

**Comment by szmarczak** [comment]
```js
const {got} = await import('got');
```

or you can use [`got-cjs`](https://github.com/apify/got-cjs) which is maintained by Apify.
