### ISSUE TITLE
'Invalid URL' error message different in Node 18

### ISSUE THREAD

**Issue by DanCurryy** [sindresorhus/got#2107]
#### Describe the bug

 - Node.js version: v18.7.0
 - OS & version: Mac OS Monterey 12.4

#### Actual behavior

Expected error.message to be of the form (as seen in node v14.17.6):
`Invalid URL: invalid-url.com`

#### Expected behavior

We receive an error message:
`Invalid URL`

Without the URL included in the message

#### Code to reproduce

```js
async function test () {
  const { default: got } = await import('got')
  return got.get('invalid-url.com')
}

function main () {
  return test()
    .then(res => {
      console.log(res)
    })
    .catch(err => {
      console.log(err.message)
    })
}

main()
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The URL should be available under `error.input`. This is actually a Node.js issue, Got doesn't modify URL error messages.

@sindresorhus Do we want to change this?

**Comment by sindresorhus** [comment]
I think we should first try to get it fixed in Node.js

**Comment by DanCurryy** [comment]
Found where the change was made - seems it was intentional and will not be getting 
 "fixed" as such: https://github.com/nodejs/node/blob/75b68c6e4db515f76df73af476eccf382bbcb00a/lib/internal/errors.js#L1363

As well as the following [PR](https://github.com/nodejs/node/pull/38614) that introduced it, so will close this unless it's within the mandate for got to alter the error at all.

**Comment by sindresorhus** [comment]
Closing as the URL is available programmatically and the Node.js reasoning for hiding it makes sense.
