### ISSUE TITLE
Issue with SSL/TSL when using multiple threads

### ISSUE THREAD

**Issue by vadnala** [sindresorhus/got#2114]
#### Describe the bug

 - Node.js version: 14.15.5
 - OS & version: Windows Server 2019

#### Actual behavior

When using multiple threads and using the same login (with SSL/TSL), at times, **got** POST requests are rejected with the following error 

write EPROTO 9872:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 80

But, if we switch to a single thread, there are no errors. So, is there a way to support multiple threads?
Or, can each thread create a dedicated SSL stream so that there are no clashes!

**Comment by szmarczak** [comment]
Why didn't you include a reproduction code? I have no idea what to do here. You can try upgrading to Node.js 18.

The error is an OpenSSL one, which is used directly by Node. Got doesn't alter it.
