### ISSUE TITLE
Why the name "got"? No really? It's hard to find "got" related errors on google search 

### ISSUE THREAD

**Issue by nomanoff** [sindresorhus/got#2115]
#### What would you like to discuss?
I really like the library but i have a problem with the name. Every time I make a google search for a specific error related to "got" it never gives me the right result. So my question is: Is there a better way to google search "got" related bugs or errors. 
I really really wanna use this library for my upcoming projects but so far my google search results are not on point. 
But really apreciate the hard work behind this library. 

Thanks for the answers.
...

#### Checklist

- [x] I have read the documentation.
- still reading

**Comment by szmarczak** [comment]
I'm not the one who came up with the name but I guess it came like this: GET request -> got.

It's visible when you for example search `best http clients for node js`.

**Comment by erahhal** [comment]
It's impossible to find anything for this library on google.  perhaps rename it got.js?  anything unique.  I can assure you that many are struggling and many don't use the library due to the difficulty of finding support through search.
