### ISSUE TITLE
Request body can't be querystring.parse(str)

### ISSUE THREAD

**Issue by bisubus** [sindresorhus/got#212]
When the request is supplied with body that differs from `{ ... }` object, it throws

> options.body must be a ReadableStream, string, Buffer or plain Object

`is-plain-object` expects an object to inherit from either `null` or `Object` directly.

This makes 

```
got.post(url, { data: querystring.parse(query) });
```

to fail, because `querystring.parse(...)` object [inherits from empty object that inherits from `null`](https://github.com/nodejs/node/blob/v6.3.0/lib/querystring.js#L11-L12).

This looks more like a bug rather than zealous sanitization.

**Comment by floatdrop** [comment]
@bisubus I see positive side in this – you should explicitly set fields, that you are sending.

P.s. why you are passing result of `querystring.parse` to `body`? Why not just pass `query` as is?

**Comment by bisubus** [comment]
@floatdrop Why to not just get own enumerable properties from the object in this case? As for the example above, the workaround should be `Object.assign({}, querystring.parse(query))`, it doesn't add much clarity.

I'm quite sure (don't have this piece of code at hand at this moment) that this was done because `got.post(url, { data: query })` makes a `text/plain` request and not `application/x-www-form-urlencoded`, not a very good thing for POST request (maybe a subject for another issue?)

**Comment by floatdrop** [comment]
> makes a `text/plain` request and not `application/x-www-form-urlencoded`, not a very good thing for POST request (maybe a subject for another issue?)

This is right behaviour, if you pass String to `body`. Maybe we should move from `is-plain-obj` to `is-obj`.

@bisubus mind to make a PR?

**Comment by bisubus** [comment]
@floatdrop 

Sure, will do this. I see that [`is-obj` allows functions](https://github.com/sindresorhus/is-obj/blob/master/index.js). Wouldn't it be better to stick to `util.isObject` instead?

**Comment by sindresorhus** [comment]
@bisubus Functions are objects. `util.isObject` is deprecated.

**Comment by bisubus** [comment]
@sindresorhus That's correct. This requires [this spec](https://github.com/sindresorhus/got/blob/master/test/error.js#L47) to be fixed but otherwise it looks fine. Function type shouldn't be reserved for future use as callbacks here, should it?

**Comment by sindresorhus** [comment]
@bisubus We could always just do `isObj(body) && body !== 'function'`.

**Comment by bisubus** [comment]
@sindresorhus My guess that the code cannot gain much from `is-obj` dependency then, right?
