### ISSUE TITLE
Instance plugins

### ISSUE THREAD

**Issue by jeanbmar** [sindresorhus/got#2122]
#### What problem are you trying to solve?

The plugin feature using `extend` is pretty cool to implement reusable logic accross different projects.
It works well for options and request handling, but it would be a nice addition to have something for custom methods at a higher level.
We can't define custom methods on the got instance with `Object.defineProperty` because the instance get replaced when we use `extend`.

The existing pagination feature is a good example of what an instance plugin could be.

A concrete idea I have is making a plugin to manage cookies in a more convenient way.
Calling `instance.defaults.options.cookieJar` and the different `tough-cookie` methods is tedious, and wrapping that stuff in a plugin could be useful.

#### Describe the feature

The instance plugin feature consists in allowing reusable logic on the got instance. 
A way to implement it could be a new hook that would give access to the newly created got instance when `extend` is called.

Here is an example with the cookie jar idea.
Let's say we are coding a scraper and need to set some cookies at start or during execution.

```js
import got from 'got';
import { cookieJarPlugin } from 'got-cookie-jar-plugin';

const client = got.extend(cookieJarPlugin);
client.setCookie(/* ... */); // a new method from the plugin
console.log(client.cookieJar); // a new getter from the plugin
const response = await client('https://www.google.com');
console.log(client.getCookie(/* ... */)); // another new method from the plugin
```

The plugin itself would look like:

```js
export default {
  hooks: {
    afterCreate: [
      (gotInstance) => { /* there goes my plugin logic */ },
    ]
  },
}
```

#### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
There's no benefit over this:

```js
const client = got.extend({ cookieJar });
await cookieJar.setCookie(...);

const response = await client('https://www.google.com');

const cookies = await cookieJar.getCookie(...);
console.log(cookies);
```

**Comment by jeanbmar** [comment]
@szmarczak Unless you don't want to init a cookie jar on every project, to keep a reference on a cookie jar everywhere you use got, to use async cookie jar methods or to deal with tough-cookie API.

But it isn't the topic of this issue really. I gave an example to illustrate how a plugin system could be used. The example itself isn't important. I would appreciate a feedback on the actual idea.

**Comment by szmarczak** [comment]
Without knowing what are the use cases it's hard to say
