### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by mruanova** [sindresorhus/got#2123]
please create a CHANGELOG.md file following https://keepachangelog.com/en/1.0.0/ with all the versions listed on  https://github.com/sindresorhus/got/commits/main/package.json

**Comment by sindresorhus** [comment]
We use GitHub Releases, like most projects on GitHub: https://github.com/sindresorhus/got/releases

We see no need for a separate changelog file, but thanks for the suggestion.
