### ISSUE TITLE
why got promise .text(), .json() and .buffer() is not a function, and isCanceled is false

### ISSUE THREAD

**Issue by lqd1434** [sindresorhus/got#2133]
#### What would you like to discuss?
why got promise .text(), .json() and .buffer() is not a function, and isCanceled is false(I use got in electron, and i use dynamic import)

the code is follow:
```js
Got(url, {
    method: 'GET',
    timeout: {
      send: 10000
    },
    headers: headerObj,
    searchParams: paramObj
  })
```
...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
We don't support Electron here, sorry.
