### ISSUE TITLE
Having trouble migrating from Axios

### ISSUE THREAD

**Issue by jeff-eastman** [sindresorhus/got#2142]
#### What would you like to discuss?
Axios migration.

I'm trying to refactor my React app to use Got instead of Axios. I've hit a road block right off the get-go, and after reading the documentation, unclear on how to proceed. I'm trying to issue a simple GET request, but encountering this error:

**Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.constants" in client code** 

Would greatly appreciate help.

...

#### Checklist

- [X ] I have read the documentation.

**Comment by jeff-eastman** [comment]
npm install buffer -> quickly resolved the initial issue. 

Now I'm seeing this though:

![image](https://user-images.githubusercontent.com/29335232/189655478-7e1a23a2-9d2c-4c31-956a-4a7d0349aca5.png)

**Comment by sindresorhus** [comment]
Got is for Node.js. I think you want https://github.com/sindresorhus/ky instead.
