### ISSUE TITLE
`url` must not start with a slash when using prefixUrl

### ISSUE THREAD

**Issue by Inrixia** [sindresorhus/got#2147]
#### Describe the bug

 - Node.js version: v18.5.0
 - OS & version: Windows 10 & got 12.4.1

#### Actual behavior

When extending got with a `prefixUrl` and then attempting to call a endpoint starting with a slash the error ```'url' must not start with a slash``` is thrown. 

This is caused by this check here https://github.com/sindresorhus/got/blob/26fffe94618b370629f6148b6d21ebfeab1e5299/source/core/options.ts#L1399-L1401

The issue is if using api types generated by something like https://www.npmjs.com/package/openapi-typescript then all api paths will be prefixed with a slash making it impossible to use `prefixUrl` as intended.

The check for a url starting with a slash should be amended to check for `prefixUrl`, or there should be some way to override the error.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
You need to remove the leading slash before passing the URL to got. This is working as intended, leading slashes are ambiguous.

https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#note-2
