### ISSUE TITLE
Is it possible to log request body in a beforeRequest hook?

### ISSUE THREAD

**Issue by thekevinbrown** [sindresorhus/got#2148]
#### What would you like to discuss?

We'd like to log our requests. It's working fine in a `beforeRequest` hook, except that I cannot tell how to get to the body of the request.

**Sample Code**
```javascript
const got = require('got@11.8.2');

const result = await got.post('http://google.com', { 
    json: { someKey: 'someValue' },
    hooks: {
        beforeRequest: [console.log]
    }
});
```

**Playground Link**
https://runkit.com/embed/pr3hql6551qj

#### Question

How can I get `{ "someKey": "someValue" }` to log out from within the `beforeRequest` hook?

#### Checklist

- [x] I have read the documentation.

I have also read the source, but I can't tell how to get to `kBody` from the `options` parameter I'm being passed in the `beforeRequest` hook.

**Comment by szmarczak** [comment]
You need to log `options.body` `options.form` `options.json` explicitly since those options are not enumerable.

**Comment by thekevinbrown** [comment]
Thank you!
