### ISSUE TITLE
error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

### ISSUE THREAD

**Issue by kaname-png** [sindresorhus/got#2151]
#### Describe the bug

 - Node.js version: v18.6.0
 - OS & version: Windows 11

#### Actual behavior
node_modules/cacheable-request/dist/types.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

#### Expected behavior
No error

#### Typescript config

```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"alwaysStrict": true,
		"declaration": true,
		"declarationMap": true,
		"emitDecoratorMetadata": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"forceConsistentCasingInFileNames": true,
		"importHelpers": true,
		"importsNotUsedAsValues": "error",
		"incremental": true,
		"lib": ["esnext"],
		"module": "ESNext"
		"moduleResolution": "Node",
		"newLine": "lf",
		"noEmitHelpers": true,
		"noFallthroughCasesInSwitch": true,
		"noImplicitReturns": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"preserveConstEnums": true,
		"pretty": true,
		"removeComments": false,
		"resolveJsonModule": true,
		"sourceMap": true,
		"strict": true,
		"target": "ES2020",
		"useDefineForClassFields": true
	}
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/got/issues/2051#issuecomment-1251796386

**Comment by mysoly** [comment]
You can remove `resolution-mode="require"` part from your code (like `<reference types="node" resolution-mode="require"/>`)
