### ISSUE TITLE
Add Response.redirected

### ISSUE THREAD

**Issue by mishushakov** [sindresorhus/got#2152]
#### What problem are you trying to solve?

Should be `true` if request got redirected

#### Describe the feature

https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected

#### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
We have [`response.redirectUrls`](https://github.com/sindresorhus/got/blob/main/documentation/3-streams.md#redirecturls)
