### ISSUE TITLE
Get certificate after response?

### ISSUE THREAD

**Issue by mishushakov** [sindresorhus/got#2153]
#### What would you like to discuss?

Is there a way to retrieve TLS certificate after response?

in Node you can do:

```js
res.connection.getPeerCertificate()
```

right now I'm setting a variable from `checkServerIdentity`, but it doesn't always work as expected

```js
https: {
  checkServerIdentity (hostname, certificate) {
    sslCertificate = certificate
   }
}
```

#### Checklist

- [X] I have read the documentation.

**Comment by szmarczak** [comment]
`checkServerIdentity` has a different purpose. https://nodejs.org/api/tls.html#tlscheckserveridentityhostname-cert

You could try `response.socket.getPeerCertificate()` but I'm not sure if this will work as the socket may be closed already.

**Comment by szmarczak** [comment]
Alternatively you could try the `response` event

**Comment by mishushakov** [comment]
@szmarczak thanks for taking time to answer!

I'm using TypeScript and getting "Property 'getPeerCertificate' does not exist on type 'Socket'."
But, when I use `(response.socket as any).getPeerCertificate()` in my `response` event listener, it works regardless!

Maybe the types need some improvement?

**Comment by szmarczak** [comment]
> Maybe the types need some improvement?

No, that's correct. `socket` can be either `net.Socket` or `tls.TLSSocket` which extends `net.Socket`.

**Comment by mishushakov** [comment]
Do you know a stable way to get the certs from a http request?
