### ISSUE TITLE
Cant run it on AWS lambda

### ISSUE THREAD

**Issue by Port2all** [sindresorhus/got#2157]
#### What would you like to discuss?

Hello guys.

I have issues with running got on AWS lambda (Node 14, x86_64).
Locally it works perfectly with:
`import got from "got";`
But after deployment it says something like 'you can't use import outside the module'.
Tried with 'required':
`"errorMessage": "require() of ES Module /opt/nodejs/node_modules/got/dist/source/index.js from /var/task/src/index.js not supported.\nInstead change the require of /opt/nodejs/`;
or
```
 "errorType": "Error",
  "errorMessage": "Must use import to load ES Module: /opt/nodejs/node_modules/got/dist/source/index.js\nrequire() of ES modules is not supported.\nrequire() of /opt/nodejs/node_modules/got/dist/source/index.js from /var/task/src/index.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename /opt/nodejs/node_modules/got/dist/source/index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /opt/nodejs/node_modules/got/package.json.\n",
  "trace": [
    "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /opt/nodejs/node_modules/got/dist/source/index.js",
```

Is it possible at all to use it inside AWS lambda?
...

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
From the readme:

> Warning: This package is native [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and no longer provides a CommonJS export. If your project uses CommonJS, you'll have to [convert to ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) or use the [dynamic import()](https://v8.dev/features/dynamic-import) function. Please don't open issues for questions regarding CommonJS / ESM. You can also use [Got v11](https://github.com/sindresorhus/got/tree/v11.8.3) instead which is pretty stable. We will backport security fixes to v11 for the foreseeable future.
