### ISSUE TITLE
followRedirect options question

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/got#216]
How it is supposed to work? Documentation states:

> followRedirect
> 
> Type: boolean
> Default: true
> 
> Defines if redirect responses should be followed automatically.

So, when I made a request that return 3xx, I expected got to follow the redirect and return me the results. Instead, I get an exception. 

The exception is thrown [here](https://github.com/sindresorhus/got/blob/master/index.js#L120) and it seems intentional, so maybe I'm missing something...

**Comment by floatdrop** [comment]
@parro-it `got` is following redirects without exceptions (unless there are less than 10 redirects) with `followRedirect` enabled. If you wish to process 3xx response, you can disable `followRedirect` option, but still there will be no exception.

Can you post `got` version and exception?

**Comment by parro-it** [comment]
I'm using `got` version 6.3.0

> failed with "Response code 303 (See Other)"
>       stream.catch.then.e (node_modules/got/index.js:115:13)
>     process._tickCallback (internal/process/next_tick.js:103:7)

@floatdrop, to work as you said, it seems that [this line of code](https://github.com/sindresorhus/got/blob/master/index.js#L106):

```js
const limitStatusCode = opts.followRedirect ? 299 : 399;
```

should be instead:

```js
const limitStatusCode = opts.followRedirect ? 399 : 299;
```

Otherwise, if `followRedirect` is false, got throws on any 3xx response.

**Comment by floatdrop** [comment]
@parro-it it should work, we have [test case] for it.

Order in ternary-if is correct, because all codes that are greater than `limitStatusCode` should cause exception. In case of `false` in `followRedirect` - all codes that are greater than `399` should throw exception.

**Comment by parro-it** [comment]
Ok I think I understood the problem. In function `requestAsEventEmitter`, you are doing redirection only for `GET` and `HEAD ` method. 

Since I'm doing a POST request, requestAsEventEmitter doesn't redirect and the 303 response will reach the point above, and since 303 > 299, it throw the exception.

**Comment by floatdrop** [comment]
@parro-it yes, redirects for POST requests are forbidden by specification (and since you can pass Stream in body).
