### ISSUE TITLE
Use Node.js conditional exports and provide both CJS and ESM source code

### ISSUE THREAD

**Issue by HosseinAgha** [sindresorhus/got#2168]
#### What problem are you trying to solve?

Got ships as an ESM module. Of course, the future of Node is ESM. But we are a long way to reach there. 
  1. Importing CJS from ESM is a compatibility nightmare so modern web frameworks like Remix and Next.js still compile to CJS on the server side.     
  2. In order to use libraries like Got in their server-side code we have to compile the package down to CJS   

In my experience, the current ESM migration strategy of packages like Got alienates the Node.js community newcomers and we should find a way to make this transition as smooth as possible.

#### Describe the feature

The [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) feature in Node.js is pretty stable (available since Node 13). It lets the package developers provide 2 versions of the package (one ESM and one CJS) even TypeScript suggest providing the `types` key in conditional exports now (since TS 4.7).  
We can provide 2 compile targets for TypeScript so the Got package.json would be like this:  

```json
{
  "exports": {
      ".": {
          "import": "./dist/esm/index.js",
          "require": "./dist/cjs/index.js",
          "type": "./dist/types/index.d.ts"
      }
  }  
}
```

*I'd be happy to contribute this feature if you are OK with the above proposal*

#### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
We have no plans to provide conditional exports. Conditions exports come with their own problems: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849#gistcomment-3850849

**Comment by sindresorhus** [comment]
> In order to use libraries like Got in their server-side code we have to compile the package down to CJS

You don't have to. You can import ESM from CJS:

```js
const {default: got} = await import('got');

await got('https://github.com')

```

**Comment by sindresorhus** [comment]
I'm going to close this as we're not going to change our minds about this.
