### ISSUE TITLE
The GET, HEAD and DELETE methods must NOT have a body

### ISSUE THREAD

**Issue by Sunvas** [sindresorhus/got#2181]
#### Describe the bug

 - Node.js version: 19
 - OS & version: Linux

When I'm trying make a `DELETE` request with body...

#### Actual behavior

...I receive error "The GET, HEAD and DELETE methods must NOT have a body" .

#### Expected behavior

`DELETE`  requests MAY have a body. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

#### Code to reproduce

```
await got('...', {
	method:"DELETE",
	json:{test:1}
});
```

**Comment by sindresorhus** [comment]
https://stackoverflow.com/a/72596867/64949

**Comment by szmarczak** [comment]
The spec says:

> A client SHOULD NOT generate content in a DELETE request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported. An origin server SHOULD NOT rely on private agreements to receive content, since participants in HTTP communication are often unaware of intermediaries along the request chain.

**Comment by loripolve** [comment]
Looks like this is still not possible even today.
I need to make a request to this endpoint:
https://developer.spotify.com/documentation/web-api/reference/remove-tracks-playlist
Is there any option to allow this behaviour?
