### ISSUE TITLE
ETIMEDOUT taking far longer than timeout

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/got#2188]
#### What would you like to discuss?

We've discussed this type of thing before and never fully fixed it. Here's a recent example:

```
DEBUG: GitHub failure: RequestError
{
  "err": {
    "name": "TimeoutError",
    "code": "ETIMEDOUT",
    "timings": {
      "start": 1669307856735,
      "socket": 1669307856735,
      "lookup": 1669307859457,
      "connect": 1669307859457,
      "error": 1669308120448,
      "phases": {
        "wait": 0,
        "dns": 2722,
        "tcp": 0,
        "total": 263713
      }
    },
    "event": "request",
    "message": "Timeout awaiting 'request' for 10000ms",
```

This just seems wrong - 10s timeout but it takes 26x longer before it actually times out. Is it explainable or must be a bug somehow? This is in got v11.

FYI the host is api.github.com

#### Checklist

- [x] I have read the documentation.

**Comment by anhtumai** [comment]
@rarkins  Can you show me your code to get these logs?

**Comment by rarkins** [comment]
The log above comes from this code: https://github.com/renovatebot/renovate/blob/bc7793c63197452a804d0eb8dde8c5b59f03d180/lib/util/http/github.ts#L58-L78

**Comment by anhtumai** [comment]
@rarkins  I tested with `got` version 11, and got the same behavior. The request took a lot longer. I tried again with `version 13.0.0` and the bug disappeared, as I mentioned above.

I think the bug has been resolved and updating `got` to `13.0.0`, or maybe `12.x.x` in your project can help

**Comment by rarkins** [comment]
We can't use ESM-only yet unfortunately. Thanks for testing it

**Comment by anhtumai** [comment]
Perhaps you can upgrade to `version 13` and use `dynamic import` (https://v8.dev/features/dynamic-import) to load the package

This issue is related to `got version 11` so I think we can close this issue @szmarczak

**Comment by viceice** [comment]
> Perhaps you can upgrade to `version 13` and use `dynamic import` (https://v8.dev/features/dynamic-import) to load the package
> 
> This issue is related to `got version 11` so I think we can close this issue @szmarczak

we can't upgrade, because typescript will automatically downlevel the dynamic imports to a require call. 😕

**Comment by AKhodykin** [comment]
Got the same behaviour. But then realised, that got has 2 retries under the hood by default (if you don't set it to zero in options). So it actually throws ETIMEDOUT error only after all retries finished unsuccessfully. And it seems, that "total" time in timings is calculated with respect to the number of retries.

It's really unevident and its' very easy to miss this point in the documentation!

**Comment by adrianhorning08** [comment]
@AKhodykin wait, so how do you fix it? 😅 I'm trying this and it still hangs

```js
const res = await gotScraping({
      url: `url`,
      proxyUrl: getSmartProxyUrl(),
      timeout: {
        request: 8000,
      },
      retry: {
        limit: 0,
        methods: ["GET"],
        statusCodes: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
        errorCodes: [
          "ETIMEDOUT",
          "ECONNRESET",
          "EADDRINUSE",
          "ECONNREFUSED",
          "EPIPE",
          "ENOTFOUND",
          "ENETUNREACH",
          "EAI_AGAIN",
        ],
        maxRetryAfter: 1000,
        calculateDelay: ({ computedValue }) => computedValue,
        backoffLimit: Number.POSITIVE_INFINITY,
        noise: 100,
      },
    });
```
