### ISSUE TITLE
ESM modules with ESLint & Airbnb Base

### ISSUE THREAD

**Issue by ilnuribat** [sindresorhus/got#2194]
This suggestion is similar to https://github.com/chalk/chalk/commit/85f7e96f758e95dee5211b9bca1a173b8fb3abe9 commit on chalk repo

I want to import `got` inside javascript repo with `"type": "module"` on package.json. But eslint-import-plugin needs "main" field to be set

...

Right now I've got an error `import/no-unresolved: Unable to resolve path to module 'got'`

Example: https://github.com/ilnuribat/got-eslint-airbnb-esm

#### Checklist

- [ x ] I have read the documentation and made sure this feature doesn't already exist.

PS: 
https://eslint.org/docs/latest/user-guide/configuring/configuration-files
`Note that ESLint does not support ESM configuration at this time.`

**Comment by ilnuribat** [comment]
https://eslint.org/docs/latest/user-guide/configuring/configuration-files
`Note that ESLint does not support ESM configuration at this time.`

**Comment by sindresorhus** [comment]
You are trying to fix this in the wrong place. You cannot fix every package out there, but you can fix the plugin. I'm not interested in continuing to work around that plugin. I made a one-time exception in Chalk, but I don't intend to continue doing that.
