### ISSUE TITLE
Context will remain same through out a request ?

### ISSUE THREAD

**Issue by amal-chandran** [sindresorhus/got#2201]
#### What would you like to discuss?
- There is no discription talking much about when the context is getting updated / created.
- Im having a use case where i need to identify each request with an id but not able to pass those id as header to server
- I need to know whether the context is recreated for each request and will persisit.
- When i tested the same it works as expected but need a conformation before the actual usage.

![image](https://user-images.githubusercontent.com/29562232/209523496-8ea91ef5-e86f-46f6-8805-2ed121113a4f.png)

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Yes, the context is persisted throughout the entire chain of requests.
