### ISSUE TITLE
node v18's FormData "-\n-" will become "-\r\n-"

### ISSUE THREAD

**Issue by qidizi** [sindresorhus/got#2203]
#### Describe the bug

 - Node.js version:  v18.12.1
 - OS & version:   Darwin qm.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

#### Actual behavior

request:       
```js
// node global.FormData,not npm
form = new FormData();
    form.set('imN_notRN','a\na');

// print :    imN_notRN value "a\na"  
    console.log('imN_notRN value',JSON.stringify(form.get('imN_notRN')))

  // php "echo json_encode($_POST);"  will print :    { imN_notRN: 'a\r\na' } 
   console.log (await got({
        url: 'http://127.0.0.1:8000/?',
        method: 'POST',
        body: form,
        responseType: 'json'
    }).json());
```   

#### Expected behavior

php "echo json_encode($_POST);"  will print :    { imN_notRN: '`a\na`' }     

#### Code to reproduce

```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart-form-data
