### ISSUE TITLE
npm audit issue with got

### ISSUE THREAD

**Issue by marijana-rukavina** [sindresorhus/got#2212]
#### Describe the bug

 - Node.js version: 16.18.0
 - OS & version: Windows 10

When I run the `npm install` I get 7 moderate severity vulnerabilities. When I do `npm audit` I get the following;
![image](https://user-images.githubusercontent.com/84860380/215522216-21225e89-5246-4087-a9f6-f6152888c960.png)

#### Actual behavior

I tried to update the got version to 12.1.0
I tried doing `npm cache clean --force` and uninstalling and installing got again.
Nothing helped

#### Expected behavior

I want to resolve these vulnerabilities caused by got package

#### Code to reproduce

```json
"devDependencies": {
    "@cypress-audit/lighthouse": "^1.3.1",
    "@cypress/grep": "^3.1.3",
    "@cypress/skip-test": "^2.6.1",
    "@testing-library/cypress": "^8.0.3",
    "@types/jquery": "^3.5.14",
    "@types/node": "^16.11.59",
    "cy2": "^2.0.0",
    "cypress": "^10.10.0",
    "cypress-mochawesome-reporter": "^3.2.3",
    "cypress-multi-reporters": "^1.6.1",
    "cypress-xpath": "^1.8.0",
    "defu": "^6.1.0",
    "eslint-plugin-cypress": "^2.12.1",
    "gmail-tester": "^1.3.5",
    "mocha": "^10.0.0",
    "mocha-junit-reporter": "^2.0.2",
    "prettier": "2.0.2",
    "tslint-plugin-cypress": "^1.0.4",
    "typescript": "^4.8.3"
  },
  "lint-staged": {
    "cypress/**/*.{js}": [
      "eslint . --fix",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "lint-staged"
    }
  },
  "prettier": {
    "printWidth": 150,
    "singleQuote": true
  },
  "dependencies": {
    "date-fns": "^2.29.3",
    "generate-password": "^1.7.0",
    "got": "^12.1.0"
  }
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
> I tried to update the got version to 12.1.0

The latest version is 12.5.3. Try that version.

**Comment by marijana-rukavina** [comment]
It didn't help :(

**Comment by Fania** [comment]
I've got the same issue on MacOS (Ventura 13.1). I also updated `got` to 12.5.3 but it still says this:
```
got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
No fix available
```

**Comment by Afaliya0-0Liong** [comment]
(ubuntu 20.04LTS)I tried the latest got. It works!

**Comment by sindresorhus** [comment]
> I've got the same issue on MacOS (Ventura 13.1). I also updated got to 12.5.3 but it still says this:

The warning is referring to Got v11, not v12.
