### ISSUE TITLE
ESM only? breaks typescript projects

### ISSUE THREAD

**Issue by dcsan** [sindresorhus/got#2216]
#### What would you like to discuss?

When i try to run this with typescript I get the error below.
Is this module now ESM only? It doesn't play with typescript well even on new projects, never mind large code bases.

```
$ ts-node src/testImages.ts
/Users/dc/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/dc/dev/revel/revel-tasks/node_modules/got/dist/source/index.js from /Users/dc/dev/revel/revel-tasks/src/testImages.ts not supported.
```

https://javascript.plainenglish.io/how-to-correctly-use-typescript-module-import-syntax-and-settings-in-various-circumstances-e98bfa87f70f

the main reason I went for got is cos node-fetch is now ESM only. 

If you are committed to the breaking change, can you recommend an alternative that isn't plagued by an ESM only base?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sindresorhus** [comment]
> If you are committed to the breaking change, can you recommend an alternative that isn't plagued by an ESM only base?

https://www.npmjs.com/package/got-cjs

**Comment by hexboy** [comment]
If the package is used in an async context, you could use [await import(…)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) from CommonJS instead of `require(…)`.

```js
async function getData() {
  const { default: got } = await import('got');
  const response = await got.get(url);
  ...
}
```
