### ISSUE TITLE
Improve retries option defaults

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#222]
This should be done. There is a problem with current defaults for `retries` – almost every person, that uses `got` stumbles on hanging calls for some urls and almost every time this caused by silent retries.

Here some issues with this option – #215 #187 #156 (and there is more people, who asks me at work about it 😳).

Would love hear suggestions about this.

**Comment by sindresorhus** [comment]
Shouldn't we look more into why it's hanging? Maybe there's something we could improve regarding the retry logic or even reduce the number of retries to `1` or `2`. It would be too bad to set it to `0`. Network is generally pretty unstable and having retrying by default in theory means more reliable network requests.

> almost every person, that uses got stumbles on hanging calls for some urls and almost every time this caused by silent retries.

I've never stumbled upon that, and I use `got` in a lot of modules.

**Comment by floatdrop** [comment]
@sindresorhus yeah, maybe I'm exaggerating things, but fact is – most of questions about `got` in Jabber is resolved by telling people about `retries`. If you know about it, it is never an issue, but if you don't – it takes quite amount of time to figure it out.

Maybe docs improvement will help, maybe reducing retries. Maybe both.

**Comment by sindresorhus** [comment]
@floatdrop No, you're not exaggerating if it's the case that it's just hanging. That's bad. Having a test case that reproduces the hanging would be very beneficial, so we could do some experimenting. We should understand the problem before trying to fix it. Could be something unrelated to the number of retries. Maybe the `is-retry-allowed` blacklist is missing a problematic code.

**Comment by jewelsjacobs** [comment]
My issue is doc related.  I'm not sure how to use the retries function properly so I can't figure out how to generate a decent log error.  I'm catching my request errors in a promise function. 

How do I define the number of retries with the function if the function is supposed to return a `delay in milliseconds`?

Is it this?

```
options.retries = function(retry, error) {
                if (error) {
                    // in a promise
                    return new Error(error));
                }

    this.retry = 5;
    return 2000;
}
```

I tried looking at the test for retry for some guidance https://github.com/sindresorhus/got/blob/master/test/retry.js and the source itself but couldn't figure out the best way to define the number of retries using the function option.

Any suggestions?  Help would be much appreciated!

Thanks!

**Comment by sindresorhus** [comment]
@floatdrop What should we do about this? I wonder if it works better in latest Node.js?

**Comment by floatdrop** [comment]
@sindresorhus I would go with reducing retry delay time from exponential to constant, because requests likely land in different backend (clouds and stuff). What do you think about this?

**Comment by sindresorhus** [comment]
Can you elaborate a bit more. How will exponential=>constant help? I don't even know what the problem actually was.

**Comment by floatdrop** [comment]
@sindresorhus for now we use [this](https://github.com/sindresorhus/got/blob/master/index.js#L285) formula for calculating delay between retries – it grows exponentially. If server is not responding, we will wait 1, 2, 4, 8, 16 seconds (w/o adding timeout time). It sums up to half a minute waiting on dead service. If user set timeout to `100ms` – isn't it expected to run about a second with 5 retries?

In other hand, backing up retries can reduce traffic amplification, when something goes wrong and all services start retrying endpoint.

**Comment by sindresorhus** [comment]
I think we should lower the default retry to `3` in the next major. I can't imagine something that is working needing more than 2 requests, and 3 just to be sure. That would make the default max 7 seconds. Is that acceptable?

---

> In other hand, backing up retries can reduce traffic amplification, when something goes wrong and all services start retrying endpoint.

[Thundering herd problem](https://en.m.wikipedia.org/wiki/Thundering_herd_problem)

**Comment by sindresorhus** [comment]
@AlexTes Any thoughts?
