### ISSUE TITLE
Security: cacheable-request should be updated on the 11.x.x version

### ISSUE THREAD

**Issue by yoavain** [sindresorhus/got#2220]
#### Describe the bug

Got version 11.8.6 uses a vulnerable version of cacheable-request:
https://github.com/jaredwray/cacheable-request/security/advisories/GHSA-8x6c-cv3v-vp6g

Seems that version 10.2.7 of cacheable-request has a fix.
The GitHub repo still doesn't show that release, but npmjs repo has it

**Comment by yoavain** [comment]
Seems from the code, that it's not a simple dependency update. It requires a backport of some changes from the main branch (12.x). 
Unfortunately, many projects that use 11.8.6 are unable to upgrade to the 12.x version

**Comment by arnulfojr** [comment]
Looks like cacheable-request dropped support for v8 at EOY 2022. Sadly, v8 was the last version supporting CJS, that means that it might actually be really hard to pull the actual fix on got's 11.8.x ...

https://github.com/jaredwray/cacheable-request/blob/main/SECURITY.md

I reached out in https://github.com/jaredwray/cacheable-request to see if it's possible to have that fix in a CJS version of the package... maybe that simplifies/unblocks(?) the adoption.

**Comment by dscalzi** [comment]
Upgrading cacheable-request from v7 to v8 in got 11 should fix the issue.

**Comment by yukha-dw** [comment]
I don't think this is really a vulnerability?
`got v11.8.6` use `cacheable-request ^7.0.2`, which requires `http-cache-semantics ^4.0.0` (there is a caret there, including the fix `v4.1.1`)
https://github.com/jaredwray/cacheable-request/blob/635f3698f9eaa3fe93e46d82f398efd970852de7/package.json#L34 

Maybe the security alert will be dismissed after this PR
https://github.com/github/advisory-database/pull/1693

**Comment by dscalzi** [comment]
The security advisory was withdrawn, so this should be closed.
