### ISSUE TITLE
Back-port of CVE fix

### ISSUE THREAD

**Issue by nihillno** [sindresorhus/got#2244]
Is it possible that the fix for this:

https://github.com/advisories/GHSA-rc47-6667-2j5j

...be back-ported to a version of got prior to the move from CommonJS to ESmodule? I need to update this module in a large project that is CommonJS and the two systems aren't playing nicely with each other.

**Comment by sindresorhus** [comment]
Sorry. We are no longer supporting v11. You can either patch it yourself using the patch-package package or use the latest version with `await import()` which does work from CommonJS.

**Comment by nihillno** [comment]
@sindresorhus Thanks. Using "await import" triggers the old "Cannot use keyword 'await' outside an async function" error. Which commit should I be looking for to patch locally?
