### ISSUE TITLE
ECONNEREFUSED or ENOTFOUND crashes the application

### ISSUE THREAD

**Issue by venuziano** [sindresorhus/got#2246]
#### Describe the bug

 - Node.js version: v17.9.0
 - OS & version: Windows 10
 - GOT version: 12.6.0

When an endpoint call return ECONNEREFUSED or ENOTFOUND the application crashes without any error handling or catch. I tried to add some try-catchs but it didn't work.

#### Actual behavior
![image](https://user-images.githubusercontent.com/15386984/229532077-4d8b82e7-e081-420e-bdfe-b8340c6402f0.png)
![image](https://user-images.githubusercontent.com/15386984/229532618-ecbdebbf-b79c-40e6-87bc-0932b7dd96f4.png)

#### Expected behavior

Something that doesn't crash the application. 

#### Code to reproduce

Just call an invalid URL, example: https://asdasdasd.com

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
It looks like you're just not catching and handling the errors thrown by Got.

**Comment by venuziano** [comment]
I was catching and handling the error incorect, found the property way. Thanks @sindresorhus!

**Comment by dog-master** [comment]
> I was catching and handling the error incorect, found the property way. Thanks @sindresorhus!

Have any vaild commit？ I am also experiencing this problem.
