### ISSUE TITLE
`http.request` now receives a `timeout` option

### ISSUE THREAD

**Issue by sotojuan** [sindresorhus/got#226]
This is new in [Node v6.8.0](https://nodejs.org/en/blog/release/v6.8.0). PR [here](https://github.com/nodejs/node/pull/8101).

Not sure what the implications for `got` are but thought I'd let you know!

**Comment by kevva** [comment]
All tests passes using `6.8.0` so I guess it doesn't have any direct implications.

**Comment by sindresorhus** [comment]
@floatdrop Maybe it could simplify your `timed-out` module?

**Comment by floatdrop** [comment]
@sindresorhus maybe, but it was not backported to `4.x` branch. So somewhere in the future.

**Comment by floatdrop** [comment]
Dups #257 – will be resolved there.
