### ISSUE TITLE
file:// protocol support

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#227]
It'd be convenient to not have to handle this ourselves each time we need it.

Use cases:
- Requesting data from URLs in an HTML document where such a protocol is most likely to occur

**Comment by sindresorhus** [comment]
Why?

**Comment by stevenvachon** [comment]
Original comment updated.

**Comment by sindresorhus** [comment]
Haven't had a chance to think this through yet, but sounds like a pretty good venue for security issues.

[`fetch()` intentionally doesn't support `file://`.](https://github.com/github/fetch/pull/92#issuecomment-140665932)

**Comment by stevenvachon** [comment]
`file://` is part of the `fetch()` spec: https://fetch.spec.whatwg.org/#basic-fetch

**Comment by sindresorhus** [comment]
Please read the actual text there about it.

**Comment by stevenvachon** [comment]
Make it optional, then. That way, we could do something like:
```js
const baseUrl = new URL("http://domain/")
const url = new URL("file://dir/file")
got(url, { supportFileProtocol: baseUrl.protocol==="file:" })
```

**Comment by stevenvachon** [comment]
Now that I think of it, a separate package should be written to handle this as it can then be used with any similar request library. If we want, we can document its use in this package's readme.

**Comment by tommedema** [comment]
@stevenvachon are you aware of any such package?

**Comment by stevenvachon** [comment]
@tommedema no, but I also haven't begun to use this library yet either.

**Comment by sindresorhus** [comment]
Going to pass on this. See https://github.com/bitinn/node-fetch/issues/75#issuecomment-299755555 for reasoning.

**Comment by szmarczak** [comment]
I don't think it's a good idea, it could lead to potential security issues.
