### ISSUE TITLE
Wrong type for retry option

### ISSUE THREAD

**Issue by Cluster2a** [sindresorhus/got#2272]
#### Describe the bug

 - Node.js version: 19
 - OS & version: 

#### Actual behavior

According to the `index.d.ts` the `GotOptions` accept a number or a `RetryOptions` for the `retry` attribute.
Passing the attribute leads to an exception: `RequestError: Unexpected retry option: retries`

#### Expected behavior
Passing the retry parameter as in the code below would not lead to an exception.
Both ways fail, but should be good, according to @types/got.

#### Code to reproduce

```js
const response = await got(server.config.MINIO_HOST, {
	timeout: {
		lookup: 100,
		connect: 50,
		secureConnect: 50,
		socket: 1000,
		send: 10000,
		response: 1000
	},
	retry: {
		retries: 5
	}
});
```

```js
const response = await got(server.config.MINIO_HOST, {
	timeout: {
		lookup: 100,
		connect: 50,
		secureConnect: 50,
		socket: 1000,
		send: 10000,
		response: 1000
	},
	retry: 5
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Got ships with its own types. `@types/got` are outdated.
