### ISSUE TITLE
Why not CJS?

### ISSUE THREAD

**Issue by eldoy** [sindresorhus/got#2280]
#### What would you like to discuss?

After installing Got my app crashed because it's ESM only. I'm using it in every lib. Now you're forcing me to waste so much time upgrading, or I'll be stuck with old versions forever.

Why not make it work for CJS? What's the problem? You are making the entire ecosystem unstable with these decisions, can't trust any of your code, completely erratic behavior.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849#gistcomment-3850849
