### ISSUE TITLE
Generate self-signed certificates for tests

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#23]
For now we are using [certificates](https://github.com/sindresorhus/got/tree/master/test/ssl) from [request/request](https://github.com/request/request/tree/master/tests/ssl). We need to generate our own :)

**Comment by silverwind** [comment]
I use the `pem` module for this in another project, like this:

````js
require("pem").createCertificate({ days: 365, selfSigned: true }, function (err, keys) {
  // keys.serviceKey = private key
  // keys.certificate = certificate
}
````

**Comment by floatdrop** [comment]
Thanks @silverwind, it worked!

**Comment by sindresorhus** [comment]
Thanks for the tip @silverwind :)
