### ISSUE TITLE
Request fails with NGHTTP2_INTERNAL_ERROR for http2 requests

### ISSUE THREAD

**Issue by teammakdi** [sindresorhus/got#2300]
#### Describe the bug

 - Node.js version: 18.17.0
 - OS & version: Ubuntu
 - Got version: 13.0.0

#### Actual behavior

```
RequestError: Stream closed with error code NGHTTP2_INTERNAL_ERROR
```

#### Expected behavior

Response with status 200

#### Code to reproduce

```js
import got from 'got';

async function main() {
    try {
        const response = await got('https://frogtoon.com/ads.txt', {
            http2: true,
        });
        console.log(response.body);
    } catch (error) {
        console.log(error);
    }
}

main()
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

Original Issue: https://github.com/apify/crawlee/issues/2081

**Comment by teammakdi** [comment]
Works with http2 as `false`

**Comment by teammakdi** [comment]
@sindresorhus can you please have a look?

**Comment by sindresorhus** [comment]
HTTP2 support is handled by https://github.com/szmarczak/http2-wrapper

// @szmarczak
