### ISSUE TITLE
Socket hang up error when using the delete method with stream API

### ISSUE THREAD

**Issue by VanTigranyan** [sindresorhus/got#2303]
#### Describe the bug

 - Node.js version:  21
 - OS & version:  MacOS Sonoma

When using the stream API, all methods work correctly, but when using the delete method, we get a `socket hang up` error every time. I am not sure what is so specific about the delete method, but this happens only when using it. I tried to change the agent and the response type; I even tested this on my friends' machines, and I can reproduce it on any machine. 

#### Actual behavior

Using the delete method with the stream API ends up with a `socket hang up` error consistently.

#### Expected behavior

Using the delete method with the stream API should be able to connect to the provided resource and return a response.

#### Code to reproduce

```js
import got from 'got';
import https from 'https';

const stream = got.stream.delete('https://jsonplaceholder.typicode.com/posts/1');

stream
    .on('request', (request) => {
        console.log('Request event triggered\n', request.headers);
    })
    .on('data', chunk => {
        console.log('Data event triggered\n');
    })
    .on('response', (response) => {
        console.log('Response event triggered\n');
        response.on('end', () => {
            console.log('Response END is called\n');
        });
    })
    .on('end', () => console.log('END called\n'))
    .on('finish', () => console.log('FINISH called\n'))
    .on('pause', () => console.log('PAUSE called\n'))
    .on('close', () => console.log('CLOSE called\n'))
    .on('error', (error) => {
        console.log('Error event triggered\n', error, '\n');
    });
```

#### Checklist

- [*] I have read the documentation.
- [*] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
You need to pass `{body: ''}` as option. See: https://github.com/sindresorhus/got/blob/main/documentation/3-streams.md#new-requesturl-options-defaults

**Comment by VanTigranyan** [comment]
Oh wow. @sindresorhus Thank you so much for the quick response. That worked. Could you explain why I need to set the body to empty string explicitly if it's a delete method, please? I thought delete methods don't have body (usually).

**Comment by sindresorhus** [comment]
I'm honestly not sure. I didn't add that part. Probably some weird behavior with Node.js streams. Maybe @szmarczak remembers.

**Comment by VanTigranyan** [comment]
I would assume if we don't pass a body, the library would set it to an empty string (if it's required). @szmarczak do you know why we need to do that instead? Thanks a lot in advance.
