### ISSUE TITLE
Allow dynamically set followRedirect

### ISSUE THREAD

**Issue by VanTigranyan** [sindresorhus/got#2307]
#### What problem are you trying to solve?
Request library allows passing `followRedirect` as a function that gets the intermediate response and then returns boolean, by which the library decides whether to follow the redirect. Got doesn't allow this. As a workaround, I tried to change options.followRedirect to false in beforeRedirect hook, but that doesn't work as one would expect. 

#### Describe the feature
Allow both plain boolean and function type for the `followRedirect` option.
I already made proper changes in the code and in README and added tests to make sure all works correctly.
https://github.com/sindresorhus/got/pull/2306
...

```js
  const {statusCode} = await got('temporary', {followRedirect(response) {
        t.is(response.headers.location, '/redirect');
        return false;
  }});
```
#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/got/commit/7c3f14700fc1c77f58eb0072d152624b6b6f3af5
