### ISSUE TITLE
Unexpected lowercasing of headers

### ISSUE THREAD

**Issue by f-mer** [sindresorhus/got#231]
Lowercasing of headers is rather unexpected.
I have to communicate with some services that seem to be strict about casing of headers and sending headers lowercased does not give back the expected response. Took me some time to figure out that [got](https://github.com/sindresorhus/got) lowercases headers.

I see that it is easier to merge options this way but it would be nice to respect casing .

Related #50

**Comment by sindresorhus** [comment]
As I already commented in #50, headers are case-insensitive.

**Comment by f-mer** [comment]
Some services do not respect [rfc](https://tools.ietf.org/html/rfc2616#section-4.2) and misbehave as pointed out [here](https://github.com/request/request/issues/346#issuecomment-10216859).
Would it be possible to remove the default headers safely?

**Comment by sindresorhus** [comment]
`got` is made for compliant servers. Sounds like `request` would be a better choice for you :)

**Comment by f-mer** [comment]
Thanks for taking your time. Really like the simplicity of got.
