### ISSUE TITLE
Error object doesn't contain response

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#232]
The docs say the error object contains the response in promise mode, but it doesn't seem to be the case.

```
try {
  var resp = await got(...)
} catch(e) {
  // e.response is not available
}
```

If the request fails due to a 404, the response should still be available so you can see the output, etc. How can that be done?

**Comment by sindresorhus** [comment]
This test contradicts your statement: https://github.com/sindresorhus/got/blob/205e224bcd3e1cc756841c62d0f6a0e503d7dfbb/test/error.js#L24

Submit a failing test and we'll look into it ;)

**Comment by Jakobud** [comment]
Maybe I'm also confused on this but I'm experiencing the same thing. I disable my internet connection in order to force a timeout error:

```
got(api.somewhere.com, {
        json: true,
        timeout: 5000
      }).then((res) => {
        // some code here
      }).catch((err) => {
        console.error('timed out');
        console.error(err.response);
        console.error(err);
      });
```

That prints out:

```
timed out
undefined
RequestError: getaddrinfo ENOTFOUND api.somewhere.com api.somewhere.com:443
    at ClientRequest.req.once.err (d:\myproject\node_modules\got\index.js:70:21)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1016:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Am I just misunderstanding something here?

**Comment by satazor** [comment]
@Jakobud the response is only available if the request went trough and a response was received. If a network error occurred, such as being offline, then there will be no response.

**Comment by rightaway** [comment]
@Jakobud Do you get a `response` property if the error is a 404?

**Comment by Jakobud** [comment]
Yes I do get the `response` with a 404. I wasn't aware that I would get no response without a network connection.

Can you guys advice a good way to write a test that simulates a timeout when accessing a url?

**Comment by kevva** [comment]
https://github.com/node-nock/nock#socket-timeout

**Comment by Jakobud** [comment]
> @Jakobud the response is only available if the request went trough and a response was received. If a network error occurred, such as being offline, then there will be no response.

Does this mean that if a request times out, I will also not get a response in that situation? Thanks,

**Comment by floatdrop** [comment]
@Jakobud yes, until `got` have an response object it can not assign it to error. In timeout case – there is no response by definition.
