### ISSUE TITLE
NPM Says: Types are not integrated

### ISSUE THREAD

**Issue by sequencerr** [sindresorhus/got#2338]
https://www.npmjs.com/package/got
DefinitelyTyped icon, indicating that this package has TypeScript declarations provided by the separate @types/got package

https://github.com/sindresorhus/got?tab=readme-ov-file#comparison:~:text=TypeScript%20support

But they are actually are there.

**Comment by sindresorhus** [comment]
That's a problem with the npm site, not this package. They don't support the `exports` field in package.json.
