### ISSUE TITLE
Get intermediate redirect urls

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#234]
It would be useful if there were a way to get all redirected urls in a request. So if you request url `a`, but it redirects to `b` which redirects to `c` and finally to `d`, if there were a `urls` property on the response that would return `['a', 'b', 'c', 'd']`. There's the `redirect` event that could be used to capture these urls but that seems to only work when using streams.

**Comment by floatdrop** [comment]
I saw nice trick in [aggregate-error](https://github.com/sindresorhus/aggregate-error) – we can make `url` an iterable with `toString` method that get last url. But this will be surprising for some people, I guess.

**Comment by sindresorhus** [comment]
Let's go the explicit route with a `urls` property.
