### ISSUE TITLE
POSTs whose bodys are instances of createReadStream hang with latest node

### ISSUE THREAD

**Issue by stephen-willoughby** [sindresorhus/got#2341]
#### Describe the bug

 - Node.js version: 20.11.1
 - OS & version: macos 14.4

Whilst trying to move to support node 20, I have come across the following behaviour. If I drop to node 20.9.0 it works correctly. If I replace `got` with `axios` it works correctly.

Of note is https://github.com/nock/nock/issues/2595 but as switching to axios seems to work and everyone on the nock issue is using `got`, `got` seems the more likely candidate.

#### Actual behavior
this code completes with 13 and nothing outputted
...

#### Expected behavior
I should outputted the body `{ foo: 'bar' }` and `complete`
...

#### Code to reproduce

Note you need to provide `somefile.txt`, its content is irrelevant.
```js
import nock from 'nock'
import { createReadStream } from 'fs'
import got from 'got'

const myFile = 'somefile.txt'
const host = 'http://example.com'
const path = '/some/path'
const response = { foo: 'bar' }
const options = {
  method: 'post',
  url: host + path,
  body: createReadStream(myFile)
}

nock(host)
  .post(path)
  .reply(200, response)

try {
  const result = await got(options)
  console.log(result.body)
} catch (error) {
  console.error('error')
  console.error(error)
}
console.log('complete')

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by stephen-willoughby** [comment]
For old node

```
{"foo":"bar"}
complete

Process finished with exit code 0
```

for node 20.11.1

```
Process finished with exit code 13
```

**Comment by sindresorhus** [comment]
Does it work without Nock? If yes, then the issue is definitely Nock as it should work with anything that normally works without it.

You can replace Nock with https://httpbin.org for testing.

**Comment by stephen-willoughby** [comment]
Yes, it works without nock, replacing it with https://httpbin.org/post, but similarly nock works with axios in place of got.

**Comment by masontikhonov** [comment]
@sindresorhus I tend to agree that it _might_ be an issue with Got, in particular with `asPromise(request)`, which returns promise that never resolves in some rare conditions (changes to streams that were done in node v20.10.0 + some nock behavior).

**Comment by aduh95** [comment]
FYI patching Nock source the following way resolved the issue for me:

```diff
index d82c2446b540759cbc54ad7b26222a80109b8ec9..bf24add845d12e436c97b3ea5e2e38f87b77d489 100644
--- a/lib/intercepted_request_router.js
+++ b/lib/intercepted_request_router.js
@@ -68,7 +68,7 @@ class InterceptedRequestRouter {
     // For parity with Node, it's important the socket event is emitted before we begin playback.
     // This flag is set when playback is triggered if we haven't yet gotten the
     // socket event to indicate that playback should start as soon as it comes in.
-    this.readyToStartPlaybackOnSocketEvent = false
+    this.readyToStartPlaybackOnSocketEvent = true

     this.attachToReq()

```

**Comment by stephen-willoughby** [comment]
this is no longer an issue for me
