### ISSUE TITLE
Is TypeScript support outdated? 

### ISSUE THREAD

**Issue by Kinuseka** [sindresorhus/got#2344]
#### What would you like to discuss?

Upon looking at the docs, it seems that `@types/got` does not align to whatever is mentioned to the docs. The functions are either missing in types or lacking support in some function.

For example `Options` does not exist but in docs there is a mention of it. 

Upon looking at the source code, it seems it was apparently made for Got v9.6 which is very outdated. 

I have been looking around at the docs but it seems there's no mention of TS installations.

#### Checklist

- [ /] I have read the documentation.

**Comment by sindresorhus** [comment]
Got ships with its own types.
