### ISSUE TITLE
'url' property not on response

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#235]
`response.url` is undefined. To get the url after redirects I need to use `response.socket._httpMessage.res.url`.

```
  return got(url)
    .then(async (response) => {
      console.log(response.requestUrl)
      console.log(response.url)
      console.log(response.socket._httpMessage.res.url)
    })
```

Using version 6.5.0.

**Comment by sindresorhus** [comment]
Would you mind submitting a [failing test](https://github.com/avajs/ava#failing-tests)? That would make it a lot easier for us to fix the problem ;)

**Comment by kevva** [comment]
We only set `url` when there are redirects. Maybe we should stay consistent and always add it @sindresorhus @floatdrop?

**Comment by floatdrop** [comment]
@kevva I think #230 covers this case, it just not released yet.

**Comment by kevva** [comment]
@floatdrop, nah, that's only `requestUrl`. He want the final URL that we set [here](https://github.com/sindresorhus/got/blob/master/index.js#L37). It's not that useful when there aren't any redirects but API-wise I think it's better to be consistent anyway.

**Comment by sindresorhus** [comment]
Agreed
