### ISSUE TITLE
Use Vite, Module "node:stream" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by TyCoding** [sindresorhus/got#2368]
error: 

Module "node:stream" has been externalized for browser compatibility. Cannot access "node:stream.Readable" in client cod

Using got('http://') in a new Vite project will directly cause this error, which seems to be a node:stream problem. How can I solve this problem?

**Comment by sindresorhus** [comment]
This would be a question to ask on the Vite repo, not here.
