### ISSUE TITLE
Better documentation for retries function

### ISSUE THREAD

**Issue by jewelsjacobs** [sindresorhus/got#237]
I'm not sure how to use the retries function properly so I can't figure out how to generate a decent log error.  I'm catching my request errors in a promise function. 

How do I define the number of retries with the function if the function is supposed to return a `delay in milliseconds`?

Is it this?

```js
options.retries = function(retry, error) {
    if (error) {
        // in a promise
        return new Error(error));
    }

    this.retry = 5;
    return 2000;
}
```

I tried looking at the test for retry for some guidance https://github.com/sindresorhus/got/blob/master/test/retry.js and the source itself but couldn't figure out the best way to define the number of retries using the function option.

Any suggestions?  Help would be much appreciated!

Thanks!

**Comment by floatdrop** [comment]
@jewelsjacobs you can look, how retries implemented in [`got` source code](https://github.com/sindresorhus/got/blob/master/index.js#L272).

First argument in callback is current number of retries, that happened before this callback, so you can just check it's value:

```js
options.retries = function(retry, error) {
    if (retry > 5) {
        // got promise will be rejected with `error`
        return 0;
    }

    return 2000;
}
```

**Comment by floatdrop** [comment]
Closing in favor of #222
