### ISSUE TITLE
An error occurred when introducing got

### ISSUE THREAD

**Issue by Inteside** [sindresorhus/got#2376]
`File: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\decompress-response@6.0.0\node_modules\decompress-response\index.js:1:1
  × Module not found: Can't resolve 'stream' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\decompress-response@6.0.0\node_modules\decompress-response'
   ╭─[2:33]
 1 │ 'use strict';
 2 │ const {Transform, PassThrough} = require('stream');
   ·                                  ─────────────────
 3 │ const zlib = require('zlib');
 4 │ const mimicResponse = require('mimic-response');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\decompress-response@6.0.0\node_modules\decompress-response\index.js:1:1
  × Module not found: Can't resolve 'zlib' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\decompress-response@6.0.0\node_modules\decompress-response'
   ╭─[3:13]
 1 │ 'use strict';
 2 │ const {Transform, PassThrough} = require('stream');
 3 │ const zlib = require('zlib');
   ·              ───────────────
 4 │ const mimicResponse = require('mimic-response');
 5 │ 
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\agent.js:1:1
  × Module not found: Can't resolve 'url' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[4:14]
 2 │ // See https://github.com/facebook/jest/issues/2549
 3 │ // eslint-disable-next-line node/prefer-global/url
 4 │ const {URL} = require('url');
   ·               ──────────────
 5 │ const EventEmitter = require('events');
 6 │ const tls = require('tls');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\agent.js:1:1
  × Module not found: Can't resolve 'tls' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[6:12]
 4 │ const {URL} = require('url');
 5 │ const EventEmitter = require('events');
 6 │ const tls = require('tls');
   ·             ──────────────
 7 │ const http2 = require('http2');
 8 │ const QuickLRU = require('quick-lru');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\agent.js:1:1
  × Module not found: Can't resolve 'http2' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[7:14]
 5 │ const EventEmitter = require('events');
 6 │ const tls = require('tls');
 7 │ const http2 = require('http2');
   ·               ────────────────
 8 │ const QuickLRU = require('quick-lru');
 9 │ const delayAsyncDestroy = require('./utils/delay-async-destroy.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\auto.js:1:1
  × Module not found: Can't resolve 'url' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[4:32]
 2 │ // See https://github.com/facebook/jest/issues/2549
 3 │ // eslint-disable-next-line node/prefer-global/url
 4 │ const {URL, urlToHttpOptions} = require('url');
   ·                                 ──────────────
 5 │ const http = require('http');
 6 │ const https = require('https');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\auto.js:1:1
  × Module not found: Can't resolve 'http' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[5:13]
 3 │ // eslint-disable-next-line node/prefer-global/url
 4 │ const {URL, urlToHttpOptions} = require('url');
 5 │ const http = require('http');
   ·              ───────────────
 6 │ const https = require('https');
 7 │ const resolveALPN = require('resolve-alpn');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\auto.js:1:1
  × Module not found: Can't resolve 'https' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[6:14]
 4 │ const {URL, urlToHttpOptions} = require('url');
 5 │ const http = require('http');
 6 │ const https = require('https');
   ·               ────────────────
 7 │ const resolveALPN = require('resolve-alpn');
 8 │ const QuickLRU = require('quick-lru');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\client-request.js:1:1
  × Module not found: Can't resolve 'url' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[4:32]
 2 │ // See https://github.com/facebook/jest/issues/2549
 3 │ // eslint-disable-next-line node/prefer-global/url
 4 │ const {URL, urlToHttpOptions} = require('url');
   ·                                 ──────────────
 5 │ const http2 = require('http2');
 6 │ const {Writable} = require('stream');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\client-request.js:1:1
  × Module not found: Can't resolve 'http2' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[5:14]
 3 │ // eslint-disable-next-line node/prefer-global/url
 4 │ const {URL, urlToHttpOptions} = require('url');
 5 │ const http2 = require('http2');
   ·               ────────────────
 6 │ const {Writable} = require('stream');
 7 │ const {Agent, globalAgent} = require('./agent.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\client-request.js:1:1
  × Module not found: Can't resolve 'stream' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[6:19]
 4 │ const {URL, urlToHttpOptions} = require('url');
 5 │ const http2 = require('http2');
 6 │ const {Writable} = require('stream');
   ·                    ─────────────────
 7 │ const {Agent, globalAgent} = require('./agent.js');
 8 │ const IncomingMessage = require('./incoming-message.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\incoming-message.js:1:1
  × Module not found: Can't resolve 'stream' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[2:19]
 1 │ 'use strict';
 2 │ const {Readable} = require('stream');
   ·                    ─────────────────
 3 │ 
 4 │ class IncomingMessage extends Readable {
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\index.js:1:1
  × Module not found: Can't resolve 'http2' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source'
   ╭─[2:14]
 1 │ 'use strict';
 2 │ const http2 = require('http2');
   ·               ────────────────
 3 │ const {
 4 │     Agent,
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies\h1-over-h2.js:1:1
  × Module not found: Can't resolve 'tls' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies'
   ╭─[2:12]
 1 │ 'use strict';
 2 │ const tls = require('tls');
   ·             ──────────────
 3 │ const http = require('http');
 4 │ const https = require('https');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies\h1-over-h2.js:1:1
  × Module not found: Can't resolve 'http' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies'
   ╭─[3:13]
 1 │ 'use strict';
 2 │ const tls = require('tls');
 3 │ const http = require('http');
   ·              ───────────────
 4 │ const https = require('https');
 5 │ const JSStreamSocket = require('../utils/js-stream-socket.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies\h1-over-h2.js:1:1
  × Module not found: Can't resolve 'https' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies'
   ╭─[4:14]
 2 │ const tls = require('tls');
 3 │ const http = require('http');
 4 │ const https = require('https');
   ·               ────────────────
 5 │ const JSStreamSocket = require('../utils/js-stream-socket.js');
 6 │ const {globalAgent} = require('../agent.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies\h2-over-h1.js:1:1
  × Module not found: Can't resolve 'http' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies'
   ╭─[2:13]
 1 │ 'use strict';
 2 │ const http = require('http');
   ·              ───────────────
 3 │ const https = require('https');
 4 │ const Http2OverHttpX = require('./h2-over-hx.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies\h2-over-h1.js:1:1
  × Module not found: Can't resolve 'https' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies'
   ╭─[3:14]
 1 │ 'use strict';
 2 │ const http = require('http');
 3 │ const https = require('https');
   ·               ────────────────
 4 │ const Http2OverHttpX = require('./h2-over-hx.js');
 5 │ const getAuthorizationHeaders = require('./get-auth-headers.js');
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies\initialize.js:1:1
  × Module not found: Can't resolve 'url' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\proxies'
   ╭─[4:14]
 2 │ // See https://github.com/facebook/jest/issues/2549
 3 │ // eslint-disable-next-line node/prefer-global/url
 4 │ const {URL} = require('url');
   ·               ──────────────
 5 │ const checkType = require('../utils/check-type.js');
 6 │ 
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils\calculate-server-name.js:1:1
  × Module not found: Can't resolve 'net' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils'
   ╭─[2:15]
 1 │ 'use strict';
 2 │ const {isIP} = require('net');
   ·                ──────────────
 3 │ const assert = require('assert');
 4 │ 
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils\calculate-server-name.js:1:1
  × Module not found: Can't resolve 'assert' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils'
   ╭─[3:15]
 1 │ 'use strict';
 2 │ const {isIP} = require('net');
 3 │ const assert = require('assert');
   ·                ─────────────────
 4 │ 
 5 │ const getHost = host => {
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils\js-stream-socket.js:1:1
  × Module not found: Can't resolve 'stream' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils'
   ╭─[2:15]
 1 │ 'use strict';
 2 │ const stream = require('stream');
   ·                ─────────────────
 3 │ const tls = require('tls');
 4 │ 
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils\js-stream-socket.js:1:1
  × Module not found: Can't resolve 'tls' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\http2-wrapper@2.2.1\node_modules\http2-wrapper\source\utils'
   ╭─[3:12]
 1 │ 'use strict';
 2 │ const stream = require('stream');
 3 │ const tls = require('tls');
   ·             ──────────────
 4 │ 
 5 │ // Really awesome hack.
   ╰────/nFile: D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\resolve-alpn@1.2.1\node_modules\resolve-alpn\index.js:1:1
  × Module not found: Can't resolve 'tls' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\resolve-alpn@1.2.1\node_modules\resolve-alpn'
   ╭─[2:12]
 1 │ 'use strict';
 2 │ const tls = require('tls');
   ·             ──────────────
 3 │ 
 4 │ module.exports = (options = {}, connect = tls.connect) => new Promise((resolve, reject) => {
   ╰────/nFile: javascript/esm|D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\@szmarczak+http-timer@5.0.1\node_modules\@szmarczak\http-timer\dist\source\index.js:1:1
  × Module not found: Can't resolve 'util' in 'D:\Desktop\教务系统逆向\rsbuild-project\node_modules\.pnpm\@szmarczak+http-timer@5.0.1\node_modules\@szmarczak\http-timer\dist\source'
   ╭─[2:22]
 1 │ import { errorMonitor } from 'events';
 2 │ import { types } from 'util';
   ·                       ──────
 3 │ import deferToConnect from 'defer-to-connect';
 4 │ const timer = (request) => {
   ╰────/nFile: node:buffer:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:crypto:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:dns:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:dns" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:events:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:events" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:http:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:http" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:https:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:https" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:net:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:net" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:os:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:os" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:process:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:process" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:stream:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:stream" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:tls:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:tls" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:url:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:url" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs./nFile: node:util:1:1
  × Module build failed:
  ╰─▶   × Reading from "node:util" is not handled by plugins (Unhandled scheme).
        │ Rspack supports "data:" and "file:" URIs by default.
        │ You may need an additional plugin to handle "node:" URIs.`

**Comment by sindresorhus** [comment]
This is a problem with your build config, not this package.
