### ISSUE TITLE
Allow runtime detection of the `got` version

### ISSUE THREAD

**Issue by osher** [sindresorhus/got#2385]
#### What problem are you trying to solve?

* I'm modernizing some codebase that used `got@10`, migrating to `got@14`.
* That codebase is composing `user-agent` header strings that included the version of `got` among other things like the version of the service and the runtime version of node.
* we do not [use `package-lock.json`](https://medium.com/israeli-tech-radar/the-truth-about-package-lock-json-6ac0e8072ef8), and we want to reflect the version that landed in the distribution.
* I used to do that by `require('got/package').version`, however, since the introduction of the `package.json:exports` section - I cannot do that anymore 😞 

#### Describe the feature

Allow runtime detection of the `got` version. 

Two ways to do that:

* `got` should export a `version` field, that should reflect the `version` field in the package.json

e.g.: 

```js
import { pkg: { name, version } } from '../config.js'  //<-- reads from local package.json
import got from `got`

const { version: gotVersion } = got

const userAgentHeader = `${name}/${version}; nodejs/${process.version}; got/${gotVersion}`
```

or, alternatively

* allow to import the `package.json`

```js
import { pkg: { name, version } } from '../config.js'  //<-- reads from local package.json
import gotPackage from `got/pacakge.json`
const { version: gotVersion } = gotPackage

const userAgentHeader = `${name}/${version}; nodejs/${process.version}; got/${gotVersion}`
```

#### Checklist

- [v] I have read the documentation and made sure this feature doesn't already exist.

**Comment by osher** [comment]
If you would like to accept this feature, and tell me which way you prefer - I'll be happy to submit a PR.

However - I might need help in onboarding:  I cloned the repo, ran `npm install && npm run test` and the test suite does not exit, and I see failures.

node `v20.17.0`,  npm 10.8.2, Fedora 39 in WSL.

**Comment by sindresorhus** [comment]
I'm not interested in adding any kind of version export. This should be solved by your bundler instead. It's not a problem specific to this package. It applies to every package with an exports field. I also believe Node.js is working on a method to get the package.json of a specific package.

**Comment by osher** [comment]
I see. Thanks for the response.

Well. I'm writing server code in plain JS, I do not have any bundler.

So the solution would be to locate the node_modules, find the package.json, and read it manually.... 😝

**Comment by osher** [comment]
mm!

sorry for the hassle! Looks like the solution is much simpler than I thought. 

Sharing:

```js
import { readFileSync } from 'node:fs';
const gotPath = import.meta.resolve("got").slice(6) // remove 'file:/' prefix;
const pkgPath = gotPath.replace(/\/got\/.*/, '/got/package.json');
const { version } = JSON.parse( readFileSync( pkgPath.replace('file:/', '') ) );
```

Add some error-handling, and there you go 🙂
