### ISSUE TITLE
Buffer.from causes incompatibility with node 4

### ISSUE THREAD

**Issue by mmcbride1007** [sindresorhus/got#241]
`Buffer.from` wasn't added to Node until v5.10.0, so the changes in 5888ca7 caused this to break when running Node 4. I'm thinking the engines in `package.json` needs to be updated to reflect this?

**Comment by squarejaw** [comment]
`Buffer.from` was [backported to v4.5.0](https://nodejs.org/en/blog/release/v4.5.0/), so it would be nice if that was the minimum version required.

**Comment by floatdrop** [comment]
@mmcbride1007 @squarejaw future testing was added in `6.6.2` – should work on `4.x` now.
