### ISSUE TITLE
Error handling with got.stream()

### ISSUE THREAD

**Issue by zeke** [sindresorhus/got#244]
👋 

I'm trying to download a tarball and unpack it. This code works:

```js
got.stream(tarballUrl)
  .pipe(gunzip())
  .pipe(extractor) // extract is a `tar-fs` tar.extract function
  .on('error', function (e) {
    callback(e)
  })
```

But if the tarballUrl 404s, the error handler is not called. I can move it up in the chain and the error handler _is_ called:

```js
got.stream(tarballUrl)
  .on('error', function (e) {
    callback(e)
  })
  .pipe(gunzip())
  .pipe(extractor)
```

But then the success case no longer works.

How should I write this code so it will still have the streamy goodness, but also handle HTTP errors?

**Comment by floatdrop** [comment]
@zeke you should add error handlers in both places (after `stream` and `extractor`), because thats how streams in Node.JS works.

**Comment by zeke** [comment]
Yeah but this doesn't work:

```
got.stream(tarballUrl)
  .on('error', function (e) {
    callback(e)
  })
  .pipe(gunzip())
  .pipe(extractor)
```

The `.on` is not properly chaining to the next `.pipe`. Does the error handler need to return something?

**Comment by floatdrop** [comment]
@zeke added some tests for piping – they pass. May be you should not `gunzip` stream from got, because it will be gunzipped (if server sends valid `content-encoding` header).

**Comment by zeke** [comment]
Thanks for the info, @floatdrop. Much appreciated.
