### ISSUE TITLE
Support Promise .finally

### ISSUE THREAD

**Issue by txssseal** [sindresorhus/got#246]
I noticed that got does not have support for .finally.  It would be really nice to have this.

**Comment by julien-f** [comment]
Got use the available Promise implementation, if you want to have `.finally()` you can simply use Bluebird :)

```js
global.Promise = require('bluebird')
```

**Comment by sindresorhus** [comment]
Got, like most other promise returning modules, just use the standard Promise, which doesn't yet have support for `.finally`.

If you want finally, do `global.Promise = require('bluebird')` (or any other promise lib with `.finally` support in your app (never do this in a reusable module!). Or use https://github.com/sindresorhus/p-finally

**Comment by txssseal** [comment]
Aaahhh. Thanks, didn't know this.
