### ISSUE TITLE
Can't install got@5 on node@7 with engine-string=true

### ISSUE THREAD

**Issue by Strate** [sindresorhus/got#247]
Package.json contains node version requirement as "<7". Is it really reasonable? As for now I can't use some packages from npm, which depends on "got@5" with node@7.

**Comment by sholladay** [comment]
The first order of business is to make sure you are on an up-to-date version of `npm`, as they decided that `engineStrict` in `package.json` was a bad idea and removed support for it. Doesn't look like `got` was ever using that, though, and Node 7 should come with modern `npm` anyway. But I would `npm install --global npm` to update `npm` and then remove and reinstall your dependencies (e.g. `rm -rf node_modules && npm install`), just to be safe.

Now that being said, if you are using the [engine-strict config option](https://docs.npmjs.com/misc/config#engine-strict), which is still supported, or you cannot update `npm` for some reason, then I think you will find this useful. 😉 

```sh
$ npm show got@5 engines
got@5.0.0 { node: '>=0.10.0' }
got@5.1.0 { node: '>=0.10.0' }
got@5.2.0 { node: '>=0.10.0' }
got@5.2.1 { node: '>=0.10.0' }
got@5.3.0 { node: '>=0.10.0' }
got@5.3.1 { node: '>=0.10.0' }
got@5.3.2 { node: '>=0.10.0' }
got@5.4.0 { node: '>=0.10.0' }
got@5.4.1 { node: '>=0.10.0' }
got@5.4.2 { node: '>=0.10.0' }
got@5.5.0 { node: '>=0.10.0' }
got@5.5.1 { node: '>=0.10.0' }
got@5.6.0 { node: '>=0.10.0' }
got@5.7.0 { node: '>=0.10.0 <7' }
got@5.7.1 { node: '>=0.10.0 <7' }
```
```sh
$ npm show got@6 engines
got@6.0.0 { node: '>=4' }
got@6.0.1 { node: '>=4' }
got@6.0.2 { node: '>=4' }
got@6.1.0 { node: '>=4' }
got@6.1.1 { node: '>=4' }
got@6.1.2 { node: '>=4' }
got@6.2.0 { node: '>=4' }
got@6.3.0 { node: '>=4' }
got@6.5.0 { node: '>=4' }
got@6.6.0 { node: '>=4' }
got@6.6.1 { node: '>=4' }
got@6.6.2 { node: '>=4.5.0' }
got@6.6.3 { node: '>=4' }
got@6.7.0 { node: '>=4' }
got@6.7.1 { node: '>=4' }
```

I'll note that `got@6` was released well over a year ago, so you should probably upgrade. It basically amounts to changing callbacks to promises (see the [release notes](https://github.com/sindresorhus/got/releases/tag/v6.0.0)).

If you have to stay on the very specific combination of Node 7 and `got@5` and `engine-strict` for some reason, then you should probably use `~5.6.0` in your `package.json`. I'm not sure it will work 100% correctly, but it's worth a try. If you have time, you can go explore the codebase back when it was at https://github.com/sindresorhus/got/commit/fbeab05f5bb56052d1af0b22959e0a6a1a992e6e. Maybe some of the nearby commits or issues from that time period will mention Node 7 incompatibility.

**Comment by fritx** [comment]
Same issue here:
I've installed the latest npm as @sholladay  mentioned. Still not work.

```plain
$ node -v
v7.7.4
$ npm -v
4.4.4
```

```plain
$ npm i -g hotel
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"7.7.4","npm":"4.4.4"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"4.4.4","node":"7.7.4"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dji/.npm/_logs/2017-04-10T08_07_41_408Z-debug.log
```

**Comment by fritx** [comment]
Just removed `engine-strict=true` in ~/.npmrc and it works. My bad!

**Comment by AlexTes** [comment]
Nice detective work @sholladay!
I do strongly disagree with your final suggestion. To @Strate and anyone else with the same question, ignoring this engine restriction is possibly a very bad idea. I dug around and it's hard to find the exact reason the restriction was added. Maybe @floatdrop remembers why he added it. In any case! The upgrade path, timeline, and commits suggest floatdrop found `got` v5 broke with Node v7, not that we actively broke compatibility with Node v7 in version v5.7. In other words, until floatdrop comments, downgrading to `got` <=v5.6.0 and using it with Node >= v7 is risky.

Like sholladay said, upgrading to `got` >= v6 [seems effortless](https://github.com/sindresorhus/got/releases/tag/v6.0.0). Unless you're on Node <=v0.12 in which case you should upgrade Node instead.

If a dependency of yours is still using `got` < v6 please ask them to upgrade, better yet PR or if you're unwilling to, please mention which dependency is using an outdated version of `got` and I'll take a look at opening a PR myself.

**Comment by floatdrop** [comment]
@AlexTes @fritx there were problems with Node 7 at these version, so we put restriction in `package.json`, unfortunately I do not remember what exactly were broken.

**Comment by AlexTes** [comment]
I guessed right 😛.

Didn't notice it was unmaintained @floatdrop. That's kinda bad. How about I PR the most popular dependents of v5 and we deprecate the releases?

This can be closed now.
