### ISSUE TITLE
Default timeout

### ISSUE THREAD

**Issue by yanivefraim** [sindresorhus/got#256]
Can we have default timeout? Thanks!

**Comment by floatdrop** [comment]
@yanivefraim we can, but I don't see default timeout in popular libraries (like [request](https://www.npmjs.com/package/request) or [axios](https://github.com/mzabriskie/axios)). May be #203 is what you are looking for?

**Comment by yanivefraim** [comment]
@floatdrop - thanks for answering. I'm not using got directly. I'm using Yeoman's [inquirer-npm-name](https://github.com/sboudrias/inquirer-npm-name), which uses [npm-name](https://github.com/sindresorhus/npm-name), which uses got...

The final result is, that when I ask the user for npm module name, inside my Yeoman generator, and for some reason connection to npm fails, the UI gets stuck (with no timeout).

**Comment by floatdrop** [comment]
@yanivefraim okay, can you open issue in `npm-name` as well? It more likely, that timeout lands there first.

**Comment by yanivefraim** [comment]
@floatdrop - yes, thanks!

**Comment by sindresorhus** [comment]
I think there's a reason those libs doesn't provide a default timeout. Python doesn't have a default timeout either. `Got` doesn't know what it's being used for. Maybe someone needs a request to take one hour. What do we know. There's really no good default that fits all. Better to just never timeout and then let consumers with more knowledge set it to what they want. We should probably make this more clear in the readme.
