### ISSUE TITLE
 const in `for of` loop throws SyntaxError in Firefox < 51

### ISSUE THREAD

**Issue by nathantbaker** [sindresorhus/got#259]
in `index.js` line 323, would it make sense to use let and not const because of this compatibility issue?

`for (const el of helpers) {
	got.stream[el] = (url, opts) => got.stream(url, Object.assign({}, opts, {method: el}));
}`

> [2] Prior Firefox 51, using the for...of loop construct with the const keyword threw a SyntaxError ("missing = in const declaration"). This has been fixed (bug 1101653).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Gecko_note_2

**Comment by sindresorhus** [comment]
No, the main target is Node.js. It's up to you to properly transpile it if needed in the browser. You could also use version 5, which uses ES5 syntax.

**Comment by nathantbaker** [comment]
Thanks, the feedback is appreciated. Cheers.
