### ISSUE TITLE
'encoding' option doesn't change output

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#268]
If I set the like this `got.stream(url, { encoding: 'latin1' })`, it doesn't seem to change the output as I would have expected for the file contents. I then tried changing the encoding string to a random string, and `got` didn't report any error. Is the encoding option being used? I'm using version 6.6.3.

Same with setting the option to `null`, it should return a Buffer but doesn't seem to change anything.

**Comment by floatdrop** [comment]
@rightaway can you post code snippet, that reproduces error?

**Comment by rightaway** [comment]
Try this example. It downloads a sample `latin1`/ISO-8859-1 encoded file and saves it to disk. Open that file and you'll see the strange question mark characters �. http://stackoverflow.com/a/3527176/779159 explains it's because of the wrong encoding being applied, and `latin1` should fix it.

```js
import fs from 'fs'
import got from 'got'

got.stream('http://vancouver-webpages.com/multilingual/french.asis', { encoding: 'latin1' })
  .pipe(fs.createWriteStream('/tmp/file.txt'))
```

**Comment by sindresorhus** [comment]
From the Node.js docs:

> Note: Today's browsers follow the WHATWG spec which aliases both 'latin1' and ISO-8859-1 to win-1252. This means that while doing something like http.get(), if the returned charset is one of those listed in the WHATWG spec it's possible that the server actually returned win-1252-encoded data, and using 'latin1' encoding may incorrectly decode the characters. - https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings

**Comment by rightaway** [comment]
Does it mean I need to change `'latin1'` to `'win-1252'` in the code sample above? I've tried it but still the same result. How can I get it to output the file as expected?

**Comment by sindresorhus** [comment]
I don't know. The Node.js docs are unclear about what you should do. I guess the safest thing to do would be to manually convert using something like https://github.com/ashtuchkin/iconv-lite
