### ISSUE TITLE
.cancel() method on the promise

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/got#274]
Would is be possible to expose the [http.ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest) as `promise.ClientRequest` or similar, so one can `.abort()` pending requests?

I could use this for https://github.com/sindresorhus/is-online/pull/39.

**Comment by sindresorhus** [comment]
I think we should rather expose an abort() method on the promise. Official promise cancellation is not happening, so we can just go with something homemade. Could maybe use https://github.com/sindresorhus/p-cancelable

**Comment by silverwind** [comment]
I just thougth that there would be more useful stuff on the `ClientRequest` to justify exposing it as a whole, but looking at the class members there, there's really not much in there, so I guess a `.abort()` is okay.

**Comment by sindresorhus** [comment]
@floatdrop Thoughts?

**Comment by floatdrop** [comment]
@sindresorhus sure,  this will be handy.

**Comment by julien-f** [comment]
You should go for `promise.cancel()`, at least it will be aligned with [Bluebird](http://bluebirdjs.com/docs/api/cancel.html).

**Comment by AlexTes** [comment]
I started work on this with p-cancelable. Can't quite get p-cancelable to be happy yet on cancellation. Asked Sindre for help. If that doesn't work out I'll repost in here.

**Comment by sindresorhus** [comment]
@AlexTes Did you figure it out? If not, I'd be happy to take a look if you do a PR of what you got.

**Comment by AlexTes** [comment]
@sindresorhus completely forgot about this one. I found a branch and stash. I'll put it on my list and take a look tonight (in 8h).
