### ISSUE TITLE
Handling both ParseError and HTTPError simultaneously

### ISSUE THREAD

**Issue by sonicdoe** [sindresorhus/got#278]
[Previous discussion](https://github.com/SamVerschueren/travis-got/pull/2#pullrequestreview-25498565) /cc @SamVerschueren @floatdrop @sindresorhus

To summarize, Travis CI’s API returns HTML on `403 Forbidden` responses. For example, try:

```sh
curl -i -H "Authorization: token fail" https://api.travis-ci.org/repos/SamVerschueren/travis-got 
```

When using got’s `json` option this causes a `ParseError` (instead of an `HTTPError`) to be thrown. To avoid this, I suggested to catch the error, check the status code for `403`, and re-throw an `HTTPError`. While this works, it requires us to manually create an error which is an undocumented API of got, as far as I can tell.

@SamVerschueren suggested to disable got’s `json` option and parse the body ourselves. Again, while this works, we would still have to manually throw a `ParseError` in case the body can’t be parsed.

So, either way, we would have to to manually create and throw a `ParseError` or an `HTTPError`.

> I would recommend looking into how other HTTP libs handle this, like `request`. We might be doing something wrong, or not.

@sindresorhus request currently just [logs a debug message](https://github.com/request/request/blob/v2.80.1/request.js#L1116-L1120). This behavior has also been discussed in https://github.com/request/request/issues/440.

**Comment by sonicdoe** [comment]
I have taken a look at a few other HTTP client libraries which do something similar. To give an overview:

- [request](https://github.com/request/request) just [logs a debug message](https://github.com/request/request/blob/v2.80.1/request.js#L1116-L1120) (see also https://github.com/request/request/issues/440)
- [axios](https://github.com/mzabriskie/axios) ignores parsing errors (see also https://github.com/mzabriskie/axios/issues/61)
- [Unirest](https://github.com/Mashape/unirest-nodejs) ignores parsing errors (see [source](https://github.com/Mashape/unirest-nodejs/blob/v0.5.1/index.js#L784-L790))
- [httparty](https://github.com/jnunemaker/httparty) parses based on `Content-Type` (see [docs/README.md#parsing-json](https://github.com/jnunemaker/httparty/blob/702e5a3d145e37cf6ae17cded84cc1a9b85a84c1/docs/README.md#parsing-json))
- [Faraday](https://github.com/lostisland/faraday) parses based on `Content-Type` but also tries to parse JSON-like responses (see [source](https://github.com/lostisland/faraday_middleware/blob/0.11.0.1/lib/faraday_middleware/response/parse_json.rb#L14-L19))
- [Tesla](https://github.com/teamon/tesla) parses based on `Content-Type` (see [source](https://github.com/teamon/tesla/blob/v0.6.0/lib/tesla/middleware/json.ex))

This is also related to #168 (automatic parsing based on `Content-Type`) as it would solve this issue with, at least, Travis CI’s API because it actually returns the correct `Content-Type`.

**Comment by SamVerschueren** [comment]
I'm playing with this in my head since the issue was created. So what I personally think would be nice is that `got` only throws a `ParseError` if the status code indicates success `2xx` and the body is not json.

```js
try {
    return JSON.parse(response);
} catch (err) {
    throw new ParseError(err);
}
```

In all the other cases, if an error status code is returned like 4xx or 5xx, it should try to parse the response (if `json` is set to `true`), if it fails to parse the response, it should throw an `HttpError` with the unparsed body.

```js
try {
    throw new HttpError(statusCode, JSON.parse(response));
} catch (err) {
    throw new HttpError(statusCode, response);
}
```

**Comment by AlexTes** [comment]
I'm with Sam!
I like 'always try to parse the response, if bad things happened don't expect json but be helpful, and try to parse the body as such'. It says: for 2xx we take strict responsibility to do as asked, the rest we'll try to help out but it's mainly on you.

I also wouldn't object to saying 'no 200, no automagic parsing for you'. It's simpler, and doesn't beg the question if we don't mind breaking if a 201 json response gets changed to 204 no json response. Especially if both sport correct content-type headers. I would understand the user that feels the `json` option was meant as mere convenience not setting an ultimatum. It says: if things aren't simple _you_ figure them out.

For the same reasons I'm also still a fan of [dropping the json option](https://github.com/sindresorhus/got/pull/264). It causes too many issues. Using a parse option would make obvious when things are the user's responsibility and when they're ours. It would say: if asked we always try and parse for you, if the situation is more complex, _you_ figure it out.

**Comment by SamVerschueren** [comment]
Yes, I think that a lot of APIs just return a "descriptive" error message when something goes wrong instead of returning a JSON object with that error message.

If everything is ok (status 2xx) and the developer sets `json` to `true`, that means he expects JSON and if not, we can safely throw a `ParseError` because it's not JSON.

In all the other cases we should try to parse but if that fails it means the body is not parseable and is most likely a string error message. If you throw a `ParseError` here, it's not clear that actually what happened was an `HttpError` but the body is not parseable which actually hides what really happened imo.

**Comment by sonicdoe** [comment]
> In all the other cases, if an error status code is returned like 4xx or 5xx, it should try to parse the response (if `json` is set to `true`), if it fails to parse the response, it should throw an `HttpError` with the unparsed body.

I don’t think ignoring parsing errors (even only on error responses) is a good idea. This leads to errors like https://github.com/mzabriskie/axios/issues/61#issue-68540010.

I’m still undecided but I would like to float the following idea by you:

```js
got('https://api.travis-ci.org', {
  parse: res => {
    if (res.statusCode === 403) return res.body
    return JSON.parse(res.body)
  }
})
```

This builds upon @AlexTes’s proposal in https://github.com/sindresorhus/got/pull/264. This would make sure that the user knows what to expect for `body` in case of `403 Forbidden` but still allows a `ParseError` to be thrown on, for example, `400 Bad Request`.

**Comment by sindresorhus** [comment]
I vote for Sam's proposal in https://github.com/sindresorhus/got/issues/278#issuecomment-285441196.

@floatdrop Thoughts?

**Comment by floatdrop** [comment]
@sindresorhus let's do this 👍
