### ISSUE TITLE
Can't re-throw / throw custom errors from error handlers.

### ISSUE THREAD

**Issue by antony** [sindresorhus/got#279]
I'm currently switching from `request` library to `got`, and I seem to have encountered a problem with the way errors are created.

My code looks something like this (simplified, actually logs before throwing):

```
function post (url, body) {
    return got(url, { body })
    .catch(RequestError, ReadError, ParseError, HTTPError, MaxRedirectsError, (err) => { throw err })
    .catch((err) => { throw err })
}
```

and the code which calls it would look like this:

```
return post('/xxx/yyy', { foo: 'bar' })
  .then(({ body }) => {
    log.info('ok', body)
  })
  .catch((err) => {
    log.error(`some error`, err)
  })
```

The reason being that the post method is generic and simply wants to log, and then continue the rejection.

Unfortunately, due to the way that got seems to catch any errors my handlers throw, before continuing to throw them, the error wrapping causes my test to fail (and my original error to be lost)

```
 1) my-test "before all" hook:
     Error: TypeError: Object.defineProperty called on non-object
      at client.post.then.catch (src/.../service/my-service.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
It seems like `create-error-class` is trying to add 'response' property to my `Error` object, but I don't want it to, because there isn't a response.

I can't currently see a way around this. Any ideas?

**Comment by antony** [comment]
A bit of further clarification which might be useful.

The error comes from `nock` throwing an `Error` due to a non-matching request. The line which then tries to turn that into a 'RequestError' is here:

```
https://github.com/sindresorhus/got/blob/master/index.js#L73
```

and it fails because `err` is a generic `Error` object:

```
{ Error: Nock: No match for request {
  "method": "POST",
  "url": "https://xxx.yyy",
  "headers": {
    "user-agent": "got/6.7.1 (https://github.com/sindresorhus/got)",
    "accept-encoding": "gzip,deflate",
    "authorization": "Basic aaa:bbb",
    "accept": "application/json",
    "content-type": "application/x-www-form-urlencoded",
    "content-length": 7
  },
  "body": "foo=bar"
}

```

**Comment by AlexTes** [comment]
Hi @antony!

I'm afraid you removed too much code for me to see what's really going wrong. From experience I'm guessing one of two things is happening:
1. You're trying to create a got error without passing the required arguments. (maybe you're using nock's `replyWithError`?
2. The testing lib you're using is trying to create a got error without passing the required arguments.

Here's an example that works just fine, I can rewrite it using whatever testing lib you like, I used [ava](https://github.com/avajs/ava) because she's really straightforward.

```js
const test = require('ava');
const got = require('got');
const nock = require('nock');

function post(url, body) {
  return got('http://localhost:8080/', { body })
    .catch((err) => { throw err; }); // this could be removed
}

test('test error route', (t) => {
  nock('http://localhost:8080/')
    .get('/')
    .reply(500, 'Intentional Error');

  return post('localhost:8080', { name: 'alex' })
    .then(() => {
      t.fail();
    })
    .catch(() => {
      t.pass();
    });
});

test('throws', (t) => {
  nock('http://localhost:8080/')
    .post('/')
    .reply(500, 'Intentional Error');

  return t.throws(got('localhost:8080/'), got.HTTPError);
});
```

**Comment by antony** [comment]
Hi @AlexTes 
Thanks for the swift response!

I think I found out what it is - but unfortunately it does still indicate a problem in `got`.

When a route doesn't match in nock, nock throws an error to say that there is no match.

What happens is that got tries to add info to this error, and fails, and ends up throwing the error I listed above - which isn't useful because there is no indication that the route didn't match - the error gets swallowed.

There should be a check before trying to append to errors, and potentially wrapping an existing error before trying to append to it would be a good fix.

**Comment by AlexTes** [comment]
I think one of us is confused about the interplay of nock and got. I don't think got can catch nocks errors, unless nock isn't acting like a server in the way I thought. Whatever the response is, got should be able to turn it into an error without issue. I'll try your scenario: pointing got at a route that doesn't match but somehow still gets caught by nock.

Again, it would be helpful if you supplied the code that demonstrates this behavior!

**Comment by antony** [comment]
Hi Alexander,

Of course! I'll try to create a sample project, sorry :)

Cheers,
Antony

On Fri, 10 Mar 2017, 10:42 Alexander Tesfamichael, <notifications@github.com>
wrote:

I think one of us is confused about the interplay of nock and got. I don't
think got can catch nocks errors, unless nock isn't acting like a server in
the way I thought. Whatever the response is, got should be able to turn it
into an error without issue. I'll try your scenario: pointing got at a
route that doesn't match but somehow still gets caught by nock.

Again, it would be helpful if you supplied the code that demonstrates this
behavior!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sindresorhus/got/issues/279#issuecomment-285636684>,
or mute
the thread

**Comment by antony** [comment]
Took me a while - here is a demonstration of the problem. The thing to note is that I'm trying to log errors, and then re-throw them to the catching code.

https://github.com/vendigo-group/got-problems

As you can see, the nock errors are swallowed, and the result is a test fail. The error of the fail is thrown from the `got` code.

**Comment by antony** [comment]
In hindsight... I think I might have figured this out.

Our old library `request-promise` allowed bluebird as a promise library. I'm using a multiple-catch, which native promises do not support. I think this can probably be closed!

**Comment by AlexTes** [comment]
The way you were catching errors was one of the elements I was curious about seeing in action 😉 .

Glad to see you figured it out!
