### ISSUE TITLE
Allow choice of promise library

### ISSUE THREAD

**Issue by antony** [sindresorhus/got#290]
We use bluebird throughout our application - it's much faster than native promises, and it allows us to do the multiple catch I mentioned in a previous issue.

The reason for this is that we'd ideally like to treat `HTTPError`, `ParseError` in one manner, and other errors in another manner. This is achieved in bluebird style as follows:

```js
got(...)
.then(({ body, statusCode }) => {
})
.catch(HttpError, ParseError, (e) => {
  ... handle data problem
})
.catch((e) => {
  ... handle communication problem
})
```

We can of course check the prototype and use an if statement, but it's less clean and less readable to do so.

It'd be great if we could configure the promise type got uses, something like

```js
const got = require('got')
got.Promise = require('bluebird')
```

which is similar to how mongoose, and a few other libraries do it.

Is this something you'd consider?

**Comment by sindresorhus** [comment]
Why not `global.Promise  = require('bluebird')` like most people use in their application? That way you don't have to convince every single module you use to expose its Promise constructor.

**Comment by antony** [comment]
That is an excellent idea - I'd not considered that approach. Thanks!

**Comment by AlexTes** [comment]
@antony do keep in mind that if you're using async / await you lose your bluebird promise!

I dislike messing with globals because they have issues like the thing I just mentioned. I would humbly suggest:
```js
const Promise = require('bluebird');
const got = require('got');

Promise.resolve(got.get('URL'))
  .catch(got.HTTPError, () => { /* handle HTTPError */ });
```

**Comment by sindresorhus** [comment]
I highly doubt `Promise` is the slow part of Got which deals with networking 😜

**Comment by AlexTes** [comment]
Fair point 😅.
