### ISSUE TITLE
Not timing out some requests

### ISSUE THREAD

**Issue by calebmer** [sindresorhus/got#292]
It looks like `got` is failing to timeout certain long requests. Here is the URL for one such endpoint `got` fails to time out: http://www.voiceblog.jp/chappecast/rss2.0.xml

To try this out for yourself open up a Node.js REPL and write:

```js
require('got')('http://www.voiceblog.jp/chappecast/rss2.0.xml').then(console.log, console.error)
```

Perhaps this is really an issue with the `timed-out` module by @floatdrop?

**Comment by calebmer** [comment]
Here is an example in RunKit: https://runkit.com/58e023b82830330014a733fb/58e0300e2830330014a73666

**Comment by AlexTes** [comment]
Why do you expect `got` to time out by default?
If you feel there's a reason, do share! 
If you feel something could be improved to make it more obvious `got` does not time out by default, do share!
😉

**Comment by calebmer** [comment]
Ah, sorry for not investigating further! I assumed that `got` had a timeout by default (which is not a safe assumption). In the code I’m actually running I have a generous timeout set (10s) with 5 retries and I didn’t do the exponential retry math. I let it run for about one and a half minutes and didn’t see any timeout errors, so I tried to reproduce and didn’t set out a timeout in my reproduction.

Sorry about that 😊

**Comment by AlexTes** [comment]
@calebmer no problem!
Helpful to know it was the exponential backoff that surprised.

**Comment by mautematico** [comment]
> 31 to 36 seconds to timeout.
that number is exactly what I was looking for. Why is that (so high)? can it be overriden?

**Comment by AlexTes** [comment]
@mautematico yes it can! By setting the [timeout option](https://github.com/sindresorhus/got#timeout) to whatever you want and overriding the default 2 retries and setting it to 0.

Thanks for letting us know it's currently confusing.
