### ISSUE TITLE
7.0.0

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#298]
I'd like for us to do a v7 soonish.

Remaining issues: https://github.com/sindresorhus/got/milestone/5

Any other breaking changes we should get into the release? I'm hoping we won't have to do another major release for a long while, so would be nice to land anything breaking now.

// @floatdrop @AlexTes

**Comment by floatdrop** [comment]
@sindresorhus should we wait for #281 in `7.0.0`?

**Comment by sindresorhus** [comment]
@floatdrop It's not a blocker. Just would be nice, as I'd like to have it on by default, which would be a breaking change.

**Comment by sindresorhus** [comment]
@lukechilds Do you think it will be ready in a couple of weeks? Or should we just defer it to another release?

**Comment by lukechilds** [comment]
I would like to say it will be ready in a couple of weeks but I'm waiting to hear back on some client work which will take priority so I can't guarantee anything unfortunately.

Regarding enabling cache by default, I think it'll have to be opt in as we aren't bundling a cache store with Got. To enable caching the user will have to manually install and pass in a cache store:

```js
const got = require('got');
const levelup = require('levelup');
const redisdown = require('redisdown');
const db = levelup('mydb', { db: redisdown, host: 'localhost', port: 6379 });

got('foo.com', {cache: db});
```

No caching by default so would just be a SemVer minor release.

**Comment by sindresorhus** [comment]
@lukechilds Alright. No pressure. We can add it in a minor release later on. I don't want to rush this feature.

**Comment by floatdrop** [comment]
@sindresorhus looks like it is time to ship. Should something be fixed before?

**Comment by sindresorhus** [comment]
@floatdrop We need to write a good changelog first. Hop into Gitter.

**Comment by maccelerated** [comment]
I just needed to say that options.body being an object instead of a string made my day. Thank you for the awesome module.

**Comment by sindresorhus** [comment]
@maccelerated Glad you liked that. Do let us know in a new issue if there's anything else that could be improved ;)

**Comment by avimar** [comment]
@sindresorhus Where is that changelog? I see you're talking about breaking changes but I can't find a list. (Semver of breaking changes since my current version 6.5...)

Thanks!

**Comment by AlexTes** [comment]
@avimar [releases](https://github.com/sindresorhus/got/releases) is where you want to look 😉.
Here's [the changelog for v7.0.0](https://github.com/sindresorhus/got/releases/tag/v7.0.0).

**Comment by avimar** [comment]
Thanks, got it! (Was expecting a CHANGELOG file like many projects have now.)
