### ISSUE TITLE
Support stream retries

### ISSUE THREAD

**Issue by dmathieu** [sindresorhus/got#309]
While standard requests allow specifying a `retries` number or function, it seems `got.stream` doesn't handle it.
Yet a streaming request can fail just like any other one. Handling those retries seems quite useful.

Unfortunately, my node-fu isn't good enough to implement this while making sure it does work (I've tried doing so in my error handler, but it appears the second request never starts, as if duplexer3 couldn't handle multiple requests).

**Comment by sindresorhus** [comment]
> I've tried doing so in my error handler, but it appears the second request never starts, as if duplexer3 couldn't handle multiple requests

Yes, you can't reuse a stream.

**Comment by sindresorhus** [comment]
I agree. We should support this.

**Comment by floatdrop** [comment]
`got.stream` should support retries, because it [reuses `requestAsEventEmmitter`](https://github.com/sindresorhus/got/blob/master/index.js#L212) code. Yet after body content is piped into stream no retries will be applied on stream errors.

@sindresorhus should we cache streamed body to allow retries?

**Comment by sindresorhus** [comment]
> should we cache streamed body to allow retries?

You mean so it can continue where it left off in case the connection is broken in the middle of a request? Is that even possible? Or am I misunderstanding?

**Comment by floatdrop** [comment]
I mean, that content will be resent from beginning, if something goes wrong. In case of input streams it mesns we should save what we have sent somewhere.

Отправлено с iPhone

**Comment by sindresorhus** [comment]
@floatdrop We might be able to build that upon what being added in https://github.com/sindresorhus/got/pull/284.

**Comment by overlookmotel** [comment]
I've just published a module that uses got and resumes after network errors: https://www.npmjs.com/package/got-resume

If a request fails, the next request picks up from where the last one left off, using HTTP range headers.

It's designed for downloading large files where network errors are common.

**Comment by szmarczak** [comment]
Please see #501 .

**Comment by silentroach** [comment]
Why not retry requests if no input streams used? For example I use `got` to stream the response from server to parser.

**Comment by szmarczak** [comment]
@silentroach The thing is that if it errors while downloading you could get duplicated response.

**Comment by silentroach** [comment]
what about "bad" response status/codes? it will throw before I will get any data.

**Comment by szmarczak** [comment]
@silentroach Not necessarily. If the response body is short, then everything will be sent in one packet, thus the `data` event will be emitted immediately.

**Comment by silentroach** [comment]
sad :{
