### ISSUE TITLE
Recent Electron support (#311) breaks in Atom

### ISSUE THREAD

**Issue by lselden** [sindresorhus/got#314]
Re Pull: #311 

I'm on the latest atom version (v1.17.1), and `require('electron').net` returns `undefined`, so attempting to use got I get:
```
TypeError: Cannot read property 'request' of undefined
    at get (...\node_modules\got\index.js:46:17)
    at Immediate.setImmediate (...\node_modules\got\index.js:116:3)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```
relevant line:
https://github.com/sindresorhus/got/blob/master/index.js#L43

quickfix: perhaps instead of:
`fn = require('electron').net;`
it could be:
`fn = require('electron').net || fn;`

**Comment by sindresorhus** [comment]
What are you trying to use it for? Are using it with browserify/webpack in an Atom plugin?

**Comment by lselden** [comment]
No, I'm testing out code by requiring from the Atom developer tools. I'm using a customized version of https://github.com/douglascalhoun/eval-javascript to eval code on the fly. It's admittedly an edge case, but might be relevant to plugin developers.

**Comment by sindresorhus** [comment]
@lselden Can you try latest master? I added support for running in the Electron renderer process.

**Comment by lselden** [comment]
Specifying the `useElectronNet: false` option worked. Without specifying that option it failed.
I think the issue is that the electron version in the current build of atom is 1.3.15, and it looks like the .net module was only added in v1.4 (judging by [v1.3](https://github.com/electron/electron/tree/1-3-x/docs) vs [v1.4](https://github.com/electron/electron/tree/1-4-x/docs) docs.
