### ISSUE TITLE
Can't await got@7.0.0 promise

### ISSUE THREAD

**Issue by timdp** [sindresorhus/got#316]
Not sure what's going on yet, but this doesn't work with got@7.0.0:

```js
(async () => {
  const getting = got('localhost:8080')
  console.log('getting', getting)
  const resp = await getting
  console.log('resp', resp)
})()
```

With version 6, I get:

```
getting Promise { <pending> }
resp IncomingMessage {
...
```

With 7.0.0 on the other hand, I get:

```
getting PCancelable {
  undefined,
  _pending: true,
  _canceled: false,
  _reject: [Function: z],
  _cancel: [Function],
  _promise: Promise { <pending> } }
resp undefined
```

and it seems to be pretty much synchronous. I was using a remote endpoint before and it didn't slow down at all.

Could it be that p-cancelable isn't working?

I'm on Node 7.9.0 on Ubuntu 16.04.

**Comment by AlexTes** [comment]
@timdp could be. Thanks for reporting, I'll take a look.

**Comment by sindresorhus** [comment]
Confirmed, but it works on Node.js 8 RC1. Node.js 8 should be out in a few days.

Try it yourself with: https://nodejs.org/download/rc/v8.0.0-rc.1/


My test-case:

```js
const got = require('got');

(async () => {
  const getting = got('https://sindresorhus.com')
  console.log('getting', getting)
  const resp = await getting
  console.log('resp', resp)
})();
```

**Comment by timdp** [comment]
Yeah but Node 7.6+ has native support for async as well. I wonder what's wrong with it then.

**Comment by sindresorhus** [comment]
@timdp Promise subclassing is probably buggy in that V8 version as async/await was just added then.

**Comment by sindresorhus** [comment]
Just stay on Got v6 until you can upgrade to Node.js 8. I'm not really interested in spending time fixing this.

**Comment by timdp** [comment]
I'd still be slightly worried that p-cancelable has a bug in Node 7, but it's up to you.

For what it's worth, I was curious so I've established that all this works fine in Node 7.9.0:

```js
class Promise2 extends Promise {}

class Thenable {
  constructor (delay) {
    this._delay = delay
  }

  then (cb1, cb2) {
    setTimeout(cb1, this._delay)
  }

  catch (cb) {}
}

;(async () => {
  const start1 = Date.now()
  await new Promise2((resolve, reject) => {
    setTimeout(resolve, 500)
  })
  console.log(Date.now() - start1)

  const start2 = Date.now()
  await new Thenable(500)
  console.log(Date.now() - start2)
})()
```

**Comment by sindresorhus** [comment]
@timdp If you remove the `extends Promise` and `super()` call from [`p-cancelable`](https://github.com/sindresorhus/p-cancelable/blob/master/index.js) it should work in Node.js 7. I prefer to be `instanceof` compatible with `Promise` though. Node.js 7 is non-LTS release, so it's pretty much unsupported in a few days when Node.js 8 comes out.

**Comment by timdp** [comment]
@sindresorhus Yeah, I'm actually trying to come up with a PR for that as we speak. But I definitely understand the rationale behind trying to extend the native `Promise`. That being said, the way `p-cancelable` calls the super constructor rightaway kinda scares me--not that I have a better solution. It feels like a reason not to extend `Promise` though.

Anyway, sorry to go off topic. I suppose this should be in a `p-cancelable` issue, but if you're not looking to support it, it's not worth it.

Shouldn't this be made explicit though? I.e., shouldn't `p-cancelable` complain if it's running on Node 7, through package.json `engines` or even just the readme? Of course, it's "just" `await` that's affected, but that's a pretty big one, given that a lot of people will probably have upgraded to Node 7 just to get that.

I know it's a passing phenomenon, but for example, at our company, we're using the natively supported Node 7.6.0 on AWS Elastic Beanstalk, and the native `async` is _the_ reason why we are doing that. A lot of our apps on Beanstalk use `got` (yay!) so it's a bit of a downer that upgrading will break our code, even if it's just for a while. Yes, our tests will catch it (although more as a side effect) but it's still something extra to keep in mind. Moreover, if some transitive dependency upgrades to the new `got` or another package that uses `p-cancelable`, it'll also bite us, and it'll be harder to notice.

Sorry to be bitching about this. It just feels a bit like you're underestimating the impact, but I'll happily be proven wrong.

**Comment by sindresorhus** [comment]
I'm open to consider a workaround for Node.js 7 if it's important to you. I just assumed it would be easier to upgrade to Node.js 8, as it will be the supported long-term release and it's pretty similar to Node.js 7, so should be an easy upgrade in theory.

> That being said, the way p-cancelable calls the super constructor rightaway kinda scares me

I think it's ok. It wastes one promise, but that shouldn't matter much.

**Comment by timdp** [comment]
> I'm open to consider a workaround for Node.js 7 if it's important to you.

That's okay. We'll just hope for a Beanstalk upgrade soonish. Like you said, it's the LTS release, so here's hoping the AWS guys will scramble to support it. And the LTS element should solve other people's issues as well because they'll all be very similar.

> It wastes one promise, but that shouldn't matter much.

I don't mind the small performance loss from that one promise. It was more about resolving the promise itself and yet overriding the whole "thenable" API, which basically negates the whole superclass. (Come to think of it, do you need to call `resolve` to begin with? I'm guessing that's mainly for the garbage collector?)

I'll just close this issue. It's pretty clear that the message is "just use Node 8." :wink:

Thanks for taking the time to reply, I know you're busy. :+1:

**Comment by sindresorhus** [comment]
> (Come to think of it, do you need to call resolve to begin with? I'm guessing that's mainly for the garbage collector?)

GC yes, it's not required to work.
