### ISSUE TITLE
electron addition in 7.0 breaks bundling with webpack

### ISSUE THREAD

**Issue by gdub22** [sindresorhus/got#317]
Since upgrading to 7.0, trying to bundle got with webpack now throws an error:
`Module not found: Error: Can't resolve 'electron'`

I believe this is because webpack analyzes and finds this dynamic require here:
https://github.com/sindresorhus/got/blob/6fc1902805bae0791ee36895d351823248da9d07/index.js#L44

Even with the `useElectronNet: false` option, it still tries to pick it up.

**Comment by gdub22** [comment]
Ended up just explicitly ignoring the `electron` dependency in my webpack config.

**Comment by aviaryan** [comment]
@gdub22 Can you tell me how to do so? I am facing the same problem.

**Comment by gdub22** [comment]
@aviaryan add electron to `externals` in your webpack config e.g.
```js
externals: {
  'electron': 'electron'
}
```
