### ISSUE TITLE
Error: Unexpected token: operator (>) [./~/get-stream/buffer-stream.js:4,0]

### ISSUE THREAD

**Issue by vinhngle** [sindresorhus/got#321]
Hi,

I used `got` with [create-react-app](https://github.com/facebookincubator/create-react-app). Everything is good until I tried to run `yarn build` project. It threw an exception like this: 
```
⇒  yarn build
yarn build v0.24.5
$ react-scripts build
Creating an optimized production build...
Skipping static resource ".../react-example/build/static/js/main.aa0e5d44.js" (2.24 MB) - max size is 2.1 MB
Failed to compile.

static/js/main.aa0e5d44.js from UglifyJs
Unexpected token: operator (>) [./~/get-stream/buffer-stream.js:4,0][static/js/main.aa0e5d44.js:35510,23]

error Command failed with exit code 1.
```
I wonder if there is a bug in `get-stream` make the build failed. Can you help me to check this.

I also create an issue ticket in `create-react-repo`: [#2433](https://github.com/facebookincubator/create-react-app/issues/2433)

**Comment by kevva** [comment]
UglifyJS doesn't support minifying ES2015 code. If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
