### ISSUE TITLE
`strictSSL` option in tests doesn't seem to exist

### ISSUE THREAD

**Issue by lukechilds** [sindresorhus/got#327]
There is a `strictSSL` option in the HTTPS tests that doesn't seem to exist. 

Here it is in the test: https://github.com/sindresorhus/got/blob/ff0cef0040f226a91afc22664cbd3c2a04292a03/test/https.js#L50

Looking through the history it looks like it creeped in here: https://github.com/sindresorhus/got/commit/d61333015f6695d6a9fbe883b500cc9221c6e161

Is this ok to be removed?

**Comment by sindresorhus** [comment]
Yeah, we're are strict by default, with no way to turn it off, so that option does indeed look moot.
