### ISSUE TITLE
no such file or directory ... \node_modules\got\package

### ISSUE THREAD

**Issue by SilverMountainSoftware** [sindresorhus/got#330]
I am trying to import google-translate-api into my Angular app which pulls in got but I am getting the following error and I don't know what to do with it. It looks like it is trying to read package.json, but if I change  

const pkg = require('./package');
to
const pkg = require('./package.json');

it compiles, but then fails Configstore ("Uncaught TypeError: fs.readFileSync is not a function") . Thanks for any help.

ERROR in ./~/got/package
Module build failed: Error: ENOENT: no such file or directory, open 'I:\Code\.....\node_modules\got\package'
    at Error (native)
 @ ./~/got/index.js 19:12-32
 @ ./~/google-translate-api/index.js
 @ ./src/app/google-translate.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by sindresorhus** [comment]
These are all problems with Webpack. Open an issue on the Webpack issue tracker.

**Comment by nomad3k** [comment]
It's not a webpack bug.  You just need to amend the resolve.extensions in your webpack.config.

    resovle: {
        extensions: ['', '.js', '.jsx', '.json']
    }
