### ISSUE TITLE
Can I use async/await with got?

### ISSUE THREAD

**Issue by SilentImp** [sindresorhus/got#331]
Hi, 
If `got` function is thenable, then, perhaps, it return promise? And, if so, then why I can't use `async/await` with `got`?

~~~js
static async getNameSpaceId() {
    const body = await got('https://gitlab.com/api/v4/namespaces',{
      headers: {"PRIVATE-TOKEN": process.env.GITLAB_TOKEN}
    }); 
    console.log(body); // undefined
  }
~~~

What have go wrong?

**Comment by AlexTes** [comment]
@SilentImp are you using Node 7 by chance? See: #316.

**Comment by SilentImp** [comment]
$ node --version
v7.9.0

**Comment by sindresorhus** [comment]
Use Node.js 8. Node.js 7 is not LTS.
