### ISSUE TITLE
Access to body error

### ISSUE THREAD

**Issue by mjasinski5** [sindresorhus/got#332]
Hello.

When error is thrown (for example HTTPError), the following properties are accessible (example):

```
{ 
    message: 'Response code 401 (Unauthorized)',
    host: 'someHost,
    hostname: 'someHostName,
    method: 'POST',
    path: 'somepath',
    statusCode: 401,
    statusMessage: 'Unauthorized' 
  }
```
and there no way to access origin error (body from the error response). Ive done a research through options and theres none :( After that I dive in into code and I've 'fixed' that by adding 2-3 lines of code. Is that something you would like to have in your library? I can provide PR. Desired output would be like this:
```
{ 
    message: 'Response code 401 (Unauthorized)',
    host: 'someHost,
    hostname: 'someHostName,
    method: 'POST',
    path: 'somepath',
    statusCode: 401,
    statusMessage: 'Unauthorized',
   body: 'originError'
  }
```

**Comment by AlexTes** [comment]
@mjasinski5 check out the `err.response` property 😉. 
In the [Errors](https://github.com/sindresorhus/got#errors) section there's the following line:
>In Promise mode, the response is attached to the error.

Maybe you'd feel we should explicitly mention this includes any response body?

**Comment by mjasinski5** [comment]
hmm Im using async await (wrapped in https://github.com/danielstjules/swaddle) and there's no response in try/catch. Ive also tried pure promise version (ofc in swaddle) and it doesnt work as well. After quick test, within this change: https://github.com/mjasinski5/got/commit/31bf33c2960865b5872565dcc6690f90d5180eb9 it worked as expect.

**Comment by mjasinski5** [comment]
To close, Ive fixed that.. its fine on your side :)
