### ISSUE TITLE
`got.stream()` does not emit `end` event for request timeout errors

### ISSUE THREAD

**Issue by overlookmotel** [sindresorhus/got#337]
I'm finding some inconsistencies on when an `end` event is emitted by `got.stream()`.

When a socket timeout occurs, an `error` event is emitted, followed by `end` event. But a request timeout emits `error` event only. The `end` event is also not emitted when an `ECONNREFUSED` error occurs (and possibly other errors too).

This is with got v7.0.0 and Node v6.10.2 on Mac OS 10.12.4.

It seems to me that the behaviour should be consistent - either all errors should also emit `end` on the stream, or none should. Personally I prefer the option that `end` should always be emitted.

Code to replicate:

```js
'use strict';

// Modules
const got = require('got');

let count = 0;
run();

function run() {
	count++;
	console.log(new Date(), `Starting attempt ${count}`);

	let bytes = 0, timer, req;

	const stream = got.stream('http://releases.ubuntu.com/16.04.2/ubuntu-16.04.2-desktop-amd64.iso', {
		retries: 0,
		timeout: {connect: 1000, socket: 1000, request: 1000}
	});

	stream.on('error', err => {
		console.log(new Date(), 'Error', err);
		if (timer) clearTimeout(timer);
	});

	stream.on('end', () => {
		console.log(new Date(), 'Ended');
		setTimeout(run, 5000);
	});

	stream.on('request', _req => {
		console.log(new Date(), 'Sent HTTP request');
		req = _req;
	});

	stream.on('response', res => console.log(new Date(), 'headers', res.headers));

	stream.on('data', chunk => {
		bytes += chunk.length;
		console.log(new Date(), `Received ${chunk.length} bytes, ${bytes} (${bytes / 1024}K) total`);
	});

	timer = setTimeout(() => {
		console.log(new Date(), 'Aborting');
		req.abort();
	}, 2000);
}
```

The above script attempts a download repeatedly and continues until it hits a request timeout (how long this takes to happen probably depends on your internet connection, for me can take 30 attempts). You'll see in logging output that the `end` event is not emitted after the request timeout.

**Comment by overlookmotel** [comment]
Any thoughts on this?

**Comment by sindresorhus** [comment]
Can you reproduce this with `master` branch?

`$ npm i sindresorhus/got`

**Comment by sindresorhus** [comment]
Not reproducible in master.
