### ISSUE TITLE
Improve timeout documentation

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#340]
The timeout info in the readme (https://github.com/sindresorhus/got#timeout) should document the default value used. Is it a number, if so what value? Or is it an object, if so what values do each of the keys have?

Also, in versions older than 7.0.0 I used to do

```js
got(url, {
  timeout: 5000
})`
```

Is the following the exact equivalent of the above in 7.0.0, or do I not need to change anything? Or instead of `request` below do I use `connect` or `socket`?

```js
got(url, {
  timeout: {
    request: 5000
  }
})`
```

**Comment by szmarczak** [comment]
`readme.md` (updated):

> ###### timeout
> 
> Type: `number` `Object`
> 
> Milliseconds to wait for the server to end the response before aborting request with `ETIMEDOUT` error (a.k.a. `request` property). By default there's no timeout.
> 
> This also accepts an object with separate `connect`, `socket`, and `request` fields for connection, socket, and entire request timeouts.

<br>

> Is the following the exact equivalent of the above in 7.0.0, or do I not need to change anything?

Yes, it is. There's no need to change anything.
