### ISSUE TITLE
response.req.headers is empty object in node 8

### ISSUE THREAD

**Issue by gunjam** [sindresorhus/got#342]
When running node 8 the request object in the resolved response always has a headers property of an empty object regardless of how many headers were set. This does not occur when running node 6.

The headers are correctly set in the outbound request in both versions of node, just in node 8 they are not added to the response's request object.

Ta.

**Comment by kevva** [comment]
I Node.js v8 you have to use `res.req.getHeader(name)` or `res.req.getHeaders()`. See https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_response_getheader_name for more info.

**Comment by gunjam** [comment]
Ah! Ok, sorry :) Thanks for the info.
