### ISSUE TITLE
How to handle 4XX and 5XX errors?

### ISSUE THREAD

**Issue by bertolo1988** [sindresorhus/got#343]
I was trying to setup a test where i expected an error 401.

```
    nock(url)
        .post('/myroute')
        .reply(401, {sometStuff:'nice error'});

```
I was expecting my promise to resolve with a response with statusCode=401 and a few other parameters on my body but i got an error instead:

```
{ HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (/home/tbertolo/code/myproject/my-client/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'HTTPError',
  host: 'myhost.com:80',
  hostname: 'myhost.com',
  method: 'POST',
  path: '/myroute',
  protocol: 'http:',
  url: 'http://myhost.com/myroute',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers: {} 
```

I went in the code to see what was happening... and then i found the cause:

```
if (statusCode !== 304 && (statusCode < 200 || statusCode > limitStatusCode)) {
	throw new got.HTTPError(statusCode, res.headers, opts);
}
```

Can you guys fix this? I would like to handle the errors on my own.

Am i doing something wrong?

**Comment by sindresorhus** [comment]
Got considers anything other than 2xx failure. If you want to handle it yourself you can simple `.catch()` it. The `response` is attached to the error.

**Comment by bertolo1988** [comment]
@sindresorhus thanks alot for clarifying.
