### ISSUE TITLE
Cannot cancel when timeout option is set

### ISSUE THREAD

**Issue by Lalem001** [sindresorhus/got#344]
When the options.timeout, or options.timeout.request, is set, the `pCancelable` promise is wrapped in a `pTimeout` promise. This prevents the possibility of calling cancel.

See [index.js#L130-L132](https://github.com/sindresorhus/got/blob/master/index.js#L130-L132).

Is this intentional?

**Comment by Lalem001** [comment]
While on the topic of cancel and timeout, should the timeout cancel the request?

**Comment by sindresorhus** [comment]
Thanks for reporting. Looks like an oversight on our part.

The timeout should cancel the request, yes, but I don't think that's working either right now.

// @djmadeira

**Comment by sindresorhus** [comment]
Does it make sense if `p-timeout` calls `.cancel()` on the input promise if that method exists when a timeout happens? And `p-timeout` should have a `.cancel()` method itself that cancels the timeout and calls the `.cancel()` method of the input promise if any. How does that sound?

// @floatdrop @lukechilds @AlexTes

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/pull/360 fixes the issue with a workaround, but I prefer to eventually fix this properly in `p-timeout`, so reopening this so we don't forget.
