### ISSUE TITLE
`electron.net` in renderer process

### ISSUE THREAD

**Issue by maccelerated** [sindresorhus/got#346]
Maybe I am not supposed to be doing network labor in the renderer processes, but `got` explodes when used there.

- `Uncaught TypeError: this.on is not a function`
- `Uncaught TypeError: this.on is not a function`
- `Uncaught TypeError: Cannot read property 'ended' of undefined`
- `Uncaught TypeError: Cannot read property 'corked' of undefined`

The issue seems to just be with `got@^7` and Electron.

- `require('got')('https://google.com');` does not work
- `require('electron').remote.require('got')('https://google.com');` does work

**Comment by maccelerated** [comment]
Well, I cried wolf. The issue seems to just be with `got@^7` and Electron

**Comment by maccelerated** [comment]
I tracked it down into Electron's IPC code. It seems to be the perfect storm between `get-stream` and Electron's `_writable_stream` and remote calling `.write()` with global scope instead of the steam instance.

**Comment by maccelerated** [comment]
Root of the problem and its fix.

```JavaScript
const stream = require('stream')
const {net} = require('electron').remote

const request = net.request('https://example.com');

request.on('response', (response) => {
  const str = new stream.PassThrough()
  str.write = str.write.bind(str)
  str.once = str.once.bind(str)
  str.end = str.end.bind(str)
  str.on = str.on.bind(str)
  response.pipe(str);
})

request.end()
```

**Comment by sindresorhus** [comment]
Electron issue: https://github.com/electron/electron/issues/10017

**Comment by Siilwyn** [comment]
> Maybe I am not supposed to be doing network labor in the renderer processes.
Why not?

Just bumped into the same problem, what would the best workaround be?

**Comment by maccelerated** [comment]
Moving `got` out of the renderer was going to be unrealistic, so now I just have the `useElectronNet` option hardcoded everywhere I use `got`. If someone else's package is using `got`, that'll be a different story.
