### ISSUE TITLE
Uncaught error: The header content contains invalid characters

### ISSUE THREAD

**Issue by pietermees** [sindresorhus/got#353]
I've been seeing occasional uncaught exceptions:
```
Uncaught error: TypeError: The header content contains invalid characters 
   at get (/var/app/current/node_modules/got/index.js:49:18) 
   at Immediate.setImmediate (/var/app/current/node_modules/got/index.js:124:3)
```
Scanning the code it seems that errors thrown directly by `http.request` or `https.request` on that line are not caught.

This is happening on a server that processes a very large number of http requests and I haven't been able to track down which requests cause this error.

**Comment by sindresorhus** [comment]
What exact version of Got do you have installed and how are you using it (Promise API or Streaming)?

**Comment by sindresorhus** [comment]
Wonder if it's something like https://github.com/request/request/issues/2120 or https://stackoverflow.com/questions/43194065/node-js-http-typeerror-the-header-content-contains-invalid-characters

**Comment by pietermees** [comment]
That would be 7.1.0 and Promise mode

**Comment by sindresorhus** [comment]
I think this is fixed in master. Could you try running master?

I could reproduce the unhandled exception when I put a throw statement in 7.1.0 here: https://github.com/sindresorhus/got/blob/b725ef576864fc6dd331b4df58ddb12f2f7d6b3a/index.js#L48 When I did the same in master, it was handled, since we now correctly catch and propagate errors: https://github.com/sindresorhus/got/blob/8b040afc0749523fcaaf6db81702c27e74f7a1d2/index.js#L258-L260

**Comment by pietermees** [comment]
When I update to the latest commit on master and run my test suite, the process never exits and I'm getting a `(node:56384) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit` warning.

Could it be that some sort of memory leak was introduce in the master codebase since 7.1.0?

**Comment by sindresorhus** [comment]
Not sure. Usually, that warning is just an annoying false positive though.

**Comment by pietermees** [comment]
Yeah, I've noticed ;)
Although in this case it does seem to correlate with a bigger issue of my
process not exiting. No other errors or warnings though.

**Comment by pietermees** [comment]
I've been able to replicate this in my load tests. It seems that more and more listeners are added somewhere in the code and not cleaned up. Could it be that if a request fails some listeners are not removed?

Could this be somehow related to me using `agentkeepalive` to reuse sockets? Others might not be running into this if sockets are not being reused for thousands of requests?

**Comment by petitchevalroux** [comment]
@pietermees as stated in #382 original issue seems ok in master branch

I get the MaxListenersExceededWarning warning too on connect and request event but it may be better to open a new issue

**Comment by pietermees** [comment]
@petitchevalroux seems like @timdp opened up a new issue for the memory leak
I'll close this issue
