### ISSUE TITLE
Thrown HTTPError should include a response body

### ISSUE THREAD

**Issue by DaveLo** [sindresorhus/got#354]
Giving a cursory look at the library code there is one situation where an HTTPError is thrown after a response body has been parsed (below).

```
      if (opts.json && res.body) {
        try {
          res.body = JSON.parse(res.body);
        } catch (e) {
          if (statusCode >= 200 && statusCode < 300) {
            throw new got.ParseError(e, statusCode, opts, data);
          }
        }
      }

      if (statusCode !== 304 && (statusCode < 200 || statusCode > limitStatusCode)) {
        throw new got.HTTPError(statusCode, res.headers, opts);
      }
```

 I come here from an API consuming library using yours for its  [requests](https://github.com/MONEI/Shopify-api-node). The API in question sends back a detailed error response body, that would be hugely helpful in debugging but unfortunately is scrubbed by the HTTPError Method so what I get is:

```
"err":{
  "message": "Response code 422 (Unprocessable Entity)",
  "name": "HTTPError",
  "stack": "HTTPError: Response code 422 (Unprocessable Entity)
      at stream.catch.then.data (*****/node_modules/got/index.js:183:13)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)"
}
```
From adding some logging into the if block that throws the error I was able to get my error body, but ideally you should be able to get this data in the thrown error. Something along these lines maybe? [Gist](https://gist.github.com/DaveLo/e5d070078daf3eebdb4f7ba0f08ff083) - Lns 54, 70, 76

**Comment by floatdrop** [comment]
Response is there, but property is not enumeratable – https://github.com/sindresorhus/got/blob/master/index.js#L327 (to not bloat output).

Check the `response` property.

**Comment by DaveLo** [comment]
Ahh, that makes more sense. I appreciate the help.
