### ISSUE TITLE
Missing ParseError when JSON.parse fails on Mac OSX

### ISSUE THREAD

**Issue by bitstrider** [sindresorhus/got#355]
First off thanks for all the great work on this lib 💯 , it is indeed super-lightweight compared to `request`! 

So I noticed a bug in `got@7.1.0`, where this piece of code seems to fail silently on **Mac OSX 10**
```javascript
const got = require("got")

got("https://www.google.com",{json:true})
.then(res => {
  console.log(res)
})
.catch(err => {
  console.log(err)
}
```

From what I understand it should throw a `ParseError`

I have not tested on **Windows** yet, but it works fine on RunKit:
https://runkit.com/bitstrider/598ce38277f2670012f7b0e2

**Comment by sindresorhus** [comment]
You're missing a `)` at the end of your provided code. If I add that it works fine for me:

```
{ ParseError: Unexpected token < in JSON at position 0 in "https://www.google.com/":
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="...
    at stream.catch.then.data (/Users/sindresorhus/dev/oss/got/index.js:176:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'ParseError',
  host: 'www.google.com',
  hostname: 'www.google.com',
  method: 'GET',
  path: '/',
  protocol: 'https:',
  url: 'https://www.google.com/',
  statusCode: 200,
  statusMessage: 'OK' }
```

**Comment by bitstrider** [comment]
@sindresorhus oops that was a typo the post, here's a screenshot of my run:

![image](https://user-images.githubusercontent.com/143295/29218134-cd5b244c-7e81-11e7-8ee7-55385c811b44.png)

As you can see here there's no output

**Comment by sindresorhus** [comment]
Maybe try upgrading your Node.js version. I've tried with Node.js 4, 6, 8, and it works fine for me.

**Comment by bitstrider** [comment]
So I'm running node v6.2.0. Do you rule out it being a platform specific issue?

**Comment by sindresorhus** [comment]
6.2.0 is a very old version of the 6.x.x line. Please try upgrading to the latest 6.x.x before we continue this. I'm on macOS too, so I doubt it's platform specific.

**Comment by bitstrider** [comment]
Yep you were totally right, updated node and issue is gone. Thanks for your patience!
