### ISSUE TITLE
How to get IP address of the final destination host

### ISSUE THREAD

**Issue by abhishekdubey1** [sindresorhus/got#356]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/got/issues/356)

Hi,

How can I get the ip address of the final host after redirection?

Thanks,

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#827 Add remote ip address to response](https://issuehunt.io/r/sindresorhus/got/pull/827)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/got/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by szmarczak** [comment]
@sindresorhus Will this be implemented? I thought `gotResponse.socket.remoteAddress` would return that but it doesn't, I think I've missed something...

**Comment by sindresorhus** [comment]
Got returns the final URL in the response object, so you can use that to resolve it to an IP-address. Untested, but something like this should do it:

```js
const util = require('util');
const dns = require('dns');
const got = require('got');

(async () => {
	const response = await got('sindresorhus.com');
	const ip = await util.promisify(dns.lookup)(new URL(response.url).hostname, {family: 4}).address;
	console.log(ip);
})();
```

**Comment by Cerberooo** [comment]
@sindresorhus With native NodeJS (`{ get } = require('http')`) the IP is stored in the response object `response.connection.remoteAddress`. Is it possible to implement that also in Got, so no extra step is needed?

**Comment by sindresorhus** [comment]
@Cerberooo Can you show a code example of how it would look like and how you would use it?

**Comment by Cerberooo** [comment]
@sindresorhus I use it in a link checker tool to check only links from a specific IP range. Unfortunately I have to make two requests to get the IP address and the html of a link.

Example usage:
```javascript
const { get: get } = require('http');
const { get: getSsl } = require('https');

const url = new url.URL('https://github.com/sindresorhus/got/issues/356');

function getIp(url) {
    return new Promise(function(resolve, reject) {
        // Empty path for just checking the host
        url.pathname = '/';

        // Check if https
        if (url.protocol.includes('https')) {
            getSsl(url, function(response) {
                resolve(response.connection.remoteAddress);
            }).on('error', reject);

            return;
        }

        get(url, function(response) {
            resolve(response.connection.remoteAddress);
        }).on('error', reject);
    });
}

const ip = await getIp(url);
```

**Comment by sindresorhus** [comment]
And you want this, correct?

```js
const got = require('got');

(async () => {
	try {
		const response = await got('https://sindresorhus.com');
		console.log(response.body); //=> '<!doctype html> ...'
		console.log(response.ip); //=> 104.28.26.119
	} catch (error) {
		const {response} = error;
		console.log(response.body); //=> 'Internal server error ...'
		console.log(response.ip); //=> 104.28.26.119
	}
})();
```

---

Should it be `.ip`, `.ipAddress`, or `remoteAddress`?

@szmarczak Thoughts?

**Comment by Cerberooo** [comment]
Yep, revised code because I misunderstood your question.

In Got there is the connection object too. So I think its good when the ip is there, because when there is no connection there cant be an ip.

**Comment by szmarczak** [comment]
`.ip` or `.ipAddress` seems too general. I don't know if it's a local or remote IP. So either `.remoteIP` or `.remoteAddress`... Anyway I'm good with anything, it just needs to be documented. Let's choose one.

**Comment by sindresorhus** [comment]
But it’s on the “response”. Doesn’t that make it clear it’s the remote IP?

**Comment by szmarczak** [comment]
Yeah, it does. So maybe let's go with just `.ip`?

**Comment by sindresorhus** [comment]
👍
