### ISSUE TITLE
Got not working with electron (it crashes)

### ISSUE THREAD

**Issue by ngprasad** [sindresorhus/got#359]
I noticed this issue on electron with got. Here's the code snippet I am using:-
    `got(url, {
      headers: {
        Authorization: oauthHeader
      }    
    }).then((response) => {
      console.log(response.body);
    }).catch((e) => {
      console.log(e);
    });`

But it doesn't work and the app crashes. However if I add `useElectron: false` flag to options it works.

**Comment by kevva** [comment]
In what environment? And what error does it give you?

**Comment by andreygmc** [comment]
We got the same problem (got: "7.1.0", electron: "1.6.6"):
```
TypeError: this.on is not a function
at once (events.js:305:8)
at CallbacksRegistry.apply (.../electron.asar/common/api/callbacks-registry.js:48:42)
at EventEmitter.<anonymous> (.../electron.asar/renderer/api/remote.js:299:21)
at emitThree (events.js:116:13)
at EventEmitter.emit (events.js:194:7)
```
`useElectronNet = false` fixes the problem

**Comment by carvallegro** [comment]
Looking at [package.json](https://github.com/sindresorhus/got/blob/v7.1.0/package.json) file, there's no electron dependency. I'd look around this.

In [this commit](https://github.com/sindresorhus/got/commit/213057084cc4de325a829c82aae50d55b4f73c7d), electron is required and we can see that in the package.json "electron" has been added to the keywords, not to the dependencies 

Thank you for the workaround tho @ngprasad

**Comment by carvallegro** [comment]
Either that or there's there's a bad initialization of opts.useElectronNet or process.versions.electron because it requires it anyway

**Comment by kevva** [comment]
> Either that or there's there's a bad initialization of opts.useElectronNet or process.versions.electron because it requires it anyway. I am personally not using electron and have an issue with it.

We assumes that if `process.versions.electron` is `true` that you're in a `electron` environment and therefore it shouldn't be added as a dependency. In @andreygmc case it looks like he's using `electron` though but that something failed within it.
