### ISSUE TITLE
Include Host header

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#36]
[HTTP/1.1 RFC Section 14.23](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23):

> 14.23 Host
> A client MUST include a Host header field in all HTTP/1.1 request messages

Seems like we must support this?

[Relevant section in request](https://github.com/request/request/blob/v2.51.1/request.js#L457-L468)

**Comment by sindresorhus** [comment]
Agh, so why don't node do that for us then...

Does any of the other tiny HTTP libs implement this?

**Comment by floatdrop** [comment]
@sindresorhus in fact, it does - https://github.com/joyent/node/blob/v0.10.35-release/lib/http.js#L1381-L1386
