### ISSUE TITLE
Progress Events with Promises?

### ISSUE THREAD

**Issue by framerate** [sindresorhus/got#361]
```
got('todomvc.com')
	.on('downloadProgress', progress => {
		// Report download progress
	})
	.on('uploadProgress', progress => {
		// Report upload progress
	})
	.then(response => {
		// Done
	});
```

Copy pasted from docs straight into my electron app:

```
TypeError: got(...).on is not a function
```

Am I missing something or was this functionality removed?

**Comment by AlexTes** [comment]
Not released yes @framerate 😉 .
You need to take a look at the latest released README. Either through the [tagged commit](https://github.com/sindresorhus/got/tree/v7.1.0#readme) or [npm page](https://www.npmjs.com/package/got).

**Comment by framerate** [comment]
Ok thank you!

**Comment by pregnantboy** [comment]
Any idea when will this feature be released?

**Comment by framerate** [comment]
#366 just popped up too, @AlexTes, if you have any info on how we can help wrap up the latest release! Seems like people really want the feature! :)
