### ISSUE TITLE
Calling got.stream via options flag with got()

### ISSUE THREAD

**Issue by zfoster** [sindresorhus/got#362]
Looking through the source, I see `got.stream` calls `asStream`, with got calling `asPromise`, with the various methods added one level down.

I'd love to be able to do something like: 

```
got(url, {
  stream: true
})
``` 

which under the hood would call `asStream`. Something similar is fine too.

The use case is to have got wrapped so each request has the same configurable retries and timeout specs.

**Comment by sindresorhus** [comment]
👍

**Comment by Lancher** [comment]
So it will be something like returning a new stream object from `got()`?
```
const stream = await got(url, {stream: true, ...})
stream.pipe(process.stdout)
```

**Comment by sindresorhus** [comment]
@Lancher Without the `await`, yes.

**Comment by zfoster** [comment]
Thanks! 👍
