### ISSUE TITLE
Example from readme doesn't seem to work

### ISSUE THREAD

**Issue by astoilkov** [sindresorhus/got#366]
Tried to use the example below but it doesn't seem to work with `7.1.0`. The `on` method is not defined.

> Note: Progress events can also be used with promises.
> ```
> got('todomvc.com')
> 	.on('downloadProgress', progress => {
> 		// Report download progress
> 	})
> 	.on('uploadProgress', progress => {
> 		// Report upload progress
> 	})
> 	.then(response => {
> 		// Done
> 	});
> ```

**Comment by astoilkov** [comment]
Oops. I found out why. The commit is after the `7.1.0` release. It would be awesome to use this feature. Is a `7.2.0` release coming soon or should I use a more complicated approach?

**Comment by framerate** [comment]
I'm also curious what the status of the new release is! Is there a roadmap we can see or somehow we can help finish it?

**Comment by sindresorhus** [comment]
Closing as v8 is the latest release now.
