### ISSUE TITLE
Wrong request payload serialization

### ISSUE THREAD

**Issue by joaom182** [sindresorhus/got#370]
Hello,

I've an issue with `PATH/PUT/POST` requests.

**Application A** send a request to **Application B** with `payload` data.

The `got` implemenation:

```javascript
got.patch(`${API_URL}/${appId}/app-metadata/${userId}`, {
   headers: {
      Authorization: `Bearer ${API_TOKEN}`
   },
   json: true,
   body: {
      roles: ["system.access"] // -> Array String
   }
})
```

But **Application B** serielizes payload like this:

```javascript
let payload = request.payload // {  roles: "system.access" } --> A String rather than Array String
```

Has anyone ever faced this problem?

**Comment by kevva** [comment]
We have a test for this here https://github.com/sindresorhus/got/blob/master/test/post.js#L72-L78. How do you parse it in the API?

**Comment by joaom182** [comment]
@kevva if you pass two items in array, it's works... but if you pass only one not works.

**Comment by kevva** [comment]
Works fine for me.

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests) and I'll take a closer look.
