### ISSUE TITLE
Why are you throwing on status 503?

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [sindresorhus/got#371]
`got` gives me an error and no response body when a server answers with a status code 503. This is the case whenever a page is protected by Cloudflare. `request` gives me a 503 status as well, but it also correctly downloads the response body and I can then go on to the real page. With `got` I can't do anything.

A page you can use to test this would be https://torrents.me - the first one I found that always serves Cloudflare's page on the first visit (clear your cookies if you want to see it again). You can try to `got` it - it will throw - and then `request` it - it won't and it will give you the body.

I need `got` to go on and download the response body. As long as it doesn't I can't switch to it (I would like very much to do that). I also believe `got` should be as capable as the browser for all things that are about getting webpages (whereas I think it's OK to leave the handling of cookies and other extra stuff to other modules).

Thank you for reading!

**Comment by kevva** [comment]
The body is still available on `err.response.body`:

```
got('http://service.unavailable').catch(err => {
    console.log(err.response.body);    
});
```

**Comment by sindresorhus** [comment]
Got rejects the promise for anything that is not a success (unlike `request`). We think it's better to handle unsuccessful requests in an alternative code-path.

**Comment by MySidesTheyAreGone** [comment]
Oh sorry guys, I see it's in the docs after all; I missed it. Thanks!

**Comment by MySidesTheyAreGone** [comment]
Ahem, do you do that in stream mode too? Because I'm not seeing it. Here's all the keys on the error object:

```
[ 'name',
  'host',
  'hostname',
  'method',
  'path',
  'protocol',
  'url',
  'statusCode',
  'statusMessage',
  'headers' ]
```
I use streaming so I can abort if the download size is too large.
