### ISSUE TITLE
Proxy request from KOA2 with pipe stream

### ISSUE THREAD

**Issue by JasonBoy** [sindresorhus/got#374]
I was trying to proxy the requests from koa2 application  to a api endpoint:
```javascript
ctx.req.pipe(got.stream(apiEndpoint + ctx.url, {method: ctx.method})).pipe(ctx.res)
```
but looks like it always return 404, when I switch back to `request`, it works again

**Comment by kevva** [comment]
Could you post the error?

**Comment by sindresorhus** [comment]
`got.stream` is a readable stream, not a transform stream.

**Comment by kevva** [comment]
I think his code should work. When writing to `got.stream` the data gets posted to the URL and the response is then piped. We've one example in the tests https://github.com/sindresorhus/got/blob/master/test/stream.js#L50-L55.

**Comment by JasonBoy** [comment]
@kevva inside the () or not should be the same since pipe will return the stream inside .pipe(), and  I try to recoding the requests from got, looks like all the headers were discarded, only with some default headers added by got, resulting all the session info from cookies are missed, so the result is that I cannot just pipe the request to got? or i can only set the headers manually?

**Comment by kevva** [comment]
> or i can only set the headers manually?

Yes, you'll have to set them manually.

**Comment by JasonBoy** [comment]
and on the other hand, `got.stream` 's http response, including headers will not pipe to ctx.res?

**Comment by kevva** [comment]
Yes, it will. It's just the headers from the incoming request that doesn't get applied (I think).

**Comment by JasonBoy** [comment]
@sindresorhus if `got.stream` is a readable stream, then the code in readme: 
`fs.createReadStream('index.html').pipe(got.stream.post('todomvc.com'));` it pipes a readable stream to `got.stream.post`(is this a writable stream?), pipe() should pipe to a writable stream , right? 
or the `got.stream` and `got.stream.post` returns a different type of stream?

**Comment by kevva** [comment]
Yes, if you do a `POST`, `PUT` or `PATCH` it'll return a `Duplex` stream, otherwise it's just a `Readable`.
