### ISSUE TITLE
Get the original error when using streams?

### ISSUE THREAD

**Issue by paambaati** [sindresorhus/got#377]
How do I get the original `Error` object on a stream error? I throw custom error messages (for example, `throw new Error("Some specific error message goes here!");`), and would like to preserve them.

Currently, `got` transforms them into —

```json
{
    "type": "StdError",
    "message": "Response code 500 (Internal Server Error)",
    "name": "HTTPError",
}
```

**Comment by kevva** [comment]
Have you checked `err.response.body`?

**Comment by paambaati** [comment]
@kevva `err` doesn't have a `response`.

**Comment by paambaati** [comment]
@kevva Simple repro —

```node
const http = require('http');
const got = require('got');

const server = http.createServer((request, response) => {
    response.writeHead(500, { 'Content-Type': 'application/json' });
    response.write(JSON.stringify({
        error: true,
        message: 'test error',
        status: 999
    }));
    response.end();
});

server.listen(1080, () => {
    console.log("Server is listening");
    const gt = got('http://localhost:1080/');
    gt.then(proxyResponse => {
        console.log('RECEIVED RESPONSE!');
    }).catch(err => {
        console.error('ERROR', err);
    });
});
```

**Comment by brandon93s** [comment]
`err.response` is now provided by got (tested against master) and the original error can be found in `err.response.body`.

Using the sample reproduction script above, change the error log to `console.log('Original Error', err.response.body)` to log the original error.

![image](https://user-images.githubusercontent.com/4730164/42413655-9a1545d4-81f2-11e8-92f9-f094d3b1fed8.png)
