### ISSUE TITLE
Misguiding message on not 200 status code

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#38]
This take me a wile to figure out, that I don'' have network problems from this error message:

```
Error: Couldn't connect to http://subhost.yandex.net.
```

Could we change it to somethig more accurate (that may include status code):

```
Error: Response status code from http://subhost.yandex.net is not OK (403).
```

**Comment by sindresorhus** [comment]
:+1: I'm always happy to improve error messages.

**Comment by kevva** [comment]
https://github.com/jshttp/statuses
