### ISSUE TITLE
Uncatched errors when http/https.request throw an exception

### ISSUE THREAD

**Issue by petitchevalroux** [sindresorhus/got#382]
I'm using got to request non node web server and sometimes I get two types of uncatched errors : 

 - TypeError: The header content contains invalid characters
 - TypeError: Request path contains unescaped characters

I tried to reproduce this in tests but at the moment I failed because I can't send invalid characters in node http/https server (as it throw the same exception but in createServer)

Here is the callstack : 
TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:52:11)
    at Object.exports.request (http.js:31:10)
    at get (/Users/patrick/code/node-http-download-stream/node_modules/got/index.js:49:18)
    at Immediate.setImmediate (/Users/patrick/code/node-http-download-stream/node_modules/got/index.js:124:3)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) 

with node v6.11.3

**Comment by petitchevalroux** [comment]
@sindresorhus this issue affect npm publish version but not current master.

To reproduce just clone this branch https://github.com/petitchevalroux/got/tree/uncatched-error
and run [code here](https://github.com/petitchevalroux/got/blob/uncatched-error/uncatched.js) : 

node uncatched.js
/Users/patrick/code/got/uncatched.js:7
    throw new TypeError("Request path contains unescaped characters");
    ^

TypeError: Request path contains unescaped characters
    at Object.http.request (/Users/patrick/code/got/uncatched.js:7:11)
    at get (/Users/patrick/code/got/node_modules/got/index.js:49:18)
    at Immediate.setImmediate (/Users/patrick/code/got/node_modules/got/index.js:124:3)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

I wish to contribute by adding unit tests to the current version in order to avoid any futur issue but I can't find any mock framework in this project in order to cleanly mock http.request behavior.
Did you plan to use one ? If not I suggest [sinon.js](http://sinonjs.org/)

And last question do you plan to publish current master to npm ?

**Comment by sindresorhus** [comment]
Yes, Sinon is fine. I plan to do a new release in a couple of days.

**Comment by petitchevalroux** [comment]
As stated in https://stackoverflow.com/questions/37900687/problems-with-ava-asynchronous-tests-when-stubbing-with-sinon test.serial seems mandatory

**Comment by petitchevalroux** [comment]
Duplicate of #382

**Comment by lukechilds** [comment]
@petitchevalroux Just to keep you updated:

> I wish to contribute by adding unit tests to the current version in order to avoid any future issue

In the next release the behaviour will be slightly different. If the request function throws, Got will throw an instance of `got.RequestError` rather than throwing the raw error from the request function.

Your code will most likely continue to work with this change but just a heads up.

More info here: https://github.com/sindresorhus/got/pull/412

**Comment by pcraum** [comment]
@lukechilds ty for the update ;)

**Comment by petitchevalroux** [comment]
@lukechilds ty for the updates ;)
