### ISSUE TITLE
v7 retry on timeout

### ISSUE THREAD

**Issue by elpaxdota** [sindresorhus/got#385]
Sorry for opening this but I need some explanation. I have this code:

    var req = got(url, { retries: 10, timeout: 3000 })
    .then(response => {
    	return response.body;
    })
    .catch(err => {
    	if (err.name === "RequestError" && err.code === "ETIMEDOUT") {
    		console.log("get request timed out");
    	    	req.cancel();
	    }
    });
    return req;

So timeout is working, but req does not repeat. What I need to do ? I have got@7.1.0 installed.

**Comment by szmarczak** [comment]
@brandon93s Yeah. Haven't checked this one.
