### ISSUE TITLE
Create new Release 7.1.1

### ISSUE THREAD

**Issue by SrPatinhas** [sindresorhus/got#389]
Im trying to use a package that as got as dependency, and I'm using it with electron, witch dont let me to do uploads because of the useElectronNet: false`, and I would like to know if it could be made a release for that fix.

Thanks

**Comment by sindresorhus** [comment]
I plan to do a new release today or tomorrow. Nothing is stopping you from using `npm i sindresorhus/got` directly though.

**Comment by sindresorhus** [comment]
New release is out: https://github.com/sindresorhus/got/releases/tag/v8.0.0
