### ISSUE TITLE
got.stream creating different file from same URL

### ISSUE THREAD

**Issue by framerate** [sindresorhus/got#397]
This is a weird one...

I wrote this script `fuckyou.js`:
```
const fs = require('fs');
const path = require('path');
const got = require('got');

got.stream('https://s3-us-west-1.amazonaws.com/scl-cdn/doomtrooper/assets/video.md5').pipe(fs.createWriteStream(path.join(__dirname, '/fuckyou.md5')));
```

And then I run it...

```
➜  dt-client git:(master) ✗ node fuckyou.js 
➜  dt-client git:(master) ✗ cat fuckyou.md5 
b05eea1123e1b191dc4aa198ec62422f
```

But inside my electron code, I put:

```
got.stream('https://s3-us-west-1.amazonaws.com/scl-cdn/doomtrooper/assets/video.md5').pipe(fs.createWriteStream(path.join(__dirname, '/fuckyou.md5')));
```

which creates the `fuckyou.md5` in my electron folder...

contents:
```
61bf54985c111c3bb43cace3ceb655ea
```

If you curl the file, you'll see the standalone `b05eea1123e1b191dc4aa198ec62422f` is correct.

PLEASE TELL ME WHAT I'M DOING WRONG. I'm starting to feel like a crazy person here...

**Comment by framerate** [comment]
UPDATE:

I tried using `request` instead.

```
    const request = require('request');
    request('https://s3-us-west-1.amazonaws.com/scl-cdn/doomtrooper/assets/video.md5').pipe(fs.createWriteStream(path.join(__dirname, '/fuckyou.md5')));
```

prints `b05eea1123e1b191dc4aa198ec62422f` to file. 

This seems to be a bug in got... Help!

**Comment by lukechilds** [comment]
Does tweaking this option help?

https://github.com/sindresorhus/got#useelectronnet

**Comment by framerate** [comment]
> Does tweaking this option help?

Unless I'm misreading the README, it appears that option is for HTTP mode, not stream mode:

`got(url, [options])`

Could just be the layout of the README though?

**Comment by lukechilds** [comment]
Those options apply to `got` and all helper methods.

**Comment by framerate** [comment]
> Those options apply to got and all helper methods.

Gotcha, I'll give it another try. I reverted everything to request and everything is working as expected. I've spent the last 2 days debugging this thinking I was going crazy! Definitely something wonky going on here. 

If you want to investigate too, that file should be public.

**Comment by lukechilds** [comment]
Yeah, I know Sindre had similar issues with electron: https://github.com/sindresorhus/got/issues/315

**Comment by framerate** [comment]
@lukechilds that looks like it entirely could be the same bug. I assume that fix is NOT on npm yet?

**Comment by lukechilds** [comment]
Sorry, edited my last comment with more info as you were replying ^

**Comment by framerate** [comment]
> Sorry, edited my last comment with more info as you were replying

Got it! Thanks for the quick response. How frustrating this weekend has been for me!

I hope this new release is out soon, I think it includes the `progress` event and I'm eager to work that into my app!

**Comment by lukechilds** [comment]
We've made some major changes to Got in master, however a few obscure bugs sneaked their way in, unfortunately I've been too busy with client work to iron them out. Hoping to get them sorted next week so a new release should be out very soon.

**Comment by brandon93s** [comment]
This appears to be functioning correctly with `electron@latest` and current got master.

```js
// demo.js
const fs = require('fs');
const path = require('path');
const got = require('./source/index');

got.stream('https://s3-us-west-1.amazonaws.com/scl-cdn/doomtrooper/assets/video.md5')
.pipe(fs.createWriteStream(path.join(__dirname, '/demo.md5')));
```

```sh
got master = $ node .\demo.js
got master = $ cat .\demo.md5
f3dabdb85243b4b772da84fba640989b

got master = $ npx electron .\demo.js
got master = $ cat .\demo.md5
f3dabdb85243b4b772da84fba640989b
```
