### ISSUE TITLE
Support for binary files

### ISSUE THREAD

**Issue by julien-f** [sindresorhus/got#4]
IMHO, it is too bad that this module cannot be used for binary content due to the `setEncoding('utf-8')`.

I think it should instead return a buffer and let the user call `toString()` to obtain a string if necessary.

See https://gist.github.com/julien-f/9cc9976ce768890eb274#file-get-js for inspiration, maybe :)

**Comment by shaunc** [comment]
Is there any way to get `response.body` as a buffer if you want it that way? Seems even with `{encoding: 'binary'}` response body is string. Or do you have to use stream?

**Comment by sindresorhus** [comment]
@shaunc From the docs:

> Encoding to be used on setEncoding of the response data. **If null, the body is returned as a Buffer.**

`binary` is a string encoding, not actual binary nor buffer.
