### ISSUE TITLE
Proxy headers in got.stream

### ISSUE THREAD

**Issue by tarmolov** [sindresorhus/got#401]
I use `got@6.7.1`. I need to proxy an url from some upstream. So, I do
```
got.stream(url).pipe(res);
```
where `res` is an express response.

But it proxies only body, not headers. To proxy headers as well I have to add an extra handler
```
got.stream(url)
    .on('response', (msg) => {
        res.set(msg.headers);
    })
    .pipe(res);
```

Is it expected behaviour? For example `request` library proxies body and headers out of the box.

**Comment by sindresorhus** [comment]
It's just an oversight. It should proxy headers too.
