### ISSUE TITLE
How to set multiple cookies

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#408]
The demo in the README shows how to pass a single cookie, but what's the recommended approach for passing multiple cookies along with the request?

**Comment by harryparkdotio** [comment]
since `got` takes in any `<key>: <value>` set in headers and passes them to the request, the recommended approach would be to do the following:

```js
{
    ...
    headers: {
        ...
        cookie: [cookie.serialize('foo', 'bar'), cookie.serialize('fizz', 'buzz')].join(';'),
        ...
    },
    ...
}
```
