### ISSUE TITLE
Clean way to parse cookies from response

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#409]
Right now if I want to get a cookie from the response, I need to do something like `response.headers['set-cookie'].find(header => header.startsWith('myCookie='))` which isn't nice. It would be great to have a way to do something like `response.cookies` which would return something like

```js
myCookie: {
  line: 'myCookie=myValue; expires=Wed, 23-Dec-2022 01:15:27 GMT; Max-Age=158201182; path=/; domain=.site.com',
  value: 'myValue',
  expires: Date('Wed, 23-Dec-2022 01:15:27 GMT'),
  maxAge: 158201182,
  path: '/',
  domain: '.site.com'
},
anotherCookie: {
  ...
}
```

**Comment by gkcgautam** [comment]
@rightaway You may use the [set-cookie-parser](https://www.npmjs.com/package/set-cookie-parser) package for parsing the `set-cookie` header. The output from this module is similar to what you need.
