### ISSUE TITLE
Don't include a given request header when its value is null or undefined

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#410]
If you do `got(url, { headers: { cookie: null } })`, the HTTP request has a header of `cookie: null` rather than not appearing at all. If you replace `null` with `undefined` then you get an error.

If a header is `null` or `undefined` the it shouldn't be added to the request headers.

**Comment by sindresorhus** [comment]
Agreed. Would you be interested in doing a pull request?

**Comment by rightaway** [comment]
I could take a look at it sure. Could you give me a pointer on which part of the code to study that would be relevant to this?

**Comment by lukechilds** [comment]
This is probably what you're looking for:
https://github.com/sindresorhus/got/blob/master/index.js#L461-L464
