### ISSUE TITLE
Bug - Problems in the declaration of dependencies

### ISSUE THREAD

**Issue by Angelk90** [sindresorhus/got#432]
@sindresorhus :
In the package.json file, the following dependencies are missing:
- events
- http
- https
- stream
- url
- fs
- querystring
It would be very useful to add it.

**Comment by sindresorhus** [comment]
Those are Node.js built-ins and should not be defined as dependencies.

https://nodejs.org/api/modules.html#modules_core_modules

**Comment by Angelk90** [comment]
@sindresorhus : I had to install them manually, one by one, otherwise it did not work, so what should I do?

**Comment by sindresorhus** [comment]
Use http://webchat.freenode.net/?channels=node.js for Node.js support questions ;)
