### ISSUE TITLE
Unable to resolve module http

### ISSUE THREAD

**Issue by Angelk90** [sindresorhus/got#433]
What can be causing this problem?

my dependencies:
	"dependencies": {
		"events": "^1.1.1",
		"fs": "0.0.1-security",
		"google-translate-api": "^2.3.0",
		"http": "0.0.0",
		"https": "^1.0.0",
		"querystring": "^0.2.0",
		"react": "16.0.0",
		"react-native": "0.50.4",
		"stream": "0.0.2",
		"url": "^0.11.0"
	},

![errorgot](https://user-images.githubusercontent.com/20476002/33514507-600c1194-d755-11e7-971a-de1b62194b95.jpg)

**Comment by sindresorhus** [comment]
Please don't open duplicate issues. I already answered your question.

**Comment by sangram7031** [comment]
please send me the link or solution I have the same issue
