### ISSUE TITLE
[README] Proxy walkthrough by tunnel

### ISSUE THREAD

**Issue by zckrs** [sindresorhus/got#435]
Hi,

Since some day I try to use `got` with proxy (httpsOverHttp) through agent.

I follows https://github.com/sindresorhus/got#proxies who purpose to use [`tunnel`](https://github.com/koichik/node-tunnel).

Unfortunately I never succeeded to get my API with the [`tunnel`](https://github.com/koichik/node-tunnel).

But when I replace
```diff
- const tunnel = require('tunnel');
+ const tunnel = require('tunnel-agent');
```

:tada: everythings works well.

Can we update README to use [`tunnel-agent`](https://github.com/request/tunnel-agent) instead of  [`tunnel`](https://github.com/koichik/node-tunnel) ?

Related https://github.com/sindresorhus/got/issues/79

**Comment by buschtoens** [comment]
Facing the same problems. `tunnel-agent` works though. For anyone stumbling across this, who wants `HTTP_PROXY` and `HTTPS_PROXY` environment variables to just work :tm: , install [`caw`](https://github.com/kevva/caw) as suggested here in #79.

```js
got('http://github.com', {
  agent: {
    http: caw({ protocol: 'http' }),
    https: caw({ protocol: 'https' })
  }
});
```
