### ISSUE TITLE
Got Overwriting cache with 304 response - should use existing cache

### ISSUE THREAD

**Issue by jvetyska** [sindresorhus/got#445]
Just ran into a serious problem with Got caching.

I am requesting the same file multiple times and using javascript Map to cache the file (via a CLI).
The first time the file is requested, the cache entry doesn't exist, so it's undefined, that is correct.
The second time the file is requested, the cache entry exists, it's got status 200, and body.
The third and subsequent time the file is requested, the cache entry is overwritten with the 304 response, with blank body. 

Got should return the cached resource when available, instead of making fresh request and then overwriting the cache with worthless data.

**Comment by rarkins** [comment]
@lukechilds are you aware of this or have any insight? I had a disaster with Renovate when I enabled caching for querying Docker Hub. I never got back to debugging it but it sounds very similar to the above.

**Comment by lukechilds** [comment]
Thanks for the detailed description, if you can provide some code reproducing the error I'll take a look as soon as I can.

**Comment by jvetyska** [comment]
Maybe this can be solved with `got` adding an option to force the use of cache.
The problem seems to arise when you are requesting from server that has no-cache policy or none specified.
Using `got` you may not be aware of it and still want to cache the pages in memory (Map for example) but what you end up with instead is a mess. It is common practice for servers to return 304 response if the content didn't change - and that is the big problem with current way `got` is implemented with caching requests - as you will end up with cached 304 response with no content.
There are application when many URLs need to be requested and many may be duplicates so the caching is very useful feature. However it seems that it would be very beneficial to be able to override the cache policy of the response or just simply allow stale content.

**Comment by lukechilds** [comment]
The underlying implementation Got uses is here: https://github.com/lukechilds/cacheable-request

As far as I'm aware it follows RFC 7234 exactly. If the cacheing behave's differently to how you want then either:

1. RFC 7234 Caching is not what you want to do, you should disable the in built caching and implement your own custom cache logic.
2. There is a bug in my RFC 7234 implementation and it's not behaving correctly.

If you can provide some test code and tell me what you're expecting to do and what it's doing instead I can tell you which one of those is happening. And push a fix if it's 2.

**Comment by jvetyska** [comment]
@lukechilds, I think the first case is more relevant. I think it's the fact that `got` allows caching of requests, there can be a lot of unforeseen issues down the road, because the caching fully depends on the headers, but it may provide false hope that all the requests are indeed cached. And you are well aware of all the problems with 304 server response. 
So I think it is great to follow the RFC spec, however it might be good idea to help clear the air and solve a lot of potential issues by adding a flag that would force `got` to use cached content when available to avoid all the potential revalidation response issues and make the code more predictable for those application that expect to use the cache without the need to reinvent the wheel.

**Comment by reggiezhang** [comment]
I also encounter this issue.

**Comment by lukechilds** [comment]
@reggiezhang Do you still get the same issue if you use `got` instead of `got.stream`?

It's possible that you're consuming the stream before I get a chance to copy it which would also explain the apparent random occurrence.

**Comment by reggiezhang** [comment]
@lukechilds I haven't try got instead of got.stream currently. I'll let you know if I meet same issue by got later.

**Comment by szmarczak** [comment]
I can't reproduce w/ master: https://gist.github.com/szmarczak/61130bc351c72f2ee1e2228429b1df4d (tried streams too)

**Comment by lukechilds** [comment]
`cacheable-request@6.0.0` published which *I think* should resolve this. I'd be grateful if anyone who was encountering the issue could test this.

@szmarczak @sindresorhus Will obvs need to update `cacheable-request` in Got to get the major version so might be better if we can get some users to test this before we pull the trigger.

It is also technically a breaking change due to the fact it changes the API, but only at a very minor level that people shouldn't really be relying on anyway. So although it's unlikely to cause any issues, if we update Got to use this version we should probably major bump Got too.
