### ISSUE TITLE
Retrieving data from request on error

### ISSUE THREAD

**Issue by MattRh** [sindresorhus/got#446]
Situation: I have to work with service that provide janky API, on some errors it returns HTML answer instead of JSON answer. Earlier in version ^6.0 there was a way to catch an exception on JSON parse(i.e. statusCode 502 and some HTML answer that contains information).
In version ^8.0 I couldn't find any way to get responce data from server when error is >400. Can you add responce body into HttpError or add some option that allows me to catch ParseError with any statusCode returned by service?

**Comment by sindresorhus** [comment]
The response should be available on all errors, see docs. You could check for `instanceof got.ParseError`.

**Comment by MattRh** [comment]
In new versions this code prevents me from catching all parse errors
```
if (statusCode >= 200 && statusCode < 300) {
	throw new got.ParseError(err, statusCode, opts, data);
}
```
And event when I can catch parseError I am not able to get full responce, because it is cut by `data.slice(0, 77)`

**Comment by ronnyhaase** [comment]
I'm just running into a similar problem:
In case the server e.g. sends a 400 or 422, it's very likely that there is a body containing details what is wrong, which I can not access because body is not passed in erroring response...

**Comment by ronnyhaase** [comment]
OK, I've got my answer: I can use the response property from the error, `error.response.body`.
Where `error` is what I receive in a catch.

Still, it might be considerable to also pass body to the error object in case of a `HTTPError` or add documentation for this case?

**Comment by MattRh** [comment]
@ronnyhaase can you show in sources, where error.responce is set? Because I don't have much opportunity to test errors by hands and just analysing sources

**Comment by ronnyhaase** [comment]
Right here 😉:
https://github.com/sindresorhus/got/blob/master/index.js#L347

So you have access to the response (incl. the body), like this:
`got(/* ... *).catch(error => error.response /* ... */)`

**Comment by ronnyhaase** [comment]
@MattRh It should also be possible to solve your scenario:

`got('https://httpstat.us/400', { json: true }).catch(e => console.error(e.response.body))`

So I tell GOT to expect JSON, while I get text. Still e.response.body is a String. No parsing error or something.

**Comment by MattRh** [comment]
Yes, thanks. I think this issue can be closed

**Comment by ErikPettersson** [comment]
This gets the response body — but it doesn't feel like the most suitable solution.
Possibly it might not ever close the stream if there is no body sent?

Why couldn't this be injected into the error event as the docs say?

`got.stream(stuff)
     .on('error', (err, thisIsAlwaysNull, res) => {
            var body = "";
            res.on('data', (data) => {
              const decoder = new StringDecoder('utf8');
              body = decoder.write(data)
            })
            res.on('end', () => {
              console.log("END", body)
            })`

**Comment by brandon93s** [comment]
See https://github.com/sindresorhus/got/issues/318#issuecomment-403235732 and https://github.com/sindresorhus/got/issues/467#issuecomment-403189894 for additional details and recommendations on working with APIs that do not return JSON.
