### ISSUE TITLE
Stream stucks in download progress

### ISSUE THREAD

**Issue by eronfin** [sindresorhus/got#449]
Hello,

I'm building a simple proxy to stream video from google drive.

Snippet code:
```javascript
var cnt = 1;
got.stream(urlStream, { headers })
    .on('request', (request) => {
        console.log(new Date(), 'Sent HTTP request ' + cnt);
    })
    .on('response', (response) => {
        res.statusCode = response.statusCode;
        Object.keys(response.headers).forEach(key => {
            res.setHeader(key, response.headers[key]);
        });
        console.log('Response ' + cnt++);
    })
    .on('downloadProgress', progress => {
        console.log('Download ' + cnt);
    })
    .on('error', function(e) {
    	console.log(e);
    }).pipe(res);
```

It's working properly on my local (macOS), but when i deploy on Ubuntu Xenial 16.04 64 bit, streaming download progress stuck at 128KB (this size can be changed), and i did not get any error message from app console. After i refreshed browser a several times, this problem is solved and i can watch video normally, download progress does not stuck anymore.

Screenshot:
Stuck at 128KB
![https://imgur.com/a/PZe1m](https://i.imgur.com/XRj2Wap.png)

This is output from app console, callback downloadProgress does not fire anymore
![https://imgur.com/a/tXwen](https://i.imgur.com/A2JEX8i.png)

Sorry for my bad English, hope you can understand my issue and help me to solve it.
Thank you!

**Comment by szmarczak** [comment]
That may be caused by your side (wrong Google Drive handling perhaps?) or you set `content-encoding` header to the `got`'s one. Server encoding and got encoding may be different, so you shouldn't set that on the `response` event. The server will compress data for you (e.g. `express` with compression middleware).

**Comment by szmarczak** [comment]
Try:

```js
        Object.keys(response.headers).forEach(key => {
            if (key !== 'content-encoding') res.setHeader(key, response.headers[key]);
        });
```
