### ISSUE TITLE
Plain object in post body

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#450]
When making a post request I get `TypeError: The `body` option must be a stream.Readable, string, Buffer or plain Object`, but I'm passing in a plain object to body, like `got.post(url, { body: { value: 'arg' } })`. When happens to the plain object in `body`, does it get turned into JSON or into a querystring or something else?

**Comment by lukechilds** [comment]
Can you provide some runnable code reproducing your problem.

**Comment by rightaway** [comment]
```js
await got.post('https://jsonplaceholder.typicode.com/posts', {
    body: {
      title: 'foo',
      body: 'bar',
    },
  })
```

What happens to an object in `body`, does it get JSON stringified or turned into querystring or something?

**Comment by lukechilds** [comment]
>What happens to an object in body, does it get JSON stringified or turned into querystring or something?

Nothing happens to it, that's why you're getting errors.

The supported types for body are listed in the docs: https://github.com/sindresorhus/got#body

**Comment by rightaway** [comment]
Unless I set `form: true` in which case `body` must be an array or plain object right? Shouldn't the above work with the addition to `form: true`?

**Comment by rightaway** [comment]
The content type is set to application/json rather than the correct one as mentioned in the docs.

**Comment by rightaway** [comment]
I see that form/json parameter is required to use a plain object.

**Comment by davalapar** [comment]
Truly confusing as hell, turns out yes `json` and `form` is required if you want to pass a plain object as the body instead of a `form-data` instance.

```
        got('https://www.google.com/recaptcha/api/siteverify', {
          json: true,
          form: true,
          body: {
            secret: 'XYZ',
            response: 'XYZ',
          },
        })
```

**Comment by szmarczak** [comment]
@davalapar https://github.com/sindresorhus/got#json
