### ISSUE TITLE
Pipe got.stream to got.stream: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by egorovli** [sindresorhus/got#458]
Hi.

I was trying to do something like

```js
got.stream('sindresorhus.com').pipe(got.stream.post('sindresorhus.com'))
```

but stuck on the following error:

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type null
    at Function.byteLength (buffer.js:510:11)
    at Timeout.setInterval [as _onTimeout] (/Users/egorovli/Dev/project/node_modules/got/index.js:236:35)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```

Other examples work fine, though:

```js
got.stream('sindresorhus.com').pipe(fs.createWriteStream('index.html'))     // ✔️
fs.createReadStream('index.html').pipe(got.stream.post('sindresorhus.com')) // ✔️
```

Using

```
got 8.2.0
node 9.2.0
```

**Comment by vnenkpet** [comment]
I have the exact same problem. What is strange is that sometimes it actually works OK, sometimes it throws this error.

I'm pretty much only doing
```js
got.stream(downloadUrl).pipe(got.stream.put(uploadUrl))
```

**Comment by alextes** [comment]
Hmm, seems that headers on the request are `null` sometimes when using got's provided writable stream. Not sure if there's a better way to get headers. In any case, it might be smart to use more defensive coding accessing an internal API like this.

I'll have to do some more digging to fully understand the intricacies of reporting upload progress and how `_headers` gets populated during a request.

Interesting to note the POST goes through fine. It's just the progress reporting that appears to break.

Thanks for reporting.

**Comment by arturmuller** [comment]
Hey @alextes, thanks for responding over the weekend! 🙏 

What do you mean by internal APIs? I thought streams were regular, public (and awesome!) part of Got?

Anyhow, do you have any tips how to get this to work? Doesn't have to be elegant.

**Comment by mnmkng** [comment]
Just wanna reference this other issue that seems very related: https://github.com/sindresorhus/got/issues/476

@alextes Yes, `null` `req._headers` are the cause of our issue too. For us, downgrading to `8.2.0` fixes the problem though.

**Comment by SkeLLLa** [comment]
Got the same error.

**Comment by rainder** [comment]
Ok so the problem lays here 
https://github.com/sindresorhus/got/blob/master/index.js#L206

replacing 
`const headersSize = Buffer.byteLength(req._header);` 
with 
`const headersSize = req._header ? Buffer.byteLength(req._header) : 0;`

fixes the problem and doesn't break any existing behaviour.
