### ISSUE TITLE
Parsing non-200 responses

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/got#46]
For now we [don't have](https://github.com/sindresorhus/got/blob/master/index.js#L108-L112) parsing on responses, that are not okay by them selves:

```js
read(res, encoding, function (err, data) {
	err = new GotError(url + ' response code is ' + statusCode + ' (' + status[statusCode] + ')', err);
	err.code = statusCode;
	cb(err, data, response);
});
```

But it is not convinient, when API returns JSON (like [github does](https://developer.github.com/v3/#client-errors)) and we need to parse it by hands.

On other side we have huge amount of services, that proxy'ed and return 50x codes with default nginx error page.

So question is - maybe we should parse JSON on non-200 responses silently? Anyway `got` is already in error state.

**Comment by sindresorhus** [comment]
I think we should if the response content-type is JSON.

**Comment by floatdrop** [comment]
@sindresorhus well, this will introduce content-type matching, which I like to avoid. This still could be done in userland (because data is passed to callback anyway):

```js
got('nginx.com/errored', funciton (err, data, res) {
    if (err) {
        // Explicitly says, that we expect non-json responses
        if (/text-json/.test(res.headers['content-type'])) {
            //...
        }
    }
});
```

And it will be inconsistent with 200 responses (should we then add content-type matching there?).

**Comment by sindresorhus** [comment]
yeah, nvm
