### ISSUE TITLE
Using useElectronNet results in error: HTTP trailers are not supported

### ISSUE THREAD

**Issue by wwwouter** [sindresorhus/got#461]
I'm using this code to upload a file to S3:

```
const response = await got.put(urlString, {
      body: fs.readFileSync(filename),
      useElectronNet: true,
    });
``` 
And this throws an uncaughtException "HTTP trailers are not supported"

This because the response is parsed by mimic-response:  `mimicResponse(res, progressStream);`
and mimic-response uses a `knownProps` array to read values from the `IncomingMessage`.
`knownProps` props contains 'trailers' and 'rawTrailers'. When these are read from the `IncomingMessage`, this throws an error because of this code:
https://github.com/electron/electron/blob/1c0ea0286ed7f8fb9075d1a6c03c758c72e965b8/lib/browser/api/net.js#L59

mimic-response should be made aware of that it is using electron.net or got should do something to prevent the reading of these properties.

If you let me know what you'd prefer, I can make a pull request 😄

**Comment by sindresorhus** [comment]
I think it would be more appropriate to remove the `useElectronNet` option altogether. The Electron implementation is far from compatible and they're not really fixing any of the issues. It sounded promising when I first added it, but it's only been a headache since then.

**Comment by wwwouter** [comment]
That would be too bad, because for us the combination of got and electron works perfectly, except for this error...

Would it be possible to wrap electron support in a provider and keep it out of the got codebase, but still be available for people who want to use it at their own peril?
