### ISSUE TITLE
Download file from one location and upload to another

### ISSUE THREAD

**Issue by mdybich** [sindresorhus/got#468]
Hi.

I'm working on the node application where I need to download file from one location (AWS S3) and upload that file to another place (OneDrive).

OneDrive upload has some limitation:
`If your app splits a file into multiple byte ranges, the size of each byte range MUST be a multiple of 320 KiB (327,680 bytes). Using a fragment size that does not divide evenly by 320 KiB will result in errors committing some files.`

I'm wondering if `got` provides a good way to handle this scenario.

Currently I'm trying something like that (but probably inside `dataHandler` I need to use stream instead of plain put method).
```
function streamData(s3Url, oneDriveUploadUrl) {
  got.stream(s3Url).on("data", data => {

    got.put(oneDriveUploadUrl, {
        headers: {
          "Content-Length": data.length,
          "Content-Range": `bytes 0-${data.length - 1}/${data.length}`
        },
        body: data
  })
}
```

I also tried pipe operator:
```
got.stream(s3DownloadUrl).pipe(got.put.stream(oneDriveUploadUrl
```
but it didn't work.

**Comment by brandon93s** [comment]
@mdybich see the updated `streamData` implementation below. The `Content-Range` header needs to be a sliding window of the format `{starting-byte}-{ending-byte}/{total-bytes}`. Using the `'downloadProgress'` event we can extract out the missing pieces of information required for this request. 

```js
function streamData(s3Url, oneDriveUploadUrl) {
	let total = 0;
	let transferred = 0;
	const stream = got.stream(s3Url);

	// capture progress
	stream.on('downloadProgress', progress => {
		total = progress.total
		transferred = progress.transferred
	})

	// put part to one drive
	stream.on('data', data => {
		got.put(oneDriveUploadUrl, {
			headers: {
				"Content-Length": data.length,
				"Content-Range": `bytes ${transferred}-${data.length - 1}/${total}`
			},
			body: data
		})
	})
}
```

Based on OneDrive API [documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession#example).
