### ISSUE TITLE
HTTPError 401 (Unauthorized)

### ISSUE THREAD

**Issue by BannerBomb** [sindresorhus/got#475]
My script used to work before but all of a sudden it just stopped working and now gives a `HTTPError 401 (Unauthorized)` error how would I fix it? Here is my script.

```js
exports.gistUpload = (text, lang = 'js') => {
	const filename = 'cripsbot_upload.' + lang;
	return got.post('https://api.github.com/gists', {
			body: {
				files: {
					[filename]: {
						content: text
					}
				}
			},
			json: true
		})
		.then(res => {
			if (res && res.body && res.body.html_url) {
				return {
					success: true,
					url: res.body.html_url,
					rawUrl: res.body.files[filename].raw_url
				};
			} else {
				return {
					success: false
				};
			}
		});
};
```
It is used to upload text to github.com anonymously, it used to work but then stopped and I have not changed anything in it before nor after it started erroring. It first gave an HTTPError 422 (Unprocessable Entity) but now it gives `HTTPError 401 (Unauthorized)` is there anything wrong with my script? and if there is what do I need to change?

**Comment by sindresorhus** [comment]
Not sure how this worked before since you're not authenticating, at least not in the code you've posted here. https://developer.github.com/v3/gists/#authentication

**Comment by sindresorhus** [comment]
Cool. Also check out https://github.com/sindresorhus/gh-got which makes it easier to use the Github API.
