### ISSUE TITLE
ignore ssl verification

### ISSUE THREAD

**Issue by legrandjeremy** [sindresorhus/got#477]
Hello,

I'm using got since several months and I love it !
I'm facing an issue with an https request with an invalid SSL certificate.
If I use Postman or Curl I can ignore the SSL check, but I don't find a way to ignore with got library.

on chrome I recevied this : ERR_CERT_AUTHORITY_INVALID

Any ideas ?

Thanks in advance !

**Comment by sindresorhus** [comment]
See: https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Got passes options to `https.request`.

**Comment by sindresorhus** [comment]
I don't know, sorry. Whatever is correct for Node.js, is correct for Got.

**Comment by pyrho** [comment]
For other coming here in search of an answer: `got('https://local.dev', { rejectUnauthorized: false });`

ps:
`got` ships with Typescript definition files which are a nice way to explore modules' APIs.
In this case `got()` takes a second argument of type `OptionsOfDefaultResponseBody`, and if you drill down this type you will eventually `rejectUnauthorized` under node's `https.RequestOptions` type.

**Comment by jgehrcke** [comment]
> For others coming here in search of an answer: got('https://local.dev', { rejectUnauthorized: false });

wow, this should be top-level documented.

**Comment by PierBover** [comment]
Now it's actually:

```
got('https://local.dev', {https: { rejectUnauthorized: false }});
```

**Comment by sarus** [comment]
Using the latest got `^11.7.0` I had to do:

```
got('https://local.dev', { rejectUnauthorized: false });
```
Nesting `rejectUnauthorized` in the `https` property did not work for.
