### ISSUE TITLE
Allow to cache authenticated responses

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/got#480]
I'm trying to use `got` to cache my authenticated github requests.

Github API returns `Cache-Control: private` header for authenticated requests, so `http-cache-semantics` without `shared: false` option determines the response as not cacheable.

I'd like to find a way to pass `shared: false` configuration all the way `got > cacheable-request > http-cache-semantics`. Any ideas how?

ps: I've also opened issue in `cacheable-request` repo: https://github.com/lukechilds/cacheable-request/issues/32

UPD: By reading source code in all 3 libraries I figured that I can just pass `shared: false` in got options (despite typescript forbidding it) and it goes all the way to `http-cache-semantics`. But unfortunately it doesn't solve my problem of authenticated github requests being not cached. Digging further...

**Comment by brandon93s** [comment]
@kirillgroshkov does this still require assistance? It looks like a work-around was found: https://github.com/kornelski/http-cache-semantics/issues/9

**Comment by lukechilds** [comment]
Let me know if there's anything I can do in `cacheable-request`.

**Comment by kirillgroshkov** [comment]
Yes, workaround still works for me, thanks!
