### ISSUE TITLE
Add JSON reviver

### ISSUE THREAD

**Issue by piranna** [sindresorhus/got#482]
https://github.com/sindresorhus/got/blob/81f2537e6950643e986c09c182dbf29d5fcee8e2/index.js#L363

Add an option to pass a reviver function to `JSON.parse()` when using the `json` mode. Maybe it would be used the `json` option itself, setting it to the reviver function instead of just using `true`.

**Comment by sindresorhus** [comment]
We've discussed this previously, but if you need that you can just handle the JSON manually. It's not a common case and it's not worth the overhead of adding a new option. Thanks for the suggestion though.

**Comment by piranna** [comment]
I have searched for it and didn't find anything, hope this issue helps :-) It's not needed a new option if `json` one is reused, but I understand it's a not so common case, just only a desirabled one. I'm already processing the output myself, it's just a matter I would have liked that `got` itself does it for code clarity.
