### ISSUE TITLE
Remove rejectUnauthorized references

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/got#483]
I discovered this option reading [is-reachable](https://github.com/sindresorhus/is-reachable/blob/master/index.js#L16) code, looks like it was added in the past but it's not present in the current codebase.

Also we can find tests reference it:

https://github.com/sindresorhus/got/search?utf8=%E2%9C%93&q=rejectUnauthorized&type=

**Comment by sindresorhus** [comment]
See: https://nodejs.org/api/https.html#https_https_request_options_callback

I've fixed the docs.
