### ISSUE TITLE
Opting out of default user-agent

### ISSUE THREAD

**Issue by iflp** [sindresorhus/got#485]
Hi,

The `user-agent` header is optional in RFC 2616, it shouldn't be enforced imo. Currently there is no way to send a request without the `user-agent` header.

Happy to submit a PR to make this happen.

**Comment by sindresorhus** [comment]
What's your use-case? It optional, true, but it's a good practice to set it.

**Comment by ragingnerd** [comment]
Thanks for the fast reply.

I need to explicitly send the request without setting a user-agent. It's weird I know, but that's the requirement. I'm aware of the best practices and whilst I appreciate the intention behind making it compulsory, I think we should follow the RFC spec and let the user decide what to do.

Maybe allowing users to opt-out is a good compromise? E.G. Explicitly setting  `user-agent: null` will remove it, if nothing is specified add the default user-agent.

**Comment by sindresorhus** [comment]
> Maybe allowing users to opt-out is a good compromise? E.G. Explicitly setting user-agent: null will remove it, if nothing is specified add the default user-agent.

That's how it currently works: https://github.com/sindresorhus/got/blob/a03d21e697311825c275d086e9335947a5538059/test/headers.js#L128-L136

We should document that better.

**Comment by kaatt** [comment]
Explicitly setting user-agent: null doesn't remove the header. Maybe it works for unicorns but not user-agent.
