### ISSUE TITLE
setImmediate package needs to be installed, to use got in a browser environment

### ISSUE THREAD

**Issue by unquietwiki** [sindresorhus/got#486]
https://github.com/yuzujs/setImmediate needs to be installed, if using got in a Browserify deployment; otherwise, got won't be able to do a setImmediate call.

**Comment by sindresorhus** [comment]
That's an issue with Browserify. It's up to Browserify to correctly polyfill Node.js APIs.

**Comment by unquietwiki** [comment]
@sindresorhus Acknowledged; just wanted to bring it to your attention. Thanks!
