### ISSUE TITLE
Cache doesn't work properly when using `query` option

### ISSUE THREAD

**Issue by bdougherty** [sindresorhus/got#487]
Noticed that two requests that share the same base url but have a different query string were coming from the cache of the first request when using the `query` option. I was using a `Map` for the cache and the only key in there did not include the query string, so not sure if this is an issue here or with [cacheable-request](https://github.com/lukechilds/cacheable-request).

Notice there is only one key and the assertion fails in this example:

```js
const got = require('got');

(async () => {
	const cache = new Map();

	const { body: body1 } = await got('https://nominatim.openstreetmap.org/search', {
		cache,
		query: {
			format: 'jsonv2',
			addressdetails: 1,
			q: 'philadelphia, pa'
		}
	});

	const { body: body2 } = await got('https://nominatim.openstreetmap.org/search', {
		cache,
		query: {
			format: 'jsonv2',
			addressdetails: 1,
			q: 'atlantic city, nj'
		}
	});

	console.assert(body1 !== body2);
	// Assertion failed
	console.log([...cache.keys()]);
	// [ 'cacheable-request:GET:https://nominatim.openstreetmap.org/search' ]
})();
```

But everything works fine when using a `URL`:

```js
const { URL } = require('url');
const got = require('got');

(async () => {
	const cache = new Map();

	const url1 = new URL('https://nominatim.openstreetmap.org/search');
	url1.searchParams.set('format', 'jsonv2');
	url1.searchParams.set('addressdetails', 1);
	url1.searchParams.set('q', 'philadelphia, pa');

	const { body: body1 } = await got(url1, {
		cache
	});

	const url2 = new URL('https://nominatim.openstreetmap.org/search');
	url2.searchParams.set('format', 'jsonv2');
	url2.searchParams.set('addressdetails', 1);
	url2.searchParams.set('q', 'atlantic city, nj');

	const { body: body2 } = await got(url2, {
		cache
	});

	console.assert(body1 !== body2);
	console.log([...cache.keys()]);
	// [ 'cacheable-request:GET:https://nominatim.openstreetmap.org/search?addressdetails=1&format=jsonv2&q=philadelphia, pa',
	// 'cacheable-request:GET:https://nominatim.openstreetmap.org/search?addressdetails=1&format=jsonv2&q=atlantic city, nj' ]
})();
```

**Comment by lukechilds** [comment]
Thanks for reporting with details. Definitely looks like an issue with `cacheable-request`. Would you mind reporting this over there?

**Comment by brandon93s** [comment]
@sindresorhus //label=external

**Comment by lukechilds** [comment]
@bdougherty sorry, I've been really busy on other projects recently. I'll have some free time coming up soon, if you can reproduce this error with `cacheable-request` and create an issue over there with an example I will get this resolved.

**Comment by jstewmon** [comment]
This issue was a bit tricky - it came down to got's normalized arguments not accounting for the fact that cacheable-request uses url.format to create the cache key. url.format doesn't use the same option parameters as `http.request`, so the options have to be explicitly aligned for everything to work correctly. I suppose this type of issue can be more easily mitigated if everyone standardizes on the WHATWG URL API.
