### ISSUE TITLE
HTTP Status code associated with each redirect

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/got#488]
Currently `redirectUrls` expose a collection of each redirect until reach the final URL:

```
redirectUrls:
   [ 'https://httpbin.org/relative-redirect/5',
     'https://httpbin.org/relative-redirect/4',
     'https://httpbin.org/relative-redirect/3',
     'https://httpbin.org/relative-redirect/2',
     'https://httpbin.org/relative-redirect/1',
     'https://httpbin.org/get' ]
```

I want to ask if could support a structure similar to that to know the HTTP status code associated with each redirect.

```
redirectUrls:
   [ [301, 'https://httpbin.org/relative-redirect/5'],
     [301, 'https://httpbin.org/relative-redirect/4'],
     [301, 'https://httpbin.org/relative-redirect/3'],
     [301, 'https://httpbin.org/relative-redirect/2'],
     [301, 'https://httpbin.org/relative-redirect/1'],
     [302, 'https://httpbin.org/get' ]]
```

**Comment by szmarczak** [comment]
You can use this API:

> [**.on('redirect', response, nextOptions)**](https://github.com/sindresorhus/got#onrequest-request)
redirect event to get the response object of a redirect. The second argument is options for the next request to the redirect location.

Then save HTTP status code for each redirect. If you want more, it could store all the responses, but there's no need. It'd be too bloated.

**Comment by brandon93s** [comment]
Building upon @szmarczak's suggestion, the following code snippet produces the output you desire:

```js
const redirects = [];
const request = got.get('https://httpbin.org/relative-redirect/5');

request.on('redirect', info => {
	redirects.push([info.statusCode, info.url]);
});

const response = await request;
```

**Comment by Kikobeats** [comment]
Thanks! Works like a charm.

**Comment by scheung38** [comment]
How to add Bearer token in this call? as I am using it my my redirect but getting:


 headers:
   { server: 'nginx/1.12.1',
     date: 'Thu, 31 Jan 2019 15:41:50 GMT',
     'content-type': 'application/json',
     'content-length': '15',
     connection: 'close' },
  body: 'No access token' }
