### ISSUE TITLE
got@8.3.1 is not setting Transfer-Encoding: chunked header

### ISSUE THREAD

**Issue by VasiliiKuznecov** [sindresorhus/got#489]
I have following code in my app:

```javascript
const { Readable } = require('stream');
const FormData = require('form-data');
const got = require('got');

const form = new FormData();
const stream = new Readable();

const headers = { Authorization: `OAuth <token>` };

stream.push('{"a":1}');
stream.push(null);

form.append('field1', 'field1');
form.append('field2', stream);

got.post(url, {
    headers,
    body: form
})
```

And with got@8.3.1 I'm getting 502 error from server.
While using got@8.3.0 everything works fine.

I found out that got@8.3.0 adds header: Transfer-Encoding: chunked, while got@8.3.1 doesn't.

**Comment by zuban** [comment]
I have got the same error, 
Here is the comparison:
```
v8.3.1:

POST /api/v1/artbuyer/briefings HTTP/1.1
user-agent: got/8.3.1 (https://github.com/sindresorhus/got)
content-type: multipart/form-data; boundary=--------------------------558951591065782284282183
x-auth-token: ...
accept-encoding: gzip, deflate
content-length: 433
Host: play:9000
Connection: close
v.8.3.0: 

POST /api/v1/artbuyer/briefings HTTP/1.1
user-agent: got/8.3.0 (https://github.com/sindresorhus/got)
content-type: multipart/form-data; boundary=--------------------------315337818893402991498635
x-auth-token: ...
accept-encoding: gzip,deflate
Host: play:9000
Connection: close
Content-Length: 0
```

**Comment by sindresorhus** [comment]
@VasiliiKuznecov Got never added a `transfer-encoding` header AFAIK. What did change in 8.3.1 is that Got now adds a `content-length` header when you use `form-data` (https://github.com/sindresorhus/got/commit/de9514d897ca58ec70bbf82acc52e43b44cca870).

Would you be able to submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests)?

**Comment by sindresorhus** [comment]
@zuban The only difference for you is that `content-length` is now correct, which is how it should be. The behavior in Got 8.3.0 was incorrect, see https://github.com/sindresorhus/got/pull/466.

**Comment by brandon93s** [comment]
I've setup a few separate test cases and haven't had any luck reproducing this. `Transfer-Encoding: chunked` is only supported by HTTP/1.1 (not 1.0, not /2) and implementation support is spotty. I can't see where got was ever sending this header, though. 

Typically, support for this header is going to live in a reverse proxy or firewall. Without knowing more about the server that these requests were made against, I'm afraid there isn't much that can be done here.
