### ISSUE TITLE
Reducing dependencies

### ISSUE THREAD

**Issue by Nepoxx** [sindresorhus/got#491]
I feel like dependencies which consist entirely of code like this:

```js
'use strict';
module.exports = object => {
	const ret = {};

	for (const [key, value] of Object.entries(object)) {
		ret[key.toLowerCase()] = value;
	}

	return ret;
};
```

should be eliminated. (from [here](https://github.com/sindresorhus/lowercase-keys/blob/master/index.js))

Got is the second HTTP request library with the most dependencies as seen here: https://npmcompare.com/compare/axios,got,request,reqwest,superagent

Reducing dependencies would therefore increase score on that website and therefore visibility.

Here's an interesting article on this "problem" https://medium.com/@caspervonb/the-internet-is-at-the-mercy-of-a-handful-of-people-73fac4bc5068

**Comment by sindresorhus** [comment]
I'm already working on reducing dependencies in master, but it's a non-goal to remove dependencies for the sake of it.

**Comment by sindresorhus** [comment]
> Reducing dependencies would therefore increase score on that website and therefore visibility.

An arbitrary score on a random website is not something I care about.

**Comment by Nepoxx** [comment]
> but it's a non-goal to remove dependencies for the sake of it.

That's why I said "problem" (with quotes). The thing is that it's a security concern (as mentioned in the linked article).

> An arbitrary score on a random website is not something I care about.

No need to be like this, I was simply making a suggestion to improve the code base, sorry it offended you.
