### ISSUE TITLE
Pipe through closed stream

### ISSUE THREAD

**Issue by StarpTech** [sindresorhus/got#545]
Hi,
in Got 8 I could pipe through a closed stream. In Got 9 I get this error:

```js
Failed to pipe. The response has been emitted already.
```
to fix this I have to remove the `await PEvent(response, 'response')` event of the first stream:

Reproducible:
```js
    const response = await this.httpClient.get(url, {
      stream: true
    })
   await PEvent(response, 'response')
   const stream = stream.pipe(response2)
   await PEvent(stream, 'response')
```
Solution:
```js
    const response = await this.httpClient.get(sub.topic, {
      stream: true
    })
   // await PEvent(response, 'response')
   const stream = stream.pipe(response2)
   await PEvent(stream, 'response')
```

Does the new behaviour fix a bug or is it best-practice? At least we should add it to the release notes as breaking-change.

**Comment by szmarczak** [comment]
> Does the new behaviour fix a bug or is it best-practice?

It's best practice to avoid bugs. See #223.

We could emit the error after the [stream.Readable's `end` event](https://nodejs.org/api/stream.html#stream_event_end), but there's a chance you'll get only a piece of the response (e.g. flowing mode is on), and we don't want that when we are piping it to a HTTP response.
