### ISSUE TITLE
Add readme FAQ on how Got is better than `node-fetch` and `request`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#548]
https://twitter.com/sindresorhus/status/1027276595822653440

**Comment by szmarczak** [comment]
*please verify before publish*

|                       |  `got`  | `request` | `node-fetch` | `axios` |
|-----------------------|:-------:|:---------:|:------------:|:-------:|
| HTTP support          |    ✔    |     ✔    |       ✔      |    ✔   |
| HTTPS support         |    ✔    |     ✔    |       ✔      |    ✔   |
| HTTP/2 support        |    ✖    |     ✖    |       ✖      |    ✖   |
| Promise API           |    ✔    |     ✔    |       ✔      |    ✔   |
| Stream API            |    ✔    |     ✔    |       ✖      |    ✖   |
| Request cancelation   |    ✔    |     ✖    |       ✖      |    ✔   |
| RFC compliant caching |    ✔    |     ✖    |       ✖      |    ✖   |
| Follows redirects     |    ✔    |     ✔    |       ✔      |    ✔   |
| Retries on failure    |    ✔    |     ✖    |       ✖      |    ✖   |
| Progress events       |    ✔    |     ✖    |       ✖      |    ✔   |
| Handles gzip/deflate  |    ✔    |     ✔    |       ✔      |    ✔   |
| Advanced timeouts     |    ✔    |     ✖    |       ✖      |    ✖   |
| Errors with metadata  |    ✔    |     ✖    |       ✖      |    ✔   |
| JSON mode             |    ✔    |     ✖    |       ✖      |    ✔   |
| Custom defaults       |    ✔    |     ✔    |       ✖      |    ✔   |
| Composable            |    ✔    |     ✖    |       ✖      |    ✖   |
| Hooks                 |    ✔    |     ✖    |       ✖      |    ✔   |
| Issues open           | ![][gio] | ![][rio] |   ![][nio]   | ![][aio] |
| Issues closed         | ![][gic] | ![][ric] |   ![][nic]   | ![][aic] |
| Downloads             |  ![][gd] |  ![][rd] |    ![][nd]   |  ![][ad] |
| Coverage              |  ![][gc] |  ![][rc] |    ![][nc]   |  ![][ac] |
| Build                 |  ![][gb] |  ![][rb] |    ![][nb]   |  ![][ab] |
| Dependents            | ![][gdp] | ![][rdp] |   ![][ndp]   | ![][adp] |
| Install size          | ![][gis] | ![][ris] |   ![][nis]   | ![][ais] |


[gio]: https://img.shields.io/github/issues/sindresorhus/got.svg
[rio]: https://img.shields.io/github/issues/request/request.svg
[nio]: https://img.shields.io/github/issues/bitinn/node-fetch.svg
[aio]: https://img.shields.io/github/issues/axios/axios.svg


[gic]: https://img.shields.io/github/issues-closed/sindresorhus/got.svg
[ric]: https://img.shields.io/github/issues-closed/request/request.svg
[nic]: https://img.shields.io/github/issues-closed/bitinn/node-fetch.svg
[aic]: https://img.shields.io/github/issues-closed/axios/axios.svg


[gd]: https://img.shields.io/npm/dm/got.svg
[rd]: https://img.shields.io/npm/dm/request.svg
[nd]: https://img.shields.io/npm/dm/node-fetch.svg
[ad]: https://img.shields.io/npm/dm/axios.svg


[gc]: https://coveralls.io/repos/github/sindresorhus/got/badge.svg?branch=master
[rc]: https://coveralls.io/repos/github/request/request/badge.svg?branch=master
[nc]: https://coveralls.io/repos/github/bitinn/node-fetch/badge.svg?branch=master
[ac]: https://coveralls.io/repos/github/mzabriskie/axios/badge.svg?branch=master


[gb]: https://travis-ci.org/sindresorhus/got.svg?branch=master
[rb]: https://travis-ci.org/request/request.svg?branch=master
[nb]: https://travis-ci.org/bitinn/node-fetch.svg?branch=master
[ab]: https://travis-ci.org/axios/axios.svg?branch=master


[gdp]: https://badgen.net/npm/dependents/got
[rdp]: https://badgen.net/npm/dependents/request
[ndp]: https://badgen.net/npm/dependents/node-fetch
[adp]: https://badgen.net/npm/dependents/axios


[gis]: https://packagephobia.now.sh/badge?p=got
[ris]: https://packagephobia.now.sh/badge?p=request
[nis]: https://packagephobia.now.sh/badge?p=node-fetch
[ais]: https://packagephobia.now.sh/badge?p=axios
