### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by wescoder** [sindresorhus/got#551]
I use GOT on some of my node projects and I really like it.
I would like to have it working on some of my isomorphic ones like one that uses Next.js.
Would it be possible to make it work?
What would be the challenges and difficulties of giving browser compatibility?

**Comment by sindresorhus** [comment]
That is a non-goal for this project, but it should in theory still work in the browser if you run it through Browserify or Webpack (as they bundle shims for Node.js APIs). I remember Got v7 working in the browser after being run through Browserify.

**Comment by sindresorhus** [comment]
Relevant issue: https://github.com/sindresorhus/got/issues/288#issuecomment-302970189

**Comment by wescoder** [comment]
I'll give it a try again, but I remember getting errors about fs not being accessible.
I'll report here with my findings.

**Comment by styfle** [comment]
Should "browser support" be added to the Comparison table?
https://github.com/sindresorhus/got#comparison

**Comment by wescoder** [comment]
I think it should.
I will at least clarify this subject.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/ky
