### ISSUE TITLE
Migration guides

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#555]
Would be useful to have some examples of how to move from `request`, `axios`, `node-fetch` to `got`. We could first show a real world `axios` usage example and then how it would look like with `got`.

**Comment by pgilad** [comment]
Better yet, a codemod ;)

**Comment by sindresorhus** [comment]
@pgilad That would be really cool indeed, but could probably only handle the simplest of cases.

**Comment by DRSDavidSoft** [comment]
@sindresorhus It would be also useful to write documentation for beginners who have started with **got** instead of the other libraries.

Currently, got documentation rely on external libraries knowledge too much IMHO.

**Comment by sindresorhus** [comment]
@DRSDavidSoft Yeah, I agree, would be nice with a comprehensive beginner guide. I would guess most beginners don't just need an intro to Got, but also Node.js and HTTP in general.

**Comment by DRSDavidSoft** [comment]
@sindresorhus 👍 True, but you don't need to worry about guides for Node.js, Promises and HTTP mechanics -- since they're mostly covered pretty well outside the got docs.

got itself, however, could benefit from better documentation for beginners who choose to start with it.

**Comment by sindresorhus** [comment]
@DRSDavidSoft Anything specific?
