### ISSUE TITLE
Add ability to time requests

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#557]
Add ability to capture timings of every HTTP request state, e.g.

> - `time` - if `true`, the request-response cycle (including all redirects) is timed at millisecond resolution. When set, the following properties are added to the response object:
>   - `elapsedTime` Duration of the entire request/response in milliseconds (*deprecated*).
>   - `responseStartTime` Timestamp when the response began (in Unix Epoch milliseconds) (*deprecated*).
>   - `timingStart` Timestamp of the start of the request (in Unix Epoch milliseconds).
>   - `timings` Contains event timestamps in millisecond resolution relative to `timingStart`. If there were redirects, the properties reflect the timings of the final request in the redirect chain:
>     - `socket` Relative timestamp when the [`http`](https://nodejs.org/api/http.html#http_event_socket) module's `socket` event fires. This happens when the socket is assigned to the request.
>     - `lookup` Relative timestamp when the [`net`](https://nodejs.org/api/net.html#net_event_lookup) module's `lookup` event fires. This happens when the DNS has been resolved.
>     - `connect`: Relative timestamp when the [`net`](https://nodejs.org/api/net.html#net_event_connect) module's `connect` event fires. This happens when the server acknowledges the TCP connection.
>     - `response`: Relative timestamp when the [`http`](https://nodejs.org/api/http.html#http_event_response) module's `response` event fires. This happens when the first bytes are received from the server.
>     - `end`: Relative timestamp when the last bytes of the response are received.
>   - `timingPhases` Contains the durations of each request phase. If there were redirects, the properties reflect the timings of the final request in the redirect chain:
>     - `wait`: Duration of socket initialization (`timings.socket`)
>     - `dns`: Duration of DNS lookup (`timings.lookup` - `timings.socket`)
>     - `tcp`: Duration of TCP connection (`timings.connect` - `timings.socket`)
>     - `firstByte`: Duration of HTTP server response (`timings.response` - `timings.connect`)
>     - `download`: Duration of HTTP download (`timings.end` - `timings.response`)
>     - `total`: Duration entire HTTP round-trip (`timings.end`)

– https://github.com/request/request

**Comment by szmarczak** [comment]
We could use our `timed-out.js` module for that. It already does measurements. Small changes and it should be done.

**Comment by sindresorhus** [comment]
Would be useful. I think @jstewmon wanted something like this too.

**Comment by jstewmon** [comment]
Yesterday, I sketched out something to enable this. I should have a straw man ready to post tonight or tomorrow.

**Comment by szmarczak** [comment]
https://github.com/szmarczak/http-timer Tomorrow I'll send a PR.
