### ISSUE TITLE
Add TypeScript and Flow type definitions

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#558]
Having Flowtype static typings would help to catch configuration errors.

Happy to contribute the typings.

Of note, I would recommend using Flowtype to validate the project itself. It would add an extra layer of bug-proofness at a cost of additional build step.

If you need an example of how integration would look, my GitHub profile includes a number of projects using Flowtype, e.g. https://github.com/gajus/roarr.

**Comment by gajus** [comment]
> Can you elaborate on the configuration errors? I don't know what these mean, but I'm happy to know :)

Referring to API contract validation, e.g.

```js
got('http://gajus.com/', {
  followRedirects: true,
  payload: Buffer.from('test')
});

```

The above contains two errors that are hard to notice by the user and will not be caught by the program until runtime validation.

If there were static typings, e.g.

```js
type HttpClientConfiguration = {|
  +body?: string,
  +followRedirect?: boolean
|};

type HttpClient = (url: string, configuration: HttpClientConfiguration) => Promise<any>;

const got: HttpClient = async (url, configuration) => {}

```

Then the above code example would throw the following errors at a compilation step:

```
10: got('http://gajus.com/', {                             ^ Cannot call `got` with object literal bound to `configuration` because property `followRedirects` is missing in `HttpClientConfiguration` [1] but exists in object literal [2].
References:
6: type HttpClient = (url: string, configuration: HttpClientConfiguration) => Promise<any>;
                                                  ^ [1]
10: got('http://gajus.com/', {                             ^ [2]
10: got('http://gajus.com/', {                             ^ Cannot call `got` with object literal bound to `configuration` because property `payload` is missing in `HttpClientConfiguration` [1] but exists in object literal [2].
References:
6: type HttpClient = (url: string, configuration: HttpClientConfiguration) => Promise<any>;
                                                  ^ [1]
10: got('http://gajus.com/', {                             ^ [2]

```

https://flow.org/try/#0C4TwDgpgBAEsxgMIBsCWEB2xEHsMDNUBzAVwCcBDYVPKAXigG8AfAKCigGoAjHAExAB+AFxQAzsDKoMRADTsu+HMmQ4A7gCUIfVGQgBjYCKi9lEChlbMAvgG5WrUJFjwkaTMHpQAFOWSiJKRlZKH08QlJKajxROAQUdCxcAmJyKhoMAEp6AD4oAAUyHABbVDEIAB4LEBz7VjCMCSgiHGBY1wSPLwoxEAx9Hz8Qhoi06KzcpmsHFuBvAHIAC1dhAHpVogoAKxIxADow4tX5kMYFJRV1LR09QzFRSRIIeQ4wChBVCj5ReeAICXmrGsmVsQA

I am maintaining projects with dozens of freelancers working and literally thousands of individual scripts. It would be near impossible to code at this scale without static type checking. We can definitely wrap got internally with our own types (we are going to do that anyway to restrict some features), but a type-safe project would definitely be a huge incentive for me to choose got over the other available alternatives.

**Comment by sindresorhus** [comment]
Yeah, happy to have support for Flow if you're willing to do the work to add it.

**Comment by szmarczak** [comment]
> It would be near impossible to code at this scale without static type checking.

There are many projects that don't use flow. But yeah, strict typing would be nice. :+1:

**Comment by sindresorhus** [comment]
I have a style guide for TypeScript now, which should also mostly apply to Flow: https://github.com/sindresorhus/typescript-definition-style-guide

**Comment by swftvsn** [comment]
Does that mean that you're willing to move the typescript definitions file from @types/got to this project and start maintaining it here? It would be a big plus for me. I'm willing to invest some time to make that happen @sindresorhus, should I create an issue for that and start working?

**Comment by swftvsn** [comment]
Hmm, I looked at the code and couldn't make out what it does. We've since started to use https://github.com/laurisvan/request-promise-lite that suits better our needs, and so I won't be doing the types.

**Comment by sindresorhus** [comment]
Just to clarify, by "have support for Flow", I mean adding a Flow definition file, not to rewrite Got in Flow.

**Comment by gajus** [comment]
> Just to clarify, by "have support for Flow", I mean adding a Flow definition file, not to rewrite Got in Flow.

Yeah, I realised that. Thats why I quietly backed away.

I personally think that this is a fragile approach: you end up replicating changes in 2 different places (with TS support: 3 different places). However, thats better than nothing from the consumer's perspective.

**Comment by sindresorhus** [comment]
Yes, but if I were to rewrite Got, I would do it in TypeScript, not Flow, as that's what I'm familiar with and prefer.

**Comment by sindresorhus** [comment]
Closing in favor of #700.
