### ISSUE TITLE
Add native support for cookie persistence handling using an API compatible with tough-cookie

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#566]
Adding native cookie support has been discussed in multiple issues, e.g.

* https://github.com/sindresorhus/got/issues/107

However, none of the issues cover how one is supposed to implement cookie persistence between redirects.

It is simple to implement something like [tough-cookie](https://www.npmjs.com/package/tough-cookie) for a single request with no redirects. However, I haven't figured out how to keep track of cookies when a cookie is set on a redirect and the final destination depends on the cookie being present. It probably requires handling "response" and "redirect" events and modifying the request. Point is, as a consumer of an HTTP client, I want an in-built cookie support or at least an API and a recipe that allows to quickly add cookie support. Otherwise, the learning curve for starting to use Got becomes unreasonably high compared to the available alternatives, all of which (request, axios, superagent) support cookie persistence out of the box.

**Comment by gajus** [comment]
Looks like "set-cookie" can be an array.

```js
if (response.headers['set-cookie']) {
  const headers = Array.isArray(response.headers['set-cookie']) ? response.headers['set-cookie'] : [response.headers['set-cookie']];

  for (const header of headers) {
    jar.setCookieSync(header, response.url);
  }
}

```

**Comment by sindresorhus** [comment]
Makes sense. I don't think we want to directly depend on `touch-cookie` as it's pretty big, but we could add a `cookie` option that expects a `new tough.CookieJar()` instance? Or just `{cookie: require('touch-cookie')}`, not sure which is better.

**Comment by szmarczak** [comment]
I'd prefer `cookieStorage` instead of `cookie`. `cookie` is confusing with `headers.cookies`.
