### ISSUE TITLE
Set max cache time

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/got#570]
Is there any way to set a maximum expires time for caching? I've found that the npmjs registry returns the following for scoped packages:

```
cache-control: public, max-age=14400
```

This 4 hour cache time seems inappropriate, especially compared to the 300s max-age for non-scoped packages, and causes problems for my service. Is there any way to set a maximum cache time for the purposes of requerying?

**Comment by brandon93s** [comment]
@rarkins - `cacheable-request` uses https://github.com/lukechilds/keyv as the underlying cache, which supports a "global" TTL. Setting the TTL to your desired max cache time should accomplish what you're after. 

See the docs for passing in a cache store here: https://github.com/sindresorhus/got/blob/master/readme.md#cache-adapters

**Comment by rarkins** [comment]
@brandon93s thanks for the suggestion. I think this could be a workaround, but not a perfect solution. The imperfect part is that stale cache entries will be purged by `keyv` and not available for revalidation. This would significantly increase the volume of data transferred because the majority of lookups are (a) stale, but (b) revalidated.

**Comment by sindresorhus** [comment]
@rarkins What kind of solution are you looking for then?

**Comment by rarkins** [comment]
@sindresorhus from a user perspective it would be an option named like `maxCacheAge` which serves to set an upper limit on how long the result is used directly from cache before revalidating. A value of `0` would mean to always invalidate.

If only the `max-age` value in `Cache-Control` could be considered (e.g. not also the `Expires` value if present), then it could be done in at least two different ways:

1. `got` looks at `response.headers['Cache-Control`] and modifies the `max-age` value if necessary before passing to `cacheable-request`, or

2. No logic change to `got` and the option is passed transparently to `cacheable-request` and similar logic is performed there instead

**Comment by rarkins** [comment]
I looked into the details of `cacheable-request` and I think this is already possible, although I'd need to write a test to be sure.

The relevant code is: https://github.com/kornelski/http-cache-semantics/blob/d0bf1baf301dc6044a839ac309685e9385fb6c3b/index.js#L148-L150

```
        if (requestCC['max-age'] && this.age() > requestCC['max-age']) {
            return false;
        }
```

i.e. the response will be stored in cache and "not stale" for as long as the server says, however there's a function `satisfiesWithoutRevalidation()` that will return false if the age of that cached response exceeds the `max-age` in the subsequent request's `Cache-Control` header.

**Comment by szmarczak** [comment]
Fix: https://github.com/lukechilds/cacheable-request/pull/58
