### ISSUE TITLE
Document the `response.retryCount` property

### ISSUE THREAD

**Issue by Rowno** [sindresorhus/got#574]
Looks like the [`response` documentation](https://github.com/sindresorhus/got#goturl-options) became outdated with the 9.0 release because the new [`retryCount` property](https://github.com/sindresorhus/got/blob/8f30f1fdefaa96ad55758a352730d00697862952/source/request-as-event-emitter.js#L51) isn't documented.

**Comment by szmarczak** [comment]
I feel like there should be another section for the `response` object. What do you think?

**Comment by Rowno** [comment]
Probably a good idea, I thought the `response` object wasn't documented at all until I stumbled upon that sentence. 😅
