### ISSUE TITLE
Use `http.request(url, options, callback)` when targeting Node 10.9.0

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#580]
1. [ ] Use `http.request(url, options, callback)`
2. [x] Use [`Stream.pipeline(from, ..., to, callback)`](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback)
3. [ ] (Maybe) deprecate legacy `Url` usage

**Comment by szmarczak** [comment]
We're targeting Node 10 now, so maybe let's deprecate legacy `Url` usage?

**Comment by sindresorhus** [comment]
You mean deprecating specifying an object as the first argument, right? If yes, then I agree.

However, should we still continue supporting specifying URL components as options as the second argument?

**Comment by szmarczak** [comment]
Yup. And remove it in our code too.

**Comment by sindresorhus** [comment]
Let’s do it.
