### ISSUE TITLE
example given in readme not working

### ISSUE THREAD

**Issue by walkwel** [sindresorhus/got#586]
![screen shot 2018-08-24 at 11 56 23 am](https://user-images.githubusercontent.com/23698860/44568749-ae3d0380-a795-11e8-8a14-cbbffd5d17b3.png)

Just installed the package and used the given example but gives an error.

Here is the code.

`async () => {
      const response = await got('sindresorhus.com')
      console.log('response body', response);
    }`

**Comment by sindresorhus** [comment]
It requires support for async functions, which means Node.js 8 or higher.

**Comment by walkwel** [comment]
My node version is 8.11.1

![screen shot 2018-08-24 at 4 11 58 pm](https://user-images.githubusercontent.com/23698860/44580681-7abfa080-a7b8-11e8-8689-8c339f8490b0.png)
