### ISSUE TITLE
Is the agents example correct?

### ISSUE THREAD

**Issue by ash0080** [sindresorhus/got#587]
the agentkeepalive is almost a server side agent, you can even not assign a host for it, could it be used as a proxy or proxies?

**Comment by sindresorhus** [comment]
No, the `agentkeepalive` example doesn't have anything to do with proxies. I've fixed this now.

**Comment by ash0080** [comment]
Besides, node-tunnel has a bug, 
typically say, the tunnel.httpsOverHttp still use port 80 for a mistake,
so, it's not suitable for got, at least not for current version.
