### ISSUE TITLE
Error url property is wrong when baseUrl has pathname

### ISSUE THREAD

**Issue by Moeriki** [sindresorhus/got#601]
### Problem

When a `baseUrl` contains a pathname the error url property is wrong.

### Example

```js
const client = got.extend({ baseUrl: 'https://my-api.got/rest' });

client.get('/resource').catch((err) => {
  console.log(err.url);
});
```

When this endpoint errors.

**Expected:** `https://my-api.got/rest/resource`
**Actual:** `https://my-api.got/resource`

### Solution

I think the solution lies [somewhere around here](https://github.com/sindresorhus/got/blob/master/source/errors.js#L24).

**Comment by Moeriki** [comment]
I was wrong.

Starting the request url with `/` resets the pathname, which makes sense. Though confusing if you don't immediately think of it.

**Comment by szmarczak** [comment]
What got version are you using?

**Comment by Moeriki** [comment]
Version `9.0.0`.

**Comment by szmarczak** [comment]
You need at least `9.1.0`.

> Normalize the URL in the `baseUrl` option. (#579) c901c46
