### ISSUE TITLE
Requests with timeout always takes longer than 6 seconds

### ISSUE THREAD

**Issue by amio** [sindresorhus/got#602]
EXPECTED

- Set `timeout: 100` in option, the request should failed no too much longer than 100ms

CURRENT BEHAVIOR

- It takes longer than 6s to failed on 'ETIMEOUT'

REPRODUCE

https://runkit.com/amio/5b5873387b9d1e0011ef8f77

- https://untitled-qvjzo3otxk19.runkit.sh/
  `{ status: 'OK', timespan: 377 }` ✔
- https://untitled-qvjzo3otxk19.runkit.sh/2000
  `{ status: 'OK', timespan: 389 }` ✔
- https://untitled-qvjzo3otxk19.runkit.sh/200
  `{ "status": "Timeout awaiting 'request' for 200ms", "timespan": 6657 }` ✘

**Comment by szmarczak** [comment]
It should be 900 ms in total.

300 ms timeout * (1 req + 2 retries) = 900ms

**Comment by szmarczak** [comment]
Also could you make a failing test? To be sure it's Got's failure.

**Comment by sindresorhus** [comment]
Failing test docs: https://github.com/avajs/ava#failing-tests

**Comment by amio** [comment]
@szmarczak Sure, I'll take on this later :D

**Comment by alextes** [comment]
Looks like a simple misunderstanding. Still I'm curious, @amio , why did you expect a timeout to take 100ms? Is it because you were unaware we retry twice by default?

**Comment by szmarczak** [comment]
> Set timeout: 100 in option, the request should failed no too much longer than 100ms

@alextes is right. With timeouts enabled it should take 300ms in total and fail.

**Comment by amio** [comment]
@alextes Yup, I didn't notice the default value for `retry` is 2, I thought "retry" is an optional feature :D

I was testing if timeout works as expected, so set it to 100ms for triggering the error, then found it's response takes 6 seconds long =.=

**Comment by alextes** [comment]
I have the feeling I've seen this issue a bunch of times but looking through the issues says otherwise. If we get another I'm proposing an extension to the timeout docs explaining the in-practice timeout is not what one would naively expect 😅 .

Thanks for reporting amio
Closing!

**Comment by amio** [comment]
The clarification solved my problem, thanks!

PS, the timing still looks not quite as expected with default options (`retry === 2`), is it a problem?

- https://untitled-qvjzo3otxk19.runkit.sh/100 => `timespan: 6397` (expect 300+)
- https://untitled-qvjzo3otxk19.runkit.sh/200 => `timespan: 6763` (expect 600+)
- https://untitled-qvjzo3otxk19.runkit.sh/300 => `timespan: 7087` (expect 900+)

Acting like expected time span plus extra 6000ms 🤔

**Comment by szmarczak** [comment]
Can you show `response.timings` on latest got?

**Comment by szmarczak** [comment]
It should have.

Cc @sindresorhus

**Comment by sindresorhus** [comment]
@szmarczak I guess it could be useful, but then we need to clearly document that the response may be empty depending on when the timeout occurred.

**Comment by szmarczak** [comment]
Agreed

**Comment by voldern** [comment]
If I've understand the code correctly this happens because of how the default retry delay is calculated: https://github.com/sindresorhus/got/blob/master/source/normalize-arguments.js#L259.

So your request times out after 300ms, then it waits `((1 << 1) * 1000) + Math.random() * 100;` so ≃ 2000ms, then it times out after 300ms and then waits `((1 << 2) * 1000) + Math.random() * 100;` which is ≃ 4000ms. In total around 6600ms.

If you want a slower timeout before it retries you would have to send in a function to the `retries` argument.

**Comment by szmarczak** [comment]
@sindresorhus Maybe we should expose the retry delay?

**Comment by sindresorhus** [comment]
@szmarczak In what form? Can you provide an example of how it would look like using it?

**Comment by DenisKrsk** [comment]
Hey. I have the same problem. The timeout is longer than expected.
 **1000 => 6329; 2000 => 9232; 3000 => 12266; 4000 => 15291**

`const  got  =  require ( 'got' );
const  ProxyAgent  =  require ('proxy-agent');

(async function(){
    var startTime = Date.now()
    var response = await got("https://gmail.com",
        {   
            timeout: 4000, 
            retries:0,
            decompress:false,
            agent: new ProxyAgent("https://192.168.1.11")
        }).catch(e=>{console.log(e)});
    console.log(Date.now() - startTime);
})();`

**Comment by szmarczak** [comment]
@amio Sorry for late response, but I just recalled this:

The `retry` function delays the next request by `((2 ** (iteration - 1)) * 1000)`.

@sindresorhus What about making a `retry.delay` option?

```js
{
	retry: {
		retries: 2,
		delay: iteration => Math.random() * 100
	}
}
```

**Comment by chris-erickson** [comment]
This could be useful for me.  I have an upstream consumer with a hard coded max wait of 10s, and this backoff logic constrains me a bit.  I control the thing I'm calling with Got, and would prefer a lot of retries in a short time to the exponential backoff since it's likely a brief blip from a deploy and that 10s window to complete the request is always looming.  The only way I can account for this now is to shorten the timeout wait, but that starts to encroach on a legitimately long wait on the downstream service.

**Comment by szmarczak** [comment]
You can do now (master branch):
```
{
	retry: {
		calculateDelay: ({attemptCount, computedValue})	=> {
			if (computedValue !== 0) {
				// You can provide a constant
				return 1000;
				// Or compute the delay based on `attemptCount`:
				return attemptCount * 1000;
			}

			return 0;
		}
	}
}
```

**Comment by sindresorhus** [comment]
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
