### ISSUE TITLE
Unable to get hook to fire

### ISSUE THREAD

**Issue by ruudud** [sindresorhus/got#611]
Hi, have some trouble getting the `beforeRequest` hook to fire. Tested using master (292f78a).

```javascript
const inst = got.extend({ hooks: { beforeRequest: [ () => { console.log('test'); } ] } });
inst.get('http://httpbin.org/'); // nothing logged
```

The only way I can get it to fire, is using `got.create` and adding a custom handler.

What am I doing wrong?

**Comment by loris** [comment]
I do confirm the issue against master.

It will only work this way:

`inst('http://httpbin.org/');`

If you use method shortcut (ie, `inst.get('http://httpbin.org/');`) or any options (ie, `inst('http://httpbin.org/', { method: 'GET' });`, hooks will not fire.

**Comment by szmarczak** [comment]
```
inst('http://httpbin.org/', {});
```

doesn't work either.

**Comment by szmarczak** [comment]
Found solution, working on a fix.
