### ISSUE TITLE
Maximum allowed response length

### ISSUE THREAD

**Issue by jiripospisil** [sindresorhus/got#617]
It would be great if it was possible to set the maximum allowed response length. If the response was larger than that, it would report an error. It should *not* rely on the response's `Content-Length`. 

Looking at the available API, it could be done manually by consuming the response as stream and counting but exposing it as an option would be more user friendly.

```javascript
const response = await got(url, {
  maxResponseLength: 123, // bytes
});
```

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/master/advanced-creation.md#limiting-download--upload

**Comment by benjie** [comment]
The above has moved to:

https://github.com/sindresorhus/got/blob/master/documentation/advanced-creation.md#limiting-download--upload-size

Permalink:

https://github.com/sindresorhus/got/blob/49c16ee54fb19ea7aa77e24ac8c2b602f0aad265/documentation/advanced-creation.md#limiting-download--upload-size

**Comment by szmarczak** [comment]
@benjie Good spot. Also it's not compatible with streams, since they use `stream.destroy`. Although we can make `stream.cancel` an alias to `stream.destroy`.

**Comment by benjie** [comment]
That seems wise; or update the doc. Thanks for the heads up :pray:

**Comment by szmarczak** [comment]
Updated: https://github.com/sindresorhus/got/blob/488001730f8094d1f569d6ca2d940a8915580dc8/documentation/examples/advanced-creation.js#L40-L77
