### ISSUE TITLE
can be hooks options not to be normalized?

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [sindresorhus/got#618]
I wanna use this lib with facebook graph API, but I have a single problem:

It will be awesome if I can use hooks for "signing" requests. In facebook API terms it just
```JavaScript
createHmac('sha256', FB_CLIENT_SECRET).update(ACCESS_TOKEN)
```
appended to query.

How i can follow this logic with `got`:
1 if options.query['access_token'] != void 0
2 then "sign" request

[https://developers.facebook.com/docs/graph-api/securing-requests/](https://developers.facebook.com/docs/graph-api/securing-requests/)

**Comment by dmitry-vakhnenko** [comment]
In python world with `requests` package we have session object, that can be extended for the same behavior.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/master/advanced-creation.md#signing-requests

**Comment by dmitry-vakhnenko** [comment]
Options inside hooks are normalized `request` options. So, for adding query options I should extract query, parse it, and replace param inside `options`. it`s pretty uncomfortable.
