### ISSUE TITLE
got does not work in electron renderer process with timeouts

### ISSUE THREAD

**Issue by phillipCouto** [sindresorhus/got#620]
Seems to be the problem is due to `got` is using the nodejs timers and [timeout.unref()](https://github.com/sindresorhus/got/blob/master/source/timed-out.js#L22) does not exist.

Sees like it is missing the check for `unref` like [the code above](https://github.com/sindresorhus/got/blob/master/source/timed-out.js#L16).

**Comment by phillipCouto** [comment]
I am more than happy to submit a merge request as it seems like a simple enough change.

**Comment by szmarczak** [comment]
timeout.ref() was added in Node v0.9.1. AFAIK electron uses Node's timers.

**Comment by phillipCouto** [comment]
Yes but the problem is in the renderer process it is the api from chrome and not nodeJS. Which is only setTimeout and clearTimeout. 

As per the second part of my OP adding the same check as what is used by the immediate fixes the problem.

**Comment by szmarczak** [comment]
It should exist as this file tells so: https://github.com/electron/electron/blob/master/lib/common/init.js but maybe I've missed something

Could you paste the stacktrace here?

**Comment by phillipCouto** [comment]
@szmarczak any update on this?

**Comment by sindresorhus** [comment]
Latter

**Comment by phillipCouto** [comment]
Thank you @szmarczak and @sindresorhus!
