### ISSUE TITLE
Consider getaddrinfo errors and some others

### ISSUE THREAD

**Issue by satazor** [sindresorhus/got#621]
The current error codes for network errors do not account DNS errors and some other network errors. In `npms-analyzer`, we consider the following list:

```
    'ETIMEDOUT',
    'ECONNRESET',
    'EADDRINUSE',
    'ESOCKETTIMEDOUT', *
    'ECONNREFUSED',
    'EPIPE',
    'ENOTFOUND', *
    'ENETUNREACH', *
    'EAI_AGAIN', *
```

Items marked with * are not currently interpreted as a network error.
Let me know if you agree on adding them, if so I will make a PR.

**Comment by szmarczak** [comment]
Node never throws "ESOCKETTIMEDOUT". Yeah, we can consider adding the rest.

**Comment by satazor** [comment]
You are right, perhaps it was being thrown in some older versions.
