### ISSUE TITLE
Consider defaulting retries to zero / turned off

### ISSUE THREAD

**Issue by trygve-lie** [sindresorhus/got#629]
I have currently added got to the test suite for [circuit-b](https://github.com/trygve-lie/circuit-b). Circuit-b is a implementation of the [circuit breaker pattern](https://doc.akka.io/docs/akka/current/common/circuitbreaker.html) using AsyncHooks to intercept the underlaying Net.socket of requests in a node.js instance done by any http client in a service.

During this I noticed that got has a retry feature with a default set to 2 retries and I thought I would like to comment a little bit on this.

A retry pattern with exponential reconnects is a nice pattern if one are doing long lived TCP/UDP socket connections where there are just a fiev connections. Then the process of reconnecting in it self is not a big stress on the upstream service when things have errored. 

But; when the transport is http requests a reconnect pattern might not be the optimal choice. 

If one have two services with a high amount of request between them, lets say ~400req/s (a lot of our services easilly get up to that), this pattern gets very dangerous if the upstream server starts failing. Even if it recovers after a very short time, the client requesting the erroring upstream server have already aggregated a queue of some thousand requests. This queue will then be released upon the upstream recovering service on top of already fresh incomming requests. In many cases this can be too much and deadly for the recovering upstream service causing to constantly error. In reality one end up with DDoSing one self.

I have seen this happen in multiple high trafficed services where retry features have been applied to http requests. This is why we have the circuit breaker pattern which is quite the opposite of a retry pattern. 

It is nice to be able to have a retry feature in a http client but I would like to suggest that the default retries should be set to zero and not 2 as it is now. Iow; let this be a feature one turn on if one want such a feature instead of something one have to turn off.

What do you think?

**Comment by szmarczak** [comment]
You can always set retry to 0 or use a custom agent with `keepAlive` option set to true.

You're free to choose the options, nobody says you must stay with the defaults, do they? :)

There's no need to change the default value. That's what the most users want ;)

>  this pattern gets very dangerous if the upstream server starts failing

No. It depends on how you write the code. You can do an additional layer for the inner communication between the servers. 

> Even if it recovers after a very short time, the client requesting the erroring upstream server have already aggregated a queue of some thousand requests.

Stop processing clients who have disconnected.
