### ISSUE TITLE
Option to not retry on timeout errors

### ISSUE THREAD

**Issue by medikoo** [sindresorhus/got#654]
I'm configuring requests for AWS lambda environment, and case is that:
- I set timeout option to ensure it ends before allowed lambda invocation time ends (so I handle eventual timeout gently by rejecting lambda invocation with meaningful error), and automated retry after such timeout occurs is unwanted.
- I'd like to have retries applied for case of temporary network or server unavailability errors.

Is there an option to achieve that?

**Comment by szmarczak** [comment]
Yes, the documentation states:

> [retry](https://github.com/sindresorhus/got#retry)
> ...
> The retries property can be a number or a function with retry and error arguments. The function must return a delay in milliseconds (0 return value cancels retry).

If you pass a function through the `retry.retries` option, it will use yours instead of [the default one](https://github.com/sindresorhus/got/blob/7f18ef397341214d9f46d774f69e65d6cdd95494/source/normalize-arguments.js#L205-L241).

**Comment by medikoo** [comment]
I indicated that I want to _conditionally_ opt out from default behavior, and assuming I'll follow what you suggest (so provide my own `retry.retries`) I'm forced to copy and paste [this part](https://github.com/sindresorhus/got/blob/7f18ef397341214d9f46d774f69e65d6cdd95494/source/normalize-arguments.js#L206-L241), which is not great.

So how I can do this cleanly:

```javascript

const defaultRetries = resolveDefaultRetriesFromGot(); // What should be here?

got(url, {
  retry: {
    retries: (iteration, error) => {
      if (error instanceof got.TimeoutError) return 0;
      return defaultRetries(iteration, error);
    }
  }
});

```

**Comment by szmarczak** [comment]
```js
const defaultRetries = got.defaults.options.retry.retries;
```

Please tell me if it works or not :)

**Comment by medikoo** [comment]
> Please tell me if it works or not :)

Not really, as `got.defaults.options.retry.retries` equals `2` -> https://github.com/sindresorhus/got/blob/7f18ef397341214d9f46d774f69e65d6cdd95494/source/index.js#L8

Default function appears there only after options normalization is made.

That could be solved if normalized `options` would be exposed on promise as returned by `got(url)`.
Then I could just override `options.retry.retries` function with decorated version

**Comment by szmarczak** [comment]
I'll try to fix this when I'm back home.

**Comment by sindresorhus** [comment]
@szmarczak We already let people configure which HTTP status codes to retry on, maybe we should also allow people to specify which network errors codes to retry on?

**Comment by szmarczak** [comment]
@sindresorhus Definitely yes! I'll make a PR 😺
