### ISSUE TITLE
case-sensitive urls (twitter)

### ISSUE THREAD

**Issue by jamesbillinger** [sindresorhus/got#664]
#### What would you like to discuss?
I know that this isn't the first time that case-sensitivity has been discussed, but I ran into an issue using got with Twitter's shortened urls (t.co) - which are case sensitive.  So a browser can successfully access https://t.co/aTswyWBwIN but not https://t.co/atswywbwin

I understand that this may be "non-standard", but if someone as large as Twitter is relying on this perhaps got would provide a mechanism to support it?

Thanks, I appreciate all the work and totally understand if this is technically undesirable.
...

#### Checklist

- [x] I have read the documentation.

**Comment by jamesbillinger** [comment]
Axios is working perfectly in this scenario - I had another package that was lowercasing the url.  Sorry for the mistake, and thanks again for a great library.

**Comment by szmarczak** [comment]
Sorry, but you haven't made clear what you're trying to do. Can you explain?

**Comment by jamesbillinger** [comment]
Yeah, sorry, I was trying to use "got" to load URLs pulled from Twitter's API.  They return shortened "t.co" URLs that are case-sensitive.  Initially I was receiving 404 errors because the URLs were being passed as lowercase, and I mistakenly blamed "got" for the case changes.  LIke I said, I've since realized that it was a different lib that was responsible, and "got" was working perfectly.
