### ISSUE TITLE
got pause/resume download

### ISSUE THREAD

**Issue by karmac2015** [sindresorhus/got#668]
#### What would you like to discuss?

How can I pause/ resume got when using it to downloading a file from another server?
**Note**: I want to use the same request to not registering events again

#### Checklist

- [ ] I have read the documentation.

**Comment by szmarczak** [comment]
Use [streams](https://github.com/sindresorhus/got#gotstreamurl-options).

```js
gotStream.pause();
gotStream.resume();
```

**Comment by blogwy** [comment]
how use? Cannot read property 'pause' of undefined
