### ISSUE TITLE
127.0.0.1:0 causes exception in io.js@2

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#67]
request lib also has this issue: https://github.com/request/request/issues/1596

**Comment by floatdrop** [comment]
@stevenvachon hm... I get this error only on `iojs@2`, but not in `IOjs@1.8.2`, Node 0.10 or 0.12. Also  only `127.0.0.1:0` host is throwing error, which is pretty strange.

**Comment by sindresorhus** [comment]
Is there an io.js ticket for this? If not, can you open one? I don't see how this is relevant to `got` though. We're just a consumer of the HTTP API.

**Comment by stevenvachon** [comment]
```js
var req = require("http").request({hostname:"127.0.0.1",port:0});
req.on("error",function(e){throw e});
```
does not produce the same error

**Comment by julien-f** [comment]
Again, for me it makes no sense to attempt to connect to port 0…

**Comment by stevenvachon** [comment]
It doesn't, but should it *throw* an error when all other errors are returned in the callback (in request and got libs)

**Comment by julien-f** [comment]
Ahhh, I understand now!

Indeed it would make sense for all errors to be async.

**Comment by sindresorhus** [comment]
Seems like it's fixed in Node 4:

```
❯ node -e 'require("./")("http://127.0.0.1:0", err => console.error(err));'     
{ [RequestError: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:65229)]
  message: 'connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:65229)',
  code: 'EADDRNOTAVAIL',
  host: '127.0.0.1:0',
  hostname: '127.0.0.1',
  method: 'GET',
  path: '/' }
```
