### ISSUE TITLE
Add HISTORY.md / changelog

### ISSUE THREAD

**Issue by clocked0ne** [sindresorhus/got#672]
#### What problem are you trying to solve?

There is no quick way to see what has changed in each new package revision.

#### Describe the feature

Add a History/changelog file that indicates what has changed in each version pushed to NPM.
For a module which deals in something as complex as HTTP requests I feel this is essential.

E.g. Documentation changes which have unexpected consequences: https://github.com/sindresorhus/got/pull/670

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by tusbar** [comment]
Yes there is: https://github.com/sindresorhus/got/releases

**Comment by clocked0ne** [comment]
I didn't even think to check there 😨  closing
