### ISSUE TITLE
`accept-encoding` headers default value when using `{decompress: true}` may result in "incorrect header check"

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#677]
I am making a request with `{decompress: true}`.

Here is the request that got is producing:

```bash
curl -H 'user-agent:got/9.4.0 (https://github.com/sindresorhus/got)' -H 'host:www.finnkino.fi' -H 'accept-encoding:gzip, deflate' -H 'Connection:close' 'https://www.finnkino.fi/en/websales/show/1269786'

```

As you can see (and as is documented), Got adds `accept-encoding:gzip, deflate` header.

The problem is that the reserver responds with:

```
< HTTP/1.1 200 OK
< Cache-Control: private, no-store
< Content-Type: text/html; charset=utf-8
< Content-Encoding: deflate
< Server: Microsoft-IIS/8.0
< X-AspNetMvc-Version: 5.2
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< Date: Sat, 15 Dec 2018 13:30:30 GMT
< Content-Length: 15849
< Set-Cookie: NSC_MC_wt_IUUQT=ffffffff09b4cc7545525d5f4f58455e445a4a42378b;expires=Sat, 15-Dec-2018 14:00:30 GMT;path=/;secure;httponly

```

which results in:

```
ReadError: incorrect header check
    at EventEmitter.emitter.on (/[..]/node_modules/got/source/as-promise.js:28:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I am assuming this is because response includes `Content-Length` together with `Content-Encoding: deflate`.

If I override `content-encoding` to `gzip`, Got processes the request without complaining.

Is there a reason to include "decompress" algorithm in the first place?

**Comment by sindresorhus** [comment]
Sounds related to https://github.com/sindresorhus/got/issues/388#issuecomment-346275633.

**Comment by simon300000** [comment]
I think I might found a solution to this and #388 

Error: ReadError: incorrect header check
```javascript
(async () => {
  console.log((await got('https://api.bilibili.com/x/v1/dm/list.so?oid=53534698')).body)
})()
```

Works:
```javascript
const got = require('got')
const { inflateRaw } = require('zlib')

;(async () => {
  let buffer = (await got('https://api.bilibili.com/x/v1/dm/list.so?oid=53534698', { decompress: false })).body
  inflateRaw(buffer, function(err, data) {
    if (err) throw err
    console.log(String(data))
  })
})()
```

It seems like for some deflate request we need to use `inflateRaw` function.
I didn't find out why.


Ref: request/request#2197

**Comment by szmarczak** [comment]
@sindresorhus has already answered why.

> it's because browsers are more lenient to incorrect responses than Node.js
