### ISSUE TITLE
Get intermediate redirect url and stop

### ISSUE THREAD

**Issue by ash0080** [sindresorhus/got#680]
```
got(url, {
        agent,
        timeout: CONFIG.TIMEOUT,
        hooks: {
          beforeRedirect: [
             options=> {
              console.dir(options)
              if (options.hostname === 'matchedHost') {
                 const reUrl = options.href
                // any way to return the reUrl here?
                options.followRedirect = false
              }
            }
          ]
        }
    })
```
Tried assignment, non-arrow function and return,  all not work

**Comment by ash0080** [comment]
OK,  I got it, the followRedirect false will throw an Error. 
so new question is how to stop the next request and keep the reUrl out.

**Comment by szmarczak** [comment]
Could you complete the issue template please? To solve the issue we need know what you're trying to do, what error you got, etc.

As I see it there's nothing wrong with your code. Just do: `response.headers.location` for the redirect location.

Make sure to read the documentation, it has many helpful tips. If there's any problem, I'll be happy to help.

**Comment by ash0080** [comment]
@szmarczak I have read all docs, the problem in this practice is there are several redirects, I only want to get the specific intermediate one match the condition and stop it Immediately, or else, the later redirect will be post an error to server and all recorded url will be expired. special use case, but it exist.

**Comment by szmarczak** [comment]
Oh, I understand now. Thanks for clarification :)

Unfortunately, you can't just stop processing redirects. It goes till the end.
But, you can do this (taken from [`advanced-creation.md`](https://github.com/sindresorhus/got/blob/master/advanced-creation.md#denying-redirects-that-lead-to-other-sites-than-specified), just modified a bit):

```js
const processResponse = response => {
	// do something
};

const gotInstance = got.create({
	options: got.defaults.options,
	handler: (options, next) => {
		const promiseOrStream = next(options);
		return promiseOrStream.on('redirect', response => {
			processResponse(response);

			const host = new URL(resp.url).host;
			if (host === 'someSite') {
				promiseOrStream.cancel(`Redirection stopped at ${host}`);
			}
		});
	}
});

gotInstance(...);
```

**Comment by ash0080** [comment]
@szmarczak I use await async pattern, so I try to make it like this

```
try {
      await got(url, {
        headers: {
          userAgent: CONFIG.USER_AGENT,
        },
        agent,
        timeout: CONFIG.TIMEOUT,
        hooks: {
          beforeRedirect: [
            options => {
              if (options.hostname === 'MATCH_PATTERN') {
                redirectArray.push(options.href)
                options.followRedirect = false
              }
            }
          ]
        }
      })
    } catch (error) {
      if (error.statusCode === 302) {
        const redirectTo = _.last(redirectArray)
        return redirectTo
      }
      throw new Error('NO MATCH')
    }
```

but the problem i faced is the options.href should match options.hostname but not in fact. strange

**Comment by epeli** [comment]
I had a situation where I had to prevent doing redirects to other than the original domain. I wanted got to just reject with error if it tries to redirect to an unwanted domain.

So my workaround for now is just to change the request domain to something invalid:

```ts
            beforeRedirect: [
                (options) => {
                    const {hostname} = new URL(originalURL);
                    if (options.hostname !== hostname) {
                        options.hostname = "cross-domain-redirect.invalid";
                    }

                    return options;
                },
            ],
```

**Comment by szmarczak** [comment]
@epeli No need for a workaround. Just throw an error within the hook.
