### ISSUE TITLE
Performing transformation on the data returned from the response

### ISSUE THREAD

**Issue by muliyul** [sindresorhus/got#681]
#### What would you like to discuss?

Is it possible to add custom transformation the data returned from the response?

Example:
I have an api that returns base64 encoded PDF but I want to serve it to the client with streams (from the first byte received)

I noticed there's an `encoding` option however it doesn't accept custom implementations.

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Use [after response hook](https://github.com/sindresorhus/got#hooksafterresponse).

```js
const got = require('got');

const instance = got.extend({
	hooks: {
		afterResponse: [
			(response, retryWithMergedOptions) => {
				if (response.statusCode === 200) {
					response.body = process(body);
				}

				return response;
			}
		]
	},
	mutableDefaults: true
});
```

**Comment by muliyul** [comment]
This didn't work for me. For some reason afterResponse doesn't get called.

**Comment by szmarczak** [comment]
> I was expecting this to work with streams because it wasn't stated anywhere that it shouldn't

Streams are much different than the usual Promise implementation. Some hooks won't work there - you receive the data immediately; promises give you the whole result. Yup, a note in the README would be nice.

`.pipe()` does the job. [This test](https://github.com/sindresorhus/got/blob/91c0607b21f85adc568a0d182b47483e59855f95/test/stream.js#L116-L119) proves it.

> however apparently it was transforming all the request (incl headers). I just want to transform the response body

Can you provide a fully-working example?

**Comment by muliyul** [comment]
Got it to work using [this](https://github.com/hapijs/b64). cheers!

**Comment by szmarczak** [comment]
I'm glad you solved the issue :)

**Comment by muliyul** [comment]
@szmarczak I'd like to open a PR for a readme update. What hooks are supported for streams? I know `beforeRequest` is but that's all I know.

**Comment by szmarczak** [comment]
> I'd like to open a PR for a readme update.

Sure! 😄 

> What hooks are supported for streams?

Well, streams don't have retry support. So `beforeRetry` is promise-only. `beforeRequest` just modifies the options, so it works for both. `afterResponse` needs the whole response, so it works only with promises. `beforeRedirect` just checks the headers, it works for both.
