### ISSUE TITLE
How do I make a basic http post request?

### ISSUE THREAD

**Issue by AbhishekMadiraju** [sindresorhus/got#682]

**Comment by AbhishekMadiraju** [comment]
```
let beg = 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token'; 
let reqBody1 = 'client_id=' + client_id + '&scope=offline_access%20user.read%20mail.read' +
 '&code=' + output + '&redirect_uri=' + process.env.WEBAPP_ENDPOINT + '/msteamsauth';
let reqBody2 = '&grant_type=authorization_code' + '&client_secret=' + client_secret;
let reqBody = reqBody1 + reqBody2;
const resp = await got.post(beg, {
           body: reqBody,
           headers: {
                    'content-type': 'application/x-www-form-urlencoded'
            }
 });
```

That's how I am doing it now. Is it right?

**Comment by szmarczak** [comment]
Please read the API before making an issue.

**Comment by szmarczak** [comment]
> That's how I am doing it now. Is it right?

Yes. [`got.post(url, [options])`](https://github.com/sindresorhus/got#gotposturl-options) where `options` is [this](https://github.com/sindresorhus/got#options).

**Comment by sindresorhus** [comment]
Tip: Use the `form` option instead of concatenating the query strings.

https://github.com/sindresorhus/got#form

**Comment by nivaldodasilva** [comment]
This is not so obvious at all. Still not understand why we cannot just post:

`await got.post('url', {
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    },
                    body: {
                            a: 1,
                            b: 'Why not',
                            c: false
                     }
                });`

**Comment by Giotino** [comment]
> This is not so obvious at all. Still not understand why we cannot just post:
> 
> `await got.post('url', { headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: { a: 1, b: 'Why not', c: false } });`

Because, in your example, `body` is not a `string | Buffer | stream.Readable or form-data instance` https://github.com/sindresorhus/got#body .
You should use the `form` option https://github.com/sindresorhus/got#form
