### ISSUE TITLE
Strange timing data for http requests

### ISSUE THREAD

**Issue by casret** [sindresorhus/got#687]
#### Describe the bug

 - Node.js version: tested with 9.11.2, 10.15.0, and 11.6.0
 - OS & version: tested with Mac OS Mojave, and Linux

When I get timing data for an http request, the numbers don't make sense.  (https works).

#### Actual behavior

I get timing data where phases.request is a epoch time instead of duration.  In production when I use keepalive, I also see cases where upload < start, but the repro and pull request only demonstrate the phases.request weirdness.  

If you use https, the timings look fine.

#### Expected behavior

I would expect phases.requests to be an actual duration.

#### Code to reproduce

```js
const got = require("got")

const url = "http://google.com/"
;(async () => {
  const response = await got(url)

  console.log(response.timings)
})()
```

#### Checklist

- [ x] I have read the documentation.
- [ x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
```js
{ start: 1546537817663,
  socket: 1546537817665,
  lookup: 1546537817666,
  connect: 1546537817667, // note this occurs later (socket `connect` event)
  upload: 1546537817666,  // than this (request `finished` event)
  response: 1546537817920,
  end: 1546537817923,
  error: null,
  phases:
   { wait: 2,
     dns: 1,
     tcp: 1,
     request: 1546537817666,
     firstByte: 254,
     download: 3,
     total: 260 } }
```

Even if I include [`deferToConnect`](https://github.com/szmarczak/defer-to-connect) into the `finished` callback, it still fails because `socket.connecting` is `false` before emitting the `connect` event.

**Comment by szmarczak** [comment]
> I also see cases where upload < start

Have you got any logs? As I find it impossible, because `timer(...)` is called before `request.end()`...

**Comment by szmarczak** [comment]
Fixed in `@szmarczak/http-timer@1.1.2` :tada:

**Comment by casret** [comment]
@szmarczak I think you are right, I must've been looking at the connect/upload timings that you mentioned in the thread.  I'll use 1.1.2 and check in production if anything is still off.

**Comment by szmarczak** [comment]
Sure. I'll reopen this issue if you find anything wrong :)
