### ISSUE TITLE
Timeout option not working with proxy (using tunnel as proxy)

### ISSUE THREAD

**Issue by lounsbrough** [sindresorhus/got#689]
#### Describe the bug

 - Node.js version: 11.0.0
 - OS & version: Windows 10 Pro

The timeout option does not seem to work when using a proxy. I'm using tunnel per the examples in the README.

#### Actual behavior

`timeout` option set to 10000 milliseconds. Request via proxy takes > 30 seconds to timeout.

#### Expected behavior

Request should timeout after the specified number of milliseconds.

#### Code to reproduce

```
const response = await got(url, {
    agent: tunnel.httpsOverHttp({
        proxy: {
            host: proxy.host,
            port: proxy.port,
            proxyAuth: `${proxy.username}:${proxy.password}`,
            headers: getRequestHeaders()
        }
    }),
    headers: getRequestHeaders(),
    timeout: 10000
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you set the `retry` option to `0` and try again?

**Comment by lounsbrough** [comment]
With timeout set to 0, the connections fail almost instantly.

**Comment by szmarczak** [comment]
Is it a Timeout Error?

**Comment by szmarczak** [comment]
Try setting `timeout` to 1000 and `retry` to 0. Does it fail?

**Comment by lounsbrough** [comment]
With retries set to 0, it also fails immediately.

**Comment by lounsbrough** [comment]
I've found a workaround which is to reject the Promise with my own timeout. I'm going to close this issue and if it becomes a problem for me again I'll upload example code of the failure.
Thanks!

**Comment by shikar** [comment]
> #### Describe the bug
> * Node.js version: 11.0.0
> * OS & version: Windows 10 Pro
> 
> The timeout option does not seem to work when using a proxy. I'm using tunnel per the examples in the README.
> 
> #### Actual behavior
> `timeout` option set to 10000 milliseconds. Request via proxy takes > 30 seconds to timeout.
> 
> #### Expected behavior
> Request should timeout after the specified number of milliseconds.
> 
> #### Code to reproduce
> ```
> const response = await got(url, {
>     agent: tunnel.httpsOverHttp({
>         proxy: {
>             host: proxy.host,
>             port: proxy.port,
>             proxyAuth: `${proxy.username}:${proxy.password}`,
>             headers: getRequestHeaders()
>         }
>     }),
>     headers: getRequestHeaders(),
>     timeout: 10000
> });
> ```
> 
> #### Checklist
> * [x]  I have read the documentation.
> * [x]  I have tried my code with the latest version of Node.js and Got.

How to solve it?

**Comment by szmarczak** [comment]
@shikar If you're having a similar issue to this one, please open a new issue.
