### ISSUE TITLE
Normal http proxy behaviour

### ISSUE THREAD

**Issue by andrefernandes** [sindresorhus/got#69]
Is honoring the default proxy behaviour ("npm config" or env variables) intended or is this supposed to be a low-level API that will never do it?
Thanks.

**Comment by sindresorhus** [comment]
You can easily use it with a proxy: https://github.com/sindresorhus/got#proxy

Built-in proxy support will come when someone implements it. I don't need or care about it.

**Comment by andrefernandes** [comment]
Thanks for the quick answer :)
