### ISSUE TITLE
Support non utf-8 servers

### ISSUE THREAD

**Issue by piuccio** [sindresorhus/got#692]
#### What would you like to discuss?

I was trying to use `got` with servers that don't use `utf-8` (in this case it's `shift_jis`) and this line prevents me from making any request
https://github.com/sindresorhus/got/blob/33b838fe167ccb09f7728c379480099cbbbe38a0/source/request-as-event-emitter.js#L43

`decodeURI` only works with UTF8 strings, but my URL is encoded in Shift JIS

Here's an example URL https://kw.travel.rakuten.co.jp/keyword/Search.do?f_query=%93%8C%8B%9E%89w

Note the `f_query=`, if you try to decode it as it is it'll throw an error `URIError: URI malformed`
However it's correctly handled by the server

Would it be possible to add an option to skip uri validation?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
Sorry, no. You can decode the URL yourself before passing it to Got.

**Comment by piuccio** [comment]
No I can't because the server doesn't accept utf8, the URL itself if fine as it is because it's in ASCII, browsers and curl can handle it just fine. Try `curl https://kw.travel.rakuten.co.jp/keyword/Search.do?f_query=%93%8C%8B%9E%89w` you'll get a response, while `got` throws an exception

I just want to disable that check in your code that prevents me from sending non utf8 values.

If you don't care it's fine I can use the native `http` module directly, but you dismissed me as if I'm asking something stupid.

To avoid extra options maybe that line should be

```js
if (options.encoding !== nul) {
   decodeURI(currentUrl);
}
```

so it's only disabled for people that specify their own encoding

**Comment by shuiRong** [comment]
I also had this problem today and then solved it using `iconv-lite`

https://gist.github.com/shuiRong/f4703da89e7f07baafaaa4a8fad86668
