### ISSUE TITLE
Right-hand side of 'instanceof' is not an Object

### ISSUE THREAD

**Issue by oknoorap** [sindresorhus/got#693]
#### Describe the bug

 - Node.js version: 10.12.0
 - OS & version: Linux 4.13.0-41-generic 46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'm using CRA (Create React App) version 2, customized-cra, and mobx, when I try to run simple code, I got an error.

#### Actual behavior
```
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
    at normalize (normalize-arguments.js:188)
    at got (create.js:37)
```

#### Expected behavior
Should return html body.

#### Code to reproduce

codesandbox: https://codesandbox.io/s/n4q68m36ll

code:
```js
try {
      console.log(this.resturl.spinnerList)
      const response = await got('sindresorhus.com')
      console.log(response.body)
    } catch (error) {
      console.log(error)
    }
```

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
```
TypeError: Right-hand side of 'instanceof' is not an object
    at normalize (node_modules/got/source/normalize-arguments.js:137:68)
    at got (node_modules/got/source/create.js:32:28)
```

https://github.com/sindresorhus/got/blob/91c0607b21f85adc568a0d182b47483e59855f95/source/normalize-arguments.js#L137

**Comment by szmarczak** [comment]
I ran `require('url').URLSearchParams` in the sandbox. It gives `undefined`. On my local machine it works perfectly.

**Comment by oknoorap** [comment]
@szmarczak 
I'm not running my code in the codesandbox, but also in my local machine too.I just put an example link in order to add a working project example (not just code / screenshot).

**Comment by oknoorap** [comment]
@szmarczak okay i see. thank you.

**Comment by rohmanhm** [comment]
https://github.com/sindresorhus/ky is a good alternative for browsers

**Comment by oknoorap** [comment]
@rohmanhm thanks dude..
