### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by radum** [sindresorhus/got#7]
If we use this behind a corporate proxy will fail with `ECONNREFUSED` and I'm not sure how this can be updated to take a proxy option when it's called.

**Comment by sindresorhus** [comment]
@floatdrop Maybe we should just mention it in the docs?

**Comment by floatdrop** [comment]
@sindresorhus there is another module - [tunnel-agent](https://github.com/mikeal/tunnel-agent), which is used in request. I think it worth to mention it in readme :+1:

**Comment by sindresorhus** [comment]
@floatdrop tunnel-agent looks like is just node-tunnel: https://github.com/mikeal/tunnel-agent/issues/2

**Comment by floatdrop** [comment]
@sindresorhus yeah, but with some patches. Hope they will be ported to node-tunnel soon.

**Comment by radum** [comment]
@floatdrop both node-tunnel and tunnel-agent work just fine, but my problem is not with got missing proxy support is with all the other modules using got and not implementing proxy support.

I've already had this conversation some time ago with @sindresorhus (https://github.com/kevva/download/pull/13) and as he pointed out making every module downstream care about it doesn't work in real life because they suck and nobody cares about them but they are here to stay so IMHO I think proxy support should be handled by the low level modules that are actually doing the work.

Now `HTTP(S)_PROXY` env vars are fairly common and most of us are using them as a standard across all major OS. As an example I think `bower` had the same issues a long time ago and is using those env vars to make the requests as do many other modules anyways.

**Comment by floatdrop** [comment]
@radum thanks for linking this conversation. I agree with @sindresorhus, that it should be implemented in default agent. For example Go has support of `HTTP_PROXY` (without HTTPS, lol), so Node should do it as well (but apparently it won't https://github.com/joyent/node/issues/1973).

**Comment by radum** [comment]
Yeah the entire thing it's broken everywhere I know because I'm behind one and it's a pain everyday.

Python guys have done it also for their request version http://docs.python-requests.org/en/latest/user/advanced/#proxies as for Node, it should be part of core IMHO. Thanks for the alternatives and the doc update anyways.

**Comment by sindresorhus** [comment]
I'm open to it, but it would need to be in a form of a good PR (preferably with as much code as possible in depending modules) with promise to continue maintaining it, as I'm not interested.

> so Node should do it as well (but apparently it won't joyent/node#1973).

That issue is old so someone could try again, but that person should make sure the new issue has a lot of good arguments and evidence of why it should be in core.

> as for Node, it should be part of core IMHO

Agreed!

-

I do wonder why Node can't just use the system proxy settings.

**Comment by vvo** [comment]
> I do wonder why Node can't just use the system proxy settings.

Now it's time to tackle this issue for good! :-)

**Comment by shinnn** [comment]
https://github.com/iojs/io.js/issues/1490

**Comment by avimar** [comment]
For socks5 proxies, this package seems to work as a replacement for node-tunnel which only handles http proxies:

```
const got = require('got');
const SocksProxyAgent = require('socks-proxy-agent');
const proxyOptions = 'socks5://localhost:8080';
const tunnel = new SocksProxyAgent(proxyOptions);


got('https://sindresorhus.com', {
	agent: tunnel
	})
});
```

**Comment by niknah** [comment]
With the latest version of got...

```
got('https://sindresorhus.com', {
	agent: { http:tunnel, https:tunnel, http2:tunnel}
	})
});
```
