### ISSUE TITLE
Set Content-Type on POST requests

### ISSUE THREAD

**Issue by kevva** [sindresorhus/got#70]
Most POST requests (by default) are made with the `application/x-www-form-urlencoded` Content-Type. We (node) are using `text/plain` by default. I think it's worth changing this to use a more expected behavior.

**Comment by sindresorhus** [comment]
What does `request` do?

**Comment by kevva** [comment]
They have a `form` option https://github.com/request/request#applicationx-www-form-urlencoded-url-encoded-forms.

**Comment by kevva** [comment]
cc @floatdrop @julien-f @arthurvr @shinnn

**Comment by julien-f** [comment]
As a user I do not mind setting the content type myself if I already have to format my data.

**Comment by floatdrop** [comment]
It make sense in browser environment, but in node (if body is String) `text/plain` is more accurate (String is plain text, right?). I'm not sure about Stream thou - it can be `binary/octet-stream` by default.

Maybe mention it in readme somehow (like - example how to send form data)?

**Comment by floatdrop** [comment]
@kevva maybe, if body is plain object, it makes more sense to setup content-type and stringify object for user?

```js
got.post('http://somesite.com', {
    body: {
        search: 'text'
    }
});
```

**Comment by sindresorhus** [comment]
@kevva :arrow_up:

**Comment by kevva** [comment]
@floatdrop, yes, that'd be really useful.
