### ISSUE TITLE
Rewrite Got in TypeScript

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#700]
We want typings available and keeping a type definition file in sync with the actual codebase is a lot of work in itself and it's easy for them to get out of sync. I also think the codebase could benefit from being written in TypeScript, as the code is quite complex and it's easy to make subtle mistakes.

**Comment by gajus** [comment]
What is the reason for choosing TS of Flow?

**Comment by sindresorhus** [comment]
It's mainly about familiarity and popularity. Popularity means it's easier to attract potential contributors. But I've also noticed that TS has better error messages, and the fact that TS is written in TS (meaning JS) is definitely a bonus. Very few knows OCaml.

**Comment by gajus** [comment]
@sindresorhus Do you have an example of a specific error that TS produces that is more developer friendly than what Flow would produce?

The other two arguments make sense. OCaml codebase indeed makes it for a steep entry barrier to contribute to the codebase, and TS has gained a lot of popularity over the last 6 months.

**Comment by gajus** [comment]
That comment is one year old.

Flow errors improved _a lot_ over the last 12 months.

Now errors show where the issue originates and walks you through all incompatibilities down the graph.

<img width="1092" alt="screenshot 2019-01-14 at 10 37 43" src="https://user-images.githubusercontent.com/973543/51107963-7720ca80-17e8-11e9-9e35-298916b35168.png">

This helps a lot with refactoring.

I am based of course as I hardly use TS. Flow feels like a second skin.

Either way, I think that TS is the right choice for Got for the other reasons you have suggested. I was more curious what is driving the decision rather than influencing the decision.

**Comment by ferdaber** [comment]
This looks like an interesting project- I'd like to help! I can start with at least adding the TypeScript build/test steps.

**Comment by medikoo** [comment]
Aren't you worried that complexity it'll add, will shadow the benefit?

`got` codebase is now pretty straightforward to get through, and library works very well (doesn't feel buggy in any part).

What real problem converting to TS aims to solve?

**Comment by medikoo** [comment]
> Adding types will let us be more confident about doing changes

Do you remember any specific issues that wouldn't happen if it'll be TS already?

This move also makes more difficult to contribute for JS developers not interested or not familiar with TS. It narrows the audience.

**Comment by sindresorhus** [comment]
> Can't this be solved simply with JSDoc? I haven't explored that deeply, but I think TS can read types of out it as well

No, JSDoc helps to some degree, but TS is much more powerful.

This is also not really the place to discuss the merits of TS. We have already decided to use it. I would recommend asking in my [AMA](https://github.com/sindresorhus/ama) instead.

**Comment by sindresorhus** [comment]
> Do you remember any specific issues that wouldn't happen if it'll be TS already?

Not specifically, but I remember some instances where we shipped bugs because of unpredicted conditions that would have been caught with stronger types. It's not just about catching problems either, but it makes it easier for us to work on Got. We now get auto-completion for everything and can do large refactors with ease.

> This move also makes more difficult to contribute for JS developers not interested or not familiar with TS. It narrows the audience.

I'm ok with that. By requiring TS I think we'll get higher quality contributions too, as it sets a higher minimum JS/TS knowledge level. In reality though, this is irrelevant as 99.9% of the commit in Got are by the maintainers.

**Comment by sindresorhus** [comment]
The TS setup is done, so now it's possible to convert to TS file-by-file. If you want to contribute pick one or more files you think you can manage and have fun. Just rename the `.js` file to `.ts` and try to build. Make sure you read https://github.com/sindresorhus/typescript-definition-style-guide for the style we use and document all public interfaces (bonus points for documenting private ones too).

**Comment by ricardorojass** [comment]
Hi everyone, I'd like to help with this project, I'll be going to rewrite source/errors.js in TS.

**Comment by michaeldera** [comment]
I would love to help rewrite the files in TypeScript, is there a specific file I can go for?

**Comment by sindresorhus** [comment]
@michaeldera Pick any `.js` file you think you can handle and that's not already being worked on in an open PR ;)

For example: https://github.com/sindresorhus/got/blob/master/source/create.js

**Comment by Magellol** [comment]
Started to tackle https://github.com/sindresorhus/got/blob/master/source/as-stream.js in https://github.com/sindresorhus/got/pull/720 👍

**Comment by michaeldera** [comment]
#721 converted create.js to TypeScript. Ran into one issue and could use help with that. I added the details in the PR

**Comment by sindresorhus** [comment]
We are still looking for help getting this done. 🙌

Left to do:

- [ ] `source/as-promise.js`
- [ ] `source/normalize-arguments.js`
- [ ] `source/request-as-event-emitter.js`
- [ ] `source/index.js` (the above should be done first)

When these are done, we'll need help converting the [tests](https://github.com/sindresorhus/got/tree/master/test) to TypeScript.

**Comment by indiescripter** [comment]
fwiw and feel free to disagree but since a lot of people will consume this package in a JS project (meaning I'm just making this assumption)  then tests should probably remain in JS. Consumers calling from JS into TS do not get the benefit of static type safety and accordingly the Got APIs should not make any assumptions about validity of arguments passed in.

If the tests are written in TS and say an API function takes a number (and is typed as such) then when one tries to write a test that passes in, say, a string instead of a number then TS will produce a compile error. To work around the difficulty of writing tests to check the robustness of APIs against any arbitrary types of values thrown at them, one ends up doing a lot of `any` cast gymnastics.

**Comment by tobenna** [comment]
I can do `source/normalize-arguments.js`

**Comment by sindresorhus** [comment]
> To work around the difficulty of writing tests to check the robustness of APIs against any arbitrary types of values thrown at them, one ends up doing a lot of `any` cast gymnastics.

I've been doing that in other TS-written modules. It's not a big problem to write a few `as any`.

**Comment by sindresorhus** [comment]
@tobenna 👍 Great

**Comment by paulmelnikow** [comment]
I will give `source/request-as-event-emitter.js` a shot!

**Comment by sindresorhus** [comment]
I decided to disable strict-mode for now and move the rest of the files over to TS so the TS migration would not be blocking other work. The rest of the work is moved into https://github.com/sindresorhus/got/issues/758

Thanks for all the help everyone. ❤️
