### ISSUE TITLE
Set Content-Length when body is a string or a buffer

### ISSUE THREAD

**Issue by julien-f** [sindresorhus/got#71]
If not already defined by the user of course.

**Comment by sindresorhus** [comment]
:+1:

**Comment by floatdrop** [comment]
Notice [RFC 2616 Section 4.4](http://tools.ietf.org/html/rfc2616#section-4.4):

> If a Content-Length header field (section 14.13) is present, its decimal value in OCTETs represents both the entity-length and the transfer-length. The Content-Length header field MUST NOT be sent if these two lengths are different (i.e., if a Transfer-Encoding header field is present). If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored.
