### ISSUE TITLE
`electron.net` decompress caveat

### ISSUE THREAD

**Issue by ccorcos** [sindresorhus/got#717]
- Node.js version:  v11.3.0
 - OS & version: Mac OS 10.14

The `decompress: false` option doesn't work as expected. When you're using electron's net API, the chromium network stack will automatically send `accept-encoding` headers and decode the result for you. Thus, the response data will always be decoded regardless of the content-encoding header. It would be nice to add this to the documentation under the decompress option.

**Comment by szmarczak** [comment]
Currently lots of electron features are broken, because of the new electron updates. We haven't fixed that yet - currently we are focused on rewriting Got to TypeScript. Once we achieve that, we'll figure out the rest :)

**Comment by szmarczak** [comment]
Closing in favor of #899
