### ISSUE TITLE
url.path vs url.pathname

### ISSUE THREAD

**Issue by julien-f** [sindresorhus/got#72]
It seems that `http(s).request(url)` uses `url.path` while `urlLib.format(url)` uses `url.pathname`.

I do not have the time to look further but I think it can cause some issues (for instance when displaying the URL in an error message).

**Comment by floatdrop** [comment]
@julien-f nice catch. `url.format` is not quite good at formatting I think:

```js
url.format({protocol: 'http:', host: 'localhost', port: 6767});
// => http://localhost without port
```

So in error messages (that was generated from got with Object as first argument) we don't have port now. :(

May be it worth trying to replace `url.format` with some module?

**Comment by julien-f** [comment]
It's because `host` is `${hostname}:`${port}`, therefore it takes precedence.

**Comment by sindresorhus** [comment]
> It seems that http(s).request(url) uses url.path while urlLib.format(url) uses url.pathname.

Should we maybe open an issue on iojs? Seems like that should be consistent.
