### ISSUE TITLE
How to do relative redirect? 

### ISSUE THREAD

**Issue by scheung38** [sindresorhus/got#725]
Given https://website.com/homepage

If a 302 is detected from NGINX server

then temporarily redirects to 

https://website.com/homepage/sales

**Comment by szmarczak** [comment]
It follows the provided URL automatically unless you set `followRedirect` to `false`.

**Comment by scheung38** [comment]
Hi @szmarczak, could you give simple example

**Comment by szmarczak** [comment]
Could you fill the issue template first? It will help us better understand the problem you're facing.

There are many examples in the documentation.
