### ISSUE TITLE
redirect based on dynamically generated location 

### ISSUE THREAD

**Issue by scheung38** [sindresorhus/got#726]
given url: https:www.example.com/api/service/search

and that the NGINX returns 302 along with: 

statusCode: 302,
  statusMessage: 'Found',
  headers:
   { server: 'nginx/1.12.1',
     date: 'Tue, 05 Feb 2018 23:26:07 GMT',
     'content-type': 'text/html',
     'content-length': '0',
     connection: 'close',
     location: 'https://www.example.com/api/<dynamically generated value>/service/search',
     'x-request-id-ap': '8695e3150ece179618c2scscdsdvsdv' },
  body: '' }

How to redirect based on the location value as part of the catch block as got treats 302 in the catch portion of try/catch 

redirects example:

https://www.example.com/api/XA/service/search
https://www.example.com/api/LX/service/search etc

Code so far:

```
async() => {
  const redirects = []
  const headers = {
    "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJ...",
    "cache-control": "no-cache",  
  }
 const = url: https:www.example.com/api/service/search
try {
const { request } = await got(url,

      {
        method: 'POST',
        json:false,
        headers: {
          'content-type': 'text/html', 
        },
        body: JSON.stringify(headers)
      }
    )
    const response = await request
    return JSON.stringify(response)

  } catch (error) {
    throw error
  } 
```

or within the catch block make another got call?
```
try {
  const { test } = await got(error.headers.location)
}

```
?
But if doing this then I will have a try/catch surrounding second got call inside the first catch block???

**Comment by sholladay** [comment]
`got` automatically follows redirects:

https://github.com/sindresorhus/got#followredirect

You don't have to write any code to make it do this. Just point `got` at a URL and it will make another request to the `location` before returning the result. If `got` is throwing, the final destination URL may be responding with an error code - it's not because of the redirect.

I also want to point out that this code is pointless:

```js
catch (error) {
    throw error
}
```

You should remove the `try` / `catch`.

**Comment by szmarczak** [comment]
I see now. You're trying to redirect on a POST request. From the source code:

```js
const getMethodRedirectCodes = new Set([300, 301, 302, 303, 304, 305, 307, 308]);
const allMethodRedirectCodes = new Set([300, 303, 307, 308]);
```

As you can see, 302 is accepted only for GET methods... You need to catch the error and make another request manually.

**Comment by scheung38** [comment]
Hi @szmarczak, so @sholladay was in incorrect? as I am redirecting from a POST so you confirming that I need to manually redirect via the catch block? Whereas @sholladay is correct if initial request was a GET?

**Comment by szmarczak** [comment]
They're both right. @sholladay just forgot to mention that 302 will throw on POST.

> here mentions the subsequent redirect will be a GET, even if I make manual redirect in POST, meaning initial POST with a 302 response, and manually making another POST on the redirected URL, got will turn that into GET?

No, he hasn't said anything like that.

See [my comment](https://github.com/sindresorhus/got/issues/726#issuecomment-460968149) for the solution.

**Comment by scheung38** [comment]
@szmarczak but NGINX server is only providing 302 after a POST which I like to redirect, it currently does not provide any other 3xx, so you solution is to ask API NGINX to throw one of

, 303, 307, 308]); ? instead of 302?

**Comment by szmarczak** [comment]
@scheung38 

> You need to catch the error and make another request manually.

**Comment by scheung38** [comment]
Yes that is what I did, within the catch block of got I made another POST got call but it is 415 Media Format Not Found which I suspect there is no API POST available from NGINX server, so changing from providing 302 to 303, if it is easy to do so, will fix this to 200 success?

**Comment by szmarczak** [comment]
> will fix this to 200 success

If you did handle the redirection right, then no.

> there is no API POST available from NGINX server

Then why do you make a POST request?

**Comment by scheung38** [comment]
Was given that, from POST -> redirect and then use got to catch this location and make another POST.

**Comment by szmarczak** [comment]
> Was given that, from POST -> redirect and then use got to catch this location and make another POST.

No. It's in the following way:
1. Make a POST request
2. Catch the error.
3. Manually make another request - it should be a GET request.

**Comment by scheung38** [comment]
What if 3. is another POST request? Then will be a 415 ? Since access 3 directly I get 200?

**Comment by szmarczak** [comment]
> I am making a successful POST with a direct request to my redirected URL with 200, but getting 415 statusCode if accessing it via a redirect

Sorry, but this sentence makes no sense. Can you explain?

**Comment by scheung38** [comment]
@szmarczak 

Post URL A -> 302 redirect caught in error -> Post URL B (415 status code)
Post URL B -> 200

URL B is having different status code depending on how it was accessed.

Does that make sense? Thanks

**Comment by szmarczak** [comment]
Why do you make POST B twice?

>  Is it because GOT cannot handle this flow

No, Got handles everything according to the spec. You must have done something wrong...

**Comment by scheung38** [comment]
But you can confirm this flow of manually catching second redirect works or not?

Post URL A -> 302 redirect caught in error -> Post URL B

**Comment by szmarczak** [comment]
> But you can confirm this flow of manually catching second redirect works or not?

Making another request (a.k.a. manual redirect) works. If for you it doesn't, that means you did something wrong.
