### ISSUE TITLE
Cannot redirect after adding caching option

### ISSUE THREAD

**Issue by scheung38** [sindresorhus/got#728]
#### Describe the bug

 - Node.js version: v11.6.0
 - OS & version: Mac OSX

After adding caching via

```
const QuickLRU = require('quick-lru')
const storageAdapter = new QuickLRU({maxSize: 1000})
options.cache = {cache: storageAdapter}

const {request} = await got(url, options)
```

with output log

`cache: { cache: [QuickLRU], namespace: 'cacheable-request' },
`

and noticed much faster response before making the actual redirect, but as soon as redirect logic is implemented

`
CacheError: store.get is not a function

TypeError: Cannot read property of 'location' undefined
`...

**Comment by szmarczak** [comment]
```diff
-options.cache = {cache: storageAdapter}
+options.cache = storageAdapter
```
