### ISSUE TITLE
Unable to resolve module 'stream' from 'as-stream.js'

### ISSUE THREAD

**Issue by Bradzer** [sindresorhus/got#733]
#### Describe the bug

 - Node.js version: v10.15.0
 - OS & version: Linux Mint 19.1 Tessa

#### Actual behavior

`error: bundling failed: Error: Unable to resolve module `stream` from `<project_directory>/node_modules/got/source/as-stream.js`: Module `stream` does not exist in the Haste module map`

#### Expected behavior

Not a build fail.

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
This sounds like a Jest bug and should be reported on the Jest issue tracker.
