### ISSUE TITLE
Update README/comparison on http2 and lib size on the client

### ISSUE THREAD

**Issue by desmap** [sindresorhus/got#735]
The comparison with other request libs in the README is super helpful but I'd love to see more info on http/2: Currently there's a question mark, either make it a green check or a red cross (guess it's still not properly avail, right?); why I think this is crucial in 2019: with http/2's speed REST APIs get so fast again that nobody need GraphQL anymore, kidding, but a REST API on http/2 makes really a difference

**Comment by szmarczak** [comment]
It's still in development. See #167
