### ISSUE TITLE
options.method is not set to POST when using options.json

### ISSUE THREAD

**Issue by olistic** [sindresorhus/got#736]
#### Describe the bug

 - Node.js version: 11.7.0
 - OS & version: macOS 10.14.2

#### Actual behavior

If `options.body` is set and `options.method` is not, the latter will be set to `'POST'`, as documented [here](https://github.com/sindresorhus/got/tree/cd1235105423d110f1bb668e05dba16182be4fce#body). However, the same does not occur when `options.json` is set.

#### Expected behavior

`options.method` is set to `'POST'` when `options.json` is set.

#### Code to reproduce

```js
got(url, {
  json: {
    foo: 42,
  },
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
> If `options.body` is set and `options.method` is not, the latter will be set to `'POST'`, as documented [here](https://github.com/sindresorhus/got/tree/cd1235105423d110f1bb668e05dba16182be4fce#body).

We plan to change this to throw instead for this, see: https://github.com/sindresorhus/got/issues/639#issuecomment-455042713. It's better to be explicit about your intention. As Got has become more mature, we're trying hard to remove implicit behavior.

So I think we should do the same for `json`, throw a user-friendly error message.
