### ISSUE TITLE
Feature request: synchronous requests

### ISSUE THREAD

**Issue by capaj** [sindresorhus/got#739]
#### What problem are you trying to solve?
just having bad day with ec2

#### Describe the feature
it could perform the request synchronously
...

possible useage is for example when fetching ec2-metadata from `'http://169.254.169.254/latest/meta-data/'`. I want that call to block as I need the instance ID for identifying instance and I need it synchronously when I initialize a DB connection for example

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Use async function with `await` instead. This is not the right way to use blocking I/O.

**Comment by szmarczak** [comment]
Also, you can't create a blocking function in Node, so this is not the right place to make an issue.

**Comment by capaj** [comment]
@szmarczak that's not true-see: https://github.com/ForbesLindesay/sync-request

also I am aware of async/await. I write async functions every day. But I also came across a usecase where I need to fetch something synchronously.
I would be okay if you told me that it is out of scope of this project. Instead you first assume I don't know promises, then you assume it can't be done. Wrong on both accounts.
I will assume it is out of scope for got and maybe if I have some spare time I'll wrap it in https://github.com/ForbesLindesay/sync-rpc myself and publish it as `got-synchronous` or something.

**Comment by jasonkuhrt** [comment]
I would like to see this happen. I just ditched this library because it doesn't have this. There are use-cases. Mine is that were writing some test utilities to a mock api service thing (similar to https://github.com/octokit/fixtures-server) and we have no interest in dragging async into our tests for this.
