### ISSUE TITLE
error event

### ISSUE THREAD

**Issue by maxogden** [sindresorhus/got#74]
i see this in the code https://github.com/sindresorhus/got/blob/41d147baaf395025025bfd4ec639c4a22a0a7b5e/index.js#L76

but its not in the README, just wanted to double check that it should be documented. if so, im happy to send a PR adding docs

**Comment by kevva** [comment]
Might be worth documenting, even though the `error` event is kinda standardized when using streams.

**Comment by maxogden** [comment]
its standardized but 90% of people (my own estimate) don't handle errors in streams correctly :)

**Comment by floatdrop** [comment]
@maxogden yup, since this not quite standard error event (multiple arguments) - it should be in docs. :+1:
