### ISSUE TITLE
⭐ Add a `success` property

### ISSUE THREAD

**Issue by DRSDavidSoft** [sindresorhus/got#745]
#### What problem are you trying to solve?
If I set `throwHttpErrors` to false, there is no way to differentiate a successful request with an erroneous one, other than manually comparing `statusCode === 304 || ( statusCode >= 200 && statusCode < 300)`.

In other words, redefining part of the got core.

#### Describe the feature
I propose adding a new `success: boolean` property in order to quickly check for a successful request:

```javascript
(async () => {
	const response = await got('https://sindresorhus.com', {throwHttpErrors: false});
	if (response.success) {
		console.log(response.body);
		//=> '<!doctype html> ...'
	} else {
		console.log(response.statusCode);
		//=> '403'
	}
})();
```

### Suggested implementation
- Wherever the Promise is going to be `reject`ed, set `success` to false
- Otherwise, set it to `true`
    - Addendum: unless **(** the body is empty **&&** `statusCode` is not 204 **)**,  
       in which case set it to `false`

### Scope example
https://github.com/sindresorhus/got/blob/ed0400414ccfc5fa0e7572404b3644c66a8a04ba/source/as-promise.ts#L89-L102

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Why do you need it? What's the use case?

**Comment by DRSDavidSoft** [comment]
Basically the same reason as why we use `then` and `catch` as separate methods.

As to why I am not doing `throwHttpErrors` instead, this is my logic:

<sup>Sorry for the long comment ahead</sup>

1. Consider that we have `main.js` and `api-client.js`.  The latter uses `got` in order to perform some actions, e.g.:

```javascript
async function login(username, password) { ... }
async function create post(title, body) { ... }
async function doSomethingElse() { ... }
```

2. I'll first need to call `login(..., ...)` from `main.js` and await its response.

3. Possible outcomes for this special website are:
   1. The login is successful, I return with a success and then call the other methods
   2. The attempt was rejected by the endpoint, I'll return an `errorMessage` with the corresponding error from the endpoint
   3. got was unavailable to reach the endpoint, e.g. due to a network connectivity problem, or a reverse proxy blocking my request (e.g. CloudFlare, perimeterX, etc, which would return a 403 error), or simply a 503 error by the endpoint itself

Now, by the design of my logic, I am _expecting_ the http request to _either_ succeed, or fail; so throwing an `exception` for a non 200 status code really isn't valid here. (If something else beside the http request itself fails, it'll unexpected and hence should throw an exception for me.)

The flow in case of outcomes 1 and 2 is clear - we simply parse and pass the resolved content.

In the case of outcome 3 however, it's not appropriate for my code to throw an exception here. What I need is to still parse the body (imagine when a rejected authentication request is `403`ed from the server with a clear error message in the body (e.g. "<p>Login error!</p>"))
 -- then inspect the statusCode for the corresponding action.

Now I understand that this can be simply done via a `catch` statement instead, but it messes the follow of my code.

Remember, the same series of actions (often conditionally) need to be applied to the result in _both_ scenarios. Not possible to do so, unless I repeat myself. (WET not DRY)

The only ways that I can achieve this (besides the aforementioned method in the first comment), is to either wrap got in another caller function (which I'd like to avoid), or ask you to add this rather small edit.

And since a) currently, without disabling `throwHttpErrors`, this is relatively easy to differentiate and b) the proposed `success` property will fill the `reject` gap rather nicely for no-throw mode, I think this will be useful to implement.

I know this may not be a standard for say a non-REST json-based api (e.g. `/getWeatherInfo`), because the author will be NOT expecting a non-200 status code -- and it should throw out of the function / method on a fail like this.

I hope this all makes sense and I'm not unclear. :)

**Comment by szmarczak** [comment]
While I do understand the `promise.then(...).catch(...)` part, I don't quite see where you can't use `throwHttpErrors: false` and verify the error manually, like you have suggested it in the beginning.

**Comment by DRSDavidSoft** [comment]
@szmarczak I can. However, the purpose of this suggestion is to implement a counterpart to the `reject(...)`, _without_ repeating part of `got` in the user side:
```javascript
const success = statusCode === 304 || ( statusCode >= 200 && statusCode < 300);
```

n.b. this has to be written for _every_ got request.

I am suggesting that it'd be easier to use a `success` property instead -- that should be equal to a successful request performed.

**Comment by szmarczak** [comment]
@DRSDavidSoft I have encountered that some APIs provide JSON `error` key with proper value if something went wrong. It would be much easier to use `throwHttpErrors: false` and provide own `success` variable like you have done.

@sindresorhus What do you think about this?

**Comment by DRSDavidSoft** [comment]
@szmarczak I did not quite understand, do you think supporting `success` is a good idea, or do you think APIs should provide their own `error` field?

In the case of latter, the issue is that an API can return any key _independent_ of the `statusCode` (e.g. lack of `error` does not necessarily result in a `200 OK`)

In addition to that, reverse-proxies (like cloudflare) could break a JSON API. Furthermore, we might not even be dealing with a REST API (e.g. using `got` to scrape a webpage)

**Comment by szmarczak** [comment]
> I did not quite understand, do you think supporting success is a good idea, or do you think APIs should provide their own error field?

IMO that's bad idea.

> In addition to that, reverse-proxies (like cloudflare) could break a JSON API.

Then you need to catch the JSON parse error.

**Comment by DRSDavidSoft** [comment]
- May I ask the reson, why do you think it's a bad idea?

- What about the third situation?
   > we might not even be dealing with a REST API (e.g. using `got` to scrape a webpage)

   e.g. not a JSON-based API

**Comment by szmarczak** [comment]
> May I ask the reson, why do you think it's a bad idea?

The proper way is to use `promise.then(loginSuccess).catch(loginFailure)`. Otherwise you want to manually verify the response. If you get duplicated code this way you need to split the code to parts. Example:

```js
promise.then(response => {
	...
	finishLogin(response);
}).catch(error => {
	...
	finishLogin(error);
});
```

Problem solved.

There is no point in having duplicated ways to do the same thing.
