### ISSUE TITLE
Stream `fromCache` property

### ISSUE THREAD

**Issue by stvvt** [sindresorhus/got#747]
I need to `pipe()` the downloaded response for further processing (unzipping), but only when the response is not from cache. However, when using `got.stream()`, I can't figure out how to check where the response comes from - origin or cache.

```js
...
const response = got.stream(originUrl, { cache }); 
const fromCache = ...; // How to set this
if (fromCache) {
  response.pipe(unzip). ...
}
```
I've also tried
```js
const response = await got(originUrl, { cache });

if (response.fromCache) { // Here cache check is ok
  response.pipe(unzip). ...
}
```
but in this case response stream is already consumed.

Thanks

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
> I need to pipe() the downloaded response for further processing (unzipping), but only when the response is not from cache.

Why won't you use the `decompress` option?

**Comment by stvvt** [comment]
> Why won't you use the decompress option?

Maybe I should have been more specific regarding the use case: I need to regularly download a ZIP archive and unzip it. But the unzipping should take place only when the ZIP archive doesn't come from cache.

**Comment by szmarczak** [comment]
Ah, that makes sense...
