### ISSUE TITLE
Got returning response before retries

### ISSUE THREAD

**Issue by gonejack** [sindresorhus/got#748]
#### Describe the bug

 - Node.js version:  v11.3.0
 - OS & version: MacOs v11.3.0

#### Actual behavior

got return response before retry

```
[Downloaded] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
[Retry] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
[Retry] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
[Retry] http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg
```

#### Expected behavior

got should do all retries before returning response

#### Code to reproduce

```
const got = require('got');
const fs = require('fs');

async function test() {
    const url = 'http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg';
    const resp = await got(url, {
        timeout: {
            request: 1e3,
        },
        retry: 3,
        hooks: {
            beforeRetry: [(opt, err, retryN) => {
                console.log("[Retry]", opt.href)
            }]
        }
    });

    console.log('[Downloaded]', url);

    fs.createWriteStream('img').write(resp.body)
}

test();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I couldn't reproduce it: https://runkit.com/szmarczak/5c85717524f42b0012ace6c6
Could you provide another example please?

I will see if such bug is even possible to happen tomorrow.

**Comment by gonejack** [comment]
@szmarczak It could happens in possibility, especially in bad network connection and larger file: https://runkit.com/gonejack/5c85aa5cc72b580012f83021

![image](https://user-images.githubusercontent.com/2720676/54093874-669b6380-43d7-11e9-8311-86fb85b166c9.png)

**Comment by szmarczak** [comment]
Thanks for the code! It really helps. I'll try to fix this ASAP.

**Comment by szmarczak** [comment]
```
error
aborting
Cancelling
Cancelling
[Downloaded] 27404
{ start: 1554202147585,
  socket: 1554202147589,
  lookup: 1554202147757,
  connect: 1554202148089,
  upload: 1554202148089,
  response: 1554202148557,
  end: 1554202148843,
  error: 1554202148840,
  phases:
   { wait: 4,
     dns: 168,
     tcp: 332,
     request: 0,
     firstByte: 468,
     download: 286,
     total: 1258 } }
[Retry] TimeoutError: Timeout awaiting 'request' for 1000ms
```

Looks like the request isn't canceled.

**Comment by szmarczak** [comment]
```
const http = require('http');
const req = http.get('http://ipv4.download.thinkbroadband.com/1GB.zip');
req.once('response', response => {
    response.once('end', () => console.log('END'));
    setTimeout(() => req.abort(), 1000);
});
```

it logs:

```
END
```

We don't currently throw on incomplete response. That's the reason.
