### ISSUE TITLE
event for 'final' redirect

### ISSUE THREAD

**Issue by maxogden** [sindresorhus/got#75]
im porting some request code over that looks like this

```
req.on('response', handle)
```

in request, `handle` gets called when the 'final' redirect gets called, so e.g. if the first response was actually a 302, and the 2nd one is the a 200, only the 200 response will be emitted as the `response` event.

in got, `response` is emitted each time their is a response, because if [this line](https://github.com/sindresorhus/got/blob/41d147baaf395025025bfd4ec639c4a22a0a7b5e/index.js#L124) is truthy multiple times, the recursive call in there causes it to emit many times

the problem I have is that I only care about the last response, but there doesn't seem to be an event for that, but maybe i'm missing something!

**Comment by maxogden** [comment]
BTW my workaround is currently

```
var isRedirect = require('is-redirect')
request.on('response', function(res) {
  if (isRedirect(res.statusCode)) return // hack for https://github.com/sindresorhus/got/issues/75
  // handle final response here
}
```

**Comment by floatdrop** [comment]
Since `got` already have `redirect` event - may be it make sense to emit `response` on 'non-redirect' responses.

**Comment by maxogden** [comment]
@floatdrop +1 to that idea!
