### ISSUE TITLE
method POST not working

### ISSUE THREAD

**Issue by kalitine** [sindresorhus/got#750]
#### Describe the bug

 - Node.js version: v11.10.1
 - OS & version: Ubuntu 18.10
 - got version: 9.6.0

#### Actual behavior
When setting `method: 'POST'` attribute of `got` function options still making a GET request. However calling `got.post` method instead with exactly the same parameters results into a POST request.

#### Expected behavior
Making a POST instead of a GET request.

#### Code to reproduce

```js
got(url, {
      baseUrl: MY_URL,
      body: { text: MY_BODY_TEXT },
      headers: {
        'Content-type': 'application/json',
        'Ocp-Apim-Subscription-Key': MY_KEY_VALUE,
        'X-ClientTraceId': MY_ID_VALUE
      },
      json: true,
      method: 'POST',
      query: new URLSearchParams([[MY_QUERY]])
    }).then(({ body }) => body)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you make a [Runkit](https://runkit.com/szmarczak/5c8cc677cb8f3600126b44a1) snippet demonstrating the issue? I can't reproduce it.

**Comment by kalitine** [comment]
After a further investigation, I found that it was my fault. I was importing `got` like this:
```
import { get } from 'got'
```
So no surprising that I was doing a GET request. Sorry for the issue, I thought that I paied attention to everything.
