### ISSUE TITLE
POST is retrying after 120 seconds of no response - even with no timeout and retries: 0

### ISSUE THREAD

**Issue by lostpebble** [sindresorhus/got#751]
#### Describe the bug

 - Node.js version: 10.15.1
 - OS & version: Windows 10
#### Actual behavior

```typescript
const response = await got(blueprint.endpoint, {
        method: "POST",
        retries: 0,
        body: payload,
        headers: {
          "Content-Type": blueprint.payloadType === ECronJobPayloadType.TEXT ? "text/plain" : "application/json",
        }
      });
```

I'm busy making POST request like above. I'm expecting some of these requests to take a really long time (some might take 5 mins or so maybe). But since these are cron jobs - I also never want to run these tasks twice as these are very big processing jobs at times.

It seems though that got is retrying this POST request when it takes longer than 120 seconds:

(These are the logs from the server receiving this POST request, the url being hit is `/_api/test/cron-slow`)

```
14:47:36.714 index.js:52   <-- POST /_api/test/cron-slow
14:47:36.716 ApiTestRouter.ts:19 [BSIXrUOHcr6LrL2MGN4T5] Running really slow endpoint test (180 seconds)
14:49:37.802 index.js:52   <-- POST /_api/test/cron-slow
14:49:37.804 ApiTestRouter.ts:19 [Y4keM5cn01IHpztRESovg] Running really slow endpoint test (180 seconds)
```

You can see that at almost exactly 2 minutes, the request is being retried again.

#### Expected behavior

It should never run twice - as I've not specified a timeout and I've deliberately set `retries: 0`.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by lostpebble** [comment]
So, it appears that this issue might be outside of the control of `got`.

I had to increase the timeout for my entire Node.js server here: https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback

And now I can run the request for as long as that allows.

**Comment by lostpebble** [comment]
But this has now lead me to another problem after running some more tests. When I deliberately set a timeout, the requests are still retrying even though I've set `retries: 0`.

Here I've set `timeout: 1000` on the POST request:

```
const response = await got(blueprint.endpoint, {
        method: "POST",
        retries: 0,
        timeout: 1000,
        body: payload,
        headers: {
          "Content-Type": blueprint.payloadType === ECronJobPayloadType.TEXT ? "text/plain" : "application/json",
        }
      });
```

And this is what the receiving server logs look like now (3 requests received before it decided to stop retrying):

```
16:38:55.195 index.js:52   <-- POST /_api/test/cron-slow
16:38:55.197 ApiTestRouter.ts:19 [t4atGMyKA7BLWIZyLP5_K] Running really slow endpoint test (120 seconds)
16:38:57.214 index.js:52   <-- POST /_api/test/cron-slow
16:38:57.216 ApiTestRouter.ts:19 [nkuXOlQ-JIHUs9xmWdQuM] Running really slow endpoint test (120 seconds)
16:39:00.250 index.js:52   <-- POST /_api/test/cron-slow
16:39:00.252 ApiTestRouter.ts:19 [g6R4PD-0e9E3SBfN42zvL] Running really slow endpoint test (120 seconds)
```

**Comment by lostpebble** [comment]
Okay, I think I've managed to solve the retry issue now. I was using `retries` because I saw it somewhere in an issue before and TypeScript complains if I try use `retry` as an option. BUT it seems that the correct option is `retry`, like so:

```typescript
const response = await got(blueprint.endpoint, {
        method: "POST",
        // @ts-ignore
        retry: 0,
        timeout: blueprint.endpointTimeout || TimeUtils.CalculateMillis.minutesInMillis(2),
        body: payload,
        headers: {
          "Content-Type": blueprint.payloadType === ECronJobPayloadType.TEXT ? "text/plain" : "application/json",
        }
      });
```

**Comment by szmarczak** [comment]
Can you add some `beforeRetry` hook and log the event to see if it really retries?

**Comment by lostpebble** [comment]
It was definitely re-retrying - although it seems like it was Node.js itself forcing the retry because of the default server settings (120 seconds timeout). All in all doesn't seem like the problem is on `got`'s side for the original retry problem as its working fine now after upping the server's timeout settings. It might be useful to have some information about this in the docs though.

**Comment by lostpebble** [comment]
@szmarczak I'll close this issue as it appears to be resolved on my side. I do think that there should be mention in the docs that **Node.js has a default timeout of 120 seconds** which you need to increase to prevent timeouts as well.

**Comment by szmarczak** [comment]
This has happened also on https://travis-ci.org/sindresorhus/got/jobs/506835639

```
  retry › can be disabled with option
  /home/travis/build/sindresorhus/got/test/retry.js:96
   95:   t.truthy(error);
   96:   t.is(trys, 1);  
   97: });               
  Difference:
  - 0
  + 1
```

Gonna check now.
