### ISSUE TITLE
Handle HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by joh-klein** [sindresorhus/got#752]
I have an issue with a server request, that answers with an `HPE_INVALID_CONSTANT` in the end. I already filed a bug report with the provider of that service and they are looking into it – but that will take time (weeks if not months) and I need that data in the meantime. What I am doing right now is this:

```js
return new Promise((resolve, reject) => {
  let body = '';

  https
    .get(url, res => {
      res.on('data', chunk => {
        body += chunk;
      });
      res.on('end', () => {
        return resolve(body);
      });
    })
    .on('error', err => {
      if (body && err.code === 'HPE_INVALID_CONSTANT') {
        resolve(body);
      } else {
        console.log('Got error: ' + err.code);
        reject(err);
      }
    });
});
```

This is working quite OK – what I am wondering is: could I do the same with got? I am in the middle of moving all my http needs to got, so this would be awesome.

BTW: this particular request works with curl ONLY if I set it explicitly to `--http1.1` – I have given up on doing that with nodejs, though. I can't find a way.

**Comment by sindresorhus** [comment]
You might be able to handle in a `beforeError` hook: https://github.com/sindresorhus/got#hooksbeforeerror

**Comment by joh-klein** [comment]
Thanks for your quick reply! 
If I add the hook, I am at the place, where `err.code === 'HPE_INVALID_CONSTANT'` but I don't have access to the data that was transmitted until then – or do I? And if so, where/how?

**Comment by joh-klein** [comment]
I guess, what I am asking is: is there something similar to this construct from node.http(s)?
```js
res.on('data', chunk => {
  body += chunk;
});
```

**Comment by joh-klein** [comment]
To answer my own question, this does the same as my initial way with `https()`.

```js
return new Promise((resolve, reject) => {
  let body = '';

  got
    .stream(url)
    .on('data', chunk => {
      body += chunk;
    })
    .on('end', () => {
      return resolve(body);
    })
    .on('error', err => {
      if (body && err.code === 'HPE_INVALID_CONSTANT') {
        return resolve(body);
      } else {
        console.log('Got error: ' + err.message);
        reject(err);
      }
    });
});
```

**Comment by szmarczak** [comment]
> Maybe add http/https to your migration guide?

I don't think we need to - `http`/`https` is very low level, almost no one uses it (also it's not a good start). It provides very few features.

@sindresorhus What's your thoughts?

**Comment by sindresorhus** [comment]
Nah
