### ISSUE TITLE
Retries: Default errorCodes do not retry on POST for undefined code

### ISSUE THREAD

**Issue by freenerd** [sindresorhus/got#757]
#### What would you like to discuss?

First of all: thanks for creating `got` 😄 

I've been trying to wrap my head around retries and I think I found and an inconsistency between `GET` and `POST`'s handling of retries. Below code doesn't retry on `POST` but if the method is changed to `GET` it works:

```
const got = require('got');
const http = require('http');

async function run() {
    let serverCallCount = 0;
    const requestHandler = (request, response) => {
      serverCallCount += 1;
      response.statusCode = serverCallCount < 2 ? 502 : 200;
        response.end('hello');
    };
    const server = http.createServer(requestHandler);
    await server.listen(3000);

    const resp = await got('http://localhost:3000/', {
        method: 'POST',
        retry: {
            retries: 3
        }
    });
    server.close();
    console.log(resp.body);
}

run();
```

- `got: 9.6.0`
- `node: 8.15.1`

Here is a runkit showing the behaviour in more detail comparing different methods and errorCode configurations. Note that `POST` retries if `errorCodes: [ undefined ]`.

https://runkit.com/freenerd/5c90c38c8b16460012ae5e53

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
You haven't read the documentation:

> methods: `GET` `PUT` `HEAD` `DELETE` `OPTIONS` `TRACE`

It doesn't retry on POST methods.

**Comment by freenerd** [comment]
Thanks @szmarczak. I did read the documentation (as well as the retry test suite and the retry code) but just missed POST missing from the allowed methods in the default.

I still can't explain why `POST` retries on `errorCodes: [ undefined ]` though, but I guess it doesn't matter much.

For everyone else landing here, explicitly allowing POST to be retried is the solution.

```
    const resp = await got('http://localhost:3000/', {
        method: 'POST',
        retry: {
            methods: ['POST'],
            retries: 3
        }
    });
```
