### ISSUE TITLE
http digest auth

### ISSUE THREAD

**Issue by simone-sanfratello** [sindresorhus/got#762]
#### What problem are you trying to solve?

Hi, I'd like to write a porting of https://github.com/simme/node-http-digest-client to provide digest authentication, would you like to add this feature to the project? I'd like to be helped adding the feature to current options/API keeping consistency/compatibility.

#### Describe the feature

https://www.google.com/search?q=HTTP+digest+auth

```js
  const response = await got('http://some-auth-url.com', {
    // ... options
    auth: {type: 'digest', username: 'a-username', password: 'a-password'}
  })
```

my current workaround

```js
  let response
  try {
    await got('http://some-auth-url.com', {
      // ... options - NB no auth
    })
  } catch (error) {
    if (error.statusCode !== 401) {
      throw error
    }
    response = error
  }
  const headers = {
    ...options.headers,
    Authorization: calculateDigestAuthHeader(response.headers['www-authenticate'], username, password)
  }
  response = await got('http://some-auth-url.com', {
    headers
    // ... options
  })

```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
It's not something we want in Got, but it should be possible to use `got.create()` and hooks to achieve this. You can then use `got.mergeInstances()` whenever you need it. Let us know if there are any missing hooks that you need.

We plan to work on a better way to add plugins to Got, but for now, using `got.mergeInstances()` is pretty straight forward.

https://github.com/sindresorhus/got/blob/master/advanced-creation.md

**Comment by simone-sanfratello** [comment]
yep, got it, thank you!

**Comment by yovanoc** [comment]
Sorry to up this one, but I don't find any hook suitable for this, we can't access headers in the afterResponse one

**Comment by szmarczak** [comment]
@yovanoc You can.

**Comment by yovanoc** [comment]
Oups mb, not headers, I mean options, original options passed to the request

**Comment by szmarczak** [comment]
@yovanoc Perhaps `response.request.options` ?

**Comment by yovanoc** [comment]
Oh really sorry I didn't know that.

**Comment by szmarczak** [comment]
[It's in the docs.](https://github.com/sindresorhus/got#response)

**Comment by nirsnappy** [comment]
@yovanoc any chance to share your implementation ?

**Comment by yovanoc** [comment]
> @yovanoc any chance to share your implementation ?

You have it here: https://github.com/vMReal/digest-auth/issues/8
