### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_CERTIFICATE 

### ISSUE THREAD

**Issue by Mohhay** [sindresorhus/got#770]
#### UNABLE_TO_VERIFY_LEAF_CERTIFICATE ?

Hello, ive had this problem lately, and i can't solve it. Could someone help me? Its error: UNABLE_TO_VERIFY_LEAF_CERTIFICATE . If someone knows how to fix it, then i beg you to help me. PLEASE HELP ME. Ive had this problem for 3 days. Im trying to make a discord bot, thats why i need help with this, when im trying to use the command: npm install discord.js --save, it says error: UNABLE_TO_VERIFY_LEAF_CERTIFICATE . Please someone help me with this stupid error. :(

#### Checklist

I can't find a fix for this. Ive looked everywhere. Tried everything, the only thing thati have not tried is to make a discussion at github.com. This is my last try, please help me. :(

**Comment by szmarczak** [comment]
That means that the server has invalid SSL certificate. Either you need a valid SSL certificate or set `rejectUnauthorized` option to `false`.

**Comment by szmarczak** [comment]
> when im trying to use the command: npm install discord.js --save

Oh, it's not a Got error. Perhaps you want to make an issue at https://github.com/discordjs/discord.js/

**Comment by szmarczak** [comment]
Please don't make issues not related with Got in the future. This is not the right place.

**Comment by ESLRetr0** [comment]
Try:

npm config set registry https://registry.npmjs.org/ --global

Let me know if that works!
