### ISSUE TITLE
How to get headers only?

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#771]
I want to make a request, read headers, follow redirects if such occur, but do not download the body.

The use case is to expand shortened URLs.

Sometimes shortened URLs can link to large files.

I guess this requires a `resolveHeadersOnly` option.

**Comment by sindresorhus** [comment]
Can you do a `HEAD` request? That would not fetch the body.

**Comment by gajus** [comment]
That was the first thing I tried.

Unfortunately, some URLs return "Method Not Allowed" when you do `HEAD` request.

**Comment by gajus** [comment]
It is fine if whatever the approach would download _some_ of the body. I just want to make sure that I don't end up downloading some random 1GB zip files.

**Comment by szmarczak** [comment]
```js
got.stream('http://gcr.io/').on('response', response => {
    console.log(response.headers);
}).resume();
```

It will download the file, but will not save it. It's gonna be removed immediately.

**Comment by gajus** [comment]
Good suggestion, but unfortunately this would be a huge waste of bandwidth, esp. at a scale that I am doing this.

**Comment by szmarczak** [comment]
> unfortunately this would be a huge waste of bandwidth

So you do not want do download data. In other words you don't want to keep the connection, that means you want to cancel the request:

```js
const getHeaders = () => new Promise((resolve, reject) => {
    const promise = got('http://gcr.io/').on('response', response => {
        resolve(response.headers);
        promise.cancel();
    });
    
    promise.then(response => resolve(response.headers)).catch(reject);
});

(async () => {
    console.log(await getHeaders());
})();
```

I hope this solves your problem :)
