### ISSUE TITLE
Retry timeout

### ISSUE THREAD

**Issue by frux** [sindresorhus/got#779]
#### What would you like to discuss?

I need to make a request to the API which sometimes answers veeeery slowly or doesn't answer at all and then I have to try once again. So I need to wait for 1 second and if it doesn't answer I try it once again. But now I can limit only a whole request time and got will waist all the timeout on one try :(

Example of the way I wont it to work:

```js
got('http://httpstat.us/200?sleep=3000', {
    timeout: {
        request: 5000,
        requestTry: 1000
    },
    retries: 5
})
```
I expect that got will make a request with timeout 1000ms and will retry it for five times within 5000ms.

How can I do it?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
I don't quite get it. Do you want another timeout for the whole request including retries?

**Comment by frux** [comment]
@szmarczak yes. I need timeout for one retry and separate timeout for the whole request.

**Comment by szmarczak** [comment]
Then you need to `setTimeout(() => promise.cancel(), wholeRequestTimeout)`.

@sindresorhus Should we add a global timeout for everything?

**Comment by frux** [comment]
@szmarczak I'm sorry was looking at version 8. In version 9 I can retry timeout errors. This issue seems can be closed.
