### ISSUE TITLE
`http.request` throws an error while using `global-tunnel-ng`

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#782]
#### Describe the bug

 - Node.js version: v11.14.0
 - OS & version: Debian GNU/Linux 9 (stretch)
 - Got v9.6.0

#### Actual behavior

```
RequestError: Cannot read property 'proxy' of undefined
  File "/srv/node_modules/got/source/request-as-event-emitter.js", line 236, col 15, in get
    emitError(new RequestError(error, options));
  File "/srv/node_modules/got/source/request-as-event-emitter.js", line 305, col 10, in Immediate.setImmediate
    await get(options);

```

#### Expected behavior

No error.

#### Code to reproduce

Executed with `HTTP_PROXY=` configured.

```js
import globalTunnel from 'global-tunnel-ng';

globalTunnel.initialize();

got('http://gajus.com/');

```

#### Note

I am only able to reproduce this issue in Docker. Works great on OSX.

**Comment by szmarczak** [comment]
Can you please name the issue properly? The title means nothing for now, it should be more descriptive.

Second: have you tried running it using pure `http.request`?

**Comment by gajus** [comment]
> Can you please name the issue properly? The title means nothing for now, it should be more descriptive.

The title describes the error ... This is the first thing someone would Google.

Seeing some odd behaviour not related to Got, e.g.

```js
export HTTP_PROXY=http://proxy-gateway
node -e "const globalTunnel = require('global-tunnel-ng'); console.log('a', process.env.HTTP_PROXY); globalTunnel.initialize(); console.log('b', process.env.HTTP_PROXY);"
a http://proxy-gateway
b undefined

```

**Comment by szmarczak** [comment]
This doesn't seem like a Got issue - `http.request` threw an error directly.

**Comment by gajus** [comment]
https://github.com/np-maintain/global-tunnel/issues/34

My local Node version was 10.4.
