### ISSUE TITLE
Cannot omit the "accept-encoding" header using NULL

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#785]
#### Describe the bug

 - Node.js version: v11.3.0
 - Got: v9.6.0

#### Actual behavior

Cannot omit the "accept-encoding" header using `NULL`

#### Expected behavior

According to documentation:

> Headers set to null will be omitted.

#### Code to reproduce

```js
const getLatestDevtoArticlePointers = async (tagName) => {
  const articlePointers = (await got('https://dev.to/api/articles', {
    headers: {
      'accept-encoding': null
    },
    json: true,
    query: {
      tag: tagName
    }
  })).body;

  return articlePointers.map((articlePointer) => {
    return {
      id: articlePointer.id,
      publishedAt: Date.parse(articlePointer.published_at)
    };
  });
};

```

#### Impact

Cannot use certain APIs, e.g. https://github.com/thepracticaldev/dev.to/issues/2533.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/tree/v9.6.0#decompress

> Decompress the response automatically. This will set the accept-encoding header to gzip, deflate unless you set it yourself.

If you set to `accept-encoding` to null then it's **not** set. So you need to disable `decompress` option.

**Comment by gajus** [comment]
One would still expect to be able to override it, though. At least, I would expect that to be the behaviour given the documentation:

> Headers set to null will be omitted.

**Comment by szmarczak** [comment]
It is omitted as well. But keep in mind that you have `decompress` option set to true.
Options that modify the headers are *always* executed after the normalization.

**Comment by szmarczak** [comment]
We can still make a note about that in the README though :)
