### ISSUE TITLE
Suggest to use global-agent

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#789]
#### What problem are you trying to solve?

Use of proxies with `got`.

#### Describe the feature

Currently Got documentation recommends to use `tunnel` and `global-tunnel-ng` to configure HTTP proxy.

https://github.com/sindresorhus/got/blob/c8b96aa4ff37873abcb5a76dcbf8bd5cc5afc249/readme.md#proxies

[`global-tunnel`](https://github.com/salesforce/global-tunnel) (including [`global-tunnel-ng`](https://github.com/np-maintain/global-tunnel) and [`tunnel`](https://npmjs.com/package/tunnel)) are designed to support legacy Node.js versions. They use various [workarounds](https://github.com/koichik/node-tunnel/blob/5fb2fb424788597146b7be6729006cad1cf9e9a8/lib/tunnel.js#L134-L144) and rely on [monkey-patching `http.request`, `http.get`, `https.request` and `https.get` methods](https://github.com/np-maintain/global-tunnel/blob/51413dcf0534252b5049ec213105c7063ccc6367/index.js#L302-L338).

`tunnel`/ `global-tunnel` [does not work with with Node.js v11.5+](https://github.com/np-maintain/global-tunnel/issues/34).

In contrast, `global-agent` supports only Node.js v12 and above, and works by configuring [`http.globalAgent`](https://nodejs.org/api/http.html#http_http_globalagent).

**Comment by sindresorhus** [comment]
Sure, PR welcome.

**Comment by gajus** [comment]
`global-agent` has since been updated to work with Node.js v10, improved error handling, logging and documentation.
