### ISSUE TITLE
Proxy request with streams does not work

### ISSUE THREAD

**Issue by ValeraS** [sindresorhus/got#790]
#### Describe the bug

 - Node.js version: 
 - OS & version: 

https://github.com/sindresorhus/got/blob/master/migration-guides.md#L144
documentation says
> The cool feature here is that Request can proxy headers with the stream, but Got can do that too:

but `got` does not proxy request to new url when use `got` like this:
```js
request.pipe(got.stream('https://example.com/doodle.png')).pipe(response);
```

#### Actual behavior

makes a request to URL with default headers and `get` method.

#### Expected behavior

should make a request to new URL which reflects initial request.

#### Code to reproduce

https://glitch.com/edit/#!/melodious-cabinet?path=server.js

if go to https://melodious-cabinet.glitch.me/test-got you'll get `GET` string
if go to https://melodious-cabinet.glitch.me/test-request you'll get `POST{"msg":"Hello World!"}` string

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by gajus** [comment]
What Node.js version?

This could be related to https://github.com/sindresorhus/got/issues/789.

**Comment by szmarczak** [comment]
It's `master` branch. Not available for v9.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/tree/v9.6.0
