### ISSUE TITLE
Get original request body from error

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#793]
#### What would you like to discuss?

How can I get the original request body from the error object? I can do `e.response.body` for original response body and `e.response.socket._httpMessage._header` for raw request headers.

But I can't see how to get the original **request** body and raw **response** headers (can see how to get transformed version of response headers but not raw original form). And `e.options` returns `undefined` but https://github.com/sindresorhus/got#errors says it should be there?

How can I get this info from the error object?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
I think you've missed this part of the docs:

> **This readme reflects the next major version that is currently in development. You probably want [the v9 readme](https://www.npmjs.com/package/got).**

**Comment by szmarczak** [comment]
It is there, but it's working only for master branch. Check out the v9.

**Comment by rightaway** [comment]
Thanks I see it now (maybe could put it it in red text or larger or something so people like me don't waste your time with non issues).

I still can't see how to get original **request** body and raw **response** headers from `e` object, that isn't something discussed in the documentation for any version. Could you say how to get these?

**Comment by szmarczak** [comment]
You can access the body through `error.gotOptions.body`. You can't access the response headers in v9. Using the master branch it's possible. Note the master branch is not stable. It's under development.

**Comment by rightaway** [comment]
I just tried it in v9, it looks like response headers are available under `error.headers`, or is that something else?

From what I'm seeing response headers and body are `error.headers` and `error.body`, and request headers and body are `error.gotOptions.headers` and `error.gotOptions.body`. Is this as you expect?

**Comment by szmarczak** [comment]
Yup.

**Comment by rightaway** [comment]
Thank you but I'm just confused because you said "You can't access the response headers in v9. Using the master branch it's possible", what did it mean?

**Comment by szmarczak** [comment]
I meant I could not find anything about it in the readme. I haven't looked at the code yet. If it's possible but the readme doesn't say anything then it should be updated. But problem solved already by exposing the `response` object as in the master branch. I believe we will release V10 soon.
