### ISSUE TITLE
Using json and form options together

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#794]
#### What would you like to discuss?

I have to do this to get the params object to be transformed into a query string and sent in the request body. It works but the documentation hints at better ways to do this.

```js
r = await got(..., {
  json: false,
  body: new URLSearchParams({ ...paramObject }).toString()
})
value = JSON.parse(r.body)
```
I can't get it to work using this, which is cleaner and seems like the proper way to do it. Shouldn't it work the same way as above? Turn the `form` into URLSearchParams string in the body and return the result as json.

```js
r = await got(..., {
  json: true,
  form: paramObject,
})
value = r.body
```

#### Checklist

- [ x] I have read the documentation.

**Comment by szmarczak** [comment]
From the v9 docs:

> #### form
> Type: `boolean`
> Default: `false`

The `form` option is not `body`. Pass URLSearchParams to `body` and set `form` to true.

@sindresorhus I think we should rename `json` -> `isJSON` and `form` -> `isForm`.

**Comment by sindresorhus** [comment]
> I think we should rename json -> isJSON and form -> isForm.

They're not boolean options anymore. Look at the readme in `master`. `form` does accept `true`, but it also accepts an object, so `isForm` would not fit.

**Comment by szmarczak** [comment]
Yeah, I forgot about that. Thanks for reminding me :P
