### ISSUE TITLE
Resuming downloads / caching

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/got#796]
#### What would you like to discuss?

I would like advice on whether `got`'s caching will automatically implement a "range" request on subsequent GETs, assuming caching is enabled.

- There is a file on a remote host that is appended to regularly
- I want to download it initially, then check for an incremental additions every 5 minutes
- Right now I do this by calling child process out to `wget --continue` and then reading the file back

The file is about 25MB in size. I don't mind keeping my own copy of it entirely in memory although I worry a little if both my application code and got cache it redundantly. My goal is just that if only 1KB gets added to it each 5 minutes then I am downloading 1KB and not ~25MB.

@lukechilds do you know? Thanks

#### Checklist

- [x] I have read the documentation.

**Comment by lukechilds** [comment]
No it won't automatically do a range request.

Maybe I'm misunderstanding something but why do you need HTTP caching if the file is regularly updated and only appended to? Can't you just make an uncached range request every 5 minutes and update your local copy if there is new data?

**Comment by rarkins** [comment]
That could also work. Are you aware of any examples? I tried a few variants of searching on "range" in this repo and didn't find anything. I suppose I should use the bytes value returned in response headers rather than trying to calculate it myself based on the response body?

**Comment by rarkins** [comment]
I will close this, as I now realise that it wouldn't make sense to automatically perform a range request when caching.

FYI I've hit another problem (ReadError: incorrect header check) when implementing range manually, but I'll raise that as a separate issue if I conclude that it's a bug.
