### ISSUE TITLE
Tests failures on macOS

### ISSUE THREAD

**Issue by mastermatt** [sindresorhus/got#799]
#### Describe the bug

```
~/src/got: git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/src/got: git rev-parse --short HEAD
dfb46ad
~/src/got: node --version
v10.15.3
~/src/got: npm --version
6.9.0
~/src/got: sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
~/src/got: npm t
...
  4 tests failed
  1 known failure
  2 tests skipped
...
```
Failing tests, in all cases the promises resolve:
 - `unix-socket.ts › throws on invalid URL` 
 - `timeout.ts › secureConnect timeout`
 - `stream.ts › has error event #2` 
 - `error.ts › catches dns errors`

Same results for Node v8.15.0, v10.15.3, and v12.2.0 
#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Tests are passing for me using the same OS and Node.js versions.

```
  316 tests passed
  1 known failure
  2 tests skipped
```

**Comment by mastermatt** [comment]
Hmmm, well shoot.
I've blown away my `node_modules` and re-installed with the same result.
Here is the lockfile that npm 6.9.0 created for me: https://gist.github.com/mastermatt/24ed0493f063cc36242d1264dc971180

**Comment by szmarczak** [comment]
How did it create if `package-lock=false`? :confused:

**Comment by mastermatt** [comment]
deleted that line for a minute.

**Comment by szmarczak** [comment]
Just tested your lockfile on Linux (Solus):

```
  316 tests passed
  1 known failure
  2 tests skipped
```

**Comment by mastermatt** [comment]
Very odd. If no one else has this problem feel free to ignore this and I'll play around with my machine in the next day or two.

**Comment by szmarczak** [comment]
What are your Mac specs?

**Comment by mastermatt** [comment]
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	190.0.0.0.0
  SMC Version (system):	2.45f0
  System Version:	macOS 10.14.4 (18E226)
  Kernel Version:	Darwin 18.5.0

**Comment by nihal9ns** [comment]
@sindresorhus I am also experiencing weird issues with my tests. `got` seems to be working fine in node 10 but the moment I bumped my node version to 12.2.0, my tests started failing but my app still works fine. I use `nock` to mock api calls. I get weird errors with got. `err: GotError [RequestError]: connect ECONNREFUSED 127.0.0.1:443`

**Comment by nihal9ns** [comment]
@sindresorhus Sometimes it throws an illegal arg error `
First param must be a string, buffer....
`

**Comment by sindresorhus** [comment]
Closing as we're not able to reproduce this.
