### ISSUE TITLE
set-cookie

### ISSUE THREAD

**Issue by siqueira-ec** [sindresorhus/got#800]
#### What would you like to discuss?

Sometimes 'set-cookie' doesn`t appear on 'headers' and 'cookies' appears on gotOptions.headers

Can someone explain?

I would like to make any request to certain site to issue a new cookie ('set-cookie'). What can i do?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Something is [not right](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies). Servers send us `set-cookie`. We send them `cookie`.
