### ISSUE TITLE
got.stream does not handle HPE_HEADER_OVERFLOW errors

### ISSUE THREAD

**Issue by kapouer** [sindresorhus/got#803]
- Node.js version: 10.15.2
 - OS & version: linux debian/buster

When the requested url sends >= 8KB http headers
```
got.stream('/hpe').pipe(mywritestream)
```
throws an unhandled rejection corresponding to a RequestError, code 'HPE_HEADER_OVERFLOW', message 'Parse Error'.

I suppose it should handle emit an error on the stream ?

**Comment by sindresorhus** [comment]
You could increase the allowed header size: https://stackoverflow.com/a/55298067

Not really anything to handle for Got or you as the steam is already in an error state at that point.

**Comment by sindresorhus** [comment]
Oh sorry, I missed that it was "unhandled". `.pipe()` doesn't forward errors (which I incredible dumb). However, you can use [`Stream.pipeline`](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) instead, which properly forwards errors. We should definitely update our docs to use that instead.

**Comment by kapouer** [comment]
TIL [Stream.pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) ! Awesome !
