### ISSUE TITLE
Is there going to be officially maintained @types/got package?

### ISSUE THREAD

**Issue by JamesJGoodwin** [sindresorhus/got#804]
Hello. Is there going to be any official typings package for got? As I understand, @types/got is maintained not by @sindresorhus so It gets outdated as soon as new version of got is out.

Also, it would be helpfull to get dedicated docs for typings.

**Comment by sindresorhus** [comment]
Got is currently being rewritten in TypeScript. The next major version (no ETA, but hopefully in June) will ship with its own TypeScript definitions. Until then, `@types/got` is what you should use.

**Comment by sindresorhus** [comment]
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
