### ISSUE TITLE
Trailing slash is appended when using baseUrl

### ISSUE THREAD

**Issue by moritzruth** [sindresorhus/got#813]
#### Describe the bug

 - Node.js version: 12.2.0
 - OS & version: Ubuntu 19.04

#### Actual behavior

```js
got("", {baseUrl: "https://example.com/api"});
```
requests `https://example.com/api/` (with a trailing slash).

#### Expected behavior

```js
got("", {baseUrl: "https://example.com/api"});
```
requests `https://example.com/api` (without a trailing slash).

#### Code to reproduce

```js
got("", {baseUrl: "https://example.com/api"});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please read the docs before making an issue.

**Comment by moritzruth** [comment]
I read the docs more than once.

**Comment by szmarczak** [comment]
> When specified, url will be prepended by baseUrl.
> If you specify an absolute URL, it will skip the baseUrl.
> ...
> Slash at the end of baseUrl and at the beginning of the url argument is optional:
> ```js
> await got('hello', {baseUrl: 'https://example.com/v1'});
> //=> 'https://example.com/v1/hello'
> 
> await got('/hello', {baseUrl: 'https://example.com/v1/'});
> //=> 'https://example.com/v1/hello'
> 
> await got('/hello', {baseUrl: 'https://example.com/v1'});
> //=> 'https://example.com/v1/hello'
> ```

Note the first example: the slash in `baseUrl` option is not included, but the final URL is `/hello`.

IOW unless you provide an absolute URL it will add a slash because `baseUrl` is a [`path-absolute-URL`](https://url.spec.whatwg.org/#path-absolute-url-string) (it always ends with a slash).

**Comment by szmarczak** [comment]
Anyway, this is about to change. Take a look at this conversation: #783 :smiley:
