### ISSUE TITLE
Keep alive

### ISSUE THREAD

**Issue by sm2017** [sindresorhus/got#815]
#### What would you like to discuss?

How can I keep alive connection?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

I want to have some connection pool and keep alive them, reuse them for better performance
Do you have connection pool support out of the box?

#### Checklist

- [x]  I have read the documentation.

**Comment by sindresorhus** [comment]
You can use the `agent` option:
- https://github.com/sindresorhus/got#agent
- https://github.com/sindresorhus/package-json/blob/af8851efb342111d098ca38d3ed51f9007fbf146/index.js#L10-L17

**Comment by sm2017** [comment]
@sindresorhus what about pooling?

**Comment by sindresorhus** [comment]
https://stackoverflow.com/questions/17375021/how-to-manage-node-js-request-connection-pool

**Comment by emirom** [comment]
This the code according to the mentioned doc:
```
import HttpAgent, { HttpsAgent } from "agentkeepalive";

const liveOption = {
  keepAlive: true,
  maxSockets: 10,
};

export const newAliveAgent = () => {
  return {
    agent: {
      http: new HttpAgent(liveOption),
      https: new HttpsAgent(liveOption),
    },
  };
};

export const watchCustomerType = async (id: number) => {
  const url = `http://link.com`;
  const response = await got.get(url, newAliveAgent());
```
Is it ok? if so,
if I await the got.get(...) then the app is blocked! 
how can I emit an event or run a function (ex: update a list every time new data has been fetched) without awaiting and blocking the whole process? may you help me to complete the code?
