### ISSUE TITLE
Got.js throws ERR_INVALID_ARG_TYPE when mocking with nock on Node 12.x

### ISSUE THREAD

**Issue by yamalight** [sindresorhus/got#817]
#### Describe the bug

 - Node.js version: 12.x
 - OS & version: any

Trying to use nock with Got in Node 12.x breaks Got with `ERR_INVALID_ARG_TYPE`.

#### Actual behavior

When mocking API with nock.js - on request Got.js throws ERR_INVALID_ARG_TYPE and dies.

#### Expected behavior

Should correctly handle request to nock server.

#### Code to reproduce

```js
const nock = require('nock');
const got = require('got');

const thisWorks = await got('https://httpbin.org/get');
console.log(thisWorks.body);

const testServer = nock('http://localhost:8080')
    .get('/')
    .reply(200, {hello: 'world'});

const thisBreaks = await got('http://localhost:8080/');
console.log(thisBreaks.body);
```

Here's an interactive demo: 
https://runkit.com/yamalight/5cf50559b975d2001a4dfaa8

Switching to Node 10.x fixes the issue. Using e.g. node-fetch instead of Got.js also works correctly with nock.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by yamalight** [comment]
@sindresorhus yes, I've tried using other libs and they seem to work fine.
I've added `node-fetch` and `axios` to [interactive demo](https://runkit.com/yamalight/5cf50559b975d2001a4dfaa8) to demonstrate that they work fine.

**Comment by szmarczak** [comment]
Make sure you're running `11.0.0-beta.13`: https://github.com/nock/nock/issues/1509#issuecomment-490904028

Let us know then.

**Comment by yamalight** [comment]
@szmarczak yep, that does indeed fixes it. Somehow misread it and thought fix was shipped in 10.0.6. Sorry for the bother and thanks for help! 😅

**Comment by szmarczak** [comment]
No problem :)

**Comment by stevenvachon** [comment]
I'm using nock 11.0.0-beta.25 and I'm still experiencing this issue.
