### ISSUE TITLE
There is a code difference between npm package and repository for 9.6.0

### ISSUE THREAD

**Issue by anagorsky** [sindresorhus/got#818]
The source code of latest npm package does not match with current code of this repository, while version is the same. It leads to misunderstanding and makes documentation not corresponding declared functionality.

#### Actual example

For example, npm **as-promise.js** file does not contain **beforeError** hook handler which I currently try to use.

#### Expected behavior

Please, update npm package some how.
Thanks

**Comment by HellMagic** [comment]
i also have the problem, and i found the promise instance in as-promise.js doesn't have like json()、text() method, but they are found in as-promise.ts。

**Comment by sindresorhus** [comment]
This is clearly documented at the top of the readme:

> **This readme reflects the next major version that is currently in development. You probably want [the v9 readme](https://www.npmjs.com/package/got).**

**Comment by sindresorhus** [comment]
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
