### ISSUE TITLE
how to use retry and beforeRetry hook?

### ISSUE THREAD

**Issue by HellMagic** [sindresorhus/got#819]
#### What would you like to discuss?
test how to use retry feature, or if i miss some important thing, please show me a correct example.

#### Checklist

- [x ] I have read the documentation.

#### Actual behavior
beforeRetry hook just be called once

#### Expected behavior
beforeRetry hook should be called as times as retries count

#### Code to reproduce
```javascript
const got = require('got');
const nock = require('nock');

const mgot = got.extend({retry: {retries: 4, maxRetryAfter: 1000 * 2}});

console.log(got.defaults.options.retry);
console.log(mgot.defaults.options.retry);

nock('https://sindresorhus.com')
	.get('/')
	.reply(500, {message: 'nonono'});

(async () => {
    try {
        const response = await mgot('https://sindresorhus.com', {responseType: 'json', hooks: {
            beforeRetry: [
                (options, error, retryCount) => {
                    console.log('error = ', error.message);
                    console.log('retryCount = ', retryCount);
                }
            ]
        }});
    } catch(err) {
        if(err.response && err.response.body) {
            console.log('body message - ', err.response.body);
        }
    }
	
})();
```
the output shows my custom retry options is correct, eg, the value of "mgot.defaults.options.retry.retries" is equal 4, but in the beforeRetry hook i just found console once, and then the code in catch is execute.

**Comment by szmarczak** [comment]
This sounds like a bug...

1. What's your OS?
2. What's your Node version?
3. What's your Got version?

Please try the master branch. Let us know if it's not fixed there.

**Comment by HellMagic** [comment]
@szmarczak thanks for reply, i think maybe it isn't a bug, but about the [nock](https://github.com/nock/nock) module, because got work well if i use a normal express/koa server, so this issues can be closed, of course, if have some idea please let me know. 

OS: 10.14.5
Node Version: v8.11.0
Got Version: v9.6.0
nock Version: v10.0.6

**Comment by szmarczak** [comment]
It gives:

```js
Nock: No match for request {
  "method": "GET",
  "url": "https://sindresorhus.com/",
  "headers": {
    "user-agent": "got/9.6.0 (https://github.com/sindresorhus/got)",
    "accept-encoding": "gzip, deflate"
  }
}
```

Please don't report non-Got issues in the future this is not the right place.
