### ISSUE TITLE
How to convert to a string stream?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#834]
#### What would you like to discuss?
Setting the option `encoding: 'utf8'` (which is already the documented default) doesn't affect binary chunks.

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
Not clear exactly what you mean. Can you provide an example?

**Comment by stevenvachon** [comment]
```js
'use strict';
const {get} = require('http');

get('http://google.com/', {}, response => response
	.on('data', chunk => console.log(chunk)) //-> `<Buffer 3c 48 54…`
);

get('http://google.com/', {}, response => response
	.setEncoding('utf8')
	.on('data', chunk => console.log(chunk)) //-> '<html><head>…'
);
```

How can I set the encoding for a got stream?

**Comment by stevenvachon** [comment]
@sindresorhus ^^

**Comment by kevva** [comment]
You can use `.setEncoding` on a `got.stream` as well.

**Comment by stevenvachon** [comment]
@kevva can you provide an example? I couldn't get it to work.

**Comment by kevva** [comment]
@stevenvachon, just like the example you provided above, but with `got.stream` instead:

```js
got.stream('https://google.com')
    .setEncoding('utf8')
    .on('data', data => {
        console.log(data);
        //=> '<html><head>…'
    });
```

**Comment by stevenvachon** [comment]
@kevva, that isn't working for me. I'm piping to [parse5](https://npmjs.com/parse5) and it complains "Parser can work only with string streams."

**Comment by kevva** [comment]
This is working fine for me:

```js
const parser = new ParserStream();

parser.once('finish', () => {
    console.log(parser.document.childNodes[1].childNodes[0].tagName);
    //=> 'head'
});

got.stream('https://google.com')
    .setEncoding('utf8')
    .pipe(parser);
```
