### ISSUE TITLE
Cookie example from the README fails

### ISSUE THREAD

**Issue by luismesejo** [sindresorhus/got#835]
#### Describe the bug

 - Node.js version: v11.9.0
 - OS & version: macOS 10.13.6

#### Actual behavior

The code on https://github.com/sindresorhus/got#cookies throws an error on the setCookie function call... 

TypeError: Cannot read property 'loose' of undefined
    at CookieJar.setCookie (/var/app/current/node_modules/tough-cookie/lib/cookie.js:1005:15)
   
I guess the though-cookie lib is not being used properly... if I figure it out I will comment it here

...

#### Expected behavior
To set cookies and use them on the request..

...

#### Code to reproduce

```js
const {CookieJar} = require('tough-cookie');

const cookieJar = new CookieJar();
cookieJar.setCookie('foo=bar', 'https://www.google.com');
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

thanks!

**Comment by szmarczak** [comment]
Callback is missing. It should be:

```js
cookieJar.setCookie('foo=bar', 'https://www.google.com', (error, cookie) => {
	if (error) {
		throw error;
	}

	doSomething();
});
```

Or, if you prefer Promise:

```js
const setCookie = util.promisify(cookieJar.setCookie.bind(cookieJar));

await setCookie('foo=bar', 'https://www.google.com');
```

**Comment by szmarczak** [comment]
You can use `setCookieSync` if you use the default store.

**Comment by luismesejo** [comment]
it's working for me now:

```
const { CookieJar, Cookie, } = require('tough-cookie');
const newCookie = new Cookie({ key: 'foo-bar', value: 'something' });

const cookieErrorCb = (err) => {
     if ( err ) {
        console.log(err)
    }
}
cookieJar.setCookie(newCookie, 'https://yourdomain.com' cookieErrorCb);
got.get(url, { cookieJar });
```

**Comment by luismesejo** [comment]
made a PR https://github.com/sindresorhus/got/pull/836
