### ISSUE TITLE
Do not use dnsCache in Kubernetes

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#841]
Not an actual issues, just heads up to anyone who attempts to use `dnsCache` in Kubernetes – if you use `dnsCache` in Kubernetes environment, your inter-pod HTTPs requests are going to start failing with "connection refused". This is because iptables on nodes are updated in response to nodes going through different readiness states.

See this article for more context https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/.

**Comment by gajus** [comment]
@sindresorhus Just to confirm: There is no DNS cache in v9?

**Comment by szmarczak** [comment]
Yes, there's no dnsCache in v9. Have you checked if it throws? I assume you're just guessing.

`dnsCache` just translates to the `lookup` option. It works the same as the default `lookup` function except it caches the entries.

Also there is another layer of caching done in the OS-level.

**Comment by gajus** [comment]
> Yes, there's no dnsCache in v9. Have you checked if it throws? I assume you're just guessing.

Something is misbehaving in my stack when deployed on Kubernetes. I am just ruling out elements one by one.

I think I found the possible contender and documented the solution here https://github.com/gajus/lightship#best-practices.

My guess is that:

* Either programs shutdown HTTP service too soon after receiving the SIGTERM; or
* Something in the client's stack is cacheing lookup results for too long.

As I was debugging this, I remembered seeing `dnsCache` option in Got v10 documentation and figured I will add a preemptive warning to people who will run into this in the future.

**Comment by szmarczak** [comment]
> As I was debugging this, I remembered seeing dnsCache option in Got v10 documentation and figured I will add a preemptive warning to people who will run into this in the future.

`dnsCache` is disabled by default. Anyway if you enable it, it behaves the same as the default `lookup` function (it just returns immediately if the entry's cached) so it should not break anything.

I think what you're looking for is graceful shutdown (don't accept new connections, just wait until everything's closed). Or just force close all connections and done.
