### ISSUE TITLE
Setting responseType to 'json' doesn't return json.

### ISSUE THREAD

**Issue by jandrieu** [sindresorhus/got#842]
#### Describe the bug

 - Node.js version: v10.16.0
 - OS & version: Ubunto 18.04
 - Got version: 9.6.0

Setting responseType to 'json' doesn't return json.

#### Actual behavior
Setting responseType to 'json' doesn't seem to change anything (except the value of responseType in the request object);

Instead, the body is just interpreted as text. And, the .json() function doesn't exist.
```
ERROR TypeError: response.json is not a function
```
As it turns out, I did get results when I set the "json" option to true.

#### Expected behavior
The documentation and examples seem to suggest that setting the responseType to 'json' will give you JSON as a result. 

> To receive a JSON body you can either set responseType option to json or use promise.json(). Example:
>
> const got = require('got');
>
> ``` (async () => {
> 	const {body} = await got.post('https://httpbin.org/anything', {
> 		body: {
> 			hello: 'world'
> 		}
> 	}).json();
> 
> 	console.log(body);
> ```

...

#### Code to reproduce

```js
const client = got.extend( {
        responseType: 'json'
 });
const response = await client.get(url);
console.log(response);
```
and what is actually needed:
```js
const client = got.extend( {
        json: true,
 });

const response = await client.get(url);
console.log(response);
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

FWIW, this bug might be fine to resolve just by updating the documentation.

**Comment by szmarczak** [comment]
From the docs:

# **This readme reflects the next major version that is currently in development. You probably want [the v9 readme](https://www.npmjs.com/package/got).**

What part do you not understand in "this readme reflects the the next major version"? We could save some time if you looked into closed issues already 😉 (some of them are also the result of **not** reading the documentation in full). Either you want the v9 readme or `npm i sindresorhus/got#master`.

**Comment by sindresorhus** [comment]
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
