### ISSUE TITLE
Missing Typings

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#844]
#### What would you like to discuss?

This lib is now 100% typescript and I never use got because of that, now I want to try it and I see that even if this is all in typescript the released version doesn't include typings, so it's really sad

![image](https://user-images.githubusercontent.com/7302317/62054209-6af6da80-b219-11e9-949a-5eb35407ad77.png)

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
From the docs:

# **This readme reflects the next major version that is currently in development.**

[Probably] what you want is `npm i sindresorhus/got#master`.

**Comment by yovanoc** [comment]
It doesn't change anything, I already tried that.. thats simply because you didn't include definitions files in your final bundle..

**Comment by sindresorhus** [comment]
We have an alpha version of v10 out if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
