### ISSUE TITLE
Stream response only (not request body)

### ISSUE THREAD

**Issue by azz** [sindresorhus/got#845]
#### What would you like to discuss?

Is it possible to stream a response without streaming the body? e.g. I want to do:

```js
const stream = got.stream.post('https://example.com', {
  body: { some: 'object' },
  json: true,
});
```

Currently if I do this I get the error:

> The `body` option must be a stream.Readable, string or Buffer

My workaround is to do the following:

```js
import intoStream from 'into-stream';
import JSONStream from 'JSONStream';

function asStream(obj) {
  return intoStream.object(obj).pipe(JSONStream.stringify());
}

const stream = asStream({ some: 'object' }).pipe(
  got.stream.post('https://example.com', { json: true });
);
```

But I would rather avoid the need for this function if possible.

_(got@9.6.0)_

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Try the alpha version and let us know
