### ISSUE TITLE
About comparison in Readme

### ISSUE THREAD

**Issue by clutchyu** [sindresorhus/got#848]
Is there a way  to get the features of the packages in the comparison?

**Comment by szmarczak** [comment]
What do you mean? The question makes no sense at all. All the packages have these features where the tick is showed. If there's an X, the feature is missing.

**Comment by clutchyu** [comment]
> What do you mean? The question makes no sense at all. All the packages have these features where the tick is showed. If there's an X, the feature is missing.

Thank you for your reply.  I'm not familiar with these packages,I want to know if the features do official introduction include or summarized by developers?

**Comment by sindresorhus** [comment]
@clutchyu Your question still doesn't make any sense.

I'm gonna close this as it's not an issue, but feel free to continue the discussion.

**Comment by szmarczak** [comment]
> I want to know if the features do official introduction include or summarized by developers?

If you mean this:

> I want to know if the features have been properly documented.

It depends what you refer to. If you refer to Got, then yes, all the features have been documented. If you refer to axios, request etc. you have to ask them, not us.
