### ISSUE TITLE
How to use a client certificate ?

### ISSUE THREAD

**Issue by kaboume** [sindresorhus/got#851]
Hello,
I want to migrate an old php code using cUrl to nodeJs with the got module.
My script uses a **client certificate** to connect to a remote server.
Here is an extract of the cUrl php code :

```
CURLOPT_SSLCERT => $this->cert_p12_path,
CURLOPT_SSLCERTPASSWD => $this->cert_p12_password,
```

I have not found in the got documentation, how to use this kind of certificate. 
Could you please help me ?
Thanks;
Eric

**Comment by kaboume** [comment]
Ok I found.
I added theses lines in the options object 

```
      key: fs.readFileSync(__dirname + "/my_cert.pem"),
      cert: fs.readFileSync(__dirname + "/my_cert.pem"),
      passphrase: "XXXXXXX"
```

Thanks for this great module.
Eric.

**Comment by szmarczak** [comment]
Please don't make new issues if:

1. You haven't read the whole documentation.
2. You are very new to Node.

This is not the right place to ask these questions. Everything's well described in the docs.

If something's hard to understand, please make your issue clear about it. Otherwise you could save us lots of time by reading the docs instead of making issues on how to use Got :smiley:

**Comment by Freakachoo** [comment]
I would want to add a question here - is that possible to use `p12` certificates? Haven't found the way.
For example the `request` module accepts key `pfx`. Does it work for `got` also?

**Comment by szmarczak** [comment]
Check Node.js native options, Got doesn't so any certificate handling.

**Comment by Freakachoo** [comment]
Do you mean `https.request` on `Node.js native`?

**Comment by szmarczak** [comment]
Node.js native module = shipped by Node.js

**Comment by justinschw** [comment]
> Please don't make new issues if:
> 
>     1. You haven't read the whole documentation.
> 
>     2. You are very new to Node.
> 
> 
> This is not the right place to ask these questions. Everything's well described in the docs.
> 
> If something's hard to understand, please make your issue clear about it. Otherwise you could save us lots of time by reading the docs instead of making issues on how to use Got smiley

I'm sure glad he did. This isn't mentioned in the readme, and this issue sure saved me a lot of time.

**Comment by aukevanleeuwen** [comment]
For future readers the documentation for client certificates is here: https://github.com/sindresorhus/got/blob/main/documentation/5-https.md. I was searching in the wrong place ('general options') for a bit at first, so I thought I'd safe other people the trouble.
