### ISSUE TITLE
Cancelling requests using hooks

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#852]
#### What problem are you trying to solve?

Lack of ability to abort retry.

#### Describe the feature

Suppose a scenario where a website can return a 500 status code, and this would generally mean that the request should be retried after some delay. However, it may be that 500 status code comes with a response body that describes an error constant that signals that no further attempts should be made.

The particular website that I am dealing response with status code 500 and response body:

```json
{
    "code": "27401",
    "message": ""
}

```

This particular response signals that service cannot process the request because session has expired.

To handle scenarios such as this, I would like to be able to conditionally retry a request based on the last response _in addition_ to the `retry` configuration, e.g.

```js
got('example.com', {
  hooks: {
    beforeRetry: [
      (options, error, retryCount, next) => {
        if (error.body.includes('27401')) {
          next(new DataUnavailableError());
        }
      }
    ]
  }
});


```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Just throw an error within the hook: `throw ...`

Alternatively you can use [the `afterResponse` hook](https://github.com/sindresorhus/got#hooksafterresponse) to update the session.

**Comment by szmarczak** [comment]
I think we missed that part in docs about throwing errors inside hooks, didn't we?

**Comment by szmarczak** [comment]
Fixed
