### ISSUE TITLE
The functionality of resolveBodyOnly is not working

### ISSUE THREAD

**Issue by jamiehaywood** [sindresorhus/got#853]
#### Describe the bug

 - Node.js version: v10.14.1
 - OS & version: MacOS 10.13.6

The functionality of `resolveBodyOnly` is nonexistent in the current version on NPM. 
#### Actual behavior

There are no references to `resolveBodyOnly` in any of the files in the `got` package, but I can see it in the GitHub source.

#### Expected behavior

If there's advertised functionality in the README it should work...

#### Code to reproduce

```js
...
```

#### Checklist

- [x ] I have read the documentation.
- [x ] I have tried my code with the latest version of Node.js and Got.

**Comment by jamiehaywood** [comment]
Closing my own issue, because I've just seen the line `This readme reflects the next major version that is currently in development. You probably want the v9 readme.` on the README.
Apologies.

**Comment by szmarczak** [comment]
Glad there are actually people who read the readme **closely** :) There many issues like this. You've just saved us another few minutes to explain things :P

**Comment by jamiehaywood** [comment]
It is a bit annoying that the readme displays `in development` features that haven't been pushed to the package..!

**Comment by sindresorhus** [comment]
> It is a bit annoying that the readme displays in development features that haven't been pushed to the package..!

I'm surprised you have no been affected by that before. That's pretty much how all projects on GitHub operate.

**Comment by sindresorhus** [comment]
Anyway, we have an alpha version of v10 out now if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1 :)
