### ISSUE TITLE
Async iteration broken with node.js 10

### ISSUE THREAD

**Issue by epeli** [sindresorhus/got#854]
#### Describe the bug

 - Node.js version: v10.16.2
 - OS & version: macOS Mojave 10.14.4 

```js
const got = require("got");

async function main() {
    const stream = got.stream("https://www.npmjs.com/package/got");

    for await (const chunk of stream) {
        console.log("begin");
        console.log("       chunk", chunk.length);
        console.log("end");
    }
    console.log("loop done");
}

main().catch(error => {
    console.log("error", error);
});
```

#### Actual behavior

The loop in above code does not ever finish. Last line it prints is `end`. Interestingly the node process exits regardless.

#### Expected behavior

When executed the last printed line should be `loop done`.

---------------

This might be a node.js bug since with node.js 12 the above code seems to be working but I was unable to reproduce this issue without got.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by epeli** [comment]
Found a workaround: Pass it through the `PassThrough` stream and it works:


```js
const {PassThrough} = require("stream");

const stream = got
        .stream("https://www.npmjs.com/package/got")
        .pipe(new PassThrough())
```

**Comment by imcotton** [comment]
I could confirm this by simply testing sample code with online **runkit** env, trouble with Node v10 and v11, works on v12.

**Comment by szmarczak** [comment]
Actually if it works on Node 12, it's definitely a Node issue.

**Comment by imcotton** [comment]
@szmarczak native stream actually works, you could try below code snippet over https://npm.runkit.com/got

```javascript
const { get } = require('https');
const { stream } = require('got');

async function main() {

    const url = "https://www.npmjs.com/package/got";

    const readable = await new Promise(res => get(url, res));
    // const readable = stream.get(url);
    
    const chunks = [];
    
    for await (const chunk of readable) {
        chunks.push(chunk);
    }
    
    console.log("loop done: " + Buffer.concat(chunks).length);

}

main().catch(error => {
    console.log("error", error);
});
```

**Comment by szmarczak** [comment]
@imcotton `got.stream` is a Duplex stream. Duplex is a Readable too, but Readable is not Duplex.

**Comment by imcotton** [comment]
Agreed that internal difference it might between `http.get` and `got.stream`, however regarding to consumption level (e.g. `for await of` or `data` event), I think they should acting like the same, don't they?

**Comment by szmarczak** [comment]
> I think they should acting like the same, don't they?

See:

> got.stream is a Duplex stream. Duplex is a Readable too, but Readable is not Duplex.

If it wasn't working for Duplex streams, but was for Readables, and then suddenly started working for Duplex, it means Node must have done something. We did nothing.

**Comment by imcotton** [comment]
Or could it be something wrong with the [duplexer3](https://www.npmjs.com/package/duplexer3), which used by **got** internally, where the only version **0.1.4** was pushed 4 years ago, and have had this suspicious issue floatdrop/duplexer3#2 dangling.

Just my quick glance over so far, I think it's error prone for people whom stick in Node v10, this is purely observation, not blaming.

Furthermore, treat this as **won't fix** is OK to me as long as the maintainer (of **got**) have a clear stands (in README or somewhere) on dropping support for Node v10, will stop digging and looking for alternatives instead, thanks.

**Comment by szmarczak** [comment]
@imcotton It just wraps the Duplex stream. It's not broken. The issue not suspicious because the OP wants to change `null` to `false`. It doesn't change any behavior.

**Comment by imcotton** [comment]
OK then.
