### ISSUE TITLE
Lookup timeout is defeated by fast lookup

### ISSUE THREAD

**Issue by timdp** [sindresorhus/got#857]
#### Describe the bug

 - Node.js version: 12.7.0
 - OS & version: Ubuntu 19.04

#### Actual behavior

A `TimeoutError` is thrown if `dns.lookup()` calls its callback after a single event loop tick, because got doesn't start listening for the `lookup` event early enough and then lets it time out.

We're using [redns](https://www.npmjs.com/package/redns) to cache DNS responses, and passing it to got as `lookup`. When redns finds a record in its cache, it will call the callback to `lookup` in the next tick. This, however, throws off got.

The reason is that got waits for the `socket` event to listen for the `lookup` event on the socket. While that makes a lot of sense, the `socket` event is apparently [emitted asynchronously](https://github.com/nodejs/node/blob/2fd2dd75657af12a74e01a9a5e39e5f677ff3c88/lib/_http_client.js#L703-L705), and by the time it hits got, the `lookup` event has already been emitted.

I don't think the issue lies with redns, as the contract is to call the provided callback synchronously. It does that in the most efficient way: wait a single tick. As a workaround, we're currently postponing redns's callback by a tick, which gives got enough time to add the listener. However, that shouldn't be necessary.

[This Gist](https://gist.github.com/timdp/21c9aec4d127e8ccb36b05cf65c48881) proves the behavior independent of got. Additionally, it offers a solution: `createConnection` receives the socket synchronously, so by adding the listener there instead, you always capture the `lookup` event.

#### Expected behavior

`TimeoutError` is only thrown if `lookup` event doesn't occur within `timeout.lookup` ms.

#### Code to reproduce

[This Gist](https://gist.github.com/timdp/21c9aec4d127e8ccb36b05cf65c48881) (also linked above) passes a mock `lookup` implementation that essentially does what redns does: schedule the callback with the correct result on the next tick. It implements two ways of listening for `lookup`, and shows that you only get the event if you add the listener synchronously from `createConnection`.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I'll investigate into this ASAP.

**Comment by timdp** [comment]
Take your time. I _think_ our workaround is mitigating it but we're still adding some additional monitoring to make sure.

**Comment by szmarczak** [comment]
Actually this is not a bug. Try using `setImmediate`:

```js
		lookup: (_hostname, options, callback) => {
			if (typeof options === 'function') {
				callback = options;
			}
			
			setImmediate(() => callback(null, '127.0.0.1', 4));
		}
```

it works as expected.

**Comment by szmarczak** [comment]
Found a fix, so you're right. It **is** a bug.

**Comment by szmarczak** [comment]
Fixed by adding `typeof (socket.address() as net.AddressInfo).address === 'undefined'` to make sure the `lookup` event didn't occur yet: https://github.com/sindresorhus/got/commit/4faf5c79e7cd5b81ec3c5f6840b9e5918e4d02ef#diff-7ab9a52ac2fccf434c1a34ce48f2883bR113
