### ISSUE TITLE
Library retries even after 200 response

### ISSUE THREAD

**Issue by adityapatadia** [sindresorhus/got#858]
#### Describe the bug

 - Node.js version: 10.16
 - OS & version: Macos 10.14

#### Actual behavior

Default `retry` is `2`. Ideally library should not retry when successful response is received but somehow it always tries again after `timeout` time is passed.

#### Expected behavior
It should not retry after `200` response is received.

#### Code to reproduce

```js
let cacheStore = new Map();
var requestOptions = {
    timeout: 5000, // milliseconds
    encoding: null,
    decompress: true,
    headers: {
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.5'
              },
    shared: false,
    cache: cacheStore
};
got("https://www.google.com", requestOptions);
```
Put some logging in `cacheable-request` library and see that its request function is called again after `5000 ms`.

#### Checklist

- [ X ] I have read the documentation.
- [ X ] I have tried my code with the latest version of Node.js and Got.

**Comment by adityapatadia** [comment]
I should mention this will only happen when the URL gives 304 response.

**Comment by szmarczak** [comment]
Unable to reproduce the issue: https://runkit.com/szmarczak/5dbd68dc7dacab0014b541eb
