### ISSUE TITLE
is there any plugin like axios-curlirize for got?

### ISSUE THREAD

**Issue by nickfan** [sindresorhus/got#861]
#### What problem are you trying to solve?
sometime we just want a plugin to generate curl command for help us to solve server side problem,
when i use axios i found the plugin https://github.com/delirius325/axios-curlirize
could generate full curl command with the right cookies,referer,etc.. headers request.
so,is there something like this for got?

...

#### Describe the feature

generate the request as a cURL command

...

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
no
