### ISSUE TITLE
`.json` on the promise is not defined

### ISSUE THREAD

**Issue by luxferresum** [sindresorhus/got#862]
#### Describe the bug

 - Node.js version: 10.15.3
 - OS & version: Linux (Nixos)
-  got version: 9.6.0 

#### Expected behavior
The example [here](https://github.com/sindresorhus/got#json-mode) seems to suggest this to work.

#### Code to reproduce

```js
...
> got.get('https://gitlab.com/api/v4/groups/').json()
TypeError: got.get(...).json is not a function
>
>
> got('https://gitlab.com/api/v4/groups/').json()
TypeError: got(...).json is not a function

```

So did I understand the documentation wrong or is this a bug?

**Comment by rmp135** [comment]
This threw me as well. The documentation on the README is actually for the next version. You want the [npm](https://www.npmjs.com/package/got) docs for the current version. 

Looking through the bug list, this has caught a few people out.

**Comment by sindresorhus** [comment]
This is clearly pointed out at the top of the readme. In addition, this is how almost all projects work on GitHub; master branch is development.

**Comment by sindresorhus** [comment]
We have an alpha version of v10 out now if you wanna help us test: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
