### ISSUE TITLE
Redirect doesn't update Host header

### ISSUE THREAD

**Issue by lselden** [sindresorhus/got#866]
#### Describe the bug

 - Node.js version: Node v12.2.0
 - OS & version: Windows 10.0.18362

If the "Host" header is explicitly set in the initial request options it isn't updated on a redirect, which could trigger an error if the redirect is to a different domain.

#### Actual behavior

On redirect the hostname is updated (via url-to-options.js), but the "Host" header isn't automatically updated.

#### Expected behavior

Host header (if existing) is updated to match hostname, or removed so underlying http/https libraries automatically populate from hostname.

#### Code to reproduce
```js
// use mocky.io to perform a 302 redirect to https://github.com/sindresorhus/got
try {
    const result = await got.get('http://www.mocky.io/v2/5d700e1f310000acb1660a73', {
        headers: {
            Host: 'www.mocky.io'
        },
        hooks: {
            beforeRedirect: [
                options => {
                    const hostHeader = options.headers && options.headers.host;
                    const hostname = options.hostname || options.host;
                    if (hostHeader !== hostname) {
                        console.warn('Host header does not match destination hostname. This will likely fail');
                        // uncomment for workaround
                        // options.headers.host = options.hostname;
                    }
                }
            ]
        }
    });
} catch (err) {
    console.warn('Failed!', err);
    // Result: RequestError: Hostname/IP does not match certificate's altnames: Host: www.mocky.io. is not in the cert's altnames: DNS:github.com, DNS:www.github.com
}
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
@sindresorhus This is an invalid usage, because Node sets the `host` header automatically by default.

However this is easy to fix by calling `delete options.host` on redirect if `options.setHost` isn't `false`. Use case: setting the IP address manually for the first request:

```js
got({
	host: '127.0.0.1',
	headers: {
		host: 'example.com'
	}
});
```

If `options.setHost` is `false`, users would need to handle the `host` header on their own.

**Comment by lselden** [comment]
Fair enough; you make a good argument. Thanks for the answer @szmarczak

**Comment by szmarczak** [comment]
@lselden I have also provided a tip on how to code the solution. You could use the handler for setting `options.setHost` to `false`, as it's called only once. Then, in a `beforeRedirect` hook you just set `options.setHost` to `true`.
