### ISSUE TITLE
Export events

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#870]
#### What problem are you trying to solve?
I'd like to avoid writing event strings manually:
```js
import {stream as streamHTTP} from 'got';
streamHTTP(url).on('error', error => {});
```

#### Describe the feature
```js
import {ERROR_EVENT, stream as streamHTTP} from 'got';
streamHTTP(url).on(ERROR_EVENT, error => {});
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Stringly-typed APIs is unfortunately the norm in JS. It would be weird to use constants for this, even though I prefer that in other languages. For TypeScript users, we could potentially expose an enum for it, or make the `on()` method only accept the allowed string events, to improve safety and auto-completion.

**Comment by szmarczak** [comment]
There's no point in avoiding strings. Each strings only stored once. IOW: million instances of `HelloWorld` will use just a few bytes in total.

Your example is very similar to one I saw months ago: someone *did* create 100 variables:
```js
const PERCENT_0 = 0;
const PERCENT_1 = 0.01;
...
const PERCENT_100 = 1;
```

And then used it all over his code. 🤦‍♂️

Like @sindresorhus has pointed out: this is how JavaScript is designed. It's not good, but we can't change that.

**Comment by stevenvachon** [comment]
I understand that they're not symbols, but they force us to use named exports instead of random strings. If there's a typo in the named import, it can throw.

**Comment by szmarczak** [comment]
These are NOT just random strings. As I mentioned earlier, each string is stored once. It cannot be duplicated or copied, strings are immutable.

Actually the `error` event is a built-in feature of `EventEmitter`.

Did you know that properties are also strings? For example: `got().on` is the same as `got()['on']`.

Strings are like symbols, except that they aren't unique. Each `"qwerty"` points to the same instance so this is why `"qwerty" === "qwerty"` is true.

Also each variable name is also a string, so making a constant for a string is pointless (unless the string is *randomly* generated; 'error' is not random; 'error' is always 'error'):
```js
const myVar = 123;

const NAME = 'myVar';

global[NAME]; // Points to `myVar`; value = 123
global['NAME']; // Points to `NAME`; value = 'myVar'
```

**Comment by stevenvachon** [comment]
`"qwerty" === "querty"` does not mean they are the same instance; it means that they have the same value.

And just because parts of Got extend `EventEmitter` doesn't mean that we need to know that. The consumer's mindset is that they are working with Got, and that can benefit from exported events.

**Comment by szmarczak** [comment]
You're wrong. Please see the [MDN docs about equality operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators).

> - Two strings are strictly equal when they have the same sequence of characters, same length, and same characters in corresponding positions.
> - Two numbers are strictly equal when they are numerically equal (have the same number value). NaN is not equal to anything, including NaN. Positive and negative zeros are equal to one another.
> - Two Boolean operands are strictly equal if both are true or both are false.
> - Two distinct objects are never equal for either strict or abstract comparisons.
> - **An expression comparing Objects is only true if the operands reference the same Object.**
> - Null and Undefined Types are strictly equal to themselves and abstractly equal to each other.

The Object rule is a base for all other rules. Strings are immutable, so each string points to the same object. Same for `undefined`s, `null`s etc.

> "qwerty" === "querty" does not mean they are the same instance

Yes, it does. Strings are also objects. If you open Chrome Dev Tools and take memory snapshot, you can see that all `qwerty`s are the same instance.

![image](https://user-images.githubusercontent.com/36894700/64678051-1a5dd880-d479-11e9-9b21-492e13fee4fb.png)

> it means that they have the same value

Another example to explain that your thinking is invalid:

```js
const a = Object.create(null, {
	myProperty: {
		value: 123
	}
});

const b = Object.create(null, {
	myProperty: {
		value: 123
	}
});

const c = a;

console.log(a === b); // false
console.log(a === c); // true
```

It doesn't check values. It checks the references.

> And just because parts of Got extend `EventEmitter` doesn't mean that we need to know that. 

If you don't then Got's not for you. You want to use Got without knowing how to use it. `EventEmitter` is a built-in feature of Node and you should know how to use it. It's a fundamental base for many many projects.

> that can benefit from exported events

My previous answer explains why this is an invalid thinking. You're just making a string to get another string, which is nonsense.

**Comment by szmarczak** [comment]
For TypeScript this would be the correct solution:

> make the on() method only accept the allowed string events, to improve safety and auto-completion.

**Comment by sindresorhus** [comment]
@szmarczak I think you're misunderstanding the argument of @stevenvachon. Regardless, constants like that is not something we plan to do. However, I've opened an issue about improve our types: https://github.com/sindresorhus/got/issues/877
