### ISSUE TITLE
Cache isn't working

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#873]
#### Describe the bug

 - Node.js version:  12.10
 - OS & version: MacOS Catalina

#### Actual behavior

When I put a cache system it does not work. I'm currently using master branch, and different module like `keyv-file` and the file is never saved.

#### Expected behavior

The file is here and used in case of subsequent request.

#### Code to reproduce

![image](https://user-images.githubusercontent.com/7302317/64939340-fc211f80-d860-11e9-8fc7-fd1e50ffee71.png)
![image](https://user-images.githubusercontent.com/7302317/64939351-04795a80-d861-11e9-9c67-70cd9918641d.png)

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please, don't try to kill us. We won't rewrite your code character by character. Copy and paste it here, otherwise the issue will be closed.

**Comment by yovanoc** [comment]
```ts
import DTConstants from "@/protocol/DTConstants";
import { stringify } from "querystring";
import { Languages } from "@/configurations/language/Languages";
import got from "got";
import { appDataPath } from "@lazyspace/common";
import KeyvFile from "keyv-file";
import { join } from "path";
import { Data } from "./data";

const cache = new KeyvFile({
  filename: join(appDataPath, "data.json"), // the file path to store the data
  expiredCheckDelay: 10 * 24 * 3600 * 1000, // ms, check and remove expired data in each ms
  writeDelay: 120, // ms, batch write to disk in a specific duration, enhance write performance.
  encode: JSON.stringify, // serialize function
  decode: JSON.parse // deserialize function
});

export interface RequestData {
  lang?: Languages;
  id?: string | number;
  ids?: (string | number)[];
  class?: keyof Data;
}

export async function request<T extends unknown>(
  serverPath: string,
  path: string,
  data: RequestData,
  defaultLang: Languages
): Promise<T> {
  const query = {
    lang: data.lang || defaultLang,
    v: DTConstants.buildVersion
  };

  const req = serverPath + path + "?" + stringify(query);

  const { body } = await got.post(req, {
    cache,
    retry: 4,
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(data),
    responseType: "json"
  });

  return body;
}
```

Sorry for that

**Comment by szmarczak** [comment]
What URL were you trying to cache?

**Comment by yovanoc** [comment]
https://proxyconnection.touch.dofus.com/data/map?lang=fr&v=1.43.2

**Comment by szmarczak** [comment]
I get `ERR_CONNECTION_REFUSED`, could you please link something that works without a proxy?

**Comment by yovanoc** [comment]
A simple POST request with the Content-Type header with this in body: 

```json
{
	"class": "Pets",
	"ids": []
}
```

**Comment by szmarczak** [comment]
Is this specific for `keyv-file`? Does it work with just `keyv`?

**Comment by yovanoc** [comment]
It doesn't work either

**Comment by szmarczak** [comment]
So the method is POST, and what's the status code?

**Comment by yovanoc** [comment]
200

**Comment by yovanoc** [comment]
In fact, even with a `new Map()` as a cache, and a `console.log(cache)` after each request it doesn't seem to work too

![image](https://user-images.githubusercontent.com/7302317/65370768-c9aa6480-dc5c-11e9-92fa-21a94845d6cf.png)

**Comment by szmarczak** [comment]
And what are the response headers?

**Comment by yovanoc** [comment]
![image](https://user-images.githubusercontent.com/7302317/65371029-91585580-dc5f-11e9-9c39-bf3a9b50f2b3.png)

**Comment by szmarczak** [comment]
I don't see any outstanding behavior. It works as expected. https://httpwg.org/specs/rfc7234.html#rfc.section.4.4

> A cache MUST invalidate the effective Request URI (Section 5.5 of [RFC7230]) as well as the URI(s) in the Location and Content-Location response header fields (if present) when a non-error status code is received in response to an unsafe request method.

`POST` is one of the unsafe methods.

**Comment by szmarczak** [comment]
I think what you're looking for is #875

**Comment by yovanoc** [comment]
Oh I was thinking it would store the response body in the cache if the request doesn't change. Like params etc
