### ISSUE TITLE
`response.timings.response` is `null` on the `response` event

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#874]
#### Describe the bug

 - Node.js version: 12.10.0
 - OS & version: mac OS 10.14.6

#### Actual behavior
```js
  timings: {
    start: 1568655873107,
    socket: 1568655873107,
    lookup: 1568655873121,
    connect: 1568655873121,
    upload: 1568655873121,
    response: null,
    end: null,
    error: null,
    phases: {
      wait: 0,
      dns: 14,
      tcp: 0,
      request: 0,
      firstByte: null,
      download: null,
      total: null
    }
  },
```

#### Expected behavior
No `null` values.

#### Code to reproduce

```js
require('got').stream('http://google.com').on('response', ({timings}) => console.log(timings)); null;
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Try using `@szmarczak/http-timer@2.0.0`

**Comment by szmarczak** [comment]
And yours code does nothing. Running it doesn't output anything. Please include reproducible code.

**Comment by stevenvachon** [comment]
Original comment updated.

**Comment by szmarczak** [comment]
This is not actually a bug. The `response` event for `http-timer` is executed **after** your `response` handler. Wrapping it in `process.nextTick` works:

```
    process.nextTick(() => {
        console.log(response.timings);
    });
```

I just need to use [`emitter.prependOnceListener(eventName, listener)`](https://nodejs.org/api/events.html#events_emitter_prependoncelistener_eventname_listener).

**Comment by szmarczak** [comment]
If you're interested you can send a PR for https://github.com/szmarczak/http-timer/issues/7 otherwise I'll do it tomorrow as it's late here.

**Comment by stevenvachon** [comment]
Thank you

**Comment by szmarczak** [comment]
You still need to wait for Got 10 or force Got 9 to use `@szmarczak/http-timer@3.0.0`.
