### ISSUE TITLE
Got v10 beta feedback

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#876]
This issue is for discussing the upcoming Got v10 version which is now in ~alpha~ beta.

Beta 1: https://github.com/sindresorhus/got/releases/tag/v10.0.0-beta.1

Let us know if you encounter any issues with upgrading or if anything is unclear in the release notes.

**Comment by kevva** [comment]
Just an FYI, but after installing the `dist` folder looks like this:

![image](https://user-images.githubusercontent.com/709159/65034336-1c2b0e80-d947-11e9-994b-58c792931787.png)

**Comment by sindresorhus** [comment]
@kevva Weird. I manually fixed it:

```
$ npm install got@10.0.0-alpha.1.1
```

or 

```
$ npm install got@next
```

**Comment by matus123** [comment]
Hi, i would like to report some issues... i don't know if this was desired.

### cannot specify own statusCodes in retry object (typescript error)
```
const test = got.create({
            options: {
                retry: {
                    statusCodes: [401],
                },
            },
        });

        got('http://localhost:5000', {
            retry: {
                statusCodes: [401],
            },
        });
```
### afterResponse hooks cannot return promise (typescript error)
```
        const test = got.create({
            options: {
                hooks: {
                    afterResponse: [
                        async (response, retry) => {
                            const options = response.request.options;
                            await doSomethingAsync();
                            return retry(options);
                        },
                    ],
                },
            },
        });
```

**Comment by jaulz** [comment]
I raised a PR for the second issue here: https://github.com/sindresorhus/got/pull/883

**Comment by szmarczak** [comment]
@jaulz Great! What about `cannot specify own statusCodes in retry object (typescript error)`?

**Comment by jaulz** [comment]
@szmarczak just created another PR for it 😊 Also could we export the types from a central place? Currently, it imports the types from multiple files and the dist folder which looks quite confusing and untypical.

```
import { CancelableRequest, Response } from 'got/dist/utils/types'
import { Got, GotStream } from 'got/dist/create'
import { ProxyStream } from 'got/dist/as-stream'
```

**Comment by sindresorhus** [comment]
@jaulz Yes, we should re-export all relevant types in https://github.com/sindresorhus/got/blob/master/source/index.ts You should not have to go digging into the folder structure.

**Comment by jaulz** [comment]
@sindresorhus is that something you are already working on or should I raise a PR?

**Comment by sindresorhus** [comment]
@jaulz A PR would be great. You know better that us what types you need exported.

**Comment by jaulz** [comment]
Okay, will tackle it next week 😊

**Comment by Feverqwe** [comment]
I think error (via util.inspect) has less information, before I can see url, body, and gotOptions
```
{ HTTPError: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (/home/user/project/node_modules/got/dist/as-promise.js:91:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError' }
```

p.s. response.request.gotOptions was moved to response.request.options (migrate manual don't have this info)

**Comment by szmarczak** [comment]
@Feverqwe read it again:

> Move top-level error properties into an .options and .response property (#773) 6eaa81b
> Migrate:
> ```diff
> - error.gotOptions
> + error.options
> ```

**Comment by Feverqwe** [comment]
> @Feverqwe read it again:
> 
> > Move top-level error properties into an .options and .response property (#773) [6eaa81b](https://github.com/sindresorhus/got/commit/6eaa81ba8db87340bbdbd79ef91594803f37b854)
> > Migrate:
> > ```diff
> > - error.gotOptions
> > + error.options
> > ```

I have debug for logging, and in log I ses less information for debug and fix error. I don't see stack, I don't see request url and etc.

**Comment by szmarczak** [comment]
Ah you meant the `gotRequest` thing...

**Comment by szmarczak** [comment]
> I have debug for logging, and in log I see less information for debug and fix error. I don't see stack (like before), I don't see request url and etc.

Runkit example please? It works be much easier to figure things out.

**Comment by Feverqwe** [comment]
Example:
```
const {inspect} = require('util');
const got = require('got');

got('https://httpstat.us/500?sleep=1000').catch(err => console.log(inspect(err)));
```
Result:
```
{ HTTPError: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (D:\Downloads\temp\example\node_modules\got\dist\as-promise.js:91:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError' }
```

**Comment by gzaripov** [comment]
I tried got@10 and I stumbled upon this error
`'url' must not begin with a slash when using 'prefixUrl'`.
It looks weird for me, it is common use case when I make a `Transport` abstraction in my app and use relative urls in many places with relative urls. And it is important to have leading slash because it gives reader knowledge that this is a relative url.

What are cons of allowing leading slash when using prefixUrl?

**Comment by SamHH** [comment]
Not sure if this has been raised yet or if it'd be considered a bug, but with the v10 alpha the `dom` property is required in `lib` in `tsconfig.json` due to the use of `URLSearchParams`, an ambient which `dom` provides. Given that this project is targeted at Node.js, the `dom` property really shouldn't be required. Instead, it'd probably make more sense to pull that interface from `@types/node`, which I _think_ exposes it, or to simply copy/paste it in.

**Comment by jaulz** [comment]
@SamHH can you please raise a PR for it?

**Comment by SamHH** [comment]
@jaulz Sure, I'll give it a go this evening.

**Comment by Feverqwe** [comment]
Error `Cannot read property 'request' of undefined` in render process. 
```js
requestFn = electron.net.request || electron.remote.net.request;
```
Maybe it shoud be
```js
requestFn = electron.remote && electron.remote.net.request || electron.net.request;
```

**Comment by szmarczak** [comment]
@Feverqwe currently electron support is broken for now. It would be great if you could make a PR.

**Comment by sindresorhus** [comment]
Alpha 3 is out: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.3

**Comment by sindresorhus** [comment]
Beta 1 is out: https://github.com/sindresorhus/got/releases/tag/v10.0.0-beta.1

The final release is getting closer. The only remaining tasks are https://github.com/sindresorhus/got/pull/928 and https://github.com/sindresorhus/got/pull/935.

**Comment by gzaripov** [comment]
@sindresorhus what do you think about it https://github.com/sindresorhus/got/issues/876#issuecomment-536603384 ?

In 10.x we will have prefixUrl that doesn't cover cases of base url such as passing url with starting slashes. Also it is not just prefix because got will add slash to it. What kind of problems does it solve then?

**Comment by yovanoc** [comment]
Since this beta 1 version I have a really weird issue, all my requests with got are failing with this: `ECONNREFUSED 127.0.0.1:443` but all links are not localhost, they are only https remote calls

**Comment by gajus** [comment]
> Since this beta 1 version I have a really weird issue, all my requests with got are failing with this: ECONNREFUSED 127.0.0.1:443 but all links are not localhost, they are only https remote calls

Whatever is the change, but now [`http.Agent`](https://nodejs.org/api/http.html#http_class_http_agent)#`addRequest` is invoked without information about the request, i.e. `addRequest` second parameter gets:

```js
{
  protocol: undefined,
  hostname: undefined,
  hash: undefined,
  search: undefined,
  pathname: undefined,
  path: '',
  href: undefined,
  port: 443,
  headers: {
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
    'accept-encoding': 'gzip',
    'x-rayroute-country-code': 'us',
    'x-rayroute-session-id': 'event-seating-lookup:412400178',
    host: 'www.cinemark.com'
  },
  prefixUrl: '',
[..]
```

Looks like a bug.

**Comment by szmarczak** [comment]
@gzaripov 

>  What kind of problems does it solve then?

See #783 and https://github.com/sindresorhus/ky/pull/11

@yovanoc @gajus please include some reproducible code. All tests are passing.

**Comment by gajus** [comment]
After further debugging, my specific case was related to

https://github.com/TooTallNate/node-https-proxy-agent

For some reason when an instance of `node-https-proxy-agent` was configured as agent in `got` options, the original request properties were no longer available to [`global-agent`](https://github.com/gajus/global-agent).

**Comment by szmarczak** [comment]
We no longer support legacy Url options. If one of the options is present when normalizing URL, it throws. We're going to deprecate [the new] URL options in Got v11 or v12. This is because we're using `request(normalizedUrl, options, responseCallback)` instead of `request(normalizedOptions, responseCallback)`.

**Comment by szmarczak** [comment]
But `request` normalizes the options and calls `addRequest` with the normalized options so there should be a `pathname` property etc...

**Comment by sindresorhus** [comment]
@gzaripov Sorry, I missed your first comment.

> I tried got@10 and I stumbled upon this error
'url' must not begin with a slash when using 'prefixUrl'.
It looks weird for me, it is common use case when I make a Transport abstraction in my app and use it in many places with relative urls. And it is important to have leading slash because it gives reader knowledge that this is a relative url.

The limitation is in place to prevent confusion. Let's say you have a prefix URL `https://example.com/foo`. If we allowed the input URL to be `/bar`, there's ambiguity whether the resulting URL would become `https://example.com/foo/bar` or `https://example.com/bar`. In the browser, the URL resolution works like the latter, where `/bar` resolves to `https://example.com/bar`, but that's not how our `prefixUrl` implementation works, and why we don't allow leading `/`.

We should indeed better document the reasoning for this.

**Comment by sindresorhus** [comment]
> Since this beta 1 version I have a really weird issue, all my requests with got are failing with this: ECONNREFUSED 127.0.0.1:443 but all links are not localhost, they are only https remote calls

@yovanoc Can you try to make a minimal test case that reproduces the issue? https://runkit.com/ is good for this.

**Comment by yovanoc** [comment]
I can't reproduce it in runkit... even in my project I can't find when it happens exactly... i will try more but hope you will find it

**Comment by yovanoc** [comment]
It seems that when got is imported in a project that also performs raw websocket calls, got throw this error (when we perform the websocket send).

**Comment by yovanoc** [comment]
Sorry for spamming, actually it's the init() from @sentry/node ... When I call this `init` all calls with got are failing. I hope you will find why :)

**Comment by gajus** [comment]
> Sorry for spamming, actually it's the init() from @sentry/node ... When I call this init all following calls with got are failing. I hope you will find why :)

Interesting, and might explain my case too. This was only happening in environment where Sentry is enabled.

**Comment by sindresorhus** [comment]
Sentry does a lot of awful swizzling, from what I can remember. I wouldn’t be surprised if they incorrectly changes an assumption Got depends on.

**Comment by ianbytchek** [comment]
Same issue as @yovanoc, the same code from example. The error doesn't seem to contain request or response body.

```ts
try {
    const response = await got('https://sindresorhus.com');
} catch (error) {
    console.log(error);
}
```

```
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.onError (/…/node_modules/got/dist/source/request-as-event-emitter.js:135:29)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at ClientRequest.origin.emit (/…/node_modules/@szmarczak/http-timer/source/index.ts:75:11)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'RequestError',
  code: 'ECONNREFUSED'
}
```

It looks like there were attempts to reproduce it without much luck. Is there a quick way to test this with webpack? If not, I'll try putting this into a separate project over the weekend. P. S. Also using serverless-offline.

**Comment by sindresorhus** [comment]
The error contains the request and response, it’s just not enumerable.

**Comment by ianbytchek** [comment]
I know it should. I tried `error.request` and `error.response` in attempt to find out more and got `null` or `undefined` in both cases, can't remember which one for sure. It seems something goes wrong at the very core.

**Comment by szmarczak** [comment]
@yovanoc @gajus Can you try latest master commit? It might be caused by `request._header` but it's not used anymore at all.

**Comment by yovanoc** [comment]
It's annoying to install from master because we have to manually build got inside node_modules but yes i'm gonna try

**Comment by szmarczak** [comment]
@yovanoc You can just download Got, run `npm build` and instead of `require('got')` you can do `require('/path/to/local/got')` ;)

**Comment by yovanoc** [comment]
```
[RequestError]: Cannot read property 'on' of undefined
```

that's what I got from master, and yeah that's what I will do from now ^^

**Comment by szmarczak** [comment]
Stacktrace please?

**Comment by yovanoc** [comment]
Oh 2 errors now, and I would say that all was fine before beta1 and this master test without any code change.

<img width="1135" alt="Screen Shot 2019-11-22 at 11 11 23 PM" src="https://user-images.githubusercontent.com/7302317/69464118-c414ec00-0d7d-11ea-9b62-1fef59ef3d79.png">

**Comment by szmarczak** [comment]
Weird... Can you paste the 125 and 152 line of `dist/source/request-as-event-emitter.js` (these point to nowhere on my side)

**Comment by yovanoc** [comment]
![image](https://user-images.githubusercontent.com/7302317/69464852-d42dcb00-0d7f-11ea-9d3c-9901766aa32a.png)

**Comment by szmarczak** [comment]
I don't see any `on` property being called here :thinking:
If you could paste some reproducible code, that would be awesome :+1:

**Comment by yovanoc** [comment]
That's the error thrown at this place, and not at this place I think. It's time for me to go to bed but I will do it later, thanks

**Comment by szmarczak** [comment]
Ah, #935 is not yet merged so you need to place `console.log(error)` before line 125 ;)

**Comment by yovanoc** [comment]
<img width="1138" alt="Screen Shot 2019-11-22 at 11 45 08 PM" src="https://user-images.githubusercontent.com/7302317/69465735-3c7dac00-0d82-11ea-874c-1b56a4fe3120.png">

**Comment by gajus** [comment]
```js
const got = require('got');
const HttpsProxyAgent = require('https-proxy-agent');

const agent = new HttpsProxyAgent('http://127.0.0.1:8000');

const main = async () => {
    await got('https://example.com', {
        agent,
    });
};

main();

```

Likely related to this issue, this code currently exits without executing anything, or at least without ever making a HTTP request.

**Comment by yovanoc** [comment]
Oh nevermind that was my fault but I think you should maybe throw an explicit error for that because it doesn't fail before it was just ignoring. I had a `cache` in a post method, just removing that and works perfectly

**Comment by szmarczak** [comment]
> I had a cache in a post method, just removing that and works perfectly

Can you include some code please?

**Comment by yovanoc** [comment]
```ts
const cache = new Map();

const body = await got
    .post(req, {
      // cache,
      retry: 4,
      headers: {
        "Content-Type": "application/json"
      },
      json
    })
    .json();
```
I had a cache in this request, just comment it and all works fine now.

Btw,  in the doc:

![image](https://user-images.githubusercontent.com/7302317/69478430-7ab2b400-0df2-11ea-9519-be30f8cade8f.png)

should be `body` not `{ body }` right?

**Comment by szmarczak** [comment]
No, it should be `{body}` because it's destructuring.

**Comment by szmarczak** [comment]
@gajus The latest master gives me this:

`RequestError: connect ECONNREFUSED 127.0.0.1:8000` (as expected)

**Comment by szmarczak** [comment]
@yovanoc Nah, you're right. It should be `body` because there's `.json()` already.

**Comment by szmarczak** [comment]
@yovanoc What did cause `[RequestError]: Cannot read property 'on' of undefined`? Is it Got-related code or yours?

**Comment by yovanoc** [comment]
I think is got, like I said I just remove the cache that I put in the post request (my bad) and now all is working perfectly

**Comment by ianbytchek** [comment]
Also tried putting this in an isolated project and there's some really weird 💩 going on, [Got#876.zip](https://github.com/sindresorhus/got/files/3882466/Got.876.zip) – unfortunately it's a heavy setup with serverless & webpack. To get the crash: `npm run start` and `curl 'http://localhost:3000'`. Observations:

1. Switching to latest alpha works as expected.
2. Also works without the serverless layer, e.g., starting express server with `app.listen(…)`.
3. Serverless does the external modules packaging, switching to packaging everything with webpack makes no difference.
4. Based on no. 2, got and sls share some common layer which might be the problem?

**Comment by szmarczak** [comment]
@ianbytchek I don't have `sls` installed. Can you try to reproduce it with master please?

**Comment by szmarczak** [comment]
> I think is got, like I said I just remove the cache that I put in the post request (my bad) and now all is working perfectly

Could you provide a RunKit example? I cannot reproduce it on my own.

**Comment by gajus** [comment]
> @gajus The latest master gives me this:
> 
> RequestError: connect ECONNREFUSED 127.0.0.1:8000 (as expected)

I was testing against the latest release.`^10.0.0-beta.1`

I have just tested against the master, and it fails too, but for a different reason:

<img width="1920" alt="Screenshot 2019-11-23 at 13 30 17" src="https://user-images.githubusercontent.com/973543/69479473-68864500-0df5-11ea-94a4-4f42cae9fbd0.png">

There is clearly a problem.

**Comment by szmarczak** [comment]
@gajus Do you have a server listening on port 8000? What's the source code?

**Comment by gajus** [comment]
> @gajus Do you have a server listening on port 8000? What's the source code?

The window on right is an instance of https://mitmproxy.org/ listening on port 8000.

The http://localhost:433 request is the actual intercepted request.

There is nothing in between, just this [code](https://github.com/sindresorhus/got/issues/876#issuecomment-557738788) to make the request and mitmproxy.

I have tested with different proxies, though – it fails with the same error.

**Comment by szmarczak** [comment]
Ok, investigating right now. Thanks for letting me know.

**Comment by szmarczak** [comment]
Found the cause, and it's not Got: https://github.com/sindresorhus/got/issues/941#issuecomment-557818133

**Comment by szmarczak** [comment]
@yovanoc The culprit is [this](https://github.com/nodejs/node/blob/8acb646478e13fb61fc844c6f873032992674ae5/lib/internal/streams/pipeline.js#L23). It seems that [`httpOptions.body`](https://github.com/sindresorhus/got/blob/d0f2dfdd1e3fbec3dba910c4948574253c584305/source/request-as-event-emitter.ts#L181-L186) is undefined in some cases (?).

**Comment by szmarczak** [comment]
But that's impossible. Dunno. It'd be best to have some reproducible code.

**Comment by sindresorhus** [comment]
Beta 2 is out: https://github.com/sindresorhus/got/releases/tag/v10.0.0-beta.2

**Comment by kennethaasan** [comment]
I tested Beta 2, but are getting this error:

```
GotError: The "listener" argument must be of type Function. Received type object
   at get (/home/node/app/node_modules/got/dist/source/request-as-event-emitter.js:187:27)
   at runNextTicks (internal/process/task_queues.js:58:5)
   at processImmediate (internal/timers.js:412:9)
   at async /home/node/app/node_modules/got/dist/source/request-as-event-emitter.js:248:13
   at checkListener (events.js:64:11)
   at ClientRequest.once (events.js:313:3)
   at new ClientRequest (_http_client.js:177:10)
   at Object.request (https.js:309:10)
   at Object.<anonymous> (/home/node/app/node_modules/agent-base/patch-core.js:25:22)
```

Running on node:12-alpine3.9 (https://github.com/nodejs/docker-node/blob/4f49f67ebd8d577dd7c97dabf5df69e6d947406c/12/alpine3.9/Dockerfile)

**Comment by rebolyte** [comment]
Using `10.0.0-beta.2` and TypeScript, there appear to be some missing types:

```sh
../../node_modules/got/dist/source/utils/options-to-url.d.ts:12:71 - error TS2304: Cannot find name 'URLSearchParams'.

12     searchParams?: Record<string, string | number | boolean | null> | URLSearchParams | string;
                                                                         ~~~~~~~~~~~~~~~

../../node_modules/got/dist/source/utils/options-to-url.d.ts:15:50 - error TS2304: Cannot find name 'URL'.

15 declare const _default: (options: URLOptions) => URL;
                                                    ~~~
...
```

**Comment by sindresorhus** [comment]
@rebolyte That’s a DefinitelyTyped bug: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960

**Comment by szmarczak** [comment]
@kennethaasan This is not a Got issue. Got uses the Node.js 10 API, and some agents don't support it - they overwrite `http.request` and `https.request` with only two arguments: `options` and `callback`, while Got provides `url`, `options` and `callback`.

**Comment by sindresorhus** [comment]
@szmarczak Maybe we should document in the readme known incompatible agents? And we should include it in the Got 10 release notes.

**Comment by sindresorhus** [comment]
@kennethaasan @gajus Please open an issue on`https-proxy-agent` and `agentkeepalive` about supporting the Node.js 10 API.

**Comment by sindresorhus** [comment]
Got v10 is finally out: https://github.com/sindresorhus/got/releases/tag/v10.0.0

Open individual issues for new bugs, features, etc.

**Comment by kennethaasan** [comment]
Btw, my error above is also related to using New Relic (https://github.com/newrelic/node-newrelic)

**Comment by arcanis** [comment]
> This is not a Got issue. Got uses the Node.js 10 API, and some agents don't support it - they overwrite `http.request` and `https.request` with only two arguments: `options` and `callback`, while Got provides `url`, `options` and `callback`.

Fwiw I got this error with `got.post`, and reverting to 9 worked. I don't use agents.

**Comment by szmarczak** [comment]
@arcanis A runkit example would be lovely.

**Comment by arcanis** [comment]
It doesn't repro on runkit. After investigating a bit it seems to be related to Jest, although I don't know if the bug comes from Jest or Got. Repro:

```
yarn init -y
yarn add jest got
```

**foo.js**

```js
const got = require(`got`);
got.post(`https://httpbin.org`, {
    responseType: `json`,
    json: {}
});
```

**foo.test.js**

```js
test(`foo`, () => {
    require(`./foo`);
});
```

Running with `node ./foo.js` yields an HTTP 405 (which is ok), whereas running `yarn jest` yields the error aforementioned ("The "listener" argument must be of type Function").

**Comment by gajus** [comment]
In all of the reported cases, it is safe to assume that something in your dependency chain is overriding `http.request`. Given that this is such a common problem, I think it is very stubborn of Got maintainers not to recognize that it is a backwards incompatibility issue.

**Comment by Mathspy** [comment]
v10 is a major version bump (AKA potential backwards incompatible) and @sindresorhus mentioned that it might be a good idea to document incomparable agents/libraries
I don't think there's much the library maintainers can do in this situation besides document incompatible libraries/agents/frameworks

**Comment by gajus** [comment]
> I don't think there's much the library maintainers can do in this situation besides document incompatible libraries/agents/frameworks

It is literally couple of lines of code to make it backwards compatible. The only reason it is not done, is because Got v10 intentionally drops < Node.js v10 support.

**Comment by szmarczak** [comment]
Also we want to drop legacy Url support, hence the URL instance (`options.url`).

**Comment by Mathspy** [comment]
That's an explicit decision from the maintainers that has several clear advantages like less maintenance burden, as well as stability on got v10 for the foreseeable future (instead of being forced to release v11 when they eventually decide to drop support for node v8) 
Plus node v8's LTS is dropping at the end of 2019 so there isn't much of a reason to remain compatible with it

**Comment by gajus** [comment]
Sure, it is just that this will result in one of the two scenarios:

1. People are not going to update to Got v10, because most of the applications will have a dependency in their tree that breaks Got.
2. Someone is going to kick off a fork of got.

**Comment by szmarczak** [comment]
> People are not going to update to Got v10, because most of the applications will have a dependency in their tree that breaks Got.

That's their responsibility to be up to date with Got.

**Comment by szmarczak** [comment]
The first alpha release was in September so there was plenty of time to adjust the code.

**Comment by yovanoc** [comment]
@szmarczak Yeah you're right but I know what he want to say, it can be hard in a project with multiple dependencies to tell each author to update their codes

**Comment by szmarczak** [comment]
You can fix this using a `beforeRequest` hook. Just normalize `options.url` using `urlToOptions` and merge the properties into options.

**Comment by Mathspy** [comment]
> 1. People are not going to update to Got v10, because most of the applications will have a dependency in their tree that breaks Got.
> 2. Someone is going to kick off a fork of got.


I don't see either of these as a bad thing, it's totally okay to rely on got v9 for few more months until dependencies have updated, and during that time it'd be great to open PRs against those dependencies making them compatible!
And it's totally fine for someone to fork `got` temporary! The maintenance burden falls back on them and they can keep the fork until eventually dependencies have all updated and the fork's goal no longer exists (though if they have a reason to keep it longer, its their burden and its their freedom, of course!)

**Comment by djpate** [comment]
> You can fix this using a `beforeRequest` hook. Just normalize `options.url` using `urlToOptions` and merge the properties into options.

Can you elaborate? Trying to use this with serverless and I've been banging my head

**Comment by szmarczak** [comment]
> Can you elaborate?

Umm... It's plain English, but here's the same sentence in Node.js:

https://runkit.com/szmarczak/5e1a212ef1a19c001a0e5fce

**Comment by szmarczak** [comment]
Updated that runkit example. Note that it doesn't pass `request` as a second argument, but a third.

**Comment by szmarczak** [comment]
@arcanis @djpate Here's the solution which should work, it uses `options.request`: https://runkit.com/szmarczak/5e1a23d8e4d193001a709110

**Comment by djpate** [comment]
@szmarczak Thanks for the code.

**Comment by szmarczak** [comment]
You may be wondering why we don't do that: it's because we want to get rid of urlToOptions to remove legacy URL usage completely.
