### ISSUE TITLE
beforeRequest hooks always has `GET` as request method 

### ISSUE THREAD

**Issue by pociej** [sindresorhus/got#878]
#### Describe the bug

 - Node.js version: 10.16.3 
 - OS & version: OSX 10.13.5 

#### Actual behaviour

`beforeRequestHook` shows that `req.method`  is `GET` even if other type of request has been made.  Additionally request body is not presented but most likely its because of first bug. 

#### Expected behaviour

 Hook shows proper value `req.method` 
...

#### Code to reproduce

```js
const got = require("got");

got("https://example.com", {
  hooks: {
    beforeRequest: [
      req => {
        //this always logs GET 
        console.log("req", req.method);
      }
    ]
  }
});

got({
  url: "https://example.com",
  method: "POST"
});
```

**Comment by tobenna** [comment]
It'll always log as **GET** because got by [default](https://github.com/sindresorhus/got#api) will make a get request.

The second request you're making isn't using the same options as the first so it won't have the hook you wrote.

If you want to reuse the same instance for future requests:

```ts
const got = require("got");

const intsance = got.extend({
  hooks: {
    beforeRequest: [
      req => {
        console.log("req", req.method);
      }
    ]
  }
});

intance({
  url: "https://example.com",
  method: "POST"
});


```

**Comment by pociej** [comment]
So what if i wanna hook into all the request to given address without worrying of instance ( many instances of got even used by external package ) ? 
Hook into node native http ?

**Comment by szmarczak** [comment]
You need to extend the Got instance and use that one. Everything is in the docs.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/master/readme.md#context

**Comment by sindresorhus** [comment]
Global hooks is not something we're interested in adding. It comes with more problems than it solves.

**Comment by pociej** [comment]
> Global hooks is not something we're interested in adding. It comes with more problems than it solves.

@sindresorhus you know your stuff better than me so you are probably right. However i don't see those problems. From other hand i can show you real case where global hook is needed. 
My case is that package A is wrapper on external API and provides method `myAPI.myResource.get()` which is wrapper on HTTP call using `got`. Then package B makes use of A and function `myFunction` at some point calls `myAPI.myResource.get()` and we want to test package B, to be sure that `myFunction` works as it should i want, among others, to be sure that HTTP call is done properly. Package A do not expose the `got` instance so i have no access to it. Ideal solution to test if HTTP request is send as it should be is global hook registered for related API url. 
Like : 
`got.globalHook('https://myAPI/myResource/myId.json', (req) => { doWhatYouNeedWithReq })`

**Comment by sindresorhus** [comment]
I think you want https://github.com/nock/nock

**Comment by pociej** [comment]
Well nock is mocking library, so i can mock what will be returned by `https://myAPI/myResource/myId.json` but it cant give me control of what was send to this url. 
Maybe thats bet i used `GET` request example. Lets say we are in case of POST. Nock gives us mock of what will be returned but not check of request body before request send. What we want to test is this request body.

**Comment by kevva** [comment]
https://github.com/nock/nock#specifying-request-body
