### ISSUE TITLE
Replace tough-cookie

### ISSUE THREAD

**Issue by Rokt33r** [sindresorhus/got#882]
#### What problem are you trying to solve?

I'm back from here. https://github.com/sindresorhus/got/issues/811
It is an issue of tough-cookie library. But the fix is in stale status for several months...

#### Describe the feature

So I'm thinking it would be really nice if `got` provides an abstract interface so I can use other cookie store than tough-cookie.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Out of curiosity, what other cookie storage would you use?

**Comment by szmarczak** [comment]
> It is an issue of tough-cookie library. But the fix is in stale status for several months...

https://github.com/salesforce/tough-cookie/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+author%3ARokt33r

You haven't opened such issue.  Not to mention that `tough-cookie` is RFC-compliant.

**Comment by tobenna** [comment]
I think @Rokt33r is referring to https://github.com/salesforce/tough-cookie/pull/130

**Comment by szmarczak** [comment]
Ah. In this case I would just open a new PR. The fix is very simple.

**Comment by szmarczak** [comment]
> So I'm thinking it would be really nice if got provides an abstract interface so I can use other cookie store than tough-cookie.

You just need to pass an object having these and you're good to go:

https://github.com/sindresorhus/got/blob/f59a5638b93c450dc722848b58b09a44f730a66f/source/request-as-event-emitter.ts#L49-L50

**Comment by Rokt33r** [comment]
@sindresorhus I'm not using any for now. But if `got` makes it possible, I would have options to fork tough-cookie or to make another one from the scratch.

@szmarczak I think we need to define cookieJar interface in this package too. Otherwise, I still need to install @types/tough-cookie every time.

Also it would be awesome if the new interface's methods return Promise rather than accepting callback although it should be breaking change...

**Comment by szmarczak** [comment]
> I think we need to define cookieJar interface in this package too. Otherwise, I still need to install @types/tough-cookie every time.

:+1:

> Also it would be awesome if the new interface's methods return Promise rather than accepting callback although it should be breaking change...

I agree. Maybe we'll see these promises in Got v11. Let's stay with the callbacks for now.

**Comment by sindresorhus** [comment]
@szmarczak It would be nice not to be so tied to `tough-cookie`. We could maybe support both though. Detect whether the input is `tough.CookieJar` and if not, have a nicer general interface using promises. ?
