### ISSUE TITLE
Cannot write to stream

### ISSUE THREAD

**Issue by sayem314** [sindresorhus/got#886]
code example
```js
'use strict';

const { existsSync, statSync, createWriteStream } = require('fs');
const got = require('got');

const download = async (url, dest, callback, bytes = 0) => {
  try {
    if (existsSync(dest)) {
      const { size } = statSync(dest);
      bytes = size + 1;
    }
    await got
      .stream(url, { headers: { Range: 'bytes=' + bytes + '-' } })
      .on('downloadProgress', callback)
      .pipe(createWriteStream(dest));
    return dest;
  } catch (err) {
    throw err;
  }
};
```

got downloads, reports progress but cannot pipe to file

**Comment by szmarczak** [comment]
> cannot pipe to file

please elaborate.

It would be very useful if you filled the issue template.

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and we'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.
