### ISSUE TITLE
Why is not the query string attached to the url

### ISSUE THREAD

**Issue by vongohren** [sindresorhus/got#888]
#### What would you like to discuss?
Im trying to use query option, which in 10.0.0 will be called searchParams.
https://github.com/sindresorhus/got#searchparams

I tried this code, but the query string is never appended to the URL
```
    const api = 'https://myapi/1/search'
    const searchParam = new URLSearchParams([['query', aStringSearchQuery]])
    console.log(searchParam.toString()); //query=theStringToSearchFor
    const json = await got(`${api}`, {query: searchParam});
    //- URL: "https://myapi/1/search"
```
I tried with a simple string and everything

Why not? Am I using it wrong?

...

#### Checklist

- [ x ] I have read the documentation.

**Comment by sindresorhus** [comment]
Are you using the alpha of v10? https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1

**Comment by vongohren** [comment]
@sindresorhus no im currently on 9.6.0. Sorry for not mentioning that. But tought it was clear as I mentioned that it will switch to searchParams in 10.0.0

**Comment by zzyyxxww** [comment]
@sindresorhus today I used 9.6.0 with the alpha docs thinking "I finally found one sindre module that isn't awesome". works great now.
I should have read the warning in the readme, but it might have been easier to catch if it was at the topmost, or at least next to a ⚠️.

**Comment by vongohren** [comment]
Could we try to figure out why its happening? Did it work for you @zzyyxxww?

**Comment by zzyyxxww** [comment]
you need to install the alpha version, for yarn I ran `yarn add got@10.0.0-alpha.1.1`.

**Comment by vongohren** [comment]
But I dont want to run an alpha version. I would expect the stable 9.6.0 would work

**Comment by zzyyxxww** [comment]
@vongohren then use the documentation for v9
https://github.com/sindresorhus/got/blob/v9.6.0/readme.md

**Comment by vongohren** [comment]
@zzyyxxww i am using that, if you look at my code and the code for 9.6.0

```
const got = require('got');

const query = new URLSearchParams([['key', 'a'], ['key', 'b']]);

got('https://example.com', {query});

console.log(query.toString());
```

Its the same. So please read the issue before making assumptions

**Comment by zzyyxxww** [comment]
Both your code and the code from the readme is working as expected for 9.6.0, I created a project for you to test.
https://github.com/zzyyxxww/got-9.6.0-search-params

> no im currently on 9.6.0.
I'm making assumptions based on what you write. When you said you were on 9.6.0, I assumed you were on 9.6.0. Can you confirm you are in fact in 9.6.0?

**Comment by Zyles** [comment]
I too seem to have this problem on latest alpha.

I can't access URLs that require a token in the query and get 401 unauthorized and failed requests.

**Comment by szmarczak** [comment]
I don't know what are you doing wrong, for me it works as expected:

https://runkit.com/szmarczak/5db2b922ae6c4e001adf480f
