### ISSUE TITLE
Minimize the browserified size

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#89]
Turns out some people use this with `browserify`, but by default `got` is huge when browserified, since it includes the `buffer` browser polyfill and other things. We should look into if there's any way to get it down without too much work.

Relevant: https://twitter.com/mattdesl/status/624703076159590400

Not sure, but this might be useful: https://github.com/miguelmota/buffer-to-arraybuffer

**Comment by floatdrop** [comment]
Full list of browserified modules: https://gist.github.com/floatdrop/acfb074b261288655e45

Top of size-eaters:

* browserify-zlib is 173.3 Kb
* duplexify is 64.9 Kb
* buffer is 43.7 Kb

**Comment by mattdesl** [comment]
:+1: 

I started [got-xhr](https://github.com/Jam3/got-xhr) for this reason but haven't published it yet. If possible, I would rather build on an existing module than add more clutter to npm.

But with that said, it might be necessary to have a separate `got`-like module that has a more limited scope than `got`. Things like: 

- avoiding Buffer, and instead using ArrayBuffer since it is more common in the browser
- avoiding zlib, since the browser handles gzip for us anyways (from what I understand?)
- avoiding streams entirely
- just using [xhr](https://www.npmjs.com/package/xhr) under the hood

**Comment by mattdesl** [comment]
Update: I'm now using [xhr-request](https://github.com/Jam3/xhr-request) in node/browser for non-streamed requests. 

For streamed requests, [simple-get](https://github.com/feross/simple-get) is pretty good, and half the size of `got`.

`got` could probably be almost as small as `simple-get` by doing something like this:
https://github.com/feross/simple-get/blob/d212b1022d21b49c8ec83acf251d1dc4aeb38ca3/package.json#L10-L12

**Comment by kevva** [comment]
https://github.com/sindresorhus/got/commit/66542fd92b95fbcb4be9550850a59aa557f33465 reduced the size from 471 KB to 268 KB.

**Comment by floatdrop** [comment]
With `6.0.0` version got is almost same size as simple-get, but still 10x bigger than `xhr`.

```
❯ browserify -r simple-get | wc -c
  194566

❯ browserify -r got | wc -c
  207787

❯ browserify -r xhr | wc -c
   11147
```

**Comment by sindresorhus** [comment]
@floatdrop Woot! Try [gzipping](https://github.com/sindresorhus/gzip-size-cli) too. That gives more accurate numbers.

**Comment by mattdesl** [comment]
Nice!

gzip can be misleading when you are considering how bundle size affects parse/execution time. :smile:

More details:
https://timkadlec.com/2014/09/js-parse-and-execution-time/

**Comment by mattdesl** [comment]
But you should probably include `uglifyjs -cm` to get a better idea.

**Comment by mattdesl** [comment]
p.s. You can't run `got` through `uglify-js` right now because it has some ES6-isms (which also means it will break on safari, IE and the likes).

```sh
 browserify -r got | uglifyjs -cm | wc -c
Parse error at -:7172,5
Unexpected token: name (redirectCount)
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/matt/npm/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
   ...
```

**Comment by thisconnect** [comment]
@mattdesl about Unexpected token: name (redirectCount) it is caused by `let`, see https://github.com/mishoo/UglifyJS2/issues/887
