### ISSUE TITLE
PUT request with option `JSON: true` throws `ParseError: Unexpected token O in JSON at position 0`

### ISSUE THREAD

**Issue by AlbertEmil** [sindresorhus/got#892]
I am currently implementing some PUT requests and encountered some weird (at least to me) behaviour: When trying to send some JSON-formatted payload through a PUT request, a `ParseError` will be raised:

> ParseError: Unexpected token O in JSON at position 0

The code snippet for reference is as follows:

```
const updateRecord = async (studentId, record) => {
    const response = await got(someUrl, {
        method: 'PUT',
        json: true,
        body: record,
    })
    return response.body;
}
```

Since `json` option is set to true, the argument passed to the `body` should be parsed automatically into a string as [stated in the docs](https://github.com/sindresorhus/got#json-mode). However, this does not seem to work for PUT requests and the mentioned error is thrown. In addition, the same behaviour can be reproduced by using:

```
const updateRecord = async (studentId, record) => {
    const response = await got(someUrl, {
        method: 'PUT',
        json: record,
    })
    return response.body;
}
```

The only way I was able to circumvent the error is as follows:

```
const updateRecord = async (studentId, record) => {
    const response = await got(someUrl, {
        method: 'PUT',
        body: JSON.stringify(record),
    })
    return response.body;
}
```

However, this does not seem to be a desired behaviour since `JSON.stringify(record)` should be called by either providing `json: True` or `json: <object>` [as per documentation](https://github.com/sindresorhus/got#json-mode). 

Am I missing something here? Just started to begin using this otherwise lovely module...

**Comment by szmarczak** [comment]
In the latest alpha version `json` is an object.
