### ISSUE TITLE
Cache duration

### ISSUE THREAD

**Issue by Zyles** [sindresorhus/got#894]
#### What problem are you trying to solve?

I want to add a custom cache duration for requests despite what the server is telling me.

#### Describe the feature

Able to set the duration of a cached request.

Some data is not changed often and to make less requests across the network I want to cache the response for a longer period instead of having to build my own cache layer.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
Duplicate of #875
