### ISSUE TITLE
Support sending multiple headers with the same name

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#896]
I need to send a HTTP request with multiple headers of the same name, e.g.

```
x-foo: 1
x-foo: 2

```

For a bit of context, this is spec compliant request:

https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable

I have tried using an array (i.e. `{'x-foo': ['1', '2']}`), but that just sends a comma separated list of values under the same header, i.e.

```
x-foo: 1, 2

```

, which is not great, because if one of the values contains a comma, then it is impossible to distinguish the original values.

**Comment by szmarczak** [comment]
> then it is impossible to distinguish the original values.

then encode it.

**Comment by gajus** [comment]
> then encode it.

I don't control the server.

The API requires to send two headers.

**Comment by sindresorhus** [comment]
We should indeed support this. We should change it so that supplying an array causes it to create multiple headers. Node.js does support this already `request.setHeader('Cookie', ['type=ninja', 'language=javascript']);`, so we're probably just incorrectly stringifying the array somewhere.

PR welcome to fix this.

**Comment by szmarczak** [comment]
@gajus You're looking at parsed request received by the server. It **is** split into two headers:

```
> require('.')('https://httpbin.org/anything', {headers: {foo: ['bar1:1=1', 'bar2']}}).json().then(console.log)
Promise { <pending> }
> GET /anything HTTP/1.1
user-agent: got/10.0.0-alpha.3 (https://github.com/sindresorhus/got)
foo: bar1:1=1
foo: bar2
accept-encoding: gzip, deflate, br
accept: application/json
Host: httpbin.org
Connection: close


{
  args: {},
  data: '',
  files: {},
  form: {},
  headers: {
    Accept: 'application/json',
    'Accept-Encoding': 'gzip, deflate, br',
    Foo: 'bar1:1=1,bar2',
    Host: 'httpbin.org',
    'User-Agent': 'got/10.0.0-alpha.3 (https://github.com/sindresorhus/got)'
  },
  json: null,
  method: 'GET',
  origin: '185.54.56.146, 185.54.56.146',
  url: 'https://httpbin.org/anything'
}
```

```diff
$ git diff
diff --git a/source/request-as-event-emitter.ts b/source/request-as-event-emitter.ts
index af776b0..8197580 100644
--- a/source/request-as-event-emitter.ts
+++ b/source/request-as-event-emitter.ts
@@ -266,6 +266,9 @@ export default (options: NormalizedOptions, input?: TransformStream) => {
                        } catch (error) {
                                emitError(new RequestError(error, options));
                        }
+
+                       // @ts-ignore
+                       console.log(request._header);
                };
 
                if (options.cache) {
```
