### ISSUE TITLE
RequestError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by Zyles** [sindresorhus/got#901]
#### What would you like to discuss?

I can not seem to make a request. Using "got": "^9.6.0" and  "electron": "^5.0.11"

Error:

`RequestError: getaddrinfo ENOTFOUND`

How can I find out the full URL of the request to make sure it is correct?

Code:

```
apiClient.js:
import config from '../../config/config'
import got from 'got'

const apiClient = got.extend({
  prefixUrl: config.baseUrl,
  headers: {
    'X-User-Agent': 'ApiClient ' + config.version,
    Accept: 'application/json',
    'Content-Type': 'application/json'
  },
  hooks: {
    beforeRequest: [
      async options => {
        // WORKS
        console.log('beforeRequest hook called')
      }
    ]
  }
})

export {
  apiClient
}
```

```
apiCalls.js:
import { apiClient } from './apiClient'
import config from '../../config/config'

const version = config.version
const datasource = config.datasource

class ApiCalls {

  async getOrder (id, accessToken) {

    const searchParams = new URLSearchParams([['datasource', datasource], ['token', accessToken]])

    try {
      const response = await apiClient(`${version}/orders/${id}`, { searchParams })
     // NO RESPONSE
      console.log(response)
    } catch (error) {
      throw new Error(error)
    }

    
  }
}

export default ApiCalls
```

If I change searchParams to `{ searchParams, useElectronNet: true }`

and

`import { electron } from 'electron'`

I get error:
`"Error: Cannot find module 'electron'"`

#### Checklist

- [x] I have read the documentation.

**Comment by Zyles** [comment]
Tried `10.0.0-alpha.2.2`

Now I get `Uncaught Error: socket hang up`

This works with nodejs http and axios. So not sure what I did wrong here.

**Comment by Zyles** [comment]
Okay so prefixUrl does not seem to work.

Uncommenting it and using a full URL I at least get a Transform response:
```
const response = await apiClient(`https://myapi.com/${version}/orders/${id}/?datasource=${datasource}&token=${accessToken}`)
```

Also seem to have the problem appending parameters as seen in this ticket https://github.com/sindresorhus/got/issues/888

Was hoping to replace axios for the retry and cache functionality but I guess I will wait a bit longer for these bugs to be fixed.

**Comment by szmarczak** [comment]
Please read the documentation before making an issue.

From the [docs](https://github.com/sindresorhus/got/blob/master/readme.md#errors):
> Each error contains an `options` property which are the options Got used to create a request - just to make debugging easier.
