### ISSUE TITLE
timeouts not working

### ISSUE THREAD

**Issue by davalapar** [sindresorhus/got#902]
#### Describe the bug

 - Node.js version: 12.10.0
 - OS & version: Win7 x64

#### Actual behavior

Implementing a simple request timeout is quite hard guys.

The syntax is as simple as "if 7000 milliseconds pass after I created this request, and I don't want it to retry, it should throw an Error", but it doesn't.

```js
// stuck, no timeout
const response = await got(targetURL, { timeout: 7000 });
```

```js
// stuck, no timeout
const response = await got(targetURL, { timeout: 7000, retry: { retries: 0 } });
```

```js
// stuck, no timeout
const response = await got(targetURL, { timeout: 7000, retry: { retries: 0, maxRetryAfter: 0 } });
```

```js
// this one works, is the custom user agent the problem?
// also, should a custom user agent be a problem? it should just timeout anyway right
    const response = await got(target, {
      timeout: 4000,
      retry: { retries: 0 },
      headers: { 'user-agent': null },
    });
```

Shouldn't the got request just throw regardless of the targetURL's value?

#### Expected behavior

It should timeout easily.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
What is your Got version?

**Comment by davalapar** [comment]
Hi mate thanks for response, it's 9.6.0.

**Comment by davalapar** [comment]
Hey man, just also tried it on 10.0.0-alpha.2.2, still getting stuck sometimes.

I also don't think it's a user-agent problem, with or without useragent set to null it still gets stuck

**Comment by szmarczak** [comment]
Runkit example please? I can't confirm nor deny your issue right now. I need something reproducible.

**Comment by davalapar** [comment]
found it weird really, it's just a recursive scraper loop involving the following code:

```js
// inside some async function:
const response = await got(targetURL, { timeout: 7000, retry: { retries: 0 } });
// find links within response body
// put new links in the queue and process the next one from the queue
```

i ended up writing https://github.com/davalapar/request where what i did was create a timeout that aborts the request once it times out, then once response is created i clear that and create a new timeout to destroy the request and response this time once it times out - kinda worked well so far.

**Comment by d1y** [comment]
> What is your Got version?

but, I also encountered this problem, I just want to implement, if timeout, directly throw new Error ()

**Comment by szmarczak** [comment]
Sorry, but without any reproducible code I don't know where to look.
