### ISSUE TITLE
Sending file doesn't work

### ISSUE THREAD

**Issue by artem-a** [sindresorhus/got#903]
#### Describe the bug

 - Node.js version: v10.17.0
 - OS & version: Ubuntu 18.04 x64

Got doesn't send a file through form-data. I send form-data to the Mailgun api and get an error

```
'message' parameter is missing
```
#### Code to reproduce

```js
    const form = new FormData()
    form.append('to', mail.data.to)
    form.append('message', mail.message.createReadStream(), { filename: 'message.txt' })

      const response = await got('/<domain>/messages.mime', {
        headers: form.getHeaders(),
        body: form,
        auth: 'api:xxxxxx'
      })
```
This code work properly with 8.3.0 version, but doesn't work with versions 8.3.2, 9.x

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by davalapar** [comment]
have you tried using `multi-part` instead https://www.npmjs.com/package/multi-part

**Comment by artem-a** [comment]
@davalapar thanks a lot, it works for me.

**Comment by szmarczak** [comment]
You must've done something incorrectly. It works as expected.
