### ISSUE TITLE
How to calculate the response body size

### ISSUE THREAD

**Issue by Huachao** [sindresorhus/got#904]
#### What would you like to discuss?
When I migrate from the `request` package, I found a requirement that I can't be satisfied that I want to calculate the response body size (without `Content-Length` header in response). Previously, I add an event listener to the response object like following
```js
const request = require('request')
  request(
    { method: 'GET'
    , uri: 'http://www.google.com'
    , gzip: true
    }
  , function (error, response, body) {
      // body is the decompressed response body
      console.log('server encoded the data as: ' + (response.headers['content-encoding'] || 'identity'))
      console.log('the decoded data is: ' + body)
    }
  )
  .on('response', function(response) {
    // unmodified http.IncomingMessage object
    response.on('data', function(data) {
      // compressed data as it is received
      console.log('received ' + data.length + ' bytes of compressed data')
    })
  })
```
In the above example, I can get the data length of compressed data.
...

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
You can add a `.on('response')` to Got too.

**Comment by Huachao** [comment]
@sindresorhus thanks 😄

**Comment by Huachao** [comment]
@sindresorhus thanks for your quick reply. Although I can listen to the emitted `response` event, the response here is fully received, unlike the above example, the trunks received in `data` events are compressed data(for gzip content encoding), and in`got` I can only get the uncompressed data trunks.

**Comment by szmarczak** [comment]
The best solution would be to set `options.decompress` to false, and then decompress it in the `afterResponse` hook.

**Comment by rightaway** [comment]
@szmarczak Documentation says the `response` event is type https://nodejs.org/api/http.html#http_class_http_incomingmessage, is it possible to get response size from that?

Could `got` add response size (bytes it actually downloaded, not after decompress) as a property on response? It will be useful to have this information by default.

**Comment by szmarczak** [comment]
`Buffer.byteLength(response.body)`

**Comment by rightaway** [comment]
@szmarczak That doesn't work when responseType was set to json because Buffer.byteLength excepts string, Buffer or ArrayBuffer and throws error when it gets Object.

```js
const gotpromise = got(url)
gotpromise.on("downloadProgress", progressfunction)
const res = await gotpromise
console.log("after", Buffer.byteLength(res.body))
```

Can you show how to get the size of the original response body? I can add a `gotpromise.on("response")` before the `await` line but it's asynchronous so how to get the result of that in console.log?

I need the size regardless of what responseType is, such as text, json or buffer. The true amount of bytes it actually downloaded, not after decompress.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/3-streams.md#rawbody

**Comment by szmarczak** [comment]
Please read the docs :)

**Comment by rightaway** [comment]
@szmarczak Is it safe to modify the response object?

For example setting `res.bodyLength = Buffer.byteLength(res.rawBody)` so that you can pass the response around the application and access the response length anywhere?

**Comment by szmarczak** [comment]
After the promise resolves you can do anything you want with it.

**Comment by rightaway** [comment]
> After the promise resolves you can do anything you want with it.

@szmarczak How about for errors?

Is it safe to modify the error object `e` in `catch(e)` such as adding, removing or changing properties on `e`, `e.response`, `e.request` or `e.options`?

**Comment by szmarczak** [comment]
Same. After you catch it Got doesn't alter it in any way, you can freely modify it.
