### ISSUE TITLE
v10.0.0-alpha.2 dist folder missing

### ISSUE THREAD

**Issue by pke** [sindresorhus/got#905]
#### Describe the bug

 - Node.js version: 12
 - OS & version: Windows 8.1
 - got version: v10.0.0-alpha.2

#### Actual behavior

The latest alpha release from NPM does not come with the dist folder, therefore the lib can not be resolved as per `package.json` `main` entry that points to the `dist` folder

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
I think you missed the `.2` at the end. Make sure you copy-paste the install instruction:

```
npm install got@10.0.0-alpha.2.2
```
