### ISSUE TITLE
Do not treat set-cookie as a special cookie

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#916]
#### Describe the bug

It appears that `set-cookie` is being treated as a special cookie that is parsed into an array when multiple values are present, ie.

#### actual behaviour

given these two responses:

```
< HTTP/1.1 200 OK
< foo: bar1
< foo: baz1
< Date: Sun, 03 Nov 2019 22:30:16 GMT
< Connection: keep-alive
< Content-Length: 0

< HTTP/1.1 200 OK
< set-cookie: foo
< set-cookie: bar
< Date: Sun, 03 Nov 2019 22:32:10 GMT
< Connection: keep-alive
< Content-Length: 0

```

got (^10.0.0-alpha.3.2) parses the first one as:

```js
{
  headers: {foo: 'bar1, baz1'}
}
```

and the second one as:

```js
{
  headers: {'set-cookie': ['foo', 'bar']}
}
```

#### expected

Both cases should return an array of values when the same array is present multiple times.

**Comment by gajus** [comment]
For what it is worth, I have fixed it with this wrapper:

```js
/**
 * @see https://github.com/sindresorhus/got/issues/916
 */
const parseRawHeaders = (rawHeaders) => {
  const headers = {};

  let headerIndex = -1;

  const headerLength = rawHeaders.length;

  let headerName;

  while (headerIndex++ < headerLength) {
    if (headerIndex % 2 === 0) {
      headerName = rawHeaders[headerIndex];

      continue;
    }

    const headerValue = rawHeaders[headerIndex];

    if (headers[headerName] && Array.isArray(headers[headerName])) {
      headers[headerName].push(headerValue);
    } else if (headers[headerName] && !Array.isArray(headers[headerName])) {
      headers[headerName] = [headers[headerName]].concat(headerValue);
    } else {
      headers[headerName] = headerValue;
    }
  }

  return headers;
};

```

**Comment by gajus** [comment]
Not 100% sure how to handle certain cases, e.g. What to do when the same header=value pair was included multiple times.

```
< HTTP/1.1 200 OK
< Date: Sun, 03 Nov 2019 22:32:10 GMT
< Connection: keep-alive
< Connection: keep-alive
< Content-Length: 0

```

**Comment by szmarczak** [comment]
This is not "special cookie". This is the right behavior according to the spec.

**Comment by gajus** [comment]
> This is the right behavior according to the spec.

I thought this might be the case, though I couldn't find the spec for this.

Can you share a link please?

**Comment by szmarczak** [comment]
Node.js docs: https://nodejs.org/api/http.html#http_message_headers

Spec: https://tools.ietf.org/html/rfc2616#section-4.2
