### ISSUE TITLE
Throw an error after receiving X bytes when using streams

### ISSUE THREAD

**Issue by suprMax** [sindresorhus/got#919]
#### What would you like to discuss?
I want to be able to bail if the response body size goes over a certain threshold. I am using this library to request and process data from external urls and not checking this would allow to potentially DoS the service.

The shortest implementation I could come up with was this:

```javascript
const requestDataIfNotTooBig = (url, callback) => {
  const sizeLimit = 1e6;
  const stream = got.stream(url);

  let bufferLength = 0;
  let body = '';
  let response;

  stream.on('data', (chunk) => {
    bufferLength += chunk.length;
    body += chunk.toString();

    if (bufferLength <= sizeLimit) return;

    stream.destroy();
    stream.emit('error', `Response was too large - aborted after ${sizeLimit} bytes.`);
  });

  stream.on('error', callback);

  stream.on('response', (_response) => {
    response = _response;
  });

  stream.on('end', () => {
    const { statusCode, url } = response;

    if (statusCode !== 200) return callback(`Request failed with code ${statusCode}`, null);
    if (!body) return callback('Request got empty body', null);

    callback(null, { statusCode, url, body });
  });
};
```

Is there an easier way to do this? It seems that as soon as I switch into the "stream" mode there is no simple way to get the response and the body unless I capture those myself.
...

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
This is almost identical to #904

> It seems that as soon as I switch into the "stream" mode there is no simple way to get the response and the body unless I capture those myself.

That's right. If the server doesn't specify the `content-length` header there is no real way to get the length of the response but to capture it.

**Comment by szmarczak** [comment]
I'll leave this issue open, although there were at least 3 issues very similar to this. If you have any ideas how to solve this, feel free.

**Comment by suprMax** [comment]
I think if there was an event similar to `response` that would be fired when the stream is drained with both `response` object and collected `body` it would reduce the code drastically.

**Comment by szmarczak** [comment]
I think it should be done via attaching a Transform stream.

**Comment by suprMax** [comment]
you mean have like an extra plugin you can pipe `got` stream to? good idea

**Comment by szmarczak** [comment]
Here's the solution, it is in our docs: https://github.com/sindresorhus/got/blob/master/documentation/advanced-creation.md#limiting-download--upload-size
