### ISSUE TITLE
Generate documentation from types

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#920]
https://github.com/TypeStrong/typedoc

It'd be best to generate Markdown, but it can be JSON too. We can generate Markdown later.

**Comment by sindresorhus** [comment]
I’m not a big fan of Typedoc. The docs UI it creates is not very user friendly and the generator itself is missing support for lots of TS features and it’s quite buggy. There’s unfortunately no other docs generator for TS.

**Comment by szmarczak** [comment]
Is there something that just reads comments? E.g. if we know what we are documenting, what arguments does it take, what's its description, we can generate markdown on our own.

**Comment by szmarczak** [comment]
I mean we could code the look of the docs.

**Comment by sindresorhus** [comment]
I mean, we could still use it in addition to human written notes, but it's not good enough to replace our handwritten docs.

**Comment by szmarczak** [comment]
Since #758 is now fixed, I think we can start looking deeper into this issue.

Deno has pretty nice docs IMO: https://doc.deno.land/https/deno.land/std/http/server.ts

But it has its own `deno doc` generator. `typedoc` is still missing lots of things (131 issues as of 24/09/2020):
- https://github.com/TypeStrong/typedoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug
- https://github.com/TypeStrong/typedoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aenhancement

**Comment by szmarczak** [comment]
Closing as we cannot do anything about this right now. The documentation has been updated and is more clear than Got 11.

**Comment by UltiRequiem** [comment]
😔
