### ISSUE TITLE
When version 10 will be released?

### ISSUE THREAD

**Issue by leodinas-hao** [sindresorhus/got#923]
#### What would you like to discuss?

... Do we have a schedule of release date for v.10? Thank you very much in advance.

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
In a couple of days.

**Comment by leodinas-hao** [comment]
Fabulous! Thanks very much.

**Comment by sindresorhus** [comment]
It's taking a little bit longer than a couple of days, but it's imminent: https://github.com/sindresorhus/got/issues/876#issuecomment-554917473

**Comment by sindresorhus** [comment]
It's out now: https://github.com/sindresorhus/got/releases/tag/v10.0.0
