### ISSUE TITLE
Timeouts don't work when establishing tcp connection

### ISSUE THREAD

**Issue by GeorgeBekh** [sindresorhus/got#926]
#### Describe the bug

 - Node.js version: v12.12.0
 - OS & version: Debian GNU/Linux buster

#### Actual behavior

Request with timeout set to **1ms** actually fails in **10s** with message 
```
TimeoutError: Timeout awaiting 'request' for 1ms
```

#### Expected behavior

Request with timeout set to 1ms fails in 1ms.

#### Code to reproduce

```js
const got = require('got');

got({
    url: 'http://8.8.8.8',
    timeout: {
        lookup: 1,
        connect: 1,
        secureConnect: 1,
        socket: 1,
        response: 1,
        send: 1,
        request: 1
    }
});
```

#### Checklist
 
- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Read the docs please.

**Comment by szmarczak** [comment]
Okay, I'll save you some time `options.retry: 0`

**Comment by GeorgeBekh** [comment]
Thanks, you're right.
Nevertheless it's really unintuitive and frustrating.
Especially because you have to read this line which is in the middle of a param description to really figure out what's wrong

> Delays between retries counts with function 1000 * Math.pow(2, retry) + Math.random() * 100, where retry is attempt number (starts from 1).

**Comment by szmarczak** [comment]
That's why there is a tick called `I have read the documentation`.
If you haven't read it, please don't check it. It won't make your issue less prioritized :wink:

If you have read the documentation in full, there's a big chance that this is a bug.
If you have not, perhaps you missed something (but we still can't be so sure).

It's just a hint for us where to look first - the documentation or the source code.

Sadly, many people make that mistake.

**Comment by GeorgeBekh** [comment]
Well i'd still consider it a bug. A bug of documentation. Because timeout option is essentially useless without the retry option.

As a user of your library when i set **all** timeout options to 1ms I expect the statement to execute withing the sum of those timeouts.
I as a new user really shouldn't have the ability to shoot myself in the leg that simply.
You shouldn't expect developers to know the docs by heart.

Imagine a developer thinking this:
> Well, if i put these timeout options to 500 ms my request will fail in `1000 * Math.pow(2, retry) + Math.random() * 100` ms, since the default value for retry is **definitely** 2 it will fail in about 4 + 0.5 secs (which still doesn't explain how i got 10 secs on my different machine btw)

May be you should consider putting kind of `timeout.allRetries` option, or stating a connection between **timeout** and **retry** option **very clearly** in the docs.

**Comment by szmarczak** [comment]
What you're looking for `got.extend({retry: 0})`

**Comment by GeorgeBekh** [comment]
It's okay as a workaround, but ideally i shouldn't have to think about it every time i start a new project.

It's very uncommon to **imply** retries. Take any http client: curl, fetch, golang's `http.Client`.

```bash
# "Eeeh... what's the default value for retries in curl?"
curl --connect-timeout 1 http://8.8.8.8

# "Guess what? it's 0!"
curl --connect-timeout 1 --retry 2 http://8.8.8.8/

# proceed to work as expected and everyone's happy
```

The ideal solution is to make retry default to `0`.
I understand you have to provide backwards compatibility, but you can at least warn about this unexpected behaviour in docs and fix it in the next major release.

**Comment by szmarczak** [comment]
I disagree. Most of the open source projects (that use Got) use the `retry` functionality.

> warn about this unexpected behaviour in the docs and fix it in the next major release.

[As per the docs:](https://github.com/sindresorhus/got#retry)

![image](https://user-images.githubusercontent.com/36894700/68508464-c4d25c00-026e-11ea-9ded-25c4c6d78234.png)

This is not an unexpected behavior. This is **indeed expected**.

If you want to change this behavior, feel free to open a new issue :smiley:

**Comment by GeorgeBekh** [comment]
I'm not saying that retry functionality is unexpected or shouldn't be used.
I'm neither saying that this functionality is undocumented.
What I'm actually saying that the "retrying by default" behaviour is **unexpected**. 
How can you actually tell that these open source project use this option intentionally and not just by accident? :)  (Which can lead to the real bugs in these projects)

**Comment by GeorgeBekh** [comment]
Just for the sake of it :) 
https://github.com/sindresorhus/got/issues/927
