### ISSUE TITLE
Default retries to 0

### ISSUE THREAD

**Issue by GeorgeBekh** [sindresorhus/got#927]
#### What problem are you trying to solve?

Got's users can easily produce a bug while working with timeouts. I've definitely did and spent the first hour of my `got` experience troubleshooting.

Consider this possible scenario:
```js
const got = require("got");

// app is an express app
app.get("/get-stuff-quickly", async (req, res) => {
  // ...
  // fetch stuff from DB

  let requestId;
  try {
    requestId = await got("http://some-metrics.com/hit", {
      timeout: 50
    });
  } catch (e) {
    // proceed without requestId. Not that important
  }

  // send requestId and stuff in response
  // ...
});
```

As a new user of the `Got` package who read the docs on timeout I expect this minor request to take 50ms **at max**. While in reality in this scenario it can take **up to 4 seconds** to fail! Which will be crucial to the application and will be considered a bug.

That's because there's a `retry` option that defaults to `2`. and the delay between the retries is calculated with this formula 
> 1000 * Math.pow(2, retry) + Math.random() * 100

So the working code would be:
```js
requestId = await got("http://some-metrics.com/hit", {
      timeout: 50,
      retry: 0
    });
```
Which means every time i use timeout (you should always btw :) ) i have to remember to set `retry` to zero. Which is very unintuitive and error-prone.

#### Describe the feature

Make `retry` default to `0` to prevent unnecessary troubleshouting and bugfixing.

I think, that we should learn from the wise

```
# "Eeeh... what's the default value for retries in curl?"
curl --connect-timeout 1 http://8.8.8.8

# "Guess what? it's 0!"
curl --connect-timeout 1 --retry 2 http://8.8.8.8/

# Proceeds to work as expected and everyone's happy
```

#### Checklist

- [x] This time I have read the documentation on `retry` option and made sure this feature doesn't already exist.

**Comment by sindresorhus** [comment]
Retries are useful for most users as networking is inherently unreliable. However, we should definitely make this behavior clearer in the docs.
