### ISSUE TITLE
Use JSON.stringify for POST if Content-Type is 'application/json'

### ISSUE THREAD

**Issue by maxvipon** [sindresorhus/got#93]
Now according to doc:
> If `body` is a plain Object, it will be stringified with [`querystring.stringify`](https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options) and sent as `application/x-www-form-urlencoded`.

But if I need post json data there is no option for this. And I have to use Promise to throw out SyntaxError exception:
```js
Client.prototype.create = function create(resource, options, data) {
    resource = this.makeUrl(resource, options);
    options = this.processHeaders(options);

    options.headers['Content-Type'] = 'application/json';

    try {
        options.body = JSON.stringify(data);
    } catch (ex) {
        return new Promise(function () { throw ex; });
    }

    return got.post(resource, options);
};
```

**Comment by floatdrop** [comment]
@maxvipon `JSON.stringify` does not throw `SyntaxError` - `JSON.parse` does. Do you really need `try...catch` here?

**Comment by maxvipon** [comment]
my bad

**Comment by floatdrop** [comment]
@maxvipon no problems. If you want to guard against `CircularReference`, you can use [json-stringify-safe](https://www.npmjs.com/package/json-stringify-safe).

**Comment by maxvipon** [comment]
thanks
