### ISSUE TITLE
`got` will success when server response timeout.

### ISSUE THREAD

**Issue by heroboy** [sindresorhus/got#933]
#### Describe the bug

 - Node.js version: 12.4.0
 - OS & version:  windows10

#### Actual behavior

`got` success return response and body.

#### Expected behavior

Like `request` lib, raise a timeout error.

#### Code to reproduce

```js
const got = require('got');
const http = require('http')
const request = require('request');
let s = http.createServer((request, resp) =>
{
	//a server not end the response
	resp.write('aaaaa');
});
s.listen(9988);
s.unref();
async function test001()
{
	let resp = await got('http://127.0.0.1:9988', { timeout: 1000 });
	console.log('get resp', resp.body);//output: get resp aaaaa
        //compare with the request lib.
	request('http://127.0.0.1:9988', { timeout: 1000 }, (err, resp, body) =>
	{
		if (err)
		{
			console.log('error', err); //output: error Error: ESOCKETTIMEDOUT
		}
		else
		{
			console.log('body', body)
		}
	})
}

test001().catch(console.error);
```

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by heroboy** [comment]
```js
let resp = await got('http://127.0.0.1:9988', { timeout: 200, hooks: { beforeRetry: [() => console.log('retry')] } });
```
`retry` will be printed after resp got.

**Comment by heroboy** [comment]
After inspect the code. I guess:
When timeout, you will call `request.abort()`, this will make the response emit 'end' event.
And then in 'as-promise.ts' it successfully await the stream, and resolve the promise.

**Comment by szmarczak** [comment]
It's fixed in the alpha version.
