### ISSUE TITLE
Gzip seems not work in my project

### ISSUE THREAD

**Issue by grapehunter** [sindresorhus/got#945]
#### What would you like to discuss?
Enviroment: 
Running in render process with Electron 7 (But not use Electron.net.)

Code: 
`got('http://www.example.com', { decompress: true }).then(r => console.log(r.body));`

Result:
![image](https://user-images.githubusercontent.com/3354458/69620507-73044100-1078-11ea-9d5e-d8b023e145ce.png)

It looks like the gzip data is not being decoded correctly

#### Checklist

- [x] I have read the documentation.
- [x] I have removed node_modules and reinstalled all dependencies by `yarn install`.
- [x] I have removed .yarnclean and reinstalled all dependencies by `yarn install`.

**Comment by szmarczak** [comment]
What Got version are you running?

**Comment by grapehunter** [comment]
> What Got version are you running?

The latest release version with `yarn install got`, I think it is 9.6.0

**Comment by grapehunter** [comment]
Is it possible that the relevant code was cleared by yarn clean?
Here is my .yarnclean
```
# test directories
__tests__
test
tests
powered-test

# asset directories
docs
doc
website
images
assets

# examples
example
examples

# code coverage directories
coverage
.nyc_output

# build scripts
Makefile
Gulpfile.js
Gruntfile.js

# configs
appveyor.yml
circle.yml
codeship-services.yml
codeship-steps.yml
wercker.yml
.tern-project
.gitattributes
.editorconfig
.*ignore
.eslintrc
.jshintrc
.flowconfig
.documentup.json
.yarn-metadata.json
.travis.yml

# misc
# *.md
*.gz
```

**Comment by grapehunter** [comment]
I have found out the reason.
In get-response.js
```
const decompressResponse = require('decompress-response');
```
decompressResponse is not a function but a empty object. I don't know why so far

**Comment by szmarczak** [comment]
Glad you've solved the issue! PR welcome :)

**Comment by szmarczak** [comment]
It used to work some while ago. Now electron support is broken.

**Comment by adityapk00** [comment]
Was this fixed? It seems to be broken with electron, and fails with the same error.

**Comment by szmarczak** [comment]
Electron support has been deprecated, as the `electron.net`API differs very much from the Node js `http` API.

**Comment by ci010** [comment]
> I have found out the reason.
> In get-response.js
> 
> ```
> const decompressResponse = require('decompress-response');
> ```
> 
> decompressResponse is not a function but a empty object.
> decompress-response was disabled in package.json
> 
> ```
> "browser": {
> 		"decompress-response": false,
> 		"electron": false
> 	}
> }
> ```
> 
> After removing `"decompress-response": false,`, all is working now

Notice that the `package.json` referring here is from `got`, which means if you want to bundle got with webpack in target `electron-renderer`. You will need to modify the `got` package.json in `node_modules`. I think we should simply remove this field since `got` is a package for node environment, not the browser.
