### ISSUE TITLE
json option no longer work with got.stream.post

### ISSUE THREAD

**Issue by sylvaindumont** [sindresorhus/got#950]
#### Describe the bug

 - Node.js version: 12.13.0
 - OS & version: Ubuntu 19.10

`got.stream.post` no longer works with `json` option since #921 

#### Actual behavior

a `body` is set in [asStream](https://github.com/sindresorhus/got/blob/master/source/as-stream.ts#L28)
the request now have a `body` and a `json` option and throw in [normalizeRequestArguments](https://github.com/sindresorhus/got/blob/master/source/normalize-arguments.ts#L326)

#### Expected behavior

the `json` argument should work with `got.stream.post`, as it did until #921 

#### Code to reproduce

```js
got.stream.post('https://sindresorhus.com',  {json: {}})
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/abdfee258a8a18a9db0f8711250cc2cb6d5fb179/source/as-stream.ts#L22

Should be `options.body || options.json || options form`
