### ISSUE TITLE
https urls get "ECONNREFUSED 127.0.0.1:443" (https-proxy-agent breaks got without even using it)

### ISSUE THREAD

**Issue by xPaw** [sindresorhus/got#951]
#### Describe the bug

 - Node.js version: v12.13.0
 - OS & version: Windows 10 1909
- Got v10

#### Actual behavior

```
(node:17240) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 127.0.0.1:443
at onError (D:\GitHub\thelounge\node_modules\got\dist\source\request-as-event-emitter.js:124:29)
at handleRequest (D:\GitHub\thelounge\node_modules\got\dist\source\request-as-event-emitter.js:153:17)
at processTicksAndRejections (internal/process/task_queues.js:93:5)                                                                                        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)                                     
```

For some reason it's resolving any https url to 127.0.0.1. Even changing the port in the uri still tries to connect to 443. `http` appears to work fine.

got@9.6.0 works fine.

#### Code to reproduce

```js
require("https-proxy-agent");
const got = require("got");

got("https://google.com:1337", { // or just "https://google.com"
	timeout: 5000,
})
	.on("response", (a) => {
		console.log(a);
	})
	.on("error", (e) => {
		console.log(e);
	});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by xPaw** [comment]
Tried the alpha/beta versions.

`10.0.0-alpha.3.2` works, `10.0.0-beta.1` tries to connect to 127.0.0.1.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/got/issues/876#issuecomment-560072618. This is a not a problem with Got. Please open an issue on `https-proxy-agent`.

**Comment by xPaw** [comment]
Please note that I'm not passing `https-proxy-agent` into `got` but it still breaks.

**Comment by szmarczak** [comment]
`https-proxy-agent` overrides `http.request`. Their functions takes only two arguments instead of three. Got uses Node.js 10 API, which is three arguments.

**Comment by dashmug** [comment]
I have the same problem. I'm using `got` in a project using `serverless`.

My app does not use `got` directly but `serverless` uses it. 😢

**Comment by sdomagala** [comment]
Hi @szmarczak,
I don't think this ticket should be closed, every project with serverless is going to break after this release.
For now I've just downgraded to got@9 but it would be great to upgrade.

Cheers

**Comment by liteCarma** [comment]
Which proxy agent will work? I couldn't find it, had to go back to version 9

**Comment by dashmug** [comment]
@sdomagala The problem is caused by something not related to `got`. If the cause is in `serverless`, you should file a bug issue there.

**Comment by sdomagala** [comment]
I wonder why `got` picks up dependencies from other packages, seems like an issue with the package itself to me. I understand that breaking change can be something different in API, dependencies of other packages interfering with this one look like a regression to me.

**Comment by dashmug** [comment]
@sdomagala It's because `node-agent-base` is patching a core NodeJS method. There's nothing `got` could have done to prevent this.

**Comment by sdomagala** [comment]
I assume you're referring to this patch function mentioned couple comments up: https://github.com/TooTallNate/node-agent-base/blob/1aaf316cc3f7e3bad0616d42b483da61416406fd/patch-core.js . You could just check if `patchMarker` is set and use given API accordingly. So, you could fix this regression in `got` repo or report it somewhere else, that's up to you, but there is a way.

**Comment by szmarczak** [comment]
@sdomagala Node.js core is not a dependency. Patching it is not a good idea. @dashmug  is right. There's a way to fix that issue, but it's not Got fault. Got 10 is using the Node.js 10 API (Node 8 is being dropped).

> that's up to you

That's up to **you**, as Got does nothing wrong at this point.

**Comment by sindresorhus** [comment]
This should be fixed now in `node-agent-base` v5: https://github.com/TooTallNate/node-agent-base/releases/tag/5.0.0
