### ISSUE TITLE
Testing with jest and nock times out with new json option

### ISSUE THREAD

**Issue by rkrayovskyy** [sindresorhus/got#952]
#### Describe the bug

 - Node.js version: 10.15.3
 - OS & version: OS X 10.14.6
 - Got version: 10.0.1
 - Jest version: 24.9.0
 - Nock version: 11.7.0

After upgrading Got to 10.0.1 from 9.x and following the breaking changes list to migrate, tests are timing out with the following:
`Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error`

#### Actual behavior
I am testing API with nock mocks.

##### I had the following before the migration:
```js
// v1.js
const restClient = got.extend({
    baseUrl: 'http://my-api.com',
    json: true,
  })

module.exports = async ctx => {
  const {
    request: {
      body: { email },
    },
  } = ctx
  const body = { email }
  return await restClient.post('/v1/users', { body })
}
```

```js
// api-mock.js
const nock = require('nock')
module.exports = url => nock(url)
    .post('/v1/users')
    .delay(1000)
    .reply((uri, { email }) => {
      ...
      return [status, body]
    })
```

```js
// v1.spec.js
...
test(`should pass`, async () => {
      ctx.request.body = { email }
      await createUser()(ctx, next)
      ...
})
```

##### Changes after the migration:
```js
// v1.js
const restClient = got.extend({
    prefixUrl: 'http://my-api.com', // <- 1
    responseType: 'json', // <- 2
  })

module.exports = async ctx => {
  const {
    request: {
      body: { email },
    },
  } = ctx
  const json = { email } // <- 3
  return await restClient.post('/v1/users', { json })
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by rkrayovskyy** [comment]
The moment I submitted this, figured out I also had to remove leading slash to comply with 

> Note: We also made it stricter to reduce ambiguity. The Got url argument now cannot be prefixed with a slash when this option is used.

I guess I got confused that slash still exists in the docs - is that a mistake? Do you want me to put PR up to fix that?

**Comment by szmarczak** [comment]
> I guess I got confused that slash still exists in the docs - is that a mistake? Do you want me to put PR up to fix that?

Yup, it's a mistake. A PR would be amazing :smiley:

Does removing the `/` fix your issue?

**Comment by rkrayovskyy** [comment]
> Does removing the / fix your issue?
yes, it does

Here's the PR: https://github.com/sindresorhus/got/pull/957
