### ISSUE TITLE
TypeScript cannot figure out which Got type to use

### ISSUE THREAD

**Issue by scttcper** [sindresorhus/got#954]
#### What would you like to discuss?

With `@types/got` we could use type `GotOptions` and be able to pass this to `got.get(options)` however with v10 the types are `string | OptionsOfDefaultResponseBody` and `OptionsOfDefaultResponseBody` and its friends are not available to import at the root of the project. I was wondering if this was on purpose.

What i'm looking for and not sure how to do with v10
```ts
const options: GotOptions = {
	url: 'https://example.com',
};
const response = await got(options);
```

Also, this example from the docs isn't working for me and I'm wondering if it should accept a partial? Opened https://github.com/sindresorhus/got/pull/953 with a demo
```ts
got.mergeOptions(got.defaults.options, {
	responseType: 'json',
});
```

#### Checklist

- [x] I have read the documentation.

Really excited about the release of v10 🎉

**Comment by szmarczak** [comment]
> What i'm looking for and not sure how to do with v10

I don't understand the example. The URL is invalid.

**Comment by yovanoc** [comment]
We have this error when we try to do that

![image](https://user-images.githubusercontent.com/7302317/69960126-028e7180-1509-11ea-8bd9-7fa28915259b.png)

The only way I had to manage this is to do an `as const` and don't declare as `GotOptions` like this:

```ts
const options = {
    method,
    cookieJar,
    agent,
    responseType: "json",
    form,
    headers
  } as const;

await got(url, options);
```

**Comment by scttcper** [comment]
> I don't understand the example. The URL is invalid.

Sorry was being too terse. There would be a bunch of properties and a valid url passed to options, there just isn't a good type to import and use.

**Comment by szmarczak** [comment]
```ts
const options: GotOptions = {
	url: 'https://example.com'
};
```

This is correct. The example:

```ts
const response = await got(options);
```

fails because it tries to use

```ts
<T>(url: string | Merge<Options, {isStream: true}>, options?: Merge<Options, {isStream: true}>): ProxyStream<T>;
```

instead of

```ts
<T = string>(url: string | OptionsOfDefaultResponseBody, options?: OptionsOfDefaultResponseBody): CancelableRequest<Response<T>>
```

The Got interface looks like:

```ts
export type OptionsOfDefaultResponseBody = Merge<Options, {isStream?: false; resolveBodyOnly?: false; responseType?: 'default'}>;
type OptionsOfTextResponseBody = Merge<Options, {isStream?: false; resolveBodyOnly?: false; responseType: 'text'}>;
type OptionsOfJSONResponseBody = Merge<Options, {isStream?: false; resolveBodyOnly?: false; responseType: 'json'}>;
type OptionsOfBufferResponseBody = Merge<Options, {isStream?: false; resolveBodyOnly?: false; responseType: 'buffer'}>;
type ResponseBodyOnly = {resolveBodyOnly: true};

interface GotFunctions {
	// `asPromise` usage
	<T = string>(url: string | OptionsOfDefaultResponseBody, options?: OptionsOfDefaultResponseBody): CancelableRequest<Response<T>>;
	(url: string | OptionsOfTextResponseBody, options?: OptionsOfTextResponseBody): CancelableRequest<Response<string>>;
	<T>(url: string | OptionsOfJSONResponseBody, options?: OptionsOfJSONResponseBody): CancelableRequest<Response<T>>;
	(url: string | OptionsOfBufferResponseBody, options?: OptionsOfBufferResponseBody): CancelableRequest<Response<Buffer>>;

	// `resolveBodyOnly` usage
	<T = string>(url: string | Merge<OptionsOfDefaultResponseBody, ResponseBodyOnly>, options?: Merge<OptionsOfDefaultResponseBody, ResponseBodyOnly>): CancelableRequest<T>;
	(url: string | Merge<OptionsOfTextResponseBody, ResponseBodyOnly>, options?: Merge<OptionsOfTextResponseBody, ResponseBodyOnly>): CancelableRequest<string>;
	<T>(url: string | Merge<OptionsOfJSONResponseBody, ResponseBodyOnly>, options?: Merge<OptionsOfJSONResponseBody, ResponseBodyOnly>): CancelableRequest<T>;
	(url: string | Merge<OptionsOfBufferResponseBody, ResponseBodyOnly>, options?: Merge<OptionsOfBufferResponseBody, ResponseBodyOnly>): CancelableRequest<Buffer>;

	// `asStream` usage
	<T>(url: string | Merge<Options, {isStream: true}>, options?: Merge<Options, {isStream: true}>): ProxyStream<T>;
}
```

And if we do:

```ts
type CorrectGotType = <T = string>(url: string | OptionsOfDefaultResponseBody, options?: OptionsOfDefaultResponseBody) => CancelableRequest<Response<T>>;

const typedInstance = instance as CorrectGotType;
await typedInstance(options as GotOptions);
```

it still fails because:

```ts
Argument of type 'GotOptions' is not assignable to parameter of type 'Merge<Merge<RequestOptions, Merge<GotOptions, URLOptions>>, { isStream?: false | undefined; resolveBodyOnly?: false | undefined; responseType?: "default" | undefined; }>'.
  Type 'GotOptions' is not assignable to type '{ isStream?: false | undefined; resolveBodyOnly?: false | undefined; responseType?: "default" | undefined; }'.
    Types of property 'isStream' are incompatible.
      Type 'boolean | undefined' is not assignable to type 'false | undefined'.
        Type 'true' is not assignable to type 'false | undefined'.ts(2345)
```

TS is dumb, because it ignores the fact that we handle `isStream` seperately for `true` and `false`.

**Comment by szmarczak** [comment]
[Playground Link](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoHsDmmA2EDyADmMOiAM7IDeAUMvcuWHGAK7kBcyARuunnBABuGgF8aNUJFiIUGbHmp0GACnTFSFLvNwENZSgDJqTFuy5gorCKICUFqxBENka-VrRZdREgeTGqUzZOZHgccht7ULhwpzEJBAMwZDAvPG00lABeV3VfDx08H01yW2QsgD4lFygINigQZDySgDog9hFRISA)

**Comment by szmarczak** [comment]
`true | false` gives `boolean` but `boolean extends true` gives `false` :thinking_face:

**Comment by szmarczak** [comment]
https://github.com/microsoft/TypeScript/issues/24929#issuecomment-560506225

**Comment by szmarczak** [comment]
It works if it is `type` instead of `interface`:

http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoHsDmmA2EDyADmMOiAM7IDeAUMvcuWHGAK7kBcyARuunnBABuGgF8aNMAE9CKDNjzIAvMgAUq9MVIUu83AS1lKAMmqNmbTsjBRWKUQEplAPmu2ITgD5qNhnWix9IhIjZFMqcxZ2LngccnsnJVdY+K8fTRD-PTxg7XJE115+CEEHEUkZFABRAA9IEAATCAbslBVWsOo6Bhg+LgBybjgofpFRcoQjMGtAvC5a+qaW2ba1DLzdFdyjAq6GZCgINigQZHWjADomKPIx8rAVi970ZWRB4dGJB4UIVSpryxcGx2RxCIA

**Comment by szmarczak** [comment]
I think I have found a workaround:

```ts
interface ToggleOptions {
    status?: boolean;
}

function toggle(options: ToggleOptions): boolean {
	return options.status;
};

type T = {
    (options: ToggleOptions & {
        status: true;
    }): true;
    (options: ToggleOptions & {
        status?: false;
    }): false;
};

interface I extends T {}

const typedToggle = toggle as I;

typedToggle({});
```

we need to make `GotFunctions` be a `type` instead of an `interface`.

**Comment by szmarczak** [comment]
I've found a workaround:

```ts
interface ToggleOptions {
    status?: boolean;
}

const toggle = (options: ToggleOptions): boolean => {
	return options.status || false;
};

interface TypedToggle {
    (options: ToggleOptions & {status: true}): true;
    (options: ToggleOptions & {status?: false}): false;
}

// Works:
// const typedToggle = toggle as TypedToggle;
// Fails:
const typedToggle: TypedToggle = (options: ToggleOptions): boolean => {
	return options.status || false;
}

typedToggle({});
```

we need to define `Got` first and then cast it.

**Comment by szmarczak** [comment]
If we extend `GotFunctions` by

```ts
	// Generic usage
	<T>(url: string | Options, options?: Options): CancelableRequest<T> | ProxyStream<T>;
```

then it would pass but you would have to cast it as `CancelableRequest<Response<string>>` by yourself which is not convenient.

The fix would be to use [`T extends OptionsOfResultA ? A : T extends OptionsOfResult B ? B : ...`](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoHsDmmA2EDyADmMOiAM7IDeAUMvcuWHGAK7kBcyARuunnBABuGgF8aNUJFiIUGbHmp0GAHlTIIAD0ggAJpXm4CxUhQB8ACnQmynNAEou6rTv3UmLdlzBRWEUcgA-Mg+fshc8DjkECIMyAD08WgAFsCU8MBRHMr0ichWNhROWEZEJLbIAGTuzGx2of6OIb4xOQlJBeVFaCV4ZaaU1VQedRFwUY1jE7EMnQPFCsZd5E28-BCCIuI0CLZgIb0QC0bIALz51svHfYUrZ2ZKcVAQbFAgyJcDAHQj7FsiNDAhwsVACcAMh36tnsQna92QkWiQA) as it works as expected.

**Comment by sindresorhus** [comment]
// @pmmmwh

**Comment by ViceIce** [comment]
Workaround:

```ts
type OptionsOfJSONResponseBody = Merge<
    Options,
    {
        isStream?: false;
        resolveBodyOnly?: false;
        responseType: 'json';
    }
>;
await got<ResultType>(url, opts as OptionsOfJSONResponseBody )
```

**Comment by pmmmwh** [comment]
> // @pmmmwh

I am thinking, maybe we should expose some of our internal option types to the outside world? That seems like a good idea to make sure TypeScript infers them correctly. For example, the following works:

```ts
const options: OptionsOfDefaultResponseBody = {
	url: 'https://example.com',
};
const response = await got(options);
```

**Comment by mrhyde** [comment]
@pmmmwh is right about the bigger picture of this issue. Just trying to proxy arguments types to nested function

```typescript
  const queuedGet = (...args: Parameters<GotFunctions>) =>
    queue.add(() => got.get(...args))
```
will fail with error
```
Types of property 'isStream' are incompatible.
  Type 'false | undefined' is not assignable to type 'true'.
```

P.S. I have submitted a PR for exporting `GotFunctions` interface https://github.com/sindresorhus/got/pull/1017

**Comment by novemberborn** [comment]
> TS is dumb, because it ignores the fact that we handle `isStream` seperately for `true` and `false`.

Put differently, the type definitions in Got are so complex they're bumping up against TypeScript's limits.

There's little point railing against TypeScript here. Got's ideal API may just not be expressible. You should consider moving a little closer to what TypeScript can handle.

With my compile errors so far, it seems like providing the URL as a `url` property fixes things.

**Comment by szmarczak** [comment]
> Put differently, the type definitions in Got are so complex they're bumping up against TypeScript's limits.

See [function overloads](https://www.typescriptlang.org/docs/handbook/functions.html#overloads). The same should be possible when using interfaces IMO.

**Comment by lagden** [comment]
go back to the old and good JavaScript...
you are making up problems. IMO.

**Comment by bkhartmire** [comment]
I was coming across this error as well when trying to use got.post and pass in options. 
```
Argument of type 'GotOptions' is not assignable to parameter of type 'Merge<Merge<RequestOptions, Merge<GotOptions, URLOptions>>, { isStream?: false | undefined; resolveBodyOnly?: false | undefined; responseType?: "default" | undefined; }>'.
  Type 'GotOptions' is not assignable to type '{ isStream?: false | undefined; resolveBodyOnly?: false | undefined; responseType?: "default" | undefined; }'.
    Types of property 'isStream' are incompatible.
      Type 'boolean | undefined' is not assignable to type 'false | undefined'.
        Type 'true' is not assignable to type 'false | undefined'.ts(2345)
```

It worked when I used got.extend first.
```
const body = {example: 'hello'}

const api = got.extend({
    prefixUrl: 'example.com',
    responseType: 'json',
});

const res = await api('/endpoint', {method: 'POST', json: body})
```

**Comment by cah-dunn** [comment]
The entire problem is a result of the dynamic return type being inferred from values in the options object. IMO the simplest workaround is to avoid using the `isStream`, `responseType` and `resolveBodyOnly` options altogether.

EX:
`got.get<CustomType>(url, { responseType: 'json' })` => `got.get(url).json<CustomType>()`
`got.get(url, { responseType: 'blob' })` => `got.get(url).blob()`
`got.get(url, { responseType: 'text' })` => `got.get(url).text()`
`got.get(url, { isStream: true })` => `got.stream(url)`

This allows for a base options type that always matches the default overload (i.e. `OptionsOfDefaultResponseBody`).

EX:
`type StrictOptions = Exclude<Options, 'isStream' | 'responseType' | 'resolveBodyOnly'>`

I might even suggest `StrictOptions` be an exported type from `got`.

**Comment by cah-dunn** [comment]
The entire problem is a result of the dynamic return type being inferred from values in the options object. IMO the simplest workaround is to avoid using the `isStream`, `responseType` and `resolveBodyOnly` options altogether.

EX:
`got.get<CustomType>(url, { responseType: 'json' })` => `got.get(url).json<CustomType>()`
`got.get(url, { responseType: 'blob' })` => `got.get(url).blob()`
`got.get(url, { responseType: 'text' })` => `got.get(url).text()`
`got.get(url, { isStream: true })` => `got.stream(url)`

This allows for a base options type that always matches the default overload (i.e. `OptionsOfDefaultResponseBody`).

EX:
`type StrictOptions = Omit<Options, 'isStream' | 'responseType' | 'resolveBodyOnly'>`

I might even suggest `StrictOptions` be an exported type from `got`.

**Comment by resynth1943** [comment]
I'm bumping up against something with the typings, althought it _might_ not be related to this issue. After an update, it no longer seems possible to import `FormOptions` and friends from `got`; This breaks my code.

**Comment by resynth1943** [comment]
Well if we don't, I'll explore other alternatives. This is really weird, as it was working great last time I checked.

Thanks anyway for the package, Sindre. :heart:

**Comment by mrhyde** [comment]
@resynth1943 I'm not sure where you managed to find `FormOptions` but there was no such export unless you are confusing it with `GotOptions`

**Comment by resynth1943** [comment]
Nope. I'm pretty sure it exported something named `FormOptions`. Possibly `GotFormOptions`. Nevertheless, my code was using it, so it most likely exists, unless the setup was invalid.

**Comment by mrhyde** [comment]
You were using `@types/got` which was made for an older version. You need to update your code to v10 or rollback. It has nothing to do with this issue.

**Comment by resynth1943** [comment]
> You were using `@types/got` which was made for an older version. You need to update your code to v10 or rollback. It has nothing to do with this issue.

Well that [package](https://www.npmjs.com/package/@types/got) has a *lot* of weekly downloads. 171,998, to be exact. It's an understandable point of confusion. :stuck_out_tongue:

**Comment by viceice** [comment]
Maybe someone should add a [package removal pr](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) to  for `@types/got`

**Comment by cesarfd** [comment]
Or just mark it as deprecated.

**Comment by viceice** [comment]
That what the link above does, it will remove the types from the repo and pushes a new version to npm with deprecation notice

**Comment by szmarczak** [comment]
> Maybe someone should add a package removal pr to for @types/got

Some people are still using Got 9 so removal is inappropriate

**Comment by viceice** [comment]
the type are still available on npm, they will only be removed from git repo. on npm only a new deprecated version (here major) will be published.

**Comment by rifler** [comment]
maybe we should create two new packages `got-legacy` and `@types/got-legacy` with all history from `got`.
After that changing dependencies will be easy - just replace `require('got')` to `require('got-legacy')` without additional testing.
And after that you can update your project to use got@10

**Comment by scttcper** [comment]
This issue is about v10 stream vs cancellable request response types not 10’s built in types vs 9’s definitely typed package.

**Comment by mattddean** [comment]
Another workaround for those still using Got v10

```ts
const textRequest = got.extend({ responseType: 'text' })
const res = await textRequest.put('https://api.example.com/v1/whatever', {
  json: { some: 'property' },
})
```
