### ISSUE TITLE
Deprecation of path parameter in options in got 10

### ISSUE THREAD

**Issue by darksabrefr** [sindresorhus/got#955]
Hello,
With got 10, the [`path` option parameter is deprecated](https://github.com/sindresorhus/got/blob/master/source/utils/options-to-url.ts#L40) but the got documentation says options can contain ["Any of the https.request options"](https://github.com/sindresorhus/got#options).
[This node doc page](https://nodejs.org/api/http.html#http_http_request_options_callback) documents the `path` option. I have understand that I can use options `pathname` + `searchParams` to achieve the same result but there is, I think, a regression or a documentation issue. `path` can be useful in some cases, so why deprecate it ?

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
It's definitely not a regression. You should use `pathname` instead (or any URL property).

**Comment by szmarczak** [comment]
It's made like that to normalize the URL better. Previously Got was using the legacy Url API, which has been deprecated. We need to normalize the URL so you can take a look at it using hooks and modify it if necessary.

**Comment by szmarczak** [comment]
Since it's popular it's been made backwards-compatible: b3f1ac9c9725459f4ffab9baa20b9459d3495fba
