### ISSUE TITLE
get speed on download progress

### ISSUE THREAD

**Issue by devMagics** [sindresorhus/got#956]
#### What problem are you trying to solve?
get speed on download progress
...

#### Describe the feature
this feature is missing get internet connect speed
...

#### Checklist

- [ ] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
It's not missing, it's just not implemented.

**Comment by szmarczak** [comment]
@sindresorhus Should this be a feature?

**Comment by sindresorhus** [comment]
That’s outside the scope of Got. You could pass the Got stream to a package like https://github.com/fent/node-streamspeed or https://github.com/freeall/progress-stream

**Comment by mistercorea** [comment]
It's pretty dumb way to do it but you can calculate quickly by 
`
checkSpeedInterval = setInterval(() => {
    speed = ((totalTransferred - prev) / 10 ** 6).toFixed(2);
    prev = totalTransferred;
  }, 1000);
`
and make sure you have 
`
totalTransferred = transferred;
`
on downloadProgress event.

**Comment by mistercorea** [comment]
> That’s outside the scope of Got. You could pass the Got stream to a package like https://github.com/fent/node-streamspeed or https://github.com/freeall/progress-stream

How can you pass the stream to those library?
