### ISSUE TITLE
JSON Responses

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#961]
#### Describe the bug

 - Node.js version: 13.3
 - OS & version: MacOS Catalina

I get `GotError: Unexpected token  in JSON at position 0 in ...` when I add `responseType: "json"` .
But this happens 2 times out of 5 .. and If I remove the responseType and log the body, all is good..

PS: right before this error there is this warning every time: `(node:34140) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Please fill out the bug issue template, then I'll reopen.
