### ISSUE TITLE
Package size increased three times with version 10

### ISSUE THREAD

**Issue by Siilwyn** [sindresorhus/got#964]
#### What would you like to discuss?
The package install size has [increased from 300kb to 1.1MB](https://packagephobia.now.sh/result?p=got) all of the sudden with the release of version ten.
There must be possibilities to get this somewhat down I think even though new features were added. :thought_balloon:

**Comment by sindresorhus** [comment]
It’s because we now bundle the TypeScript definitions. If you look at https://bundlephobia.com/result?p=got, the actual code size only increased slightly.

**Comment by Siilwyn** [comment]
Ah that explains a lot, appreciate the reply! Would it be an idea to package this in a separate 'types package'? Or is that a bad idea for other reasons?

**Comment by fspoettel** [comment]
See [TS docs on Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). Bundling typings is preferred for projects written in TS which applies here. It results in less maintenance overhead and _does not_ increase the final size of your bundle when importing `got`.

It also does not matter much from a pure disk space perspective in most cases. TS users would have to install `@types/got` anyway and tools like _Visual Studio Code_ download `@types` packages automatically to offer auto completion features. I hope this answers your question.

**Comment by Siilwyn** [comment]
Alright since this is a "best practice" I'll close this one up!

**Comment by szmarczak** [comment]
The main culprit is this: https://packagephobia.now.sh/result?p=@types/keyv

**Comment by szmarczak** [comment]
I just noticed that all types from DefinitelyTyped have big package size :confused:

**Comment by szmarczak** [comment]
That's because they do this:

```
  "dependencies": {
    "@types/node": "*"
  },
```

`@types/node` weighs 670KB. So, in the comparison table the size is 670KB too much, since when you do TypeScript you have already `@types/node` installed :)
