### ISSUE TITLE
Unhandled promise rejection with "socket hang up" & timeout

### ISSUE THREAD

**Issue by darksabrefr** [sindresorhus/got#965]
On `socket hang up` errors, [timeouts are not cleared](https://github.com/sindresorhus/got/blob/master/source/utils/timed-out.ts#L74).
When the `socket hang up` occurs, it is immediately thrown so the promise returned by got immediately rejects. But as timeouts are not cleared, you will get an unhandled promise rejection after the time set in your timeout.

 - Node.js version: 13.2.0
 - OS & version: Ubuntu 19.10

#### Actual behavior

```
UnhandledPromiseRejectionWarning: GotError: Timeout awaiting 'request' for 1000ms
    at onError (/home/clement/dev/tests/node_modules/got/dist/source/request-as-event-emitter.js:121:29)
    at ClientRequest.<anonymous> (/home/clement/dev/tests/node_modules/got/dist/source/request-as-event-emitter.js:136:21)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at Immediate.timeoutHandler [as _onImmediate] (/home/clement/dev/tests/node_modules/got/dist/source/utils/timed-out.js:58:17)
    at Immediate.timeoutHandler [as _onImmediate] (/home/clement/dev/tests/node_modules/got/dist/source/utils/timed-out.js:58:31)
    at processImmediate (internal/timers.js:441:21)
    at emitUnhandledRejectionWarning (internal/process/promises.js:141:15)
    at processPromiseRejections (internal/process/promises.js:203:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

#### Code to reproduce

You need a `socket hang up` to see the bug. A good manner to have one if to put `socket.destroy();` [here](https://github.com/sindresorhus/got/blob/master/source/utils/timed-out.ts#L108). It's a simulation, but I can generate the same stack trace as my real life application where "true" `socket hang up`s sometimes occur.
```js
'use strict';

const got = require('got');

const gotOptions = {
	timeout: 1000,
	retry: 0
};
got('https://google.com', gotOptions)
	.catch((e) => {
		console.log(e.message)
	});

setTimeout(() => {}, 5000);
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The check was introduced here: https://github.com/sindresorhus/got/commit/35d547975087e174fe3872b6fb8816a454987db5#diff-7ab9a52ac2fccf434c1a34ce48f2883bR87 and it was correct while using the same check in `request-as-event-emitter.ts`, but it has been changed in #908

**Comment by szmarczak** [comment]
I think it's safe to remove it now.

**Comment by darksabrefr** [comment]
Thank you again @szmarczak for your fast fix !

**Comment by xPaw** [comment]
I think it this still happens if you cancel the promise on 10.0.2.

1. Call `promise.cancel()` (for example in downloadProgress)
2. catch `CancelError: Promise was canceled`
3. `then` resolved with first param being `undefined`

And later I'm getting `UnhandledPromiseRejectionWarning: GotError: Timeout awaiting 'request' for 5000ms`

**Comment by xPaw** [comment]
Furthermore, if a request times out after receiving headers (`response` event), it throws GotError timeout, and then I get a unhandled rejection with premature close (I am not canceling the request anywhere myself.

1. `catch GotError: Timeout awaiting 'request' for 1000ms` <- fine
2. `UnhandledPromiseRejectionWarning: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close`

**Comment by szmarczak** [comment]
@xPaw A RunKit example(s) would be best.

**Comment by szmarczak** [comment]
I cannot reproduce: https://runkit.com/szmarczak/5dec2a32477b9a001a784841

**Comment by xPaw** [comment]
This code reproduces:
```
const got = require('got');

process.on('unhandledRejection', console.log);

(async () => {
    const promise = got('https://example.com', {
        timeout: 1000,
        retry: 0,
    }).on('downloadProgress', () => {
        promise.cancel();
    });
    
    try {
        await promise;
    } catch (error) {
        console.log('Caught:', error);
    }
    
    await new Promise(resolve => setTimeout(resolve, 2000));
})();
```

I think `retry: 0` is important for it to happen.

**Comment by szmarczak** [comment]
@xPaw Indeed. Could you open a new issue about this?

**Comment by calvinl** [comment]
> Furthermore, if a request times out after receiving headers (`response` event), it throws GotError timeout, and then I get a unhandled rejection with premature close (I am not canceling the request anywhere myself.
> 
> `catch GotError: Timeout awaiting 'request' for 1000ms` <- fine
> 
> And then,
> 
> ```
> (node:15204) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
>     at IncomingMessage.onclose (internal/streams/end-of-stream.js:61:15)
>     at IncomingMessage.emit (events.js:219:5)
>     at IncomingMessage.origin.emit (D:\GitHub\thelounge\node_modules\@szmarczak\http-timer\dist\index.js:40:20)
>     at TLSSocket.socketCloseListener (_http_client.js:377:11)
>     at TLSSocket.emit (events.js:224:7)
>     at net.js:666:12
>     at TCP.done (_tls_wrap.js:488:7)
> ```

I'm not 100% certain yet, but I think I may be seeing this issue (hopefully it's not something in my code). I have a script that makes 100 requests to various URLs and even though I've wrapped the requests in a try/catch block there are some that slip through with a UnhandledPromiseRejectionWarning error after the timeout. Not sure how to reproduce though, but here's some pseudocode:

```js
const urls = [...];
const processUrl = async url => {
  try {
    const res = await got(url, { ...gotOptions });

    // do something
    return res.body;
  } catch (e) {
    // handle error
  }
}
const results = await Promise.all(urls.map(processUrl));
```

I also tried with 10.0.3 and it still seems to be happening. Maybe I'm doing something wrong here?

**Comment by szmarczak** [comment]
Please include some reproducible code. That's not enough info to solve your issue :/

**Comment by szmarczak** [comment]
What are your options?

**Comment by calvinl** [comment]
@szmarczak I will - just wanted to raise it first since someone else brought it up but the reproducible bit had cancellations in there. I suspect it may be a race condition, but will keep you posted. Thank you!
