### ISSUE TITLE
got@10.0.1 incompatible with proxy-agent@3.1.1

### ISSUE THREAD

**Issue by seiya-git** [sindresorhus/got#968]
#### Describe the bug

 - Node.js version: 12.13.1
 - OS & version: Win 10 x64

#### Actual behavior

got@10.0.1: when you request a page with the `proxy-agent` module in the code, the requests goes to the localhost instead of actual ip.

got@9.6.0: works fine.

#### Expected behavior

Return page without error.

#### Code to reproduce

```js
const a = require('proxy-agent');
const g = require('got');
const u = 'https://google.com/';

g(u).then(x => console.log(x));
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by simontong** [comment]
Having same issue, also `tunnel` is not compatible with `got`.

You closed this issue, I'm guessing you were able to solve it? Care to share?

**Comment by Hamper** [comment]
@simontong  #951

**Comment by ash0080** [comment]
Not mentioned to agent, only request a https protocol url will throw this error

**Comment by Nisthar** [comment]
@ash0080 i am having the same issue. did u find a solution? or does this module doesn't work with https urls?

**Comment by ash0080** [comment]
@Nisthar I haven't tried it recently, before I was back to version 9.6
