### ISSUE TITLE
Is there a way to preprocess options (query string) before normalization?

### ISSUE THREAD

**Issue by pcwiek** [sindresorhus/got#970]
#### How to pre-process options before they undergo normalization?
I wanted to use `qs` to stringify my query object across the board for all calls that use query strings
```typescript
// hypothetically...
import qs from 'qs';
import got from 'got';

const client = got.extend({
    hooks: {
        init: [
            request => {
                if (typeof request.searchParams !== 'object') {
                    return;
                }
                if (request.searchParams instanceof URLSearchParams) {
                    return;
                }
                request.searchParams = qs.stringify(request.searchParams);
            }
        ]
    }
});
```
so I could call the client like the following:
```typescript
await client.get('http://localhost', { searchParams: { foo: 'bar', baz: [1,2,3] } });
```
and it would all be sunshine and rainbows.

Unfortunately it seems that [`hooks.init`](https://github.com/sindresorhus/got#hooksinit) is called before the _plain_ options are normalized, but `searchParams` is not a part of 'plain' options. All other options seems to undergo normalization first, so I get:
```
TypeError: The `searchParams` value '1,2,3' must be a string, number, boolean or null
    at validateSearchParams (/mnt/project/node_modules/got/dist/source/utils/options-to-url.js:6:19)
    at Object.exports.default (/mnt/project/node_modules/got/dist/source/utils/options-to-url.js:54:13)
    at Object.exports.normalizeArguments (/mnt/project/node_modules/got/dist/source/normalize-arguments.js:213:47)
```

Is there a way to make it work without sprinkling `qs.stringify` everywhere? If not, that's fine, I'll add it to all calls that require it, I'd just like to keep it contained if possible.

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
You can't, there's no need too for your use case. Why don't you override `options.url.searchParams` then?

**Comment by pcwiek** [comment]
Huh, I'm honestly not sure how. `URL#searchParams` is marked as a readonly property and `search` should be overwritten instead, and neither of those are actual objects so I'd have to 'break'/extend the typings a little bit.
Another option is to pass it all through in `context`.

I'll have to weigh my options and pick one 😉

**Comment by szmarczak** [comment]
> Huh, I'm honestly not sure how. URL#searchParams is marked as a readonly property

Use `searchParams.append(..)` or/and `searchParams.set(...)`.

> search should be overwritten instead

Sure. You have to `options.url.search = new URLSearchParams(...).toString();` or just `options.url.search = someString;`.

**Comment by pcwiek** [comment]
OK, thanks! That answers my question.

Now I'll have to pick one, streamlined approach.
