### ISSUE TITLE
Cancel/abort a streaming request without throwing an error

### ISSUE THREAD

**Issue by xPaw** [sindresorhus/got#971]
After upgrading to v10 we get error event `ERR_STREAM_PREMATURE_CLOSE` after calling `request.abort()`, which didn't happen in earlier versions. It seems like there no `cancel` function on the stream returned by `got.stream` either.

You can see the code here: https://github.com/thelounge/thelounge/blob/6032bd16a530859fef9140b6b35ca534b17be916/src/plugins/irc-events/link.js#L338-L364

What's the correct approach?

**Comment by szmarczak** [comment]
`got.stream(...).destroy()`

**Comment by xPaw** [comment]
`destroy` also throws premature close.

```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:61:15)
    at IncomingMessage.emit (events.js:210:5)
    at IncomingMessage.origin.emit (D:\GitHub\thelounge\node_modules\@szmarczak\http-timer\dist\index.js:40:20)
    at TLSSocket.socketCloseListener (_http_client.js:364:11)
    at TLSSocket.emit (events.js:215:7)
    at net.js:664:12
    at TCP.done (_tls_wrap.js:483:7) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

**Comment by szmarczak** [comment]
This proves the request is aborted:

https://github.com/sindresorhus/got/blob/b962d08188250a442b093f13009b1e1f3633ec27/test/stream.ts#L264-L271

I'll investigate more tomorrow.

**Comment by szmarczak** [comment]
Also, there's no need to use `got.stream(..)` in your code. You can achieve the same using `got(...).on('downloadProgress', ...)`

**Comment by szmarczak** [comment]
> Downgraded to node 12, and both abort/destroy still throw premature close

What about Node 10!

**Comment by xPaw** [comment]
> You can achieve the same using got(...).on('downloadProgress', ...)

Can we get the request early? For example, we do not download at all for video/audio mime types.

**Comment by szmarczak** [comment]
> .on('request', request) seems to be a stream-only event, or am I wrong?

[It's all in the readme, just read it:](https://github.com/sindresorhus/got#streams-1)

> Note: Progress events, redirect events and request/response events can also be used with promises.

**Comment by xPaw** [comment]
I tried using promises, but it doesn't make it any easier.

If I cancel a request, it throws a CancelError, and I don't see a way of accessing the data it downloaded up until the cancellation.

`gotRequest.then((res) => { console.log("data", res); });` logs `data undefined` after a CancelError catch.

And then after canceling I get `(node:10352) UnhandledPromiseRejectionWarning: GotError: Timeout awaiting 'request' for 5000ms`, which sounds like the timeout timer is not canceled.

**Comment by xPaw** [comment]
I basically solved thelounge's issues by doing the following:
1. Call set a bool isCanceled and call got.stream(...).destroy()
2. In error event, if isCanceled is set, ignore it
3. Listen to `close` instead of `end`
4. On `end` also call destroy (this doesn't throw an error of premature close)

**Comment by xPaw** [comment]
So calling `destroy` won't throw an error now, and I no longer need to keep track of my destroy calls, is that correct?

**Comment by szmarczak** [comment]
It will throw only if you pass an error as an argument: `stream.destroy(error)`.

So to answer your question: yes, that's right.

**Comment by szmarczak** [comment]
Note that this is on the `master` branch. You need to wait for a new release.

**Comment by andrisi** [comment]
@szmarczak you could add a note to the docs under the Stream section to note that it will throw only if you pass an error as an argument to stream.destroy() as you said above. Otherwise works like charm. Thanks!

**Comment by szmarczak** [comment]
@andrisi https://nodejs.org/api/stream.html#stream_writable_destroy_error
