### ISSUE TITLE
RequestError: read ECONNRESET in new version of got

### ISSUE THREAD

**Issue by fengkx** [sindresorhus/got#987]
#### Describe the bug

 - Node.js version: v12.13.0
 - OS & version: Linux

#### Actual behavior
Got throw a ReuestError in request in latest version.
```js
GotError: read ECONNRESET
    at onError (/home/fengkx/project/NodeRSSBot/node_modules/got/dist/source/request-as-event-emitter.js:138:29)
    at handleRequest (/home/fengkx/project/NodeRSSBot/node_modules/got/dist/source/request-as-event-emitter.js:171:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)
```
#### Expected behavior

request success and no throw happen

#### Code to reproduce
This error is thrown when I use got in NodeRSSBot. for example
https://github.com/fengkx/NodeRSSBot/blob/master/middlewares/test-url.js#L17

I am sorry I cannot provide a simple code to reproduce the problem.

I try to extract out the logic to a simple script. But the error just disappear when I do this. But I can reproduce the problem every single time my bot try to make a request in both my laptop and VPS. 

I am pretty sure I have read the release not of version 10 and made the migration to my code. And I try using `const got = require('got')` directly rather than make my instance using `got.extend` too. 

#### Try to narrow down the problem

This problem didn't show up in version `9.6.0`

So I try to narrow down the problem a bit. I installed several versions of got from `9.6.0` to `10.0.3`. And find that the problem start to show up in version `10.0.0-beta.1`

Then I try to compile got commit by commit and find the problem start to show up from 
518f0f5 

But I can't figure out what's going on. Any idea?

full err that I caught: https://paste.ubuntu.com/p/YxBxFpg7Bc/ Hope to help😓

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you try `got@10.0.4`?

**Comment by fengkx** [comment]
I try `got@10.0.4`. it still throw an error.
error.stack is the same.

**Comment by szmarczak** [comment]
Unfortunately I can't help you without the code to reproduce your issue. You may try running Node 13 and Node 10.

**Comment by fengkx** [comment]
running on Node 13. It show the smae error. And I try to mock the this function using jest. error didn't show up....

I also try using the break on expectation feature in debugger. It just stuck and no error throw and no break point is made.

**Comment by szmarczak** [comment]
From the docs:

> Each error contains an options property which are the options Got used to create a request - just to make debugging easier.

So catch the error, `console.log(error.options)` and post the options here - that will definitely help.

**Comment by fengkx** [comment]
I have already paste the full error I caught in ubuntu pastebin above. It is JSON serialized. The `console.log` version below. In fact my code is using the default instance `const got = require('got')` and pass no option `got.get(URL_STRING)`

```js
{
  headers: { 'user-agent': 'got (https://github.com/sindresorhus/got)' },
  prefixUrl: [Getter/Setter],
  hooks: {
    beforeError: [],
    init: [],
    beforeRequest: [],
    beforeRedirect: [],
    beforeRetry: [],
    afterResponse: []
  },
  timeout: {},
  retry: {
    calculateDelay: [Function: calculateDelay],
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429,
      500, 502, 503,
      504
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity
  },
  method: 'GET',
  maxRedirects: 10,
  decompress: true,
  throwHttpErrors: true,
  followRedirect: true,
  isStream: false,
  cache: false,
  dnsCache: false,
  useElectronNet: false,
  responseType: 'text',
  resolveBodyOnly: false,
  methodRewriting: true,
  ignoreInvalidCookies: false,
  url: URL {
    href: 'https://0xffff.one/atom',
    origin: 'https://0xffff.one',
    protocol: 'https:',
    username: '',
    password: '',
    host: '0xffff.one',
    hostname: '0xffff.one',
    port: '',
    pathname: '/atom',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  }
}
```

**Comment by jaulz** [comment]
Same issue here... tried multiple versions and tried to investigate what the actually issue was. Though, finally I rolled back to 10.0.0-alpha.2.2 and now it's working again.

**Comment by szmarczak** [comment]
I wish I could help more. I tried both: `got(options)` and `got(string)` and there are no errors.
Can you try `master` branch with Node **v13.4.0** (this is not the latest one) one more time?

I couldn't find anything that would cause the connection to drop in 518f0f5.

**Comment by jaulz** [comment]
Please try the following in `package.json`:
```json
  "resolutions": {
    "agent-base": "^5.0.0"
  }
```

**Comment by szmarczak** [comment]
I do not use `yarn`.

**Comment by fengkx** [comment]
Try the master branch on Nodev13.4.0 same error.

stack

```js
GotError: read ECONNRESET
    at onError (/home/fengkx/project/NodeRSSBot/node_modules/got/dist/source/request-as-event-emitter.js:136:29)
    at handleRequest (/home/fengkx/project/NodeRSSBot/node_modules/got/dist/source/request-as-event-emitter.js:169:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
```

err.options
```json
{
  "headers": {
    "user-agent": "Mozilla/5.0  NodeRSSBot v0.4.0(https://github.com/fengkx/NodeRSSBot)",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 "
  },
  "prefixUrl": "",
  "hooks": {
    "beforeError": [],
    "init": [],
    "beforeRequest": [],
    "beforeRedirect": [],
    "beforeRetry": [],
    "afterResponse": [
      null
    ]
  },
  "timeout": {
    "response": 40000
  },
  "retry": {
    "limit": 2,
    "methods": [
      "GET",
      "PUT",
      "HEAD",
      "DELETE",
      "OPTIONS",
      "TRACE"
    ],
    "statusCodes": [
      408,
      413,
      429,
      500,
      502,
      503,
      504,
      521,
      522,
      524
    ],
    "errorCodes": [
      "ETIMEDOUT",
      "ECONNRESET",
      "EADDRINUSE",
      "ECONNREFUSED",
      "EPIPE",
      "ENOTFOUND",
      "ENETUNREACH",
      "EAI_AGAIN"
    ],
    "maxRetryAfter": null
  },
  "method": "GET",
  "maxRedirects": 10,
  "decompress": true,
  "throwHttpErrors": true,
  "followRedirect": true,
  "isStream": false,
  "cache": false,
  "dnsCache": false,
  "useElectronNet": false,
  "responseType": "text",
  "resolveBodyOnly": false,
  "methodRewriting": true,
  "ignoreInvalidCookies": false,
  "url": "https://0xffff.one/atom"
}
```

**Comment by szmarczak** [comment]
Unfortunately I cannot help you without any reproducible code...

**Comment by szmarczak** [comment]
Could you set up a reproducible repo? That would definitely help.

**Comment by fengkx** [comment]
If I am able to do this. I have already do it. But every time when I factor out the part of code then the error disappear.

If you don't mind using telegram. Try this docker `docker pull fengkx/node_rssbot:201912120719382547f8`

Or maybe I should just stick with `9.6`...

**Comment by szmarczak** [comment]
Sure, my telegram username is the same as my GitHub one.

**Comment by jaulz** [comment]
Just upgrade agent-base and everything should be fine.

**Comment by fengkx** [comment]
> 
> 
> Just upgrade agent-base and everything should be fine.

I though I have upgrade to the latest version of agent-base until I try this 
```bash
$ npm ls agent-base 
noderssbot@0.4.0 /home/fengkx/project/NodeRSSBot
├─┬ http-proxy-agent@3.0.0
│ └── agent-base@5.0.0 
├─┬ https-proxy-agent@4.0.0
│ └── agent-base@5.1.1 
└─┬ socks-proxy-agent@4.0.2
  └── agent-base@4.2.1 

```

Then I try to remove socks-proxy-agent everything is ok now. Thanks.
I think the issue should be closed now.
