### ISSUE TITLE
promise API throws errors instead of rejecting promise

### ISSUE THREAD

**Issue by dylang** [sindresorhus/got#99]
I believe it's an anti-pattern to synchronously throw errors in promises.

Example:

```
var mightBeFalse = false;
got(mightBeFalse)
    .then(doStuff)
    .catch(handleRejectedPromise); 
```

`got` synchronously `throws`
```
Parameter `url` must be a string or object, not boolean
```

Instead of rejecting the promise which would be handled by `handleRejectedPromises`.

**Comment by floatdrop** [comment]
@dylang yeah, errors in Promise API should be returned as rejected promises. Good catch :+1:

**Comment by dylang** [comment]
Thanks @floatdrop!
