### ISSUE TITLE
Cannot assign `got.mergeOptions(...)` to instance defaults

### ISSUE THREAD

**Issue by cesarfd** [sindresorhus/got#993]
#### What would you like to discuss?

Even if I set `mutableDefaults` as true, (TS 3.7.3, got 10.0.4), TS still complains that `defaults` is a read-only property. The readme example of the `afterResponse` hook doesn't seem to work when using TS.

According to the definition file, `defaults` may or may not be `ReadOnly`.

If I just invoke `client.mergeOptions(client.defaults.options, updatedOptions);` instead of reassigning `client.defaults.options` it seems to work fine but in that case it works even if I don't set `mutableDefaults` as true.

Any ideas or have I just misunderstood how it works?

#### Checklist

- [ x] I have read the documentation.

**Comment by szmarczak** [comment]
What Got version do you use?

https://github.com/sindresorhus/got/blob/d083a5954f2b8db414549fac98fa74856ee286a7/source/create.ts#L59

perhaps it guesses the type wrongly. What happens if you cast it as `Defaults`?

**Comment by cesarfd** [comment]
> 
> 
> What Got version do you use?
> 
> https://github.com/sindresorhus/got/blob/d083a5954f2b8db414549fac98fa74856ee286a7/source/create.ts#L59
> 
> perhaps it guesses the type wrongly. What happens if you cast it as `Defaults`?

I'm using got 10.0.4 with TS 3.7.3.

If I set `defaults` as just `Defaults` instead of `Defaults | Readonly<Defaults>` then it complains because `mergeOptions` returns a `NormalizedOptions` type. Even if I try to recast it as `Defaults` it's not accepted by the compiler.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/d083a5954f2b8db414549fac98fa74856ee286a7/test/create.ts#L135-L159

Our tests use TypeScript, there's proof that it works as expected ^

Please include some reproducible code.

**Comment by cesarfd** [comment]
Yeah, I saw these tests, the difference is that in this case you are not reassigning the entire `options` property like the example in the readme does.

The code is here: https://github.com/sindresorhus/got#hooksafterresponse

This will probably work fine in pure JS but in TS it's not possible to reassign the `options` property.

**Comment by szmarczak** [comment]
Will write a test for that, thanks for reporting :)

**Comment by cesarfd** [comment]
Thanks!
