### ISSUE TITLE
Content-Length is no longer sent

### ISSUE THREAD

**Issue by lpinca** [sindresorhus/got#996]
#### Describe the bug

 - Node.js version: v13.3.0
 - OS & version: macOS 10.15.2

The `Content-Length` header is no longer automatically sent if the `Content-Type` header is specified and set to `application/json`.

#### Code to reproduce

```js
const assert = require('assert');
const { createServer } = require('http');

const got = require('got');

const server = createServer(function(request, response) {
  assert.strictEqual(request.headers['content-length'], '13');
  response.end();
});

server.listen(function() {
  const data = { foo: 'bar' };
  const { port } = this.address();

  got
    .post(`http://localhost:${port}`, {
      headers: { 'Content-Type': 'application/json' },
      // json: true,
      // body: data,
      json: data,
    })
    .catch(console.error)
    .finally(function() {
      server.close();
    });
});
```

This example works as expected in `got@9`.

#### Actual behavior

The header is not sent.

#### Expected behavior

The header is sent.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I have made a typo:

https://github.com/sindresorhus/got/blob/7bf92f459d7da1ab31e7db3821e93882f50d1468/source/normalize-arguments.ts#L38

Instead of `noContentType` it should `is.undefined(headers['content-length'])`. Will fix this tomorrow as it's very late here.
