### ISSUE TITLE
Timeout option is not honored

### ISSUE THREAD

**Issue by lpinca** [sindresorhus/got#997]
#### Describe the bug

 - Node.js version: v13.3.0
 - OS & version: macOS 10.15.2

The timeout option does not work as expected when the TCP connection cannot be established. The test case below works as expected with `got@8` but not with `got@9` or `got@10`.

#### Code to reproduce

```js
const got = require('got');

// 192.0.2.1 is non-routable IP address used to prevent the TCP connection from
// being established. See https://tools.ietf.org/html/rfc5737#section-3
got('http://192.0.2.1/test', { retry: 0, timeout: 500 }).catch(console.error);
```

#### Actual behavior

The promise is rejected after ~10 seconds.

#### Expected behavior

The promise is rejected after 500 milliseconds.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I'll fix this ASAP, thanks for reporting.

**Comment by kibertoad** [comment]
@szmarczak Any chance for fixed version to be released?

**Comment by d1y** [comment]
> I'll fix this ASAP, thanks for reporting.

I also encountered this problem, how do I solve this problem? Thank you very much😐

**Comment by d1y** [comment]
I tried doing this,
```ts
try {
    const res: any = await new Promise(async rcv=> {
      // [bug] https://github.com/sindresorhus/got/issues/997
      got(url, { timeout: fetchSubDataLinkTimeout }).then(r=> {
        rcv(r.body)
      }).catch(err=> rcv(false))
      setTimeout(()=> rcv(false), fetchSubDataLinkTimeout)
    })
    if (!res) throw new Error()
    let body: string = res.body
    const config = ssrUtils.fetchDataToSSR(body)
    if (config) {
      const code = Base64.encode(url)
      ssrUtils.createSubLinkNodeFile(code, config)
      return config
    } else {
      logger.ssr(logLevel.error, allTextMsg.subNodeFail, url)
      return false
    }
    // TODO 发送请求之后, 将此时的更新的时间更新到某个文件中
  } catch (e) {
    console.log('请求失败')
    logger.ssr(logLevel.error, allTextMsg.subNodeFail, url)
    return false
  }
```

**Comment by szmarczak** [comment]
@d1y @kibertoad Just upgrade to `v10.1.0`.
